FrontEndControl2: FEConfig::CartAssemblyID Class Reference
FEConfig::CartAssemblyID Class Reference
#include <CartConfig.h>
Public Member Functions
CartAssemblyID (unsigned port=0, unsigned band=0, unsigned WCAFacility=0, unsigned WCAId=0, unsigned CCAFacility=0, unsigned CCAId=0)
void reset ()
reset all data to defaults.
bool WCAValid () const
bool CCAValid () const
bool isValid () const
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned port_m
what port the cartridge is connected to. Usually same as band_m.
unsigned band_m
the cartridge band.
unsigned WCAFacility_m
the provider portion of the primary key.
unsigned WCAId_m
along with provider, uniquely identifies a record in WCAs table.
unsigned CCAFacility_m
the provider portion of the primary key.
unsigned CCAId_m
along with provider, uniquely identifies a record in ColdCarts table.
Detailed Description
Definition at line 114 of file CartConfig.h.
Constructor & Destructor Documentation
FEConfig::CartAssemblyID::CartAssemblyID (unsigned port = 0, unsigned band = 0, unsigned WCAFacility = 0, unsigned WCAId = 0, unsigned CCAFacility = 0, unsigned CCAId = 0) inline
Definition at line 123 of file CartConfig.h.
Member Function Documentation
bool FEConfig::CartAssemblyID::CCAValid () const inline
Definition at line 144 of file CartConfig.h.
References CCAId_m.
Referenced by FEConfig::ConfigProviderIniFile::getFrontEndConfig(), FEConfig::ConfigProviderMySQL::getFrontEndConfig(), and isValid().
bool FEConfig::CartAssemblyID::isValid () const inline
Definition at line 147 of file CartConfig.h.
References CCAValid(), and WCAValid().
Referenced by FEConfig::ConfigProviderIniFile::getCartAssemblyConfig(), FEConfig::ConfigProviderMySQL::getCartAssemblyConfig(), FEConfig::Configuration::Record::isValid(), and FEConfig::ConfigProviderIniFile::saveCartAssemblyConfig().
void FEConfig::CartAssemblyID::reset () inline
reset all data to defaults.
Definition at line 137 of file CartConfig.h.
Referenced by FEConfig::ConfigProviderIniFile::parseCartRow(), and FEConfig::Configuration::Record::reset().
void FEConfig::CartAssemblyID::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 83 of file CartConfig.cpp.
bool FEConfig::CartAssemblyID::WCAValid () const inline
Definition at line 141 of file CartConfig.h.
References WCAId_m.
Referenced by FEConfig::ConfigProviderIniFile::getFrontEndConfig(), FEConfig::ConfigProviderMySQL::getFrontEndConfig(), and isValid().
Member Data Documentation
unsigned FEConfig::CartAssemblyID::band_m
the cartridge band.
Definition at line 117 of file CartConfig.h.
Referenced by FEConfig::ConfigProviderIniFile::parseCartRow(), CartAssembly::setColdCartConfig(), and CartAssembly::setWCAConfig().
unsigned FEConfig::CartAssemblyID::CCAFacility_m
the provider portion of the primary key.
Definition at line 120 of file CartConfig.h.
Referenced by FEConfig::ConfigProviderIniFile::getCartAssemblyConfig(), FEConfig::ConfigProviderMySQL::getCartAssemblyConfig(), FEConfig::ConfigProviderMySQL::getFrontEndConfig(), FEConfig::ConfigProviderIniFile::getFrontEndConfig(), and FEConfig::ConfigProviderIniFile::parseCartRow().
unsigned FEConfig::CartAssemblyID::CCAId_m
along with provider, uniquely identifies a record in ColdCarts table.
Definition at line 121 of file CartConfig.h.
Referenced by CCAValid(), FEConfig::ConfigProviderMySQL::getCartAssemblyConfig(), FEConfig::ConfigProviderIniFile::getCartAssemblyConfig(), FEConfig::ConfigProviderIniFile::getFrontEndConfig(), FEConfig::ConfigProviderMySQL::getFrontEndConfig(), and FEConfig::ConfigProviderIniFile::parseCartRow().
unsigned FEConfig::CartAssemblyID::port_m
what port the cartridge is connected to. Usually same as band_m.
Definition at line 116 of file CartConfig.h.
Referenced by FEConfig::ConfigManager::configureCartAssembly(), FEConfig::ConfigProviderIniFile::getFrontEndConfig(), and FEConfig::ConfigProviderIniFile::parseCartRow().
unsigned FEConfig::CartAssemblyID::WCAFacility_m
the provider portion of the primary key.
Definition at line 118 of file CartConfig.h.
Referenced by FEConfig::ConfigProviderIniFile::getCartAssemblyConfig(), FEConfig::ConfigProviderMySQL::getCartAssemblyConfig(), FEConfig::ConfigProviderMySQL::getFrontEndConfig(), FEConfig::ConfigProviderIniFile::getFrontEndConfig(), and FEConfig::ConfigProviderIniFile::parseCartRow().
unsigned FEConfig::CartAssemblyID::WCAId_m
along with provider, uniquely identifies a record in WCAs table.
Definition at line 119 of file CartConfig.h.
Referenced by FEConfig::ConfigProviderIniFile::getCartAssemblyConfig(), FEConfig::ConfigProviderMySQL::getCartAssemblyConfig(), FEConfig::ConfigProviderMySQL::getFrontEndConfig(), FEConfig::ConfigProviderIniFile::getFrontEndConfig(), FEConfig::ConfigProviderIniFile::parseCartRow(), and WCAValid().
The documentation for this class was generated from the following files:
CONFIG/CartConfig.h
CONFIG/CartConfig.cpp