FrontEndControl2: MeasureSISCurrent Class Reference
MeasureSISCurrent Class Reference
#include <MeasureSISCurrent.h>
Public Member Functions
MeasureSISCurrent (ColdCartImpl &ColdCart, XYPlotArray &target)
virtual ~MeasureSISCurrent ()
void reset ()
reset all state to initial/just constructed.
bool start (int pol, int sbMixer, float IMagStart, float IMagStop, float IMagStep, float VJLow, float VJHigh, float VJStep, int repeatCount=1)
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
virtual void requestStop ()
main thread can call this to request worker thread to stop.
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
virtual void optimizeAction ()
derived classes must declare an optimizeAction method for the worker thread to call.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
virtual void exitAction (bool success)
derived classes may declare an exitAction which gets called just prior to the thread exiting.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Private Member Functions
void readData (int VJSteps, bool printHeader=false)
Private Attributes
ColdCartImpl & coldCart_m
int pol_m
which polarization to measure: 0 or 1.
int sbMagnet_m
which SIS magnet to sweep: 1 or 2 indicating SIS1/SIS2 or -1 indicating both (or band-specific modes.)
int sbMixer_m
which SIS mixer to measure: 1 or 2 indicating SIS1/SIS2 or -1 indicating both.
float VJ1Nom_m
cached SIS1 voltage to return to after the measurement.
float VJ2Nom_m
cached SIS2 voltage.
float IMag1Nom_m
cached SIS1 magnet current to return to after the measurement.
float IMag2Nom_m
cached SIS2 magnet current.
float IMagStart_m
start of magnet current range to sweep
float IMagStop_m
end of magnet range
float IMagStep_m
magnet current step size
float IMagSet_m
instantaneous magnet current setting in force
float VJLow_m
start of SIS voltage range to sweep
float VJHigh_m
end of SIS range
float VJStep_m
SIS voltage step size.
int repeatCount_m
how many times to repeat the measurement
float progress_m
value between 0 and 100 for the progress bar.
XYPlotArray & data_m
plot data to return
std::ostream * dataFile_mp
output data file
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 31 of file MeasureSISCurrent.h.
Constructor & Destructor Documentation
MeasureSISCurrent::MeasureSISCurrent (ColdCartImpl & ColdCart, XYPlotArray & target) inline
Definition at line 33 of file MeasureSISCurrent.h.
References reset().
virtual MeasureSISCurrent::~MeasureSISCurrent () inline virtual
Definition at line 40 of file MeasureSISCurrent.h.
References dataFile_mp.
Member Function Documentation
void MeasureSISCurrent::optimizeAction () protected virtual
derived classes must declare an optimizeAction method for the worker thread to call.
Implements OptimizeBase.
Definition at line 135 of file MeasureSISCurrent - FEControl DLL 2.3.23beta1 experiment with inner loop of SIS current vs magnet measurement.cpp.
References FEMCEventQueue::EVENT_OPTIMIZE_DONE.
void MeasureSISCurrent::readData (int VJSteps, bool printHeader = false) private
Definition at line 251 of file MeasureSISCurrent - FEControl DLL 2.3.23beta1 experiment with inner loop of SIS current vs magnet measurement.cpp.
void MeasureSISCurrent::reset ()
reset all state to initial/just constructed.
Definition at line 31 of file MeasureSISCurrent - FEControl DLL 2.3.23beta1 experiment with inner loop of SIS current vs magnet measurement.cpp.
Referenced by MeasureSISCurrent().
bool MeasureSISCurrent::start (int pol, int sbMixer, float IMagStart, float IMagStop, float IMagStep, float VJLow, float VJHigh, float VJStep, int repeatCount = 1)
Definition at line 44 of file MeasureSISCurrent - FEControl DLL 2.3.23beta1 experiment with inner loop of SIS current vs magnet measurement.cpp.
References OptimizeBase::startWorkerThread().
Member Data Documentation
ColdCartImpl& MeasureSISCurrent::coldCart_m private
Definition at line 56 of file MeasureSISCurrent.h.
XYPlotArray& MeasureSISCurrent::data_m private
plot data to return
Definition at line 75 of file MeasureSISCurrent.h.
std::ostream* MeasureSISCurrent::dataFile_mp private
output data file
Definition at line 76 of file MeasureSISCurrent.h.
Referenced by ~MeasureSISCurrent().
float MeasureSISCurrent::IMag1Nom_m private
cached SIS1 magnet current to return to after the measurement.
Definition at line 63 of file MeasureSISCurrent.h.
float MeasureSISCurrent::IMag2Nom_m private
cached SIS2 magnet current.
Definition at line 64 of file MeasureSISCurrent.h.
float MeasureSISCurrent::IMagSet_m private
instantaneous magnet current setting in force
Definition at line 68 of file MeasureSISCurrent.h.
float MeasureSISCurrent::IMagStart_m private
start of magnet current range to sweep
Definition at line 65 of file MeasureSISCurrent.h.
float MeasureSISCurrent::IMagStep_m private
magnet current step size
Definition at line 67 of file MeasureSISCurrent.h.
float MeasureSISCurrent::IMagStop_m private
end of magnet range
Definition at line 66 of file MeasureSISCurrent.h.
int MeasureSISCurrent::pol_m private
which polarization to measure: 0 or 1.
Definition at line 58 of file MeasureSISCurrent.h.
float MeasureSISCurrent::progress_m private
value between 0 and 100 for the progress bar.
Definition at line 73 of file MeasureSISCurrent.h.
int MeasureSISCurrent::repeatCount_m private
how many times to repeat the measurement
Definition at line 72 of file MeasureSISCurrent.h.
int MeasureSISCurrent::sbMagnet_m private
which SIS magnet to sweep: 1 or 2 indicating SIS1/SIS2 or -1 indicating both (or band-specific modes.)
Definition at line 59 of file MeasureSISCurrent.h.
int MeasureSISCurrent::sbMixer_m private
which SIS mixer to measure: 1 or 2 indicating SIS1/SIS2 or -1 indicating both.
Definition at line 60 of file MeasureSISCurrent.h.
float MeasureSISCurrent::VJ1Nom_m private
cached SIS1 voltage to return to after the measurement.
Definition at line 61 of file MeasureSISCurrent.h.
float MeasureSISCurrent::VJ2Nom_m private
cached SIS2 voltage.
Definition at line 62 of file MeasureSISCurrent.h.
float MeasureSISCurrent::VJHigh_m private
end of SIS range
Definition at line 70 of file MeasureSISCurrent.h.
float MeasureSISCurrent::VJLow_m private
start of SIS voltage range to sweep
Definition at line 69 of file MeasureSISCurrent.h.
float MeasureSISCurrent::VJStep_m private
SIS voltage step size.
Definition at line 71 of file MeasureSISCurrent.h.
The documentation for this class was generated from the following files:
OPTIMIZE/MeasureSISCurrent.h
OPTIMIZE/MeasureSISCurrent - FEControl DLL 2.3.23beta1 experiment with inner loop of SIS current vs magnet measurement.cpp
OPTIMIZE/MeasureSISCurrent.cpp