FrontEndControl2: LORTMImpl Class Reference
LORTMImpl Class Reference
implementation class for the LORTM module
#include <LORTMImpl.h>
Classes
struct LORTMLasers_t
struct LORTMOther_t
struct LORTMStatus_t
Public Types
enum SystemStates {
STARTUP = 0, INTERLOCK = 1, STANDBY = 2, LOCKING = 3,
OPERATIONAL = 4, MANUAL = 5
}
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Public Member Functions
LORTMImpl (unsigned long channel, unsigned long nodeAddress)
virtual ~LORTMImpl ()
void setFreqRefLaser (double freqGHz)
void getFirmwareInfo (std::string &serialNum, std::string &protocolRev, std::string &firmwareRev)
void getAMBSIInfo (unsigned long &numErrors, unsigned long &numTransactions) const
virtual unsigned short SystemGetStatus ()
void getErrorList (std::string &errorList)
virtual void SystemClearErrors ()
unsigned char getSystemState () const
bool getInterlockStatus () const
bool getPhaselockStatus () const
bool getTuningReady () const
bool getRFInputReady () const
bool PhaseLockTuningInit (short band, double freqLO1, double freqLO2, double freqFLOOG, short sbLock)
bool PhaseLockGetTuning (double *freqLSB, double *freqUSB, double *freqRef1, double *freqRef2, double *freqSlaveLaser, short *factorM) const
bool laserEnable (int laser, bool enable)
bool laserSetFrequency (int laser, double freq)
bool getMonitorLORTMStatus (LORTMStatus_t &target)
bool getMonitorLORTMLasers (LORTMLasers_t &target)
bool getMonitorLORTMOther (LORTMOther_t &target)
Public Member Functions inherited from LORTMImplBase
LORTMImplBase (const std::string &name)
virtual ~LORTMImplBase ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual std::string GetSerialNumber ()
virtual std::string GetProtocolRevision ()
virtual std::string GetFirmwareVersion ()
virtual unsigned long AMBSINumErrors ()
virtual unsigned long AMBSINumTransactions ()
virtual float AmbientTemperature ()
virtual short SystemGetError ()
virtual short SystemGetWarning ()
virtual float LaserBiasMon1 ()
virtual float LaserBiasMon2 ()
virtual float LaserBiasMon3 ()
virtual float LaserBiasMon4 ()
virtual float TempIntegOutMon1 ()
virtual float TempIntegOutMon2 ()
virtual float TempIntegOutMon3 ()
virtual float TempIntegOutMon4 ()
virtual float LaserTempMon1 ()
virtual float LaserTempMon2 ()
virtual float LaserTempMon3 ()
virtual float LaserTempMon4 ()
virtual float LaserTecIMon1 ()
virtual float LaserTecIMon2 ()
virtual float LaserTecIMon3 ()
virtual float LaserTecIMon4 ()
virtual float LaserPowMon1 ()
virtual float LaserPowMon2 ()
virtual float LaserPowMon3 ()
virtual float LaserPowMon4 ()
virtual float PhMixBiasMon1 ()
virtual float PhMixBiasMon2 ()
virtual float PhMixBiasMon3 ()
virtual float PhMixBiasMon4 ()
virtual float LaserSlowCorrMon ()
virtual float RFAGCGainMon ()
virtual float RFPowMon34dB ()
virtual float ExternThermMon ()
virtual float InternThermMon ()
virtual unsigned char LaserGetStatus1 ()
virtual unsigned char LaserGetStatus2 ()
virtual unsigned char LaserGetStatus3 ()
virtual unsigned char LaserGetStatus4 ()
virtual bool LaserISrcEnable (int laser)
virtual unsigned long LaserFrequency (int laser)
virtual float LaserCalibCoeffA (int laser, int coeff)
virtual float LaserCalibCoeffB (int laser, int coeff)
virtual float LaserCalibCoeffC (int laser, int coeff)
virtual unsigned short PhaselockGetStatus ()
virtual unsigned char PhaselockGetSelectedLaser ()
virtual unsigned char PhaselockGetSelectedBand ()
virtual void ResetAMBSI ()
virtual void ResetDevice ()
virtual void SystemManualModeRequest ()
virtual void SystemStandbyModeRequest ()
virtual void SystemLoadAllParameters ()
virtual void SystemSaveAllParameters ()
virtual void PhaseLockTuningInit (unsigned long slaveFreqMHz)
virtual void PhaseLockTuningFinalize ()
virtual void LaserISrcEnable (int laser, bool enable)
virtual void LaserSetFrequency (int laser, unsigned long slaveFreqMHz)
virtual void LaserCalibrationSelect (int laser)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Private Member Functions
double getRef2DivideBy (short band) const
helper to find the reference 2 divide-by value
void resetTuning ()
helper to clear the tuning frequency state.
Private Attributes
double freqFLOOG_m
double freqLSB_m
double freqUSB_m
double freqRef1_m
double freqRef2_m
double freqRefLaser_m
double freqSlaveLaser_m
short sbLock_m
short band_m
short factorM_m
std::string errorList_m
Static Private Attributes
static const double wlRefLaser
reference laser nominal wavelength
static const double c
m/s speed of light in vacuum
Additional Inherited Members
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Public Attributes inherited from LORTMImplBase
float AmbientTemperature_value
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Types inherited from LORTMImplBase
enum MonitorControlOffset {
GET_SERIAL_NUMBER = 0x00000, GET_PROTOCOL_REV_LEVEL = 0x30000, AMBSI_NUM_ERRORS = 0x30001, AMBSI_NUM_TRANSACIONS = 0x30002,
GET_AMBIENT_TEMPERATURE = 0x30003, GET_SW_REV_LEVEL = 0x30004, RESET_AMBSI = 0x31000, RESET_DEVICE = 0x31001,
SYSTEM_MANUAL_MODE_REQUEST = 0x01000, SYSTEM_STANDBY_MODE_REQUEST = 0x01001, SYSTEM_LOAD_ALL_PARAMS = 0X01002, SYSTEM_SAVE_ALL_PARAMS = 0x01003,
SYSTEM_CLEAR_ERRORS = 0x01004, SYSTEM_GET_STATUS = 0x01100, SYSTEM_GET_ERROR = 0x01101, SYSTEM_GET_WARNING = 0x01102,
SYSTEM_GET_INTERLOCK_STATUS = 0x01120, SYSTEM_STARTUP_MODE = 0x01800, SIGNAL_LASER_BIAS_MON1 = 0x01500, SIGNAL_LASER_BIAS_MON2 = 0x01501,
SIGNAL_LASER_BIAS_MON3 = 0x01502, SIGNAL_LASER_BIAS_MON4 = 0x01503, SIGNAL_TEMP_INTEG_OUT_MON1 = 0x01504, SIGNAL_TEMP_INTEG_OUT_MON2 = 0x01505,
SIGNAL_TEMP_INTEG_OUT_MON3 = 0x01506, SIGNAL_TEMP_INTEG_OUT_MON4 = 0x01507, SIGNAL_LASER_TEMP_MON1 = 0x01508, SIGNAL_LASER_TEMP_MON2 = 0x01509,
SIGNAL_LASER_TEMP_MON3 = 0x0150A, SIGNAL_LASER_TEMP_MON4 = 0x0150B, SIGNAL_LASER_TEC_I_MON1 = 0x0150C, SIGNAL_LASER_TEC_I_MON2 = 0x0150D,
SIGNAL_LASER_TEC_I_MON3 = 0x0150E, SIGNAL_LASER_TEC_I_MON4 = 0x0150F, SIGNAL_LASER_POW_MON1 = 0x01510, SIGNAL_LASER_POW_MON2 = 0x01511,
SIGNAL_LASER_POW_MON3 = 0x01512, SIGNAL_LASER_POW_MON4 = 0x01513, SIGNAL_PHMIX_BIAS_MON1 = 0x01514, SIGNAL_PHMIX_BIAS_MON2 = 0x01515,
SIGNAL_PHMIX_BIAS_MON3 = 0x01516, SIGNAL_PHMIX_BIAS_MON4 = 0x01517, SIGNAL_LASER_SLOW_CORR_MON = 0x01518, SIGNAL_RF_AGC_GAIN_MON = 0x01519,
SIGNAL_RF_POW_MON_34DB = 0x0151A, SIGNAL_EXTERN_THERM_MON = 0x0151B, SIGNAL_INTERN_THERM_MON = 0x0151C, SIGNAL_GROUND = 0x0151F,
LASER_GET_STATUS1 = 0x0203C, LASER_GET_STATUS2 = 0x0203D, LASER_GET_STATUS3 = 0x0203E, LASER_GET_STATUS4 = 0x0203F,
LASER_ICRC_BIAS = 0x02000, LASER_TEMP_SETPOINT = 0x02004, LASER_ISRC_ENABLE = 0x02008, LASER_TEMP_CTRL_ENABLE = 0x0200C,
LASER_FREQUENCY = 0x02050, LASER_OPERATING_CURRENT = 0x02070, LASER_POWER_CALIB_COEFF = 0x02074, LASER_CALIBRATION_CURRENT = 0x02100,
LASER_CALIBRATION_COEFF_A = 0x02110, LASER_CALIBRATION_COEFF_B = 0x02120, LASER_CALIBRATION_COEFF_C = 0x02130, PHASELOCK_TUNING_INIT = 0x03000,
PHASELOCK_TUNING_FINALIZE = 0x03001, PHASELOCK_GET_STATUS = 0x03020, PHASELOCK_GET_SELECTED_LASER = 0x03034, PHASELOCK_GET_SELECTED_BAND = 0x03035,
LL_OPTSW_CALIBRATION = 0x06110, LL_OPTSW_BANDSEL = 0x06111, LL_OPTSW_SLAVESEL = 0x06112
}
Protected Member Functions inherited from LORTMImplBase
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Protected Attributes inherited from LORTMImplBase
std::string SerialNumber_value
std::string ProtocolRevision_value
std::string FirmwareVersion_value
unsigned long CANStatus_value
unsigned long AMBSINumErrors_value
unsigned long AMBSINumTransactions_value
int AmbientTemperature_status
unsigned short SystemGetStatus_value
unsigned char systemState
bool systemWarning
bool systemError
bool operationPending
short SystemGetError_value
short SystemGetWarning_value
bool SystemGetInterlockStatus_value
float LaserBiasMon1_value
float LaserBiasMon2_value
float LaserBiasMon3_value
float LaserBiasMon4_value
float TempIntegOutMon1_value
float TempIntegOutMon2_value
float TempIntegOutMon3_value
float TempIntegOutMon4_value
float LaserTempMon1_value
float LaserTempMon2_value
float LaserTempMon3_value
float LaserTempMon4_value
float LaserTecIMon1_value
float LaserTecIMon2_value
float LaserTecIMon3_value
float LaserTecIMon4_value
float LaserPowMon1_value
float LaserPowMon2_value
float LaserPowMon3_value
float LaserPowMon4_value
float PhMixBiasMon1_value
float PhMixBiasMon2_value
float PhMixBiasMon3_value
float PhMixBiasMon4_value
float LaserSlowCorrMon_value
float RFAGCGainMon_value
float RFPowMon34dB_value
float ExternThermMon_value
float InternThermMon_value
unsigned char LaserGetStatus1_value
unsigned char LaserGetStatus2_value
unsigned char LaserGetStatus3_value
unsigned char LaserGetStatus4_value
unsigned short PhaselockGetStatus_value
bool phaselockLocked
bool phaselockTuningReady
bool phaselockRFInputReady
unsigned char PhaselockGetSelectedLaser_value
unsigned char PhaselockGetSelectedBand_value
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
implementation class for the LORTM module
Definition at line 28 of file LORTMImpl.h.
Member Enumeration Documentation
enum LORTMImpl::SystemStates
Enumerator
STARTUP
INTERLOCK
STANDBY
LOCKING
OPERATIONAL
MANUAL
Definition at line 50 of file LORTMImpl.h.
Constructor & Destructor Documentation
LORTMImpl::LORTMImpl (unsigned long channel, unsigned long nodeAddress)
Definition at line 33 of file LORTMImpl.cpp.
References LORTMImplBase::initialize(), and resetTuning().
virtual LORTMImpl::~LORTMImpl () inline virtual
Definition at line 31 of file LORTMImpl.h.
Member Function Documentation
void LORTMImpl::getAMBSIInfo (unsigned long & numErrors, unsigned long & numTransactions) const
Definition at line 51 of file LORTMImpl.cpp.
References LORTMImplBase::AMBSINumErrors_value, and LORTMImplBase::AMBSINumTransactions_value.
void LORTMImpl::getErrorList (std::string & errorList)
Definition at line 68 of file LORTMImpl.cpp.
References errorList_m.
void LORTMImpl::getFirmwareInfo (std::string & serialNum, std::string & protocolRev, std::string & firmwareRev)
Definition at line 42 of file LORTMImpl.cpp.
References LORTMImplBase::GetFirmwareVersion(), LORTMImplBase::GetProtocolRevision(), and LORTMImplBase::GetSerialNumber().
bool LORTMImpl::getInterlockStatus () const inline
Definition at line 62 of file LORTMImpl.h.
References LORTMImplBase::SystemGetInterlockStatus_value.
bool LORTMImpl::getMonitorLORTMLasers (LORTMLasers_t & target)
Definition at line 278 of file LORTMImpl.cpp.
References LORTMImpl::LORTMLasers_t::LaserBiasMon1_value, LORTMImplBase::LaserBiasMon1_value, LORTMImpl::LORTMLasers_t::LaserBiasMon2_value, LORTMImplBase::LaserBiasMon2_value, LORTMImpl::LORTMLasers_t::LaserBiasMon3_value, LORTMImplBase::LaserBiasMon3_value, LORTMImpl::LORTMLasers_t::LaserBiasMon4_value, LORTMImplBase::LaserBiasMon4_value, LORTMImpl::LORTMLasers_t::LaserGetStatus1_value, LORTMImplBase::LaserGetStatus1_value, LORTMImpl::LORTMLasers_t::LaserGetStatus2_value, LORTMImplBase::LaserGetStatus2_value, LORTMImpl::LORTMLasers_t::LaserGetStatus3_value, LORTMImplBase::LaserGetStatus3_value, LORTMImpl::LORTMLasers_t::LaserGetStatus4_value, LORTMImplBase::LaserGetStatus4_value, LORTMImpl::LORTMLasers_t::LaserSlowCorrMon_value, LORTMImplBase::LaserSlowCorrMon_value, LORTMImpl::LORTMLasers_t::LaserTempMon1_value, LORTMImplBase::LaserTempMon1_value, LORTMImpl::LORTMLasers_t::LaserTempMon2_value, LORTMImplBase::LaserTempMon2_value, LORTMImpl::LORTMLasers_t::LaserTempMon3_value, LORTMImplBase::LaserTempMon3_value, LORTMImpl::LORTMLasers_t::LaserTempMon4_value, and LORTMImplBase::LaserTempMon4_value.
bool LORTMImpl::getMonitorLORTMOther (LORTMOther_t & target)
Definition at line 296 of file LORTMImpl.cpp.
References LORTMImpl::LORTMOther_t::ExternThermMon_value, LORTMImplBase::ExternThermMon_value, LORTMImpl::LORTMOther_t::InternThermMon_value, LORTMImplBase::InternThermMon_value, LORTMImpl::LORTMOther_t::LaserPowMon1_value, LORTMImplBase::LaserPowMon1_value, LORTMImpl::LORTMOther_t::LaserPowMon2_value, LORTMImplBase::LaserPowMon2_value, LORTMImpl::LORTMOther_t::LaserPowMon3_value, LORTMImplBase::LaserPowMon3_value, LORTMImpl::LORTMOther_t::LaserPowMon4_value, LORTMImplBase::LaserPowMon4_value, LORTMImpl::LORTMOther_t::LaserTecIMon1_value, LORTMImplBase::LaserTecIMon1_value, LORTMImpl::LORTMOther_t::LaserTecIMon2_value, LORTMImplBase::LaserTecIMon2_value, LORTMImpl::LORTMOther_t::LaserTecIMon3_value, LORTMImplBase::LaserTecIMon3_value, LORTMImpl::LORTMOther_t::LaserTecIMon4_value, LORTMImplBase::LaserTecIMon4_value, LORTMImpl::LORTMOther_t::PhMixBiasMon1_value, LORTMImplBase::PhMixBiasMon1_value, LORTMImpl::LORTMOther_t::PhMixBiasMon2_value, LORTMImplBase::PhMixBiasMon2_value, LORTMImpl::LORTMOther_t::PhMixBiasMon3_value, LORTMImplBase::PhMixBiasMon3_value, LORTMImpl::LORTMOther_t::PhMixBiasMon4_value, LORTMImplBase::PhMixBiasMon4_value, LORTMImpl::LORTMOther_t::RFAGCGainMon_value, LORTMImplBase::RFAGCGainMon_value, LORTMImpl::LORTMOther_t::RFPowMon34dB_value, and LORTMImplBase::RFPowMon34dB_value.
bool LORTMImpl::getMonitorLORTMStatus (LORTMStatus_t & target)
Definition at line 257 of file LORTMImpl.cpp.
References LORTMImpl::LORTMStatus_t::errorCode, LORTMImpl::LORTMStatus_t::interlockStatus, LORTMImpl::LORTMStatus_t::operationPending, LORTMImplBase::operationPending, LORTMImplBase::PhaselockGetSelectedBand_value, LORTMImplBase::PhaselockGetSelectedLaser_value, LORTMImpl::LORTMStatus_t::phaselockLocked, LORTMImplBase::phaselockLocked, LORTMImpl::LORTMStatus_t::phaselockRFInputReady, LORTMImplBase::phaselockRFInputReady, LORTMImpl::LORTMStatus_t::phaselockTuningReady, LORTMImplBase::phaselockTuningReady, LORTMImpl::LORTMStatus_t::selectedBand, LORTMImpl::LORTMStatus_t::selectedLaser, LORTMImpl::LORTMStatus_t::systemError, LORTMImplBase::systemError, LORTMImplBase::SystemGetError_value, LORTMImplBase::SystemGetInterlockStatus_value, LORTMImplBase::SystemGetWarning_value, LORTMImpl::LORTMStatus_t::systemState, LORTMImplBase::systemState, LORTMImpl::LORTMStatus_t::systemWarning, LORTMImplBase::systemWarning, and LORTMImpl::LORTMStatus_t::warningCode.
bool LORTMImpl::getPhaselockStatus () const inline
Definition at line 65 of file LORTMImpl.h.
References LORTMImplBase::phaselockLocked.
double LORTMImpl::getRef2DivideBy (short band) const private
helper to find the reference 2 divide-by value
Definition at line 321 of file LORTMImpl.cpp.
References ColdCartImpl::getMultiplier().
Referenced by PhaseLockTuningInit().
bool LORTMImpl::getRFInputReady () const inline
Definition at line 71 of file LORTMImpl.h.
References LORTMImplBase::phaselockRFInputReady.
unsigned char LORTMImpl::getSystemState () const inline
Definition at line 59 of file LORTMImpl.h.
References LORTMImplBase::systemState.
bool LORTMImpl::getTuningReady () const inline
Definition at line 68 of file LORTMImpl.h.
References LOCKING, OPERATIONAL, LORTMImplBase::phaselockTuningReady, and LORTMImplBase::systemState.
bool LORTMImpl::laserEnable (int laser, bool enable)
Definition at line 240 of file LORTMImpl.cpp.
References LORTMImplBase::LaserISrcEnable().
bool LORTMImpl::laserSetFrequency (int laser, double freq)
Definition at line 248 of file LORTMImpl.cpp.
References LORTMImplBase::LaserSetFrequency().
bool LORTMImpl::PhaseLockGetTuning (double * freqLSB, double * freqUSB, double * freqRef1, double * freqRef2, double * freqSlaveLaser, short * factorM) const
Definition at line 221 of file LORTMImpl.cpp.
References factorM_m, freqLSB_m, freqRef1_m, freqRef2_m, freqSlaveLaser_m, and freqUSB_m.
bool LORTMImpl::PhaseLockTuningInit (short band, double freqLO1, double freqLO2, double freqFLOOG, short sbLock)
Definition at line 79 of file LORTMImpl.cpp.
References band_m, factorM_m, freqFLOOG_m, freqLSB_m, freqRef1_m, freqRef2_m, freqRefLaser_m, freqSlaveLaser_m, freqUSB_m, ColdCartImpl::getMultiplier(), getRef2DivideBy(), LORTMImplBase::PhaseLockTuningInit(), resetTuning(), and sbLock_m.
void LORTMImpl::resetTuning () private
helper to clear the tuning frequency state.
Definition at line 333 of file LORTMImpl.cpp.
References band_m, factorM_m, freqFLOOG_m, freqLSB_m, freqRef1_m, freqRef2_m, freqSlaveLaser_m, and freqUSB_m.
Referenced by LORTMImpl(), and PhaseLockTuningInit().
void LORTMImpl::setFreqRefLaser (double freqGHz) inline
Definition at line 34 of file LORTMImpl.h.
References freqRefLaser_m.
void LORTMImpl::SystemClearErrors () virtual
Reimplemented from LORTMImplBase.
Definition at line 74 of file LORTMImpl.cpp.
References errorList_m, and LORTMImplBase::SystemClearErrors().
unsigned short LORTMImpl::SystemGetStatus () virtual
Reimplemented from LORTMImplBase.
Definition at line 56 of file LORTMImpl.cpp.
References errorList_m, LORTMImplBase::systemError, LORTMImplBase::SystemGetError(), and LORTMImplBase::SystemGetStatus().
Member Data Documentation
short LORTMImpl::band_m private
Definition at line 152 of file LORTMImpl.h.
Referenced by PhaseLockTuningInit(), and resetTuning().
const double LORTMImpl::c static private
m/s speed of light in vacuum
Definition at line 142 of file LORTMImpl.h.
std::string LORTMImpl::errorList_m private
Definition at line 155 of file LORTMImpl.h.
Referenced by getErrorList(), SystemClearErrors(), and SystemGetStatus().
short LORTMImpl::factorM_m private
Definition at line 153 of file LORTMImpl.h.
Referenced by PhaseLockGetTuning(), PhaseLockTuningInit(), and resetTuning().
double LORTMImpl::freqFLOOG_m private
Definition at line 144 of file LORTMImpl.h.
Referenced by PhaseLockTuningInit(), and resetTuning().
double LORTMImpl::freqLSB_m private
Definition at line 145 of file LORTMImpl.h.
Referenced by PhaseLockGetTuning(), PhaseLockTuningInit(), and resetTuning().
double LORTMImpl::freqRef1_m private
Definition at line 147 of file LORTMImpl.h.
Referenced by PhaseLockGetTuning(), PhaseLockTuningInit(), and resetTuning().
double LORTMImpl::freqRef2_m private
Definition at line 148 of file LORTMImpl.h.
Referenced by PhaseLockGetTuning(), PhaseLockTuningInit(), and resetTuning().
double LORTMImpl::freqRefLaser_m private
Definition at line 149 of file LORTMImpl.h.
Referenced by PhaseLockTuningInit(), and setFreqRefLaser().
double LORTMImpl::freqSlaveLaser_m private
Definition at line 150 of file LORTMImpl.h.
Referenced by PhaseLockGetTuning(), PhaseLockTuningInit(), and resetTuning().
double LORTMImpl::freqUSB_m private
Definition at line 146 of file LORTMImpl.h.
Referenced by PhaseLockGetTuning(), PhaseLockTuningInit(), and resetTuning().
short LORTMImpl::sbLock_m private
Definition at line 151 of file LORTMImpl.h.
Referenced by PhaseLockTuningInit().
const double LORTMImpl::wlRefLaser static private
reference laser nominal wavelength
Definition at line 141 of file LORTMImpl.h.
The documentation for this class was generated from the following files:
LORTMImpl.h
LORTMImpl.cpp