FrontEndControl2: CryostatPumping Class Reference
CryostatPumping Class Reference
#include <CryostatPumping.h>
Public Member Functions
CryostatPumping (CryostatImpl &cryo)
virtual ~CryostatPumping ()
void reset ()
reset all state to initial/just constructed.
bool start (float switchTemperature=30, int cycleTimeSec=20, int timeoutSec=172800)
virtual void stop ()
< start the cryostat pumping process
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
virtual void requestStop ()
main thread can call this to request worker thread to stop.
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
virtual void optimizeAction ()
derived classes must declare an optimizeAction method for the worker thread to call.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
virtual void exitAction (bool success)
derived classes may declare an exitAction which gets called just prior to the thread exiting.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Private Attributes
CryostatImpl & Cryostat_m
float switchTemperature_m
int cycleTimeSec_m
int timeoutSec_m
int elapsedSec_m
bool enable_m
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 29 of file CryostatPumping.h.
Constructor & Destructor Documentation
CryostatPumping::CryostatPumping (CryostatImpl & cryo) inline
Definition at line 31 of file CryostatPumping.h.
References reset().
virtual CryostatPumping::~CryostatPumping () inline virtual
Definition at line 36 of file CryostatPumping.h.
Member Function Documentation
void CryostatPumping::optimizeAction () protected virtual
derived classes must declare an optimizeAction method for the worker thread to call.
Implements OptimizeBase.
Definition at line 49 of file CryostatPumping.cpp.
References CryostatImpl::Cryostat_t::cryostatTemperature0_value, CryostatImpl::Cryostat_t::cryostatTemperature5_value, FEMCEventQueue::EVENT_CRYO_PUMP_DONE, and FEMCEventQueue::EVENT_PROGRESS.
void CryostatPumping::reset ()
reset all state to initial/just constructed.
Definition at line 28 of file CryostatPumping.cpp.
Referenced by CryostatPumping().
bool CryostatPumping::start (float switchTemperature = 30, int cycleTimeSec = 20, int timeoutSec = 172800)
Definition at line 34 of file CryostatPumping.cpp.
References OptimizeBase::startWorkerThread().
void CryostatPumping::stop () virtual
< start the cryostat pumping process
stop the cryostat pumping process
Definition at line 45 of file CryostatPumping.cpp.
Member Data Documentation
CryostatImpl& CryostatPumping::Cryostat_m private
Definition at line 55 of file CryostatPumping.h.
int CryostatPumping::cycleTimeSec_m private
Definition at line 58 of file CryostatPumping.h.
int CryostatPumping::elapsedSec_m private
Definition at line 60 of file CryostatPumping.h.
bool CryostatPumping::enable_m private
Definition at line 61 of file CryostatPumping.h.
float CryostatPumping::switchTemperature_m private
Definition at line 57 of file CryostatPumping.h.
int CryostatPumping::timeoutSec_m private
Definition at line 59 of file CryostatPumping.h.
The documentation for this class was generated from the following files:
OPTIMIZE/CryostatPumping.h
OPTIMIZE/CryostatPumping.cpp