FrontEndControl2: WCAImpl Class Reference
WCAImpl Class Reference
#include <WCAImpl.h>
Classes
struct AMC_t
structure for returning AMC monitor data.
struct PA_t
structure for returning power amp monitor data.
struct Photomixer_t
structure for returning photomixer monitor data.
struct PLL_t
structure for returning PLL monitor data.
struct YTO_t
structure for returning YTO monitor data.
Public Member Functions
WCAImpl (unsigned long channel, unsigned long nodeAddress, const std::string &name, int port, int band, const std::string &ESN="")
conststruct with the CAN channel and node for the front end, the name for the cold cart, the location within the front end M&C and power distribution system, the actual cartridge band which may be different than the location, and the ESN
virtual ~WCAImpl ()
int getBand () const
const std::string & getBandText (std::string &toFill) const
void reset ()
set all state data to defaults, as if just constructed.
void queryCartridgeState ()
determine the cartridge state data based on monitor values.
virtual void ytoCoarseTune (unsigned short val)
override the base class YTO coarse tuning control and cache the value.
unsigned short getYTOCoarseTuneSetting () const
get the last set YTO coarse tuning state.
void ytoCoarseTuneWithTrace (unsigned short coarseYIG, const char *traceText=NULL)
Debugging wrapper for setting the YTO coarse tuning.
virtual void pllSidebandLockSelect (bool val)
override the base class sideband lock select control and cache the value.
bool getPLLSidebandLockSelectSetting () const
get the last set sideband lock select state.
virtual void pllNullLoopIntegrator (bool val)
override the base class null integrator control and cache the value.
bool getPLLNullLoopIntegratorSetting () const
get the last set null integrator state.
virtual float pllLockDetectVoltage ()
override base class lock voltage reading, for debugging with defeatNormalLockDetect.
virtual float pllCorrectionVoltage ()
override base class correction voltage reading, for measuring statistics.
void resetPllCorrectionVoltageStats ()
reset accumulating statistics on PLL correction voltage.
bool testPLLCorrectionVoltageStats () const
Test whether the variance of the PLL correction voltage is in range.
bool testPLLUnlockDetect ()
Test unlock detect latch. Returns true if the lock was previously lost.
void clearUnlockDetect ()
Clear the unlock detect latch.
bool testPLLCVInRange (const float &cv) const
Test whether the given PLL correction voltage is not on or near the voltage rails.
bool testPLLPowerLevels ()
Test the Ref and IF power levels for normal in locked state.
bool testPLLLockDetectVoltage ()
Test the lock detect voltage for logical high.
bool testNormalLockDetect ()
Normal lock detection using the lock detect voltage and the IF and reference power levels.
bool bandSupportsAlternateLockMethod () const
True if this band can be used with the alternate lock method.
bool testAlternateLockDetect ()
Alternate lock detection algorithm which ignores lock detect voltage.
bool interrogateLock ()
Interrogate normal and, if appropriate, alternate lock signals.
bool monitorLockForDisplay () const
Return whether the PLL seems locked based on prior state and latest monitor data.
bool searchForLock (int &coarseYIG, int windowSteps, int stepSize)
Perform the LO lock search algorithm.
bool adjustPLL (float targetCorrVoltage)
Step the YTO to achieve the target PLL correction voltage.
virtual void paPol0DrainVoltage (float val)
override the base class PA drain voltage control and cache the value.
virtual void paPol1DrainVoltage (float val)
override the base class PA drain voltage control and cache the value.
virtual void paPol0GateVoltage (float val)
override the base class PA gate voltage control and cache the value.
virtual void paPol1GateVoltage (float val)
override the base class PA gate voltage control and cache the value.
void setPAEnable (bool val)
set the PA enable state.
bool getPAEnableSetting () const
get the PA enable state.
void setPADrainVoltage (int pol, float val)
set the PA drain voltage control for the specified pol.
float getPADrainVoltageSetting (int pol) const
get the PA drain voltage setting for the specified pol.
float getPADrainVoltage (int pol)
monitor the the PA drain voltage.
float getPAGateVoltageSetting (int pol) const
get the PA gate voltage setting for the specified pol.
void setEnableLO (bool enable, bool setAMC=false, bool detune=false)
enable/disable LO output.
bool getEnableLO () const
is the LO output currently disabled?
void setLOPower (int pol, float percent)
set the LO output power level as a percentage of maximum
bool setAMC (float VDE, float VGE)
void getAMCSetting (float &VDE, float &VGE) const
virtual void photomixerEnable (bool val)
set the photomixer enable state.
bool getPhotomixerEnableSetting () const
get the photomixer enable state.
bool getMonitorYTO (YTO_t &target) const
get the YTO monitor data.
bool getMonitorPhotomixer (Photomixer_t &target) const
get the photomixer monitor data.
bool getMonitorPLL (PLL_t &target) const
get the PLL monitor data.
bool getMonitorAMC (AMC_t &target) const
get the AMC monitor data.
bool getMonitorPA (PA_t &target) const
get the power amp monitor data.
void appendThermalLog (std::string &target) const
append thermal information to a logging string
void appendThermalLogHeader (std::string &target) const
append thermal header information to a logging string
Public Member Functions inherited from WCAImplBase
WCAImplBase (const std::string &name, int port)
virtual ~WCAImplBase ()
int getPort () const
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual unsigned short ytoCoarseTune ()
virtual bool photomixerEnable ()
virtual float photomixerVoltage ()
virtual float photomixerCurrent ()
virtual float pllAssemblyTemp ()
virtual float pllYTOHeaterCurrent ()
virtual float pllRefTotalPower ()
virtual float pllIfTotalPower ()
virtual bool pllUnlockDetectLatch ()
virtual bool pllLoopBandwidthSelect ()
virtual bool pllSidebandLockSelect ()
virtual bool pllNullLoopIntegrator ()
virtual float amcGateAVoltage ()
virtual float amcDrainAVoltage ()
virtual float amcDrainACurrent ()
virtual float amcGateBVoltage ()
virtual float amcDrainBVoltage ()
virtual float amcDrainBCurrent ()
virtual unsigned char amcMultiplierDVoltage ()
virtual float amcGateEVoltage ()
virtual float amcDrainEVoltage ()
virtual float amcDrainECurrent ()
virtual float amcMultiplierDCurrent ()
virtual float amcSupplyVoltage5V ()
virtual float paPol0GateVoltage ()
virtual float paPol0DrainVoltage ()
virtual float paPol0DrainCurrent ()
virtual float paPol1GateVoltage ()
virtual float paPol1DrainVoltage ()
virtual float paPol1DrainCurrent ()
virtual float paSupplyVoltage3V ()
virtual float paSupplyVoltage5V ()
virtual void pllClearUnlockDetectLatch ()
virtual void pllLoopBandwidthSelect (bool val)
virtual void amcDrainBVoltage (float val)
virtual void amcMultiplierDVoltage (unsigned char val)
virtual void amcGateEVoltage (float val)
virtual void amcDrainEVoltage (float val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Public Member Functions inherited from ThermalLoggable
ThermalLoggable ()
virtual ~ThermalLoggable ()
Static Public Member Functions
static bool checkPol (int pol)
check whether valid value is provided for pol.
static int getMultiplier (int band)
get the warm multiplier for the given band.
static bool getAltLoopBW (int band)
static void appendThermalLogHeaderImpl (std::string &target)
append thermal header information to a logging string
static void appendThermalLogPlaceholder (std::string &target)
append zero data to the thermal log so that columns will align.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Private Attributes
int band_m
which cartridge band this is.
unsigned short ytoCoarseTune_m
caches the last set course tuning.
int pllSidebandLockSelect_m
caches the last set sideband lock value.
bool pllNullLoopIntegrator_m
caches the last set null integrator value.
bool paEnable_m
is the LO PA enabled?
bool LOEnable_m
is the LO output enabled/disabled via setEnableLO()?
bool photomixerEnable_m
is the photomixer enabled?
float paDrainVoltage_m [2]
caches latest control values set.
float paGateVoltage_m [2]
caches latest control values set.
float amcDrainEVoltage_m
caches latest control value set.
float amcGateEVoltage_m
caches latest control value set.
bool isLockedLO_m
true if the LO is currently locked.
bool alternateLockTest_m
true if the lock was found using the alternate lock test method.
int pllCorrectionVoltage_count
accumulate sample size of PLL CV since last tuning or reset.
float pllCorrectionVoltage_max
accumulate max PLL CV in sample.
float pllCorrectionVoltage_min
accumulate min PLL CV in sample.
Static Private Attributes
static const float maxCVVariation
maximum threshold for PLL Correction Voltage variation when properly locked.
static const float lowCVRange
minimum PLL Correction Voltage considered in-range
static const float highCVRange
maximum PLL CV in-range
static const float lowLockDetectVoltage
minimum Lock Detect Voltage when locked
static const float lowIFTotalPower
minimum IF Total Power Detect Voltage magnitude when locked
static const float lowRefTotalPower
minimum Reference Total Power Detect Voltage magnitude when locked
static const float minSettingPAVD
minumum allowed LO PA drain voltage setting
static const float maxSettingPAVD
maximum allowed LO PA drain voltage setting
static const float minSettingPAVG
minumum allowed LO PA gate voltage setting
static const float maxSettingPAVG
maximum allowed LO PA gate voltage setting
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Types inherited from WCAImplBase
enum MonitorControlOffset {
YTO_COARSE_TUNE = 0x0800, PHOTOMIXER_ENABLE = 0x0810, PHOTOMIXER_VOLTAGE = 0x0814, PHOTOMIXER_CURRENT = 0x0818,
PLL_LOCK_DETECT_VOLTAGE = 0x0820, PLL_CORRECTION_VOLTAGE = 0x0821, PLL_ASSEMBLY_TEMP = 0x0822, PLL_YTO_HEATER_CURRENT = 0x0823,
PLL_REF_TOTAL_POWER = 0x0824, PLL_IF_TOTAL_POWER = 0x0825, PLL_UNLOCK_DETECT_LATCH = 0x0827, PLL_CLEAR_UNLOCK_DETECT_LATCH = 0x0828,
PLL_LOOP_BANDWIDTH_SELECT = 0x0829, PLL_SIDEBAND_LOCK_POL_SELECT = 0x082A, PLL_NULL_LOOP_INTEGRATOR = 0x082B, AMC_GATE_A_VOLTAGE = 0x0830,
AMC_DRAIN_A_VOLTAGE = 0x0831, AMC_DRAIN_A_CURRENT = 0x0832, AMC_GATE_B_VOLTAGE = 0x0833, AMC_DRAIN_B_VOLTAGE = 0x0834,
AMC_DRAIN_B_CURRENT = 0x0835, AMC_MULTIPLIER_D_VOLTAGE = 0x0836, AMC_GATE_E_VOLTAGE = 0x0837, AMC_DRAIN_E_VOLTAGE = 0x0838,
AMC_DRAIN_E_CURRENT = 0x0839, AMC_MULTIPLIER_D_CURRENT = 0x083A, AMC_SUPPLY_VOLTAGE_5V = 0x083B, PA_GATE_VOLTAGE = 0x0840,
PA_DRAIN_VOLTAGE = 0x0841, PA_DRAIN_CURRENT = 0x0842, PA_SUPPLY_VOLTAGE_3V = 0x0848, PA_SUPPLY_VOLTAGE_5V = 0x084C
}
Protected Member Functions inherited from WCAImplBase
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Protected Attributes inherited from WCAImplBase
unsigned short ytoCoarseTune_value
bool photomixerEnable_value
float photomixerVoltage_value
float photomixerCurrent_value
float pllLockDetectVoltage_value
float pllCorrectionVoltage_value
float pllAssemblyTemp_value
float pllYTOHeaterCurrent_value
float pllRefTotalPower_value
float pllIfTotalPower_value
bool pllUnlockDetectLatch_value
bool pllLoopBandwidthSelect_value
bool pllSidebandLockSelect_value
bool pllNullLoopIntegrator_value
float amcGateAVoltage_value
float amcDrainAVoltage_value
float amcDrainACurrent_value
float amcGateBVoltage_value
float amcDrainBVoltage_value
float amcDrainBCurrent_value
unsigned char amcMultiplierDVoltage_value
float amcGateEVoltage_value
float amcDrainEVoltage_value
float amcDrainECurrent_value
float amcMultiplierDCurrent_value
float amcSupplyVoltage5V_value
float paPol0GateVoltage_value
float paPol0DrainVoltage_value
float paPol0DrainCurrent_value
float paPol1GateVoltage_value
float paPol1DrainVoltage_value
float paPol1DrainCurrent_value
float paSupplyVoltage3V_value
float paSupplyVoltage5V_value
int ytoCoarseTune_status
int photomixerEnable_status
int photomixerVoltage_status
int photomixerCurrent_status
int pllLockDetectVoltage_status
int pllCorrectionVoltage_status
int pllAssemblyTemp_status
int pllYTOHeaterCurrent_status
int pllRefTotalPower_status
int pllIfTotalPower_status
int pllUnlockDetectLatch_status
int pllClearUnlockDetectLatch_status
int pllLoopBandwidthSelect_status
int pllSidebandLockSelect_status
int pllNullLoopIntegrator_status
int amcGateAVoltage_status
int amcDrainAVoltage_status
int amcDrainACurrent_status
int amcGateBVoltage_status
int amcDrainBVoltage_status
int amcDrainBCurrent_status
int amcMultiplierDVoltage_status
int amcGateEVoltage_status
int amcDrainEVoltage_status
int amcDrainECurrent_status
int amcMultiplierDCurrent_status
int amcSupplyVoltage5V_status
int paPol0GateVoltage_status
int paPol0DrainVoltage_status
int paPol0DrainCurrent_status
int paPol1GateVoltage_status
int paPol1DrainVoltage_status
int paPol1DrainCurrent_status
int paSupplyVoltage3V_status
int paSupplyVoltage5V_status
AmbRelativeAddr baseRCA
AmbRelativeAddr ytoCoarseTune_RCA
AmbRelativeAddr photomixerEnable_RCA
AmbRelativeAddr photomixerVoltage_RCA
AmbRelativeAddr photomixerCurrent_RCA
AmbRelativeAddr pllLockDetectVoltage_RCA
AmbRelativeAddr pllCorrectionVoltage_RCA
AmbRelativeAddr pllAssemblyTemp_RCA
AmbRelativeAddr pllYTOHeaterCurrent_RCA
AmbRelativeAddr pllRefTotalPower_RCA
AmbRelativeAddr pllIfTotalPower_RCA
AmbRelativeAddr pllUnlockDetectLatch_RCA
AmbRelativeAddr pllClearUnlockDetectLatch_RCA
AmbRelativeAddr pllLoopBandwidthSelect_RCA
AmbRelativeAddr pllSidebandLockSelect_RCA
AmbRelativeAddr pllNullLoopIntegrator_RCA
AmbRelativeAddr amcGateAVoltage_RCA
AmbRelativeAddr amcDrainAVoltage_RCA
AmbRelativeAddr amcDrainACurrent_RCA
AmbRelativeAddr amcGateBVoltage_RCA
AmbRelativeAddr amcDrainBVoltage_RCA
AmbRelativeAddr amcDrainBCurrent_RCA
AmbRelativeAddr amcMultiplierDVoltage_RCA
AmbRelativeAddr amcGateEVoltage_RCA
AmbRelativeAddr amcDrainEVoltage_RCA
AmbRelativeAddr amcDrainECurrent_RCA
AmbRelativeAddr amcMultiplierDCurrent_RCA
AmbRelativeAddr amcSupplyVoltage5V_RCA
AmbRelativeAddr paPol0GateVoltage_RCA
AmbRelativeAddr paPol0DrainVoltage_RCA
AmbRelativeAddr paPol0DrainCurrent_RCA
AmbRelativeAddr paPol1GateVoltage_RCA
AmbRelativeAddr paPol1DrainVoltage_RCA
AmbRelativeAddr paPol1DrainCurrent_RCA
AmbRelativeAddr paSupplyVoltage3V_RCA
AmbRelativeAddr paSupplyVoltage5V_RCA
int port_m
to which FEMC port is this module connected.
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 33 of file WCAImpl.h.
Constructor & Destructor Documentation
WCAImpl::WCAImpl (unsigned long channel, unsigned long nodeAddress, const std::string & name, int port, int band, const std::string & ESN = "")
conststruct with the CAN channel and node for the front end, the name for the cold cart, the location within the front end M&C and power distribution system, the actual cartridge band which may be different than the location, and the ESN
Definition at line 41 of file WCAImpl.cpp.
References WCAImplBase::initialize(), reset(), and FEHardwareDevice::setESN().
virtual WCAImpl::~WCAImpl () inline virtual
Definition at line 46 of file WCAImpl.h.
Member Function Documentation
bool WCAImpl::adjustPLL (float targetCorrVoltage)
Step the YTO to achieve the target PLL correction voltage.
Definition at line 342 of file WCAImpl.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, clearUnlockDetect(), interrogateLock(), pllCorrectionVoltage(), WCAImplBase::ytoCoarseTune(), and ytoCoarseTuneWithTrace().
void WCAImpl::appendThermalLog (std::string & target) const virtual
append thermal information to a logging string
Implements ThermalLoggable.
Definition at line 618 of file WCAImpl.cpp.
References WCAImplBase::pllAssemblyTemp_value.
void WCAImpl::appendThermalLogHeader (std::string & target) const inline virtual
append thermal header information to a logging string
Implements ThermalLoggable.
Definition at line 344 of file WCAImpl.h.
References appendThermalLogHeaderImpl().
void WCAImpl::appendThermalLogHeaderImpl (std::string & target) static
append thermal header information to a logging string
Definition at line 614 of file WCAImpl.cpp.
Referenced by appendThermalLogHeader(), and CartAssembly::appendThermalLogHeaderImpl().
void WCAImpl::appendThermalLogPlaceholder (std::string & target) static
append zero data to the thermal log so that columns will align.
Definition at line 624 of file WCAImpl.cpp.
Referenced by CartAssembly::appendThermalLog().
bool WCAImpl::bandSupportsAlternateLockMethod () const inline
True if this band can be used with the alternate lock method.
Definition at line 126 of file WCAImpl.h.
References band_m.
Referenced by pllLockDetectVoltage(), and searchForLock().
static bool WCAImpl::checkPol (int pol) inline static
check whether valid value is provided for pol.
Definition at line 231 of file WCAImpl.h.
Referenced by getPADrainVoltageSetting(), and getPAGateVoltageSetting().
void WCAImpl::clearUnlockDetect ()
Clear the unlock detect latch.
Definition at line 165 of file WCAImpl.cpp.
References WCAImplBase::pllClearUnlockDetectLatch().
Referenced by adjustPLL(), searchForLock(), and setEnableLO().
static bool WCAImpl::getAltLoopBW (int band) inline static
Definition at line 251 of file WCAImpl.h.
Referenced by CartAssembly::setLOFrequency().
void WCAImpl::getAMCSetting (float & VDE, float & VGE) const inline
Definition at line 212 of file WCAImpl.h.
References amcDrainEVoltage_m, and amcGateEVoltage_m.
int WCAImpl::getBand () const inline
Definition at line 49 of file WCAImpl.h.
References band_m.
Referenced by CartridgesContainer::addCartridge().
const std::string & WCAImpl::getBandText (std::string & toFill) const
Definition at line 55 of file WCAImpl.cpp.
References band_m.
bool WCAImpl::getEnableLO () const inline
is the LO output currently disabled?
Definition at line 200 of file WCAImpl.h.
References LOEnable_m.
bool WCAImpl::getMonitorAMC (AMC_t & target) const
get the AMC monitor data.
Definition at line 581 of file WCAImpl.cpp.
References WCAImplBase::amcDrainACurrent_value, WCAImpl::AMC_t::amcDrainACurrent_value, WCAImplBase::amcDrainAVoltage_value, WCAImpl::AMC_t::amcDrainAVoltage_value, WCAImplBase::amcDrainBCurrent_value, WCAImpl::AMC_t::amcDrainBCurrent_value, WCAImplBase::amcDrainBVoltage_value, WCAImpl::AMC_t::amcDrainBVoltage_value, WCAImplBase::amcDrainECurrent_value, WCAImpl::AMC_t::amcDrainECurrent_value, WCAImplBase::amcDrainEVoltage_value, WCAImpl::AMC_t::amcDrainEVoltage_value, WCAImplBase::amcGateAVoltage_value, WCAImpl::AMC_t::amcGateAVoltage_value, WCAImplBase::amcGateBVoltage_value, WCAImpl::AMC_t::amcGateBVoltage_value, WCAImplBase::amcGateEVoltage_value, WCAImpl::AMC_t::amcGateEVoltage_value, WCAImplBase::amcMultiplierDCurrent_value, WCAImpl::AMC_t::amcMultiplierDCurrent_value, WCAImplBase::amcMultiplierDVoltage_value, WCAImpl::AMC_t::amcMultiplierDVoltage_value, WCAImplBase::amcSupplyVoltage5V_value, and WCAImpl::AMC_t::amcSupplyVoltage5V_value.
bool WCAImpl::getMonitorPA (PA_t & target) const
get the power amp monitor data.
Definition at line 598 of file WCAImpl.cpp.
References WCAImplBase::paPol0DrainCurrent_value, WCAImpl::PA_t::paPol0DrainCurrent_value, WCAImplBase::paPol0DrainVoltage_value, WCAImpl::PA_t::paPol0DrainVoltage_value, WCAImplBase::paPol0GateVoltage_value, WCAImpl::PA_t::paPol0GateVoltage_value, WCAImplBase::paPol1DrainCurrent_value, WCAImpl::PA_t::paPol1DrainCurrent_value, WCAImplBase::paPol1DrainVoltage_value, WCAImpl::PA_t::paPol1DrainVoltage_value, WCAImplBase::paPol1GateVoltage_value, WCAImpl::PA_t::paPol1GateVoltage_value, WCAImplBase::paSupplyVoltage3V_value, WCAImpl::PA_t::paSupplyVoltage3V_value, WCAImplBase::paSupplyVoltage5V_value, and WCAImpl::PA_t::paSupplyVoltage5V_value.
bool WCAImpl::getMonitorPhotomixer (Photomixer_t & target) const
get the photomixer monitor data.
Definition at line 543 of file WCAImpl.cpp.
References WCAImplBase::photomixerCurrent_value, WCAImpl::Photomixer_t::photomixerCurrent_value, WCAImplBase::photomixerEnable_value, WCAImpl::Photomixer_t::photomixerEnable_value, WCAImplBase::photomixerVoltage_value, and WCAImpl::Photomixer_t::photomixerVoltage_value.
bool WCAImpl::getMonitorPLL (PLL_t & target) const
get the PLL monitor data.
Definition at line 551 of file WCAImpl.cpp.
References FEHardwareDevice::minimalMonitoring_m, monitorLockForDisplay(), WCAImplBase::pllAssemblyTemp_value, WCAImpl::PLL_t::pllAssemblyTemp_value, pllCorrectionVoltage(), WCAImplBase::pllCorrectionVoltage_value, WCAImpl::PLL_t::pllCorrectionVoltage_value, WCAImplBase::pllIfTotalPower(), WCAImplBase::pllIfTotalPower_value, WCAImpl::PLL_t::pllIfTotalPower_value, WCAImpl::PLL_t::pllLock_value, pllLockDetectVoltage(), WCAImplBase::pllLockDetectVoltage_value, WCAImpl::PLL_t::pllLockDetectVoltage_value, WCAImplBase::pllLoopBandwidthSelect_value, WCAImpl::PLL_t::pllLoopBandwidthSelect_value, WCAImplBase::pllNullLoopIntegrator_value, WCAImpl::PLL_t::pllNullLoopIntegrator_value, WCAImplBase::pllRefTotalPower(), WCAImplBase::pllRefTotalPower_value, WCAImpl::PLL_t::pllRefTotalPower_value, WCAImplBase::pllSidebandLockSelect_value, WCAImpl::PLL_t::pllSidebandLockSelect_value, WCAImplBase::pllUnlockDetectLatch(), WCAImplBase::pllUnlockDetectLatch_value, WCAImpl::PLL_t::pllUnlockDetectLatch_value, WCAImplBase::pllYTOHeaterCurrent_value, and WCAImpl::PLL_t::pllYTOHeaterCurrent_value.
bool WCAImpl::getMonitorYTO (YTO_t & target) const
get the YTO monitor data.
Definition at line 537 of file WCAImpl.cpp.
References WCAImplBase::ytoCoarseTune_value, and WCAImpl::YTO_t::ytoCoarseTune_value.
static int WCAImpl::getMultiplier (int band) inline static
get the warm multiplier for the given band.
Definition at line 235 of file WCAImpl.h.
Referenced by CartAssembly::queryCartridgeState(), and CartAssembly::setLOFrequency().
float WCAImpl::getPADrainVoltage (int pol) inline
monitor the the PA drain voltage.
Definition at line 182 of file WCAImpl.h.
References WCAImplBase::paPol0DrainVoltage(), and WCAImplBase::paPol1DrainVoltage().
float WCAImpl::getPADrainVoltageSetting (int pol) const inline
get the PA drain voltage setting for the specified pol.
Definition at line 177 of file WCAImpl.h.
References checkPol(), and paDrainVoltage_m.
bool WCAImpl::getPAEnableSetting () const inline
get the PA enable state.
Definition at line 168 of file WCAImpl.h.
References paEnable_m.
float WCAImpl::getPAGateVoltageSetting (int pol) const inline
get the PA gate voltage setting for the specified pol.
Definition at line 188 of file WCAImpl.h.
References checkPol(), and paGateVoltage_m.
bool WCAImpl::getPhotomixerEnableSetting () const inline
get the photomixer enable state.
Definition at line 224 of file WCAImpl.h.
References photomixerEnable_m.
bool WCAImpl::getPLLNullLoopIntegratorSetting () const inline
get the last set null integrator state.
Definition at line 88 of file WCAImpl.h.
References pllNullLoopIntegrator_m.
bool WCAImpl::getPLLSidebandLockSelectSetting () const inline
get the last set sideband lock select state.
Definition at line 81 of file WCAImpl.h.
References pllSidebandLockSelect_m.
unsigned short WCAImpl::getYTOCoarseTuneSetting () const inline
get the last set YTO coarse tuning state.
Definition at line 71 of file WCAImpl.h.
References ytoCoarseTune_m.
Referenced by testAlternateLockDetect().
bool WCAImpl::interrogateLock ()
Interrogate normal and, if appropriate, alternate lock signals.
Definition at line 234 of file WCAImpl.cpp.
References alternateLockTest_m, pllCorrectionVoltage(), pllNullLoopIntegrator_m, testNormalLockDetect(), testPLLCorrectionVoltageStats(), testPLLCVInRange(), and testPLLPowerLevels().
Referenced by adjustPLL().
bool WCAImpl::monitorLockForDisplay () const
Return whether the PLL seems locked based on prior state and latest monitor data.
Definition at line 244 of file WCAImpl.cpp.
References alternateLockTest_m, lowIFTotalPower, lowLockDetectVoltage, lowRefTotalPower, pllCorrectionVoltage_count, pllCorrectionVoltage_max, pllCorrectionVoltage_min, WCAImplBase::pllCorrectionVoltage_value, WCAImplBase::pllIfTotalPower_value, WCAImplBase::pllLockDetectVoltage_value, WCAImplBase::pllNullLoopIntegrator_value, WCAImplBase::pllRefTotalPower_value, testPLLCorrectionVoltageStats(), and testPLLCVInRange().
Referenced by getMonitorPLL().
void WCAImpl::paPol0DrainVoltage (float val) virtual
override the base class PA drain voltage control and cache the value.
Reimplemented from WCAImplBase.
Definition at line 408 of file WCAImpl.cpp.
References FEMCEventQueue::addStatusMessage(), maxSettingPAVD, paDrainVoltage_m, and WCAImplBase::paPol0DrainVoltage().
void WCAImpl::paPol0GateVoltage (float val) virtual
override the base class PA gate voltage control and cache the value.
Reimplemented from WCAImplBase.
Definition at line 430 of file WCAImpl.cpp.
References FEMCEventQueue::addStatusMessage(), maxSettingPAVG, paGateVoltage_m, and WCAImplBase::paPol0GateVoltage().
void WCAImpl::paPol1DrainVoltage (float val) virtual
override the base class PA drain voltage control and cache the value.
Reimplemented from WCAImplBase.
Definition at line 419 of file WCAImpl.cpp.
References FEMCEventQueue::addStatusMessage(), maxSettingPAVD, paDrainVoltage_m, and WCAImplBase::paPol1DrainVoltage().
void WCAImpl::paPol1GateVoltage (float val) virtual
override the base class PA gate voltage control and cache the value.
Reimplemented from WCAImplBase.
Definition at line 441 of file WCAImpl.cpp.
References FEMCEventQueue::addStatusMessage(), maxSettingPAVG, paGateVoltage_m, and WCAImplBase::paPol1GateVoltage().
void WCAImpl::photomixerEnable (bool val) virtual
set the photomixer enable state.
Reimplemented from WCAImplBase.
Definition at line 528 of file WCAImpl.cpp.
References band_m, WCAImplBase::photomixerEnable(), photomixerEnable_m, and WCAImplBase::port_m.
float WCAImpl::pllCorrectionVoltage () virtual
override base class correction voltage reading, for measuring statistics.
Reimplemented from WCAImplBase.
Definition at line 141 of file WCAImpl.cpp.
References WCAImplBase::pllCorrectionVoltage(), pllCorrectionVoltage_count, pllCorrectionVoltage_max, and pllCorrectionVoltage_min.
Referenced by adjustPLL(), getMonitorPLL(), interrogateLock(), and testAlternateLockDetect().
float WCAImpl::pllLockDetectVoltage () virtual
override base class lock voltage reading, for debugging with defeatNormalLockDetect.
Reimplemented from WCAImplBase.
Definition at line 133 of file WCAImpl.cpp.
References bandSupportsAlternateLockMethod(), FrontEndLVWrapper::defeatNormalLockDetect, and WCAImplBase::pllLockDetectVoltage().
Referenced by getMonitorPLL(), and testPLLLockDetectVoltage().
void WCAImpl::pllNullLoopIntegrator (bool val) virtual
override the base class null integrator control and cache the value.
Reimplemented from WCAImplBase.
Definition at line 118 of file WCAImpl.cpp.
References WCAImplBase::pllNullLoopIntegrator(), and pllNullLoopIntegrator_m.
void WCAImpl::pllSidebandLockSelect (bool val) virtual
override the base class sideband lock select control and cache the value.
Reimplemented from WCAImplBase.
Definition at line 113 of file WCAImpl.cpp.
References WCAImplBase::pllSidebandLockSelect(), and pllSidebandLockSelect_m.
void WCAImpl::queryCartridgeState ()
determine the cartridge state data based on monitor values.
Definition at line 75 of file WCAImpl.cpp.
References alternateLockTest_m, band_m, isLockedLO_m, paDrainVoltage_m, paEnable_m, paGateVoltage_m, WCAImplBase::paPol0DrainVoltage_RCA, WCAImplBase::paPol0GateVoltage_RCA, WCAImplBase::paPol1DrainVoltage_RCA, WCAImplBase::paPol1GateVoltage_RCA, WCAImplBase::photomixerEnable(), photomixerEnable_m, WCAImplBase::pllNullLoopIntegrator(), pllNullLoopIntegrator_m, WCAImplBase::pllSidebandLockSelect(), pllSidebandLockSelect_m, WCAImplBase::port_m, FEHardwareDevice::syncMonitorWithRetry(), testNormalLockDetect(), WCAImplBase::ytoCoarseTune(), and ytoCoarseTune_m.
void WCAImpl::reset ()
set all state data to defaults, as if just constructed.
Definition at line 61 of file WCAImpl.cpp.
References alternateLockTest_m, amcDrainEVoltage_m, amcGateEVoltage_m, isLockedLO_m, LOEnable_m, paDrainVoltage_m, paEnable_m, paGateVoltage_m, photomixerEnable_m, pllNullLoopIntegrator_m, pllSidebandLockSelect_m, resetPllCorrectionVoltageStats(), and ytoCoarseTune_m.
Referenced by WCAImpl().
void WCAImpl::resetPllCorrectionVoltageStats ()
reset accumulating statistics on PLL correction voltage.
Definition at line 151 of file WCAImpl.cpp.
References pllCorrectionVoltage_count, pllCorrectionVoltage_max, and pllCorrectionVoltage_min.
Referenced by reset(), and ytoCoarseTune().
bool WCAImpl::searchForLock (int & coarseYIG, int windowSteps, int stepSize)
Perform the LO lock search algorithm.
Definition at line 275 of file WCAImpl.cpp.
References alternateLockTest_m, bandSupportsAlternateLockMethod(), clearUnlockDetect(), isLockedLO_m, WCAImplBase::pllNullLoopIntegrator(), testAlternateLockDetect(), testPLLLockDetectVoltage(), FrontEndLVWrapper::tryAlternateLockMethod, and ytoCoarseTuneWithTrace().
bool WCAImpl::setAMC (float VDE, float VGE)
Definition at line 512 of file WCAImpl.cpp.
References WCAImplBase::amcDrainEVoltage(), amcDrainEVoltage_m, WCAImplBase::amcGateEVoltage(), amcGateEVoltage_m, band_m, and WCAImplBase::port_m.
Referenced by setEnableLO().
void WCAImpl::setEnableLO (bool enable, bool setAMC = false, bool detune = false)
enable/disable LO output.
when disabled: sets the LO PA drain voltage to zero. if 'detune' is true, tunes the LO output to the far end of the band. if 'setAMC' is true, sets the AMC drain voltage to zero.
Definition at line 464 of file WCAImpl.cpp.
References amcDrainEVoltage_m, amcGateEVoltage_m, band_m, clearUnlockDetect(), LOEnable_m, paDrainVoltage_m, paEnable_m, WCAImplBase::paPol0DrainVoltage(), WCAImplBase::paPol1DrainVoltage(), WCAImplBase::pllNullLoopIntegrator(), pllNullLoopIntegrator_m, setAMC(), WCAImplBase::ytoCoarseTune(), and ytoCoarseTune_m.
void WCAImpl::setLOPower (int pol, float percent)
set the LO output power level as a percentage of maximum
Definition at line 498 of file WCAImpl.cpp.
References WCAImplBase::paPol0DrainVoltage(), and WCAImplBase::paPol1DrainVoltage().
void WCAImpl::setPADrainVoltage (int pol, float val) inline
set the PA drain voltage control for the specified pol.
Definition at line 172 of file WCAImpl.h.
References WCAImplBase::paPol0DrainVoltage(), and WCAImplBase::paPol1DrainVoltage().
void WCAImpl::setPAEnable (bool val)
set the PA enable state.
Definition at line 452 of file WCAImpl.cpp.
References band_m, paEnable_m, WCAImplBase::paPol0DrainVoltage(), WCAImplBase::paPol0GateVoltage(), WCAImplBase::paPol1DrainVoltage(), WCAImplBase::paPol1GateVoltage(), and WCAImplBase::port_m.
bool WCAImpl::testAlternateLockDetect ()
Alternate lock detection algorithm which ignores lock detect voltage.
Definition at line 186 of file WCAImpl.cpp.
References getYTOCoarseTuneSetting(), pllCorrectionVoltage(), pllCorrectionVoltage_count, pllCorrectionVoltage_max, pllCorrectionVoltage_min, testPLLCorrectionVoltageStats(), testPLLCVInRange(), testPLLPowerLevels(), and WCAImplBase::ytoCoarseTune().
Referenced by searchForLock().
bool WCAImpl::testNormalLockDetect ()
Normal lock detection using the lock detect voltage and the IF and reference power levels.
Definition at line 182 of file WCAImpl.cpp.
References testPLLLockDetectVoltage(), and testPLLPowerLevels().
Referenced by interrogateLock(), and queryCartridgeState().
bool WCAImpl::testPLLCorrectionVoltageStats () const
Test whether the variance of the PLL correction voltage is in range.
Used as a double-check on the alternateLockDetect method.
Definition at line 157 of file WCAImpl.cpp.
References maxCVVariation, pllCorrectionVoltage_max, and pllCorrectionVoltage_min.
Referenced by interrogateLock(), monitorLockForDisplay(), and testAlternateLockDetect().
bool WCAImpl::testPLLCVInRange (const float & cv) const
Test whether the given PLL correction voltage is not on or near the voltage rails.
Definition at line 169 of file WCAImpl.cpp.
References highCVRange, and lowCVRange.
Referenced by interrogateLock(), monitorLockForDisplay(), and testAlternateLockDetect().
bool WCAImpl::testPLLLockDetectVoltage ()
Test the lock detect voltage for logical high.
Definition at line 178 of file WCAImpl.cpp.
References lowLockDetectVoltage, and pllLockDetectVoltage().
Referenced by searchForLock(), and testNormalLockDetect().
bool WCAImpl::testPLLPowerLevels ()
Test the Ref and IF power levels for normal in locked state.
Definition at line 173 of file WCAImpl.cpp.
References lowIFTotalPower, lowRefTotalPower, WCAImplBase::pllIfTotalPower(), and WCAImplBase::pllRefTotalPower().
Referenced by interrogateLock(), testAlternateLockDetect(), and testNormalLockDetect().
bool WCAImpl::testPLLUnlockDetect ()
Test unlock detect latch. Returns true if the lock was previously lost.
Definition at line 161 of file WCAImpl.cpp.
References WCAImplBase::pllUnlockDetectLatch().
void WCAImpl::ytoCoarseTune (unsigned short val) virtual
override the base class YTO coarse tuning control and cache the value.
Reimplemented from WCAImplBase.
Definition at line 102 of file WCAImpl.cpp.
References resetPllCorrectionVoltageStats(), WCAImplBase::ytoCoarseTune(), and ytoCoarseTune_m.
void WCAImpl::ytoCoarseTuneWithTrace (unsigned short coarseYIG, const char * traceText = NULL)
Debugging wrapper for setting the YTO coarse tuning.
Definition at line 108 of file WCAImpl.cpp.
References WCAImplBase::ytoCoarseTune().
Referenced by adjustPLL(), and searchForLock().
Member Data Documentation
bool WCAImpl::alternateLockTest_m private
true if the lock was found using the alternate lock test method.
Definition at line 367 of file WCAImpl.h.
Referenced by interrogateLock(), monitorLockForDisplay(), queryCartridgeState(), reset(), and searchForLock().
float WCAImpl::amcDrainEVoltage_m private
caches latest control value set.
Definition at line 364 of file WCAImpl.h.
Referenced by getAMCSetting(), reset(), setAMC(), and setEnableLO().
float WCAImpl::amcGateEVoltage_m private
caches latest control value set.
Definition at line 365 of file WCAImpl.h.
Referenced by getAMCSetting(), reset(), setAMC(), and setEnableLO().
int WCAImpl::band_m private
which cartridge band this is.
Definition at line 355 of file WCAImpl.h.
Referenced by adjustPLL(), bandSupportsAlternateLockMethod(), getBand(), getBandText(), photomixerEnable(), queryCartridgeState(), setAMC(), setEnableLO(), and setPAEnable().
const float WCAImpl::highCVRange static private
maximum PLL CV in-range
Definition at line 375 of file WCAImpl.h.
Referenced by testPLLCVInRange().
bool WCAImpl::isLockedLO_m private
true if the LO is currently locked.
Definition at line 366 of file WCAImpl.h.
Referenced by queryCartridgeState(), reset(), and searchForLock().
bool WCAImpl::LOEnable_m private
is the LO output enabled/disabled via setEnableLO()?
Definition at line 360 of file WCAImpl.h.
Referenced by getEnableLO(), reset(), and setEnableLO().
const float WCAImpl::lowCVRange static private
minimum PLL Correction Voltage considered in-range
Definition at line 374 of file WCAImpl.h.
Referenced by testPLLCVInRange().
const float WCAImpl::lowIFTotalPower static private
minimum IF Total Power Detect Voltage magnitude when locked
Definition at line 377 of file WCAImpl.h.
Referenced by monitorLockForDisplay(), and testPLLPowerLevels().
const float WCAImpl::lowLockDetectVoltage static private
minimum Lock Detect Voltage when locked
Definition at line 376 of file WCAImpl.h.
Referenced by monitorLockForDisplay(), and testPLLLockDetectVoltage().
const float WCAImpl::lowRefTotalPower static private
minimum Reference Total Power Detect Voltage magnitude when locked
Definition at line 378 of file WCAImpl.h.
Referenced by monitorLockForDisplay(), and testPLLPowerLevels().
const float WCAImpl::maxCVVariation static private
maximum threshold for PLL Correction Voltage variation when properly locked.
Definition at line 373 of file WCAImpl.h.
Referenced by testPLLCorrectionVoltageStats().
const float WCAImpl::maxSettingPAVD static private
maximum allowed LO PA drain voltage setting
Definition at line 381 of file WCAImpl.h.
Referenced by paPol0DrainVoltage(), and paPol1DrainVoltage().
const float WCAImpl::maxSettingPAVG static private
maximum allowed LO PA gate voltage setting
Definition at line 383 of file WCAImpl.h.
Referenced by paPol0GateVoltage(), and paPol1GateVoltage().
const float WCAImpl::minSettingPAVD static private
minumum allowed LO PA drain voltage setting
Definition at line 380 of file WCAImpl.h.
const float WCAImpl::minSettingPAVG static private
minumum allowed LO PA gate voltage setting
Definition at line 382 of file WCAImpl.h.
float WCAImpl::paDrainVoltage_m[2] private
caches latest control values set.
Definition at line 362 of file WCAImpl.h.
Referenced by getPADrainVoltageSetting(), paPol0DrainVoltage(), paPol1DrainVoltage(), queryCartridgeState(), reset(), and setEnableLO().
bool WCAImpl::paEnable_m private
is the LO PA enabled?
Definition at line 359 of file WCAImpl.h.
Referenced by getPAEnableSetting(), queryCartridgeState(), reset(), setEnableLO(), and setPAEnable().
float WCAImpl::paGateVoltage_m[2] private
caches latest control values set.
Definition at line 363 of file WCAImpl.h.
Referenced by getPAGateVoltageSetting(), paPol0GateVoltage(), paPol1GateVoltage(), queryCartridgeState(), and reset().
bool WCAImpl::photomixerEnable_m private
is the photomixer enabled?
Definition at line 361 of file WCAImpl.h.
Referenced by getPhotomixerEnableSetting(), photomixerEnable(), queryCartridgeState(), and reset().
int WCAImpl::pllCorrectionVoltage_count private
accumulate sample size of PLL CV since last tuning or reset.
Definition at line 369 of file WCAImpl.h.
Referenced by monitorLockForDisplay(), pllCorrectionVoltage(), resetPllCorrectionVoltageStats(), and testAlternateLockDetect().
float WCAImpl::pllCorrectionVoltage_max private
accumulate max PLL CV in sample.
Definition at line 370 of file WCAImpl.h.
Referenced by monitorLockForDisplay(), pllCorrectionVoltage(), resetPllCorrectionVoltageStats(), testAlternateLockDetect(), and testPLLCorrectionVoltageStats().
float WCAImpl::pllCorrectionVoltage_min private
accumulate min PLL CV in sample.
Definition at line 371 of file WCAImpl.h.
Referenced by monitorLockForDisplay(), pllCorrectionVoltage(), resetPllCorrectionVoltageStats(), testAlternateLockDetect(), and testPLLCorrectionVoltageStats().
bool WCAImpl::pllNullLoopIntegrator_m private
caches the last set null integrator value.
Definition at line 358 of file WCAImpl.h.
Referenced by getPLLNullLoopIntegratorSetting(), interrogateLock(), pllNullLoopIntegrator(), queryCartridgeState(), reset(), and setEnableLO().
int WCAImpl::pllSidebandLockSelect_m private
caches the last set sideband lock value.
Definition at line 357 of file WCAImpl.h.
Referenced by getPLLSidebandLockSelectSetting(), pllSidebandLockSelect(), queryCartridgeState(), and reset().
unsigned short WCAImpl::ytoCoarseTune_m private
caches the last set course tuning.
Definition at line 356 of file WCAImpl.h.
Referenced by getYTOCoarseTuneSetting(), queryCartridgeState(), reset(), setEnableLO(), and ytoCoarseTune().
The documentation for this class was generated from the following files:
WCAImpl.h
WCAImpl.cpp