FrontEndControl2: CryostatImpl Class Reference
CryostatImpl Class Reference
implementation class for the IF Switch module
#include <CryostatImpl.h>
Classes
struct Cryostat_t
Public Member Functions
CryostatImpl (unsigned long channel, unsigned long nodeAddress, const std::string &ESN="")
virtual ~CryostatImpl ()
bool cryoPumpingEnable (bool val)
bool getMonitorCryostat (Cryostat_t &target) const
void appendThermalLog (std::string &target) const
append thermal information to a logging string
void appendThermalLogHeader (std::string &target) const
append thermal header information to a logging string
Public Member Functions inherited from CryostatImplBase
CryostatImplBase (const std::string &name)
virtual ~CryostatImplBase ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual float cryostatTemperature0 ()
virtual float cryostatTemperature1 ()
virtual float cryostatTemperature2 ()
virtual float cryostatTemperature3 ()
virtual float cryostatTemperature4 ()
virtual float cryostatTemperature5 ()
virtual float cryostatTemperature6 ()
virtual float cryostatTemperature7 ()
virtual float cryostatTemperature8 ()
virtual float cryostatTemperature9 ()
virtual float cryostatTemperature10 ()
virtual float cryostatTemperature11 ()
virtual float cryostatTemperature12 ()
virtual bool backingPumpEnable ()
virtual bool turboPumpEnable ()
virtual bool turboPumpErrorState ()
virtual bool turboPumpHighSpeed ()
virtual unsigned char gateValveState ()
virtual unsigned char solenoidValveState ()
virtual float vacuumCryostatPressure ()
virtual float vacuumPortPressure ()
virtual bool vacuumGaugeEnable ()
virtual bool vacuumGaugeErrorState ()
virtual float supplyCurrent230V ()
virtual void backingPumpEnable (bool val)
virtual void turboPumpEnable (bool val)
virtual void gateValveState (unsigned char val)
virtual void solenoidValveState (unsigned char val)
virtual void vacuumGaugeEnable (bool val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Public Member Functions inherited from ThermalLoggable
ThermalLoggable ()
virtual ~ThermalLoggable ()
Private Attributes
class CryostatPumping * cryoPumpMonitor_mp
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Types inherited from CryostatImplBase
enum MonitorControlOffset {
CRYOSTAT_TEMP = 0x0000, BACKING_PUMP_ENABLE = 0x0034, TURBO_PUMP_ENABLE = 0x0038, TURBO_PUMP_STATE = 0x0039,
TURBO_PUMP_SPEED = 0x003A, GATE_VALVE_STATE = 0x003C, SOLENOID_VALVE_STATE = 0x0040, VACUUM_CRYOSTAT_PRES = 0x0044,
VACUUM_PORT_PRES = 0x0045, VACUUM_GAUGE_ENABLE = 0x0046, VACUUM_GAUGE_STATE = 0x0047, SUPPLY_CURRENT_230V = 0x0048
}
Protected Member Functions inherited from CryostatImplBase
FEMC_ERROR CryostatMonitorTempsensor (AmbRelativeAddr RCA, float &target)
helper to monitor a cryostat temperature sensor
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Protected Attributes inherited from CryostatImplBase
float cryostatTemperature0_value
float cryostatTemperature1_value
float cryostatTemperature2_value
float cryostatTemperature3_value
float cryostatTemperature4_value
float cryostatTemperature5_value
float cryostatTemperature6_value
float cryostatTemperature7_value
float cryostatTemperature8_value
float cryostatTemperature9_value
float cryostatTemperature10_value
float cryostatTemperature11_value
float cryostatTemperature12_value
bool backingPumpEnable_value
bool turboPumpEnable_value
bool turboPumpErrorState_value
bool turboPumpHighSpeed_value
unsigned char gateValveState_value
unsigned char solenoidValveState_value
float vacuumCryostatPressure_value
float vacuumPortPressure_value
bool vacuumGaugeEnable_value
bool vacuumGaugeErrorState_value
float supplyCurrent230V_value
int cryostatTemperature0_status
int cryostatTemperature1_status
int cryostatTemperature2_status
int cryostatTemperature3_status
int cryostatTemperature4_status
int cryostatTemperature5_status
int cryostatTemperature6_status
int cryostatTemperature7_status
int cryostatTemperature8_status
int cryostatTemperature9_status
int cryostatTemperature10_status
int cryostatTemperature11_status
int cryostatTemperature12_status
int backingPumpEnable_status
int supplyCurrent230V_status
int turboPumpEnable_status
int turboPumpErrorState_status
int turboPumpHighSpeed_status
int gateValveState_status
int solenoidValveState_status
int vacuumCryostatPressure_status
int vacuumPortPressure_status
int vacuumGaugeEnable_status
int vacuumGaugeErrorState_status
AmbRelativeAddr baseRCA
AmbRelativeAddr cryostatTemperature0_RCA
AmbRelativeAddr cryostatTemperature1_RCA
AmbRelativeAddr cryostatTemperature2_RCA
AmbRelativeAddr cryostatTemperature3_RCA
AmbRelativeAddr cryostatTemperature4_RCA
AmbRelativeAddr cryostatTemperature5_RCA
AmbRelativeAddr cryostatTemperature6_RCA
AmbRelativeAddr cryostatTemperature7_RCA
AmbRelativeAddr cryostatTemperature8_RCA
AmbRelativeAddr cryostatTemperature9_RCA
AmbRelativeAddr cryostatTemperature10_RCA
AmbRelativeAddr cryostatTemperature11_RCA
AmbRelativeAddr cryostatTemperature12_RCA
AmbRelativeAddr backingPumpEnable_RCA
AmbRelativeAddr supplyCurrent230V_RCA
AmbRelativeAddr turboPumpEnable_RCA
AmbRelativeAddr turboPumpErrorState_RCA
AmbRelativeAddr turboPumpHighSpeed_RCA
AmbRelativeAddr gateValveState_RCA
AmbRelativeAddr solenoidValveState_RCA
AmbRelativeAddr vacuumCryostatPressure_RCA
AmbRelativeAddr vacuumPortPressure_RCA
AmbRelativeAddr vacuumGaugeEnable_RCA
AmbRelativeAddr vacuumGaugeErrorState_RCA
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
implementation class for the IF Switch module
Definition at line 30 of file CryostatImpl.h.
Constructor & Destructor Documentation
CryostatImpl::CryostatImpl (unsigned long channel, unsigned long nodeAddress, const std::string & ESN = "")
Definition at line 28 of file CryostatImpl.cpp.
References CryostatImplBase::initialize(), and FEHardwareDevice::setESN().
CryostatImpl::~CryostatImpl () virtual
Definition at line 38 of file CryostatImpl.cpp.
References cryoPumpMonitor_mp.
Member Function Documentation
void CryostatImpl::appendThermalLog (std::string & target) const virtual
append thermal information to a logging string
Implements ThermalLoggable.
Definition at line 92 of file CryostatImpl.cpp.
References CryostatImplBase::backingPumpEnable_value, CryostatImplBase::cryostatTemperature0_value, CryostatImplBase::cryostatTemperature10_value, CryostatImplBase::cryostatTemperature11_value, CryostatImplBase::cryostatTemperature12_value, CryostatImplBase::cryostatTemperature1_value, CryostatImplBase::cryostatTemperature2_value, CryostatImplBase::cryostatTemperature3_value, CryostatImplBase::cryostatTemperature4_value, CryostatImplBase::cryostatTemperature5_value, CryostatImplBase::cryostatTemperature6_value, CryostatImplBase::cryostatTemperature7_value, CryostatImplBase::cryostatTemperature8_value, CryostatImplBase::cryostatTemperature9_value, CryostatImplBase::gateValveState_value, CryostatImplBase::solenoidValveState_value, CryostatImplBase::supplyCurrent230V_value, CryostatImplBase::turboPumpEnable_value, CryostatImplBase::turboPumpErrorState_value, CryostatImplBase::turboPumpHighSpeed_value, CryostatImplBase::vacuumCryostatPressure_value, and CryostatImplBase::vacuumPortPressure_value.
void CryostatImpl::appendThermalLogHeader (std::string & target) const virtual
append thermal header information to a logging string
Implements ThermalLoggable.
Definition at line 117 of file CryostatImpl.cpp.
bool CryostatImpl::cryoPumpingEnable (bool val)
Definition at line 45 of file CryostatImpl.cpp.
References CryostatImplBase::backingPumpEnable(), and cryoPumpMonitor_mp.
bool CryostatImpl::getMonitorCryostat (Cryostat_t & target) const
Definition at line 62 of file CryostatImpl.cpp.
References CryostatImpl::Cryostat_t::backingPumpEnable_value, CryostatImplBase::backingPumpEnable_value, CryostatImpl::Cryostat_t::cryostatTemperature0_value, CryostatImplBase::cryostatTemperature0_value, CryostatImpl::Cryostat_t::cryostatTemperature10_value, CryostatImplBase::cryostatTemperature10_value, CryostatImpl::Cryostat_t::cryostatTemperature11_value, CryostatImplBase::cryostatTemperature11_value, CryostatImpl::Cryostat_t::cryostatTemperature12_value, CryostatImplBase::cryostatTemperature12_value, CryostatImpl::Cryostat_t::cryostatTemperature1_value, CryostatImplBase::cryostatTemperature1_value, CryostatImpl::Cryostat_t::cryostatTemperature2_value, CryostatImplBase::cryostatTemperature2_value, CryostatImpl::Cryostat_t::cryostatTemperature3_value, CryostatImplBase::cryostatTemperature3_value, CryostatImpl::Cryostat_t::cryostatTemperature4_value, CryostatImplBase::cryostatTemperature4_value, CryostatImpl::Cryostat_t::cryostatTemperature5_value, CryostatImplBase::cryostatTemperature5_value, CryostatImpl::Cryostat_t::cryostatTemperature6_value, CryostatImplBase::cryostatTemperature6_value, CryostatImpl::Cryostat_t::cryostatTemperature7_value, CryostatImplBase::cryostatTemperature7_value, CryostatImpl::Cryostat_t::cryostatTemperature8_value, CryostatImplBase::cryostatTemperature8_value, CryostatImpl::Cryostat_t::cryostatTemperature9_value, CryostatImplBase::cryostatTemperature9_value, CryostatImpl::Cryostat_t::gateValveState_value, CryostatImplBase::gateValveState_value, CryostatImpl::Cryostat_t::solenoidValveState_value, CryostatImplBase::solenoidValveState_value, CryostatImpl::Cryostat_t::supplyCurrent230V_value, CryostatImplBase::supplyCurrent230V_value, CryostatImpl::Cryostat_t::turboPumpEnable_value, CryostatImplBase::turboPumpEnable_value, CryostatImpl::Cryostat_t::turboPumpErrorState_value, CryostatImplBase::turboPumpErrorState_value, CryostatImpl::Cryostat_t::turboPumpHighSpeed_value, CryostatImplBase::turboPumpHighSpeed_value, CryostatImpl::Cryostat_t::vacuumCryostatPressure_value, CryostatImplBase::vacuumCryostatPressure_value, CryostatImpl::Cryostat_t::vacuumGaugeEnable_value, CryostatImplBase::vacuumGaugeEnable_value, CryostatImpl::Cryostat_t::vacuumGaugeErrorState_value, CryostatImplBase::vacuumGaugeErrorState_value, CryostatImpl::Cryostat_t::vacuumPortPressure_value, and CryostatImplBase::vacuumPortPressure_value.
Member Data Documentation
class CryostatPumping* CryostatImpl::cryoPumpMonitor_mp private
Definition at line 76 of file CryostatImpl.h.
Referenced by cryoPumpingEnable(), and ~CryostatImpl().
The documentation for this class was generated from the following files:
CryostatImpl.h
CryostatImpl.cpp