FrontEndControl2: FEConfig::ParamTable Class Reference
FEConfig::ParamTable Class Reference
A ParamTable is a 2-D table of float values, indexed by a double 'freq' column.
#include <LookupTables.h>
Public Types
typedef base_type::iterator iterator
declare iterator types
typedef base_type::const_iterator const_iterator
Public Member Functions
ParamTable (unsigned numCols, double minInterpolateInterval=0.0)
construct with the number of columns to hold, not including the 'freq' col.
virtual ~ParamTable ()
void reset (unsigned numCols)
discard all contents and resize the number of columns.
void clear ()
discard all contents, keeping the same number of columns.
bool set (const double &freq, unsigned col, float value)
set a value at a given 'freq' and 'col'.
float get (const double &freq, unsigned col, bool interpolate=true) const
get a value at a given 'freq' and col.
bool get (const double &freq, ParamTableRow &target, bool interpolate=true) const
get a row of values corresponding to 'freq'.
bool get (const_iterator &it, double &freq, ParamTableRow &target) const
get the row of values at location 'it'.
const const_iterator begin () const
expose map's const iterator access methods.
const const_iterator end () const
expose map's const iterator access methods.
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
int freqWidth_m
field width for streaming double frequencies in GHz.
int freqPrecision_m
precision for streaming double frequencies in GHz.
Protected Attributes
unsigned numCols_m
holds a fixed number of columns, not including the freq col.
double minInterpolateInterval_m
when interpolating, if the difference between adjacent frequencies is smaller than this, don't interpolate. Instead pick the nearest value.
Private Types
typedef std::map< double, ParamTableRow > base_type
implemented in terms of STL map.
Static Private Member Functions
static double calculateWeight (const double &freq, const double &freqLo, const double &freqHi)
calculate the weight – a number between 0.0 and 1.0 indicating position of freq between freqLo and freqHi.
Detailed Description
A ParamTable is a 2-D table of float values, indexed by a double 'freq' column.
Given an LO frequency 'freq', a ParamTableRow may be retrieved. Linear interpolation is used if the requested freq is between two indexed rows.
Definition at line 99 of file LookupTables.h.
Member Typedef Documentation
typedef std::map<double, ParamTableRow> FEConfig::ParamTable::base_type private
implemented in terms of STL map.
Definition at line 100 of file LookupTables.h.
typedef base_type::const_iterator FEConfig::ParamTable::const_iterator
Definition at line 109 of file LookupTables.h.
typedef base_type::iterator FEConfig::ParamTable::iterator
declare iterator types
Definition at line 108 of file LookupTables.h.
Constructor & Destructor Documentation
FEConfig::ParamTable::ParamTable (unsigned numCols, double minInterpolateInterval = 0.0) inline
construct with the number of columns to hold, not including the 'freq' col.
Definition at line 114 of file LookupTables.h.
virtual FEConfig::ParamTable::~ParamTable () inline virtual
Definition at line 121 of file LookupTables.h.
Member Function Documentation
const const_iterator FEConfig::ParamTable::begin () const inline
expose map's const iterator access methods.
Definition at line 156 of file LookupTables.h.
Referenced by CartHealthCheck::prepare(), FEConfig::ConfigProviderIniFile::saveColdCartConfig(), and FEConfig::ConfigProviderIniFile::saveWCAConfig().
static double FEConfig::ParamTable::calculateWeight (const double & freq, const double & freqLo, const double & freqHi) inline static private
calculate the weight – a number between 0.0 and 1.0 indicating position of freq between freqLo and freqHi.
Definition at line 170 of file LookupTables.h.
void FEConfig::ParamTable::clear () inline
discard all contents, keeping the same number of columns.
Definition at line 129 of file LookupTables.h.
Referenced by FrontEndDatabase::getMixerParams(), FrontEndDatabase::getWCALOParams(), and reset().
const const_iterator FEConfig::ParamTable::end () const inline
expose map's const iterator access methods.
Definition at line 160 of file LookupTables.h.
Referenced by CartHealthCheck::prepare(), FEConfig::ConfigProviderIniFile::saveColdCartConfig(), and FEConfig::ConfigProviderIniFile::saveWCAConfig().
float FEConfig::ParamTable::get (const double & freq, unsigned col, bool interpolate = true) const
get a value at a given 'freq' and col.
If 'interpolate' is true, performs linear interpolation between rows if needed, but won't interpolate if the interval is smaller than minInterpolateInterval_m. Otherwise returns the value from the nearest row. Returns false if table is empty or col is out of bounds.
Definition at line 51 of file LookupTables.cpp.
Referenced by CartAssembly::adjustLOPowerAmps(), CartAssembly::getIVCurveDefaults(), CartAssembly::getSISMagnetNominal(), main(), CartAssembly::optimizeIFPower(), CartHealthCheck::prepare(), FEConfig::ConfigProviderIniFile::saveColdCartConfig(), FEConfig::ConfigProviderIniFile::saveWCAConfig(), CartAssembly::setLNABias(), CartAssembly::setLOPowerAmps(), and CartAssembly::setSISBias().
bool FEConfig::ParamTable::get (const double & freq, ParamTableRow & target, bool interpolate = true) const
get a row of values corresponding to 'freq'.
If 'interpolate' is true, performs linear interpolation between rows if needed, but won't interpolate if the interval is smaller than minInterpolateInterval_m. Otherwise returns the nearest row. returns false if the table is empty.
Definition at line 59 of file LookupTables.cpp.
References FEConfig::ParamTableRow::clear(), and FEConfig::ParamTableRow::weightedAdd().
bool FEConfig::ParamTable::get (const_iterator & it, double & freq, ParamTableRow & target) const
get the row of values at location 'it'.
The frequency is placed in 'freq' and the remaining values in 'target' returns true if iterator is valid.
Definition at line 122 of file LookupTables.cpp.
References FEConfig::ParamTableRow::clear().
void FEConfig::ParamTable::reset (unsigned numCols) inline
discard all contents and resize the number of columns.
Definition at line 124 of file LookupTables.h.
References clear().
bool FEConfig::ParamTable::set (const double & freq, unsigned col, float value)
set a value at a given 'freq' and 'col'.
This creates a new row for 'freq' if needed. Returns false if 'col' is out of bounds.
Definition at line 33 of file LookupTables.cpp.
References FEConfig::ParamTableRow::set().
Referenced by FEConfig::ConfigProviderIniFile::getColdCartConfig(), FrontEndDatabase::getMixerParams(), FrontEndDatabase::getPreampParams(), FEConfig::ConfigProviderIniFile::getWCAConfig(), FrontEndDatabase::getWCALOParams(), and main().
void FEConfig::ParamTable::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 134 of file LookupTables.cpp.
Referenced by FEConfig::operator<<().
Member Data Documentation
int FEConfig::ParamTable::freqPrecision_m
precision for streaming double frequencies in GHz.
Definition at line 112 of file LookupTables.h.
Referenced by FEConfig::MagnetParams::MagnetParams(), FEConfig::MixerParams::MixerParams(), and CartHealthCheck::prepare().
int FEConfig::ParamTable::freqWidth_m
field width for streaming double frequencies in GHz.
Definition at line 111 of file LookupTables.h.
Referenced by CartHealthCheck::prepare().
double FEConfig::ParamTable::minInterpolateInterval_m protected
when interpolating, if the difference between adjacent frequencies is smaller than this, don't interpolate. Instead pick the nearest value.
Definition at line 104 of file LookupTables.h.
Referenced by FEConfig::MagnetParams::MagnetParams(), and FEConfig::MixerParams::MixerParams().
unsigned FEConfig::ParamTable::numCols_m protected
holds a fixed number of columns, not including the freq col.
Definition at line 103 of file LookupTables.h.
The documentation for this class was generated from the following files:
CONFIG/LookupTables.h
CONFIG/LookupTables.cpp