FrontEndControl2: WCAImplBase Class Reference
WCAImplBase Class Reference
#include <WCAImplBase.h>
Public Member Functions
WCAImplBase (const std::string &name, int port)
virtual ~WCAImplBase ()
int getPort () const
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual unsigned short ytoCoarseTune ()
virtual bool photomixerEnable ()
virtual float photomixerVoltage ()
virtual float photomixerCurrent ()
virtual float pllLockDetectVoltage ()
virtual float pllCorrectionVoltage ()
virtual float pllAssemblyTemp ()
virtual float pllYTOHeaterCurrent ()
virtual float pllRefTotalPower ()
virtual float pllIfTotalPower ()
virtual bool pllUnlockDetectLatch ()
virtual bool pllLoopBandwidthSelect ()
virtual bool pllSidebandLockSelect ()
virtual bool pllNullLoopIntegrator ()
virtual float amcGateAVoltage ()
virtual float amcDrainAVoltage ()
virtual float amcDrainACurrent ()
virtual float amcGateBVoltage ()
virtual float amcDrainBVoltage ()
virtual float amcDrainBCurrent ()
virtual unsigned char amcMultiplierDVoltage ()
virtual float amcGateEVoltage ()
virtual float amcDrainEVoltage ()
virtual float amcDrainECurrent ()
virtual float amcMultiplierDCurrent ()
virtual float amcSupplyVoltage5V ()
virtual float paPol0GateVoltage ()
virtual float paPol0DrainVoltage ()
virtual float paPol0DrainCurrent ()
virtual float paPol1GateVoltage ()
virtual float paPol1DrainVoltage ()
virtual float paPol1DrainCurrent ()
virtual float paSupplyVoltage3V ()
virtual float paSupplyVoltage5V ()
virtual void ytoCoarseTune (unsigned short val)
virtual void photomixerEnable (bool val)
virtual void pllClearUnlockDetectLatch ()
virtual void pllLoopBandwidthSelect (bool val)
virtual void pllSidebandLockSelect (bool val)
virtual void pllNullLoopIntegrator (bool val)
virtual void amcDrainBVoltage (float val)
virtual void amcMultiplierDVoltage (unsigned char val)
virtual void amcGateEVoltage (float val)
virtual void amcDrainEVoltage (float val)
virtual void paPol0GateVoltage (float val)
virtual void paPol0DrainVoltage (float val)
virtual void paPol1GateVoltage (float val)
virtual void paPol1DrainVoltage (float val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Protected Types
enum MonitorControlOffset {
YTO_COARSE_TUNE = 0x0800, PHOTOMIXER_ENABLE = 0x0810, PHOTOMIXER_VOLTAGE = 0x0814, PHOTOMIXER_CURRENT = 0x0818,
PLL_LOCK_DETECT_VOLTAGE = 0x0820, PLL_CORRECTION_VOLTAGE = 0x0821, PLL_ASSEMBLY_TEMP = 0x0822, PLL_YTO_HEATER_CURRENT = 0x0823,
PLL_REF_TOTAL_POWER = 0x0824, PLL_IF_TOTAL_POWER = 0x0825, PLL_UNLOCK_DETECT_LATCH = 0x0827, PLL_CLEAR_UNLOCK_DETECT_LATCH = 0x0828,
PLL_LOOP_BANDWIDTH_SELECT = 0x0829, PLL_SIDEBAND_LOCK_POL_SELECT = 0x082A, PLL_NULL_LOOP_INTEGRATOR = 0x082B, AMC_GATE_A_VOLTAGE = 0x0830,
AMC_DRAIN_A_VOLTAGE = 0x0831, AMC_DRAIN_A_CURRENT = 0x0832, AMC_GATE_B_VOLTAGE = 0x0833, AMC_DRAIN_B_VOLTAGE = 0x0834,
AMC_DRAIN_B_CURRENT = 0x0835, AMC_MULTIPLIER_D_VOLTAGE = 0x0836, AMC_GATE_E_VOLTAGE = 0x0837, AMC_DRAIN_E_VOLTAGE = 0x0838,
AMC_DRAIN_E_CURRENT = 0x0839, AMC_MULTIPLIER_D_CURRENT = 0x083A, AMC_SUPPLY_VOLTAGE_5V = 0x083B, PA_GATE_VOLTAGE = 0x0840,
PA_DRAIN_VOLTAGE = 0x0841, PA_DRAIN_CURRENT = 0x0842, PA_SUPPLY_VOLTAGE_3V = 0x0848, PA_SUPPLY_VOLTAGE_5V = 0x084C
}
Protected Member Functions
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Protected Attributes
unsigned short ytoCoarseTune_value
bool photomixerEnable_value
float photomixerVoltage_value
float photomixerCurrent_value
float pllLockDetectVoltage_value
float pllCorrectionVoltage_value
float pllAssemblyTemp_value
float pllYTOHeaterCurrent_value
float pllRefTotalPower_value
float pllIfTotalPower_value
bool pllUnlockDetectLatch_value
bool pllLoopBandwidthSelect_value
bool pllSidebandLockSelect_value
bool pllNullLoopIntegrator_value
float amcGateAVoltage_value
float amcDrainAVoltage_value
float amcDrainACurrent_value
float amcGateBVoltage_value
float amcDrainBVoltage_value
float amcDrainBCurrent_value
unsigned char amcMultiplierDVoltage_value
float amcGateEVoltage_value
float amcDrainEVoltage_value
float amcDrainECurrent_value
float amcMultiplierDCurrent_value
float amcSupplyVoltage5V_value
float paPol0GateVoltage_value
float paPol0DrainVoltage_value
float paPol0DrainCurrent_value
float paPol1GateVoltage_value
float paPol1DrainVoltage_value
float paPol1DrainCurrent_value
float paSupplyVoltage3V_value
float paSupplyVoltage5V_value
int ytoCoarseTune_status
int photomixerEnable_status
int photomixerVoltage_status
int photomixerCurrent_status
int pllLockDetectVoltage_status
int pllCorrectionVoltage_status
int pllAssemblyTemp_status
int pllYTOHeaterCurrent_status
int pllRefTotalPower_status
int pllIfTotalPower_status
int pllUnlockDetectLatch_status
int pllClearUnlockDetectLatch_status
int pllLoopBandwidthSelect_status
int pllSidebandLockSelect_status
int pllNullLoopIntegrator_status
int amcGateAVoltage_status
int amcDrainAVoltage_status
int amcDrainACurrent_status
int amcGateBVoltage_status
int amcDrainBVoltage_status
int amcDrainBCurrent_status
int amcMultiplierDVoltage_status
int amcGateEVoltage_status
int amcDrainEVoltage_status
int amcDrainECurrent_status
int amcMultiplierDCurrent_status
int amcSupplyVoltage5V_status
int paPol0GateVoltage_status
int paPol0DrainVoltage_status
int paPol0DrainCurrent_status
int paPol1GateVoltage_status
int paPol1DrainVoltage_status
int paPol1DrainCurrent_status
int paSupplyVoltage3V_status
int paSupplyVoltage5V_status
AmbRelativeAddr baseRCA
AmbRelativeAddr ytoCoarseTune_RCA
AmbRelativeAddr photomixerEnable_RCA
AmbRelativeAddr photomixerVoltage_RCA
AmbRelativeAddr photomixerCurrent_RCA
AmbRelativeAddr pllLockDetectVoltage_RCA
AmbRelativeAddr pllCorrectionVoltage_RCA
AmbRelativeAddr pllAssemblyTemp_RCA
AmbRelativeAddr pllYTOHeaterCurrent_RCA
AmbRelativeAddr pllRefTotalPower_RCA
AmbRelativeAddr pllIfTotalPower_RCA
AmbRelativeAddr pllUnlockDetectLatch_RCA
AmbRelativeAddr pllClearUnlockDetectLatch_RCA
AmbRelativeAddr pllLoopBandwidthSelect_RCA
AmbRelativeAddr pllSidebandLockSelect_RCA
AmbRelativeAddr pllNullLoopIntegrator_RCA
AmbRelativeAddr amcGateAVoltage_RCA
AmbRelativeAddr amcDrainAVoltage_RCA
AmbRelativeAddr amcDrainACurrent_RCA
AmbRelativeAddr amcGateBVoltage_RCA
AmbRelativeAddr amcDrainBVoltage_RCA
AmbRelativeAddr amcDrainBCurrent_RCA
AmbRelativeAddr amcMultiplierDVoltage_RCA
AmbRelativeAddr amcGateEVoltage_RCA
AmbRelativeAddr amcDrainEVoltage_RCA
AmbRelativeAddr amcDrainECurrent_RCA
AmbRelativeAddr amcMultiplierDCurrent_RCA
AmbRelativeAddr amcSupplyVoltage5V_RCA
AmbRelativeAddr paPol0GateVoltage_RCA
AmbRelativeAddr paPol0DrainVoltage_RCA
AmbRelativeAddr paPol0DrainCurrent_RCA
AmbRelativeAddr paPol1GateVoltage_RCA
AmbRelativeAddr paPol1DrainVoltage_RCA
AmbRelativeAddr paPol1DrainCurrent_RCA
AmbRelativeAddr paSupplyVoltage3V_RCA
AmbRelativeAddr paSupplyVoltage5V_RCA
int port_m
to which FEMC port is this module connected.
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
WCAImplBase (const WCAImplBase &other)
void logMon (bool printHeader=false) const
Private Attributes
Time lastMonitorTime
int monitorPhase
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 33 of file WCAImplBase.h.
Member Enumeration Documentation
enum WCAImplBase::MonitorControlOffset protected
Enumerator
YTO_COARSE_TUNE
PHOTOMIXER_ENABLE
PHOTOMIXER_VOLTAGE
PHOTOMIXER_CURRENT
PLL_LOCK_DETECT_VOLTAGE
PLL_CORRECTION_VOLTAGE
PLL_ASSEMBLY_TEMP
PLL_YTO_HEATER_CURRENT
PLL_REF_TOTAL_POWER
PLL_IF_TOTAL_POWER
PLL_UNLOCK_DETECT_LATCH
PLL_CLEAR_UNLOCK_DETECT_LATCH
PLL_LOOP_BANDWIDTH_SELECT
PLL_SIDEBAND_LOCK_POL_SELECT
PLL_NULL_LOOP_INTEGRATOR
AMC_GATE_A_VOLTAGE
AMC_DRAIN_A_VOLTAGE
AMC_DRAIN_A_CURRENT
AMC_GATE_B_VOLTAGE
AMC_DRAIN_B_VOLTAGE
AMC_DRAIN_B_CURRENT
AMC_MULTIPLIER_D_VOLTAGE
AMC_GATE_E_VOLTAGE
AMC_DRAIN_E_VOLTAGE
AMC_DRAIN_E_CURRENT
AMC_MULTIPLIER_D_CURRENT
AMC_SUPPLY_VOLTAGE_5V
PA_GATE_VOLTAGE
PA_DRAIN_VOLTAGE
PA_DRAIN_CURRENT
PA_SUPPLY_VOLTAGE_3V
PA_SUPPLY_VOLTAGE_5V
Definition at line 100 of file WCAImplBase.h.
Constructor & Destructor Documentation
WCAImplBase::WCAImplBase (const std::string & name, int port)
Definition at line 34 of file WCAImplBase.cpp.
References AMC_DRAIN_A_CURRENT, AMC_DRAIN_A_VOLTAGE, AMC_DRAIN_B_CURRENT, AMC_DRAIN_B_VOLTAGE, AMC_DRAIN_E_CURRENT, AMC_DRAIN_E_VOLTAGE, AMC_GATE_A_VOLTAGE, AMC_GATE_B_VOLTAGE, AMC_GATE_E_VOLTAGE, AMC_MULTIPLIER_D_CURRENT, AMC_MULTIPLIER_D_VOLTAGE, AMC_SUPPLY_VOLTAGE_5V, amcDrainACurrent(), amcDrainACurrent_RCA, amcDrainACurrent_value, amcDrainAVoltage(), amcDrainAVoltage_RCA, amcDrainAVoltage_value, amcDrainBCurrent(), amcDrainBCurrent_RCA, amcDrainBCurrent_value, amcDrainBVoltage(), amcDrainBVoltage_RCA, amcDrainBVoltage_value, amcDrainECurrent(), amcDrainECurrent_RCA, amcDrainECurrent_value, amcDrainEVoltage(), amcDrainEVoltage_RCA, amcDrainEVoltage_value, amcGateAVoltage(), amcGateAVoltage_RCA, amcGateAVoltage_value, amcGateBVoltage(), amcGateBVoltage_RCA, amcGateBVoltage_value, amcGateEVoltage(), amcGateEVoltage_RCA, amcGateEVoltage_value, amcMultiplierDCurrent(), amcMultiplierDCurrent_RCA, amcMultiplierDCurrent_value, amcMultiplierDVoltage_RCA, amcSupplyVoltage5V(), amcSupplyVoltage5V_RCA, amcSupplyVoltage5V_value, baseRCA, PA_DRAIN_CURRENT, PA_DRAIN_VOLTAGE, PA_GATE_VOLTAGE, PA_SUPPLY_VOLTAGE_3V, PA_SUPPLY_VOLTAGE_5V, paPol0DrainCurrent(), paPol0DrainCurrent_RCA, paPol0DrainCurrent_value, paPol0DrainVoltage(), paPol0DrainVoltage_RCA, paPol0DrainVoltage_value, paPol0GateVoltage(), paPol0GateVoltage_RCA, paPol0GateVoltage_value, paPol1DrainCurrent(), paPol1DrainCurrent_RCA, paPol1DrainCurrent_value, paPol1DrainVoltage(), paPol1DrainVoltage_RCA, paPol1DrainVoltage_value, paPol1GateVoltage(), paPol1GateVoltage_RCA, paPol1GateVoltage_value, paSupplyVoltage3V(), paSupplyVoltage3V_RCA, paSupplyVoltage3V_value, paSupplyVoltage5V(), paSupplyVoltage5V_RCA, paSupplyVoltage5V_value, PHOTOMIXER_CURRENT, PHOTOMIXER_ENABLE, PHOTOMIXER_VOLTAGE, photomixerCurrent(), photomixerCurrent_RCA, photomixerCurrent_value, photomixerEnable_RCA, photomixerVoltage(), photomixerVoltage_RCA, photomixerVoltage_value, PLL_ASSEMBLY_TEMP, PLL_CLEAR_UNLOCK_DETECT_LATCH, PLL_CORRECTION_VOLTAGE, PLL_IF_TOTAL_POWER, PLL_LOCK_DETECT_VOLTAGE, PLL_LOOP_BANDWIDTH_SELECT, PLL_NULL_LOOP_INTEGRATOR, PLL_REF_TOTAL_POWER, PLL_SIDEBAND_LOCK_POL_SELECT, PLL_UNLOCK_DETECT_LATCH, PLL_YTO_HEATER_CURRENT, pllAssemblyTemp(), pllAssemblyTemp_RCA, pllAssemblyTemp_value, pllClearUnlockDetectLatch_RCA, pllCorrectionVoltage(), pllCorrectionVoltage_RCA, pllCorrectionVoltage_value, pllIfTotalPower(), pllIfTotalPower_RCA, pllIfTotalPower_value, pllLockDetectVoltage(), pllLockDetectVoltage_RCA, pllLockDetectVoltage_value, pllLoopBandwidthSelect_RCA, pllNullLoopIntegrator_RCA, pllRefTotalPower(), pllRefTotalPower_RCA, pllRefTotalPower_value, pllSidebandLockSelect_RCA, pllUnlockDetectLatch_RCA, pllYTOHeaterCurrent(), pllYTOHeaterCurrent_RCA, pllYTOHeaterCurrent_value, YTO_COARSE_TUNE, and ytoCoarseTune_RCA.
virtual WCAImplBase::~WCAImplBase () inline virtual
Definition at line 36 of file WCAImplBase.h.
References shutdown().
WCAImplBase::WCAImplBase (const WCAImplBase & other) private
Member Function Documentation
float WCAImplBase::amcDrainACurrent () virtual
Definition at line 257 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::amcDrainAVoltage () virtual
Definition at line 253 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::amcDrainBCurrent () virtual
Definition at line 269 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::amcDrainBVoltage () virtual
Definition at line 265 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by amcDrainBVoltage(), and WCAImplBase().
void WCAImplBase::amcDrainBVoltage (float val) virtual
Definition at line 354 of file WCAImplBase.cpp.
References amcDrainBVoltage(), and SYNCCMD_LOG_FLOAT.
float WCAImplBase::amcDrainECurrent () virtual
Definition at line 285 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::amcDrainEVoltage () virtual
Definition at line 281 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by amcDrainEVoltage(), WCAImpl::setAMC(), and WCAImplBase().
void WCAImplBase::amcDrainEVoltage (float val) virtual
Definition at line 366 of file WCAImplBase.cpp.
References amcDrainEVoltage(), and SYNCCMD_LOG_FLOAT.
float WCAImplBase::amcGateAVoltage () virtual
Definition at line 249 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::amcGateBVoltage () virtual
Definition at line 261 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::amcGateEVoltage () virtual
Definition at line 277 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by amcGateEVoltage(), WCAImpl::setAMC(), and WCAImplBase().
void WCAImplBase::amcGateEVoltage (float val) virtual
Definition at line 362 of file WCAImplBase.cpp.
References amcGateEVoltage(), and SYNCCMD_LOG_FLOAT.
float WCAImplBase::amcMultiplierDCurrent () virtual
Definition at line 289 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
unsigned char WCAImplBase::amcMultiplierDVoltage () virtual
Definition at line 273 of file WCAImplBase.cpp.
References SYNCMON_LOG_BYTE.
Referenced by amcMultiplierDVoltage(), and monitorAction().
void WCAImplBase::amcMultiplierDVoltage (unsigned char val) virtual
Definition at line 358 of file WCAImplBase.cpp.
References amcMultiplierDVoltage(), and SYNCCMD_LOG_BYTE.
float WCAImplBase::amcSupplyVoltage5V () virtual
Definition at line 293 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
int WCAImplBase::getPort () const inline
Definition at line 39 of file WCAImplBase.h.
References port_m.
void WCAImplBase::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Definition at line 184 of file WCAImplBase.cpp.
References FrontEndLVWrapper::nodeAddress.
Referenced by WCAImpl::WCAImpl().
void WCAImplBase::logMon (bool printHeader = false) const private
Definition at line 462 of file WCAImplBase.cpp.
Referenced by monitorAction().
void WCAImplBase::monitorAction (Time * timestamp_p) protected virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implements FEHardwareDevice.
Definition at line 386 of file WCAImplBase.cpp.
References amcMultiplierDVoltage(), amcMultiplierDVoltage_value, lastMonitorTime, logMon(), FEHardwareDevice::logMonitors_m, FEHardwareDevice::minimalMonitoring_m, monitorPhase, photomixerCurrent(), photomixerCurrent_value, photomixerEnable(), photomixerEnable_value, pllAssemblyTemp(), pllAssemblyTemp_value, pllCorrectionVoltage(), pllCorrectionVoltage_value, pllIfTotalPower(), pllIfTotalPower_value, pllLockDetectVoltage(), pllLockDetectVoltage_value, pllLoopBandwidthSelect(), pllLoopBandwidthSelect_value, pllNullLoopIntegrator(), pllNullLoopIntegrator_value, pllRefTotalPower(), pllRefTotalPower_value, pllSidebandLockSelect(), pllSidebandLockSelect_value, pllUnlockDetectLatch(), pllUnlockDetectLatch_value, FEHardwareDevice::randomizeAnalogMonitors_m, ytoCoarseTune(), and ytoCoarseTune_value.
float WCAImplBase::paPol0DrainCurrent () virtual
Definition at line 305 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::paPol0DrainVoltage () virtual
Definition at line 301 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImpl::getPADrainVoltage(), paPol0DrainVoltage(), WCAImpl::paPol0DrainVoltage(), WCAImpl::setEnableLO(), WCAImpl::setLOPower(), WCAImpl::setPADrainVoltage(), WCAImpl::setPAEnable(), and WCAImplBase().
void WCAImplBase::paPol0DrainVoltage (float val) virtual
Reimplemented in WCAImpl.
Definition at line 374 of file WCAImplBase.cpp.
References paPol0DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float WCAImplBase::paPol0GateVoltage () virtual
Definition at line 297 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by paPol0GateVoltage(), WCAImpl::paPol0GateVoltage(), WCAImpl::setPAEnable(), and WCAImplBase().
void WCAImplBase::paPol0GateVoltage (float val) virtual
Reimplemented in WCAImpl.
Definition at line 370 of file WCAImplBase.cpp.
References paPol0GateVoltage(), and SYNCCMD_LOG_FLOAT.
float WCAImplBase::paPol1DrainCurrent () virtual
Definition at line 317 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::paPol1DrainVoltage () virtual
Definition at line 313 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImpl::getPADrainVoltage(), paPol1DrainVoltage(), WCAImpl::paPol1DrainVoltage(), WCAImpl::setEnableLO(), WCAImpl::setLOPower(), WCAImpl::setPADrainVoltage(), WCAImpl::setPAEnable(), and WCAImplBase().
void WCAImplBase::paPol1DrainVoltage (float val) virtual
Reimplemented in WCAImpl.
Definition at line 382 of file WCAImplBase.cpp.
References paPol1DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float WCAImplBase::paPol1GateVoltage () virtual
Definition at line 309 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by paPol1GateVoltage(), WCAImpl::paPol1GateVoltage(), WCAImpl::setPAEnable(), and WCAImplBase().
void WCAImplBase::paPol1GateVoltage (float val) virtual
Reimplemented in WCAImpl.
Definition at line 378 of file WCAImplBase.cpp.
References paPol1GateVoltage(), and SYNCCMD_LOG_FLOAT.
float WCAImplBase::paSupplyVoltage3V () virtual
Definition at line 321 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::paSupplyVoltage5V () virtual
Definition at line 325 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::photomixerCurrent () virtual
Definition at line 205 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by monitorAction(), and WCAImplBase().
bool WCAImplBase::photomixerEnable () virtual
Definition at line 197 of file WCAImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), photomixerEnable(), WCAImpl::photomixerEnable(), and WCAImpl::queryCartridgeState().
void WCAImplBase::photomixerEnable (bool val) virtual
Reimplemented in WCAImpl.
Definition at line 334 of file WCAImplBase.cpp.
References photomixerEnable(), and SYNCCMD_LOG_BOOL.
float WCAImplBase::photomixerVoltage () virtual
Definition at line 201 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
float WCAImplBase::pllAssemblyTemp () virtual
Definition at line 217 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by monitorAction(), and WCAImplBase().
void WCAImplBase::pllClearUnlockDetectLatch () virtual
Definition at line 338 of file WCAImplBase.cpp.
References SYNCCMD_LOG_BOOL.
Referenced by WCAImpl::clearUnlockDetect().
float WCAImplBase::pllCorrectionVoltage () virtual
Reimplemented in WCAImpl.
Definition at line 213 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by monitorAction(), WCAImpl::pllCorrectionVoltage(), and WCAImplBase().
float WCAImplBase::pllIfTotalPower () virtual
Definition at line 229 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImpl::getMonitorPLL(), monitorAction(), WCAImpl::testPLLPowerLevels(), and WCAImplBase().
float WCAImplBase::pllLockDetectVoltage () virtual
Reimplemented in WCAImpl.
Definition at line 209 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by monitorAction(), WCAImpl::pllLockDetectVoltage(), and WCAImplBase().
bool WCAImplBase::pllLoopBandwidthSelect () virtual
Definition at line 237 of file WCAImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and pllLoopBandwidthSelect().
void WCAImplBase::pllLoopBandwidthSelect (bool val) virtual
Definition at line 342 of file WCAImplBase.cpp.
References pllLoopBandwidthSelect(), and SYNCCMD_LOG_BOOL.
bool WCAImplBase::pllNullLoopIntegrator () virtual
Definition at line 245 of file WCAImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), WCAImpl::pllNullLoopIntegrator(), pllNullLoopIntegrator(), WCAImpl::queryCartridgeState(), WCAImpl::searchForLock(), and WCAImpl::setEnableLO().
void WCAImplBase::pllNullLoopIntegrator (bool val) virtual
Reimplemented in WCAImpl.
Definition at line 350 of file WCAImplBase.cpp.
References pllNullLoopIntegrator(), and SYNCCMD_LOG_BOOL.
float WCAImplBase::pllRefTotalPower () virtual
Definition at line 225 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImpl::getMonitorPLL(), monitorAction(), WCAImpl::testPLLPowerLevels(), and WCAImplBase().
bool WCAImplBase::pllSidebandLockSelect () virtual
Definition at line 241 of file WCAImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), WCAImpl::pllSidebandLockSelect(), pllSidebandLockSelect(), and WCAImpl::queryCartridgeState().
void WCAImplBase::pllSidebandLockSelect (bool val) virtual
Reimplemented in WCAImpl.
Definition at line 346 of file WCAImplBase.cpp.
References pllSidebandLockSelect(), and SYNCCMD_LOG_BOOL.
bool WCAImplBase::pllUnlockDetectLatch () virtual
Definition at line 233 of file WCAImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by WCAImpl::getMonitorPLL(), monitorAction(), and WCAImpl::testPLLUnlockDetect().
float WCAImplBase::pllYTOHeaterCurrent () virtual
Definition at line 221 of file WCAImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by WCAImplBase().
void WCAImplBase::shutdown () virtual
Definition at line 189 of file WCAImplBase.cpp.
Referenced by ~WCAImplBase().
unsigned short WCAImplBase::ytoCoarseTune () virtual
Definition at line 193 of file WCAImplBase.cpp.
References SYNCMON_LOG_INT.
Referenced by WCAImpl::adjustPLL(), monitorAction(), WCAImpl::queryCartridgeState(), WCAImpl::setEnableLO(), WCAImpl::testAlternateLockDetect(), WCAImpl::ytoCoarseTune(), ytoCoarseTune(), and WCAImpl::ytoCoarseTuneWithTrace().
void WCAImplBase::ytoCoarseTune (unsigned short val) virtual
Reimplemented in WCAImpl.
Definition at line 330 of file WCAImplBase.cpp.
References SYNCCMD_LOG_INT, and ytoCoarseTune().
Member Data Documentation
AmbRelativeAddr WCAImplBase::amcDrainACurrent_RCA protected
Definition at line 228 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcDrainACurrent_status protected
Definition at line 191 of file WCAImplBase.h.
float WCAImplBase::amcDrainACurrent_value protected
Definition at line 155 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcDrainAVoltage_RCA protected
Definition at line 227 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcDrainAVoltage_status protected
Definition at line 190 of file WCAImplBase.h.
float WCAImplBase::amcDrainAVoltage_value protected
Definition at line 154 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcDrainBCurrent_RCA protected
Definition at line 231 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcDrainBCurrent_status protected
Definition at line 194 of file WCAImplBase.h.
float WCAImplBase::amcDrainBCurrent_value protected
Definition at line 158 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcDrainBVoltage_RCA protected
Definition at line 230 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcDrainBVoltage_status protected
Definition at line 193 of file WCAImplBase.h.
float WCAImplBase::amcDrainBVoltage_value protected
Definition at line 157 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcDrainECurrent_RCA protected
Definition at line 235 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcDrainECurrent_status protected
Definition at line 198 of file WCAImplBase.h.
float WCAImplBase::amcDrainECurrent_value protected
Definition at line 162 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcDrainEVoltage_RCA protected
Definition at line 234 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcDrainEVoltage_status protected
Definition at line 197 of file WCAImplBase.h.
float WCAImplBase::amcDrainEVoltage_value protected
Definition at line 161 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcGateAVoltage_RCA protected
Definition at line 226 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcGateAVoltage_status protected
Definition at line 189 of file WCAImplBase.h.
float WCAImplBase::amcGateAVoltage_value protected
Definition at line 153 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcGateBVoltage_RCA protected
Definition at line 229 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcGateBVoltage_status protected
Definition at line 192 of file WCAImplBase.h.
float WCAImplBase::amcGateBVoltage_value protected
Definition at line 156 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcGateEVoltage_RCA protected
Definition at line 233 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcGateEVoltage_status protected
Definition at line 196 of file WCAImplBase.h.
float WCAImplBase::amcGateEVoltage_value protected
Definition at line 160 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcMultiplierDCurrent_RCA protected
Definition at line 236 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcMultiplierDCurrent_status protected
Definition at line 199 of file WCAImplBase.h.
float WCAImplBase::amcMultiplierDCurrent_value protected
Definition at line 163 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::amcMultiplierDVoltage_RCA protected
Definition at line 232 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcMultiplierDVoltage_status protected
Definition at line 195 of file WCAImplBase.h.
unsigned char WCAImplBase::amcMultiplierDVoltage_value protected
Definition at line 159 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and monitorAction().
AmbRelativeAddr WCAImplBase::amcSupplyVoltage5V_RCA protected
Definition at line 237 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::amcSupplyVoltage5V_status protected
Definition at line 200 of file WCAImplBase.h.
float WCAImplBase::amcSupplyVoltage5V_value protected
Definition at line 164 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorAMC(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::baseRCA protected
Definition at line 210 of file WCAImplBase.h.
Referenced by WCAImplBase().
Time WCAImplBase::lastMonitorTime private
Definition at line 254 of file WCAImplBase.h.
Referenced by monitorAction().
int WCAImplBase::monitorPhase private
Definition at line 255 of file WCAImplBase.h.
Referenced by monitorAction().
AmbRelativeAddr WCAImplBase::paPol0DrainCurrent_RCA protected
Definition at line 240 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::paPol0DrainCurrent_status protected
Definition at line 203 of file WCAImplBase.h.
float WCAImplBase::paPol0DrainCurrent_value protected
Definition at line 167 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPA(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::paPol0DrainVoltage_RCA protected
Definition at line 239 of file WCAImplBase.h.
Referenced by WCAImpl::queryCartridgeState(), and WCAImplBase().
int WCAImplBase::paPol0DrainVoltage_status protected
Definition at line 202 of file WCAImplBase.h.
float WCAImplBase::paPol0DrainVoltage_value protected
Definition at line 166 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPA(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::paPol0GateVoltage_RCA protected
Definition at line 238 of file WCAImplBase.h.
Referenced by WCAImpl::queryCartridgeState(), and WCAImplBase().
int WCAImplBase::paPol0GateVoltage_status protected
Definition at line 201 of file WCAImplBase.h.
float WCAImplBase::paPol0GateVoltage_value protected
Definition at line 165 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPA(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::paPol1DrainCurrent_RCA protected
Definition at line 243 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::paPol1DrainCurrent_status protected
Definition at line 206 of file WCAImplBase.h.
float WCAImplBase::paPol1DrainCurrent_value protected
Definition at line 170 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPA(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::paPol1DrainVoltage_RCA protected
Definition at line 242 of file WCAImplBase.h.
Referenced by WCAImpl::queryCartridgeState(), and WCAImplBase().
int WCAImplBase::paPol1DrainVoltage_status protected
Definition at line 205 of file WCAImplBase.h.
float WCAImplBase::paPol1DrainVoltage_value protected
Definition at line 169 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPA(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::paPol1GateVoltage_RCA protected
Definition at line 241 of file WCAImplBase.h.
Referenced by WCAImpl::queryCartridgeState(), and WCAImplBase().
int WCAImplBase::paPol1GateVoltage_status protected
Definition at line 204 of file WCAImplBase.h.
float WCAImplBase::paPol1GateVoltage_value protected
Definition at line 168 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPA(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::paSupplyVoltage3V_RCA protected
Definition at line 244 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::paSupplyVoltage3V_status protected
Definition at line 207 of file WCAImplBase.h.
float WCAImplBase::paSupplyVoltage3V_value protected
Definition at line 171 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPA(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::paSupplyVoltage5V_RCA protected
Definition at line 245 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::paSupplyVoltage5V_status protected
Definition at line 208 of file WCAImplBase.h.
float WCAImplBase::paSupplyVoltage5V_value protected
Definition at line 172 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPA(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::photomixerCurrent_RCA protected
Definition at line 214 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::photomixerCurrent_status protected
Definition at line 177 of file WCAImplBase.h.
float WCAImplBase::photomixerCurrent_value protected
Definition at line 142 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPhotomixer(), monitorAction(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::photomixerEnable_RCA protected
Definition at line 212 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::photomixerEnable_status protected
Definition at line 175 of file WCAImplBase.h.
bool WCAImplBase::photomixerEnable_value protected
Definition at line 140 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPhotomixer(), and monitorAction().
AmbRelativeAddr WCAImplBase::photomixerVoltage_RCA protected
Definition at line 213 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::photomixerVoltage_status protected
Definition at line 176 of file WCAImplBase.h.
float WCAImplBase::photomixerVoltage_value protected
Definition at line 141 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPhotomixer(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::pllAssemblyTemp_RCA protected
Definition at line 217 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllAssemblyTemp_status protected
Definition at line 180 of file WCAImplBase.h.
float WCAImplBase::pllAssemblyTemp_value protected
Definition at line 145 of file WCAImplBase.h.
Referenced by WCAImpl::appendThermalLog(), WCAImpl::getMonitorPLL(), monitorAction(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::pllClearUnlockDetectLatch_RCA protected
Definition at line 222 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllClearUnlockDetectLatch_status protected
Definition at line 185 of file WCAImplBase.h.
AmbRelativeAddr WCAImplBase::pllCorrectionVoltage_RCA protected
Definition at line 216 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllCorrectionVoltage_status protected
Definition at line 179 of file WCAImplBase.h.
float WCAImplBase::pllCorrectionVoltage_value protected
Definition at line 144 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPLL(), monitorAction(), WCAImpl::monitorLockForDisplay(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::pllIfTotalPower_RCA protected
Definition at line 220 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllIfTotalPower_status protected
Definition at line 183 of file WCAImplBase.h.
float WCAImplBase::pllIfTotalPower_value protected
Definition at line 148 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPLL(), monitorAction(), WCAImpl::monitorLockForDisplay(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::pllLockDetectVoltage_RCA protected
Definition at line 215 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllLockDetectVoltage_status protected
Definition at line 178 of file WCAImplBase.h.
float WCAImplBase::pllLockDetectVoltage_value protected
Definition at line 143 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPLL(), monitorAction(), WCAImpl::monitorLockForDisplay(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::pllLoopBandwidthSelect_RCA protected
Definition at line 223 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllLoopBandwidthSelect_status protected
Definition at line 186 of file WCAImplBase.h.
bool WCAImplBase::pllLoopBandwidthSelect_value protected
Definition at line 150 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPLL(), and monitorAction().
AmbRelativeAddr WCAImplBase::pllNullLoopIntegrator_RCA protected
Definition at line 225 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllNullLoopIntegrator_status protected
Definition at line 188 of file WCAImplBase.h.
bool WCAImplBase::pllNullLoopIntegrator_value protected
Definition at line 152 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPLL(), monitorAction(), and WCAImpl::monitorLockForDisplay().
AmbRelativeAddr WCAImplBase::pllRefTotalPower_RCA protected
Definition at line 219 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllRefTotalPower_status protected
Definition at line 182 of file WCAImplBase.h.
float WCAImplBase::pllRefTotalPower_value protected
Definition at line 147 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPLL(), monitorAction(), WCAImpl::monitorLockForDisplay(), and WCAImplBase().
AmbRelativeAddr WCAImplBase::pllSidebandLockSelect_RCA protected
Definition at line 224 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllSidebandLockSelect_status protected
Definition at line 187 of file WCAImplBase.h.
bool WCAImplBase::pllSidebandLockSelect_value protected
Definition at line 151 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPLL(), and monitorAction().
AmbRelativeAddr WCAImplBase::pllUnlockDetectLatch_RCA protected
Definition at line 221 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllUnlockDetectLatch_status protected
Definition at line 184 of file WCAImplBase.h.
bool WCAImplBase::pllUnlockDetectLatch_value protected
Definition at line 149 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPLL(), and monitorAction().
AmbRelativeAddr WCAImplBase::pllYTOHeaterCurrent_RCA protected
Definition at line 218 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::pllYTOHeaterCurrent_status protected
Definition at line 181 of file WCAImplBase.h.
float WCAImplBase::pllYTOHeaterCurrent_value protected
Definition at line 146 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorPLL(), and WCAImplBase().
int WCAImplBase::port_m protected
to which FEMC port is this module connected.
Definition at line 248 of file WCAImplBase.h.
Referenced by getPort(), WCAImpl::photomixerEnable(), WCAImpl::queryCartridgeState(), WCAImpl::setAMC(), and WCAImpl::setPAEnable().
AmbRelativeAddr WCAImplBase::ytoCoarseTune_RCA protected
Definition at line 211 of file WCAImplBase.h.
Referenced by WCAImplBase().
int WCAImplBase::ytoCoarseTune_status protected
Definition at line 174 of file WCAImplBase.h.
unsigned short WCAImplBase::ytoCoarseTune_value protected
Definition at line 139 of file WCAImplBase.h.
Referenced by WCAImpl::getMonitorYTO(), and monitorAction().
The documentation for this class was generated from the following files:
FEBASE/WCAImplBase.h
FEBASE/WCAImplBase.cpp