FrontEndControl2: FrontEndDatabase Class Reference
FrontEndDatabase Class Reference
#include <FrontEndDatabase.h>
Public Types
enum COMPONENT_TYPES {
CTYPE_CRYOSTAT = 6, CTYPE_LPR = 17, CTYPE_CCA = 20, CTYPE_WCA = 11,
CTYPE_FETIM = 221, CTYPE_FLOOGM_MODULE = 96, CTYPE_IFSWICH_ASSY = 129, CTYPE_IFSWICH_SUBRACK = 162,
CTYPE_CPDS_ASSY = 4, CTYPE_CPDS_SUBRACK = 159
}
enum TESTDATA_TYPES {
TD_CCA_LNA_BIAS = 1, TD_CCA_TEMPSENSORS = 2, TD_CCA_SIS_BIAS = 3, TD_CRYOSTATTEMPS = 4,
TD_FLOOGDIST = 5, TD_IFTOTALPOWER = 6, TD_IFSPECTRUM = 7, TD_LPR_WARMHEALTH = 8,
TD_PHOTOMIXER_WARMHEALTH = 9, TD_IFSWITCHTEMPS = 10, TD_WCA_AMC_BIAS = 12, TD_WCA_PA_BIAS = 13,
TD_WCA_PLL_BIAS = 14, TD_YFACTOR = 15, TD_CPDS_MONITOR = 24, TD_IV_CURVE = 39,
TD_FINE_LO_SWEEP = 59
}
Types of test data we can insert/retrieve from the database:
Public Member Functions
FrontEndDatabase ()
FrontEndDatabase (const std::string &host, const std::string &user, const std::string &password, const std::string &dbName)
virtual ~FrontEndDatabase ()
bool getConfigurationRecord (const ID_T &configId, FEConfig::Configuration::Record &target) const
bool getMixerParams (const ID_T &componentId, FEConfig::MixerParams &mxrTarget, FEConfig::MagnetParams &magTarget) const
bool getPreampParams (const ID_T &componentId, FEConfig::ColdCartConfig &target) const
bool getWCAYIGLimits (const ID_T &componentId, double &FLOYIG, double &FHIYIG) const
bool getWCALOParams (const ID_T &componentId, FEConfig::PowerAmpParams &target) const
bool getConfigCryostat (const ID_T &configId, ID_T &componentId, std::string &SN) const
bool getConfigLPR (const ID_T &configId, ID_T &componentId, std::string &SN) const
bool getConfigFETIM (const ID_T &configId, ID_T &componentId, std::string &SN) const
bool getConfigFLOOGDistModule (const ID_T &configId, ID_T &componentId, std::string &SN) const
bool getConfigIFSwitchAssy (const ID_T &configId, ID_T &componentId, std::string &SN) const
bool getConfigCPDSAssy (const ID_T &configId, ID_T &componentId, std::string &SN) const
bool getConfigCCA (const ID_T &configId, int band, ID_T &componentId, std::string &SN) const
bool getConfigWCA (const ID_T &configId, int band, ID_T &componentId, std::string &SN) const
bool insertCryostatData (const ID_T &configId, DATASTATUS_TYPES dataStatus, const CryostatImpl::Cryostat_t &source) const
insert cryostat monitor data into database
bool insertIfSwitchData (const ID_T &configId, DATASTATUS_TYPES dataStatus, const IFSwitchImpl::IFSwitch_t &source) const
insert IF switch monitor data into database
bool insertLPRMonitorData (const ID_T &configId, DATASTATUS_TYPES dataStatus, const LPRImpl::LPR_t &source) const
insert LPR monitor data into database
bool findOrCreatePowerModuleDataHeader (ID_T &headerId, const ID_T &configId, DATASTATUS_TYPES dataStatus) const
create or find the latest test data header for saving many bands' CPDS voltages and currents monitor data.
bool insertPowerModuleData (const ID_T &headerId, unsigned band, double FreqLO, PowerModuleImpl::PowerModule_t &source) const
insert CPDS voltages and currents monitor data into database
bool findOrCreatePhotomixerDataHeader (ID_T &headerId, const ID_T &configId, DATASTATUS_TYPES dataStatus) const
create or find the latest test data header for saving many bands' photomixer monitor data.
bool insertPhotomixerData (const ID_T &headerId, unsigned band, const WCAImpl::Photomixer_t &source) const
insert photomixer monitor data, attached to a previously created TestData_header record.
bool insertPLLMonitorData (const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const WCAImpl::PLL_t &source) const
insert WCA PLL monitor data into database.
bool findOrCreateFLOOGDistHealthDataHeader (ID_T &headerId, const ID_T &configId, DATASTATUS_TYPES dataStatus) const
create or find the latest test data header for saving many bands' Ref Total Power monitor data.
bool insertFLOOGDistHealthData (const ID_T &headerId, unsigned band, float refTotalPower) const
insert Ref Total Power monitor data, attached to a previously created TestData_header record.
bool insertAMCMonitorData (const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const WCAImpl::AMC_t &source) const
insert WCA AMC monitor data into database.
bool insertPAMonitorData (const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const WCAImpl::PA_t &source) const
insert WCA PA monitor data into database.
bool insertCartTempData (const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band, const ColdCartImpl::CartridgeTemp_t &source) const
insert cartridge temperatures monitor data into database.
bool createSISMonitorDataHeader (ID_T &headerId, const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band) const
create a test data header for saving up to four mixers' SIS monitor data.
bool insertSISMonitorData (const ID_T &headerId, double FreqLO, unsigned pol, unsigned sb, const ColdCartImpl::SIS_t &source) const
insert SIS monitor data for a single mixer, attached to a previously created TestData_header record.
bool createLNAMonitorDataHeader (ID_T &headerId, const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band) const
create a test data header for saving up to four preamps' LNA monitor data.
bool insertLNAMonitorData (const ID_T &headerId, double FreqLO, unsigned pol, unsigned sb, const ColdCartImpl::LNA_t &source) const
insert LNA monitor data for three preamp stages, attached to a previously created TestData_header record.
bool insertIVCurveData (const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, unsigned pol, unsigned sb, const std::string &legend, const XYPlotArray &source) const
insert the given I-V curve into the database. legend gives additional descriptive text for this curve.
bool insertIFTotalPowerData (const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const std::string &legend, const IFPowerDataSet &data) const
insert IF total power data into the database.
bool insertYFactorData (const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const std::string &legend, const IFPowerDataSet &data) const
insert Y-factor data into the database.
bool findOrCreateFineLOSSweepDataHeader (ID_T &headerId, const ID_T &configId, DATASTATUS_TYPES dataStatus, unsigned band, const std::string &legend) const
create or find the latest test data header for saving multiple traces of Fine LO Sweep data.
bool insertFineLOSweepSubHeader (ID_T &subHeaderId, const ID_T &headerId, unsigned band, unsigned pol, float tiltAngle, double startLOFreq, double stopLOFreq, double stepLOFreq, float SISVoltage, float targetSIS1Current, const std::string &legend) const
create a new Fine LO Sweep subHeader attached to a previously created TestData_header record.
bool insertFineLOSSweepData (const ID_T &subHeaderId, const XYPlotArray &sisCurrents, const XYPlotArray &loPaVoltages) const
insert Fine LO Sweep data, attached to a previously created subHeader record.
Private Attributes
std::string measSWVer_m
Detailed Description
Definition at line 42 of file FrontEndDatabase.h.
Member Enumeration Documentation
enum FrontEndDatabase::COMPONENT_TYPES
Enumerator
CTYPE_CRYOSTAT
CTYPE_LPR
CTYPE_CCA
CTYPE_WCA
CTYPE_FETIM
CTYPE_FLOOGM_MODULE
CTYPE_IFSWICH_ASSY
CTYPE_IFSWICH_SUBRACK
CTYPE_CPDS_ASSY
CTYPE_CPDS_SUBRACK
Definition at line 70 of file FrontEndDatabase.h.
enum FrontEndDatabase::TESTDATA_TYPES
Types of test data we can insert/retrieve from the database:
Enumerator
TD_CCA_LNA_BIAS
TD_CCA_TEMPSENSORS
TD_CCA_SIS_BIAS
TD_CRYOSTATTEMPS
TD_FLOOGDIST
TD_IFTOTALPOWER
TD_IFSPECTRUM
TD_LPR_WARMHEALTH
TD_PHOTOMIXER_WARMHEALTH
TD_IFSWITCHTEMPS
TD_WCA_AMC_BIAS
TD_WCA_PA_BIAS
TD_WCA_PLL_BIAS
TD_YFACTOR
TD_CPDS_MONITOR
TD_IV_CURVE
TD_FINE_LO_SWEEP
Definition at line 113 of file FrontEndDatabase.h.
Constructor & Destructor Documentation
FrontEndDatabase::FrontEndDatabase ()
Definition at line 52 of file FrontEndDatabase.cpp.
FrontEndDatabase::FrontEndDatabase (const std::string & host, const std::string & user, const std::string & password, const std::string & dbName)
Definition at line 57 of file FrontEndDatabase.cpp.
virtual FrontEndDatabase::~FrontEndDatabase () inline virtual
Definition at line 51 of file FrontEndDatabase.h.
Member Function Documentation
bool FrontEndDatabase::createLNAMonitorDataHeader (ID_T & headerId, const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band) const
create a test data header for saving up to four preamps' LNA monitor data.
Definition at line 792 of file FrontEndDatabase.cpp.
References getConfigCCA(), measSWVer_m, and TD_CCA_LNA_BIAS.
bool FrontEndDatabase::createSISMonitorDataHeader (ID_T & headerId, const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band) const
create a test data header for saving up to four mixers' SIS monitor data.
Definition at line 742 of file FrontEndDatabase.cpp.
References getConfigCCA(), measSWVer_m, and TD_CCA_SIS_BIAS.
bool FrontEndDatabase::findOrCreateFineLOSSweepDataHeader (ID_T & headerId, const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band, const std::string & legend) const
create or find the latest test data header for saving multiple traces of Fine LO Sweep data.
Definition at line 1064 of file FrontEndDatabase.cpp.
References measSWVer_m, and TD_FINE_LO_SWEEP.
bool FrontEndDatabase::findOrCreateFLOOGDistHealthDataHeader (ID_T & headerId, const ID_T & configId, DATASTATUS_TYPES dataStatus) const
create or find the latest test data header for saving many bands' Ref Total Power monitor data.
Definition at line 596 of file FrontEndDatabase.cpp.
References getConfigFLOOGDistModule(), measSWVer_m, and TD_FLOOGDIST.
bool FrontEndDatabase::findOrCreatePhotomixerDataHeader (ID_T & headerId, const ID_T & configId, DATASTATUS_TYPES dataStatus) const
create or find the latest test data header for saving many bands' photomixer monitor data.
Definition at line 511 of file FrontEndDatabase.cpp.
References measSWVer_m, and TD_PHOTOMIXER_WARMHEALTH.
bool FrontEndDatabase::findOrCreatePowerModuleDataHeader (ID_T & headerId, const ID_T & configId, DATASTATUS_TYPES dataStatus) const
create or find the latest test data header for saving many bands' CPDS voltages and currents monitor data.
Definition at line 449 of file FrontEndDatabase.cpp.
References getConfigCPDSAssy(), measSWVer_m, and TD_CPDS_MONITOR.
bool FrontEndDatabase::getConfigCCA (const ID_T & configId, int band, ID_T & componentId, std::string & SN) const inline
Definition at line 103 of file FrontEndDatabase.h.
References CTYPE_CCA.
Referenced by createLNAMonitorDataHeader(), createSISMonitorDataHeader(), insertCartTempData(), and insertIVCurveData().
bool FrontEndDatabase::getConfigCPDSAssy (const ID_T & configId, ID_T & componentId, std::string & SN) const inline
Definition at line 99 of file FrontEndDatabase.h.
References CTYPE_CPDS_ASSY, and CTYPE_CPDS_SUBRACK.
Referenced by findOrCreatePowerModuleDataHeader().
bool FrontEndDatabase::getConfigCryostat (const ID_T & configId, ID_T & componentId, std::string & SN) const inline
Definition at line 83 of file FrontEndDatabase.h.
References CTYPE_CRYOSTAT.
Referenced by insertCryostatData().
bool FrontEndDatabase::getConfigFETIM (const ID_T & configId, ID_T & componentId, std::string & SN) const inline
Definition at line 89 of file FrontEndDatabase.h.
References CTYPE_FETIM.
bool FrontEndDatabase::getConfigFLOOGDistModule (const ID_T & configId, ID_T & componentId, std::string & SN) const inline
Definition at line 92 of file FrontEndDatabase.h.
References CTYPE_FLOOGM_MODULE.
Referenced by findOrCreateFLOOGDistHealthDataHeader().
bool FrontEndDatabase::getConfigIFSwitchAssy (const ID_T & configId, ID_T & componentId, std::string & SN) const inline
Definition at line 95 of file FrontEndDatabase.h.
References CTYPE_IFSWICH_ASSY, and CTYPE_IFSWICH_SUBRACK.
Referenced by insertIfSwitchData().
bool FrontEndDatabase::getConfigLPR (const ID_T & configId, ID_T & componentId, std::string & SN) const inline
Definition at line 86 of file FrontEndDatabase.h.
References CTYPE_LPR.
Referenced by insertLPRMonitorData().
bool FrontEndDatabase::getConfigurationRecord (const ID_T & configId, FEConfig::Configuration::Record & target) const
Definition at line 69 of file FrontEndDatabase.cpp.
References FEConfig::Configuration::Record::CAId_m, FEConfig::Configuration::Record::configId_m, FEConfig::Configuration::Record::description_m, FEConfig::Configuration::Record::keyFacility_m, and FEConfig::Configuration::Record::keyFrontEnd_m.
bool FrontEndDatabase::getConfigWCA (const ID_T & configId, int band, ID_T & componentId, std::string & SN) const inline
Definition at line 106 of file FrontEndDatabase.h.
References CTYPE_WCA.
Referenced by insertAMCMonitorData(), insertPAMonitorData(), and insertPLLMonitorData().
bool FrontEndDatabase::getMixerParams (const ID_T & componentId, FEConfig::MixerParams & mxrTarget, FEConfig::MagnetParams & magTarget) const
Definition at line 110 of file FrontEndDatabase.cpp.
References FEConfig::ParamTable::clear(), FIELD_TO_DOUBLE, FIELD_TO_SINGLE, FIELD_TO_UNSIGNED, and FEConfig::ParamTable::set().
bool FrontEndDatabase::getPreampParams (const ID_T & componentId, FEConfig::ColdCartConfig & target) const
Definition at line 166 of file FrontEndDatabase.cpp.
References FIELD_TO_DOUBLE, FIELD_TO_SINGLE, FIELD_TO_UNSIGNED, FEConfig::ParamTable::set(), and FEConfig::ColdCartConfig::usePreampParams().
bool FrontEndDatabase::getWCALOParams (const ID_T & componentId, FEConfig::PowerAmpParams & target) const
Definition at line 262 of file FrontEndDatabase.cpp.
References FEConfig::ParamTable::clear(), FIELD_TO_DOUBLE, FIELD_TO_SINGLE, and FEConfig::ParamTable::set().
bool FrontEndDatabase::getWCAYIGLimits (const ID_T & componentId, double & FLOYIG, double & FHIYIG) const
Definition at line 225 of file FrontEndDatabase.cpp.
References FIELD_TO_DOUBLE.
bool FrontEndDatabase::insertAMCMonitorData (const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const WCAImpl::AMC_t & source) const
insert WCA AMC monitor data into database.
Definition at line 645 of file FrontEndDatabase.cpp.
References WCAImpl::AMC_t::amcDrainACurrent_value, WCAImpl::AMC_t::amcDrainAVoltage_value, WCAImpl::AMC_t::amcDrainBCurrent_value, WCAImpl::AMC_t::amcDrainBVoltage_value, WCAImpl::AMC_t::amcDrainECurrent_value, WCAImpl::AMC_t::amcDrainEVoltage_value, WCAImpl::AMC_t::amcGateAVoltage_value, WCAImpl::AMC_t::amcGateBVoltage_value, WCAImpl::AMC_t::amcGateEVoltage_value, WCAImpl::AMC_t::amcMultiplierDCurrent_value, WCAImpl::AMC_t::amcMultiplierDVoltage_value, WCAImpl::AMC_t::amcSupplyVoltage5V_value, getConfigWCA(), measSWVer_m, and TD_WCA_AMC_BIAS.
bool FrontEndDatabase::insertCartTempData (const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band, const ColdCartImpl::CartridgeTemp_t & source) const
insert cartridge temperatures monitor data into database.
Definition at line 858 of file FrontEndDatabase.cpp.
References ColdCartImpl::CartridgeTemp_t::cartridgeTemperature0_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature1_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature2_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature3_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature4_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature5_value, getConfigCCA(), measSWVer_m, and TD_CCA_TEMPSENSORS.
bool FrontEndDatabase::insertCryostatData (const ID_T & configId, DATASTATUS_TYPES dataStatus, const CryostatImpl::Cryostat_t & source) const
insert cryostat monitor data into database
Definition at line 318 of file FrontEndDatabase.cpp.
References CryostatImpl::Cryostat_t::cryostatTemperature0_value, CryostatImpl::Cryostat_t::cryostatTemperature10_value, CryostatImpl::Cryostat_t::cryostatTemperature11_value, CryostatImpl::Cryostat_t::cryostatTemperature12_value, CryostatImpl::Cryostat_t::cryostatTemperature1_value, CryostatImpl::Cryostat_t::cryostatTemperature2_value, CryostatImpl::Cryostat_t::cryostatTemperature3_value, CryostatImpl::Cryostat_t::cryostatTemperature4_value, CryostatImpl::Cryostat_t::cryostatTemperature5_value, CryostatImpl::Cryostat_t::cryostatTemperature6_value, CryostatImpl::Cryostat_t::cryostatTemperature7_value, CryostatImpl::Cryostat_t::cryostatTemperature8_value, CryostatImpl::Cryostat_t::cryostatTemperature9_value, getConfigCryostat(), measSWVer_m, and TD_CRYOSTATTEMPS.
bool FrontEndDatabase::insertFineLOSSweepData (const ID_T & subHeaderId, const XYPlotArray & sisCurrents, const XYPlotArray & loPaVoltages) const
insert Fine LO Sweep data, attached to a previously created subHeader record.
Definition at line 1130 of file FrontEndDatabase.cpp.
bool FrontEndDatabase::insertFineLOSweepSubHeader (ID_T & subHeaderId, const ID_T & headerId, unsigned band, unsigned pol, float tiltAngle, double startLOFreq, double stopLOFreq, double stepLOFreq, float SISVoltage, float targetSIS1Current, const std::string & legend) const
create a new Fine LO Sweep subHeader attached to a previously created TestData_header record.
Definition at line 1089 of file FrontEndDatabase.cpp.
bool FrontEndDatabase::insertFLOOGDistHealthData (const ID_T & headerId, unsigned band, float refTotalPower) const
insert Ref Total Power monitor data, attached to a previously created TestData_header record.
Definition at line 624 of file FrontEndDatabase.cpp.
bool FrontEndDatabase::insertIfSwitchData (const ID_T & configId, DATASTATUS_TYPES dataStatus, const IFSwitchImpl::IFSwitch_t & source) const
insert IF switch monitor data into database
Definition at line 368 of file FrontEndDatabase.cpp.
References getConfigIFSwitchAssy(), measSWVer_m, IFSwitchImpl::IFSwitch_t::pol0Sb1AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol0Sb2AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol1Sb1AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol1Sb2AssemblyTemp_value, and TD_IFSWITCHTEMPS.
bool FrontEndDatabase::insertIFTotalPowerData (const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const std::string & legend, const IFPowerDataSet & data) const
insert IF total power data into the database.
Definition at line 943 of file FrontEndDatabase.cpp.
References ColdCartImpl::hasSb2(), measSWVer_m, IFPowerDataSet::PHOT0_IF0, IFPowerDataSet::PHOT0_IF1, IFPowerDataSet::PHOT0_IF2, IFPowerDataSet::PHOT0_IF3, IFPowerDataSet::PHOT15_IF0, IFPowerDataSet::PHOT15_IF1, IFPowerDataSet::PHOT15_IF2, IFPowerDataSet::PHOT15_IF3, and TD_IFTOTALPOWER.
bool FrontEndDatabase::insertIVCurveData (const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, unsigned pol, unsigned sb, const std::string & legend, const XYPlotArray & source) const
insert the given I-V curve into the database. legend gives additional descriptive text for this curve.
Definition at line 900 of file FrontEndDatabase.cpp.
References getConfigCCA(), measSWVer_m, and TD_IV_CURVE.
bool FrontEndDatabase::insertLNAMonitorData (const ID_T & headerId, double FreqLO, unsigned pol, unsigned sb, const ColdCartImpl::LNA_t & source) const
insert LNA monitor data for three preamp stages, attached to a previously created TestData_header record.
Definition at line 816 of file FrontEndDatabase.cpp.
References ColdCartImpl::LNA_t::lnaSt1DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt1DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt1GateVoltage_value, ColdCartImpl::LNA_t::lnaSt2DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt2DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt2GateVoltage_value, ColdCartImpl::LNA_t::lnaSt3DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt3DrainVoltage_value, and ColdCartImpl::LNA_t::lnaSt3GateVoltage_value.
bool FrontEndDatabase::insertLPRMonitorData (const ID_T & configId, DATASTATUS_TYPES dataStatus, const LPRImpl::LPR_t & source) const
insert LPR monitor data into database
Definition at line 406 of file FrontEndDatabase.cpp.
References LPRImpl::LPR_t::EDFALaserDriveCurrent_value, LPRImpl::LPR_t::EDFALaserPhotoDetectCurrent_value, LPRImpl::LPR_t::EDFALaserPumpTemperature_value, LPRImpl::LPR_t::EDFAModulationInput_value, LPRImpl::LPR_t::EDFAPhotoDetectCurrent_value, LPRImpl::LPR_t::EDFAPhotoDetectPower_value, getConfigLPR(), LPRImpl::LPR_t::LPRTemperature0_value, LPRImpl::LPR_t::LPRTemperature1_value, measSWVer_m, and TD_LPR_WARMHEALTH.
bool FrontEndDatabase::insertPAMonitorData (const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const WCAImpl::PA_t & source) const
insert WCA PA monitor data into database.
Definition at line 695 of file FrontEndDatabase.cpp.
References getConfigWCA(), measSWVer_m, WCAImpl::PA_t::paPol0DrainCurrent_value, WCAImpl::PA_t::paPol0DrainVoltage_value, WCAImpl::PA_t::paPol0GateVoltage_value, WCAImpl::PA_t::paPol1DrainCurrent_value, WCAImpl::PA_t::paPol1DrainVoltage_value, WCAImpl::PA_t::paPol1GateVoltage_value, WCAImpl::PA_t::paSupplyVoltage3V_value, WCAImpl::PA_t::paSupplyVoltage5V_value, and TD_WCA_PA_BIAS.
bool FrontEndDatabase::insertPhotomixerData (const ID_T & headerId, unsigned band, const WCAImpl::Photomixer_t & source) const
insert photomixer monitor data, attached to a previously created TestData_header record.
Definition at line 535 of file FrontEndDatabase.cpp.
References WCAImpl::Photomixer_t::photomixerCurrent_value, and WCAImpl::Photomixer_t::photomixerVoltage_value.
bool FrontEndDatabase::insertPLLMonitorData (const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const WCAImpl::PLL_t & source) const
insert WCA PLL monitor data into database.
Definition at line 557 of file FrontEndDatabase.cpp.
References getConfigWCA(), measSWVer_m, WCAImpl::PLL_t::pllAssemblyTemp_value, WCAImpl::PLL_t::pllYTOHeaterCurrent_value, and TD_WCA_PLL_BIAS.
bool FrontEndDatabase::insertPowerModuleData (const ID_T & headerId, unsigned band, double FreqLO, PowerModuleImpl::PowerModule_t & source) const
insert CPDS voltages and currents monitor data into database
Definition at line 477 of file FrontEndDatabase.cpp.
References PowerModuleImpl::PowerModule_t::currentN15V_value, PowerModuleImpl::PowerModule_t::currentN6V_value, PowerModuleImpl::PowerModule_t::currentP15V_value, PowerModuleImpl::PowerModule_t::currentP24V_value, PowerModuleImpl::PowerModule_t::currentP6V_value, PowerModuleImpl::PowerModule_t::currentP8V_value, PowerModuleImpl::PowerModule_t::voltageN15V_value, PowerModuleImpl::PowerModule_t::voltageN6V_value, PowerModuleImpl::PowerModule_t::voltageP15V_value, PowerModuleImpl::PowerModule_t::voltageP24V_value, PowerModuleImpl::PowerModule_t::voltageP6V_value, and PowerModuleImpl::PowerModule_t::voltageP8V_value.
bool FrontEndDatabase::insertSISMonitorData (const ID_T & headerId, double FreqLO, unsigned pol, unsigned sb, const ColdCartImpl::SIS_t & source) const
insert SIS monitor data for a single mixer, attached to a previously created TestData_header record.
Definition at line 766 of file FrontEndDatabase.cpp.
References ColdCartImpl::SIS_t::sisCurrent_value, ColdCartImpl::SIS_t::sisMagnetCurrent_value, ColdCartImpl::SIS_t::sisMagnetVoltage_value, and ColdCartImpl::SIS_t::sisVoltage_value.
bool FrontEndDatabase::insertYFactorData (const ID_T & configId, DATASTATUS_TYPES dataStatus, unsigned band, double FreqLO, const std::string & legend, const IFPowerDataSet & data) const
insert Y-factor data into the database.
Definition at line 995 of file FrontEndDatabase.cpp.
References ColdCartImpl::hasSb2(), measSWVer_m, IFPowerDataSet::PCOLD_IF0, IFPowerDataSet::PCOLD_IF1, IFPowerDataSet::PCOLD_IF2, IFPowerDataSet::PCOLD_IF3, IFPowerDataSet::PHOT0_IF0, IFPowerDataSet::PHOT0_IF1, IFPowerDataSet::PHOT0_IF2, IFPowerDataSet::PHOT0_IF3, IFPowerDataSet::PHOT15_IF0, IFPowerDataSet::PHOT15_IF1, IFPowerDataSet::PHOT15_IF2, IFPowerDataSet::PHOT15_IF3, TD_YFACTOR, IFPowerDataSet::YFACTOR_IF0, IFPowerDataSet::YFACTOR_IF1, IFPowerDataSet::YFACTOR_IF2, and IFPowerDataSet::YFACTOR_IF3.
Member Data Documentation
std::string FrontEndDatabase::measSWVer_m private
Definition at line 213 of file FrontEndDatabase.h.
Referenced by createLNAMonitorDataHeader(), createSISMonitorDataHeader(), findOrCreateFineLOSSweepDataHeader(), findOrCreateFLOOGDistHealthDataHeader(), findOrCreatePhotomixerDataHeader(), findOrCreatePowerModuleDataHeader(), insertAMCMonitorData(), insertCartTempData(), insertCryostatData(), insertIfSwitchData(), insertIFTotalPowerData(), insertIVCurveData(), insertLPRMonitorData(), insertPAMonitorData(), insertPLLMonitorData(), and insertYFactorData().
The documentation for this class was generated from the following files:
CONFIG/FrontEndDatabase.h
CONFIG/FrontEndDatabase.cpp