FrontEndControl2: CartridgesContainer Class Reference
CartridgesContainer Class Reference
#include <CartridgesContainer.h>
Classes
class Impl
Public Member Functions
CartridgesContainer ()
~CartridgesContainer ()
void reset ()
bool addCartridge (int port, WCAImpl &WCA, ColdCartImpl &coldCart)
bool addCartridge (int port, WCAImpl &WCA)
bool addCartridge (int port, ColdCartImpl &coldCart)
bool deleteCartridge (int port)
void queryCartridgeState ()
void measureSISVoltageError (int port)
bool existsCartAssembly (int port) const
bool existsColdCart (int port) const
bool existsWCA (int port) const
CartAssembly * getCartAssembly (int port)
const CartAssembly * getCartAssembly (int port) const
const ColdCartImpl * getColdCart (int port) const
const WCAImpl * getWCA (int port) const
void startMonitor ()
void stopMonitor ()
bool pauseMonitor (int port, bool pauseWCA, bool pauseCC)
bool setObserving (int port)
void clearObserving ()
int getObserving () const
bool setEnable (int port)
bool clearEnable (int port)
bool getEnable (int port) const
void print (const std::string &callerName, int port=-1) const
void appendThermalLog (std::string &target) const
append thermal information to a logging string
void appendThermalLogHeader (std::string &target) const
append thermal header information to a logging string
Public Member Functions inherited from ThermalLoggable
ThermalLoggable ()
virtual ~ThermalLoggable ()
Private Attributes
Impl * carts_mp
int numEnabled_m
int observingPort_m
Detailed Description
Definition at line 30 of file CartridgesContainer.h.
Constructor & Destructor Documentation
CartridgesContainer::CartridgesContainer ()
Definition at line 72 of file CartridgesContainer.cpp.
CartridgesContainer::~CartridgesContainer ()
Definition at line 78 of file CartridgesContainer.cpp.
References carts_mp, and reset().
Member Function Documentation
bool CartridgesContainer::addCartridge (int port, WCAImpl & WCA, ColdCartImpl & coldCart)
Definition at line 90 of file CartridgesContainer.cpp.
References carts_mp, WCAImpl::getBand(), ColdCartImpl::getBand(), and print().
bool CartridgesContainer::addCartridge (int port, WCAImpl & WCA)
Definition at line 110 of file CartridgesContainer.cpp.
References carts_mp, and print().
bool CartridgesContainer::addCartridge (int port, ColdCartImpl & coldCart)
Definition at line 123 of file CartridgesContainer.cpp.
References carts_mp, and print().
void CartridgesContainer::appendThermalLog (std::string & target) const virtual
append thermal information to a logging string
Implements ThermalLoggable.
Definition at line 312 of file CartridgesContainer.cpp.
References carts_mp.
void CartridgesContainer::appendThermalLogHeader (std::string & target) const virtual
append thermal header information to a logging string
Implements ThermalLoggable.
Definition at line 321 of file CartridgesContainer.cpp.
References CartAssembly::appendThermalLogHeaderImpl().
bool CartridgesContainer::clearEnable (int port)
Definition at line 264 of file CartridgesContainer.cpp.
References carts_mp, clearObserving(), getEnable(), numEnabled_m, observingPort_m, and print().
Referenced by deleteCartridge().
void CartridgesContainer::clearObserving ()
Definition at line 244 of file CartridgesContainer.cpp.
References carts_mp, existsCartAssembly(), observingPort_m, and print().
Referenced by clearEnable(), and setObserving().
bool CartridgesContainer::deleteCartridge (int port)
Definition at line 136 of file CartridgesContainer.cpp.
References carts_mp, clearEnable(), and existsCartAssembly().
bool CartridgesContainer::existsCartAssembly (int port) const
Definition at line 159 of file CartridgesContainer.cpp.
References carts_mp.
Referenced by clearObserving(), deleteCartridge(), print(), and setObserving().
bool CartridgesContainer::existsColdCart (int port) const
Definition at line 165 of file CartridgesContainer.cpp.
References carts_mp.
bool CartridgesContainer::existsWCA (int port) const
Definition at line 173 of file CartridgesContainer.cpp.
References carts_mp.
CartAssembly * CartridgesContainer::getCartAssembly (int port)
Definition at line 181 of file CartridgesContainer.cpp.
References carts_mp.
Referenced by startMonitor().
const CartAssembly * CartridgesContainer::getCartAssembly (int port) const
Definition at line 185 of file CartridgesContainer.cpp.
References carts_mp.
const ColdCartImpl * CartridgesContainer::getColdCart (int port) const
Definition at line 189 of file CartridgesContainer.cpp.
References carts_mp.
bool CartridgesContainer::getEnable (int port) const
Definition at line 278 of file CartridgesContainer.cpp.
References carts_mp.
Referenced by clearEnable(), measureSISVoltageError(), setEnable(), and setObserving().
int CartridgesContainer::getObserving () const inline
Definition at line 64 of file CartridgesContainer.h.
References observingPort_m.
const WCAImpl * CartridgesContainer::getWCA (int port) const
Definition at line 197 of file CartridgesContainer.cpp.
References carts_mp.
void CartridgesContainer::measureSISVoltageError (int port)
Definition at line 153 of file CartridgesContainer.cpp.
References carts_mp, and getEnable().
bool CartridgesContainer::pauseMonitor (int port, bool pauseWCA, bool pauseCC)
Definition at line 223 of file CartridgesContainer.cpp.
References carts_mp.
void CartridgesContainer::print (const std::string & callerName, int port = -1) const
Definition at line 286 of file CartridgesContainer.cpp.
References carts_mp, existsCartAssembly(), numEnabled_m, and observingPort_m.
Referenced by addCartridge(), clearEnable(), clearObserving(), reset(), setEnable(), and setObserving().
void CartridgesContainer::queryCartridgeState ()
Definition at line 144 of file CartridgesContainer.cpp.
References carts_mp.
void CartridgesContainer::reset ()
Definition at line 83 of file CartridgesContainer.cpp.
References carts_mp, numEnabled_m, observingPort_m, and print().
Referenced by ~CartridgesContainer().
bool CartridgesContainer::setEnable (int port)
Definition at line 252 of file CartridgesContainer.cpp.
References carts_mp, getEnable(), numEnabled_m, and print().
bool CartridgesContainer::setObserving (int port)
Definition at line 232 of file CartridgesContainer.cpp.
References carts_mp, clearObserving(), existsCartAssembly(), getEnable(), observingPort_m, and print().
void CartridgesContainer::startMonitor ()
Definition at line 205 of file CartridgesContainer.cpp.
References getCartAssembly().
void CartridgesContainer::stopMonitor ()
Definition at line 214 of file CartridgesContainer.cpp.
References carts_mp.
Member Data Documentation
Impl* CartridgesContainer::carts_mp private
Definition at line 79 of file CartridgesContainer.h.
Referenced by addCartridge(), appendThermalLog(), clearEnable(), clearObserving(), deleteCartridge(), existsCartAssembly(), existsColdCart(), existsWCA(), getCartAssembly(), getColdCart(), getEnable(), getWCA(), measureSISVoltageError(), pauseMonitor(), print(), queryCartridgeState(), reset(), setEnable(), setObserving(), stopMonitor(), and ~CartridgesContainer().
int CartridgesContainer::numEnabled_m private
Definition at line 81 of file CartridgesContainer.h.
Referenced by clearEnable(), print(), reset(), and setEnable().
int CartridgesContainer::observingPort_m private
Definition at line 82 of file CartridgesContainer.h.
Referenced by clearEnable(), clearObserving(), getObserving(), print(), reset(), and setObserving().
The documentation for this class was generated from the following files:
CartridgesContainer.h
CartridgesContainer.cpp