FrontEndControl2: CartHealthCheck Class Reference
CartHealthCheck Class Reference
#include <CartHealthCheck.h>
Public Member Functions
CartHealthCheck (FrontEndDatabase &dbObject, CartAssembly &ca, XYPlotArray &ivData)
virtual ~CartHealthCheck ()
void reset ()
reset all state to initial/just constructed.
bool prepare (const FEICDataBase::ID_T &feConfig, FEICDataBase::DATASTATUS_TYPES dataStatus, double &freqLOret, bool receiverIsCold, int warmUpTimeSeconds)
how long to wait before taking health check data
bool start ()
wait the specified warmUpTimeSeconds start the health check measurements.
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
virtual void requestStop ()
main thread can call this to request worker thread to stop.
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
virtual void optimizeAction ()
worker thread method to take the measurements.
virtual void exitAction (bool success)
gets called just prior to the thread exiting.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Private Attributes
FrontEndDatabase & dbObject_m
database interface for saving results.
CartAssembly & ca_m
CartAssembly to healthCheck.
XYPlotArray & ivData_m
output data array for I-V curves
FEICDataBase::ID_T feConfig_m
configuration ID for the front end
FEICDataBase::DATASTATUS_TYPES dataStatus_m
data status for saving results
bool receiverIsCold_m
true if receiver is cold
int warmUpTimeSeconds_m
how long to wait before taking health check data
double freqLO_m
LO frequency for cartridge operation.
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 32 of file CartHealthCheck.h.
Constructor & Destructor Documentation
CartHealthCheck::CartHealthCheck (FrontEndDatabase & dbObject, CartAssembly & ca, XYPlotArray & ivData) inline
Parameters
dbObject database interface for saving results
ca CartAssembly to healthCheck
ivData output data array for I-V curves
Definition at line 34 of file CartHealthCheck.h.
References reset().
virtual CartHealthCheck::~CartHealthCheck () inline virtual
Definition at line 43 of file CartHealthCheck.h.
Member Function Documentation
void CartHealthCheck::exitAction (bool success) protected virtual
gets called just prior to the thread exiting.
Reimplemented from OptimizeBase.
Definition at line 584 of file CartHealthCheck.cpp.
References FEMCEventQueue::EVENT_CARTHC_DONE.
void CartHealthCheck::optimizeAction () protected virtual
worker thread method to take the measurements.
Implements OptimizeBase.
Definition at line 288 of file CartHealthCheck.cpp.
References FEMCEventQueue::addStatusMessage(), WCAImpl::AMC_t::amcDrainACurrent_value, WCAImpl::AMC_t::amcDrainAVoltage_value, WCAImpl::AMC_t::amcDrainBCurrent_value, WCAImpl::AMC_t::amcDrainBVoltage_value, WCAImpl::AMC_t::amcDrainECurrent_value, WCAImpl::AMC_t::amcDrainEVoltage_value, WCAImpl::AMC_t::amcGateAVoltage_value, WCAImpl::AMC_t::amcGateBVoltage_value, WCAImpl::AMC_t::amcGateEVoltage_value, WCAImpl::AMC_t::amcMultiplierDCurrent_value, WCAImpl::AMC_t::amcMultiplierDVoltage_value, WCAImpl::AMC_t::amcSupplyVoltage5V_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature0_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature1_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature2_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature3_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature4_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature5_value, ColdCartImpl::hasSb2(), ColdCartImpl::LNA_t::lnaSt1DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt1DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt1GateVoltage_value, ColdCartImpl::LNA_t::lnaSt2DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt2DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt2GateVoltage_value, ColdCartImpl::LNA_t::lnaSt3DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt3DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt3GateVoltage_value, WCAImpl::PA_t::paPol0DrainCurrent_value, WCAImpl::PA_t::paPol0DrainVoltage_value, WCAImpl::PA_t::paPol0GateVoltage_value, WCAImpl::PA_t::paPol1DrainCurrent_value, WCAImpl::PA_t::paPol1DrainVoltage_value, WCAImpl::PA_t::paPol1GateVoltage_value, WCAImpl::PA_t::paSupplyVoltage3V_value, WCAImpl::PA_t::paSupplyVoltage5V_value, FEHardwareDevice::pauseMonitor(), WCAImpl::Photomixer_t::photomixerCurrent_value, WCAImpl::Photomixer_t::photomixerVoltage_value, WCAImpl::PLL_t::pllAssemblyTemp_value, WCAImpl::PLL_t::pllRefTotalPower_value, WCAImpl::PLL_t::pllYTOHeaterCurrent_value, ColdCartImpl::SIS_t::sisCurrent_value, ColdCartImpl::SIS_t::sisMagnetCurrent_value, ColdCartImpl::SIS_t::sisMagnetVoltage_value, and ColdCartImpl::SIS_t::sisVoltage_value.
bool CartHealthCheck::prepare (const FEICDataBase::ID_T & feConfig, FEICDataBase::DATASTATUS_TYPES dataStatus, double & freqLOret, bool receiverIsCold, int warmUpTimeSeconds)
how long to wait before taking health check data
set up the cartridge for performing the health check. Returns the cartridge LO frequency in reference parameter freqLOret.
Parameters
feConfig front end configuration ID for saving results
dataStatus data status for saving results
freqLOret LO frequency for the cartridge is returned here.
receiverIsCold true if the receiver is cold
Definition at line 41 of file CartHealthCheck.cpp.
References FEConfig::ParamTable::begin(), FEConfig::ParamTable::end(), FEConfig::ParamTableRow::fPrecision_m, FEConfig::ParamTable::freqPrecision_m, FEConfig::ParamTable::freqWidth_m, FEConfig::ParamTableRow::fWidth_m, FEConfig::ParamTable::get(), FEConfig::ColdCartConfig::getPreampParams(), ColdCartImpl::hasSb2(), FEConfig::ColdCartConfig::magnetParams_m, FEConfig::ColdCartConfig::mixerParams_m, and FEConfig::WCAConfig::PAParams_m.
void CartHealthCheck::reset ()
reset all state to initial/just constructed.
Definition at line 32 of file CartHealthCheck.cpp.
Referenced by CartHealthCheck().
bool CartHealthCheck::start ()
wait the specified warmUpTimeSeconds start the health check measurements.
executes on worker thread.
Definition at line 283 of file CartHealthCheck.cpp.
References OptimizeBase::startWorkerThread().
Member Data Documentation
CartAssembly& CartHealthCheck::ca_m private
CartAssembly to healthCheck.
Definition at line 69 of file CartHealthCheck.h.
FEICDataBase::DATASTATUS_TYPES CartHealthCheck::dataStatus_m private
data status for saving results
Definition at line 73 of file CartHealthCheck.h.
FrontEndDatabase& CartHealthCheck::dbObject_m private
database interface for saving results.
Definition at line 68 of file CartHealthCheck.h.
FEICDataBase::ID_T CartHealthCheck::feConfig_m private
configuration ID for the front end
Definition at line 72 of file CartHealthCheck.h.
double CartHealthCheck::freqLO_m private
LO frequency for cartridge operation.
Definition at line 76 of file CartHealthCheck.h.
XYPlotArray& CartHealthCheck::ivData_m private
output data array for I-V curves
Definition at line 70 of file CartHealthCheck.h.
bool CartHealthCheck::receiverIsCold_m private
true if receiver is cold
Definition at line 74 of file CartHealthCheck.h.
int CartHealthCheck::warmUpTimeSeconds_m private
how long to wait before taking health check data
Definition at line 75 of file CartHealthCheck.h.
The documentation for this class was generated from the following files:
OPTIMIZE/CartHealthCheck.h
OPTIMIZE/CartHealthCheck.cpp