FrontEndControl2: OptimizeBase Class Reference
OptimizeBase Class Reference abstract
#include <OptimizeBase.h>
Classes
struct optimizeData
Data structure shared between the main thread and the worker thread: worker accesses it through owner->data_m or via helper functions.
Public Member Functions
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
virtual void requestStop ()
main thread can call this to request worker thread to stop.
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
virtual void optimizeAction ()=0
derived classes must declare an optimizeAction method for the worker thread to call.
virtual void exitAction (bool success)
derived classes may declare an exitAction which gets called just prior to the thread exiting.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Protected Attributes
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Private Member Functions
OptimizeBase (const OptimizeBase &other)
forbid copy constructor
OptimizeBase & operator= (const OptimizeBase &other)
forbid assignment
bool stopWorkerThread ()
force the worker thread to stop. Only called from destructor so private.
Static Private Member Functions
static void * optimizeThread (OptimizeBase *owner)
the worker thread runner function. Calls derived class' optimizeAction().
Private Attributes
std::string name_m
the name of this OptimizeBase object.
pthread_t thread_m
the worker thread handle.
Detailed Description
Definition at line 30 of file OptimizeBase.h.
Constructor & Destructor Documentation
OptimizeBase::OptimizeBase (const char * name = "")
construct with an object name to use for logging
Definition at line 26 of file OptimizeBase.cpp.
OptimizeBase::~OptimizeBase () virtual
destructor forces worker thread to stop.
Definition at line 31 of file OptimizeBase.cpp.
References stopWorkerThread().
OptimizeBase::OptimizeBase (const OptimizeBase & other) private
forbid copy constructor
Member Function Documentation
bool OptimizeBase::busy () const inline
true if the thread was started and it has not finished or or been stopped.
Definition at line 38 of file OptimizeBase.h.
References data_m, and OptimizeBase::optimizeData::start_m.
virtual void OptimizeBase::exitAction (bool success) inline protected virtual
derived classes may declare an exitAction which gets called just prior to the thread exiting.
whatever value is passed to setFinished(bool) by optimizeAction() is passed in here as success.
Reimplemented in MaximizeIFPower, MeasureIFPower, CartHealthCheck, MeasureFineLOSweep, ThermalLogger, and MeasureIVCurve.
Definition at line 86 of file OptimizeBase.h.
Referenced by optimizeThread().
bool OptimizeBase::finished () const
true if setFinished() has been called by the derived class' optimizeAction()
Definition at line 35 of file OptimizeBase.cpp.
References data_m, OptimizeBase::optimizeData::finished_m, and OptimizeBase::optimizeData::lock_m.
Referenced by optimizeThread().
OptimizeBase& OptimizeBase::operator= (const OptimizeBase & other) private
forbid assignment
virtual void OptimizeBase::optimizeAction () protected pure virtual
derived classes must declare an optimizeAction method for the worker thread to call.
Implemented in MaximizeIFPower, MeasureIFPower, CartHealthCheck, MeasureFineLOSweep, MixerHeating, ThermalLogger, MixerDeflux, OptimizeLOPowerAmp, MeasureIVCurve, CryostatPumping, and MeasureSISCurrent.
Referenced by optimizeThread().
void * OptimizeBase::optimizeThread (OptimizeBase * owner) static private
the worker thread runner function. Calls derived class' optimizeAction().
Definition at line 91 of file OptimizeBase.cpp.
References data_m, exitAction(), finished(), OptimizeBase::optimizeData::lock_m, name_m, optimizeAction(), OptimizeBase::optimizeData::stop_m, OptimizeBase::optimizeData::stopped_m, and success().
Referenced by startWorkerThread().
void OptimizeBase::requestStop () virtual
main thread can call this to request worker thread to stop.
Reimplemented in MaximizeIFPower, MixerHeating, and MeasureIVCurve.
Definition at line 49 of file OptimizeBase.cpp.
References data_m, and OptimizeBase::optimizeData::stop_m.
Referenced by MeasureIVCurve::requestStop(), MixerHeating::requestStop(), and MaximizeIFPower::requestStop().
void OptimizeBase::setEvent (short eventCode, short band = 0, short pol = -1, short param = 0, short progress = 0, const std::string & message = std::string()) inline protected
send an event to the client via the FEMCEventQueue.
Definition at line 96 of file OptimizeBase.h.
References FEMCEventQueue::addEvent().
Referenced by setProgress().
void OptimizeBase::setFinished (bool success = true) protected
derived class calls to report that the optimization procedure is finished.
Definition at line 64 of file OptimizeBase.cpp.
References data_m, OptimizeBase::optimizeData::finished_m, OptimizeBase::optimizeData::lock_m, OptimizeBase::optimizeData::start_m, success(), and OptimizeBase::optimizeData::success_m.
void OptimizeBase::setProgress (short progress) inline protected
helper for reporting progress.
Definition at line 109 of file OptimizeBase.h.
References FEMCEventQueue::EVENT_PROGRESS, and setEvent().
void OptimizeBase::setStatusMessage (bool success, const std::string & message) inline protected
send a status message event to the client via FEMCEventQueue
Definition at line 105 of file OptimizeBase.h.
References FEMCEventQueue::addStatusMessage().
bool OptimizeBase::startWorkerThread () protected
start the worker thread. Call from derived class after all preconditions are set.
Definition at line 55 of file OptimizeBase.cpp.
References data_m, name_m, optimizeThread(), OptimizeBase::optimizeData::reset(), OptimizeBase::optimizeData::start_m, and thread_m.
Referenced by CryostatPumping::start(), OptimizeLOPowerAmp::start(), MixerHeating::start(), MeasureSISCurrent::start(), MeasureIVCurve::start(), ThermalLogger::start(), MixerDeflux::start(), MaximizeIFPower::start(), MeasureFineLOSweep::start(), CartHealthCheck::start(), MeasureIFPower::startVsVD(), and MeasureIFPower::startVsVJ().
bool OptimizeBase::stopRequested () const inline
main or worker thread can use this to check whether the thread has been told to stop.
Definition at line 51 of file OptimizeBase.h.
References data_m, and OptimizeBase::optimizeData::stop_m.
bool OptimizeBase::stopWorkerThread () private
force the worker thread to stop. Only called from destructor so private.
Definition at line 72 of file OptimizeBase.cpp.
References data_m, name_m, OptimizeBase::optimizeData::reset(), OptimizeBase::optimizeData::start_m, OptimizeBase::optimizeData::stop_m, and OptimizeBase::optimizeData::stopped_m.
Referenced by ~OptimizeBase().
bool OptimizeBase::success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
Definition at line 42 of file OptimizeBase.cpp.
References data_m, OptimizeBase::optimizeData::lock_m, and OptimizeBase::optimizeData::success_m.
Referenced by optimizeThread(), and setFinished().
Member Data Documentation
struct OptimizeBase::optimizeData OptimizeBase::data_m protected
single instance of shared data structure.
Referenced by busy(), finished(), optimizeThread(), requestStop(), setFinished(), startWorkerThread(), stopRequested(), stopWorkerThread(), and success().
const std::string& OptimizeBase::logDir_m protected
directory to use for logs and results files.
Definition at line 56 of file OptimizeBase.h.
std::string OptimizeBase::name_m private
the name of this OptimizeBase object.
Definition at line 120 of file OptimizeBase.h.
Referenced by optimizeThread(), startWorkerThread(), and stopWorkerThread().
pthread_t OptimizeBase::thread_m private
the worker thread handle.
Definition at line 122 of file OptimizeBase.h.
Referenced by startWorkerThread().
The documentation for this class was generated from the following files:
OPTIMIZE/OptimizeBase.h
OPTIMIZE/OptimizeBase.cpp