FrontEndControl2: AMBSIHardwareDevice Class Reference
AMBSIHardwareDevice Class Reference
#include <AMBSIHardwareDevice.h>
Public Member Functions
AMBSIHardwareDevice (const std::string &name)
virtual ~AMBSIHardwareDevice ()
virtual std::string AMBSISerialNum ()
virtual std::string AMBSIFirmwareRev ()
virtual unsigned long AMBSINumErrors ()
virtual unsigned long AMBSINumTransactions ()
virtual float AMBSITemperature ()
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Protected Types
enum MonitorControlOffset {
AMBSI_BASE = 0x30000UL, AMBSI_SERIAL_NUMBER = 0x0000, AMBSI_FIRMWARE_REV = 0x0000, AMBSI_NUM_ERRORS = 0x0001,
AMBSI_NUM_TRANSACTIONS = 0x0002, AMBSI_TEMPERATURE = 0x0003
}
Protected Attributes
std::string AMBSISerialNum_value
std::string AMBSIFirmwareRev_value
unsigned long AMBSINumErrors_value
unsigned long AMBSINumTransactions_value
float AMBSITemperature_value
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
AMBSIHardwareDevice (const AMBSIHardwareDevice &other)
forbid copy constructor
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
virtual void monitorAction (Time *timestamp_p)=0
derived classes must declare a monitorAction method for the monitor thread to call.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 33 of file AMBSIHardwareDevice.h.
Member Enumeration Documentation
enum AMBSIHardwareDevice::MonitorControlOffset protected
Enumerator
AMBSI_BASE
AMBSI_SERIAL_NUMBER
AMBSI_FIRMWARE_REV
AMBSI_NUM_ERRORS
AMBSI_NUM_TRANSACTIONS
AMBSI_TEMPERATURE
Definition at line 47 of file AMBSIHardwareDevice.h.
Constructor & Destructor Documentation
AMBSIHardwareDevice::AMBSIHardwareDevice (const std::string & name)
Definition at line 33 of file AMBSIHardwareDevice.cpp.
virtual AMBSIHardwareDevice::~AMBSIHardwareDevice () inline virtual
Definition at line 36 of file AMBSIHardwareDevice.h.
AMBSIHardwareDevice::AMBSIHardwareDevice (const AMBSIHardwareDevice & other) private
forbid copy constructor
Member Function Documentation
std::string AMBSIHardwareDevice::AMBSIFirmwareRev () virtual
Definition at line 46 of file AMBSIHardwareDevice.cpp.
References AMBSI_BASE, AMBSI_FIRMWARE_REV, AMBSIFirmwareRev_value, and FEHardwareDevice::syncMonitorThreeByteRevLevel().
Referenced by SignalSourceImpl::initialize(), and FrontEndImpl::specialGetSetupInfo().
unsigned long AMBSIHardwareDevice::AMBSINumErrors () virtual
Definition at line 51 of file AMBSIHardwareDevice.cpp.
References AMBSI_BASE, AMBSI_NUM_ERRORS, AMBSINumErrors_value, and FEHardwareDevice::unpack().
Referenced by FrontEndImplBase::monitorAction().
unsigned long AMBSIHardwareDevice::AMBSINumTransactions () virtual
Definition at line 68 of file AMBSIHardwareDevice.cpp.
References AMBSI_BASE, AMBSI_NUM_TRANSACTIONS, AMBSINumTransactions_value, and FEHardwareDevice::unpack().
Referenced by FrontEndImplBase::monitorAction().
std::string AMBSIHardwareDevice::AMBSISerialNum () virtual
Definition at line 41 of file AMBSIHardwareDevice.cpp.
References AMBSI_SERIAL_NUMBER, AMBSISerialNum_value, and FEHardwareDevice::syncMonitorEightByteESN().
Referenced by SignalSourceImpl::initialize(), FrontEndImpl::initialize(), FrontEndImpl::specialGetSetupInfo(), and FrontEndImpl::startHealthCheck().
float AMBSIHardwareDevice::AMBSITemperature () virtual
Definition at line 85 of file AMBSIHardwareDevice.cpp.
References AMBSI_BASE, AMBSI_TEMPERATURE, AMBSITemperature_value, FEHardwareDevice::FEMC_NO_ERROR, and FEHardwareDevice::FEMC_UNPACK_ERROR.
Referenced by FrontEndImplBase::monitorAction().
Member Data Documentation
std::string AMBSIHardwareDevice::AMBSIFirmwareRev_value protected
Definition at line 58 of file AMBSIHardwareDevice.h.
Referenced by AMBSIFirmwareRev(), SignalSourceImpl::getAMBSIInfo(), and FrontEndImpl::getAMBSIInfo().
unsigned long AMBSIHardwareDevice::AMBSINumErrors_value protected
Definition at line 59 of file AMBSIHardwareDevice.h.
Referenced by AMBSINumErrors(), SignalSourceImpl::getAMBSIInfo(), and FrontEndImpl::getAMBSIInfo().
unsigned long AMBSIHardwareDevice::AMBSINumTransactions_value protected
Definition at line 60 of file AMBSIHardwareDevice.h.
Referenced by AMBSINumTransactions(), SignalSourceImpl::getAMBSIInfo(), and FrontEndImpl::getAMBSIInfo().
std::string AMBSIHardwareDevice::AMBSISerialNum_value protected
Definition at line 57 of file AMBSIHardwareDevice.h.
Referenced by AMBSISerialNum(), SignalSourceImpl::getAMBSIInfo(), and FrontEndImpl::getAMBSIInfo().
float AMBSIHardwareDevice::AMBSITemperature_value protected
Definition at line 61 of file AMBSIHardwareDevice.h.
Referenced by AMBSITemperature(), SignalSourceImpl::getAMBSITemperature(), and FrontEndImpl::getAMBSITemperature().
The documentation for this class was generated from the following files:
FEBASE/AMBSIHardwareDevice.h
FEBASE/AMBSIHardwareDevice.cpp