FrontEndControl2: FEConfig::MixerParams Class Reference
FEConfig::MixerParams Class Reference
lookup table for SIS mixer voltage and current vs LO frequency
#include <LookupTables.h>
Public Types
enum PARAM_COLS {
VJ01 = 0, VJ02, VJ11, VJ12,
IJ01, IJ02, IJ11, IJ12,
NUM_COLS
}
define parameter names for use with this ParamTable
Public Types inherited from FEConfig::ParamTable
typedef base_type::iterator iterator
declare iterator types
typedef base_type::const_iterator const_iterator
Public Member Functions
MixerParams ()
constructor fixes the number of data columns at NUM_COLS.
~MixerParams ()
void streamOut (std::ostream &out) const
stream output for debugging
Public Member Functions inherited from FEConfig::ParamTable
ParamTable (unsigned numCols, double minInterpolateInterval=0.0)
construct with the number of columns to hold, not including the 'freq' col.
virtual ~ParamTable ()
void reset (unsigned numCols)
discard all contents and resize the number of columns.
void clear ()
discard all contents, keeping the same number of columns.
bool set (const double &freq, unsigned col, float value)
set a value at a given 'freq' and 'col'.
float get (const double &freq, unsigned col, bool interpolate=true) const
get a value at a given 'freq' and col.
bool get (const double &freq, ParamTableRow &target, bool interpolate=true) const
get a row of values corresponding to 'freq'.
bool get (const_iterator &it, double &freq, ParamTableRow &target) const
get the row of values at location 'it'.
const const_iterator begin () const
expose map's const iterator access methods.
const const_iterator end () const
expose map's const iterator access methods.
void streamOut (std::ostream &out) const
stream output for debugging
Static Public Member Functions
static void normalizePolSb (unsigned &pol, unsigned &sb)
utility function to force pol and sb into range.
static PARAM_COLS indexVJ (unsigned pol, unsigned sb)
get the parameter name for VJ at the given pol and sb.
static PARAM_COLS indexIJ (unsigned pol, unsigned sb)
get the parameter name for IJ at the given pol and sb.
Additional Inherited Members
Public Attributes inherited from FEConfig::ParamTable
int freqWidth_m
field width for streaming double frequencies in GHz.
int freqPrecision_m
precision for streaming double frequencies in GHz.
Protected Attributes inherited from FEConfig::ParamTable
unsigned numCols_m
holds a fixed number of columns, not including the freq col.
double minInterpolateInterval_m
when interpolating, if the difference between adjacent frequencies is smaller than this, don't interpolate. Instead pick the nearest value.
Detailed Description
lookup table for SIS mixer voltage and current vs LO frequency
Definition at line 182 of file LookupTables.h.
Member Enumeration Documentation
enum FEConfig::MixerParams::PARAM_COLS
define parameter names for use with this ParamTable
Enumerator
VJ01
SIS junction voltage for pol0 sb1.
VJ02
VJ11
VJ12
IJ01
SIS junction current for pol0 sb1.
IJ02
IJ11
IJ12
NUM_COLS
Definition at line 185 of file LookupTables.h.
Constructor & Destructor Documentation
FEConfig::MixerParams::MixerParams () inline
constructor fixes the number of data columns at NUM_COLS.
Minimum interpolation interval is 1 kHz.
Definition at line 197 of file LookupTables.h.
References FEConfig::ParamTable::freqPrecision_m, and FEConfig::ParamTable::minInterpolateInterval_m.
FEConfig::MixerParams::~MixerParams () inline
Definition at line 203 of file LookupTables.h.
Member Function Documentation
static PARAM_COLS FEConfig::MixerParams::indexIJ (unsigned pol, unsigned sb) inline static
get the parameter name for IJ at the given pol and sb.
Definition at line 217 of file LookupTables.h.
References IJ01, and normalizePolSb().
static PARAM_COLS FEConfig::MixerParams::indexVJ (unsigned pol, unsigned sb) inline static
get the parameter name for VJ at the given pol and sb.
Definition at line 212 of file LookupTables.h.
References normalizePolSb().
static void FEConfig::MixerParams::normalizePolSb (unsigned & pol, unsigned & sb) inline static
utility function to force pol and sb into range.
Definition at line 206 of file LookupTables.h.
Referenced by indexIJ(), FEConfig::MagnetParams::indexIMag(), indexVJ(), and FEConfig::ColdCartConfig::usePreampParams().
void FEConfig::MixerParams::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 142 of file LookupTables.cpp.
Referenced by FEConfig::operator<<().
The documentation for this class was generated from the following files:
CONFIG/LookupTables.h
CONFIG/LookupTables.cpp