FrontEndControl2: Maximizer Class Reference
Maximizer Class Reference abstract
#include <Maximizer.h>
Public Member Functions
Maximizer ()
virtual ~Maximizer ()
virtual void reset ()
reset all internal state to as if just constructed.
bool maximize (float &controlStart, float controlStep, float controlMin, float controlMax, bool directionUp, int maxIter, int timeOut, int interval)
perform a maximization of the dependent variable by varying the control variable.
void stopMaximizer ()
abort the process.
Protected Member Functions
void setDependentValue (float depVal)
Set the dependent value after one was requested via requestDependentValue().
virtual bool setControlValue (float control)=0
Derived class must implement.
virtual bool requestDependentValue (float &depVal)=0
Derived class must implement.
bool waitForDependentValue (float &depVal, int timeOut, int interval=20)
Wait up to timeOut ms for a fresh dependent value to be provided.
Private Types
enum searchCases {
CASE_error, CASE_a1, CASE_a2, CASE_b1,
CASE_b2, CASE_c1, CASE_c2
}
Private Member Functions
bool getDependentValue (float &depVal)
Helper function to synchronize maximize() access to the latest dependent value.
bool controlRangeCheck (const float &control) const
Check that the control value is within range.
Private Attributes
float controlMin_m
minimum allowed value for the control variable.
float controlMax_m
maximum allowed value for the control variable.
pthread_mutex_t lock_m
lock sychronizes access to the dependent value inputs below.
float depVal_m
the latest dependent value set.
bool depValReady_m
true if maximize() can unblock and read the latest value.
bool stop_m
Detailed Description
Definition at line 25 of file Maximizer.h.
Member Enumeration Documentation
enum Maximizer::searchCases private
Enumerator
CASE_error
CASE_a1
CASE_a2
CASE_b1
CASE_b2
CASE_c1
CASE_c2
Definition at line 82 of file Maximizer.h.
Constructor & Destructor Documentation
Maximizer::Maximizer () inline
Definition at line 27 of file Maximizer.h.
References lock_m, and reset().
virtual Maximizer::~Maximizer () inline virtual
Definition at line 31 of file Maximizer.h.
References lock_m.
Member Function Documentation
bool Maximizer::controlRangeCheck (const float & control) const inline private
Check that the control value is within range.
Definition at line 75 of file Maximizer.h.
References controlMax_m, and controlMin_m.
bool Maximizer::getDependentValue (float & depVal) private
Helper function to synchronize maximize() access to the latest dependent value.
Definition at line 502 of file Maximizer.cpp.
bool Maximizer::maximize (float & controlStart, float controlStep, float controlMin, float controlMax, bool directionUp, int maxIter, int timeOut, int interval)
perform a maximization of the dependent variable by varying the control variable.
Iterates up to maxIter times. Returns true if maximum found. The control value where the maximum was found is returned in controlStart. Returns false if there is an error setting the control variable via setControlValue(). Returns false if too many iterations or too much elapsed time. timeOut specified in ms. The interval specifies how long to wait between attempts after requesting a dependent value.
Definition at line 36 of file Maximizer.cpp.
Referenced by MaximizeIFPower::performPhase().
virtual bool Maximizer::requestDependentValue (float & depVal) protected pure virtual
Derived class must implement.
Called by the maximizer to request the value of the dependent variable. Implementation may provide a result right away and return true or return false and provide a value later using setDependentValue().
Implemented in MaximizeIFPower.
void Maximizer::reset () virtual
reset all internal state to as if just constructed.
Reimplemented in MaximizeIFPower.
Definition at line 27 of file Maximizer.cpp.
Referenced by Maximizer(), and MaximizeIFPower::reset().
virtual bool Maximizer::setControlValue (float control) protected pure virtual
Derived class must implement.
Called by the maximizer to set the independent control variable. If implementation returns false, the maximize function returns false.
Implemented in MaximizeIFPower.
void Maximizer::setDependentValue (float depVal) protected
Set the dependent value after one was requested via requestDependentValue().
Definition at line 495 of file Maximizer.cpp.
Referenced by MaximizeIFPower::setIFPower().
void Maximizer::stopMaximizer () inline
abort the process.
Definition at line 48 of file Maximizer.h.
References stop_m.
bool Maximizer::waitForDependentValue (float & depVal, int timeOut, int interval = 20) protected
Wait up to timeOut ms for a fresh dependent value to be provided.
pause interval ms between attempts. returns false if error or timeout.
Definition at line 515 of file Maximizer.cpp.
Referenced by MaximizeIFPower::optimizeSinglePol().
Member Data Documentation
float Maximizer::controlMax_m private
maximum allowed value for the control variable.
Definition at line 80 of file Maximizer.h.
Referenced by controlRangeCheck().
float Maximizer::controlMin_m private
minimum allowed value for the control variable.
Definition at line 79 of file Maximizer.h.
Referenced by controlRangeCheck().
float Maximizer::depVal_m private
the latest dependent value set.
Definition at line 93 of file Maximizer.h.
bool Maximizer::depValReady_m private
true if maximize() can unblock and read the latest value.
Definition at line 94 of file Maximizer.h.
pthread_mutex_t Maximizer::lock_m private
lock sychronizes access to the dependent value inputs below.
Definition at line 92 of file Maximizer.h.
Referenced by Maximizer(), and ~Maximizer().
bool Maximizer::stop_m private
Definition at line 95 of file Maximizer.h.
Referenced by stopMaximizer().
The documentation for this class was generated from the following files:
OPTIMIZE/Maximizer.h
OPTIMIZE/Maximizer.cpp