FrontEndControl2: MeasureIFPower Class Reference
MeasureIFPower Class Reference
#include <MeasureIFPower.h>
Public Member Functions
MeasureIFPower (ColdCartImpl &ColdCart, WCAImpl &WCA, XYPlotArray &target)
virtual ~MeasureIFPower ()
void reset ()
reset all state to initial/just constructed.
bool startVsVJ (int pol, int sb, const std::string &description, float VJStart, float VJStop, float VJStep, bool doYFactor, int repeatCount=1)
start a measurment of IF Power vs SIS junction voltage.
bool startVsVD (int pol, const std::string &description, float VDStart, float VDStop, float VDStep, bool doYFactor, int repeatCount=1)
start a measurment of IF Power vs LO PA drain voltage.
bool setIFPower (int pol, float powerSb1, float powerSb2)
called by main thread to feed IF power readings into the optimization process.
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
virtual void requestStop ()
main thread can call this to request worker thread to stop.
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
virtual void optimizeAction ()
worker thread calls this function repeatedly until done.
virtual void exitAction (bool success)
called by OptimizeBase prior to worker thread exit.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Private Types
enum { MODE_NONE, MODE_VJ, MODE_VD }
Private Member Functions
void readData (bool printHeader=false)
Private Attributes
ColdCartImpl & coldCart_m
the cold cartridge to operate
WCAImpl & WCA_m
the WCA to operate.
enum MeasureIFPower:: { ... } mode_m
which type of measurement is being performed.
int pol_m
Polarization to measure.
int sb_m
Sideband (1,2) to vary voltage on. -1 means do both.
bool b6SweepMode_m
For band 6 sweep SIS1 voltage to the negative of the polarity of SIS2.
float VJNom1_m
SIS1 voltage prior to starting measurement.
float VJNom2_m
SIS2 voltage prior to starting measurement.
float VDNom_m
PA drain voltage prior to starting measurement.
float VStart_m
One end of range for parameter to sweep.
float VStop_m
Other end of range for parameter to sweep.
float VStep_m
Step size for parameter to sweep.
float V_m
Current value of parameter to sweep.
float powerSb1_m
most recent SB1 power level
float powerSb2_m
most recent SB2 power level
bool doYFactor_m
if true measure with both the hot and cold load and compute Y factor.
int repeatCount_m
how many times to repeat the measurement.
int iter_m
which repetition is currently running.
bool coldHot_m
which chopper position is currently measuring. false=cold.
int noReadingCount_m
This increments while waiting for power meter readings.
bool waitForPowerReading_m
True if we are waiting for the next power meter readings.
float progress_m
progress bar value.
float progressIncrement_m
how much to increment the progress bar at each step.
XYPlotArray yFactorData_m
place to cache pCold values when measuring Y-factor
int dataIndex_m
current index into the yFactorData array.
XYPlotArray & data_m
the output data array
std::ostream * dataFile_mp
the output log file.
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 32 of file MeasureIFPower.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
MODE_NONE
MODE_VJ
MODE_VD
Definition at line 73 of file MeasureIFPower.h.
Constructor & Destructor Documentation
MeasureIFPower::MeasureIFPower (ColdCartImpl & ColdCart, WCAImpl & WCA, XYPlotArray & target) inline
Definition at line 34 of file MeasureIFPower.h.
References reset().
virtual MeasureIFPower::~MeasureIFPower () inline virtual
Definition at line 42 of file MeasureIFPower.h.
References dataFile_mp.
Member Function Documentation
void MeasureIFPower::exitAction (bool success) protected virtual
called by OptimizeBase prior to worker thread exit.
Reimplemented from OptimizeBase.
Definition at line 369 of file MeasureIFPower.cpp.
References FEMCEventQueue::EVENT_CHOPPER_MOVE, FEMCEventQueue::EVENT_OPTIMIZE_DONE, and FEMCEventQueue::EVENT_STOP_IFPOWER.
void MeasureIFPower::optimizeAction () protected virtual
worker thread calls this function repeatedly until done.
Implements OptimizeBase.
Definition at line 285 of file MeasureIFPower.cpp.
References FEMCEventQueue::EVENT_CHOPPER_MOVE.
void MeasureIFPower::readData (bool printHeader = false) private
Definition at line 407 of file MeasureIFPower.cpp.
void MeasureIFPower::reset ()
reset all state to initial/just constructed.
Definition at line 31 of file MeasureIFPower.cpp.
Referenced by MeasureIFPower().
bool MeasureIFPower::setIFPower (int pol, float powerSb1, float powerSb2)
called by main thread to feed IF power readings into the optimization process.
Definition at line 267 of file MeasureIFPower.cpp.
bool MeasureIFPower::startVsVD (int pol, const std::string & description, float VDStart, float VDStop, float VDStep, bool doYFactor, int repeatCount = 1)
start a measurment of IF Power vs LO PA drain voltage.
Definition at line 161 of file MeasureIFPower.cpp.
References FEMCEventQueue::EVENT_CHOPPER_MOVE, FEMCEventQueue::EVENT_REQUEST_IFPOWER, and OptimizeBase::startWorkerThread().
bool MeasureIFPower::startVsVJ (int pol, int sb, const std::string & description, float VJStart, float VJStop, float VJStep, bool doYFactor, int repeatCount = 1)
start a measurment of IF Power vs SIS junction voltage.
Definition at line 48 of file MeasureIFPower.cpp.
References FEMCEventQueue::EVENT_CHOPPER_MOVE, FEMCEventQueue::EVENT_REQUEST_IFPOWER, and OptimizeBase::startWorkerThread().
Member Data Documentation
bool MeasureIFPower::b6SweepMode_m private
For band 6 sweep SIS1 voltage to the negative of the polarity of SIS2.
Definition at line 77 of file MeasureIFPower.h.
ColdCartImpl& MeasureIFPower::coldCart_m private
the cold cartridge to operate
Definition at line 71 of file MeasureIFPower.h.
bool MeasureIFPower::coldHot_m private
which chopper position is currently measuring. false=cold.
Definition at line 90 of file MeasureIFPower.h.
XYPlotArray& MeasureIFPower::data_m private
the output data array
Definition at line 98 of file MeasureIFPower.h.
std::ostream* MeasureIFPower::dataFile_mp private
the output log file.
Definition at line 99 of file MeasureIFPower.h.
Referenced by ~MeasureIFPower().
int MeasureIFPower::dataIndex_m private
current index into the yFactorData array.
Definition at line 97 of file MeasureIFPower.h.
bool MeasureIFPower::doYFactor_m private
if true measure with both the hot and cold load and compute Y factor.
Definition at line 87 of file MeasureIFPower.h.
int MeasureIFPower::iter_m private
which repetition is currently running.
Definition at line 89 of file MeasureIFPower.h.
enum { ... } MeasureIFPower::mode_m
which type of measurement is being performed.
int MeasureIFPower::noReadingCount_m private
This increments while waiting for power meter readings.
If it reaches a large value the process is aborted.
Definition at line 91 of file MeasureIFPower.h.
int MeasureIFPower::pol_m private
Polarization to measure.
Definition at line 75 of file MeasureIFPower.h.
float MeasureIFPower::powerSb1_m private
most recent SB1 power level
Definition at line 85 of file MeasureIFPower.h.
float MeasureIFPower::powerSb2_m private
most recent SB2 power level
Definition at line 86 of file MeasureIFPower.h.
float MeasureIFPower::progress_m private
progress bar value.
Definition at line 94 of file MeasureIFPower.h.
float MeasureIFPower::progressIncrement_m private
how much to increment the progress bar at each step.
Definition at line 95 of file MeasureIFPower.h.
int MeasureIFPower::repeatCount_m private
how many times to repeat the measurement.
Definition at line 88 of file MeasureIFPower.h.
int MeasureIFPower::sb_m private
Sideband (1,2) to vary voltage on. -1 means do both.
Definition at line 76 of file MeasureIFPower.h.
float MeasureIFPower::V_m private
Current value of parameter to sweep.
Definition at line 84 of file MeasureIFPower.h.
float MeasureIFPower::VDNom_m private
PA drain voltage prior to starting measurement.
Definition at line 80 of file MeasureIFPower.h.
float MeasureIFPower::VJNom1_m private
SIS1 voltage prior to starting measurement.
Definition at line 78 of file MeasureIFPower.h.
float MeasureIFPower::VJNom2_m private
SIS2 voltage prior to starting measurement.
Definition at line 79 of file MeasureIFPower.h.
float MeasureIFPower::VStart_m private
One end of range for parameter to sweep.
Definition at line 81 of file MeasureIFPower.h.
float MeasureIFPower::VStep_m private
Step size for parameter to sweep.
Definition at line 83 of file MeasureIFPower.h.
float MeasureIFPower::VStop_m private
Other end of range for parameter to sweep.
Definition at line 82 of file MeasureIFPower.h.
bool MeasureIFPower::waitForPowerReading_m private
True if we are waiting for the next power meter readings.
Definition at line 93 of file MeasureIFPower.h.
WCAImpl& MeasureIFPower::WCA_m private
the WCA to operate.
Definition at line 72 of file MeasureIFPower.h.
XYPlotArray MeasureIFPower::yFactorData_m private
place to cache pCold values when measuring Y-factor
Definition at line 96 of file MeasureIFPower.h.
The documentation for this class was generated from the following files:
OPTIMIZE/MeasureIFPower.h
OPTIMIZE/MeasureIFPower.cpp