FrontEndControl2: FrontEndImplBase Class Reference
FrontEndImplBase Class Reference
#include <FrontEndImplBase.h>
Public Member Functions
FrontEndImplBase (const std::string &name)
virtual ~FrontEndImplBase ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual std::string AMBSILibraryVersion ()
virtual std::string FEMCFirmwareVersion ()
virtual std::string FEMCFPGAVersion ()
virtual unsigned char FEMCGetESNsFound ()
virtual std::string FEMCGetNextESN (bool reverseBytes=false)
virtual unsigned char specialGetSetupInfo ()
virtual unsigned char numEnabledModules ()
virtual bool powerEnableModule (int port)
virtual unsigned short getNumErrors ()
virtual unsigned short getNextError ()
virtual unsigned char getFEMode ()
virtual void powerEnableModule (int port, bool val)
virtual void specialExitProgram (bool val)
virtual void specialReadESNs (bool val)
virtual void setFEMode (unsigned char val)
Public Member Functions inherited from AMBSIHardwareDevice
AMBSIHardwareDevice (const std::string &name)
virtual ~AMBSIHardwareDevice ()
virtual std::string AMBSISerialNum ()
virtual std::string AMBSIFirmwareRev ()
virtual unsigned long AMBSINumErrors ()
virtual unsigned long AMBSINumTransactions ()
virtual float AMBSITemperature ()
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Protected Types
enum MonitorControlOffset {
SPECIAL_MONITOR = 0x20000UL, SPECIAL_CONTROL = 0x21000UL, GET_AMBSI_VERSION_INFO = 0x0000, GET_SETUP_INFO = 0x0001,
GET_VERSION_INFO = 0x0002, GET_SPECIAL_MONITOR_RCA = 0x0003, GET_SPECIAL_CONTROL_RCA = 0x0004, GET_MONITOR_RCA = 0x0005,
GET_CONTROL_RCA = 0x0006, GET_PPCOMM_TIME = 0x0007, GET_FPGA_VERSION_INFO = 0x0008, GET_ESNS_FOUND = 0x000A,
GET_ESNS = 0x000B, GET_ERRORS_NUMBER = 0x000C, GET_NEXT_ERROR = 0x000D, GET_FE_MODE = 0x000E,
SET_EXIT_PROGRAM = 0x0000, SET_REBOOT = 0x0001, SET_FE_MODE = 0x000E, SET_READ_ESN = 0x000F,
POWER_NUM_MODULES_ENABLED = 0xA0A0, POWER_ENABLE_MODULE = 0xA00C
}
Protected Types inherited from AMBSIHardwareDevice
enum MonitorControlOffset {
AMBSI_BASE = 0x30000UL, AMBSI_SERIAL_NUMBER = 0x0000, AMBSI_FIRMWARE_REV = 0x0000, AMBSI_NUM_ERRORS = 0x0001,
AMBSI_NUM_TRANSACTIONS = 0x0002, AMBSI_TEMPERATURE = 0x0003
}
Protected Member Functions
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Protected Attributes
std::string AMBSILibraryVersion_value
std::string FEMCFirmwareVersion_value
std::string FEMCFPGAVersion_value
unsigned char FEMCGetESNsFound_value
std::string FEMCGetNextESN_value
unsigned char specialGetSetupInfo_value
unsigned char numEnabledModules_value
int numEnabledModules_status
unsigned short numErrors_value
int numErrors_status
unsigned short nextError_value
int nextError_status
unsigned char FEMode_value
int FEMode_status
AmbRelativeAddr numEnabledModules_RCA
AmbRelativeAddr powerEnableModule_RCA
AmbRelativeAddr numErrors_RCA
AmbRelativeAddr nextError_RCA
AmbRelativeAddr FEMode_RCA
Protected Attributes inherited from AMBSIHardwareDevice
std::string AMBSISerialNum_value
std::string AMBSIFirmwareRev_value
unsigned long AMBSINumErrors_value
unsigned long AMBSINumTransactions_value
float AMBSITemperature_value
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
FrontEndImplBase (const FrontEndImplBase &other)
Private Attributes
Time lastMonitorTime
int monitorPhase
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 32 of file FrontEndImplBase.h.
Member Enumeration Documentation
enum FrontEndImplBase::MonitorControlOffset protected
Enumerator
SPECIAL_MONITOR
SPECIAL_CONTROL
GET_AMBSI_VERSION_INFO
GET_SETUP_INFO
GET_VERSION_INFO
GET_SPECIAL_MONITOR_RCA
GET_SPECIAL_CONTROL_RCA
GET_MONITOR_RCA
GET_CONTROL_RCA
GET_PPCOMM_TIME
GET_FPGA_VERSION_INFO
GET_ESNS_FOUND
GET_ESNS
GET_ERRORS_NUMBER
GET_NEXT_ERROR
GET_FE_MODE
SET_EXIT_PROGRAM
SET_REBOOT
SET_FE_MODE
SET_READ_ESN
POWER_NUM_MODULES_ENABLED
POWER_ENABLE_MODULE
Definition at line 69 of file FrontEndImplBase.h.
Constructor & Destructor Documentation
FrontEndImplBase::FrontEndImplBase (const std::string & name)
Definition at line 34 of file FrontEndImplBase.cpp.
virtual FrontEndImplBase::~FrontEndImplBase () inline virtual
Definition at line 35 of file FrontEndImplBase.h.
References shutdown().
FrontEndImplBase::FrontEndImplBase (const FrontEndImplBase & other) private
Member Function Documentation
std::string FrontEndImplBase::AMBSILibraryVersion () virtual
Definition at line 60 of file FrontEndImplBase.cpp.
References AMBSILibraryVersion_value, GET_AMBSI_VERSION_INFO, SPECIAL_MONITOR, and FEHardwareDevice::syncMonitorThreeByteRevLevel().
Referenced by SignalSourceImpl::initialize(), and FrontEndImpl::specialGetSetupInfo().
std::string FrontEndImplBase::FEMCFirmwareVersion () virtual
Definition at line 65 of file FrontEndImplBase.cpp.
References FEMCFirmwareVersion_value, GET_VERSION_INFO, SPECIAL_MONITOR, and FEHardwareDevice::syncMonitorThreeByteRevLevel().
Referenced by SignalSourceImpl::initialize(), and FrontEndImpl::specialGetSetupInfo().
std::string FrontEndImplBase::FEMCFPGAVersion () virtual
Definition at line 70 of file FrontEndImplBase.cpp.
References FEMCFPGAVersion_value, GET_FPGA_VERSION_INFO, SPECIAL_MONITOR, and FEHardwareDevice::syncMonitorThreeByteRevLevel().
Referenced by SignalSourceImpl::initialize(), and FrontEndImpl::specialGetSetupInfo().
unsigned char FrontEndImplBase::FEMCGetESNsFound () virtual
Definition at line 75 of file FrontEndImplBase.cpp.
References FEMCGetESNsFound_value, GET_ESNS_FOUND, and SPECIAL_MONITOR.
std::string FrontEndImplBase::FEMCGetNextESN (bool reverseBytes = false) virtual
Definition at line 92 of file FrontEndImplBase.cpp.
References FEMCGetNextESN_value, GET_ESNS, SPECIAL_MONITOR, and FEHardwareDevice::syncMonitorEightByteESN().
unsigned char FrontEndImplBase::getFEMode () virtual
Definition at line 142 of file FrontEndImplBase.cpp.
References FrontEndLVWrapper::FEMode, and SYNCMON_LOG_INT.
unsigned short FrontEndImplBase::getNextError () virtual
Definition at line 138 of file FrontEndImplBase.cpp.
References SYNCMON_LOG_INT.
Referenced by FrontEndImpl::getNextError().
unsigned short FrontEndImplBase::getNumErrors () virtual
Definition at line 135 of file FrontEndImplBase.cpp.
References SYNCMON_LOG_INT.
Referenced by FrontEndImpl::getNextError().
void FrontEndImplBase::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Reimplemented in FrontEndImpl, and SignalSourceImpl.
Definition at line 52 of file FrontEndImplBase.cpp.
References FrontEndLVWrapper::nodeAddress.
Referenced by SignalSourceImpl::initialize(), and FrontEndImpl::initialize().
void FrontEndImplBase::monitorAction (Time * timestamp_p) protected virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implements FEHardwareDevice.
Definition at line 197 of file FrontEndImplBase.cpp.
References AMBSIHardwareDevice::AMBSINumErrors(), AMBSIHardwareDevice::AMBSINumTransactions(), AMBSIHardwareDevice::AMBSITemperature(), lastMonitorTime, numEnabledModules(), and numEnabledModules_value.
unsigned char FrontEndImplBase::numEnabledModules () virtual
Definition at line 115 of file FrontEndImplBase.cpp.
References SYNCMON_LOG_BYTE.
Referenced by monitorAction(), SignalSourceImpl::powerGetMonitorNumEnabled(), and FrontEndImpl::powerGetMonitorNumEnabled().
bool FrontEndImplBase::powerEnableModule (int port) virtual
Definition at line 119 of file FrontEndImplBase.cpp.
References FEHardwareDevice::FEMC_LOG_MONITOR, FEHardwareDevice::FEMC_NO_ERROR, FEHardwareDevice::getLogger(), FEHardwareDevice::LogInterface::log(), powerEnableModule_RCA, and FEHardwareDevice::syncMonitor().
Referenced by SignalSourceImpl::queryCartridgeState(), SignalSourceImpl::setCartridgeOff(), FrontEndImpl::setCartridgeOff(), SignalSourceImpl::setCartridgeOn(), and FrontEndImpl::setCartridgeOn().
void FrontEndImplBase::powerEnableModule (int port, bool val) virtual
Definition at line 146 of file FrontEndImplBase.cpp.
References FEHardwareDevice::FEMC_LOG_COMMAND, FEHardwareDevice::getLogger(), FEHardwareDevice::LogInterface::log(), powerEnableModule_RCA, and FEHardwareDevice::syncCommand().
void FrontEndImplBase::setFEMode (unsigned char val) virtual
Reimplemented in FrontEndImpl.
Definition at line 184 of file FrontEndImplBase.cpp.
References FEHardwareDevice::pack(), SET_FE_MODE, and SPECIAL_CONTROL.
Referenced by FrontEndImpl::setFEMode().
void FrontEndImplBase::shutdown () virtual
Reimplemented in FrontEndImpl, and SignalSourceImpl.
Definition at line 57 of file FrontEndImplBase.cpp.
Referenced by SignalSourceImpl::shutdown(), FrontEndImpl::shutdown(), and ~FrontEndImplBase().
void FrontEndImplBase::specialExitProgram (bool val) virtual
Definition at line 156 of file FrontEndImplBase.cpp.
References FEHardwareDevice::pack(), SET_EXIT_PROGRAM, and SPECIAL_CONTROL.
unsigned char FrontEndImplBase::specialGetSetupInfo () virtual
Reimplemented in FrontEndImpl.
Definition at line 98 of file FrontEndImplBase.cpp.
References GET_SETUP_INFO, SPECIAL_MONITOR, specialGetSetupInfo_value, and FEHardwareDevice::unpack().
Referenced by SignalSourceImpl::initialize(), and FrontEndImpl::specialGetSetupInfo().
void FrontEndImplBase::specialReadESNs (bool val) virtual
Definition at line 170 of file FrontEndImplBase.cpp.
References FEHardwareDevice::pack(), SET_READ_ESN, and SPECIAL_CONTROL.
Member Data Documentation
std::string FrontEndImplBase::AMBSILibraryVersion_value protected
Definition at line 97 of file FrontEndImplBase.h.
Referenced by AMBSILibraryVersion(), SignalSourceImpl::getFirmwareInfo(), and FrontEndImpl::getFirmwareInfo().
std::string FrontEndImplBase::FEMCFirmwareVersion_value protected
Definition at line 98 of file FrontEndImplBase.h.
Referenced by FEMCFirmwareVersion(), SignalSourceImpl::getFirmwareInfo(), and FrontEndImpl::getFirmwareInfo().
std::string FrontEndImplBase::FEMCFPGAVersion_value protected
Definition at line 99 of file FrontEndImplBase.h.
Referenced by FEMCFPGAVersion(), SignalSourceImpl::getFirmwareInfo(), and FrontEndImpl::getFirmwareInfo().
unsigned char FrontEndImplBase::FEMCGetESNsFound_value protected
Definition at line 100 of file FrontEndImplBase.h.
Referenced by FEMCGetESNsFound().
std::string FrontEndImplBase::FEMCGetNextESN_value protected
Definition at line 101 of file FrontEndImplBase.h.
Referenced by FEMCGetNextESN().
AmbRelativeAddr FrontEndImplBase::FEMode_RCA protected
Definition at line 116 of file FrontEndImplBase.h.
int FrontEndImplBase::FEMode_status protected
Definition at line 110 of file FrontEndImplBase.h.
unsigned char FrontEndImplBase::FEMode_value protected
Definition at line 109 of file FrontEndImplBase.h.
Time FrontEndImplBase::lastMonitorTime private
Definition at line 122 of file FrontEndImplBase.h.
Referenced by monitorAction().
int FrontEndImplBase::monitorPhase private
Definition at line 123 of file FrontEndImplBase.h.
AmbRelativeAddr FrontEndImplBase::nextError_RCA protected
Definition at line 115 of file FrontEndImplBase.h.
int FrontEndImplBase::nextError_status protected
Definition at line 108 of file FrontEndImplBase.h.
unsigned short FrontEndImplBase::nextError_value protected
Definition at line 107 of file FrontEndImplBase.h.
AmbRelativeAddr FrontEndImplBase::numEnabledModules_RCA protected
Definition at line 112 of file FrontEndImplBase.h.
int FrontEndImplBase::numEnabledModules_status protected
Definition at line 104 of file FrontEndImplBase.h.
unsigned char FrontEndImplBase::numEnabledModules_value protected
Definition at line 103 of file FrontEndImplBase.h.
Referenced by monitorAction().
AmbRelativeAddr FrontEndImplBase::numErrors_RCA protected
Definition at line 114 of file FrontEndImplBase.h.
int FrontEndImplBase::numErrors_status protected
Definition at line 106 of file FrontEndImplBase.h.
unsigned short FrontEndImplBase::numErrors_value protected
Definition at line 105 of file FrontEndImplBase.h.
AmbRelativeAddr FrontEndImplBase::powerEnableModule_RCA protected
Definition at line 113 of file FrontEndImplBase.h.
Referenced by powerEnableModule().
unsigned char FrontEndImplBase::specialGetSetupInfo_value protected
Definition at line 102 of file FrontEndImplBase.h.
Referenced by specialGetSetupInfo().
The documentation for this class was generated from the following files:
FEBASE/FrontEndImplBase.h
FEBASE/FrontEndImplBase.cpp