FrontEndControl2: FEConfig::ParamTableRow Class Reference
FEConfig::ParamTableRow Class Reference
A ParamTableRow is a 1-D array of float of a fixed size.
#include <LookupTables.h>
Public Member Functions
ParamTableRow (unsigned numCols=1)
construct with the number of columns in the row. All cells are initialized to zero.
~ParamTableRow ()
void clear ()
Set all contents to zero retaining size.
float get (unsigned col) const
get the item at index 'col'. Return 0 if out of bounds.
float operator[] (unsigned col) const
another name for get().
bool set (unsigned col, float val)
set the value at index 'col'. Return false if out of bounds.
void weightedAdd (double weight, const ParamTableRow &other)
set all values to a point between this and other, determined by 'weight', which should be between 0.0 and 1.0 (not enforced.)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
int fWidth_m
field width for streaming float values.
int fPrecision_m
precision for streaming float values.
Private Types
typedef std::vector< float > base_type
implemented in terms of vector<float>.
Detailed Description
A ParamTableRow is a 1-D array of float of a fixed size.
The size may be set when constructed or new data assigned.
Definition at line 49 of file LookupTables.h.
Member Typedef Documentation
typedef std::vector<float> FEConfig::ParamTableRow::base_type private
implemented in terms of vector<float>.
Definition at line 50 of file LookupTables.h.
Constructor & Destructor Documentation
FEConfig::ParamTableRow::ParamTableRow (unsigned numCols = 1) inline
construct with the number of columns in the row. All cells are initialized to zero.
Definition at line 52 of file LookupTables.h.
FEConfig::ParamTableRow::~ParamTableRow () inline
Definition at line 58 of file LookupTables.h.
Member Function Documentation
void FEConfig::ParamTableRow::clear () inline
Set all contents to zero retaining size.
Definition at line 60 of file LookupTables.h.
Referenced by FEConfig::ParamTable::get().
float FEConfig::ParamTableRow::get (unsigned col) const inline
get the item at index 'col'. Return 0 if out of bounds.
Definition at line 64 of file LookupTables.h.
Referenced by weightedAdd().
float FEConfig::ParamTableRow::operator[] (unsigned col) const inline
another name for get().
Definition at line 69 of file LookupTables.h.
bool FEConfig::ParamTableRow::set (unsigned col, float val) inline
set the value at index 'col'. Return false if out of bounds.
Definition at line 73 of file LookupTables.h.
Referenced by FEConfig::ParamTable::set(), and weightedAdd().
void FEConfig::ParamTableRow::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 26 of file LookupTables.cpp.
Referenced by FEConfig::operator<<().
void FEConfig::ParamTableRow::weightedAdd (double weight, const ParamTableRow & other) inline
set all values to a point between this and other, determined by 'weight', which should be between 0.0 and 1.0 (not enforced.)
Definition at line 79 of file LookupTables.h.
References get(), and set().
Referenced by FEConfig::ParamTable::get().
Member Data Documentation
int FEConfig::ParamTableRow::fPrecision_m
precision for streaming float values.
Definition at line 86 of file LookupTables.h.
Referenced by CartHealthCheck::prepare().
int FEConfig::ParamTableRow::fWidth_m
field width for streaming float values.
Definition at line 85 of file LookupTables.h.
Referenced by CartHealthCheck::prepare().
The documentation for this class was generated from the following files:
CONFIG/LookupTables.h
CONFIG/LookupTables.cpp