FrontEndControl2: CompressorImplBase Class Reference
CompressorImplBase Class Reference
#include <CompressorImplBase.h>
Public Member Functions
CompressorImplBase (const std::string &name)
virtual ~CompressorImplBase ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual float getTemp1 ()
virtual float getTemp2 ()
virtual float getTemp3 ()
virtual float getTemp4 ()
virtual float getReturnLinePressure ()
virtual float getAuxTransducer ()
virtual float getSupplyPressure ()
virtual bool getPressureAlarm ()
virtual bool getTempAlarm ()
virtual bool getDriveIndicator ()
virtual bool getICCUStatusError ()
virtual bool getICCUCableError ()
virtual bool getFETIMStatusError ()
virtual bool getFETIMCableError ()
virtual bool getInterlockOverride ()
virtual unsigned char getECUType ()
virtual bool getFaultStatusError ()
virtual std::string getSWRevisionLevel ()
virtual unsigned long getTimeSinceLastPowerOn ()
virtual unsigned long getTimeSinceLastPowerOff ()
virtual void setRemoteDrive (bool val)
virtual void setRemoteReset ()
virtual void setFaultLatchReset ()
Public Member Functions inherited from AMBSIHardwareDevice
AMBSIHardwareDevice (const std::string &name)
virtual ~AMBSIHardwareDevice ()
virtual std::string AMBSISerialNum ()
virtual std::string AMBSIFirmwareRev ()
virtual unsigned long AMBSINumErrors ()
virtual unsigned long AMBSINumTransactions ()
virtual float AMBSITemperature ()
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Protected Types
enum MonitorControlOffset {
GET_TEMP_1 = 0x0001, GET_TEMP_2 = 0x0002, GET_TEMP_3 = 0x0003, GET_TEMP_4 = 0x0004,
GET_RET_PRESSURE = 0x0005, GET_AUX_2 = 0x0006, GET_SUPPLY_PRESSURE = 0x0007, GET_PRESSURE_ALARM = 0x0008,
GET_TEMP_ALARM = 0x0009, GET_DRIVE_INDICATION = 0x000A, GET_ICCU_STATUS_ERROR = 0x000B, GET_ICCU_CABLE_DETECT_ERROR = 0x000C,
GET_FETIM_STATUS_ERROR = 0x000D, GET_FETIM_CABLE_ERROR = 0x000E, GET_INTERLOCK_OVERRIDE = 0x000F, GET_ECU_TYPE = 0x0010,
GET_FAULT_STATUS_ERROR = 0x0011, GET_SW_REVISION_LEVEL = 0x0012, GET_TIME_SINCE_LAST_POWER_ON = 0x0013, GET_TIME_SINCE_LAST_POWER_OFF = 0x0014,
SET_REMOTE_DRIVE = 0x1001, SET_REMOTE_RESET = 0x1002, SET_FAULT_LATCH_RESET = 0x1003, SET_PUSH_4K_CRYOCOOLER_TEMP = 0x1004,
SET_PUSH_15K_CRYOCOOLER_TEMP = 0x1005, SET_PUSH_110K_CRYOCOOLER_TEMP = 0x1006, SET_PUSH_PORT_PRESSURE = 0x1007, SET_PUSH_DEWAR_PRESSURE = 0x1008,
SET_PUSH_GATE_VALVE_STATE = 0x1009, SET_PUSH_SOLENOID_VALVE_STATE = 0x100A, SET_PUSH_BACKING_PUMP_ENABLE = 0x100B, SET_PUSH_TURBO_PUMP_ENABLE = 0x100C,
SET_PUSH_TURBO_PUMP_STATE = 0x100D, SET_PUSH_TURBO_PUMP_SPEED = 0x100E, SET_PUSH_CRYO_SUPPLY_CURRENT_230V = 0x100F, SET_BYPASS_TIMERS = 0x2000
}
Protected Types inherited from AMBSIHardwareDevice
enum MonitorControlOffset {
AMBSI_BASE = 0x30000UL, AMBSI_SERIAL_NUMBER = 0x0000, AMBSI_FIRMWARE_REV = 0x0000, AMBSI_NUM_ERRORS = 0x0001,
AMBSI_NUM_TRANSACTIONS = 0x0002, AMBSI_TEMPERATURE = 0x0003
}
Protected Member Functions
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Protected Attributes
float getTemp1_value
float getTemp2_value
float getTemp3_value
float getTemp4_value
float getReturnLinePressure_value
float getAuxTransducer_value
float getSupplyPressure_value
bool getPressureAlarm_value
bool getTempAlarm_value
bool getDriveIndicator_value
bool getICCUStatusError_value
bool getICCUCableError_value
bool getFETIMStatusError_value
bool getFETIMCableError_value
bool getInterlockOverride_value
unsigned char getECUType_value
bool getFaultStatusError_value
std::string getSWRevisionLevel_value
unsigned long getTimeSinceLastPowerOn_value
unsigned long getTimeSinceLastPowerOff_value
Protected Attributes inherited from AMBSIHardwareDevice
std::string AMBSISerialNum_value
std::string AMBSIFirmwareRev_value
unsigned long AMBSINumErrors_value
unsigned long AMBSINumTransactions_value
float AMBSITemperature_value
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
CompressorImplBase (const CompressorImplBase &other)
Private Attributes
Time lastMonitorTime
int monitorPhase
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 31 of file CompressorImplBase.h.
Member Enumeration Documentation
enum CompressorImplBase::MonitorControlOffset protected
Enumerator
GET_TEMP_1
GET_TEMP_2
GET_TEMP_3
GET_TEMP_4
GET_RET_PRESSURE
GET_AUX_2
GET_SUPPLY_PRESSURE
GET_PRESSURE_ALARM
GET_TEMP_ALARM
GET_DRIVE_INDICATION
GET_ICCU_STATUS_ERROR
GET_ICCU_CABLE_DETECT_ERROR
GET_FETIM_STATUS_ERROR
GET_FETIM_CABLE_ERROR
GET_INTERLOCK_OVERRIDE
GET_ECU_TYPE
GET_FAULT_STATUS_ERROR
GET_SW_REVISION_LEVEL
GET_TIME_SINCE_LAST_POWER_ON
GET_TIME_SINCE_LAST_POWER_OFF
SET_REMOTE_DRIVE
SET_REMOTE_RESET
SET_FAULT_LATCH_RESET
SET_PUSH_4K_CRYOCOOLER_TEMP
SET_PUSH_15K_CRYOCOOLER_TEMP
SET_PUSH_110K_CRYOCOOLER_TEMP
SET_PUSH_PORT_PRESSURE
SET_PUSH_DEWAR_PRESSURE
SET_PUSH_GATE_VALVE_STATE
SET_PUSH_SOLENOID_VALVE_STATE
SET_PUSH_BACKING_PUMP_ENABLE
SET_PUSH_TURBO_PUMP_ENABLE
SET_PUSH_TURBO_PUMP_STATE
SET_PUSH_TURBO_PUMP_SPEED
SET_PUSH_CRYO_SUPPLY_CURRENT_230V
SET_BYPASS_TIMERS
Definition at line 70 of file CompressorImplBase.h.
Constructor & Destructor Documentation
CompressorImplBase::CompressorImplBase (const std::string & name)
Definition at line 32 of file CompressorImplBase.cpp.
virtual CompressorImplBase::~CompressorImplBase () inline virtual
Definition at line 34 of file CompressorImplBase.h.
References shutdown().
CompressorImplBase::CompressorImplBase (const CompressorImplBase & other) private
Member Function Documentation
float CompressorImplBase::getAuxTransducer () virtual
Definition at line 87 of file CompressorImplBase.cpp.
References GET_AUX_2, and SYNCMON2_LOG_FLOAT.
Referenced by monitorAction().
bool CompressorImplBase::getDriveIndicator () virtual
Definition at line 103 of file CompressorImplBase.cpp.
References GET_DRIVE_INDICATION, and SYNCMON2_LOG_BOOL.
Referenced by monitorAction().
unsigned char CompressorImplBase::getECUType () virtual
Definition at line 127 of file CompressorImplBase.cpp.
References GET_ECU_TYPE, and SYNCMON2_LOG_INT.
Referenced by monitorAction().
bool CompressorImplBase::getFaultStatusError () virtual
Definition at line 131 of file CompressorImplBase.cpp.
References GET_FAULT_STATUS_ERROR, and SYNCMON2_LOG_BOOL.
Referenced by monitorAction().
bool CompressorImplBase::getFETIMCableError () virtual
Definition at line 119 of file CompressorImplBase.cpp.
References GET_FETIM_CABLE_ERROR, and SYNCMON2_LOG_BOOL.
Referenced by monitorAction().
bool CompressorImplBase::getFETIMStatusError () virtual
Definition at line 115 of file CompressorImplBase.cpp.
References GET_FETIM_STATUS_ERROR, and SYNCMON2_LOG_BOOL.
Referenced by monitorAction().
bool CompressorImplBase::getICCUCableError () virtual
Definition at line 111 of file CompressorImplBase.cpp.
References GET_ICCU_CABLE_DETECT_ERROR, and SYNCMON2_LOG_BOOL.
Referenced by monitorAction().
bool CompressorImplBase::getICCUStatusError () virtual
Definition at line 107 of file CompressorImplBase.cpp.
References GET_ICCU_STATUS_ERROR, and SYNCMON2_LOG_BOOL.
Referenced by monitorAction().
bool CompressorImplBase::getInterlockOverride () virtual
Definition at line 123 of file CompressorImplBase.cpp.
References GET_INTERLOCK_OVERRIDE, and SYNCMON2_LOG_BOOL.
Referenced by monitorAction().
bool CompressorImplBase::getPressureAlarm () virtual
Definition at line 95 of file CompressorImplBase.cpp.
References GET_PRESSURE_ALARM, and SYNCMON2_LOG_BOOL.
Referenced by monitorAction().
float CompressorImplBase::getReturnLinePressure () virtual
Definition at line 83 of file CompressorImplBase.cpp.
References GET_RET_PRESSURE, and SYNCMON2_LOG_FLOAT.
Referenced by monitorAction().
float CompressorImplBase::getSupplyPressure () virtual
Definition at line 91 of file CompressorImplBase.cpp.
References GET_SUPPLY_PRESSURE, and SYNCMON2_LOG_FLOAT.
Referenced by monitorAction().
std::string CompressorImplBase::getSWRevisionLevel () virtual
Definition at line 135 of file CompressorImplBase.cpp.
References GET_SW_REVISION_LEVEL, getSWRevisionLevel_value, and FEHardwareDevice::syncMonitorThreeByteRevLevel().
Referenced by monitorAction().
float CompressorImplBase::getTemp1 () virtual
Definition at line 67 of file CompressorImplBase.cpp.
References GET_TEMP_1, and SYNCMON2_LOG_FLOAT.
Referenced by monitorAction().
float CompressorImplBase::getTemp2 () virtual
Definition at line 71 of file CompressorImplBase.cpp.
References GET_TEMP_2, and SYNCMON2_LOG_FLOAT.
Referenced by monitorAction().
float CompressorImplBase::getTemp3 () virtual
Definition at line 75 of file CompressorImplBase.cpp.
References GET_TEMP_3, and SYNCMON2_LOG_FLOAT.
Referenced by monitorAction().
float CompressorImplBase::getTemp4 () virtual
Definition at line 79 of file CompressorImplBase.cpp.
References GET_TEMP_4, and SYNCMON2_LOG_FLOAT.
Referenced by monitorAction().
bool CompressorImplBase::getTempAlarm () virtual
Definition at line 99 of file CompressorImplBase.cpp.
References GET_TEMP_ALARM, and SYNCMON2_LOG_BOOL.
Referenced by monitorAction().
unsigned long CompressorImplBase::getTimeSinceLastPowerOff () virtual
Definition at line 151 of file CompressorImplBase.cpp.
References FEHardwareDevice::FEMC_LOG_MONITOR, FEHardwareDevice::FEMC_NO_ERROR, GET_TIME_SINCE_LAST_POWER_OFF, LOG2_INT, and SYNCMON2.
Referenced by monitorAction().
unsigned long CompressorImplBase::getTimeSinceLastPowerOn () virtual
Definition at line 140 of file CompressorImplBase.cpp.
References FEHardwareDevice::FEMC_LOG_MONITOR, FEHardwareDevice::FEMC_NO_ERROR, GET_TIME_SINCE_LAST_POWER_ON, LOG2_INT, and SYNCMON2.
Referenced by monitorAction().
void CompressorImplBase::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Definition at line 59 of file CompressorImplBase.cpp.
References FrontEndLVWrapper::nodeAddress.
Referenced by CompressorImpl::CompressorImpl().
void CompressorImplBase::monitorAction (Time * timestamp_p) protected virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implements FEHardwareDevice.
Definition at line 177 of file CompressorImplBase.cpp.
References getAuxTransducer(), getAuxTransducer_value, getDriveIndicator(), getDriveIndicator_value, getECUType(), getECUType_value, getFaultStatusError(), getFaultStatusError_value, getFETIMCableError(), getFETIMCableError_value, getFETIMStatusError(), getFETIMStatusError_value, getICCUCableError(), getICCUCableError_value, getICCUStatusError(), getICCUStatusError_value, getInterlockOverride(), getInterlockOverride_value, getPressureAlarm(), getPressureAlarm_value, getReturnLinePressure(), getReturnLinePressure_value, getSupplyPressure(), getSupplyPressure_value, getSWRevisionLevel(), getSWRevisionLevel_value, getTemp1(), getTemp1_value, getTemp2(), getTemp2_value, getTemp3(), getTemp3_value, getTemp4(), getTemp4_value, getTempAlarm(), getTempAlarm_value, getTimeSinceLastPowerOff(), getTimeSinceLastPowerOff_value, getTimeSinceLastPowerOn(), getTimeSinceLastPowerOn_value, and lastMonitorTime.
void CompressorImplBase::setFaultLatchReset () virtual
Definition at line 172 of file CompressorImplBase.cpp.
References SET_FAULT_LATCH_RESET, and SYNCCMD2_LOG_BYTE.
void CompressorImplBase::setRemoteDrive (bool val) virtual
Definition at line 162 of file CompressorImplBase.cpp.
References SET_REMOTE_DRIVE, and SYNCCMD2_LOG_BYTE.
void CompressorImplBase::setRemoteReset () virtual
Definition at line 167 of file CompressorImplBase.cpp.
References SET_REMOTE_RESET, and SYNCCMD2_LOG_BYTE.
void CompressorImplBase::shutdown () virtual
Definition at line 64 of file CompressorImplBase.cpp.
Referenced by ~CompressorImplBase().
Member Data Documentation
float CompressorImplBase::getAuxTransducer_value protected
Definition at line 119 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
bool CompressorImplBase::getDriveIndicator_value protected
Definition at line 123 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
unsigned char CompressorImplBase::getECUType_value protected
Definition at line 129 of file CompressorImplBase.h.
Referenced by monitorAction().
bool CompressorImplBase::getFaultStatusError_value protected
Definition at line 130 of file CompressorImplBase.h.
Referenced by CompressorImpl::getMonitorCompressor(), and monitorAction().
bool CompressorImplBase::getFETIMCableError_value protected
Definition at line 127 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
bool CompressorImplBase::getFETIMStatusError_value protected
Definition at line 126 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
bool CompressorImplBase::getICCUCableError_value protected
Definition at line 125 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
bool CompressorImplBase::getICCUStatusError_value protected
Definition at line 124 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
bool CompressorImplBase::getInterlockOverride_value protected
Definition at line 128 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
bool CompressorImplBase::getPressureAlarm_value protected
Definition at line 121 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
float CompressorImplBase::getReturnLinePressure_value protected
Definition at line 118 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
float CompressorImplBase::getSupplyPressure_value protected
Definition at line 120 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
std::string CompressorImplBase::getSWRevisionLevel_value protected
Definition at line 131 of file CompressorImplBase.h.
Referenced by getSWRevisionLevel(), and monitorAction().
float CompressorImplBase::getTemp1_value protected
Definition at line 114 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
float CompressorImplBase::getTemp2_value protected
Definition at line 115 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
float CompressorImplBase::getTemp3_value protected
Definition at line 116 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
float CompressorImplBase::getTemp4_value protected
Definition at line 117 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
bool CompressorImplBase::getTempAlarm_value protected
Definition at line 122 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
unsigned long CompressorImplBase::getTimeSinceLastPowerOff_value protected
Definition at line 133 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
unsigned long CompressorImplBase::getTimeSinceLastPowerOn_value protected
Definition at line 132 of file CompressorImplBase.h.
Referenced by CompressorImpl::appendThermalLog(), CompressorImpl::getMonitorCompressor(), and monitorAction().
Time CompressorImplBase::lastMonitorTime private
Definition at line 139 of file CompressorImplBase.h.
Referenced by monitorAction().
int CompressorImplBase::monitorPhase private
Definition at line 140 of file CompressorImplBase.h.
The documentation for this class was generated from the following files:
FEBASE/CompressorImplBase.h
FEBASE/CompressorImplBase.cpp