FrontEndControl2: FrontEndImpl Class Reference
FrontEndImpl Class Reference
The top-level FrontEnd class, giving the entire control interface for the Front End.
#include <FrontEndImpl.h>
Public Member Functions
FrontEndImpl (unsigned long channel, unsigned long nodeAddress, const std::string &ESN="")
virtual ~FrontEndImpl ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
bool connected () const
bool getNextError (unsigned char &moduleNum, unsigned char &errorNum, std::string &description)
fetch the next error from the FEMC error queue.
virtual void setFEMode (unsigned char val)
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
bool getDbConfigId (FEICDataBase::ID_T &onfigId) const
bool startHealthCheck (bool isPASData, bool fullAuto=false)
bool cartHealthCheck (int port, int warmUpTimeSeconds)
bool cartHealthCheckSaveIFPowerData (int port, const IFPowerDataSet &source)
bool finishHealthCheck ()
void queryCartridgeState ()
void measureSISVoltageError (int port=0)
void setFrontEndSN (const std::string &SN)
bool addCartridge (int port, WCAImpl &WCA, ColdCartImpl &coldCart)
bool addCartridge (int port, WCAImpl &WCA)
bool addCartridge (int port, ColdCartImpl &coldCart)
bool deleteCartridge (int port)
bool addPowerModule (PowerModuleImpl &module)
bool deletePowerModule (int port)
void addCryostat ()
void deleteCryostat ()
void addFETIM ()
void deleteFETIM ()
void addIFSwitch ()
void deleteIFSwitch ()
void addLPR ()
void deleteLPR ()
void addCPDS ()
void deleteCPDS ()
bool setColdCartConfig (int port, const FEConfig::ColdCartConfig &params)
bool setWCAConfig (int port, const FEConfig::WCAConfig &params)
bool setYIGLimits (int port, double FLOYIG, double FHIYIG)
bool setCartridgeOff (int port)
bool setCartridgeOn (int port)
bool setCartridgeReady (int port)
bool setCartridgeObserving (int port)
void clearCartridgeObserving ()
int getCartridgeObserving () const
bool getCartridgeOn (int port) const
bool cartPauseMonitor (int port, bool pauseWCA, bool pauseCC)
virtual unsigned char specialGetSetupInfo ()
void getAMBSIInfo (std::string &serialNum, std::string &firmwareRev, unsigned long &numErrors, unsigned long &numTransactions)
void getFirmwareInfo (std::string &AMBSILibraryVersion, std::string &FEMCFirmwareVersion, std::string &FEMCFPGAVersion)
float getAMBSITemperature () const
unsigned short powerGetMonitorNumEnabled ()
bool cartGetMonitorYTO (int port, WCAImpl::YTO_t &target) const
bool cartGetMonitorPhotomixer (int port, WCAImpl::Photomixer_t &target) const
bool cartGetMonitorPLL (int port, WCAImpl::PLL_t &target) const
bool cartGetMonitorAMC (int port, WCAImpl::AMC_t &target) const
bool cartGetMonitorPA (int port, WCAImpl::PA_t &target) const
bool cartGetMonitorTemp (int port, ColdCartImpl::CartridgeTemp_t &target) const
bool cartGetMonitorSIS (int port, int pol, int sb, ColdCartImpl::SIS_t &target) const
bool cartGetMonitorLNA (int port, int pol, int sb, ColdCartImpl::LNA_t &target) const
bool cartGetMonitorAux (int port, int pol, ColdCartImpl::Aux_t &target) const
bool cartSetLOFrequency (int port, double freqLO, double freqFLOOG, int sbLock)
bool cartGetLOFrequency (int port, double &freqLO, double &freqREF) const
bool cartLockPLL (int port)
bool cartGetLocked (int port)
bool cartAdjustPLL (int port, float targetCorrVoltage)
bool cartAdjustYTO (int port, int steps)
bool cartNullPLLIntegrator (int port, bool enable=false)
bool cartGetNullPLLIntegrator (int port) const
bool cartSetLNABias (int port, int pol=-1, int sb=-1, const float *VD1=NULL, const float *ID1=NULL, const float *VD2=NULL, const float *ID2=NULL, const float *VD3=NULL, const float *ID3=NULL)
bool cartSetEnableLNABias (int port, bool enable=false, int pol=-1, int sb=-1)
bool cartGetEnableLNABias (int port) const
bool cartSetSISBias (int port, bool enable=false, int pol=-1, int sb=-1, const float *VJ=NULL, int openLoop=-1)
bool cartGetEnableSISBias (int port) const
bool cartSetSISMagnet (int port, bool enable=false, int pol=-1, int sb=-1, const float *IMag=NULL)
bool cartGetEnableSISMagnet (int port) const
bool cartGetSISMagnet (short port, int pol, int sb, float *IMag)
bool cartSetLOPowerAmps (int port, bool enable=false, const float *VDP0=NULL, const float *VGP0=NULL, const float *VDP1=NULL, const float *VGP1=NULL)
bool cartGetEnableLOPowerAmps (int port) const
bool cartAdjustLOPowerAmps (int port, int repeatCount=1)
bool cartSetEnableLO (int port, bool enable)
bool cartSetLOPower (int port, int pol, float percent)
bool cartOptimizeIFPower (int port, bool doPol0, bool doPol1)
bool cartSetIFPower (int port, int pol, float powerSB1, float powerSB2)
Inject the current IF power level readings for a single port and polarization.
bool cartSetVJVD (int port, int pol, float *VJ1, float *VJ2, float *VD)
bool cartGetVJVD (int port, int pol, float *VJ1, float *VJ2, float *VD)
bool cartGetLOPADrainVoltageSetting (int port, float *VDP0, float *VDP1)
bool cartSetAMC (int port, const float *VDE=NULL, const float *VGE=NULL)
void setFineLOSweepIniFile (const std::string FineLoSweepIni)
bool cartMeasureFineLOSweep (int port, float tiltAngle, int pol=-1, const float *VJ=NULL, const float *IJ=NULL, const float *fixedVD=NULL, const double *LOStart=NULL, const double *LOStop=NULL, const double *LOStep=NULL, int repeatCount=1)
bool cartMeasureIVCurve (int port, int pol, int sb, const float *VJlow_p=NULL, const float *VJhigh_p=NULL, const float *VJstep_p=NULL, int repeatCount=1)
bool cartMeasureIJvsSISMagnet (int port, int pol, int sb, float IMagStart, float IMagStop, float IMagStep, float VJLow, float VJHigh, float VJStep, int repeatCount=1)
bool cartMeasureIFPowerVsVJ (int port, int pol, int sb, float VJStart, float VJStop, float VJStep, bool doYFactor=false, int repeatCount=1)
bool cartMeasureIFPowerVsVD (int port, int pol, float VDStart, float VDStop, float VDStep, bool doYFactor=false, int repeatCount=1)
bool cartMixerDeflux (int port, int pol, int sb, int IMagMax)
void cartAbortMeasurement (int port)
const XYPlotArray & cartGetXYData (int port) const
bool cartSetEnableLNALEDs (int port, bool enable=false)
bool cartSetEnableSISHeaters (int port, bool enable=false, int pol=-1, float targetTemp=12.0, int timeout=30)
bool cartSetEnablePhotomixer (int port, bool enable=false)
bool cartGetEnablePhotomixer (int port) const
bool powerGetMonitorModule (int port, PowerModuleImpl::PowerModule_t &target) const
bool powerSetEnableModule (int port, bool enable=false)
bool ifSwitchGetMonitorModule (IFSwitchImpl::IFSwitch_t &target) const
bool ifSwitchSetAttenuation (int pol=-1, int sb=-1, unsigned char atten=15)
bool ifSwitchSetEnableTempServo (int pol=-1, int sb=-1, bool enable=false)
bool cryostatGetMonitorModule (CryostatImpl::Cryostat_t &target) const
bool cryostatSetEnableBackingPump (bool enable)
Start/stop the backing pump.
bool cryostatSetEnableTurboPump (bool enable)
Start/stop the turbo pump.
bool cryostatSetGateValveState (bool open)
Open/close the gate valve.
bool cryostatSetSolenoidValveState (bool open)
Open/close the solenoid valve.
bool cryostatSetEnableVacuumGauge (bool enable)
Enable/disable the vacuum gauge.
bool cryostatSetEnableCryoPumping (bool enable)
Enable/disable the pump-down process.
bool fetimGetMonitorModule (FETIMImpl::FETIM_t &target) const
bool fetimSetTriggerDewarN2Fill (bool enable)
Enable/disable the N2 fill trigger.
bool lprGetMonitorModule (LPRImpl::LPR_t &target) const
bool lprSetOpticalSwitchPort (int port)
Set the optical switch output port and disable the shutter.
bool lprSetOpticalSwitchShutter ()
Enables the shutter (disables the laser).
bool lprSetOpticalSwitchForceShutter ()
Enables the shutter (disables the laser) more forcefully (for debugging).
bool lprSetEDFAModulationInput (float value)
Sets the EDFA modulation input value in Volts.
void setThermalLogInterval (unsigned int interval)
set the frequency of thermal logging, in seconds.
void appendThermalLog (std::string &target) const
append thermal information to a logging string
void appendThermalLogHeader (std::string &target) const
append thermal header information to a logging string
Public Member Functions inherited from FrontEndImplBase
FrontEndImplBase (const std::string &name)
virtual ~FrontEndImplBase ()
virtual std::string AMBSILibraryVersion ()
virtual std::string FEMCFirmwareVersion ()
virtual std::string FEMCFPGAVersion ()
virtual unsigned char FEMCGetESNsFound ()
virtual std::string FEMCGetNextESN (bool reverseBytes=false)
virtual unsigned char numEnabledModules ()
virtual bool powerEnableModule (int port)
virtual unsigned short getNumErrors ()
virtual unsigned short getNextError ()
virtual unsigned char getFEMode ()
virtual void powerEnableModule (int port, bool val)
virtual void specialExitProgram (bool val)
virtual void specialReadESNs (bool val)
Public Member Functions inherited from AMBSIHardwareDevice
AMBSIHardwareDevice (const std::string &name)
virtual ~AMBSIHardwareDevice ()
virtual std::string AMBSISerialNum ()
virtual std::string AMBSIFirmwareRev ()
virtual unsigned long AMBSINumErrors ()
virtual unsigned long AMBSINumTransactions ()
virtual float AMBSITemperature ()
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Public Member Functions inherited from ThermalLoggable
ThermalLoggable ()
virtual ~ThermalLoggable ()
Private Member Functions
FrontEndImpl (const FrontEndImpl &other)
FrontEndImpl & operator= (const FrontEndImpl &other)
Private Attributes
unsigned SN_m
this front end's serial number, numeric portion only.
std::string ESN_m
this front end's ESN (can serial number)
CartridgesContainer * carts_mp
PowerModulesContainer * powerMods_mp
FrontEndDatabase * dbObject_mp
CryostatImpl * cryostat_mp
FETIMImpl * fetim_mp
IFSwitchImpl * ifSwitch_mp
LPRImpl * lpr_mp
bool cpds_m
true if the CPDS is present.
bool connected_m
true if successfully connected to the FE.
ThermalLogger * thermalLogger_mp
unsigned int thermaLogInterval_m
bool hcStarted_m
bool hcReceiverIsCold_m
int hcFacility_m
int hcDataStatus_m
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Types inherited from FrontEndImplBase
enum MonitorControlOffset {
SPECIAL_MONITOR = 0x20000UL, SPECIAL_CONTROL = 0x21000UL, GET_AMBSI_VERSION_INFO = 0x0000, GET_SETUP_INFO = 0x0001,
GET_VERSION_INFO = 0x0002, GET_SPECIAL_MONITOR_RCA = 0x0003, GET_SPECIAL_CONTROL_RCA = 0x0004, GET_MONITOR_RCA = 0x0005,
GET_CONTROL_RCA = 0x0006, GET_PPCOMM_TIME = 0x0007, GET_FPGA_VERSION_INFO = 0x0008, GET_ESNS_FOUND = 0x000A,
GET_ESNS = 0x000B, GET_ERRORS_NUMBER = 0x000C, GET_NEXT_ERROR = 0x000D, GET_FE_MODE = 0x000E,
SET_EXIT_PROGRAM = 0x0000, SET_REBOOT = 0x0001, SET_FE_MODE = 0x000E, SET_READ_ESN = 0x000F,
POWER_NUM_MODULES_ENABLED = 0xA0A0, POWER_ENABLE_MODULE = 0xA00C
}
Protected Types inherited from AMBSIHardwareDevice
enum MonitorControlOffset {
AMBSI_BASE = 0x30000UL, AMBSI_SERIAL_NUMBER = 0x0000, AMBSI_FIRMWARE_REV = 0x0000, AMBSI_NUM_ERRORS = 0x0001,
AMBSI_NUM_TRANSACTIONS = 0x0002, AMBSI_TEMPERATURE = 0x0003
}
Protected Member Functions inherited from FrontEndImplBase
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Protected Attributes inherited from FrontEndImplBase
std::string AMBSILibraryVersion_value
std::string FEMCFirmwareVersion_value
std::string FEMCFPGAVersion_value
unsigned char FEMCGetESNsFound_value
std::string FEMCGetNextESN_value
unsigned char specialGetSetupInfo_value
unsigned char numEnabledModules_value
int numEnabledModules_status
unsigned short numErrors_value
int numErrors_status
unsigned short nextError_value
int nextError_status
unsigned char FEMode_value
int FEMode_status
AmbRelativeAddr numEnabledModules_RCA
AmbRelativeAddr powerEnableModule_RCA
AmbRelativeAddr numErrors_RCA
AmbRelativeAddr nextError_RCA
AmbRelativeAddr FEMode_RCA
Protected Attributes inherited from AMBSIHardwareDevice
std::string AMBSISerialNum_value
std::string AMBSIFirmwareRev_value
unsigned long AMBSINumErrors_value
unsigned long AMBSINumTransactions_value
float AMBSITemperature_value
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
The top-level FrontEnd class, giving the entire control interface for the Front End.
Definition at line 42 of file FrontEndImpl.h.
Constructor & Destructor Documentation
FrontEndImpl::FrontEndImpl (unsigned long channel, unsigned long nodeAddress, const std::string & ESN = "")
Definition at line 47 of file FrontEndImpl.cpp.
References initialize(), and FEHardwareDevice::setESN().
FrontEndImpl::~FrontEndImpl () virtual
Definition at line 72 of file FrontEndImpl.cpp.
References carts_mp, cryostat_mp, dbObject_mp, fetim_mp, ifSwitch_mp, lpr_mp, powerMods_mp, and thermalLogger_mp.
FrontEndImpl::FrontEndImpl (const FrontEndImpl & other) private
Member Function Documentation
bool FrontEndImpl::addCartridge (int port, WCAImpl & WCA, ColdCartImpl & coldCart)
Definition at line 736 of file FrontEndImpl.cpp.
References carts_mp.
Referenced by addCartridge().
bool FrontEndImpl::addCartridge (int port, WCAImpl & WCA)
Definition at line 740 of file FrontEndImpl.cpp.
References addCartridge(), and carts_mp.
bool FrontEndImpl::addCartridge (int port, ColdCartImpl & coldCart)
Definition at line 744 of file FrontEndImpl.cpp.
References addCartridge(), and carts_mp.
void FrontEndImpl::addCPDS ()
Definition at line 812 of file FrontEndImpl.cpp.
References cpds_m.
Referenced by FEConfig::ConfigManager::configure().
void FrontEndImpl::addCryostat ()
Definition at line 760 of file FrontEndImpl.cpp.
References cryostat_mp, and deleteCryostat().
Referenced by FEConfig::ConfigManager::configure().
void FrontEndImpl::addFETIM ()
Definition at line 773 of file FrontEndImpl.cpp.
References deleteFETIM(), and fetim_mp.
Referenced by FEConfig::ConfigManager::configure().
void FrontEndImpl::addIFSwitch ()
Definition at line 786 of file FrontEndImpl.cpp.
References deleteIFSwitch(), and ifSwitch_mp.
Referenced by FEConfig::ConfigManager::configure().
void FrontEndImpl::addLPR ()
Definition at line 799 of file FrontEndImpl.cpp.
References deleteLPR(), and lpr_mp.
Referenced by FEConfig::ConfigManager::configure().
bool FrontEndImpl::addPowerModule (PowerModuleImpl & module)
Definition at line 752 of file FrontEndImpl.cpp.
References powerMods_mp.
void FrontEndImpl::appendThermalLog (std::string & target) const virtual
append thermal information to a logging string
Implements ThermalLoggable.
Definition at line 1783 of file FrontEndImpl.cpp.
References carts_mp, cryostat_mp, fetim_mp, getAMBSITemperature(), ifSwitch_mp, and lpr_mp.
void FrontEndImpl::appendThermalLogHeader (std::string & target) const virtual
append thermal header information to a logging string
Implements ThermalLoggable.
Definition at line 1769 of file FrontEndImpl.cpp.
References carts_mp, cryostat_mp, fetim_mp, ifSwitch_mp, and lpr_mp.
void FrontEndImpl::cartAbortMeasurement (int port)
Definition at line 1514 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartAdjustLOPowerAmps (int port, int repeatCount = 1)
Definition at line 1244 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartAdjustPLL (int port, float targetCorrVoltage)
Definition at line 1043 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartAdjustYTO (int port, int steps)
Definition at line 1068 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartGetEnableLNABias (int port) const
Definition at line 1146 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetEnableLOPowerAmps (int port) const
Definition at line 1236 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetEnablePhotomixer (int port) const
Definition at line 1574 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetEnableSISBias (int port) const
Definition at line 1172 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetEnableSISMagnet (int port) const
Definition at line 1196 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetLocked (int port)
Definition at line 1034 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetLOFrequency (int port, double & freqLO, double & freqREF) const
Definition at line 995 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetLOPADrainVoltageSetting (int port, float * VDP0, float * VDP1)
Definition at line 1344 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetMonitorAMC (int port, WCAImpl::AMC_t & target) const
Definition at line 668 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetMonitorAux (int port, int pol, ColdCartImpl::Aux_t & target) const
Definition at line 723 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetMonitorLNA (int port, int pol, int sb, ColdCartImpl::LNA_t & target) const
Definition at line 712 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetMonitorPA (int port, WCAImpl::PA_t & target) const
Definition at line 679 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetMonitorPhotomixer (int port, WCAImpl::Photomixer_t & target) const
Definition at line 646 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetMonitorPLL (int port, WCAImpl::PLL_t & target) const
Definition at line 657 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetMonitorSIS (int port, int pol, int sb, ColdCartImpl::SIS_t & target) const
Definition at line 701 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetMonitorTemp (int port, ColdCartImpl::CartridgeTemp_t & target) const
Definition at line 690 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetMonitorYTO (int port, WCAImpl::YTO_t & target) const
Definition at line 637 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetNullPLLIntegrator (int port) const
Definition at line 1098 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetSISMagnet (short port, int pol, int sb, float * IMag)
Definition at line 1204 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartGetVJVD (int port, int pol, float * VJ1, float * VJ2, float * VD)
Definition at line 1329 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
const XYPlotArray & FrontEndImpl::cartGetXYData (int port) const
Definition at line 1522 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartHealthCheck (int port, int warmUpTimeSeconds)
Definition at line 366 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), carts_mp, PowerModuleImpl::PowerModule_t::currentN15V_value, PowerModuleImpl::PowerModule_t::currentN6V_value, PowerModuleImpl::PowerModule_t::currentP15V_value, PowerModuleImpl::PowerModule_t::currentP24V_value, PowerModuleImpl::PowerModule_t::currentP6V_value, PowerModuleImpl::PowerModule_t::currentP8V_value, dbObject_mp, getCartridgeOn(), hcDataStatus_m, hcFacility_m, hcReceiverIsCold_m, hcStarted_m, powerGetMonitorModule(), setCartridgeObserving(), SN_m, startHealthCheck(), PowerModuleImpl::PowerModule_t::voltageN15V_value, PowerModuleImpl::PowerModule_t::voltageN6V_value, PowerModuleImpl::PowerModule_t::voltageP15V_value, PowerModuleImpl::PowerModule_t::voltageP24V_value, PowerModuleImpl::PowerModule_t::voltageP6V_value, and PowerModuleImpl::PowerModule_t::voltageP8V_value.
Referenced by startHealthCheck().
bool FrontEndImpl::cartHealthCheckSaveIFPowerData (int port, const IFPowerDataSet & source)
Definition at line 456 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), carts_mp, FrontEndLVWrapper::configId, dbObject_mp, ColdCartImpl::hasSb2(), hcDataStatus_m, hcFacility_m, hcStarted_m, IFPowerDataSet::PCOLD_IF0, IFPowerDataSet::PCOLD_IF1, IFPowerDataSet::PCOLD_IF2, IFPowerDataSet::PCOLD_IF3, IFPowerDataSet::PHOT0_IF0, IFPowerDataSet::PHOT0_IF1, IFPowerDataSet::PHOT0_IF2, IFPowerDataSet::PHOT0_IF3, IFPowerDataSet::PHOT15_IF0, IFPowerDataSet::PHOT15_IF1, IFPowerDataSet::PHOT15_IF2, IFPowerDataSet::PHOT15_IF3, SN_m, IFPowerDataSet::YFACTOR_IF0, IFPowerDataSet::YFACTOR_IF1, IFPowerDataSet::YFACTOR_IF2, and IFPowerDataSet::YFACTOR_IF3.
bool FrontEndImpl::cartLockPLL (int port)
Definition at line 1005 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartMeasureFineLOSweep (int port, float tiltAngle, int pol = -1, const float * VJ = NULL, const float * IJ = NULL, const float * fixedVD = NULL, const double * LOStart = NULL, const double * LOStop = NULL, const double * LOStep = NULL, int repeatCount = 1)
Definition at line 1373 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), carts_mp, FrontEndLVWrapper::configId, dbObject_mp, and getDbConfigId().
bool FrontEndImpl::cartMeasureIFPowerVsVD (int port, int pol, float VDStart, float VDStop, float VDStep, bool doYFactor = false, int repeatCount = 1)
Definition at line 1472 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartMeasureIFPowerVsVJ (int port, int pol, int sb, float VJStart, float VJStop, float VJStep, bool doYFactor = false, int repeatCount = 1)
Definition at line 1445 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartMeasureIJvsSISMagnet (int port, int pol, int sb, float IMagStart, float IMagStop, float IMagStep, float VJLow, float VJHigh, float VJStep, int repeatCount = 1)
Definition at line 1423 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartMeasureIVCurve (int port, int pol, int sb, const float * VJlow_p = NULL, const float * VJhigh_p = NULL, const float * VJstep_p = NULL, int repeatCount = 1)
Definition at line 1401 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartMixerDeflux (int port, int pol, int sb, int IMagMax)
Definition at line 1498 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartNullPLLIntegrator (int port, bool enable = false)
Definition at line 1083 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartOptimizeIFPower (int port, bool doPol0, bool doPol1)
Definition at line 1287 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartPauseMonitor (int port, bool pauseWCA, bool pauseCC)
Definition at line 956 of file FrontEndImpl.cpp.
References carts_mp, and FEHardwareDevice::pauseMonitor().
bool FrontEndImpl::cartSetAMC (int port, const float * VDE = NULL, const float * VGE = NULL)
Definition at line 1358 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetEnableLNABias (int port, bool enable = false, int pol = -1, int sb = -1)
Definition at line 1131 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetEnableLNALEDs (int port, bool enable = false)
Definition at line 1529 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetEnableLO (int port, bool enable)
Definition at line 1259 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartSetEnablePhotomixer (int port, bool enable = false)
Definition at line 1559 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetEnableSISHeaters (int port, bool enable = false, int pol = -1, float targetTemp = 12.0, int timeout = 30)
Definition at line 1544 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetIFPower (int port, int pol, float powerSB1, float powerSB2)
Inject the current IF power level readings for a single port and polarization.
Used for optimizing mixer and LO power amp bias voltages.
Definition at line 1301 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartSetLNABias (int port, int pol = -1, int sb = -1, const float * VD1 = NULL, const float * ID1 = NULL, const float * VD2 = NULL, const float * ID2 = NULL, const float * VD3 = NULL, const float * ID3 = NULL)
Definition at line 1106 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetLOFrequency (int port, double freqLO, double freqFLOOG, int sbLock)
Definition at line 963 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetLOPower (int port, int pol, float percent)
Definition at line 1273 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::cartSetLOPowerAmps (int port, bool enable = false, const float * VDP0 = NULL, const float * VGP0 = NULL, const float * VDP1 = NULL, const float * VGP1 = NULL)
Definition at line 1214 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetSISBias (int port, bool enable = false, int pol = -1, int sb = -1, const float * VJ = NULL, int openLoop = -1)
Definition at line 1154 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetSISMagnet (int port, bool enable = false, int pol = -1, int sb = -1, const float * IMag = NULL)
Definition at line 1180 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
bool FrontEndImpl::cartSetVJVD (int port, int pol, float * VJ1, float * VJ2, float * VD)
Definition at line 1311 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), and carts_mp.
void FrontEndImpl::clearCartridgeObserving ()
Definition at line 943 of file FrontEndImpl.cpp.
References carts_mp.
Referenced by setCartridgeObserving().
bool FrontEndImpl::connected () const inline
Definition at line 52 of file FrontEndImpl.h.
References connected_m.
bool FrontEndImpl::cryostatGetMonitorModule (CryostatImpl::Cryostat_t & target) const
Definition at line 1648 of file FrontEndImpl.cpp.
References cryostat_mp.
Referenced by startHealthCheck().
bool FrontEndImpl::cryostatSetEnableBackingPump (bool enable)
Start/stop the backing pump.
Definition at line 1655 of file FrontEndImpl.cpp.
References cryostat_mp.
bool FrontEndImpl::cryostatSetEnableCryoPumping (bool enable)
Enable/disable the pump-down process.
Definition at line 1695 of file FrontEndImpl.cpp.
References cryostat_mp.
bool FrontEndImpl::cryostatSetEnableTurboPump (bool enable)
Start/stop the turbo pump.
Definition at line 1663 of file FrontEndImpl.cpp.
References cryostat_mp.
bool FrontEndImpl::cryostatSetEnableVacuumGauge (bool enable)
Enable/disable the vacuum gauge.
Definition at line 1687 of file FrontEndImpl.cpp.
References cryostat_mp.
bool FrontEndImpl::cryostatSetGateValveState (bool open)
Open/close the gate valve.
Definition at line 1671 of file FrontEndImpl.cpp.
References cryostat_mp.
bool FrontEndImpl::cryostatSetSolenoidValveState (bool open)
Open/close the solenoid valve.
Definition at line 1679 of file FrontEndImpl.cpp.
References cryostat_mp.
bool FrontEndImpl::deleteCartridge (int port)
Definition at line 748 of file FrontEndImpl.cpp.
References carts_mp.
void FrontEndImpl::deleteCPDS ()
Definition at line 816 of file FrontEndImpl.cpp.
References cpds_m.
void FrontEndImpl::deleteCryostat ()
Definition at line 765 of file FrontEndImpl.cpp.
References cryostat_mp, and stopMonitor().
Referenced by addCryostat().
void FrontEndImpl::deleteFETIM ()
Definition at line 778 of file FrontEndImpl.cpp.
References fetim_mp, and stopMonitor().
Referenced by addFETIM().
void FrontEndImpl::deleteIFSwitch ()
Definition at line 791 of file FrontEndImpl.cpp.
References ifSwitch_mp, and stopMonitor().
Referenced by addIFSwitch().
void FrontEndImpl::deleteLPR ()
Definition at line 804 of file FrontEndImpl.cpp.
References lpr_mp, and stopMonitor().
Referenced by addLPR().
bool FrontEndImpl::deletePowerModule (int port)
Definition at line 756 of file FrontEndImpl.cpp.
References powerMods_mp.
bool FrontEndImpl::fetimGetMonitorModule (FETIMImpl::FETIM_t & target) const
Definition at line 1705 of file FrontEndImpl.cpp.
References fetim_mp.
bool FrontEndImpl::fetimSetTriggerDewarN2Fill (bool enable)
Enable/disable the N2 fill trigger.
Definition at line 1712 of file FrontEndImpl.cpp.
References fetim_mp.
bool FrontEndImpl::finishHealthCheck ()
Definition at line 544 of file FrontEndImpl.cpp.
References hcDataStatus_m, hcFacility_m, hcReceiverIsCold_m, hcStarted_m, and lprSetEDFAModulationInput().
Referenced by startHealthCheck().
void FrontEndImpl::getAMBSIInfo (std::string & serialNum, std::string & firmwareRev, unsigned long & numErrors, unsigned long & numTransactions)
Definition at line 610 of file FrontEndImpl.cpp.
References AMBSIHardwareDevice::AMBSIFirmwareRev_value, AMBSIHardwareDevice::AMBSINumErrors_value, AMBSIHardwareDevice::AMBSINumTransactions_value, and AMBSIHardwareDevice::AMBSISerialNum_value.
float FrontEndImpl::getAMBSITemperature () const
Definition at line 629 of file FrontEndImpl.cpp.
References AMBSIHardwareDevice::AMBSITemperature_value.
Referenced by appendThermalLog().
int FrontEndImpl::getCartridgeObserving () const
Definition at line 948 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::getCartridgeOn (int port) const
Definition at line 952 of file FrontEndImpl.cpp.
References carts_mp.
Referenced by cartHealthCheck().
bool FrontEndImpl::getDbConfigId (FEICDataBase::ID_T & onfigId) const
Definition at line 168 of file FrontEndImpl.cpp.
References dbObject_mp, hcFacility_m, and SN_m.
Referenced by cartMeasureFineLOSweep(), and startHealthCheck().
void FrontEndImpl::getFirmwareInfo (std::string & AMBSILibraryVersion, std::string & FEMCFirmwareVersion, std::string & FEMCFPGAVersion)
Definition at line 621 of file FrontEndImpl.cpp.
References FrontEndImplBase::AMBSILibraryVersion_value, FrontEndImplBase::FEMCFirmwareVersion_value, and FrontEndImplBase::FEMCFPGAVersion_value.
bool FrontEndImpl::getNextError (unsigned char & moduleNum, unsigned char & errorNum, std::string & description)
fetch the next error from the FEMC error queue.
if none waiting returns false. else returns true and populates moduleNum, errorNum, and description with info.
Definition at line 101 of file FrontEndImpl.cpp.
References FEMCGetErrorDescription(), FrontEndImplBase::getNextError(), and FrontEndImplBase::getNumErrors().
bool FrontEndImpl::ifSwitchGetMonitorModule (IFSwitchImpl::IFSwitch_t & target) const
Definition at line 1606 of file FrontEndImpl.cpp.
References ifSwitch_mp.
Referenced by startHealthCheck().
bool FrontEndImpl::ifSwitchSetAttenuation (int pol = -1, int sb = -1, unsigned char atten = 15)
Definition at line 1613 of file FrontEndImpl.cpp.
References ifSwitch_mp.
bool FrontEndImpl::ifSwitchSetEnableTempServo (int pol = -1, int sb = -1, bool enable = false)
Definition at line 1630 of file FrontEndImpl.cpp.
References ifSwitch_mp.
Referenced by startHealthCheck().
void FrontEndImpl::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Reimplemented from FrontEndImplBase.
Definition at line 83 of file FrontEndImpl.cpp.
References AMBSIHardwareDevice::AMBSISerialNum(), connected_m, FrontEndImplBase::initialize(), and specialGetSetupInfo().
Referenced by FrontEndImpl().
bool FrontEndImpl::lprGetMonitorModule (LPRImpl::LPR_t & target) const
Definition at line 1723 of file FrontEndImpl.cpp.
References lpr_mp.
Referenced by startHealthCheck().
bool FrontEndImpl::lprSetEDFAModulationInput (float value)
Sets the EDFA modulation input value in Volts.
Definition at line 1754 of file FrontEndImpl.cpp.
References lpr_mp.
Referenced by finishHealthCheck(), and startHealthCheck().
bool FrontEndImpl::lprSetOpticalSwitchForceShutter ()
Enables the shutter (disables the laser) more forcefully (for debugging).
Definition at line 1746 of file FrontEndImpl.cpp.
References lpr_mp.
bool FrontEndImpl::lprSetOpticalSwitchPort (int port)
Set the optical switch output port and disable the shutter.
Definition at line 1730 of file FrontEndImpl.cpp.
References lpr_mp.
Referenced by setCartridgeObserving().
bool FrontEndImpl::lprSetOpticalSwitchShutter ()
Enables the shutter (disables the laser).
Definition at line 1738 of file FrontEndImpl.cpp.
References lpr_mp.
void FrontEndImpl::measureSISVoltageError (int port = 0)
Definition at line 583 of file FrontEndImpl.cpp.
References carts_mp.
FrontEndImpl& FrontEndImpl::operator= (const FrontEndImpl & other) private
bool FrontEndImpl::powerGetMonitorModule (int port, PowerModuleImpl::PowerModule_t & target) const
Definition at line 1585 of file FrontEndImpl.cpp.
References cpds_m, and powerMods_mp.
Referenced by cartHealthCheck().
unsigned short FrontEndImpl::powerGetMonitorNumEnabled ()
Definition at line 633 of file FrontEndImpl.cpp.
References FrontEndImplBase::numEnabledModules().
bool FrontEndImpl::powerSetEnableModule (int port, bool enable = false)
Definition at line 1592 of file FrontEndImpl.cpp.
References cpds_m, and powerMods_mp.
void FrontEndImpl::queryCartridgeState ()
Definition at line 558 of file FrontEndImpl.cpp.
References FEMCEventQueue::addEvent(), carts_mp, cpds_m, FEMCEventQueue::EVENT_INITIALIZE, ifSwitch_mp, powerMods_mp, setCartridgeObserving(), and setCartridgeOn().
bool FrontEndImpl::setCartridgeObserving (int port)
Definition at line 887 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), carts_mp, clearCartridgeObserving(), ifSwitch_mp, and lprSetOpticalSwitchPort().
Referenced by cartHealthCheck(), and queryCartridgeState().
bool FrontEndImpl::setCartridgeOff (int port)
Definition at line 854 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), carts_mp, cpds_m, FrontEndImplBase::powerEnableModule(), and powerMods_mp.
Referenced by startHealthCheck().
bool FrontEndImpl::setCartridgeOn (int port)
Definition at line 868 of file FrontEndImpl.cpp.
References FEMCEventQueue::addStatusMessage(), carts_mp, cpds_m, FrontEndImplBase::powerEnableModule(), and powerMods_mp.
Referenced by queryCartridgeState(), and startHealthCheck().
bool FrontEndImpl::setCartridgeReady (int port)
Definition at line 882 of file FrontEndImpl.cpp.
References carts_mp.
bool FrontEndImpl::setColdCartConfig (int port, const FEConfig::ColdCartConfig & params)
Definition at line 824 of file FrontEndImpl.cpp.
References carts_mp.
Referenced by FEConfig::ConfigManager::configureColdCart().
void FrontEndImpl::setFEMode (unsigned char val) virtual
Reimplemented from FrontEndImplBase.
Definition at line 127 of file FrontEndImpl.cpp.
References FrontEndImplBase::setFEMode().
void FrontEndImpl::setFineLOSweepIniFile (const std::string FineLoSweepIni) inline
Definition at line 208 of file FrontEndImpl.h.
References CartAssembly::setFineLOSweepIniFile().
void FrontEndImpl::setFrontEndSN (const std::string & SN)
Definition at line 596 of file FrontEndImpl.cpp.
References SN_m.
Referenced by FEConfig::ConfigManager::configure().
void FrontEndImpl::setThermalLogInterval (unsigned int interval)
set the frequency of thermal logging, in seconds.
Definition at line 1762 of file FrontEndImpl.cpp.
References thermalLogger_mp, and thermaLogInterval_m.
bool FrontEndImpl::setWCAConfig (int port, const FEConfig::WCAConfig & params)
Definition at line 833 of file FrontEndImpl.cpp.
References carts_mp.
Referenced by FEConfig::ConfigManager::configureWCA().
bool FrontEndImpl::setYIGLimits (int port, double FLOYIG, double FHIYIG)
Definition at line 842 of file FrontEndImpl.cpp.
References carts_mp.
void FrontEndImpl::shutdown () virtual
Reimplemented from FrontEndImplBase.
Definition at line 96 of file FrontEndImpl.cpp.
References connected_m, and FrontEndImplBase::shutdown().
unsigned char FrontEndImpl::specialGetSetupInfo () virtual
Reimplemented from FrontEndImplBase.
Definition at line 600 of file FrontEndImpl.cpp.
References AMBSIHardwareDevice::AMBSIFirmwareRev(), FrontEndImplBase::AMBSILibraryVersion(), AMBSIHardwareDevice::AMBSISerialNum(), FrontEndImplBase::FEMCFirmwareVersion(), FrontEndImplBase::FEMCFPGAVersion(), and FrontEndImplBase::specialGetSetupInfo().
Referenced by initialize().
bool FrontEndImpl::startHealthCheck (bool isPASData, bool fullAuto = false)
Definition at line 180 of file FrontEndImpl.cpp.
References AMBSIHardwareDevice::AMBSISerialNum(), cartHealthCheck(), carts_mp, cryostatGetMonitorModule(), CryostatImpl::Cryostat_t::cryostatTemperature0_value, CryostatImpl::Cryostat_t::cryostatTemperature10_value, CryostatImpl::Cryostat_t::cryostatTemperature11_value, CryostatImpl::Cryostat_t::cryostatTemperature12_value, CryostatImpl::Cryostat_t::cryostatTemperature1_value, CryostatImpl::Cryostat_t::cryostatTemperature2_value, CryostatImpl::Cryostat_t::cryostatTemperature3_value, CryostatImpl::Cryostat_t::cryostatTemperature4_value, CryostatImpl::Cryostat_t::cryostatTemperature5_value, CryostatImpl::Cryostat_t::cryostatTemperature6_value, CryostatImpl::Cryostat_t::cryostatTemperature7_value, CryostatImpl::Cryostat_t::cryostatTemperature8_value, CryostatImpl::Cryostat_t::cryostatTemperature9_value, dbObject_mp, LPRImpl::LPR_t::EDFALaserDriveCurrent_value, LPRImpl::LPR_t::EDFALaserPhotoDetectCurrent_value, LPRImpl::LPR_t::EDFALaserPumpTemperature_value, LPRImpl::LPR_t::EDFAModulationInput_value, LPRImpl::LPR_t::EDFAPhotoDetectCurrent_value, LPRImpl::LPR_t::EDFAPhotoDetectPower_value, finishHealthCheck(), getDbConfigId(), hcDataStatus_m, hcFacility_m, hcReceiverIsCold_m, hcStarted_m, ifSwitchGetMonitorModule(), ifSwitchSetEnableTempServo(), lprGetMonitorModule(), lprSetEDFAModulationInput(), LPRImpl::LPR_t::LPRTemperature0_value, LPRImpl::LPR_t::LPRTemperature1_value, IFSwitchImpl::IFSwitch_t::pol0Sb1AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol0Sb2AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol1Sb1AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol1Sb2AssemblyTemp_value, setCartridgeOff(), setCartridgeOn(), and SN_m.
Referenced by cartHealthCheck().
void FrontEndImpl::startMonitor () virtual
start the monitor thread.
Reimplemented from FEHardwareDevice.
Definition at line 136 of file FrontEndImpl.cpp.
References cpds_m, cryostat_mp, fetim_mp, ifSwitch_mp, lpr_mp, powerMods_mp, FEHardwareDevice::startMonitor(), thermalLogger_mp, and thermaLogInterval_m.
void FrontEndImpl::stopMonitor () virtual
stop the monitor thread.
Reimplemented from FEHardwareDevice.
Definition at line 152 of file FrontEndImpl.cpp.
References carts_mp, cryostat_mp, fetim_mp, ifSwitch_mp, lpr_mp, powerMods_mp, FEHardwareDevice::stopMonitor(), and thermalLogger_mp.
Referenced by deleteCryostat(), deleteFETIM(), deleteIFSwitch(), and deleteLPR().
Member Data Documentation
CartridgesContainer* FrontEndImpl::carts_mp private
Definition at line 328 of file FrontEndImpl.h.
Referenced by addCartridge(), appendThermalLog(), appendThermalLogHeader(), cartAbortMeasurement(), cartAdjustLOPowerAmps(), cartAdjustPLL(), cartAdjustYTO(), cartGetEnableLNABias(), cartGetEnableLOPowerAmps(), cartGetEnablePhotomixer(), cartGetEnableSISBias(), cartGetEnableSISMagnet(), cartGetLocked(), cartGetLOFrequency(), cartGetLOPADrainVoltageSetting(), cartGetMonitorAMC(), cartGetMonitorAux(), cartGetMonitorLNA(), cartGetMonitorPA(), cartGetMonitorPhotomixer(), cartGetMonitorPLL(), cartGetMonitorSIS(), cartGetMonitorTemp(), cartGetMonitorYTO(), cartGetNullPLLIntegrator(), cartGetSISMagnet(), cartGetVJVD(), cartGetXYData(), cartHealthCheck(), cartHealthCheckSaveIFPowerData(), cartLockPLL(), cartMeasureFineLOSweep(), cartMeasureIFPowerVsVD(), cartMeasureIFPowerVsVJ(), cartMeasureIJvsSISMagnet(), cartMeasureIVCurve(), cartMixerDeflux(), cartNullPLLIntegrator(), cartOptimizeIFPower(), cartPauseMonitor(), cartSetAMC(), cartSetEnableLNABias(), cartSetEnableLNALEDs(), cartSetEnableLO(), cartSetEnablePhotomixer(), cartSetEnableSISHeaters(), cartSetIFPower(), cartSetLNABias(), cartSetLOFrequency(), cartSetLOPower(), cartSetLOPowerAmps(), cartSetSISBias(), cartSetSISMagnet(), cartSetVJVD(), clearCartridgeObserving(), deleteCartridge(), getCartridgeObserving(), getCartridgeOn(), measureSISVoltageError(), queryCartridgeState(), setCartridgeObserving(), setCartridgeOff(), setCartridgeOn(), setCartridgeReady(), setColdCartConfig(), setWCAConfig(), setYIGLimits(), startHealthCheck(), stopMonitor(), and ~FrontEndImpl().
bool FrontEndImpl::connected_m private
true if successfully connected to the FE.
Definition at line 342 of file FrontEndImpl.h.
Referenced by connected(), initialize(), and shutdown().
bool FrontEndImpl::cpds_m private
true if the CPDS is present.
Definition at line 341 of file FrontEndImpl.h.
Referenced by addCPDS(), deleteCPDS(), powerGetMonitorModule(), powerSetEnableModule(), queryCartridgeState(), setCartridgeOff(), setCartridgeOn(), and startMonitor().
CryostatImpl* FrontEndImpl::cryostat_mp private
Definition at line 337 of file FrontEndImpl.h.
Referenced by addCryostat(), appendThermalLog(), appendThermalLogHeader(), cryostatGetMonitorModule(), cryostatSetEnableBackingPump(), cryostatSetEnableCryoPumping(), cryostatSetEnableTurboPump(), cryostatSetEnableVacuumGauge(), cryostatSetGateValveState(), cryostatSetSolenoidValveState(), deleteCryostat(), startMonitor(), stopMonitor(), and ~FrontEndImpl().
FrontEndDatabase* FrontEndImpl::dbObject_mp private
Definition at line 334 of file FrontEndImpl.h.
Referenced by cartHealthCheck(), cartHealthCheckSaveIFPowerData(), cartMeasureFineLOSweep(), getDbConfigId(), startHealthCheck(), and ~FrontEndImpl().
std::string FrontEndImpl::ESN_m private
this front end's ESN (can serial number)
Definition at line 325 of file FrontEndImpl.h.
FETIMImpl* FrontEndImpl::fetim_mp private
Definition at line 338 of file FrontEndImpl.h.
Referenced by addFETIM(), appendThermalLog(), appendThermalLogHeader(), deleteFETIM(), fetimGetMonitorModule(), fetimSetTriggerDewarN2Fill(), startMonitor(), stopMonitor(), and ~FrontEndImpl().
int FrontEndImpl::hcDataStatus_m private
Definition at line 352 of file FrontEndImpl.h.
Referenced by cartHealthCheck(), cartHealthCheckSaveIFPowerData(), finishHealthCheck(), and startHealthCheck().
int FrontEndImpl::hcFacility_m private
Definition at line 351 of file FrontEndImpl.h.
Referenced by cartHealthCheck(), cartHealthCheckSaveIFPowerData(), finishHealthCheck(), getDbConfigId(), and startHealthCheck().
bool FrontEndImpl::hcReceiverIsCold_m private
Definition at line 350 of file FrontEndImpl.h.
Referenced by cartHealthCheck(), finishHealthCheck(), and startHealthCheck().
bool FrontEndImpl::hcStarted_m private
Definition at line 349 of file FrontEndImpl.h.
Referenced by cartHealthCheck(), cartHealthCheckSaveIFPowerData(), finishHealthCheck(), and startHealthCheck().
IFSwitchImpl* FrontEndImpl::ifSwitch_mp private
Definition at line 339 of file FrontEndImpl.h.
Referenced by addIFSwitch(), appendThermalLog(), appendThermalLogHeader(), deleteIFSwitch(), ifSwitchGetMonitorModule(), ifSwitchSetAttenuation(), ifSwitchSetEnableTempServo(), queryCartridgeState(), setCartridgeObserving(), startMonitor(), stopMonitor(), and ~FrontEndImpl().
LPRImpl* FrontEndImpl::lpr_mp private
Definition at line 340 of file FrontEndImpl.h.
Referenced by addLPR(), appendThermalLog(), appendThermalLogHeader(), deleteLPR(), lprGetMonitorModule(), lprSetEDFAModulationInput(), lprSetOpticalSwitchForceShutter(), lprSetOpticalSwitchPort(), lprSetOpticalSwitchShutter(), startMonitor(), stopMonitor(), and ~FrontEndImpl().
PowerModulesContainer* FrontEndImpl::powerMods_mp private
Definition at line 331 of file FrontEndImpl.h.
Referenced by addPowerModule(), deletePowerModule(), powerGetMonitorModule(), powerSetEnableModule(), queryCartridgeState(), setCartridgeOff(), setCartridgeOn(), startMonitor(), stopMonitor(), and ~FrontEndImpl().
unsigned FrontEndImpl::SN_m private
this front end's serial number, numeric portion only.
Definition at line 324 of file FrontEndImpl.h.
Referenced by cartHealthCheck(), cartHealthCheckSaveIFPowerData(), getDbConfigId(), setFrontEndSN(), and startHealthCheck().
ThermalLogger* FrontEndImpl::thermalLogger_mp private
Definition at line 345 of file FrontEndImpl.h.
Referenced by setThermalLogInterval(), startMonitor(), stopMonitor(), and ~FrontEndImpl().
unsigned int FrontEndImpl::thermaLogInterval_m private
Definition at line 346 of file FrontEndImpl.h.
Referenced by setThermalLogInterval(), and startMonitor().
The documentation for this class was generated from the following files:
FrontEndImpl.h
FrontEndImpl.cpp