FrontEndControl2: FEConfig::ConfigProvider Class Reference
FEConfig::ConfigProvider Class Reference abstract
A ConfigProver loads FE configuration data from a database.
#include <ConfigProvider.h>
Public Member Functions
ConfigProvider ()
virtual ~ConfigProvider ()
virtual bool exists (unsigned keyFacility, unsigned configId) const =0
return true if the configuration specified by (keyFacility, configId) exists in the database, false otherwise.
virtual bool getConfiguration (unsigned keyFacility, unsigned configId, Configuration::Record &target) const =0
get the top-level configuration record specified by (keyFacility, configId).
virtual bool getAllConfigurations (unsigned keyFacility, std::vector< Configuration::Record > &target) const
get all configurations for the given provider.
virtual bool saveConfiguration (const Configuration &source)
write out the entire configuration to the ini file.
virtual bool getFrontEndConfig (unsigned keyFacility, unsigned keyFrontEnd, FrontEndConfig &target) const =0
get the FrontEndConfig portion of the specified config.
virtual bool getCryostatConfig (unsigned keyFacility, unsigned keyCryostat, CryostatConfig &target) const =0
get the CryostatConfig portion of the specified config.
virtual bool getLPRConfig (unsigned keyFacility, unsigned keyLPR, LPRConfig &target) const =0
get the LPRConfig portion of the specified config.
virtual bool getCartAssemblyConfig (CartAssemblyID id, CartAssemblyConfig &target) const =0
load the configuration for the specified CartAssembly.
virtual bool getColdCartConfig (unsigned keyFacility, unsigned keyColdCart, ColdCartConfig &target) const =0
get the ColdCartConfig portion of the specified config for the specified band.
virtual bool getWCAConfig (unsigned keyFacility, unsigned keyWCA, WCAConfig &target) const =0
get the WCAConfig portion of the specified config for the specified band.
Private Member Functions
ConfigProvider (const ConfigProvider &other)
copy construct is private and forbidden.
ConfigProvider & operator= (const ConfigProvider &other)
assignment is private and forbidden.
Detailed Description
A ConfigProver loads FE configuration data from a database.
The abstract base class declares the interface that a real provider must implement.
Definition at line 41 of file ConfigProvider.h.
Constructor & Destructor Documentation
FEConfig::ConfigProvider::ConfigProvider () inline
Definition at line 43 of file ConfigProvider.h.
virtual FEConfig::ConfigProvider::~ConfigProvider () inline virtual
Definition at line 45 of file ConfigProvider.h.
FEConfig::ConfigProvider::ConfigProvider (const ConfigProvider & other) private
copy construct is private and forbidden.
Member Function Documentation
virtual bool FEConfig::ConfigProvider::exists (unsigned keyFacility, unsigned configId) const pure virtual
return true if the configuration specified by (keyFacility, configId) exists in the database, false otherwise.
Implemented in FEConfig::ConfigProviderMySQL, and FEConfig::ConfigProviderIniFile.
Referenced by FEConfig::Configuration::load().
virtual bool FEConfig::ConfigProvider::getAllConfigurations (unsigned keyFacility, std::vector< Configuration::Record > & target) const inline virtual
get all configurations for the given provider.
Reimplemented in FEConfig::ConfigProviderIniFile.
Definition at line 56 of file ConfigProvider.h.
virtual bool FEConfig::ConfigProvider::getCartAssemblyConfig (CartAssemblyID id, CartAssemblyConfig & target) const pure virtual
load the configuration for the specified CartAssembly.
Implemented in FEConfig::ConfigProviderIniFile, and FEConfig::ConfigProviderMySQL.
Referenced by FEConfig::Configuration::load().
virtual bool FEConfig::ConfigProvider::getColdCartConfig (unsigned keyFacility, unsigned keyColdCart, ColdCartConfig & target) const pure virtual
get the ColdCartConfig portion of the specified config for the specified band.
returns false if that portion is not available or on error.
Implemented in FEConfig::ConfigProviderIniFile, and FEConfig::ConfigProviderMySQL.
virtual bool FEConfig::ConfigProvider::getConfiguration (unsigned keyFacility, unsigned configId, Configuration::Record & target) const pure virtual
get the top-level configuration record specified by (keyFacility, configId).
returns false if the config does not exist or on error.
Implemented in FEConfig::ConfigProviderMySQL, and FEConfig::ConfigProviderIniFile.
Referenced by FEConfig::Configuration::load().
virtual bool FEConfig::ConfigProvider::getCryostatConfig (unsigned keyFacility, unsigned keyCryostat, CryostatConfig & target) const pure virtual
get the CryostatConfig portion of the specified config.
returns false if that portion is not available or on error.
Implemented in FEConfig::ConfigProviderIniFile, and FEConfig::ConfigProviderMySQL.
virtual bool FEConfig::ConfigProvider::getFrontEndConfig (unsigned keyFacility, unsigned keyFrontEnd, FrontEndConfig & target) const pure virtual
get the FrontEndConfig portion of the specified config.
returns false if that portion is not available or on error.
Implemented in FEConfig::ConfigProviderIniFile, and FEConfig::ConfigProviderMySQL.
Referenced by FEConfig::Configuration::load().
virtual bool FEConfig::ConfigProvider::getLPRConfig (unsigned keyFacility, unsigned keyLPR, LPRConfig & target) const pure virtual
get the LPRConfig portion of the specified config.
returns false if that portion is not available or on error.
Implemented in FEConfig::ConfigProviderIniFile, and FEConfig::ConfigProviderMySQL.
virtual bool FEConfig::ConfigProvider::getWCAConfig (unsigned keyFacility, unsigned keyWCA, WCAConfig & target) const pure virtual
get the WCAConfig portion of the specified config for the specified band.
returns false if that portion is not available or on error.
Implemented in FEConfig::ConfigProviderIniFile, and FEConfig::ConfigProviderMySQL.
ConfigProvider& FEConfig::ConfigProvider::operator= (const ConfigProvider & other) private
assignment is private and forbidden.
virtual bool FEConfig::ConfigProvider::saveConfiguration (const Configuration & source) inline virtual
write out the entire configuration to the ini file.
Reimplemented in FEConfig::ConfigProviderIniFile.
Definition at line 60 of file ConfigProvider.h.
Referenced by FEConfig::Configuration::save().
The documentation for this class was generated from the following file:
CONFIG/ConfigProvider.h