FrontEndControl2: LPRImpl Class Reference
LPRImpl Class Reference
implementation class for the IF Switch module
#include <LPRImpl.h>
Classes
struct LPR_t
Public Member Functions
LPRImpl (unsigned long channel, unsigned long nodeAddress, const std::string &ESN="")
virtual ~LPRImpl ()
bool setObservingBand (int band)
int getObservingBand () const
bool getMonitorLPR (LPR_t &target)
void appendThermalLog (std::string &target) const
append thermal information to a logging string
void appendThermalLogHeader (std::string &target) const
append thermal header information to a logging string
Public Member Functions inherited from LPRImplBase
LPRImplBase (const std::string &name)
virtual ~LPRImplBase ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual float LPRTemperature0 ()
virtual float LPRTemperature1 ()
virtual unsigned char opticalSwitchPort ()
virtual bool opticalSwitchShutter ()
virtual bool opticalSwitchState ()
virtual bool opticalSwitchBusy ()
virtual float EDFALaserPumpTemperature ()
virtual float EDFALaserDriveCurrent ()
virtual float EDFALaserPhotoDetectCurrent ()
virtual float EDFAPhotoDetectCurrent ()
virtual float EDFAPhotoDetectPower ()
virtual float EDFAModulationInput ()
virtual void opticalSwitchPort (unsigned char val)
virtual void opticalSwitchShutter (bool val)
virtual void opticalSwitchForceShutter (bool val)
virtual void EDFAModulationInput (float val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Public Member Functions inherited from ThermalLoggable
ThermalLoggable ()
virtual ~ThermalLoggable ()
Private Attributes
int observingBand_m
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Types inherited from LPRImplBase
enum MonitorControlOffset {
LPR_TEMPERATURE_0 = 0x0000, LPR_TEMPERATURE_1 = 0x0010, OPTICAL_SWITCH_PORT = 0x0020, OPTICAL_SWITCH_SHUTTER = 0x0022,
OPTICAL_SWITCH_FORCE_SHUTTER = 0x0024, OPTICAL_SWITCH_STATE = 0x0026, OPTICAL_SWITCH_BUSY = 0x0028, EDFA_LASER_PUMP_TEMPERATURE = 0x0030,
EDFA_LASER_DRIVE_CURRENT = 0x0031, EDFA_LASER_PHOTODETECT_CURRENT = 0x0032, EDFA_PHOTODETECT_CURRENT = 0x0034, EDFA_PHOTODETECT_POWER = 0x0036,
EDFA_MODULATION_INPUT = 0x0038, EDFA_DRIVER_TEMPERATURE_ALARM = 0x003C
}
Protected Member Functions inherited from LPRImplBase
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Protected Attributes inherited from LPRImplBase
float LPRTemperature0_value
float LPRTemperature1_value
unsigned char opticalSwitchPort_value
bool opticalSwitchShutter_value
bool opticalSwitchState_value
bool opticalSwitchBusy_value
float EDFALaserPumpTemperature_value
float EDFALaserDriveCurrent_value
float EDFALaserPhotoDetectCurrent_value
float EDFAPhotoDetectCurrent_value
float EDFAPhotoDetectPower_value
float EDFAModulationInput_value
int LPRTemperature0_status
int LPRTemperature1_status
int opticalSwitchPort_status
int opticalSwitchShutter_status
int opticalSwitchForceShutter_status
int opticalSwitchState_status
int opticalSwitchBusy_status
int EDFALaserPumpTemperature_status
int EDFALaserDriveCurrent_status
int EDFALaserPhotoDetectCurrent_status
int EDFAPhotoDetectCurrent_status
int EDFAPhotoDetectPower_status
int EDFAModulationInput_status
AmbRelativeAddr baseRCA
AmbRelativeAddr LPRTemperature0_RCA
AmbRelativeAddr LPRTemperature1_RCA
AmbRelativeAddr opticalSwitchPort_RCA
AmbRelativeAddr opticalSwitchShutter_RCA
AmbRelativeAddr opticalSwitchForceShutter_RCA
AmbRelativeAddr opticalSwitchState_RCA
AmbRelativeAddr opticalSwitchBusy_RCA
AmbRelativeAddr EDFALaserPumpTemperature_RCA
AmbRelativeAddr EDFALaserDriveCurrent_RCA
AmbRelativeAddr EDFALaserPhotoDetectCurrent_RCA
AmbRelativeAddr EDFAPhotoDetectCurrent_RCA
AmbRelativeAddr EDFAPhotoDetectPower_RCA
AmbRelativeAddr EDFAModulationInput_RCA
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
implementation class for the IF Switch module
Definition at line 29 of file LPRImpl.h.
Constructor & Destructor Documentation
LPRImpl::LPRImpl (unsigned long channel, unsigned long nodeAddress, const std::string & ESN = "")
Definition at line 26 of file LPRImpl.cpp.
References LPRImplBase::initialize(), and FEHardwareDevice::setESN().
virtual LPRImpl::~LPRImpl () inline virtual
Definition at line 34 of file LPRImpl.h.
Member Function Documentation
void LPRImpl::appendThermalLog (std::string & target) const virtual
append thermal information to a logging string
Implements ThermalLoggable.
Definition at line 71 of file LPRImpl.cpp.
References LPRImplBase::EDFALaserPumpTemperature_value, LPRImplBase::LPRTemperature0_value, and LPRImplBase::LPRTemperature1_value.
void LPRImpl::appendThermalLogHeader (std::string & target) const virtual
append thermal header information to a logging string
Implements ThermalLoggable.
Definition at line 81 of file LPRImpl.cpp.
bool LPRImpl::getMonitorLPR (LPR_t & target)
Definition at line 53 of file LPRImpl.cpp.
References LPRImpl::LPR_t::EDFALaserDriveCurrent_value, LPRImplBase::EDFALaserDriveCurrent_value, LPRImpl::LPR_t::EDFALaserPhotoDetectCurrent_value, LPRImplBase::EDFALaserPhotoDetectCurrent_value, LPRImpl::LPR_t::EDFALaserPumpTemperature_value, LPRImplBase::EDFALaserPumpTemperature_value, LPRImpl::LPR_t::EDFAModulationInput_value, LPRImplBase::EDFAModulationInput_value, LPRImpl::LPR_t::EDFAPhotoDetectCurrent_value, LPRImplBase::EDFAPhotoDetectCurrent_value, LPRImpl::LPR_t::EDFAPhotoDetectPower_value, LPRImplBase::EDFAPhotoDetectPower_value, LPRImpl::LPR_t::LPRTemperature0_value, LPRImplBase::LPRTemperature0_value, LPRImpl::LPR_t::LPRTemperature1_value, LPRImplBase::LPRTemperature1_value, LPRImpl::LPR_t::opticalSwitchBusy_value, LPRImplBase::opticalSwitchBusy_value, LPRImplBase::opticalSwitchPort(), LPRImpl::LPR_t::opticalSwitchPort_value, LPRImpl::LPR_t::opticalSwitchShutter_value, LPRImplBase::opticalSwitchShutter_value, LPRImpl::LPR_t::opticalSwitchState_value, and LPRImplBase::opticalSwitchState_value.
int LPRImpl::getObservingBand () const inline
Definition at line 39 of file LPRImpl.h.
References observingBand_m.
bool LPRImpl::setObservingBand (int band)
Definition at line 36 of file LPRImpl.cpp.
References observingBand_m, LPRImplBase::opticalSwitchBusy(), and LPRImplBase::opticalSwitchPort().
Member Data Documentation
int LPRImpl::observingBand_m private
Definition at line 66 of file LPRImpl.h.
Referenced by getObservingBand(), and setObservingBand().
The documentation for this class was generated from the following files:
LPRImpl.h
LPRImpl.cpp