FrontEndControl2: PowerModuleImpl Class Reference
PowerModuleImpl Class Reference
implementation class for the Power Distribution module
#include <PowerModuleImpl.h>
Classes
struct PowerModule_t
Public Member Functions
PowerModuleImpl (unsigned long channel, unsigned long nodeAddress, const std::string &name, int port)
virtual ~PowerModuleImpl ()
bool getEnable () const
void setEnable ()
void clearEnable ()
bool getMonitorPowerModule (PowerModule_t &target) const
Public Member Functions inherited from PowerModuleImplBase
PowerModuleImplBase (const std::string &name, int port)
virtual ~PowerModuleImplBase ()
int getPort () const
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual float voltageP6V ()
virtual float currentP6V ()
virtual float voltageN6V ()
virtual float currentN6V ()
virtual float voltageP15V ()
virtual float currentP15V ()
virtual float voltageN15V ()
virtual float currentN15V ()
virtual float voltageP24V ()
virtual float currentP24V ()
virtual float voltageP8V ()
virtual float currentP8V ()
virtual bool enableModule ()
virtual void enableModule (bool val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Private Member Functions
PowerModuleImpl ()
PowerModuleImpl (const PowerModuleImpl &other)
PowerModuleImpl & operator= (const PowerModuleImpl &other)
Private Attributes
bool enable_m
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Types inherited from PowerModuleImplBase
enum MonitorControlOffset {
CURRENT_P6V = 0x0000, VOLTAGE_P6V = 0x0001, CURRENT_N6V = 0x0002, VOLTAGE_N6V = 0x0003,
CURRENT_P15V = 0x0004, VOLTAGE_P15V = 0x0005, CURRENT_N15V = 0x0006, VOLTAGE_N15V = 0x0007,
CURRENT_N24V = 0x0008, VOLTAGE_P24V = 0x0009, CURRENT_P8V = 0x000A, VOLTAGE_P8V = 0x000B,
ENABLE_MODULE = 0x000C
}
Protected Member Functions inherited from PowerModuleImplBase
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Protected Attributes inherited from PowerModuleImplBase
float voltageP6V_value
float currentP6V_value
float voltageN6V_value
float currentN6V_value
float voltageP15V_value
float currentP15V_value
float voltageN15V_value
float currentN15V_value
float voltageP24V_value
float currentP24V_value
float voltageP8V_value
float currentP8V_value
bool enableModule_value
int voltageP6V_status
int currentP6V_status
int voltageN6V_status
int currentN6V_status
int voltageP15V_status
int currentP15V_status
int voltageN15V_status
int currentN15V_status
int voltageP24V_status
int currentP24V_status
int voltageP8V_status
int currentP8V_status
int enableModule_status
AmbRelativeAddr baseRCA
AmbRelativeAddr voltageP6V_RCA
AmbRelativeAddr currentP6V_RCA
AmbRelativeAddr voltageN6V_RCA
AmbRelativeAddr currentN6V_RCA
AmbRelativeAddr voltageP15V_RCA
AmbRelativeAddr currentP15V_RCA
AmbRelativeAddr voltageN15V_RCA
AmbRelativeAddr currentN15V_RCA
AmbRelativeAddr voltageP24V_RCA
AmbRelativeAddr currentP24V_RCA
AmbRelativeAddr voltageP8V_RCA
AmbRelativeAddr currentP8V_RCA
AmbRelativeAddr enableModule_RCA
int port_m
to which FEMC port is this module connected.
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
implementation class for the Power Distribution module
Definition at line 28 of file PowerModuleImpl.h.
Constructor & Destructor Documentation
PowerModuleImpl::PowerModuleImpl (unsigned long channel, unsigned long nodeAddress, const std::string & name, int port)
Definition at line 33 of file PowerModuleImpl.cpp.
References enable_m, PowerModuleImplBase::enableModule(), and PowerModuleImplBase::initialize().
virtual PowerModuleImpl::~PowerModuleImpl () inline virtual
Definition at line 34 of file PowerModuleImpl.h.
PowerModuleImpl::PowerModuleImpl () private
PowerModuleImpl::PowerModuleImpl (const PowerModuleImpl & other) private
Member Function Documentation
void PowerModuleImpl::clearEnable ()
Definition at line 50 of file PowerModuleImpl.cpp.
References enable_m, PowerModuleImplBase::enableModule(), and PowerModuleImplBase::port_m.
bool PowerModuleImpl::getEnable () const inline
Definition at line 37 of file PowerModuleImpl.h.
References enable_m.
bool PowerModuleImpl::getMonitorPowerModule (PowerModule_t & target) const
Definition at line 56 of file PowerModuleImpl.cpp.
References PowerModuleImpl::PowerModule_t::currentN15V_value, PowerModuleImplBase::currentN15V_value, PowerModuleImpl::PowerModule_t::currentN6V_value, PowerModuleImplBase::currentN6V_value, PowerModuleImpl::PowerModule_t::currentP15V_value, PowerModuleImplBase::currentP15V_value, PowerModuleImpl::PowerModule_t::currentP24V_value, PowerModuleImplBase::currentP24V_value, PowerModuleImpl::PowerModule_t::currentP6V_value, PowerModuleImplBase::currentP6V_value, PowerModuleImpl::PowerModule_t::currentP8V_value, PowerModuleImplBase::currentP8V_value, PowerModuleImpl::PowerModule_t::enableModule_value, PowerModuleImplBase::enableModule_value, PowerModuleImpl::PowerModule_t::voltageN15V_value, PowerModuleImplBase::voltageN15V_value, PowerModuleImpl::PowerModule_t::voltageN6V_value, PowerModuleImplBase::voltageN6V_value, PowerModuleImpl::PowerModule_t::voltageP15V_value, PowerModuleImplBase::voltageP15V_value, PowerModuleImpl::PowerModule_t::voltageP24V_value, PowerModuleImplBase::voltageP24V_value, PowerModuleImpl::PowerModule_t::voltageP6V_value, PowerModuleImplBase::voltageP6V_value, PowerModuleImpl::PowerModule_t::voltageP8V_value, and PowerModuleImplBase::voltageP8V_value.
PowerModuleImpl& PowerModuleImpl::operator= (const PowerModuleImpl & other) private
void PowerModuleImpl::setEnable ()
Definition at line 44 of file PowerModuleImpl.cpp.
References enable_m, PowerModuleImplBase::enableModule(), and PowerModuleImplBase::port_m.
Member Data Documentation
bool PowerModuleImpl::enable_m private
Definition at line 65 of file PowerModuleImpl.h.
Referenced by clearEnable(), getEnable(), PowerModuleImpl(), and setEnable().
The documentation for this class was generated from the following files:
PowerModuleImpl.h
PowerModuleImpl.cpp