FrontEndControl2: PowerModuleImplBase Class Reference
PowerModuleImplBase Class Reference
#include <PowerModuleImplBase.h>
Public Member Functions
PowerModuleImplBase (const std::string &name, int port)
virtual ~PowerModuleImplBase ()
int getPort () const
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual float voltageP6V ()
virtual float currentP6V ()
virtual float voltageN6V ()
virtual float currentN6V ()
virtual float voltageP15V ()
virtual float currentP15V ()
virtual float voltageN15V ()
virtual float currentN15V ()
virtual float voltageP24V ()
virtual float currentP24V ()
virtual float voltageP8V ()
virtual float currentP8V ()
virtual bool enableModule ()
virtual void enableModule (bool val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Protected Types
enum MonitorControlOffset {
CURRENT_P6V = 0x0000, VOLTAGE_P6V = 0x0001, CURRENT_N6V = 0x0002, VOLTAGE_N6V = 0x0003,
CURRENT_P15V = 0x0004, VOLTAGE_P15V = 0x0005, CURRENT_N15V = 0x0006, VOLTAGE_N15V = 0x0007,
CURRENT_N24V = 0x0008, VOLTAGE_P24V = 0x0009, CURRENT_P8V = 0x000A, VOLTAGE_P8V = 0x000B,
ENABLE_MODULE = 0x000C
}
Protected Member Functions
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Protected Attributes
float voltageP6V_value
float currentP6V_value
float voltageN6V_value
float currentN6V_value
float voltageP15V_value
float currentP15V_value
float voltageN15V_value
float currentN15V_value
float voltageP24V_value
float currentP24V_value
float voltageP8V_value
float currentP8V_value
bool enableModule_value
int voltageP6V_status
int currentP6V_status
int voltageN6V_status
int currentN6V_status
int voltageP15V_status
int currentP15V_status
int voltageN15V_status
int currentN15V_status
int voltageP24V_status
int currentP24V_status
int voltageP8V_status
int currentP8V_status
int enableModule_status
AmbRelativeAddr baseRCA
AmbRelativeAddr voltageP6V_RCA
AmbRelativeAddr currentP6V_RCA
AmbRelativeAddr voltageN6V_RCA
AmbRelativeAddr currentN6V_RCA
AmbRelativeAddr voltageP15V_RCA
AmbRelativeAddr currentP15V_RCA
AmbRelativeAddr voltageN15V_RCA
AmbRelativeAddr currentN15V_RCA
AmbRelativeAddr voltageP24V_RCA
AmbRelativeAddr currentP24V_RCA
AmbRelativeAddr voltageP8V_RCA
AmbRelativeAddr currentP8V_RCA
AmbRelativeAddr enableModule_RCA
int port_m
to which FEMC port is this module connected.
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
PowerModuleImplBase (const PowerModuleImplBase &other)
void logMon (bool printHeader=false) const
Private Attributes
Time lastMonitorTime
int monitorPhase
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 32 of file PowerModuleImplBase.h.
Member Enumeration Documentation
enum PowerModuleImplBase::MonitorControlOffset protected
Enumerator
CURRENT_P6V
VOLTAGE_P6V
CURRENT_N6V
VOLTAGE_N6V
CURRENT_P15V
VOLTAGE_P15V
CURRENT_N15V
VOLTAGE_N15V
CURRENT_N24V
VOLTAGE_P24V
CURRENT_P8V
VOLTAGE_P8V
ENABLE_MODULE
Definition at line 65 of file PowerModuleImplBase.h.
Constructor & Destructor Documentation
PowerModuleImplBase::PowerModuleImplBase (const std::string & name, int port)
Definition at line 31 of file PowerModuleImplBase.cpp.
References baseRCA, CURRENT_N15V, CURRENT_N24V, CURRENT_N6V, CURRENT_P15V, CURRENT_P6V, CURRENT_P8V, currentN15V(), currentN15V_RCA, currentN15V_value, currentN6V(), currentN6V_RCA, currentN6V_value, currentP15V(), currentP15V_RCA, currentP15V_value, currentP24V(), currentP24V_RCA, currentP24V_value, currentP6V(), currentP6V_RCA, currentP6V_value, currentP8V(), currentP8V_RCA, currentP8V_value, ENABLE_MODULE, enableModule_RCA, VOLTAGE_N15V, VOLTAGE_N6V, VOLTAGE_P15V, VOLTAGE_P24V, VOLTAGE_P6V, VOLTAGE_P8V, voltageN15V(), voltageN15V_RCA, voltageN15V_value, voltageN6V(), voltageN6V_RCA, voltageN6V_value, voltageP15V(), voltageP15V_RCA, voltageP15V_value, voltageP24V(), voltageP24V_RCA, voltageP24V_value, voltageP6V(), voltageP6V_RCA, voltageP6V_value, voltageP8V(), voltageP8V_RCA, and voltageP8V_value.
virtual PowerModuleImplBase::~PowerModuleImplBase () inline virtual
Definition at line 35 of file PowerModuleImplBase.h.
References shutdown().
PowerModuleImplBase::PowerModuleImplBase (const PowerModuleImplBase & other) private
Member Function Documentation
float PowerModuleImplBase::currentN15V () virtual
Definition at line 130 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::currentN6V () virtual
Definition at line 118 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::currentP15V () virtual
Definition at line 124 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::currentP24V () virtual
Definition at line 136 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::currentP6V () virtual
Definition at line 112 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::currentP8V () virtual
Definition at line 142 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
bool PowerModuleImplBase::enableModule () virtual
Definition at line 145 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by PowerModuleImpl::clearEnable(), enableModule(), monitorAction(), PowerModuleImpl::PowerModuleImpl(), PowerModulesContainer::queryEnable(), and PowerModuleImpl::setEnable().
void PowerModuleImplBase::enableModule (bool val) virtual
Definition at line 150 of file PowerModuleImplBase.cpp.
References enableModule(), and SYNCCMD_LOG_INT.
int PowerModuleImplBase::getPort () const inline
Definition at line 38 of file PowerModuleImplBase.h.
References port_m.
Referenced by PowerModulesContainer::addPowerModule().
void PowerModuleImplBase::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Definition at line 100 of file PowerModuleImplBase.cpp.
References FrontEndLVWrapper::nodeAddress.
Referenced by PowerModuleImpl::PowerModuleImpl().
void PowerModuleImplBase::logMon (bool printHeader = false) const private
Definition at line 184 of file PowerModuleImplBase.cpp.
Referenced by monitorAction().
void PowerModuleImplBase::monitorAction (Time * timestamp_p) protected virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implements FEHardwareDevice.
Definition at line 154 of file PowerModuleImplBase.cpp.
References enableModule(), enableModule_value, lastMonitorTime, logMon(), FEHardwareDevice::logMonitors_m, and FEHardwareDevice::randomizeAnalogMonitors_m.
void PowerModuleImplBase::shutdown () virtual
Definition at line 105 of file PowerModuleImplBase.cpp.
Referenced by ~PowerModuleImplBase().
float PowerModuleImplBase::voltageN15V () virtual
Definition at line 127 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::voltageN6V () virtual
Definition at line 115 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::voltageP15V () virtual
Definition at line 121 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::voltageP24V () virtual
Definition at line 133 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::voltageP6V () virtual
Definition at line 109 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
float PowerModuleImplBase::voltageP8V () virtual
Definition at line 139 of file PowerModuleImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by PowerModuleImplBase().
Member Data Documentation
AmbRelativeAddr PowerModuleImplBase::baseRCA protected
Definition at line 109 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::currentN15V_RCA protected
Definition at line 117 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::currentN15V_status protected
Definition at line 102 of file PowerModuleImplBase.h.
float PowerModuleImplBase::currentN15V_value protected
Definition at line 88 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::currentN6V_RCA protected
Definition at line 113 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::currentN6V_status protected
Definition at line 98 of file PowerModuleImplBase.h.
float PowerModuleImplBase::currentN6V_value protected
Definition at line 84 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::currentP15V_RCA protected
Definition at line 115 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::currentP15V_status protected
Definition at line 100 of file PowerModuleImplBase.h.
float PowerModuleImplBase::currentP15V_value protected
Definition at line 86 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::currentP24V_RCA protected
Definition at line 119 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::currentP24V_status protected
Definition at line 104 of file PowerModuleImplBase.h.
float PowerModuleImplBase::currentP24V_value protected
Definition at line 90 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::currentP6V_RCA protected
Definition at line 111 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::currentP6V_status protected
Definition at line 96 of file PowerModuleImplBase.h.
float PowerModuleImplBase::currentP6V_value protected
Definition at line 82 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::currentP8V_RCA protected
Definition at line 121 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::currentP8V_status protected
Definition at line 106 of file PowerModuleImplBase.h.
float PowerModuleImplBase::currentP8V_value protected
Definition at line 92 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::enableModule_RCA protected
Definition at line 122 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::enableModule_status protected
Definition at line 107 of file PowerModuleImplBase.h.
bool PowerModuleImplBase::enableModule_value protected
Definition at line 93 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and monitorAction().
Time PowerModuleImplBase::lastMonitorTime private
Definition at line 131 of file PowerModuleImplBase.h.
Referenced by monitorAction().
int PowerModuleImplBase::monitorPhase private
Definition at line 132 of file PowerModuleImplBase.h.
int PowerModuleImplBase::port_m protected
to which FEMC port is this module connected.
Definition at line 125 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::clearEnable(), getPort(), and PowerModuleImpl::setEnable().
AmbRelativeAddr PowerModuleImplBase::voltageN15V_RCA protected
Definition at line 116 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::voltageN15V_status protected
Definition at line 101 of file PowerModuleImplBase.h.
float PowerModuleImplBase::voltageN15V_value protected
Definition at line 87 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::voltageN6V_RCA protected
Definition at line 112 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::voltageN6V_status protected
Definition at line 97 of file PowerModuleImplBase.h.
float PowerModuleImplBase::voltageN6V_value protected
Definition at line 83 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::voltageP15V_RCA protected
Definition at line 114 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::voltageP15V_status protected
Definition at line 99 of file PowerModuleImplBase.h.
float PowerModuleImplBase::voltageP15V_value protected
Definition at line 85 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::voltageP24V_RCA protected
Definition at line 118 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::voltageP24V_status protected
Definition at line 103 of file PowerModuleImplBase.h.
float PowerModuleImplBase::voltageP24V_value protected
Definition at line 89 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::voltageP6V_RCA protected
Definition at line 110 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::voltageP6V_status protected
Definition at line 95 of file PowerModuleImplBase.h.
float PowerModuleImplBase::voltageP6V_value protected
Definition at line 81 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
AmbRelativeAddr PowerModuleImplBase::voltageP8V_RCA protected
Definition at line 120 of file PowerModuleImplBase.h.
Referenced by PowerModuleImplBase().
int PowerModuleImplBase::voltageP8V_status protected
Definition at line 105 of file PowerModuleImplBase.h.
float PowerModuleImplBase::voltageP8V_value protected
Definition at line 91 of file PowerModuleImplBase.h.
Referenced by PowerModuleImpl::getMonitorPowerModule(), and PowerModuleImplBase().
The documentation for this class was generated from the following files:
FEBASE/PowerModuleImplBase.h
FEBASE/PowerModuleImplBase.cpp