FrontEndControl2: FEConfig::ConfigProviderMySQL Class Reference
FEConfig::ConfigProviderMySQL Class Reference
Loads FE configuration data from a MySQL database connection.
#include <ConfigProviderMySQL.h>
Public Member Functions
ConfigProviderMySQL ()
construct the provider to find connection info from the environment.
ConfigProviderMySQL (const std::string &host, const std::string &user, const std::string &password, const std::string &dbName)
construct the provider with connection info for the MySQL database server.
virtual ~ConfigProviderMySQL ()
virtual bool exists (unsigned keyFacility, unsigned configId) const
return true if the config specified by (keyFacility, configId) exists in the database, false otherwise.
virtual bool getConfiguration (unsigned keyFacility, unsigned configId, Configuration::Record &target) const
get the top-level configuration record specified by (keyFacility, configId).
virtual bool getFrontEndConfig (unsigned keyFacility, unsigned keyFrontEnd, FrontEndConfig &target) const
get the FrontEndConfig portion of the specified config.
virtual bool getCryostatConfig (unsigned keyFacility, unsigned keyCryostat, CryostatConfig &target) const
get the CryostatConfig portion of the specified config.
virtual bool getLPRConfig (unsigned keyFacility, unsigned keyLPR, LPRConfig &target) const
get the LPRConfig portion of the specified config.
virtual bool getCartAssemblyConfig (CartAssemblyID CAId, CartAssemblyConfig &target) const
load the configuration for the specified CartAssembly.
virtual bool getColdCartConfig (unsigned keyFacility, unsigned keyColdCart, ColdCartConfig &target) const
get the ColdCartConfig portion of the specified config for the specified band.
virtual bool getWCAConfig (unsigned keyFacility, unsigned keyWCA, WCAConfig &target) const
get the WCAConfig portion of the specified config for the specified band.
Public Member Functions inherited from FEConfig::ConfigProvider
ConfigProvider ()
virtual ~ConfigProvider ()
virtual bool getAllConfigurations (unsigned keyFacility, std::vector< Configuration::Record > &target) const
get all configurations for the given provider.
virtual bool saveConfiguration (const Configuration &source)
write out the entire configuration to the ini file.
Private Attributes
FrontEndDatabase * dbObject_mp
connection to the MySQL server.
Detailed Description
Loads FE configuration data from a MySQL database connection.
Definition at line 37 of file ConfigProviderMySQL.h.
Constructor & Destructor Documentation
FEConfig::ConfigProviderMySQL::ConfigProviderMySQL ()
construct the provider to find connection info from the environment.
Definition at line 31 of file ConfigProviderMySQL.cpp.
FEConfig::ConfigProviderMySQL::ConfigProviderMySQL (const std::string & host, const std::string & user, const std::string & password, const std::string & dbName)
construct the provider with connection info for the MySQL database server.
Definition at line 35 of file ConfigProviderMySQL.cpp.
FEConfig::ConfigProviderMySQL::~ConfigProviderMySQL () virtual
Definition at line 42 of file ConfigProviderMySQL.cpp.
References dbObject_mp.
Member Function Documentation
bool FEConfig::ConfigProviderMySQL::exists (unsigned keyFacility, unsigned configId) const virtual
return true if the config specified by (keyFacility, configId) exists in the database, false otherwise.
Implements FEConfig::ConfigProvider.
Definition at line 46 of file ConfigProviderMySQL.cpp.
References dbObject_mp.
bool FEConfig::ConfigProviderMySQL::getCartAssemblyConfig (CartAssemblyID CAId, CartAssemblyConfig & target) const virtual
load the configuration for the specified CartAssembly.
returns false if the configuration is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 198 of file ConfigProviderMySQL.cpp.
References FEConfig::CartAssemblyID::CCAFacility_m, FEConfig::CartAssemblyID::CCAId_m, FEConfig::CartAssemblyConfig::coldCart_m, getColdCartConfig(), getWCAConfig(), FEConfig::CartAssemblyConfig::Id_m, FEConfig::CartAssemblyID::isValid(), FEConfig::ColdCartConfig::reset(), FEConfig::WCAConfig::reset(), FEConfig::CartAssemblyConfig::reset(), FEConfig::CartAssemblyConfig::WCA_m, FEConfig::CartAssemblyID::WCAFacility_m, and FEConfig::CartAssemblyID::WCAId_m.
bool FEConfig::ConfigProviderMySQL::getColdCartConfig (unsigned keyFacility, unsigned keyColdCart, ColdCartConfig & target) const virtual
get the ColdCartConfig portion of the specified config for the specified band.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 221 of file ConfigProviderMySQL.cpp.
References FEConfig::ColdCartConfig::band_m, dbObject_mp, FEConfig::ColdCartConfig::description_m, FEConfig::ColdCartConfig::ESN_m, FEConfig::ColdCartConfig::magnetParams_m, FEConfig::ColdCartConfig::mixerParams_m, FEConfig::ColdCartConfig::reset(), and FEConfig::ColdCartConfig::SN_m.
Referenced by getCartAssemblyConfig(), and getFrontEndConfig().
bool FEConfig::ConfigProviderMySQL::getConfiguration (unsigned keyFacility, unsigned configId, Configuration::Record & target) const virtual
get the top-level configuration record specified by (keyFacility, configId).
returns false if the config does not exist or on error.
Implements FEConfig::ConfigProvider.
Definition at line 54 of file ConfigProviderMySQL.cpp.
References dbObject_mp, and FEConfig::Configuration::Record::reset().
bool FEConfig::ConfigProviderMySQL::getCryostatConfig (unsigned keyFacility, unsigned keyCryostat, CryostatConfig & target) const virtual
get the CryostatConfig portion of the specified config.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 164 of file ConfigProviderMySQL.cpp.
References dbObject_mp, FEConfig::CryostatConfig::ESN_m, FEConfig::CryostatConfig::reset(), and FEConfig::CryostatConfig::SN_m.
Referenced by getFrontEndConfig().
bool FEConfig::ConfigProviderMySQL::getFrontEndConfig (unsigned keyFacility, unsigned keyFrontEnd, FrontEndConfig & target) const virtual
get the FrontEndConfig portion of the specified config.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 64 of file ConfigProviderMySQL.cpp.
References FEConfig::CartAssemblyID::CCAFacility_m, FEConfig::CartAssemblyID::CCAId_m, FEConfig::CartAssemblyID::CCAValid(), FEConfig::CartAssemblyConfig::coldCart_m, FrontEndLVWrapper::configId, dbObject_mp, FEConfig::FrontEndConfig::ESN_m, FEConfig::FrontEndConfig::fkFETIM_m, FEConfig::FrontEndConfig::fkIFSwitch_m, FEConfig::FrontEndConfig::fkPowerDist_m, getColdCartConfig(), getCryostatConfig(), getLPRConfig(), getWCAConfig(), FEConfig::CartAssemblyConfig::Id_m, FEConfig::ColdCartConfig::reset(), FEConfig::FrontEndConfig::reset(), FEConfig::WCAConfig::reset(), FEConfig::CartAssemblyConfig::reset(), FEConfig::FrontEndConfig::setCartridgeConfig(), FEConfig::FrontEndConfig::setCryostatConfig(), FEConfig::FrontEndConfig::setLPRConfig(), FEConfig::FrontEndConfig::SN_m, FEConfig::CartAssemblyConfig::WCA_m, FEConfig::CartAssemblyID::WCAFacility_m, FEConfig::CartAssemblyID::WCAId_m, and FEConfig::CartAssemblyID::WCAValid().
bool FEConfig::ConfigProviderMySQL::getLPRConfig (unsigned keyFacility, unsigned keyLPR, LPRConfig & target) const virtual
get the LPRConfig portion of the specified config.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 181 of file ConfigProviderMySQL.cpp.
References dbObject_mp, FEConfig::LPRConfig::ESN_m, FEConfig::LPRConfig::reset(), and FEConfig::LPRConfig::SN_m.
Referenced by getFrontEndConfig().
bool FEConfig::ConfigProviderMySQL::getWCAConfig (unsigned keyFacility, unsigned keyWCA, WCAConfig & target) const virtual
get the WCAConfig portion of the specified config for the specified band.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 259 of file ConfigProviderMySQL.cpp.
References FEConfig::WCAConfig::band_m, dbObject_mp, FEConfig::WCAConfig::description_m, FEConfig::WCAConfig::ESN_m, FEConfig::WCAConfig::FHIYIG_m, FEConfig::WCAConfig::FLOYIG_m, FEConfig::WCAConfig::PAParams_m, FEConfig::WCAConfig::reset(), and FEConfig::WCAConfig::SN_m.
Referenced by getCartAssemblyConfig(), and getFrontEndConfig().
Member Data Documentation
FrontEndDatabase* FEConfig::ConfigProviderMySQL::dbObject_mp private
connection to the MySQL server.
Definition at line 83 of file ConfigProviderMySQL.h.
Referenced by exists(), getColdCartConfig(), getConfiguration(), getCryostatConfig(), getFrontEndConfig(), getLPRConfig(), getWCAConfig(), and ~ConfigProviderMySQL().
The documentation for this class was generated from the following files:
CONFIG/ConfigProviderMySQL.h
CONFIG/ConfigProviderMySQL.cpp