FrontEndControl2: MaximizeIFPower Class Reference
MaximizeIFPower Class Reference
#include <MaximizeIFPower.h>
Public Member Functions
MaximizeIFPower (ColdCartImpl &ColdCart, WCAImpl &WCA)
virtual ~MaximizeIFPower ()
virtual void reset ()
reset all state to initial/just constructed.
bool start (double freqLO, bool doPol0, bool doPol1, float startVJ1, float startVJ2, float startVD)
initial setting for PA drain voltage.
virtual void requestStop ()
abort the measurement
bool setIFPower (int pol, float powerSb1, float powerSb2)
called by main thread to feed IF power readings into the optimization process.
const MixerParams & getMixerParamsResult () const
get the resulting optimized mixer parameters vs. LO frequency.
const PowerAmpParams & getPowerAmpParamsResult () const
get the resulting optimized PA parameters vs. LO frequency.
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Public Member Functions inherited from Maximizer
Maximizer ()
virtual ~Maximizer ()
bool maximize (float &controlStart, float controlStep, float controlMin, float controlMax, bool directionUp, int maxIter, int timeOut, int interval)
perform a maximization of the dependent variable by varying the control variable.
void stopMaximizer ()
abort the process.
Protected Member Functions
virtual bool setControlValue (float control)
Called by the Maximizer base class to set the independent control variable.
virtual bool requestDependentValue (float &depVal)
Called by the Maximizer base class to request the value of the dependent variable.
virtual void optimizeAction ()
called by the OptimizeBase worker thread.
virtual void exitAction (bool success)
called by OptimizeBase prior to worker thread exit.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Protected Member Functions inherited from Maximizer
void setDependentValue (float depVal)
Set the dependent value after one was requested via requestDependentValue().
bool waitForDependentValue (float &depVal, int timeOut, int interval=20)
Wait up to timeOut ms for a fresh dependent value to be provided.
Private Types
enum OperationPhases {
OP_PHASE_NONE, OP_PHASE_1A, OP_PHASE_1B, OP_PHASE_1C,
OP_PHASE_2A, OP_PHASE_2B, OP_PHASE_2C, OP_PHASE_3A,
OP_PHASE_3B, OP_PHASE_3C, OP_PHASE_POL_DONE
}
Private Member Functions
bool optimizeSinglePol (int pol)
performs the optimization of a single pol.
bool performPhase (OperationPhases phase, float step, bool directionUp, int averaging)
perform the specified phase of the optimization.
void logOutput (bool printHeader=false)
add a line to the optimization output log.
Private Attributes
ColdCartImpl & coldCart_m
the cold cartridge to operate
WCAImpl & WCA_m
the WCA to operate.
double freqLO_m
what LO frequency applies to the optimization in-progress.
bool doPol0_m
true means optimize pol0
bool doPol1_m
true means optimize pol1
int currentPol_m
polarization currently being optimized.
float startVJ1_m
starting value for SIS1 junction voltage
float startVJ2_m
starting value for SIS2 junction voltage
float startVD_m
starting value for PA drain voltage
float VJ1_m
the current setting for SIS1 junction voltage
float VJ2_m
the current setting for SIS2 junction voltage
float VD_m
the current setting for PA drain voltage
float VJ01opt_m
float VJ02opt_m
float VJ11opt_m
float VJ12opt_m
float VD0opt_m
float VD1opt_m
float powerSb1_m
most recent SB1 power level
float powerSb2_m
most recent SB2 power level
short progress_m
local variable for progress bar percentage.
enum MaximizeIFPower::OperationPhases opPhase_m
enum MaximizeIFPower::OperationPhases failPhase_m
MixerParams mixerParams_m
where to store the resulting mixer parameters vs. frequency.
PowerAmpParams paParams_m
where to store the resulting PA parameters vs. frequency.
std::ostream * dataFile_mp
Static Private Attributes
static const short maxIter_m
maximum iterations for the optimizer loop.
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 34 of file MaximizeIFPower.h.
Member Enumeration Documentation
enum MaximizeIFPower::OperationPhases private
Enumerator
OP_PHASE_NONE
phases of the maximization process:
startup/reset phase.
OP_PHASE_1A
OP_PHASE_1B
OP_PHASE_1C
OP_PHASE_2A
OP_PHASE_2B
OP_PHASE_2C
OP_PHASE_3A
OP_PHASE_3B
OP_PHASE_3C
OP_PHASE_POL_DONE
final state for logging results for a single pol
Definition at line 115 of file MaximizeIFPower.h.
Constructor & Destructor Documentation
MaximizeIFPower::MaximizeIFPower (ColdCartImpl & ColdCart, WCAImpl & WCA) inline
Definition at line 36 of file MaximizeIFPower.h.
virtual MaximizeIFPower::~MaximizeIFPower () inline virtual
Definition at line 44 of file MaximizeIFPower.h.
Member Function Documentation
void MaximizeIFPower::exitAction (bool success) protected virtual
called by OptimizeBase prior to worker thread exit.
Reimplemented from OptimizeBase.
Definition at line 212 of file MaximizeIFPower.cpp.
References FEMCEventQueue::EVENT_PA_ADJUST_DONE, and FEMCEventQueue::EVENT_STOP_IFPOWER.
const MixerParams& MaximizeIFPower::getMixerParamsResult () const inline
get the resulting optimized mixer parameters vs. LO frequency.
Definition at line 66 of file MaximizeIFPower.h.
const PowerAmpParams& MaximizeIFPower::getPowerAmpParamsResult () const inline
get the resulting optimized PA parameters vs. LO frequency.
Definition at line 70 of file MaximizeIFPower.h.
void MaximizeIFPower::logOutput (bool printHeader = false) private
add a line to the optimization output log.
Definition at line 400 of file MaximizeIFPower.cpp.
void MaximizeIFPower::optimizeAction () protected virtual
called by the OptimizeBase worker thread.
Implements OptimizeBase.
Definition at line 171 of file MaximizeIFPower.cpp.
bool MaximizeIFPower::optimizeSinglePol (int pol) private
performs the optimization of a single pol.
Definition at line 264 of file MaximizeIFPower.cpp.
References FEMCEventQueue::EVENT_REQUEST_IFPOWER, FEMCEventQueue::EVENT_STOP_IFPOWER, and Maximizer::waitForDependentValue().
bool MaximizeIFPower::performPhase (OperationPhases phase, float step, bool directionUp, int averaging) private
perform the specified phase of the optimization.
Definition at line 353 of file MaximizeIFPower.cpp.
References FEMCEventQueue::EVENT_REQUEST_IFPOWER, and Maximizer::maximize().
bool MaximizeIFPower::requestDependentValue (float & depVal) protected virtual
Called by the Maximizer base class to request the value of the dependent variable.
Implementation may provide a result right away and return true or return false and provide a value later using setDependentValue().
Implements Maximizer.
Definition at line 166 of file MaximizeIFPower.cpp.
virtual void MaximizeIFPower::requestStop () inline virtual
abort the measurement
Reimplemented from OptimizeBase.
Definition at line 58 of file MaximizeIFPower.h.
References OptimizeBase::requestStop().
void MaximizeIFPower::reset () virtual
reset all state to initial/just constructed.
Reimplemented from Maximizer.
Definition at line 33 of file MaximizeIFPower.cpp.
References Maximizer::reset().
bool MaximizeIFPower::setControlValue (float control) protected virtual
Called by the Maximizer base class to set the independent control variable.
If implementation returns false, the maximize funtion returns false.
Implements Maximizer.
Definition at line 109 of file MaximizeIFPower.cpp.
bool MaximizeIFPower::setIFPower (int pol, float powerSb1, float powerSb2)
called by main thread to feed IF power readings into the optimization process.
Definition at line 75 of file MaximizeIFPower.cpp.
References Maximizer::setDependentValue().
bool MaximizeIFPower::start (double freqLO, bool doPol0, bool doPol1, float startVJ1, float startVJ2, float startVD)
initial setting for PA drain voltage.
start the optimization procedure.
Parameters
freqLO for which frequency to store the results.
doPol0 true means optimize pol0
doPol1 true means optimize pol1
startVJ1 initial setting for SIS1 junction voltage
startVJ2 initial setting for SIS2 junction voltage
Definition at line 50 of file MaximizeIFPower.cpp.
References OptimizeBase::startWorkerThread().
Member Data Documentation
ColdCartImpl& MaximizeIFPower::coldCart_m private
the cold cartridge to operate
Definition at line 91 of file MaximizeIFPower.h.
int MaximizeIFPower::currentPol_m private
polarization currently being optimized.
Definition at line 96 of file MaximizeIFPower.h.
std::ostream* MaximizeIFPower::dataFile_mp private
Definition at line 150 of file MaximizeIFPower.h.
bool MaximizeIFPower::doPol0_m private
true means optimize pol0
Definition at line 94 of file MaximizeIFPower.h.
bool MaximizeIFPower::doPol1_m private
true means optimize pol1
Definition at line 95 of file MaximizeIFPower.h.
enum MaximizeIFPower::OperationPhases MaximizeIFPower::failPhase_m private
double MaximizeIFPower::freqLO_m private
what LO frequency applies to the optimization in-progress.
Definition at line 93 of file MaximizeIFPower.h.
const short MaximizeIFPower::maxIter_m static private
maximum iterations for the optimizer loop.
Definition at line 113 of file MaximizeIFPower.h.
MixerParams MaximizeIFPower::mixerParams_m private
where to store the resulting mixer parameters vs. frequency.
Definition at line 148 of file MaximizeIFPower.h.
enum MaximizeIFPower::OperationPhases MaximizeIFPower::opPhase_m private
PowerAmpParams MaximizeIFPower::paParams_m private
where to store the resulting PA parameters vs. frequency.
Definition at line 149 of file MaximizeIFPower.h.
float MaximizeIFPower::powerSb1_m private
most recent SB1 power level
Definition at line 109 of file MaximizeIFPower.h.
float MaximizeIFPower::powerSb2_m private
most recent SB2 power level
Definition at line 110 of file MaximizeIFPower.h.
short MaximizeIFPower::progress_m private
local variable for progress bar percentage.
Definition at line 111 of file MaximizeIFPower.h.
float MaximizeIFPower::startVD_m private
starting value for PA drain voltage
Definition at line 99 of file MaximizeIFPower.h.
float MaximizeIFPower::startVJ1_m private
starting value for SIS1 junction voltage
Definition at line 97 of file MaximizeIFPower.h.
float MaximizeIFPower::startVJ2_m private
starting value for SIS2 junction voltage
Definition at line 98 of file MaximizeIFPower.h.
float MaximizeIFPower::VD0opt_m private
Definition at line 107 of file MaximizeIFPower.h.
float MaximizeIFPower::VD1opt_m private
Definition at line 108 of file MaximizeIFPower.h.
float MaximizeIFPower::VD_m private
the current setting for PA drain voltage
Definition at line 102 of file MaximizeIFPower.h.
float MaximizeIFPower::VJ01opt_m private
Definition at line 103 of file MaximizeIFPower.h.
float MaximizeIFPower::VJ02opt_m private
Definition at line 104 of file MaximizeIFPower.h.
float MaximizeIFPower::VJ11opt_m private
Definition at line 105 of file MaximizeIFPower.h.
float MaximizeIFPower::VJ12opt_m private
Definition at line 106 of file MaximizeIFPower.h.
float MaximizeIFPower::VJ1_m private
the current setting for SIS1 junction voltage
Definition at line 100 of file MaximizeIFPower.h.
float MaximizeIFPower::VJ2_m private
the current setting for SIS2 junction voltage
Definition at line 101 of file MaximizeIFPower.h.
WCAImpl& MaximizeIFPower::WCA_m private
the WCA to operate.
Definition at line 92 of file MaximizeIFPower.h.
The documentation for this class was generated from the following files:
OPTIMIZE/MaximizeIFPower.h
OPTIMIZE/MaximizeIFPower.cpp