FrontEndControl2: SignalSourceImpl Class Reference
SignalSourceImpl Class Reference
SignalSource is a FEMC module with one WCA attached.
#include <SignalSourceImpl.h>
Public Member Functions
SignalSourceImpl (unsigned long channel, unsigned long nodeAddress, const std::string &ESN="")
virtual ~SignalSourceImpl ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
bool connected () const
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void queryCartridgeState ()
bool addCartridge (int port, WCAImpl &WCA)
bool deleteCartridge ()
bool setWCAConfig (const FEConfig::WCAConfig &params)
bool setYIGLimits (double FLOYIG, double FHIYIG)
bool setCartridgeOff ()
bool setCartridgeOn ()
bool getCartridgeOn () const
bool cartPauseMonitor (bool pause)
void getAMBSIInfo (std::string &serialNum, std::string &firmwareRev, unsigned long &numErrors, unsigned long &numTransactions)
void getFirmwareInfo (std::string &AMBSILibraryVersion, std::string &FEMCFirmwareVersion, std::string &FEMCFPGAVersion)
float getAMBSITemperature () const
unsigned short powerGetMonitorNumEnabled ()
bool cartGetMonitorYTO (WCAImpl::YTO_t &target) const
bool cartGetMonitorPhotomixer (WCAImpl::Photomixer_t &target) const
bool cartGetMonitorPLL (WCAImpl::PLL_t &target) const
bool cartGetMonitorAMC (WCAImpl::AMC_t &target) const
bool cartGetMonitorPA (WCAImpl::PA_t &target) const
bool cartSetLOFrequency (double freqLO, double freqFLOOG, int sbLock)
bool cartGetLOFrequency (double &freqLO, double &freqREF) const
bool cartLockPLL ()
bool cartGetLocked ()
bool cartAdjustPLL (float targetCorrVoltage)
bool cartAdjustYTO (int steps)
bool cartNullPLLIntegrator (bool enable=false)
bool cartGetNullPLLIntegrator () const
bool cartSetLOPowerAmps (bool enable=false, const float *VDP0=NULL, const float *VGP0=NULL, const float *VDP1=NULL, const float *VGP1=NULL)
bool cartGetEnableLOPowerAmps () const
bool cartSetEnableLO (bool enable)
bool cartSetLOPower (int pol, float percent)
bool cartGetLOPADrainVoltageSetting (float *VDP0, float *VDP1)
bool cartSetAMC (const float *VDE=NULL, const float *VGE=NULL)
bool cartSetEnablePhotomixer (bool enable=false)
bool cartGetEnablePhotomixer () const
Public Member Functions inherited from FrontEndImplBase
FrontEndImplBase (const std::string &name)
virtual ~FrontEndImplBase ()
virtual std::string AMBSILibraryVersion ()
virtual std::string FEMCFirmwareVersion ()
virtual std::string FEMCFPGAVersion ()
virtual unsigned char FEMCGetESNsFound ()
virtual std::string FEMCGetNextESN (bool reverseBytes=false)
virtual unsigned char specialGetSetupInfo ()
virtual unsigned char numEnabledModules ()
virtual bool powerEnableModule (int port)
virtual unsigned short getNumErrors ()
virtual unsigned short getNextError ()
virtual unsigned char getFEMode ()
virtual void powerEnableModule (int port, bool val)
virtual void specialExitProgram (bool val)
virtual void specialReadESNs (bool val)
virtual void setFEMode (unsigned char val)
Public Member Functions inherited from AMBSIHardwareDevice
AMBSIHardwareDevice (const std::string &name)
virtual ~AMBSIHardwareDevice ()
virtual std::string AMBSISerialNum ()
virtual std::string AMBSIFirmwareRev ()
virtual unsigned long AMBSINumErrors ()
virtual unsigned long AMBSINumTransactions ()
virtual float AMBSITemperature ()
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Private Member Functions
SignalSourceImpl (const SignalSourceImpl &other)
SignalSourceImpl & operator= (const SignalSourceImpl &other)
Private Attributes
CartAssembly * cart_mp
int port_m
bool connected_m
true if successfully connected to the FEMC module.
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Types inherited from FrontEndImplBase
enum MonitorControlOffset {
SPECIAL_MONITOR = 0x20000UL, SPECIAL_CONTROL = 0x21000UL, GET_AMBSI_VERSION_INFO = 0x0000, GET_SETUP_INFO = 0x0001,
GET_VERSION_INFO = 0x0002, GET_SPECIAL_MONITOR_RCA = 0x0003, GET_SPECIAL_CONTROL_RCA = 0x0004, GET_MONITOR_RCA = 0x0005,
GET_CONTROL_RCA = 0x0006, GET_PPCOMM_TIME = 0x0007, GET_FPGA_VERSION_INFO = 0x0008, GET_ESNS_FOUND = 0x000A,
GET_ESNS = 0x000B, GET_ERRORS_NUMBER = 0x000C, GET_NEXT_ERROR = 0x000D, GET_FE_MODE = 0x000E,
SET_EXIT_PROGRAM = 0x0000, SET_REBOOT = 0x0001, SET_FE_MODE = 0x000E, SET_READ_ESN = 0x000F,
POWER_NUM_MODULES_ENABLED = 0xA0A0, POWER_ENABLE_MODULE = 0xA00C
}
Protected Types inherited from AMBSIHardwareDevice
enum MonitorControlOffset {
AMBSI_BASE = 0x30000UL, AMBSI_SERIAL_NUMBER = 0x0000, AMBSI_FIRMWARE_REV = 0x0000, AMBSI_NUM_ERRORS = 0x0001,
AMBSI_NUM_TRANSACTIONS = 0x0002, AMBSI_TEMPERATURE = 0x0003
}
Protected Member Functions inherited from FrontEndImplBase
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Protected Attributes inherited from FrontEndImplBase
std::string AMBSILibraryVersion_value
std::string FEMCFirmwareVersion_value
std::string FEMCFPGAVersion_value
unsigned char FEMCGetESNsFound_value
std::string FEMCGetNextESN_value
unsigned char specialGetSetupInfo_value
unsigned char numEnabledModules_value
int numEnabledModules_status
unsigned short numErrors_value
int numErrors_status
unsigned short nextError_value
int nextError_status
unsigned char FEMode_value
int FEMode_status
AmbRelativeAddr numEnabledModules_RCA
AmbRelativeAddr powerEnableModule_RCA
AmbRelativeAddr numErrors_RCA
AmbRelativeAddr nextError_RCA
AmbRelativeAddr FEMode_RCA
Protected Attributes inherited from AMBSIHardwareDevice
std::string AMBSISerialNum_value
std::string AMBSIFirmwareRev_value
unsigned long AMBSINumErrors_value
unsigned long AMBSINumTransactions_value
float AMBSITemperature_value
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
SignalSource is a FEMC module with one WCA attached.
Definition at line 30 of file SignalSourceImpl.h.
Constructor & Destructor Documentation
SignalSourceImpl::SignalSourceImpl (unsigned long channel, unsigned long nodeAddress, const std::string & ESN = "")
Definition at line 40 of file SignalSourceImpl.cpp.
References initialize(), and FEHardwareDevice::setESN().
SignalSourceImpl::~SignalSourceImpl () virtual
Definition at line 52 of file SignalSourceImpl.cpp.
References deleteCartridge().
SignalSourceImpl::SignalSourceImpl (const SignalSourceImpl & other) private
Member Function Documentation
bool SignalSourceImpl::addCartridge (int port, WCAImpl & WCA)
Definition at line 170 of file SignalSourceImpl.cpp.
References cart_mp, deleteCartridge(), and port_m.
bool SignalSourceImpl::cartAdjustPLL (float targetCorrVoltage)
Definition at line 312 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, and port_m.
bool SignalSourceImpl::cartAdjustYTO (int steps)
Definition at line 336 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, and port_m.
bool SignalSourceImpl::cartGetEnableLOPowerAmps () const
Definition at line 392 of file SignalSourceImpl.cpp.
References cart_mp.
bool SignalSourceImpl::cartGetEnablePhotomixer () const
Definition at line 467 of file SignalSourceImpl.cpp.
References cart_mp.
bool SignalSourceImpl::cartGetLocked ()
Definition at line 304 of file SignalSourceImpl.cpp.
References cart_mp.
bool SignalSourceImpl::cartGetLOFrequency (double & freqLO, double & freqREF) const
Definition at line 267 of file SignalSourceImpl.cpp.
References cart_mp.
bool SignalSourceImpl::cartGetLOPADrainVoltageSetting (float * VDP0, float * VDP1)
Definition at line 426 of file SignalSourceImpl.cpp.
References cart_mp, and port_m.
bool SignalSourceImpl::cartGetMonitorAMC (WCAImpl::AMC_t & target) const
Definition at line 150 of file SignalSourceImpl.cpp.
References cart_mp.
bool SignalSourceImpl::cartGetMonitorPA (WCAImpl::PA_t & target) const
Definition at line 159 of file SignalSourceImpl.cpp.
References cart_mp.
bool SignalSourceImpl::cartGetMonitorPhotomixer (WCAImpl::Photomixer_t & target) const
Definition at line 132 of file SignalSourceImpl.cpp.
References cart_mp.
bool SignalSourceImpl::cartGetMonitorPLL (WCAImpl::PLL_t & target) const
Definition at line 141 of file SignalSourceImpl.cpp.
References cart_mp.
bool SignalSourceImpl::cartGetMonitorYTO (WCAImpl::YTO_t & target) const
Definition at line 125 of file SignalSourceImpl.cpp.
References cart_mp, and WCAImpl::YTO_t::reset().
bool SignalSourceImpl::cartGetNullPLLIntegrator () const
Definition at line 364 of file SignalSourceImpl.cpp.
References cart_mp.
bool SignalSourceImpl::cartLockPLL ()
Definition at line 276 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, and port_m.
bool SignalSourceImpl::cartNullPLLIntegrator (bool enable = false)
Definition at line 350 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, and port_m.
bool SignalSourceImpl::cartPauseMonitor (bool pause)
Definition at line 241 of file SignalSourceImpl.cpp.
References cart_mp, and FEHardwareDevice::pauseMonitor().
bool SignalSourceImpl::cartSetAMC (const float * VDE = NULL, const float * VGE = NULL)
Definition at line 439 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, and port_m.
bool SignalSourceImpl::cartSetEnableLO (bool enable)
Definition at line 399 of file SignalSourceImpl.cpp.
References cart_mp, and port_m.
bool SignalSourceImpl::cartSetEnablePhotomixer (bool enable = false)
Definition at line 453 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, and port_m.
bool SignalSourceImpl::cartSetLOFrequency (double freqLO, double freqFLOOG, int sbLock)
Definition at line 252 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, and port_m.
bool SignalSourceImpl::cartSetLOPower (int pol, float percent)
Definition at line 413 of file SignalSourceImpl.cpp.
References cart_mp, and port_m.
bool SignalSourceImpl::cartSetLOPowerAmps (bool enable = false, const float * VDP0 = NULL, const float * VGP0 = NULL, const float * VDP1 = NULL, const float * VGP1 = NULL)
Definition at line 371 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, and port_m.
bool SignalSourceImpl::connected () const inline
Definition at line 40 of file SignalSourceImpl.h.
References connected_m.
bool SignalSourceImpl::deleteCartridge ()
Definition at line 177 of file SignalSourceImpl.cpp.
References cart_mp, and port_m.
Referenced by addCartridge(), and ~SignalSourceImpl().
void SignalSourceImpl::getAMBSIInfo (std::string & serialNum, std::string & firmwareRev, unsigned long & numErrors, unsigned long & numTransactions)
Definition at line 98 of file SignalSourceImpl.cpp.
References AMBSIHardwareDevice::AMBSIFirmwareRev_value, AMBSIHardwareDevice::AMBSINumErrors_value, AMBSIHardwareDevice::AMBSINumTransactions_value, and AMBSIHardwareDevice::AMBSISerialNum_value.
float SignalSourceImpl::getAMBSITemperature () const
Definition at line 117 of file SignalSourceImpl.cpp.
References AMBSIHardwareDevice::AMBSITemperature_value.
bool SignalSourceImpl::getCartridgeOn () const
Definition at line 234 of file SignalSourceImpl.cpp.
References cart_mp.
void SignalSourceImpl::getFirmwareInfo (std::string & AMBSILibraryVersion, std::string & FEMCFirmwareVersion, std::string & FEMCFPGAVersion)
Definition at line 109 of file SignalSourceImpl.cpp.
References FrontEndImplBase::AMBSILibraryVersion_value, FrontEndImplBase::FEMCFirmwareVersion_value, and FrontEndImplBase::FEMCFPGAVersion_value.
void SignalSourceImpl::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Reimplemented from FrontEndImplBase.
Definition at line 56 of file SignalSourceImpl.cpp.
References AMBSIHardwareDevice::AMBSIFirmwareRev(), FrontEndImplBase::AMBSILibraryVersion(), AMBSIHardwareDevice::AMBSISerialNum(), connected_m, FrontEndImplBase::FEMCFirmwareVersion(), FrontEndImplBase::FEMCFPGAVersion(), FrontEndImplBase::initialize(), and FrontEndImplBase::specialGetSetupInfo().
Referenced by SignalSourceImpl().
SignalSourceImpl& SignalSourceImpl::operator= (const SignalSourceImpl & other) private
unsigned short SignalSourceImpl::powerGetMonitorNumEnabled ()
Definition at line 121 of file SignalSourceImpl.cpp.
References FrontEndImplBase::numEnabledModules().
void SignalSourceImpl::queryCartridgeState ()
Definition at line 88 of file SignalSourceImpl.cpp.
References cart_mp, port_m, and FrontEndImplBase::powerEnableModule().
bool SignalSourceImpl::setCartridgeOff ()
Definition at line 206 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, port_m, and FrontEndImplBase::powerEnableModule().
bool SignalSourceImpl::setCartridgeOn ()
Definition at line 220 of file SignalSourceImpl.cpp.
References FEMCEventQueue::addStatusMessage(), cart_mp, port_m, and FrontEndImplBase::powerEnableModule().
bool SignalSourceImpl::setWCAConfig (const FEConfig::WCAConfig & params)
Definition at line 187 of file SignalSourceImpl.cpp.
References cart_mp.
Referenced by FEConfig::ConfigManager::configureWCA().
bool SignalSourceImpl::setYIGLimits (double FLOYIG, double FHIYIG)
Definition at line 195 of file SignalSourceImpl.cpp.
References cart_mp.
void SignalSourceImpl::shutdown () virtual
Reimplemented from FrontEndImplBase.
Definition at line 69 of file SignalSourceImpl.cpp.
References connected_m, and FrontEndImplBase::shutdown().
void SignalSourceImpl::startMonitor () virtual
start the monitor thread.
Reimplemented from FEHardwareDevice.
Definition at line 77 of file SignalSourceImpl.cpp.
References cart_mp, and FEHardwareDevice::startMonitor().
void SignalSourceImpl::stopMonitor () virtual
stop the monitor thread.
Reimplemented from FEHardwareDevice.
Definition at line 83 of file SignalSourceImpl.cpp.
References cart_mp.
Member Data Documentation
CartAssembly* SignalSourceImpl::cart_mp private
Definition at line 121 of file SignalSourceImpl.h.
Referenced by addCartridge(), cartAdjustPLL(), cartAdjustYTO(), cartGetEnableLOPowerAmps(), cartGetEnablePhotomixer(), cartGetLocked(), cartGetLOFrequency(), cartGetLOPADrainVoltageSetting(), cartGetMonitorAMC(), cartGetMonitorPA(), cartGetMonitorPhotomixer(), cartGetMonitorPLL(), cartGetMonitorYTO(), cartGetNullPLLIntegrator(), cartLockPLL(), cartNullPLLIntegrator(), cartPauseMonitor(), cartSetAMC(), cartSetEnableLO(), cartSetEnablePhotomixer(), cartSetLOFrequency(), cartSetLOPower(), cartSetLOPowerAmps(), deleteCartridge(), getCartridgeOn(), queryCartridgeState(), setCartridgeOff(), setCartridgeOn(), setWCAConfig(), setYIGLimits(), startMonitor(), and stopMonitor().
bool SignalSourceImpl::connected_m private
true if successfully connected to the FEMC module.
Definition at line 125 of file SignalSourceImpl.h.
Referenced by connected(), initialize(), and shutdown().
int SignalSourceImpl::port_m private
Definition at line 122 of file SignalSourceImpl.h.
Referenced by addCartridge(), cartAdjustPLL(), cartAdjustYTO(), cartGetLOPADrainVoltageSetting(), cartLockPLL(), cartNullPLLIntegrator(), cartSetAMC(), cartSetEnableLO(), cartSetEnablePhotomixer(), cartSetLOFrequency(), cartSetLOPower(), cartSetLOPowerAmps(), deleteCartridge(), queryCartridgeState(), setCartridgeOff(), and setCartridgeOn().
The documentation for this class was generated from the following files:
SignalSourceImpl.h
SignalSourceImpl.cpp