FrontEndControl2: AmbTransactionLogger Class Reference
AmbTransactionLogger Class Reference
#include <ambTransactionLogger.h>
Classes
class LogBuffer
Define the class for the log buffer, a circular buffer of pointers to LogEntry with a mutex to protect the queue.
struct LogEntry
define the structure for items waiting to be logged.
Public Member Functions
AmbTransactionLogger (bool useStream=false)
construct
virtual ~AmbTransactionLogger ()
void setUseStream (bool useStream)
start/stop logging to the configured log stream.
void shutdown ()
flushes log queue in preparation for destruction.
virtual void checkPoint (const char *text)
log a checkpoint transaction.
virtual void log (FEHardwareDevice::Transaction_t trans, const char *text, AmbRelativeAddr RCA, int FEStatus, unsigned long iValue, float fValue)
Log an actual transaction.
Public Member Functions inherited from FEHardwareDevice::LogInterface
LogInterface ()
virtual ~LogInterface ()
Private Member Functions
void logSingleItem (const LogEntry *entry) const
Log a single item to the output stream.
Static Private Member Functions
static void * loggerThread (AmbTransactionLogger *arg)
The function for the worker thread to which periodically logs whats in the buffer.
static const std::string & statusToText (const AmbErrorCode_t *status, std::string &statusText)
Helper function to format a AmbErrorCode_t as text for logging.
Private Attributes
LogBuffer * buffer_mp
forward declare the circular buffer class.
bool useStream_m
if true, log to the stream output.
pthread_t thread_m
handle for the logging worker thread.
bool do_shutdown
True when worker should die.
bool shutdown_done
True when worker has died.
Detailed Description
Definition at line 34 of file ambTransactionLogger.h.
Constructor & Destructor Documentation
AmbTransactionLogger::AmbTransactionLogger (bool useStream = false)
construct
Definition at line 243 of file ambTransactionLogger.cpp.
References loggerThread(), and thread_m.
AmbTransactionLogger::~AmbTransactionLogger () virtual
Definition at line 255 of file ambTransactionLogger.cpp.
References buffer_mp, and shutdown().
Member Function Documentation
void AmbTransactionLogger::checkPoint (const char * text) virtual
log a checkpoint transaction.
Reimplemented from FEHardwareDevice::LogInterface.
Definition at line 278 of file ambTransactionLogger.cpp.
References buffer_mp, and FEHardwareDevice::FEMC_LOG_CHECKPOINT.
void AmbTransactionLogger::log (FEHardwareDevice::Transaction_t trans, const char * text, AmbRelativeAddr RCA, int FEStatus, unsigned long iValue, float fValue) virtual
Log an actual transaction.
Reimplemented from FEHardwareDevice::LogInterface.
Definition at line 284 of file ambTransactionLogger.cpp.
References buffer_mp.
void * AmbTransactionLogger::loggerThread (AmbTransactionLogger * arg) static private
The function for the worker thread to which periodically logs whats in the buffer.
Definition at line 324 of file ambTransactionLogger.cpp.
References buffer_mp, do_shutdown, logSingleItem(), and shutdown_done.
Referenced by AmbTransactionLogger().
void AmbTransactionLogger::logSingleItem (const LogEntry * entry) const private
Log a single item to the output stream.
Definition at line 297 of file ambTransactionLogger.cpp.
References FrontEnd::FESelector_t::decode(), FEHardwareDevice::FEMC_LOG_CHECKPOINT, FEHardwareDevice::FEMC_LOG_COMMAND, FEHardwareDevice::FEMC_LOG_MONITOR, FEHardwareDevice::TransactionText, and useStream_m.
Referenced by loggerThread().
void AmbTransactionLogger::setUseStream (bool useStream)
start/stop logging to the configured log stream.
Definition at line 260 of file ambTransactionLogger.cpp.
References useStream_m.
void AmbTransactionLogger::shutdown ()
flushes log queue in preparation for destruction.
Definition at line 264 of file ambTransactionLogger.cpp.
References do_shutdown, and shutdown_done.
Referenced by ~AmbTransactionLogger().
const string & AmbTransactionLogger::statusToText (const AmbErrorCode_t * status, std::string & statusText) static private
Helper function to format a AmbErrorCode_t as text for logging.
Definition at line 351 of file ambTransactionLogger.cpp.
Member Data Documentation
LogBuffer* AmbTransactionLogger::buffer_mp private
forward declare the circular buffer class.
circular buffer of log entries.
Definition at line 61 of file ambTransactionLogger.h.
Referenced by checkPoint(), log(), loggerThread(), and ~AmbTransactionLogger().
bool AmbTransactionLogger::do_shutdown private
True when worker should die.
Definition at line 67 of file ambTransactionLogger.h.
Referenced by loggerThread(), and shutdown().
bool AmbTransactionLogger::shutdown_done private
True when worker has died.
Definition at line 68 of file ambTransactionLogger.h.
Referenced by loggerThread(), and shutdown().
pthread_t AmbTransactionLogger::thread_m private
handle for the logging worker thread.
Definition at line 66 of file ambTransactionLogger.h.
Referenced by AmbTransactionLogger().
bool AmbTransactionLogger::useStream_m private
if true, log to the stream output.
Definition at line 64 of file ambTransactionLogger.h.
Referenced by logSingleItem(), and setUseStream().
The documentation for this class was generated from the following files:
LOGGER/ambTransactionLogger.h
LOGGER/ambTransactionLogger.cpp