FrontEndControl2: ThermalLogger Class Reference
ThermalLogger Class Reference
#include <ThermalLogger.h>
Public Member Functions
ThermalLogger (const ThermalLoggable &source, const std::string &filenameTag=std::string())
virtual ~ThermalLogger ()
void reset ()
reset all state to initial/just constructed.
bool start (unsigned int loggingInterval)
start logging with the specified interval, in seconds.
void stop ()
stop logging
void setLoggingInterval (unsigned int loggingInterval)
change the logging interval, in seconds.
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
virtual void requestStop ()
main thread can call this to request worker thread to stop.
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
virtual void optimizeAction ()
called by the OptimizeBase worker thread.
virtual void exitAction (bool success)
called by OptimizeBase prior to worker thread exit.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Private Member Functions
void getHeaderRow (std::string &target) const
implement build a header row for the log
void getLogRow (std::string &target) const
implement build a data row for the log
Private Attributes
const ThermalLoggable * source_mp
The object we will be requesting log data from.
std::string filenameTag_m
String to use as part of the filename.
unsigned int interval_m
logging interval, seconds
bool enable_m
logging only happens while true
std::ostream * dataFile_mp
output data file stream
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 31 of file ThermalLogger.h.
Constructor & Destructor Documentation
ThermalLogger::ThermalLogger (const ThermalLoggable & source, const std::string & filenameTag = std::string()) inline
Definition at line 33 of file ThermalLogger.h.
References reset().
virtual ThermalLogger::~ThermalLogger () inline virtual
Definition at line 40 of file ThermalLogger.h.
References dataFile_mp.
Member Function Documentation
void ThermalLogger::exitAction (bool success) protected virtual
called by OptimizeBase prior to worker thread exit.
Reimplemented from OptimizeBase.
Definition at line 94 of file ThermalLogger.cpp.
void ThermalLogger::getHeaderRow (std::string & target) const private
implement build a header row for the log
Definition at line 103 of file ThermalLogger.cpp.
void ThermalLogger::getLogRow (std::string & target) const private
implement build a data row for the log
Definition at line 109 of file ThermalLogger.cpp.
void ThermalLogger::optimizeAction () protected virtual
called by the OptimizeBase worker thread.
Implements OptimizeBase.
Definition at line 78 of file ThermalLogger.cpp.
void ThermalLogger::reset ()
reset all state to initial/just constructed.
Definition at line 28 of file ThermalLogger.cpp.
Referenced by ThermalLogger().
void ThermalLogger::setLoggingInterval (unsigned int loggingInterval) inline
change the logging interval, in seconds.
Definition at line 52 of file ThermalLogger.h.
References interval_m.
bool ThermalLogger::start (unsigned int loggingInterval)
start logging with the specified interval, in seconds.
Definition at line 33 of file ThermalLogger.cpp.
References OptimizeBase::startWorkerThread().
void ThermalLogger::stop ()
stop logging
Definition at line 63 of file ThermalLogger.cpp.
Member Data Documentation
std::ostream* ThermalLogger::dataFile_mp private
output data file stream
Definition at line 73 of file ThermalLogger.h.
Referenced by ~ThermalLogger().
bool ThermalLogger::enable_m private
logging only happens while true
Definition at line 72 of file ThermalLogger.h.
std::string ThermalLogger::filenameTag_m private
String to use as part of the filename.
Definition at line 70 of file ThermalLogger.h.
unsigned int ThermalLogger::interval_m private
logging interval, seconds
Definition at line 71 of file ThermalLogger.h.
Referenced by setLoggingInterval().
const ThermalLoggable* ThermalLogger::source_mp private
The object we will be requesting log data from.
Definition at line 69 of file ThermalLogger.h.
The documentation for this class was generated from the following files:
OPTIMIZE/ThermalLogger.h
OPTIMIZE/ThermalLogger.cpp