FrontEndControl2: FEMCEventQueue Class Reference
FEMCEventQueue Class Reference
#include <FEMCEventQueue.h>
Classes
struct Event
Public Types
enum EventCodes {
EVENT_NONE = 0, EVENT_PROGRESS = 1, EVENT_STATUS_MESSAGE = 2, EVENT_IVCURVE_DONE = 3,
EVENT_PA_ADJUST_DONE = 4, EVENT_GET_VJVD = 5, EVENT_GET_MAGNET = 6, EVENT_REQUEST_IFPOWER = 7,
EVENT_STOP_IFPOWER = 8, EVENT_CRYO_PUMP_DONE = 9, EVENT_OPTIMIZE_DONE = 10, EVENT_CHOPPER_MOVE = 11,
EVENT_INITIALIZE = 12, EVENT_CARTHC_DONE = 13
}
Static Public Member Functions
static void createInstance ()
Create the singleton instance of the event queue.
static void destroyInstance ()
Destroy the singleton instance of the event queue.
static void subscribe (bool doSubscribe)
subscribe/unsubscribe to pull events from the queue.
static void addEvent (const Event &ev)
add an event to the queue.
static void addStatusMessage (bool success, const std::string &message)
shorthand for adding a status message to the queue.
static void addProgressEvent (short progress)
shorthand for reporting progress.
static bool getNextEvent (Event &target)
get the next event from the queue.
Private Member Functions
FEMCEventQueue ()
~FEMCEventQueue ()
FEMCEventQueue (const FEMCEventQueue &)
FEMCEventQueue & operator= (const FEMCEventQueue &)
Private Attributes
std::deque< Event > queue_m
pthread_mutex_t queueLock_m
int subcribers_m
Static Private Attributes
static FEMCEventQueue * instance_mp = NULL
static pthread_mutex_t instanceLock_m = PTHREAD_MUTEX_INITIALIZER
Detailed Description
Definition at line 8 of file FEMCEventQueue.h.
Member Enumeration Documentation
enum FEMCEventQueue::EventCodes
Enumerator
EVENT_NONE
EVENT_PROGRESS
EVENT_STATUS_MESSAGE
EVENT_IVCURVE_DONE
EVENT_PA_ADJUST_DONE
EVENT_GET_VJVD
EVENT_GET_MAGNET
EVENT_REQUEST_IFPOWER
EVENT_STOP_IFPOWER
EVENT_CRYO_PUMP_DONE
EVENT_OPTIMIZE_DONE
EVENT_CHOPPER_MOVE
EVENT_INITIALIZE
EVENT_CARTHC_DONE
Definition at line 17 of file FEMCEventQueue.h.
Constructor & Destructor Documentation
FEMCEventQueue::FEMCEventQueue () private
Definition at line 32 of file FEMCEventQueue.cpp.
References queueLock_m.
FEMCEventQueue::~FEMCEventQueue () private
Definition at line 39 of file FEMCEventQueue.cpp.
References queueLock_m.
FEMCEventQueue::FEMCEventQueue (const FEMCEventQueue &) private
Member Function Documentation
void FEMCEventQueue::addEvent (const Event & ev) static
add an event to the queue.
Definition at line 63 of file FEMCEventQueue.cpp.
References EVENT_PROGRESS, FEMCEventQueue::Event::eventCode_m, instance_mp, FEMCEventQueue::Event::print(), queue_m, queueLock_m, and subcribers_m.
Referenced by addProgressEvent(), addStatusMessage(), CartAssembly::measureIVCurveSingleSynchronous(), FrontEndImpl::queryCartridgeState(), and OptimizeBase::setEvent().
static void FEMCEventQueue::addProgressEvent (short progress) inline static
shorthand for reporting progress.
Definition at line 80 of file FEMCEventQueue.h.
References addEvent(), and EVENT_PROGRESS.
Referenced by CartAssembly::measureFineLOSweepSingleSynchronous(), and ColdCartImpl::measureIVCurve().
static void FEMCEventQueue::addStatusMessage (bool success, const std::string & message) inline static
shorthand for adding a status message to the queue.
Definition at line 76 of file FEMCEventQueue.h.
References addEvent(), and EVENT_STATUS_MESSAGE.
Referenced by CartAssembly::adjustLOPASinglePol(), WCAImpl::adjustPLL(), FrontEndImpl::cartAdjustLOPowerAmps(), SignalSourceImpl::cartAdjustPLL(), FrontEndImpl::cartAdjustPLL(), SignalSourceImpl::cartAdjustYTO(), FrontEndImpl::cartAdjustYTO(), CartAssembly::CartAssembly(), FrontEndImpl::cartGetVJVD(), FrontEndImpl::cartHealthCheck(), FrontEndImpl::cartHealthCheckSaveIFPowerData(), SignalSourceImpl::cartLockPLL(), FrontEndImpl::cartLockPLL(), FrontEndImpl::cartMeasureFineLOSweep(), FrontEndImpl::cartMeasureIFPowerVsVD(), FrontEndImpl::cartMeasureIFPowerVsVJ(), FrontEndImpl::cartMeasureIJvsSISMagnet(), FrontEndImpl::cartMeasureIVCurve(), FrontEndImpl::cartMixerDeflux(), SignalSourceImpl::cartNullPLLIntegrator(), FrontEndImpl::cartNullPLLIntegrator(), FrontEndImpl::cartOptimizeIFPower(), SignalSourceImpl::cartSetAMC(), FrontEndImpl::cartSetAMC(), FrontEndImpl::cartSetEnableLNABias(), FrontEndImpl::cartSetEnableLNALEDs(), SignalSourceImpl::cartSetEnablePhotomixer(), FrontEndImpl::cartSetEnablePhotomixer(), FrontEndImpl::cartSetEnableSISHeaters(), FrontEndImpl::cartSetLNABias(), SignalSourceImpl::cartSetLOFrequency(), FrontEndImpl::cartSetLOFrequency(), SignalSourceImpl::cartSetLOPowerAmps(), FrontEndImpl::cartSetLOPowerAmps(), FrontEndImpl::cartSetSISBias(), FrontEndImpl::cartSetSISMagnet(), FrontEndImpl::cartSetVJVD(), FEControlInit(), CartAssembly::measureFineLOSweep(), CartAssembly::measureFineLOSweepSingleSynchronous(), ColdCartImpl::measureIVCurve(), CartHealthCheck::optimizeAction(), CartAssembly::optimizeIFPower(), WCAImpl::paPol0DrainVoltage(), WCAImpl::paPol0GateVoltage(), WCAImpl::paPol1DrainVoltage(), WCAImpl::paPol1GateVoltage(), FrontEndImpl::setCartridgeObserving(), SignalSourceImpl::setCartridgeOff(), FrontEndImpl::setCartridgeOff(), SignalSourceImpl::setCartridgeOn(), FrontEndImpl::setCartridgeOn(), CartAssembly::setEnableSISHeaters(), ColdCartImpl::setLNAEnable(), CartAssembly::setLOFrequency(), CartAssembly::setSISBias(), ColdCartImpl::setSISEnable(), CartAssembly::setSISMagnet(), ColdCartImpl::setSISMagnetEnable(), OptimizeBase::setStatusMessage(), sigSrcControlInit(), and ColdCartImpl::sisMixerHeatingProcess().
void FEMCEventQueue::createInstance () static
Create the singleton instance of the event queue.
Since clients only insert and remove events and don't hold references, there's no need to do reference counting.
Definition at line 13 of file FEMCEventQueue.cpp.
Referenced by LVWrapperInit().
void FEMCEventQueue::destroyInstance () static
Destroy the singleton instance of the event queue.
Definition at line 21 of file FEMCEventQueue.cpp.
Referenced by LVWrapperShutdown().
bool FEMCEventQueue::getNextEvent (Event & target) static
get the next event from the queue.
Definition at line 75 of file FEMCEventQueue.cpp.
References instance_mp, queue_m, queueLock_m, and FEMCEventQueue::Event::reset().
Referenced by getNextEvent().
FEMCEventQueue& FEMCEventQueue::operator= (const FEMCEventQueue &) private
void FEMCEventQueue::subscribe (bool doSubscribe) static
subscribe/unsubscribe to pull events from the queue.
if there are no subscribers then events are discarded rather than queued.
Definition at line 52 of file FEMCEventQueue.cpp.
References instance_mp, and subcribers_m.
Referenced by subscribeForEvents().
Member Data Documentation
FEMCEventQueue * FEMCEventQueue::instance_mp = NULL static private
Definition at line 97 of file FEMCEventQueue.h.
Referenced by addEvent(), getNextEvent(), and subscribe().
pthread_mutex_t FEMCEventQueue::instanceLock_m = PTHREAD_MUTEX_INITIALIZER static private
Definition at line 98 of file FEMCEventQueue.h.
std::deque<Event> FEMCEventQueue::queue_m private
Definition at line 101 of file FEMCEventQueue.h.
Referenced by addEvent(), and getNextEvent().
pthread_mutex_t FEMCEventQueue::queueLock_m private
Definition at line 102 of file FEMCEventQueue.h.
Referenced by addEvent(), FEMCEventQueue(), getNextEvent(), and ~FEMCEventQueue().
int FEMCEventQueue::subcribers_m private
Definition at line 105 of file FEMCEventQueue.h.
Referenced by addEvent(), and subscribe().
The documentation for this class was generated from the following files:
FEMCEventQueue.h
FEMCEventQueue.cpp