FrontEndControl2: MeasureFineLOSweep Class Reference
MeasureFineLOSweep Class Reference
#include <MeasureFineLOSweep.h>
Public Member Functions
MeasureFineLOSweep (FrontEndDatabase &dbObject, CartAssembly &CA, XYPlotArray &target)
virtual ~MeasureFineLOSweep ()
void reset ()
reset all state to initial/just constructed.
bool start (const FEICDataBase::ID_T &feConfig, FEICDataBase::DATASTATUS_TYPES dataStatus, float tiltAngle, int pol, float VJ, float IJ, const float *fixedVD, double LOStart, double LOStop, double LOStep, int repeatCount=1)
start a measurement of SIS current, IF power, and PA drain voltage vs. LO frequency
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
virtual void requestStop ()
main thread can call this to request worker thread to stop.
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
virtual void optimizeAction ()
worker thread calls this function repeatedly until done.
virtual void exitAction (bool success)
called by OptimizeBase prior to worker thread exit.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Private Member Functions
void saveData (int pol)
Private Attributes
FrontEndDatabase & dbObject_m
database interface for saving results.
CartAssembly & cartAssembly_m
the cold cartridge assembly to measure.
FEICDataBase::ID_T feConfig_m
configuration ID for the front end
FEICDataBase::DATASTATUS_TYPES dataStatus_m
data status for saving results
int pol_m
Polarization to measure.
float tiltAngle_m
Tilt elevation of this measurement.
float VJNom01_m
Pol0 SIS1 voltage prior to starting measurement.
float VJNom02_m
Pol0 SIS2 voltage prior to starting measurement.
float VJNom11_m
Pol1 SIS1 voltage prior to starting measurement.
float VJNom12_m
Pol1 SIS2 voltage prior to starting measurement.
float VDNom0_m
Pol0 LO PA drain voltage prior to starting measurement.
float VDNom1_m
Pol1 LO PA drain voltage prior to starting measurement.
double freqLONom_m
LO frequency prior to starting measurement.
double freqFLOOG_m
FLOOG frequency in use by the cart assembly.
int sbLock_m
lock below/above ref setting in use by cart assembly.
float VJ_m
junction voltage setting to use for entire sweep.
float IJ_m
junction current to maintain at each LO step.
float fixedVD_m
if >=0 we are measuring at a fixed LO PA drain voltage instead of optimizing it.
double LOStart_m
One end of range for LO frequency to sweep.
double LOStop_m
Other end of range for LO frequency to sweep.
double LOStep_m
Step size for LO frequency to sweep.
int steps_m
number of LO steps to measure.
double FLO_m
Current value of LO frequency.
int repeatCount_m
how many times to repeat the measurement.
float progress_m
progress bar value.
float progressIncrement_m
how much to increment the progress bar at each step.
XYPlotArray sisCurrents_m
output data array for SIS current vs FreqLO
XYPlotArray & loPaVoltages_m
output data array for LO PA drain voltage vs FreqLO.
std::ostream * dataFile_mp
the output log file.
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 32 of file MeasureFineLOSweep.h.
Constructor & Destructor Documentation
MeasureFineLOSweep::MeasureFineLOSweep (FrontEndDatabase & dbObject, CartAssembly & CA, XYPlotArray & target) inline
Parameters
dbObject database interface for saving results
CA CartAssembly for fine LO sweep
target output data array for plot results
Definition at line 34 of file MeasureFineLOSweep.h.
References reset().
virtual MeasureFineLOSweep::~MeasureFineLOSweep () inline virtual
Definition at line 45 of file MeasureFineLOSweep.h.
References dataFile_mp.
Member Function Documentation
void MeasureFineLOSweep::exitAction (bool success) protected virtual
called by OptimizeBase prior to worker thread exit.
Reimplemented from OptimizeBase.
Definition at line 198 of file MeasureFineLOSweep.cpp.
References FEMCEventQueue::EVENT_OPTIMIZE_DONE.
void MeasureFineLOSweep::optimizeAction () protected virtual
worker thread calls this function repeatedly until done.
Implements OptimizeBase.
Definition at line 142 of file MeasureFineLOSweep.cpp.
void MeasureFineLOSweep::reset ()
reset all state to initial/just constructed.
Definition at line 30 of file MeasureFineLOSweep.cpp.
Referenced by MeasureFineLOSweep().
void MeasureFineLOSweep::saveData (int pol) private
Definition at line 231 of file MeasureFineLOSweep.cpp.
bool MeasureFineLOSweep::start (const FEICDataBase::ID_T & feConfig, FEICDataBase::DATASTATUS_TYPES dataStatus, float tiltAngle, int pol, float VJ, float IJ, const float * fixedVD, double LOStart, double LOStop, double LOStep, int repeatCount = 1)
start a measurement of SIS current, IF power, and PA drain voltage vs. LO frequency
Parameters
feConfig front end configuration ID for saving results
dataStatus data status for saving results
Definition at line 46 of file MeasureFineLOSweep.cpp.
References OptimizeBase::startWorkerThread().
Member Data Documentation
CartAssembly& MeasureFineLOSweep::cartAssembly_m private
the cold cartridge assembly to measure.
Definition at line 69 of file MeasureFineLOSweep.h.
std::ostream* MeasureFineLOSweep::dataFile_mp private
the output log file.
Definition at line 101 of file MeasureFineLOSweep.h.
Referenced by ~MeasureFineLOSweep().
FEICDataBase::DATASTATUS_TYPES MeasureFineLOSweep::dataStatus_m private
data status for saving results
Definition at line 72 of file MeasureFineLOSweep.h.
FrontEndDatabase& MeasureFineLOSweep::dbObject_m private
database interface for saving results.
Definition at line 68 of file MeasureFineLOSweep.h.
FEICDataBase::ID_T MeasureFineLOSweep::feConfig_m private
configuration ID for the front end
Definition at line 71 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::fixedVD_m private
if >=0 we are measuring at a fixed LO PA drain voltage instead of optimizing it.
Definition at line 89 of file MeasureFineLOSweep.h.
double MeasureFineLOSweep::FLO_m private
Current value of LO frequency.
Definition at line 95 of file MeasureFineLOSweep.h.
double MeasureFineLOSweep::freqFLOOG_m private
FLOOG frequency in use by the cart assembly.
Definition at line 84 of file MeasureFineLOSweep.h.
double MeasureFineLOSweep::freqLONom_m private
LO frequency prior to starting measurement.
Definition at line 83 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::IJ_m private
junction current to maintain at each LO step.
Definition at line 88 of file MeasureFineLOSweep.h.
XYPlotArray& MeasureFineLOSweep::loPaVoltages_m private
output data array for LO PA drain voltage vs FreqLO.
Definition at line 100 of file MeasureFineLOSweep.h.
double MeasureFineLOSweep::LOStart_m private
One end of range for LO frequency to sweep.
Definition at line 90 of file MeasureFineLOSweep.h.
double MeasureFineLOSweep::LOStep_m private
Step size for LO frequency to sweep.
Definition at line 92 of file MeasureFineLOSweep.h.
double MeasureFineLOSweep::LOStop_m private
Other end of range for LO frequency to sweep.
Definition at line 91 of file MeasureFineLOSweep.h.
int MeasureFineLOSweep::pol_m private
Polarization to measure.
Definition at line 74 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::progress_m private
progress bar value.
Definition at line 97 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::progressIncrement_m private
how much to increment the progress bar at each step.
Definition at line 98 of file MeasureFineLOSweep.h.
int MeasureFineLOSweep::repeatCount_m private
how many times to repeat the measurement.
Definition at line 96 of file MeasureFineLOSweep.h.
int MeasureFineLOSweep::sbLock_m private
lock below/above ref setting in use by cart assembly.
Definition at line 85 of file MeasureFineLOSweep.h.
XYPlotArray MeasureFineLOSweep::sisCurrents_m private
output data array for SIS current vs FreqLO
Definition at line 99 of file MeasureFineLOSweep.h.
int MeasureFineLOSweep::steps_m private
number of LO steps to measure.
Definition at line 93 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::tiltAngle_m private
Tilt elevation of this measurement.
Definition at line 75 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::VDNom0_m private
Pol0 LO PA drain voltage prior to starting measurement.
Definition at line 80 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::VDNom1_m private
Pol1 LO PA drain voltage prior to starting measurement.
Definition at line 81 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::VJ_m private
junction voltage setting to use for entire sweep.
Definition at line 87 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::VJNom01_m private
Pol0 SIS1 voltage prior to starting measurement.
Definition at line 76 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::VJNom02_m private
Pol0 SIS2 voltage prior to starting measurement.
Definition at line 77 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::VJNom11_m private
Pol1 SIS1 voltage prior to starting measurement.
Definition at line 78 of file MeasureFineLOSweep.h.
float MeasureFineLOSweep::VJNom12_m private
Pol1 SIS2 voltage prior to starting measurement.
Definition at line 79 of file MeasureFineLOSweep.h.
The documentation for this class was generated from the following files:
OPTIMIZE/MeasureFineLOSweep.h
OPTIMIZE/MeasureFineLOSweep.cpp