FrontEndControl2: PowerModulesContainer Class Reference
PowerModulesContainer Class Reference
#include <PowerModulesContainer.h>
Classes
class Impl
Public Member Functions
PowerModulesContainer ()
~PowerModulesContainer ()
void reset ()
bool addPowerModule (PowerModuleImpl &module)
bool deletePowerModule (int port)
void startMonitor ()
void stopMonitor ()
bool setEnable (int port)
bool clearEnable (int port)
bool getEnable (int port) const
bool queryEnable (int port)
force a query of the enabled state of the underlying hardware.
bool getMonitorPowerModule (int port, PowerModuleImpl::PowerModule_t &target) const
bool limitsCheck (int port) const
Private Attributes
Impl * modules_m
int numEnabled_m
Detailed Description
Definition at line 26 of file PowerModulesContainer.h.
Constructor & Destructor Documentation
PowerModulesContainer::PowerModulesContainer ()
Definition at line 56 of file PowerModulesContainer.cpp.
PowerModulesContainer::~PowerModulesContainer ()
Definition at line 61 of file PowerModulesContainer.cpp.
References modules_m, and reset().
Member Function Documentation
bool PowerModulesContainer::addPowerModule (PowerModuleImpl & module)
Definition at line 81 of file PowerModulesContainer.cpp.
References PowerModuleImplBase::getPort(), and modules_m.
bool PowerModulesContainer::clearEnable (int port)
Definition at line 128 of file PowerModulesContainer.cpp.
References getEnable(), limitsCheck(), modules_m, and numEnabled_m.
Referenced by deletePowerModule().
bool PowerModulesContainer::deletePowerModule (int port)
Definition at line 91 of file PowerModulesContainer.cpp.
References clearEnable(), limitsCheck(), and modules_m.
bool PowerModulesContainer::getEnable (int port) const
Definition at line 139 of file PowerModulesContainer.cpp.
References limitsCheck(), and modules_m.
Referenced by clearEnable(), and setEnable().
bool PowerModulesContainer::getMonitorPowerModule (int port, PowerModuleImpl::PowerModule_t & target) const
Definition at line 66 of file PowerModulesContainer.cpp.
References limitsCheck(), and modules_m.
bool PowerModulesContainer::limitsCheck (int port) const
Definition at line 153 of file PowerModulesContainer.cpp.
References modules_m.
Referenced by clearEnable(), deletePowerModule(), getEnable(), getMonitorPowerModule(), queryEnable(), and setEnable().
bool PowerModulesContainer::queryEnable (int port)
force a query of the enabled state of the underlying hardware.
Definition at line 146 of file PowerModulesContainer.cpp.
References PowerModuleImplBase::enableModule(), limitsCheck(), and modules_m.
void PowerModulesContainer::reset ()
Definition at line 76 of file PowerModulesContainer.cpp.
References modules_m, and numEnabled_m.
Referenced by ~PowerModulesContainer().
bool PowerModulesContainer::setEnable (int port)
Definition at line 117 of file PowerModulesContainer.cpp.
References getEnable(), limitsCheck(), modules_m, and numEnabled_m.
void PowerModulesContainer::startMonitor ()
Definition at line 99 of file PowerModulesContainer.cpp.
References modules_m.
void PowerModulesContainer::stopMonitor ()
Definition at line 108 of file PowerModulesContainer.cpp.
References modules_m.
Member Data Documentation
Impl* PowerModulesContainer::modules_m private
Definition at line 54 of file PowerModulesContainer.h.
Referenced by addPowerModule(), clearEnable(), deletePowerModule(), getEnable(), getMonitorPowerModule(), limitsCheck(), queryEnable(), reset(), setEnable(), startMonitor(), stopMonitor(), and ~PowerModulesContainer().
int PowerModulesContainer::numEnabled_m private
Definition at line 56 of file PowerModulesContainer.h.
Referenced by clearEnable(), reset(), and setEnable().
The documentation for this class was generated from the following files:
PowerModulesContainer.h
PowerModulesContainer.cpp