FrontEndControl2: FETIMImplBase Class Reference
FETIMImplBase Class Reference
#include <FETIMImplBase.h>
Public Member Functions
FETIMImplBase (const std::string &name)
virtual ~FETIMImplBase ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual float internalTemperature1 ()
virtual float internalTemperature2 ()
virtual float internalTemperature3 ()
virtual float internalTemperature4 ()
virtual float internalTemperature5 ()
virtual bool internalTemperatureOOR ()
virtual float externalTemperature1 ()
virtual float externalTemperature2 ()
virtual bool externalTemperatureOOR1 ()
virtual bool externalTemperatureOOR2 ()
virtual float getAirflowSensor1 ()
virtual float getAirflowSensor2 ()
virtual bool airflowSensorOOR ()
virtual float heliumBufferPressure ()
virtual bool heliumBufferPressureOOR ()
virtual bool sensorSingleFailed ()
virtual bool sensorMultiFailed ()
virtual float glitchValue ()
virtual bool glitchCounterTriggered ()
virtual bool delayShutdownTriggered ()
virtual bool finalShutdownTriggered ()
virtual bool getCompressorStatus ()
virtual bool getCompressorInterlockStatus ()
virtual bool getCompressorCableStatus ()
virtual void setTriggerDewarN2Fill (bool val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Protected Types
enum MonitorControlOffset {
FETIM_INTRLK_SENS_INT_TEMP = 0x0000, FETIM_INTRLK_SENS_FLOW_SENS = 0x0008, FETIM_INTRLK_SENS_SINGLE_FAIL = 0x0010, FETIM_INTRLK_GLITCH_VALUE = 0x0020,
FETIM_INTRLK_GLITCH_CNT_TRIG = 0x0022, FETIM_INTRLK_SENS_MULT_FAIL = 0x0024, FETIM_INTRLK_SENS_INT_TEMP_OOR = 0x0028, FETIM_INTRLK_SENS_FLOW_OOR = 0x002C,
FETIM_INTRLK_DELAY_TRIG = 0x0030, FETIM_INTRLK_SHUTDOWN_TRIG = 0x0034, FETIM_COMP_EXT_TEMP = 0x0040, FETIM_COMP_EXT_TEMP_OOR = 0x0044,
FETIM_COMP_HE2_PRESS = 0x0050, FETIM_COMP_HE2_PRESS_OOR = 0x0054, FETIM_COMP_FE_STATUS = 0x0058, FETIM_COMP_INTRLK_STATUS = 0x0060,
FETIM_COMP_CABLE_STATUS = 0x0068, FETIM_COMP_DEWAR_N2_FILL = 0x0080
}
Protected Member Functions
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Protected Attributes
float internalTemperature1_value
float internalTemperature2_value
float internalTemperature3_value
float internalTemperature4_value
float internalTemperature5_value
bool internalTemperatureOOR_value
float externalTemperature1_value
float externalTemperature2_value
bool externalTemperatureOOR1_value
bool externalTemperatureOOR2_value
float getAirflowSensor1_value
float getAirflowSensor2_value
bool airflowSensorOOR_value
float heliumBufferPressure_value
bool heliumBufferPressureOOR_value
bool sensorSingleFailed_value
bool sensorMultiFailed_value
float glitchValue_value
bool glitchCounterTriggered_value
bool delayShutdownTriggered_value
bool finalShutdownTriggered_value
bool getCompressorStatus_value
bool getCompressorInterlockStatus_value
bool getCompressorCableStatus_value
int internalTemperature1_status
int internalTemperature2_status
int internalTemperature3_status
int internalTemperature4_status
int internalTemperature5_status
int internalTemperatureOOR_status
int externalTemperature1_status
int externalTemperature2_status
int externalTemperatureOOR1_status
int externalTemperatureOOR2_status
int getAirflowSensor1_status
int getAirflowSensor2_status
int airflowSensorOOR_status
int heliumBufferPressure_status
int heliumBufferPressureOOR_status
int sensorSingleFailed_status
int sensorMultiFailed_status
int glitchValue_status
int glitchCounterTriggered_status
int delayShutdownTriggered_status
int finalShutdownTriggered_status
int getCompressorStatus_status
int getCompressorInterlockStatus_status
int getCompressorCableStatus_status
int setTriggerDewarN2Fill_status
AmbRelativeAddr baseRCA
AmbRelativeAddr internalTemperature1_RCA
AmbRelativeAddr internalTemperature2_RCA
AmbRelativeAddr internalTemperature3_RCA
AmbRelativeAddr internalTemperature4_RCA
AmbRelativeAddr internalTemperature5_RCA
AmbRelativeAddr internalTemperatureOOR_RCA
AmbRelativeAddr externalTemperature1_RCA
AmbRelativeAddr externalTemperature2_RCA
AmbRelativeAddr externalTemperatureOOR1_RCA
AmbRelativeAddr externalTemperatureOOR2_RCA
AmbRelativeAddr getAirflowSensor1_RCA
AmbRelativeAddr getAirflowSensor2_RCA
AmbRelativeAddr airflowSensorOOR_RCA
AmbRelativeAddr heliumBufferPressure_RCA
AmbRelativeAddr heliumBufferPressureOOR_RCA
AmbRelativeAddr sensorSingleFailed_RCA
AmbRelativeAddr sensorMultiFailed_RCA
AmbRelativeAddr glitchValue_RCA
AmbRelativeAddr glitchCounterTriggered_RCA
AmbRelativeAddr delayShutdownTriggered_RCA
AmbRelativeAddr finalShutdownTriggered_RCA
AmbRelativeAddr getCompressorStatus_RCA
AmbRelativeAddr getCompressorInterlockStatus_RCA
AmbRelativeAddr getCompressorCableStatus_RCA
AmbRelativeAddr setTriggerDewarN2Fill_RCA
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
FETIMImplBase (const FETIMImplBase &other)
void logMon (bool printHeader=false) const
Private Attributes
Time lastMonitorTime
int monitorPhase
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 32 of file FETIMImplBase.h.
Member Enumeration Documentation
enum FETIMImplBase::MonitorControlOffset protected
Enumerator
FETIM_INTRLK_SENS_INT_TEMP
FETIM_INTRLK_SENS_FLOW_SENS
FETIM_INTRLK_SENS_SINGLE_FAIL
FETIM_INTRLK_GLITCH_VALUE
FETIM_INTRLK_GLITCH_CNT_TRIG
FETIM_INTRLK_SENS_MULT_FAIL
FETIM_INTRLK_SENS_INT_TEMP_OOR
FETIM_INTRLK_SENS_FLOW_OOR
FETIM_INTRLK_DELAY_TRIG
FETIM_INTRLK_SHUTDOWN_TRIG
FETIM_COMP_EXT_TEMP
FETIM_COMP_EXT_TEMP_OOR
FETIM_COMP_HE2_PRESS
FETIM_COMP_HE2_PRESS_OOR
FETIM_COMP_FE_STATUS
FETIM_COMP_INTRLK_STATUS
FETIM_COMP_CABLE_STATUS
FETIM_COMP_DEWAR_N2_FILL
Definition at line 80 of file FETIMImplBase.h.
Constructor & Destructor Documentation
FETIMImplBase::FETIMImplBase (const std::string & name)
Definition at line 33 of file FETIMImplBase.cpp.
References airflowSensorOOR_RCA, baseRCA, delayShutdownTriggered_RCA, externalTemperature1(), externalTemperature1_RCA, externalTemperature1_value, externalTemperature2(), externalTemperature2_RCA, externalTemperature2_value, externalTemperatureOOR1_RCA, externalTemperatureOOR2_RCA, FETIM_COMP_CABLE_STATUS, FETIM_COMP_DEWAR_N2_FILL, FETIM_COMP_EXT_TEMP, FETIM_COMP_EXT_TEMP_OOR, FETIM_COMP_FE_STATUS, FETIM_COMP_HE2_PRESS, FETIM_COMP_HE2_PRESS_OOR, FETIM_COMP_INTRLK_STATUS, FETIM_INTRLK_DELAY_TRIG, FETIM_INTRLK_GLITCH_CNT_TRIG, FETIM_INTRLK_GLITCH_VALUE, FETIM_INTRLK_SENS_FLOW_OOR, FETIM_INTRLK_SENS_FLOW_SENS, FETIM_INTRLK_SENS_INT_TEMP, FETIM_INTRLK_SENS_INT_TEMP_OOR, FETIM_INTRLK_SENS_MULT_FAIL, FETIM_INTRLK_SENS_SINGLE_FAIL, FETIM_INTRLK_SHUTDOWN_TRIG, finalShutdownTriggered_RCA, getAirflowSensor1(), getAirflowSensor1_RCA, getAirflowSensor1_value, getAirflowSensor2(), getAirflowSensor2_RCA, getAirflowSensor2_value, getCompressorCableStatus_RCA, getCompressorInterlockStatus_RCA, getCompressorStatus_RCA, glitchCounterTriggered_RCA, glitchValue(), glitchValue_RCA, glitchValue_value, heliumBufferPressure(), heliumBufferPressure_RCA, heliumBufferPressure_value, heliumBufferPressureOOR_RCA, internalTemperature1(), internalTemperature1_RCA, internalTemperature1_value, internalTemperature2(), internalTemperature2_RCA, internalTemperature2_value, internalTemperature3(), internalTemperature3_RCA, internalTemperature3_value, internalTemperature4(), internalTemperature4_RCA, internalTemperature4_value, internalTemperature5(), internalTemperature5_RCA, internalTemperature5_value, internalTemperatureOOR_RCA, sensorMultiFailed_RCA, sensorSingleFailed_RCA, and setTriggerDewarN2Fill_RCA.
virtual FETIMImplBase::~FETIMImplBase () inline virtual
Definition at line 35 of file FETIMImplBase.h.
References shutdown().
FETIMImplBase::FETIMImplBase (const FETIMImplBase & other) private
Member Function Documentation
bool FETIMImplBase::airflowSensorOOR () virtual
Definition at line 184 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
bool FETIMImplBase::delayShutdownTriggered () virtual
Definition at line 212 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
float FETIMImplBase::externalTemperature1 () virtual
Definition at line 160 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
float FETIMImplBase::externalTemperature2 () virtual
Definition at line 164 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
bool FETIMImplBase::externalTemperatureOOR1 () virtual
Definition at line 168 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
bool FETIMImplBase::externalTemperatureOOR2 () virtual
Definition at line 172 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
bool FETIMImplBase::finalShutdownTriggered () virtual
Definition at line 216 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
float FETIMImplBase::getAirflowSensor1 () virtual
Definition at line 176 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
float FETIMImplBase::getAirflowSensor2 () virtual
Definition at line 180 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
bool FETIMImplBase::getCompressorCableStatus () virtual
Definition at line 228 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
bool FETIMImplBase::getCompressorInterlockStatus () virtual
Definition at line 224 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
bool FETIMImplBase::getCompressorStatus () virtual
Definition at line 220 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
bool FETIMImplBase::glitchCounterTriggered () virtual
Definition at line 208 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
float FETIMImplBase::glitchValue () virtual
Definition at line 204 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
float FETIMImplBase::heliumBufferPressure () virtual
Definition at line 188 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
bool FETIMImplBase::heliumBufferPressureOOR () virtual
Definition at line 192 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
void FETIMImplBase::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Definition at line 128 of file FETIMImplBase.cpp.
References FrontEndLVWrapper::nodeAddress.
Referenced by FETIMImpl::FETIMImpl().
float FETIMImplBase::internalTemperature1 () virtual
Definition at line 136 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
float FETIMImplBase::internalTemperature2 () virtual
Definition at line 140 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
float FETIMImplBase::internalTemperature3 () virtual
Definition at line 144 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
float FETIMImplBase::internalTemperature4 () virtual
Definition at line 148 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
float FETIMImplBase::internalTemperature5 () virtual
Definition at line 152 of file FETIMImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by FETIMImplBase().
bool FETIMImplBase::internalTemperatureOOR () virtual
Definition at line 156 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
void FETIMImplBase::logMon (bool printHeader = false) const private
Definition at line 327 of file FETIMImplBase.cpp.
Referenced by monitorAction().
void FETIMImplBase::monitorAction (Time * timestamp_p) protected virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implements FEHardwareDevice.
Definition at line 236 of file FETIMImplBase.cpp.
References airflowSensorOOR(), airflowSensorOOR_value, delayShutdownTriggered(), delayShutdownTriggered_value, externalTemperatureOOR1(), externalTemperatureOOR1_value, externalTemperatureOOR2(), externalTemperatureOOR2_value, finalShutdownTriggered(), finalShutdownTriggered_value, getCompressorCableStatus(), getCompressorCableStatus_value, getCompressorInterlockStatus(), getCompressorInterlockStatus_value, getCompressorStatus(), getCompressorStatus_value, glitchCounterTriggered(), glitchCounterTriggered_value, heliumBufferPressureOOR(), heliumBufferPressureOOR_value, internalTemperatureOOR(), internalTemperatureOOR_value, lastMonitorTime, logMon(), FEHardwareDevice::logMonitors_m, monitorPhase, FEHardwareDevice::randomizeAnalogMonitors_m, sensorMultiFailed(), sensorMultiFailed_value, sensorSingleFailed(), and sensorSingleFailed_value.
bool FETIMImplBase::sensorMultiFailed () virtual
Definition at line 200 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
bool FETIMImplBase::sensorSingleFailed () virtual
Definition at line 196 of file FETIMImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
void FETIMImplBase::setTriggerDewarN2Fill (bool val) virtual
Definition at line 232 of file FETIMImplBase.cpp.
References SYNCCMD_LOG_BOOL.
void FETIMImplBase::shutdown () virtual
Definition at line 133 of file FETIMImplBase.cpp.
Referenced by ~FETIMImplBase().
Member Data Documentation
AmbRelativeAddr FETIMImplBase::airflowSensorOOR_RCA protected
Definition at line 165 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::airflowSensorOOR_status protected
Definition at line 138 of file FETIMImplBase.h.
bool FETIMImplBase::airflowSensorOOR_value protected
Definition at line 113 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::baseRCA protected
Definition at line 152 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
AmbRelativeAddr FETIMImplBase::delayShutdownTriggered_RCA protected
Definition at line 172 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::delayShutdownTriggered_status protected
Definition at line 145 of file FETIMImplBase.h.
bool FETIMImplBase::delayShutdownTriggered_value protected
Definition at line 120 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::externalTemperature1_RCA protected
Definition at line 159 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::externalTemperature1_status protected
Definition at line 132 of file FETIMImplBase.h.
float FETIMImplBase::externalTemperature1_value protected
Definition at line 107 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::externalTemperature2_RCA protected
Definition at line 160 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::externalTemperature2_status protected
Definition at line 133 of file FETIMImplBase.h.
float FETIMImplBase::externalTemperature2_value protected
Definition at line 108 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::externalTemperatureOOR1_RCA protected
Definition at line 161 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::externalTemperatureOOR1_status protected
Definition at line 134 of file FETIMImplBase.h.
bool FETIMImplBase::externalTemperatureOOR1_value protected
Definition at line 109 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::externalTemperatureOOR2_RCA protected
Definition at line 162 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::externalTemperatureOOR2_status protected
Definition at line 135 of file FETIMImplBase.h.
bool FETIMImplBase::externalTemperatureOOR2_value protected
Definition at line 110 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::finalShutdownTriggered_RCA protected
Definition at line 173 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::finalShutdownTriggered_status protected
Definition at line 146 of file FETIMImplBase.h.
bool FETIMImplBase::finalShutdownTriggered_value protected
Definition at line 121 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::getAirflowSensor1_RCA protected
Definition at line 163 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::getAirflowSensor1_status protected
Definition at line 136 of file FETIMImplBase.h.
float FETIMImplBase::getAirflowSensor1_value protected
Definition at line 111 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::getAirflowSensor2_RCA protected
Definition at line 164 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::getAirflowSensor2_status protected
Definition at line 137 of file FETIMImplBase.h.
float FETIMImplBase::getAirflowSensor2_value protected
Definition at line 112 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::getCompressorCableStatus_RCA protected
Definition at line 176 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::getCompressorCableStatus_status protected
Definition at line 149 of file FETIMImplBase.h.
bool FETIMImplBase::getCompressorCableStatus_value protected
Definition at line 124 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::getCompressorInterlockStatus_RCA protected
Definition at line 175 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::getCompressorInterlockStatus_status protected
Definition at line 148 of file FETIMImplBase.h.
bool FETIMImplBase::getCompressorInterlockStatus_value protected
Definition at line 123 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::getCompressorStatus_RCA protected
Definition at line 174 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::getCompressorStatus_status protected
Definition at line 147 of file FETIMImplBase.h.
bool FETIMImplBase::getCompressorStatus_value protected
Definition at line 122 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::glitchCounterTriggered_RCA protected
Definition at line 171 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::glitchCounterTriggered_status protected
Definition at line 144 of file FETIMImplBase.h.
bool FETIMImplBase::glitchCounterTriggered_value protected
Definition at line 119 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::glitchValue_RCA protected
Definition at line 170 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::glitchValue_status protected
Definition at line 143 of file FETIMImplBase.h.
float FETIMImplBase::glitchValue_value protected
Definition at line 118 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::heliumBufferPressure_RCA protected
Definition at line 166 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::heliumBufferPressure_status protected
Definition at line 139 of file FETIMImplBase.h.
float FETIMImplBase::heliumBufferPressure_value protected
Definition at line 114 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::heliumBufferPressureOOR_RCA protected
Definition at line 167 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::heliumBufferPressureOOR_status protected
Definition at line 140 of file FETIMImplBase.h.
bool FETIMImplBase::heliumBufferPressureOOR_value protected
Definition at line 115 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::internalTemperature1_RCA protected
Definition at line 153 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::internalTemperature1_status protected
Definition at line 126 of file FETIMImplBase.h.
float FETIMImplBase::internalTemperature1_value protected
Definition at line 101 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::internalTemperature2_RCA protected
Definition at line 154 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::internalTemperature2_status protected
Definition at line 127 of file FETIMImplBase.h.
float FETIMImplBase::internalTemperature2_value protected
Definition at line 102 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::internalTemperature3_RCA protected
Definition at line 155 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::internalTemperature3_status protected
Definition at line 128 of file FETIMImplBase.h.
float FETIMImplBase::internalTemperature3_value protected
Definition at line 103 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::internalTemperature4_RCA protected
Definition at line 156 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::internalTemperature4_status protected
Definition at line 129 of file FETIMImplBase.h.
float FETIMImplBase::internalTemperature4_value protected
Definition at line 104 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::internalTemperature5_RCA protected
Definition at line 157 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::internalTemperature5_status protected
Definition at line 130 of file FETIMImplBase.h.
float FETIMImplBase::internalTemperature5_value protected
Definition at line 105 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImplBase(), and FETIMImpl::getMonitorFETIM().
AmbRelativeAddr FETIMImplBase::internalTemperatureOOR_RCA protected
Definition at line 158 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::internalTemperatureOOR_status protected
Definition at line 131 of file FETIMImplBase.h.
bool FETIMImplBase::internalTemperatureOOR_value protected
Definition at line 106 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
Time FETIMImplBase::lastMonitorTime private
Definition at line 183 of file FETIMImplBase.h.
Referenced by monitorAction().
int FETIMImplBase::monitorPhase private
Definition at line 184 of file FETIMImplBase.h.
Referenced by monitorAction().
AmbRelativeAddr FETIMImplBase::sensorMultiFailed_RCA protected
Definition at line 169 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::sensorMultiFailed_status protected
Definition at line 142 of file FETIMImplBase.h.
bool FETIMImplBase::sensorMultiFailed_value protected
Definition at line 117 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::sensorSingleFailed_RCA protected
Definition at line 168 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::sensorSingleFailed_status protected
Definition at line 141 of file FETIMImplBase.h.
bool FETIMImplBase::sensorSingleFailed_value protected
Definition at line 116 of file FETIMImplBase.h.
Referenced by FETIMImpl::appendThermalLog(), FETIMImpl::getMonitorFETIM(), and monitorAction().
AmbRelativeAddr FETIMImplBase::setTriggerDewarN2Fill_RCA protected
Definition at line 177 of file FETIMImplBase.h.
Referenced by FETIMImplBase().
int FETIMImplBase::setTriggerDewarN2Fill_status protected
Definition at line 150 of file FETIMImplBase.h.
The documentation for this class was generated from the following files:
FEBASE/FETIMImplBase.h
FEBASE/FETIMImplBase.cpp