FrontEndControl2: FEConfig::Configuration Class Reference
FEConfig::Configuration Class Reference
Uses the abstract ConfigProvider interface to load a Configuration record into memory.
#include <Configuration.h>
Classes
struct Record
A structure for the elements in the top-level Configuration record.
Public Member Functions
Configuration (unsigned keyFacility=0, unsigned configId=0)
Construct with the primary key items keyFacility, configId which uniquely identify a Configuration record in the config DB.
~Configuration ()
void reset (unsigned keyFacility=0, unsigned configId=0)
reset all data to defaults.
void getConfigID (unsigned &keyFacility, unsigned &configId) const
get the current values of (keyFacility, configId).
const std::string & getDescription () const
get the description for the currently loaded configuration.
bool load (const ConfigProvider &source)
load the configuration for the current values of (keyFacility, configId) from the given provider.
bool save (ConfigProvider &target)
save the currently loaded configureation to the target provider.
const FrontEndConfig * getFrontEndConfig () const
get the FrontEnd configuration item, if any.
const CartAssemblyConfig * getCartAssemblyConfig () const
get the CartAssembly config item, if this configuration is for a single cartridge only.
Private Member Functions
Configuration (const Configuration &other)
copy construct is private and forbidden.
Configuration & operator= (const Configuration &other)
assignment is private and forbidden.
Private Attributes
unsigned keyFacility_m
the provider portion of the primary key.
unsigned configId_m
along with provider uniquely identifies a Configuration.
Record config_m
the top-level configuration info currently loaded.
FrontEndConfig * FE_mp
holds the FrontEnd config, if any.
CartAssemblyConfig * cartAssy_mp
holds the CartAssembly config, if any.
Detailed Description
Uses the abstract ConfigProvider interface to load a Configuration record into memory.
The record contans config items for a whole FrontEnd, or for a single CartAssembly
Definition at line 37 of file Configuration.h.
Constructor & Destructor Documentation
FEConfig::Configuration::Configuration (unsigned keyFacility = 0, unsigned configId = 0)
Construct with the primary key items keyFacility, configId which uniquely identify a Configuration record in the config DB.
These may be changed later with reset().
Definition at line 32 of file Configuration.cpp.
FEConfig::Configuration::~Configuration () inline
Definition at line 44 of file Configuration.h.
References reset().
FEConfig::Configuration::Configuration (const Configuration & other) private
copy construct is private and forbidden.
Member Function Documentation
const CartAssemblyConfig* FEConfig::Configuration::getCartAssemblyConfig () const inline
get the CartAssembly config item, if this configuration is for a single cartridge only.
Definition at line 72 of file Configuration.h.
References cartAssy_mp.
Referenced by FEConfig::ConfigManager::configure(), and sigSrcLoadConfiguration().
void FEConfig::Configuration::getConfigID (unsigned & keyFacility, unsigned & configId) const inline
get the current values of (keyFacility, configId).
Definition at line 51 of file Configuration.h.
References configId_m, and keyFacility_m.
Referenced by FEConfig::ConfigProviderIniFile::saveConfiguration().
const std::string& FEConfig::Configuration::getDescription () const inline
get the description for the currently loaded configuration.
will be empty if no configuration is loaded.
Definition at line 56 of file Configuration.h.
References config_m, and FEConfig::Configuration::Record::description_m.
Referenced by FEConfig::ConfigManager::configure(), and FEConfig::ConfigProviderIniFile::saveConfiguration().
const FrontEndConfig* FEConfig::Configuration::getFrontEndConfig () const inline
get the FrontEnd configuration item, if any.
Definition at line 68 of file Configuration.h.
References FE_mp.
Referenced by FEConfig::ConfigManager::configure(), FELoadConfiguration(), and FEConfig::ConfigProviderIniFile::saveConfiguration().
bool FEConfig::Configuration::load (const ConfigProvider & source)
load the configuration for the current values of (keyFacility, configId) from the given provider.
returns true if the configuration was found and loaded.
Definition at line 51 of file Configuration.cpp.
References FEConfig::Configuration::Record::CAId_m, cartAssy_mp, config_m, configId_m, FEConfig::Configuration::Record::description_m, FEConfig::ConfigProvider::exists(), FE_mp, FEConfig::ConfigProvider::getCartAssemblyConfig(), FEConfig::ConfigProvider::getConfiguration(), FEConfig::ConfigProvider::getFrontEndConfig(), keyFacility_m, FEConfig::Configuration::Record::keyFrontEnd_m, and reset().
Referenced by FEConfig::ConfigManager::configure(), FELoadConfiguration(), and sigSrcLoadConfiguration().
Configuration& FEConfig::Configuration::operator= (const Configuration & other) private
assignment is private and forbidden.
void FEConfig::Configuration::reset (unsigned keyFacility = 0, unsigned configId = 0)
reset all data to defaults.
Use any nonzero values provided for the keys. Otherwise retain the existing values.
Definition at line 39 of file Configuration.cpp.
References cartAssy_mp, config_m, FrontEndLVWrapper::configId, configId_m, FE_mp, keyFacility_m, and FEConfig::Configuration::Record::reset().
Referenced by load(), and ~Configuration().
bool FEConfig::Configuration::save (ConfigProvider & target)
save the currently loaded configureation to the target provider.
Definition at line 95 of file Configuration.cpp.
References config_m, configId_m, FEConfig::Configuration::Record::description_m, keyFacility_m, and FEConfig::ConfigProvider::saveConfiguration().
Member Data Documentation
CartAssemblyConfig* FEConfig::Configuration::cartAssy_mp private
holds the CartAssembly config, if any.
Definition at line 120 of file Configuration.h.
Referenced by getCartAssemblyConfig(), load(), and reset().
Record FEConfig::Configuration::config_m private
the top-level configuration info currently loaded.
Definition at line 117 of file Configuration.h.
Referenced by getDescription(), load(), reset(), and save().
unsigned FEConfig::Configuration::configId_m private
along with provider uniquely identifies a Configuration.
Definition at line 115 of file Configuration.h.
Referenced by getConfigID(), load(), reset(), and save().
FrontEndConfig* FEConfig::Configuration::FE_mp private
holds the FrontEnd config, if any.
Definition at line 119 of file Configuration.h.
Referenced by getFrontEndConfig(), load(), and reset().
unsigned FEConfig::Configuration::keyFacility_m private
the provider portion of the primary key.
Definition at line 114 of file Configuration.h.
Referenced by getConfigID(), load(), reset(), and save().
The documentation for this class was generated from the following files:
CONFIG/Configuration.h
CONFIG/Configuration.cpp