FrontEndControl2: MeasureIVCurve Class Reference
MeasureIVCurve Class Reference
#include <MeasureIVCurve.h>
Public Member Functions
MeasureIVCurve (ColdCartImpl &ColdCart, XYPlotArray &target)
virtual ~MeasureIVCurve ()
void reset ()
reset all state to initial/just constructed.
bool start (int pol, int sb, float VJlow, float VJhigh, float VJstep, int repeatCount=1)
Start an I-V curve measurement.
virtual void requestStop ()
main thread can call this to request worker thread to stop.
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
virtual void optimizeAction ()
derived classes must declare an optimizeAction method for the worker thread to call.
virtual void exitAction (bool success)
derived classes may declare an exitAction which gets called just prior to the thread exiting.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Private Member Functions
bool actionImpl ()
Private Attributes
ColdCartImpl & coldCart_m
int pol_m
int sb_m
float VJlow_m
float VJhigh_m
float VJstep_m
int repeatCount_m
XYPlotArray & data_m
std::ostream * dataFile_mp
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 31 of file MeasureIVCurve.h.
Constructor & Destructor Documentation
MeasureIVCurve::MeasureIVCurve (ColdCartImpl & ColdCart, XYPlotArray & target) inline
Definition at line 33 of file MeasureIVCurve.h.
References reset().
virtual MeasureIVCurve::~MeasureIVCurve () inline virtual
Definition at line 40 of file MeasureIVCurve.h.
References dataFile_mp.
Member Function Documentation
bool MeasureIVCurve::actionImpl () private
void MeasureIVCurve::exitAction (bool success) protected virtual
derived classes may declare an exitAction which gets called just prior to the thread exiting.
whatever value is passed to setFinished(bool) by optimizeAction() is passed in here as success.
Reimplemented from OptimizeBase.
Definition at line 76 of file MeasureIVCurve.cpp.
References FEMCEventQueue::EVENT_IVCURVE_DONE.
void MeasureIVCurve::optimizeAction () protected virtual
derived classes must declare an optimizeAction method for the worker thread to call.
Implements OptimizeBase.
Definition at line 60 of file MeasureIVCurve.cpp.
void MeasureIVCurve::requestStop () virtual
main thread can call this to request worker thread to stop.
Reimplemented from OptimizeBase.
Definition at line 54 of file MeasureIVCurve.cpp.
References OptimizeBase::requestStop().
void MeasureIVCurve::reset ()
reset all state to initial/just constructed.
Definition at line 31 of file MeasureIVCurve.cpp.
Referenced by MeasureIVCurve().
bool MeasureIVCurve::start (int pol, int sb, float VJlow, float VJhigh, float VJstep, int repeatCount = 1)
Start an I-V curve measurement.
Definition at line 42 of file MeasureIVCurve.cpp.
References OptimizeBase::startWorkerThread().
Member Data Documentation
ColdCartImpl& MeasureIVCurve::coldCart_m private
Definition at line 60 of file MeasureIVCurve.h.
XYPlotArray& MeasureIVCurve::data_m private
Definition at line 69 of file MeasureIVCurve.h.
std::ostream* MeasureIVCurve::dataFile_mp private
Definition at line 70 of file MeasureIVCurve.h.
Referenced by ~MeasureIVCurve().
int MeasureIVCurve::pol_m private
Definition at line 62 of file MeasureIVCurve.h.
int MeasureIVCurve::repeatCount_m private
Definition at line 67 of file MeasureIVCurve.h.
int MeasureIVCurve::sb_m private
Definition at line 63 of file MeasureIVCurve.h.
float MeasureIVCurve::VJhigh_m private
Definition at line 65 of file MeasureIVCurve.h.
float MeasureIVCurve::VJlow_m private
Definition at line 64 of file MeasureIVCurve.h.
float MeasureIVCurve::VJstep_m private
Definition at line 66 of file MeasureIVCurve.h.
The documentation for this class was generated from the following files:
OPTIMIZE/MeasureIVCurve.h
OPTIMIZE/MeasureIVCurve.cpp