FrontEndControl2: LPRImplBase Class Reference
LPRImplBase Class Reference
#include <LPRImplBase.h>
Public Member Functions
LPRImplBase (const std::string &name)
virtual ~LPRImplBase ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual float LPRTemperature0 ()
virtual float LPRTemperature1 ()
virtual unsigned char opticalSwitchPort ()
virtual bool opticalSwitchShutter ()
virtual bool opticalSwitchState ()
virtual bool opticalSwitchBusy ()
virtual float EDFALaserPumpTemperature ()
virtual float EDFALaserDriveCurrent ()
virtual float EDFALaserPhotoDetectCurrent ()
virtual float EDFAPhotoDetectCurrent ()
virtual float EDFAPhotoDetectPower ()
virtual float EDFAModulationInput ()
virtual void opticalSwitchPort (unsigned char val)
virtual void opticalSwitchShutter (bool val)
virtual void opticalSwitchForceShutter (bool val)
virtual void EDFAModulationInput (float val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Protected Types
enum MonitorControlOffset {
LPR_TEMPERATURE_0 = 0x0000, LPR_TEMPERATURE_1 = 0x0010, OPTICAL_SWITCH_PORT = 0x0020, OPTICAL_SWITCH_SHUTTER = 0x0022,
OPTICAL_SWITCH_FORCE_SHUTTER = 0x0024, OPTICAL_SWITCH_STATE = 0x0026, OPTICAL_SWITCH_BUSY = 0x0028, EDFA_LASER_PUMP_TEMPERATURE = 0x0030,
EDFA_LASER_DRIVE_CURRENT = 0x0031, EDFA_LASER_PHOTODETECT_CURRENT = 0x0032, EDFA_PHOTODETECT_CURRENT = 0x0034, EDFA_PHOTODETECT_POWER = 0x0036,
EDFA_MODULATION_INPUT = 0x0038, EDFA_DRIVER_TEMPERATURE_ALARM = 0x003C
}
Protected Member Functions
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Protected Attributes
float LPRTemperature0_value
float LPRTemperature1_value
unsigned char opticalSwitchPort_value
bool opticalSwitchShutter_value
bool opticalSwitchState_value
bool opticalSwitchBusy_value
float EDFALaserPumpTemperature_value
float EDFALaserDriveCurrent_value
float EDFALaserPhotoDetectCurrent_value
float EDFAPhotoDetectCurrent_value
float EDFAPhotoDetectPower_value
float EDFAModulationInput_value
int LPRTemperature0_status
int LPRTemperature1_status
int opticalSwitchPort_status
int opticalSwitchShutter_status
int opticalSwitchForceShutter_status
int opticalSwitchState_status
int opticalSwitchBusy_status
int EDFALaserPumpTemperature_status
int EDFALaserDriveCurrent_status
int EDFALaserPhotoDetectCurrent_status
int EDFAPhotoDetectCurrent_status
int EDFAPhotoDetectPower_status
int EDFAModulationInput_status
AmbRelativeAddr baseRCA
AmbRelativeAddr LPRTemperature0_RCA
AmbRelativeAddr LPRTemperature1_RCA
AmbRelativeAddr opticalSwitchPort_RCA
AmbRelativeAddr opticalSwitchShutter_RCA
AmbRelativeAddr opticalSwitchForceShutter_RCA
AmbRelativeAddr opticalSwitchState_RCA
AmbRelativeAddr opticalSwitchBusy_RCA
AmbRelativeAddr EDFALaserPumpTemperature_RCA
AmbRelativeAddr EDFALaserDriveCurrent_RCA
AmbRelativeAddr EDFALaserPhotoDetectCurrent_RCA
AmbRelativeAddr EDFAPhotoDetectCurrent_RCA
AmbRelativeAddr EDFAPhotoDetectPower_RCA
AmbRelativeAddr EDFAModulationInput_RCA
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
LPRImplBase (const LPRImplBase &other)
void logMon (bool printHeader=false) const
Private Attributes
Time lastMonitorTime
int monitorPhase
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 32 of file LPRImplBase.h.
Member Enumeration Documentation
enum LPRImplBase::MonitorControlOffset protected
Enumerator
LPR_TEMPERATURE_0
LPR_TEMPERATURE_1
OPTICAL_SWITCH_PORT
OPTICAL_SWITCH_SHUTTER
OPTICAL_SWITCH_FORCE_SHUTTER
OPTICAL_SWITCH_STATE
OPTICAL_SWITCH_BUSY
EDFA_LASER_PUMP_TEMPERATURE
EDFA_LASER_DRIVE_CURRENT
EDFA_LASER_PHOTODETECT_CURRENT
EDFA_PHOTODETECT_CURRENT
EDFA_PHOTODETECT_POWER
EDFA_MODULATION_INPUT
EDFA_DRIVER_TEMPERATURE_ALARM
Definition at line 64 of file LPRImplBase.h.
Constructor & Destructor Documentation
LPRImplBase::LPRImplBase (const std::string & name)
Definition at line 33 of file LPRImplBase.cpp.
References baseRCA, EDFA_LASER_DRIVE_CURRENT, EDFA_LASER_PHOTODETECT_CURRENT, EDFA_LASER_PUMP_TEMPERATURE, EDFA_MODULATION_INPUT, EDFA_PHOTODETECT_CURRENT, EDFA_PHOTODETECT_POWER, EDFALaserDriveCurrent(), EDFALaserDriveCurrent_RCA, EDFALaserDriveCurrent_value, EDFALaserPhotoDetectCurrent(), EDFALaserPhotoDetectCurrent_RCA, EDFALaserPhotoDetectCurrent_value, EDFALaserPumpTemperature(), EDFALaserPumpTemperature_RCA, EDFALaserPumpTemperature_value, EDFAModulationInput(), EDFAModulationInput_RCA, EDFAModulationInput_value, EDFAPhotoDetectCurrent(), EDFAPhotoDetectCurrent_RCA, EDFAPhotoDetectCurrent_value, EDFAPhotoDetectPower(), EDFAPhotoDetectPower_RCA, EDFAPhotoDetectPower_value, LPR_TEMPERATURE_0, LPR_TEMPERATURE_1, LPRTemperature0(), LPRTemperature0_RCA, LPRTemperature0_value, LPRTemperature1(), LPRTemperature1_RCA, LPRTemperature1_value, OPTICAL_SWITCH_BUSY, OPTICAL_SWITCH_FORCE_SHUTTER, OPTICAL_SWITCH_PORT, OPTICAL_SWITCH_SHUTTER, OPTICAL_SWITCH_STATE, opticalSwitchBusy_RCA, opticalSwitchForceShutter_RCA, opticalSwitchPort_RCA, opticalSwitchShutter_RCA, and opticalSwitchState_RCA.
virtual LPRImplBase::~LPRImplBase () inline virtual
Definition at line 35 of file LPRImplBase.h.
References shutdown().
LPRImplBase::LPRImplBase (const LPRImplBase & other) private
Member Function Documentation
float LPRImplBase::EDFALaserDriveCurrent () virtual
Definition at line 113 of file LPRImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by LPRImplBase().
float LPRImplBase::EDFALaserPhotoDetectCurrent () virtual
Definition at line 117 of file LPRImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by LPRImplBase().
float LPRImplBase::EDFALaserPumpTemperature () virtual
Definition at line 109 of file LPRImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by LPRImplBase().
float LPRImplBase::EDFAModulationInput () virtual
Definition at line 129 of file LPRImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by EDFAModulationInput(), and LPRImplBase().
void LPRImplBase::EDFAModulationInput (float val) virtual
Definition at line 145 of file LPRImplBase.cpp.
References EDFAModulationInput(), and SYNCCMD_LOG_FLOAT.
float LPRImplBase::EDFAPhotoDetectCurrent () virtual
Definition at line 121 of file LPRImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by LPRImplBase().
float LPRImplBase::EDFAPhotoDetectPower () virtual
Definition at line 125 of file LPRImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by LPRImplBase().
void LPRImplBase::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Definition at line 77 of file LPRImplBase.cpp.
References FrontEndLVWrapper::nodeAddress.
Referenced by LPRImpl::LPRImpl().
void LPRImplBase::logMon (bool printHeader = false) const private
Definition at line 204 of file LPRImplBase.cpp.
Referenced by monitorAction().
float LPRImplBase::LPRTemperature0 () virtual
Definition at line 85 of file LPRImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by LPRImplBase().
float LPRImplBase::LPRTemperature1 () virtual
Definition at line 89 of file LPRImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by LPRImplBase().
void LPRImplBase::monitorAction (Time * timestamp_p) protected virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implements FEHardwareDevice.
Definition at line 149 of file LPRImplBase.cpp.
References lastMonitorTime, logMon(), FEHardwareDevice::logMonitors_m, monitorPhase, opticalSwitchBusy(), opticalSwitchBusy_value, opticalSwitchPort(), opticalSwitchPort_value, opticalSwitchShutter(), opticalSwitchShutter_value, opticalSwitchState(), opticalSwitchState_value, and FEHardwareDevice::randomizeAnalogMonitors_m.
bool LPRImplBase::opticalSwitchBusy () virtual
Definition at line 105 of file LPRImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and LPRImpl::setObservingBand().
void LPRImplBase::opticalSwitchForceShutter (bool val) virtual
Definition at line 141 of file LPRImplBase.cpp.
References SYNCCMD_LOG_BOOL.
unsigned char LPRImplBase::opticalSwitchPort () virtual
Definition at line 93 of file LPRImplBase.cpp.
References SYNCMON_LOG_INT.
Referenced by LPRImpl::getMonitorLPR(), monitorAction(), opticalSwitchPort(), and LPRImpl::setObservingBand().
void LPRImplBase::opticalSwitchPort (unsigned char val) virtual
Definition at line 133 of file LPRImplBase.cpp.
References opticalSwitchPort(), and SYNCCMD_LOG_INT.
bool LPRImplBase::opticalSwitchShutter () virtual
Definition at line 97 of file LPRImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and opticalSwitchShutter().
void LPRImplBase::opticalSwitchShutter (bool val) virtual
Definition at line 137 of file LPRImplBase.cpp.
References opticalSwitchShutter(), and SYNCCMD_LOG_BOOL.
bool LPRImplBase::opticalSwitchState () virtual
Definition at line 101 of file LPRImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction().
void LPRImplBase::shutdown () virtual
Definition at line 82 of file LPRImplBase.cpp.
Referenced by ~LPRImplBase().
Member Data Documentation
AmbRelativeAddr LPRImplBase::baseRCA protected
Definition at line 108 of file LPRImplBase.h.
Referenced by LPRImplBase().
AmbRelativeAddr LPRImplBase::EDFALaserDriveCurrent_RCA protected
Definition at line 117 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::EDFALaserDriveCurrent_status protected
Definition at line 102 of file LPRImplBase.h.
float LPRImplBase::EDFALaserDriveCurrent_value protected
Definition at line 88 of file LPRImplBase.h.
Referenced by LPRImpl::getMonitorLPR(), and LPRImplBase().
AmbRelativeAddr LPRImplBase::EDFALaserPhotoDetectCurrent_RCA protected
Definition at line 118 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::EDFALaserPhotoDetectCurrent_status protected
Definition at line 103 of file LPRImplBase.h.
float LPRImplBase::EDFALaserPhotoDetectCurrent_value protected
Definition at line 89 of file LPRImplBase.h.
Referenced by LPRImpl::getMonitorLPR(), and LPRImplBase().
AmbRelativeAddr LPRImplBase::EDFALaserPumpTemperature_RCA protected
Definition at line 116 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::EDFALaserPumpTemperature_status protected
Definition at line 101 of file LPRImplBase.h.
float LPRImplBase::EDFALaserPumpTemperature_value protected
Definition at line 87 of file LPRImplBase.h.
Referenced by LPRImpl::appendThermalLog(), LPRImpl::getMonitorLPR(), and LPRImplBase().
AmbRelativeAddr LPRImplBase::EDFAModulationInput_RCA protected
Definition at line 121 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::EDFAModulationInput_status protected
Definition at line 106 of file LPRImplBase.h.
float LPRImplBase::EDFAModulationInput_value protected
Definition at line 92 of file LPRImplBase.h.
Referenced by LPRImpl::getMonitorLPR(), and LPRImplBase().
AmbRelativeAddr LPRImplBase::EDFAPhotoDetectCurrent_RCA protected
Definition at line 119 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::EDFAPhotoDetectCurrent_status protected
Definition at line 104 of file LPRImplBase.h.
float LPRImplBase::EDFAPhotoDetectCurrent_value protected
Definition at line 90 of file LPRImplBase.h.
Referenced by LPRImpl::getMonitorLPR(), and LPRImplBase().
AmbRelativeAddr LPRImplBase::EDFAPhotoDetectPower_RCA protected
Definition at line 120 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::EDFAPhotoDetectPower_status protected
Definition at line 105 of file LPRImplBase.h.
float LPRImplBase::EDFAPhotoDetectPower_value protected
Definition at line 91 of file LPRImplBase.h.
Referenced by LPRImpl::getMonitorLPR(), and LPRImplBase().
Time LPRImplBase::lastMonitorTime private
Definition at line 127 of file LPRImplBase.h.
Referenced by monitorAction().
AmbRelativeAddr LPRImplBase::LPRTemperature0_RCA protected
Definition at line 109 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::LPRTemperature0_status protected
Definition at line 94 of file LPRImplBase.h.
float LPRImplBase::LPRTemperature0_value protected
Definition at line 81 of file LPRImplBase.h.
Referenced by LPRImpl::appendThermalLog(), LPRImpl::getMonitorLPR(), and LPRImplBase().
AmbRelativeAddr LPRImplBase::LPRTemperature1_RCA protected
Definition at line 110 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::LPRTemperature1_status protected
Definition at line 95 of file LPRImplBase.h.
float LPRImplBase::LPRTemperature1_value protected
Definition at line 82 of file LPRImplBase.h.
Referenced by LPRImpl::appendThermalLog(), LPRImpl::getMonitorLPR(), and LPRImplBase().
int LPRImplBase::monitorPhase private
Definition at line 128 of file LPRImplBase.h.
Referenced by monitorAction().
AmbRelativeAddr LPRImplBase::opticalSwitchBusy_RCA protected
Definition at line 115 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::opticalSwitchBusy_status protected
Definition at line 100 of file LPRImplBase.h.
bool LPRImplBase::opticalSwitchBusy_value protected
Definition at line 86 of file LPRImplBase.h.
Referenced by LPRImpl::getMonitorLPR(), and monitorAction().
AmbRelativeAddr LPRImplBase::opticalSwitchForceShutter_RCA protected
Definition at line 113 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::opticalSwitchForceShutter_status protected
Definition at line 98 of file LPRImplBase.h.
AmbRelativeAddr LPRImplBase::opticalSwitchPort_RCA protected
Definition at line 111 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::opticalSwitchPort_status protected
Definition at line 96 of file LPRImplBase.h.
unsigned char LPRImplBase::opticalSwitchPort_value protected
Definition at line 83 of file LPRImplBase.h.
Referenced by monitorAction().
AmbRelativeAddr LPRImplBase::opticalSwitchShutter_RCA protected
Definition at line 112 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::opticalSwitchShutter_status protected
Definition at line 97 of file LPRImplBase.h.
bool LPRImplBase::opticalSwitchShutter_value protected
Definition at line 84 of file LPRImplBase.h.
Referenced by LPRImpl::getMonitorLPR(), and monitorAction().
AmbRelativeAddr LPRImplBase::opticalSwitchState_RCA protected
Definition at line 114 of file LPRImplBase.h.
Referenced by LPRImplBase().
int LPRImplBase::opticalSwitchState_status protected
Definition at line 99 of file LPRImplBase.h.
bool LPRImplBase::opticalSwitchState_value protected
Definition at line 85 of file LPRImplBase.h.
Referenced by LPRImpl::getMonitorLPR(), and monitorAction().
The documentation for this class was generated from the following files:
FEBASE/LPRImplBase.h
FEBASE/LPRImplBase.cpp