FrontEndControl2: LORTMImplBase Class Reference
LORTMImplBase Class Reference
#include <LORTMImplBase.h>
Public Member Functions
LORTMImplBase (const std::string &name)
virtual ~LORTMImplBase ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual std::string GetSerialNumber ()
virtual std::string GetProtocolRevision ()
virtual std::string GetFirmwareVersion ()
virtual unsigned long AMBSINumErrors ()
virtual unsigned long AMBSINumTransactions ()
virtual float AmbientTemperature ()
virtual unsigned short SystemGetStatus ()
virtual short SystemGetError ()
virtual short SystemGetWarning ()
virtual float LaserBiasMon1 ()
virtual float LaserBiasMon2 ()
virtual float LaserBiasMon3 ()
virtual float LaserBiasMon4 ()
virtual float TempIntegOutMon1 ()
virtual float TempIntegOutMon2 ()
virtual float TempIntegOutMon3 ()
virtual float TempIntegOutMon4 ()
virtual float LaserTempMon1 ()
virtual float LaserTempMon2 ()
virtual float LaserTempMon3 ()
virtual float LaserTempMon4 ()
virtual float LaserTecIMon1 ()
virtual float LaserTecIMon2 ()
virtual float LaserTecIMon3 ()
virtual float LaserTecIMon4 ()
virtual float LaserPowMon1 ()
virtual float LaserPowMon2 ()
virtual float LaserPowMon3 ()
virtual float LaserPowMon4 ()
virtual float PhMixBiasMon1 ()
virtual float PhMixBiasMon2 ()
virtual float PhMixBiasMon3 ()
virtual float PhMixBiasMon4 ()
virtual float LaserSlowCorrMon ()
virtual float RFAGCGainMon ()
virtual float RFPowMon34dB ()
virtual float ExternThermMon ()
virtual float InternThermMon ()
virtual unsigned char LaserGetStatus1 ()
virtual unsigned char LaserGetStatus2 ()
virtual unsigned char LaserGetStatus3 ()
virtual unsigned char LaserGetStatus4 ()
virtual bool LaserISrcEnable (int laser)
virtual unsigned long LaserFrequency (int laser)
virtual float LaserCalibCoeffA (int laser, int coeff)
virtual float LaserCalibCoeffB (int laser, int coeff)
virtual float LaserCalibCoeffC (int laser, int coeff)
virtual unsigned short PhaselockGetStatus ()
virtual unsigned char PhaselockGetSelectedLaser ()
virtual unsigned char PhaselockGetSelectedBand ()
virtual void ResetAMBSI ()
virtual void ResetDevice ()
virtual void SystemManualModeRequest ()
virtual void SystemStandbyModeRequest ()
virtual void SystemLoadAllParameters ()
virtual void SystemSaveAllParameters ()
virtual void SystemClearErrors ()
virtual void PhaseLockTuningInit (unsigned long slaveFreqMHz)
virtual void PhaseLockTuningFinalize ()
virtual void LaserISrcEnable (int laser, bool enable)
virtual void LaserSetFrequency (int laser, unsigned long slaveFreqMHz)
virtual void LaserCalibrationSelect (int laser)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Public Attributes
float AmbientTemperature_value
Protected Types
enum MonitorControlOffset {
GET_SERIAL_NUMBER = 0x00000, GET_PROTOCOL_REV_LEVEL = 0x30000, AMBSI_NUM_ERRORS = 0x30001, AMBSI_NUM_TRANSACIONS = 0x30002,
GET_AMBIENT_TEMPERATURE = 0x30003, GET_SW_REV_LEVEL = 0x30004, RESET_AMBSI = 0x31000, RESET_DEVICE = 0x31001,
SYSTEM_MANUAL_MODE_REQUEST = 0x01000, SYSTEM_STANDBY_MODE_REQUEST = 0x01001, SYSTEM_LOAD_ALL_PARAMS = 0X01002, SYSTEM_SAVE_ALL_PARAMS = 0x01003,
SYSTEM_CLEAR_ERRORS = 0x01004, SYSTEM_GET_STATUS = 0x01100, SYSTEM_GET_ERROR = 0x01101, SYSTEM_GET_WARNING = 0x01102,
SYSTEM_GET_INTERLOCK_STATUS = 0x01120, SYSTEM_STARTUP_MODE = 0x01800, SIGNAL_LASER_BIAS_MON1 = 0x01500, SIGNAL_LASER_BIAS_MON2 = 0x01501,
SIGNAL_LASER_BIAS_MON3 = 0x01502, SIGNAL_LASER_BIAS_MON4 = 0x01503, SIGNAL_TEMP_INTEG_OUT_MON1 = 0x01504, SIGNAL_TEMP_INTEG_OUT_MON2 = 0x01505,
SIGNAL_TEMP_INTEG_OUT_MON3 = 0x01506, SIGNAL_TEMP_INTEG_OUT_MON4 = 0x01507, SIGNAL_LASER_TEMP_MON1 = 0x01508, SIGNAL_LASER_TEMP_MON2 = 0x01509,
SIGNAL_LASER_TEMP_MON3 = 0x0150A, SIGNAL_LASER_TEMP_MON4 = 0x0150B, SIGNAL_LASER_TEC_I_MON1 = 0x0150C, SIGNAL_LASER_TEC_I_MON2 = 0x0150D,
SIGNAL_LASER_TEC_I_MON3 = 0x0150E, SIGNAL_LASER_TEC_I_MON4 = 0x0150F, SIGNAL_LASER_POW_MON1 = 0x01510, SIGNAL_LASER_POW_MON2 = 0x01511,
SIGNAL_LASER_POW_MON3 = 0x01512, SIGNAL_LASER_POW_MON4 = 0x01513, SIGNAL_PHMIX_BIAS_MON1 = 0x01514, SIGNAL_PHMIX_BIAS_MON2 = 0x01515,
SIGNAL_PHMIX_BIAS_MON3 = 0x01516, SIGNAL_PHMIX_BIAS_MON4 = 0x01517, SIGNAL_LASER_SLOW_CORR_MON = 0x01518, SIGNAL_RF_AGC_GAIN_MON = 0x01519,
SIGNAL_RF_POW_MON_34DB = 0x0151A, SIGNAL_EXTERN_THERM_MON = 0x0151B, SIGNAL_INTERN_THERM_MON = 0x0151C, SIGNAL_GROUND = 0x0151F,
LASER_GET_STATUS1 = 0x0203C, LASER_GET_STATUS2 = 0x0203D, LASER_GET_STATUS3 = 0x0203E, LASER_GET_STATUS4 = 0x0203F,
LASER_ICRC_BIAS = 0x02000, LASER_TEMP_SETPOINT = 0x02004, LASER_ISRC_ENABLE = 0x02008, LASER_TEMP_CTRL_ENABLE = 0x0200C,
LASER_FREQUENCY = 0x02050, LASER_OPERATING_CURRENT = 0x02070, LASER_POWER_CALIB_COEFF = 0x02074, LASER_CALIBRATION_CURRENT = 0x02100,
LASER_CALIBRATION_COEFF_A = 0x02110, LASER_CALIBRATION_COEFF_B = 0x02120, LASER_CALIBRATION_COEFF_C = 0x02130, PHASELOCK_TUNING_INIT = 0x03000,
PHASELOCK_TUNING_FINALIZE = 0x03001, PHASELOCK_GET_STATUS = 0x03020, PHASELOCK_GET_SELECTED_LASER = 0x03034, PHASELOCK_GET_SELECTED_BAND = 0x03035,
LL_OPTSW_CALIBRATION = 0x06110, LL_OPTSW_BANDSEL = 0x06111, LL_OPTSW_SLAVESEL = 0x06112
}
Protected Member Functions
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Protected Attributes
std::string SerialNumber_value
std::string ProtocolRevision_value
std::string FirmwareVersion_value
unsigned long CANStatus_value
unsigned long AMBSINumErrors_value
unsigned long AMBSINumTransactions_value
int AmbientTemperature_status
unsigned short SystemGetStatus_value
unsigned char systemState
bool systemWarning
bool systemError
bool operationPending
short SystemGetError_value
short SystemGetWarning_value
bool SystemGetInterlockStatus_value
float LaserBiasMon1_value
float LaserBiasMon2_value
float LaserBiasMon3_value
float LaserBiasMon4_value
float TempIntegOutMon1_value
float TempIntegOutMon2_value
float TempIntegOutMon3_value
float TempIntegOutMon4_value
float LaserTempMon1_value
float LaserTempMon2_value
float LaserTempMon3_value
float LaserTempMon4_value
float LaserTecIMon1_value
float LaserTecIMon2_value
float LaserTecIMon3_value
float LaserTecIMon4_value
float LaserPowMon1_value
float LaserPowMon2_value
float LaserPowMon3_value
float LaserPowMon4_value
float PhMixBiasMon1_value
float PhMixBiasMon2_value
float PhMixBiasMon3_value
float PhMixBiasMon4_value
float LaserSlowCorrMon_value
float RFAGCGainMon_value
float RFPowMon34dB_value
float ExternThermMon_value
float InternThermMon_value
unsigned char LaserGetStatus1_value
unsigned char LaserGetStatus2_value
unsigned char LaserGetStatus3_value
unsigned char LaserGetStatus4_value
unsigned short PhaselockGetStatus_value
bool phaselockLocked
bool phaselockTuningReady
bool phaselockRFInputReady
unsigned char PhaselockGetSelectedLaser_value
unsigned char PhaselockGetSelectedBand_value
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
LORTMImplBase (const LORTMImplBase &other)
Static Private Member Functions
static float convertLaserBiasMon (unsigned short adValue)
static float convertTempIntegMon (unsigned short adValue)
static float convertTemperatureMon (unsigned short adValue)
static float convertTECIMon (unsigned short adValue)
static float convertLaserPowerMon (unsigned short adValue)
static float convertPhmixBiasMon (unsigned short adValue)
static float convertSlowCorrMon (unsigned short adValue)
static float convertRFAGCGainMon (unsigned short adValue)
static float convertRFPowMon34dB (unsigned short adValue)
Private Attributes
Time lastMonitorTime
Time lastMonitorTime30s
int monitorPhase
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 31 of file LORTMImplBase.h.
Member Enumeration Documentation
enum LORTMImplBase::MonitorControlOffset protected
Enumerator
GET_SERIAL_NUMBER
GET_PROTOCOL_REV_LEVEL
AMBSI_NUM_ERRORS
AMBSI_NUM_TRANSACIONS
GET_AMBIENT_TEMPERATURE
GET_SW_REV_LEVEL
RESET_AMBSI
RESET_DEVICE
SYSTEM_MANUAL_MODE_REQUEST
SYSTEM_STANDBY_MODE_REQUEST
SYSTEM_LOAD_ALL_PARAMS
SYSTEM_SAVE_ALL_PARAMS
SYSTEM_CLEAR_ERRORS
SYSTEM_GET_STATUS
SYSTEM_GET_ERROR
SYSTEM_GET_WARNING
SYSTEM_GET_INTERLOCK_STATUS
SYSTEM_STARTUP_MODE
SIGNAL_LASER_BIAS_MON1
SIGNAL_LASER_BIAS_MON2
SIGNAL_LASER_BIAS_MON3
SIGNAL_LASER_BIAS_MON4
SIGNAL_TEMP_INTEG_OUT_MON1
SIGNAL_TEMP_INTEG_OUT_MON2
SIGNAL_TEMP_INTEG_OUT_MON3
SIGNAL_TEMP_INTEG_OUT_MON4
SIGNAL_LASER_TEMP_MON1
SIGNAL_LASER_TEMP_MON2
SIGNAL_LASER_TEMP_MON3
SIGNAL_LASER_TEMP_MON4
SIGNAL_LASER_TEC_I_MON1
SIGNAL_LASER_TEC_I_MON2
SIGNAL_LASER_TEC_I_MON3
SIGNAL_LASER_TEC_I_MON4
SIGNAL_LASER_POW_MON1
SIGNAL_LASER_POW_MON2
SIGNAL_LASER_POW_MON3
SIGNAL_LASER_POW_MON4
SIGNAL_PHMIX_BIAS_MON1
SIGNAL_PHMIX_BIAS_MON2
SIGNAL_PHMIX_BIAS_MON3
SIGNAL_PHMIX_BIAS_MON4
SIGNAL_LASER_SLOW_CORR_MON
SIGNAL_RF_AGC_GAIN_MON
SIGNAL_RF_POW_MON_34DB
SIGNAL_EXTERN_THERM_MON
SIGNAL_INTERN_THERM_MON
SIGNAL_GROUND
LASER_GET_STATUS1
LASER_GET_STATUS2
LASER_GET_STATUS3
LASER_GET_STATUS4
LASER_ICRC_BIAS
LASER_TEMP_SETPOINT
LASER_ISRC_ENABLE
LASER_TEMP_CTRL_ENABLE
LASER_FREQUENCY
LASER_OPERATING_CURRENT
LASER_POWER_CALIB_COEFF
LASER_CALIBRATION_CURRENT
LASER_CALIBRATION_COEFF_A
LASER_CALIBRATION_COEFF_B
LASER_CALIBRATION_COEFF_C
PHASELOCK_TUNING_INIT
PHASELOCK_TUNING_FINALIZE
PHASELOCK_GET_STATUS
PHASELOCK_GET_SELECTED_LASER
PHASELOCK_GET_SELECTED_BAND
LL_OPTSW_CALIBRATION
LL_OPTSW_BANDSEL
LL_OPTSW_SLAVESEL
Definition at line 126 of file LORTMImplBase.h.
Constructor & Destructor Documentation
LORTMImplBase::LORTMImplBase (const std::string & name)
Definition at line 30 of file LORTMImplBase.cpp.
virtual LORTMImplBase::~LORTMImplBase () inline virtual
Definition at line 34 of file LORTMImplBase.h.
References shutdown().
LORTMImplBase::LORTMImplBase (const LORTMImplBase & other) private
Member Function Documentation
float LORTMImplBase::AmbientTemperature () virtual
Definition at line 180 of file LORTMImplBase.cpp.
References AmbientTemperature_status, AmbientTemperature_value, FEHardwareDevice::FEMC_LOG_MONITOR, FEHardwareDevice::FEMC_NO_ERROR, FEHardwareDevice::FEMC_UNPACK_ERROR, GET_AMBIENT_TEMPERATURE, and LOG2_FLOAT.
Referenced by monitorAction().
unsigned long LORTMImplBase::AMBSINumErrors () virtual
Definition at line 140 of file LORTMImplBase.cpp.
References AMBSI_NUM_ERRORS, AMBSINumErrors_value, FEHardwareDevice::FEMC_AMB_ERROR, FEHardwareDevice::FEMC_LOG_MONITOR, FEHardwareDevice::FEMC_NO_ERROR, LOG2_INT, and FEHardwareDevice::unpack().
Referenced by monitorAction().
unsigned long LORTMImplBase::AMBSINumTransactions () virtual
Definition at line 160 of file LORTMImplBase.cpp.
References AMBSI_NUM_TRANSACIONS, AMBSINumTransactions_value, FEHardwareDevice::FEMC_AMB_ERROR, FEHardwareDevice::FEMC_LOG_MONITOR, FEHardwareDevice::FEMC_NO_ERROR, LOG2_INT, and FEHardwareDevice::unpack().
Referenced by monitorAction().
float LORTMImplBase::convertLaserBiasMon (unsigned short adValue) static private
Definition at line 586 of file LORTMImplBase.cpp.
Referenced by LaserBiasMon1(), LaserBiasMon2(), LaserBiasMon3(), and LaserBiasMon4().
float LORTMImplBase::convertLaserPowerMon (unsigned short adValue) static private
Definition at line 613 of file LORTMImplBase.cpp.
Referenced by LaserPowMon1(), LaserPowMon2(), LaserPowMon3(), and LaserPowMon4().
float LORTMImplBase::convertPhmixBiasMon (unsigned short adValue) static private
Definition at line 617 of file LORTMImplBase.cpp.
Referenced by PhMixBiasMon1(), PhMixBiasMon2(), PhMixBiasMon3(), and PhMixBiasMon4().
float LORTMImplBase::convertRFAGCGainMon (unsigned short adValue) static private
Definition at line 625 of file LORTMImplBase.cpp.
Referenced by RFAGCGainMon().
float LORTMImplBase::convertRFPowMon34dB (unsigned short adValue) static private
Definition at line 629 of file LORTMImplBase.cpp.
Referenced by RFPowMon34dB().
float LORTMImplBase::convertSlowCorrMon (unsigned short adValue) static private
Definition at line 621 of file LORTMImplBase.cpp.
Referenced by LaserSlowCorrMon().
float LORTMImplBase::convertTECIMon (unsigned short adValue) static private
Definition at line 609 of file LORTMImplBase.cpp.
Referenced by LaserTecIMon1(), LaserTecIMon2(), LaserTecIMon3(), and LaserTecIMon4().
float LORTMImplBase::convertTemperatureMon (unsigned short adValue) static private
Definition at line 594 of file LORTMImplBase.cpp.
Referenced by ExternThermMon(), InternThermMon(), LaserTempMon1(), LaserTempMon2(), LaserTempMon3(), and LaserTempMon4().
float LORTMImplBase::convertTempIntegMon (unsigned short adValue) static private
Definition at line 590 of file LORTMImplBase.cpp.
Referenced by TempIntegOutMon1(), TempIntegOutMon2(), TempIntegOutMon3(), and TempIntegOutMon4().
float LORTMImplBase::ExternThermMon () virtual
Definition at line 348 of file LORTMImplBase.cpp.
References convertTemperatureMon(), SIGNAL_EXTERN_THERM_MON, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
std::string LORTMImplBase::GetFirmwareVersion () virtual
Definition at line 120 of file LORTMImplBase.cpp.
References FirmwareVersion_value, and GET_SW_REV_LEVEL.
Referenced by LORTMImpl::getFirmwareInfo().
std::string LORTMImplBase::GetProtocolRevision () virtual
Definition at line 100 of file LORTMImplBase.cpp.
References GET_PROTOCOL_REV_LEVEL, and ProtocolRevision_value.
Referenced by LORTMImpl::getFirmwareInfo().
std::string LORTMImplBase::GetSerialNumber () virtual
Definition at line 95 of file LORTMImplBase.cpp.
References GET_SERIAL_NUMBER, SerialNumber_value, and FEHardwareDevice::syncMonitorEightByteESN().
Referenced by LORTMImpl::getFirmwareInfo().
void LORTMImplBase::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Definition at line 87 of file LORTMImplBase.cpp.
References FrontEndLVWrapper::nodeAddress.
Referenced by LORTMImpl::LORTMImpl().
float LORTMImplBase::InternThermMon () virtual
Definition at line 352 of file LORTMImplBase.cpp.
References convertTemperatureMon(), SIGNAL_INTERN_THERM_MON, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserBiasMon1 () virtual
Definition at line 240 of file LORTMImplBase.cpp.
References convertLaserBiasMon(), SIGNAL_LASER_BIAS_MON1, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserBiasMon2 () virtual
Definition at line 244 of file LORTMImplBase.cpp.
References convertLaserBiasMon(), SIGNAL_LASER_BIAS_MON2, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserBiasMon3 () virtual
Definition at line 248 of file LORTMImplBase.cpp.
References convertLaserBiasMon(), SIGNAL_LASER_BIAS_MON3, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserBiasMon4 () virtual
Definition at line 252 of file LORTMImplBase.cpp.
References convertLaserBiasMon(), SIGNAL_LASER_BIAS_MON4, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserCalibCoeffA (int laser, int coeff) virtual
Definition at line 380 of file LORTMImplBase.cpp.
References LASER_CALIBRATION_COEFF_A, and SYNCMON2_LOG_FLOAT.
float LORTMImplBase::LaserCalibCoeffB (int laser, int coeff) virtual
Definition at line 388 of file LORTMImplBase.cpp.
References LASER_CALIBRATION_COEFF_B, and SYNCMON2_LOG_FLOAT.
float LORTMImplBase::LaserCalibCoeffC (int laser, int coeff) virtual
Definition at line 396 of file LORTMImplBase.cpp.
References LASER_CALIBRATION_COEFF_C, and SYNCMON2_LOG_FLOAT.
void LORTMImplBase::LaserCalibrationSelect (int laser) virtual
Definition at line 494 of file LORTMImplBase.cpp.
References LL_OPTSW_CALIBRATION, and SYNCCMD2_LOG_BYTE.
unsigned long LORTMImplBase::LaserFrequency (int laser) virtual
Definition at line 376 of file LORTMImplBase.cpp.
References LASER_FREQUENCY, and SYNCMON2_LOG_INT.
unsigned char LORTMImplBase::LaserGetStatus1 () virtual
Definition at line 356 of file LORTMImplBase.cpp.
References LASER_GET_STATUS1, and SYNCMON2_LOG_INT.
Referenced by monitorAction().
unsigned char LORTMImplBase::LaserGetStatus2 () virtual
Definition at line 360 of file LORTMImplBase.cpp.
References LASER_GET_STATUS2, and SYNCMON2_LOG_INT.
Referenced by monitorAction().
unsigned char LORTMImplBase::LaserGetStatus3 () virtual
Definition at line 364 of file LORTMImplBase.cpp.
References LASER_GET_STATUS3, and SYNCMON2_LOG_INT.
Referenced by monitorAction().
unsigned char LORTMImplBase::LaserGetStatus4 () virtual
Definition at line 368 of file LORTMImplBase.cpp.
References LASER_GET_STATUS4, and SYNCMON2_LOG_INT.
Referenced by monitorAction().
bool LORTMImplBase::LaserISrcEnable (int laser) virtual
Definition at line 372 of file LORTMImplBase.cpp.
References LASER_ISRC_ENABLE, and SYNCMON2_LOG_INT.
Referenced by LORTMImpl::laserEnable().
void LORTMImplBase::LaserISrcEnable (int laser, bool enable) virtual
Definition at line 481 of file LORTMImplBase.cpp.
References LASER_ISRC_ENABLE, and SYNCCMD2_LOG_BYTE.
float LORTMImplBase::LaserPowMon1 () virtual
Definition at line 304 of file LORTMImplBase.cpp.
References convertLaserPowerMon(), SIGNAL_LASER_POW_MON1, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserPowMon2 () virtual
Definition at line 308 of file LORTMImplBase.cpp.
References convertLaserPowerMon(), SIGNAL_LASER_POW_MON2, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserPowMon3 () virtual
Definition at line 312 of file LORTMImplBase.cpp.
References convertLaserPowerMon(), SIGNAL_LASER_POW_MON3, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserPowMon4 () virtual
Definition at line 316 of file LORTMImplBase.cpp.
References convertLaserPowerMon(), SIGNAL_LASER_POW_MON4, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
void LORTMImplBase::LaserSetFrequency (int laser, unsigned long slaveFreqMHz) virtual
Definition at line 488 of file LORTMImplBase.cpp.
References LASER_FREQUENCY, and SYNCCMD2_LOG_INT.
Referenced by LORTMImpl::laserSetFrequency().
float LORTMImplBase::LaserSlowCorrMon () virtual
Definition at line 336 of file LORTMImplBase.cpp.
References convertSlowCorrMon(), SIGNAL_LASER_SLOW_CORR_MON, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserTecIMon1 () virtual
Definition at line 288 of file LORTMImplBase.cpp.
References convertTECIMon(), SIGNAL_LASER_TEC_I_MON1, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserTecIMon2 () virtual
Definition at line 292 of file LORTMImplBase.cpp.
References convertTECIMon(), SIGNAL_LASER_TEC_I_MON2, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserTecIMon3 () virtual
Definition at line 296 of file LORTMImplBase.cpp.
References convertTECIMon(), SIGNAL_LASER_TEC_I_MON3, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserTecIMon4 () virtual
Definition at line 300 of file LORTMImplBase.cpp.
References convertTECIMon(), SIGNAL_LASER_TEC_I_MON4, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserTempMon1 () virtual
Definition at line 272 of file LORTMImplBase.cpp.
References convertTemperatureMon(), SIGNAL_LASER_TEMP_MON1, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserTempMon2 () virtual
Definition at line 276 of file LORTMImplBase.cpp.
References convertTemperatureMon(), SIGNAL_LASER_TEMP_MON2, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserTempMon3 () virtual
Definition at line 280 of file LORTMImplBase.cpp.
References convertTemperatureMon(), SIGNAL_LASER_TEMP_MON1, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::LaserTempMon4 () virtual
Definition at line 284 of file LORTMImplBase.cpp.
References convertTemperatureMon(), SIGNAL_LASER_TEMP_MON1, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
void LORTMImplBase::monitorAction (Time * timestamp_p) protected virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implements FEHardwareDevice.
Definition at line 501 of file LORTMImplBase.cpp.
References AmbientTemperature(), AMBSINumErrors(), AMBSINumTransactions(), ExternThermMon(), ExternThermMon_value, InternThermMon(), InternThermMon_value, LaserBiasMon1(), LaserBiasMon1_value, LaserBiasMon2(), LaserBiasMon2_value, LaserBiasMon3(), LaserBiasMon3_value, LaserBiasMon4(), LaserBiasMon4_value, LaserGetStatus1(), LaserGetStatus1_value, LaserGetStatus2(), LaserGetStatus2_value, LaserGetStatus3(), LaserGetStatus3_value, LaserGetStatus4(), LaserGetStatus4_value, LaserPowMon1(), LaserPowMon1_value, LaserPowMon2(), LaserPowMon2_value, LaserPowMon3(), LaserPowMon3_value, LaserPowMon4(), LaserPowMon4_value, LaserSlowCorrMon(), LaserSlowCorrMon_value, LaserTecIMon1(), LaserTecIMon1_value, LaserTecIMon2(), LaserTecIMon2_value, LaserTecIMon3(), LaserTecIMon3_value, LaserTecIMon4(), LaserTecIMon4_value, LaserTempMon1(), LaserTempMon1_value, LaserTempMon2(), LaserTempMon2_value, LaserTempMon3(), LaserTempMon3_value, LaserTempMon4(), LaserTempMon4_value, lastMonitorTime, lastMonitorTime30s, PhaselockGetSelectedBand(), PhaselockGetSelectedBand_value, PhaselockGetSelectedLaser(), PhaselockGetSelectedLaser_value, PhaselockGetStatus(), phaselockRFInputReady, PhMixBiasMon1(), PhMixBiasMon1_value, PhMixBiasMon2(), PhMixBiasMon2_value, PhMixBiasMon3(), PhMixBiasMon3_value, PhMixBiasMon4(), PhMixBiasMon4_value, RFAGCGainMon(), RFAGCGainMon_value, RFPowMon34dB(), RFPowMon34dB_value, systemError, SystemGetError(), SystemGetError_value, SystemGetStatus(), SystemGetWarning(), SystemGetWarning_value, and systemWarning.
unsigned char LORTMImplBase::PhaselockGetSelectedBand () virtual
Definition at line 433 of file LORTMImplBase.cpp.
References PHASELOCK_GET_SELECTED_BAND, and SYNCMON2_LOG_INT.
Referenced by monitorAction().
unsigned char LORTMImplBase::PhaselockGetSelectedLaser () virtual
Definition at line 429 of file LORTMImplBase.cpp.
References PHASELOCK_GET_SELECTED_LASER, and SYNCMON2_LOG_INT.
Referenced by monitorAction().
unsigned short LORTMImplBase::PhaselockGetStatus () virtual
Definition at line 404 of file LORTMImplBase.cpp.
References FEHardwareDevice::FEMC_LOG_MONITOR, FEHardwareDevice::FEMC_NO_ERROR, FEHardwareDevice::FEMC_UNPACK_ERROR, FEHardwareDevice::getLogger(), FEHardwareDevice::LogInterface::log(), PHASELOCK_GET_STATUS, PhaselockGetStatus_value, phaselockLocked, phaselockRFInputReady, phaselockTuningReady, and FEHardwareDevice::unpack().
Referenced by monitorAction().
void LORTMImplBase::PhaseLockTuningFinalize () virtual
Definition at line 476 of file LORTMImplBase.cpp.
References PHASELOCK_TUNING_FINALIZE, and SYNCCMD2_LOG_BYTE.
void LORTMImplBase::PhaseLockTuningInit (unsigned long slaveFreqMHz) virtual
Definition at line 472 of file LORTMImplBase.cpp.
References PHASELOCK_TUNING_INIT, and SYNCCMD2_LOG_INT.
Referenced by LORTMImpl::PhaseLockTuningInit().
float LORTMImplBase::PhMixBiasMon1 () virtual
Definition at line 320 of file LORTMImplBase.cpp.
References convertPhmixBiasMon(), SIGNAL_PHMIX_BIAS_MON1, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::PhMixBiasMon2 () virtual
Definition at line 324 of file LORTMImplBase.cpp.
References convertPhmixBiasMon(), SIGNAL_PHMIX_BIAS_MON2, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::PhMixBiasMon3 () virtual
Definition at line 328 of file LORTMImplBase.cpp.
References convertPhmixBiasMon(), SIGNAL_PHMIX_BIAS_MON3, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::PhMixBiasMon4 () virtual
Definition at line 332 of file LORTMImplBase.cpp.
References convertPhmixBiasMon(), SIGNAL_PHMIX_BIAS_MON4, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
void LORTMImplBase::ResetAMBSI () virtual
Definition at line 437 of file LORTMImplBase.cpp.
References RESET_AMBSI, and SYNCCMD2_LOG_BYTE.
void LORTMImplBase::ResetDevice () virtual
Definition at line 442 of file LORTMImplBase.cpp.
References RESET_DEVICE, and SYNCCMD2_LOG_BYTE.
float LORTMImplBase::RFAGCGainMon () virtual
Definition at line 340 of file LORTMImplBase.cpp.
References convertRFAGCGainMon(), SIGNAL_RF_AGC_GAIN_MON, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
float LORTMImplBase::RFPowMon34dB () virtual
Definition at line 344 of file LORTMImplBase.cpp.
References convertRFPowMon34dB(), SIGNAL_RF_POW_MON_34DB, and SYNCMON2_LOG_FLOAT_CONV.
Referenced by monitorAction().
void LORTMImplBase::shutdown () virtual
Definition at line 92 of file LORTMImplBase.cpp.
Referenced by ~LORTMImplBase().
void LORTMImplBase::SystemClearErrors () virtual
Reimplemented in LORTMImpl.
Definition at line 467 of file LORTMImplBase.cpp.
References SYNCCMD2_LOG_BYTE, and SYSTEM_CLEAR_ERRORS.
Referenced by LORTMImpl::SystemClearErrors().
short LORTMImplBase::SystemGetError () virtual
Definition at line 232 of file LORTMImplBase.cpp.
References SYNCMON2_LOG_INT, and SYSTEM_GET_ERROR.
Referenced by monitorAction(), and LORTMImpl::SystemGetStatus().
unsigned short LORTMImplBase::SystemGetStatus () virtual
Reimplemented in LORTMImpl.
Definition at line 205 of file LORTMImplBase.cpp.
References FEHardwareDevice::FEMC_LOG_MONITOR, FEHardwareDevice::FEMC_NO_ERROR, FEHardwareDevice::FEMC_UNPACK_ERROR, FEHardwareDevice::getLogger(), FEHardwareDevice::LogInterface::log(), operationPending, SYSTEM_GET_STATUS, systemError, SystemGetInterlockStatus_value, SystemGetStatus_value, systemState, systemWarning, and FEHardwareDevice::unpack().
Referenced by monitorAction(), and LORTMImpl::SystemGetStatus().
short LORTMImplBase::SystemGetWarning () virtual
Definition at line 236 of file LORTMImplBase.cpp.
References SYNCMON2_LOG_INT, and SYSTEM_GET_WARNING.
Referenced by monitorAction().
void LORTMImplBase::SystemLoadAllParameters () virtual
Definition at line 457 of file LORTMImplBase.cpp.
References SYNCCMD2_LOG_BYTE, and SYSTEM_LOAD_ALL_PARAMS.
void LORTMImplBase::SystemManualModeRequest () virtual
Definition at line 447 of file LORTMImplBase.cpp.
References SYNCCMD2_LOG_BYTE, and SYSTEM_MANUAL_MODE_REQUEST.
void LORTMImplBase::SystemSaveAllParameters () virtual
Definition at line 462 of file LORTMImplBase.cpp.
References SYNCCMD2_LOG_BYTE, and SYSTEM_SAVE_ALL_PARAMS.
void LORTMImplBase::SystemStandbyModeRequest () virtual
Definition at line 452 of file LORTMImplBase.cpp.
References SYNCCMD2_LOG_BYTE, and SYSTEM_STANDBY_MODE_REQUEST.
float LORTMImplBase::TempIntegOutMon1 () virtual
Definition at line 256 of file LORTMImplBase.cpp.
References convertTempIntegMon(), SIGNAL_TEMP_INTEG_OUT_MON1, and SYNCMON2_LOG_FLOAT_CONV.
float LORTMImplBase::TempIntegOutMon2 () virtual
Definition at line 260 of file LORTMImplBase.cpp.
References convertTempIntegMon(), SIGNAL_TEMP_INTEG_OUT_MON2, and SYNCMON2_LOG_FLOAT_CONV.
float LORTMImplBase::TempIntegOutMon3 () virtual
Definition at line 264 of file LORTMImplBase.cpp.
References convertTempIntegMon(), SIGNAL_TEMP_INTEG_OUT_MON3, and SYNCMON2_LOG_FLOAT_CONV.
float LORTMImplBase::TempIntegOutMon4 () virtual
Definition at line 268 of file LORTMImplBase.cpp.
References convertTempIntegMon(), SIGNAL_TEMP_INTEG_OUT_MON4, and SYNCMON2_LOG_FLOAT_CONV.
Member Data Documentation
int LORTMImplBase::AmbientTemperature_status protected
Definition at line 217 of file LORTMImplBase.h.
Referenced by AmbientTemperature().
float LORTMImplBase::AmbientTemperature_value
Definition at line 214 of file LORTMImplBase.h.
Referenced by AmbientTemperature().
unsigned long LORTMImplBase::AMBSINumErrors_value protected
Definition at line 210 of file LORTMImplBase.h.
Referenced by AMBSINumErrors(), and LORTMImpl::getAMBSIInfo().
unsigned long LORTMImplBase::AMBSINumTransactions_value protected
Definition at line 211 of file LORTMImplBase.h.
Referenced by AMBSINumTransactions(), and LORTMImpl::getAMBSIInfo().
unsigned long LORTMImplBase::CANStatus_value protected
Definition at line 209 of file LORTMImplBase.h.
float LORTMImplBase::ExternThermMon_value protected
Definition at line 256 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
std::string LORTMImplBase::FirmwareVersion_value protected
Definition at line 208 of file LORTMImplBase.h.
Referenced by GetFirmwareVersion().
float LORTMImplBase::InternThermMon_value protected
Definition at line 257 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::LaserBiasMon1_value protected
Definition at line 229 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
float LORTMImplBase::LaserBiasMon2_value protected
Definition at line 230 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
float LORTMImplBase::LaserBiasMon3_value protected
Definition at line 231 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
float LORTMImplBase::LaserBiasMon4_value protected
Definition at line 232 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
unsigned char LORTMImplBase::LaserGetStatus1_value protected
Definition at line 259 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
unsigned char LORTMImplBase::LaserGetStatus2_value protected
Definition at line 260 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
unsigned char LORTMImplBase::LaserGetStatus3_value protected
Definition at line 261 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
unsigned char LORTMImplBase::LaserGetStatus4_value protected
Definition at line 262 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
float LORTMImplBase::LaserPowMon1_value protected
Definition at line 245 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::LaserPowMon2_value protected
Definition at line 246 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::LaserPowMon3_value protected
Definition at line 247 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::LaserPowMon4_value protected
Definition at line 248 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::LaserSlowCorrMon_value protected
Definition at line 253 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
float LORTMImplBase::LaserTecIMon1_value protected
Definition at line 241 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::LaserTecIMon2_value protected
Definition at line 242 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::LaserTecIMon3_value protected
Definition at line 243 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::LaserTecIMon4_value protected
Definition at line 244 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::LaserTempMon1_value protected
Definition at line 237 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
float LORTMImplBase::LaserTempMon2_value protected
Definition at line 238 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
float LORTMImplBase::LaserTempMon3_value protected
Definition at line 239 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
float LORTMImplBase::LaserTempMon4_value protected
Definition at line 240 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMLasers(), and monitorAction().
Time LORTMImplBase::lastMonitorTime private
Definition at line 276 of file LORTMImplBase.h.
Referenced by monitorAction().
Time LORTMImplBase::lastMonitorTime30s private
Definition at line 277 of file LORTMImplBase.h.
Referenced by monitorAction().
int LORTMImplBase::monitorPhase private
Definition at line 278 of file LORTMImplBase.h.
bool LORTMImplBase::operationPending protected
Definition at line 223 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), and SystemGetStatus().
unsigned char LORTMImplBase::PhaselockGetSelectedBand_value protected
Definition at line 270 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), and monitorAction().
unsigned char LORTMImplBase::PhaselockGetSelectedLaser_value protected
Definition at line 269 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), and monitorAction().
unsigned short LORTMImplBase::PhaselockGetStatus_value protected
Definition at line 264 of file LORTMImplBase.h.
Referenced by PhaselockGetStatus().
bool LORTMImplBase::phaselockLocked protected
Definition at line 265 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), LORTMImpl::getPhaselockStatus(), and PhaselockGetStatus().
bool LORTMImplBase::phaselockRFInputReady protected
Definition at line 267 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), LORTMImpl::getRFInputReady(), monitorAction(), and PhaselockGetStatus().
bool LORTMImplBase::phaselockTuningReady protected
Definition at line 266 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), LORTMImpl::getTuningReady(), and PhaselockGetStatus().
float LORTMImplBase::PhMixBiasMon1_value protected
Definition at line 249 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::PhMixBiasMon2_value protected
Definition at line 250 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::PhMixBiasMon3_value protected
Definition at line 251 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::PhMixBiasMon4_value protected
Definition at line 252 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
std::string LORTMImplBase::ProtocolRevision_value protected
Definition at line 207 of file LORTMImplBase.h.
Referenced by GetProtocolRevision().
float LORTMImplBase::RFAGCGainMon_value protected
Definition at line 254 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
float LORTMImplBase::RFPowMon34dB_value protected
Definition at line 255 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMOther(), and monitorAction().
std::string LORTMImplBase::SerialNumber_value protected
Definition at line 206 of file LORTMImplBase.h.
Referenced by GetSerialNumber().
bool LORTMImplBase::systemError protected
Definition at line 222 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), monitorAction(), LORTMImpl::SystemGetStatus(), and SystemGetStatus().
short LORTMImplBase::SystemGetError_value protected
Definition at line 225 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), and monitorAction().
bool LORTMImplBase::SystemGetInterlockStatus_value protected
Definition at line 227 of file LORTMImplBase.h.
Referenced by LORTMImpl::getInterlockStatus(), LORTMImpl::getMonitorLORTMStatus(), and SystemGetStatus().
unsigned short LORTMImplBase::SystemGetStatus_value protected
Definition at line 219 of file LORTMImplBase.h.
Referenced by SystemGetStatus().
short LORTMImplBase::SystemGetWarning_value protected
Definition at line 226 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), and monitorAction().
unsigned char LORTMImplBase::systemState protected
Definition at line 220 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), LORTMImpl::getSystemState(), LORTMImpl::getTuningReady(), and SystemGetStatus().
bool LORTMImplBase::systemWarning protected
Definition at line 221 of file LORTMImplBase.h.
Referenced by LORTMImpl::getMonitorLORTMStatus(), monitorAction(), and SystemGetStatus().
float LORTMImplBase::TempIntegOutMon1_value protected
Definition at line 233 of file LORTMImplBase.h.
float LORTMImplBase::TempIntegOutMon2_value protected
Definition at line 234 of file LORTMImplBase.h.
float LORTMImplBase::TempIntegOutMon3_value protected
Definition at line 235 of file LORTMImplBase.h.
float LORTMImplBase::TempIntegOutMon4_value protected
Definition at line 236 of file LORTMImplBase.h.
The documentation for this class was generated from the following files:
FEBASE/LORTMImplBase.h
FEBASE/LORTMImplBase.cpp