FrontEndControl2: FEHardwareDevice::LogInterface Class Reference
FEHardwareDevice::LogInterface Class Reference
declare an interface for CAN transaction logging.
#include <FEHardwareDevice.h>
Public Member Functions
LogInterface ()
virtual ~LogInterface ()
virtual void checkPoint (const char *text)
log a checkpoint transaction.
virtual void log (Transaction_t trans, const char *text, AmbRelativeAddr RCA, int FEStatus, unsigned long iValue, float fValue)
Log an actual transaction.
Detailed Description
declare an interface for CAN transaction logging.
Definition at line 113 of file FEHardwareDevice.h.
Constructor & Destructor Documentation
FEHardwareDevice::LogInterface::LogInterface () inline
Definition at line 115 of file FEHardwareDevice.h.
virtual FEHardwareDevice::LogInterface::~LogInterface () inline virtual
Definition at line 117 of file FEHardwareDevice.h.
Member Function Documentation
virtual void FEHardwareDevice::LogInterface::checkPoint (const char * text) inline virtual
log a checkpoint transaction.
Default logger does nothing.
Reimplemented in AmbTransactionLogger.
Definition at line 120 of file FEHardwareDevice.h.
virtual void FEHardwareDevice::LogInterface::log (Transaction_t trans, const char * text, AmbRelativeAddr RCA, int FEStatus, unsigned long iValue, float fValue) inline virtual
Log an actual transaction.
Any of the monitor/control types can be adapted into text, fValue, or iValue. Default logger does nothing.
Reimplemented in AmbTransactionLogger.
Definition at line 125 of file FEHardwareDevice.h.
Referenced by LORTMImplBase::PhaselockGetStatus(), FrontEndImplBase::powerEnableModule(), and LORTMImplBase::SystemGetStatus().
The documentation for this class was generated from the following file:
FEBASE/FEHardwareDevice.h