FrontEndControl2: CartAssembly Class Reference
CartAssembly Class Reference
The class representing a generic cartridge assembly, including cartrioperations for which a CartAssembly is responsible.
#include <CartAssembly.h>
Public Member Functions
CartAssembly (const std::string &name, WCAImpl *WCA, ColdCartImpl *coldCart)
construct with a name and providing WCA and coldCart pointers to use.
~CartAssembly ()
void reset ()
set all state data to defaults, as if just constructed.
bool existsWCA () const
bool existsColdCart () const
const WCAImpl * getWCA () const
const ColdCartImpl * getColdCart () const
WCAImpl * useWCA () const
ColdCartImpl * useColdCart () const
int getBand () const
const std::string & getBandText (std::string &toFill) const
void queryCartridgeState ()
Uses monitor requests to synchronize state variables to the FE hardware state.
void measureSISVoltageError ()
find and store the offset between the set and readback SIS voltage.
void setEnable ()
Power the cartridge assembly on, start monitoring, etc.
void clearEnable ()
Power the cartridge off, stop monitoring, etc.
bool getEnable () const
void setObserving ()
set this cartridge assembly to be the observing band.
void clearObserving ()
set this cartridge assembly to be a non-observing band.
bool getObserving () const
void startMonitor ()
start the monitor threads for the WCA and ColdCart.
void stopMonitor ()
stop the monitor threads for the WCA and ColdCart.
void pauseMonitor (bool pauseWCA, bool pauseCC, const char *reason=NULL)
temporarily pause/unpause monitoring for the WCA and/or ColdCart This can used when some communication-intensive operation is in progress or to prevent monitoring while observing.
void setColdCartConfig (const FEConfig::ColdCartConfig &params)
set all configuration database parameters for the cold cartridge (SIS and LNAs)
void setWCAConfig (const FEConfig::WCAConfig &params)
set all configuration database parameters for the WCA (PLL, AMC, Power Amp, etc.) includes the YIG oscillator limits.
void setYIGLimits (double FLOYIG, double FHIYIG)
set just the YIG oscillator lower and upper limits in GHz.
const FEConfig::ColdCartConfig & getColdCartConfig ()
get the cold cartridge configuration.
const FEConfig::WCAConfig & getWCAConfig ()
get the WCA configuration.
bool setLOFrequency (double freqLO, double freqFLOOG, int sbLock)
Set the YTO tuning according to the given LO reference & floog frequencies, all in GHz.
bool getLOFrequency (double &freqLO, double &freqREF) const
Get the last set LO frequency and the corresponding expected reference frequency.
bool getLOLockSettings (double &freqFLOOG, int &sbLock) const
Get the last set FLOOG frequency and sbLock settting.
bool getMonitorYTO (WCAImpl::YTO_t &target) const
Get the monitor data for the YTO: coarse tuning and equivalent frequency in GHz.
bool lockPLL ()
initiate the lock search process. setLOFrequency must have previously succeeded.
bool adjustPLL (float targetCorrVoltage)
Adjust the YTO to get the correction voltage as close as possible to the given target voltage.
bool adjustYTO (int steps)
Adjust the YTO upward or downward as specified by 'steps'.
bool nullPLLIntegrator (bool enable=false)
Enable/disable the LO_PLL_NULL_LOOP_INTEGRATOR.
bool getNullPLLIntegrator () const
return the state of the LO_PLL_NULL_LOOP_INTEGRATOR
bool setLNABias (int pol=-1, int sb=-1, const float *VD1=NULL, const float *ID1=NULL, const float *VD2=NULL, const float *ID2=NULL, const float *VD3=NULL, const float *ID3=NULL)
Set the LNA bias for a given pol and sb or for all LNAs simultaneously.
bool setEnableLNABias (bool enable=false, int pol=-1, int sb=-1)
Enable or disable the LNA for a given pol and sb or for all LNAs simultaneously.
bool getEnableLNABias () const
Return true if the LNAs are enabled – for updating the GUI.
bool setSISBias (bool enable=false, int pol=-1, int sb=-1, const float *VJ=NULL, int openLoop=-1)
Enable/disable and set the SIS bias for a given pol and sb or for all SIS mixers simultanously.
bool getEnableSISBias () const
Return true if the SIS bias is enabled – for updating the GUI.
bool setSISMagnet (bool enable=false, int pol=-1, int sb=-1, const float *IMag=NULL)
Enable/disable and set the SIS magnet bias for a given pol and sb or for all SIS magnets simultanously.
bool getEnableSISMagnet () const
Return true if the SIS magnet is enabled – for updating the GUI.
bool getSISMagnet (int pol, int sb, float *IMag)
Get the SIS magnet bias current control for a given pol and sb.
bool getSISMagnetNominal (float &IMag01, float &IMag02, float &IMag11, float &IMag12) const
Get the nominal SIS magnet current values from the configuration database for the currently set LO frequency.
bool setLOPowerAmps (bool enable=false, const float *VDP0=NULL, const float *VGP0=NULL, const float *VDP1=NULL, const float *VGP1=NULL)
Enable/disable and set the LO power amps.
bool getLOPowerAmpsEnable () const
Return the enable state of the LO PA.
bool adjustLOPowerAmps (int repeatCount=1)
Adjust the LO PA drain voltages until the junction currents are as close as possible to the the target values given in the configuration database.
bool adjustLOPowerAmpsIsBusy () const
Returns true if the asynchronous process adjustLOPowerAmps() is still running.
bool adjustLOPASinglePol (int pol, float &VD, float targetIJ1, bool verboseLogging)
Adjust the LO PA drain voltage for the specified pol until the SIS1 junction current is close to targetIJ1.
bool optimizeIFPower (bool doPol0, bool doPol1)
Perform optmization of IF power vs.
bool setIFPower (int pol, float powerSB1, float powerSB2)
Inject the current IF power level readings for a single polarization.
bool setVJVD (int pol, float *VJ1, float *VJ2, float *VD)
Set the junction voltages and/or drain voltage for the given polarization.
bool getVJVD (int pol, float *VJ1, float *VJ2, float *VD)
Read the junction control voltages and/or drain voltage for the given polarization.
bool setAMC (const float *VDE=NULL, const float *VGE=NULL)
Set or reset the AMC digital pots.
bool measureFineLOSweep (FrontEndDatabase &dbObject, const FEICDataBase::ID_T &feConfig, FEICDataBase::DATASTATUS_TYPES dataStatus, float tiltAngle, int pol=-1, const float *VJ=NULL, const float *IJ=NULL, const float *fixedVD=NULL, const double *LOStart=NULL, const double *LOStop=NULL, const double *LOStep=NULL, int repeatCount=1)
For the given pol, set both SIS junction voltages to VJ; At each LO frequency from LOStart to LOStop by LOStep: adjust the LO PA drain voltage to get junction current IJ -or- set LO PA drain voltage to fixedVD if specified.
bool measureFineLOSweepSingleSynchronous (int pol, float VJ, float IJ, float fixedVD, float VDNom, double LOStart, double LOStop, double LOStep, XYPlotArray &sisCurrents, XYPlotArray &loPaVoltages)
Measure Fine LO sweep for a single polarization.
bool measureIVCurve (int pol, int sb, const float *VJlow_p=NULL, const float *VJhigh_p=NULL, const float *VJstep_p=NULL, int repeatCount=1)
Take an I-V curve for the given pol, and sb.
bool measureIVCurveSingleSynchronous (int pol, int sb)
Measure the I-V curve once in a synchronous fashion – not on the worker thread.
bool getIVCurveDefaults (int pol, int sb, float *VJlow_p, float *VJhigh_p, float *VJstep_p)
get the default I-V curve range values appropriate for this cartridge band.
bool measureIJvsSISMagnet (int pol, int sbMixer, float IMagStart, float IMagStop, float IMagStep, float VJLow, float VJHigh, float VJStep, int repeatCount=1)
For the given pol, and sbMixer, step the magnet current from IMagStart to IMagStop by IMagStep.
bool measureIFPowerVsVJ (int pol, int sb, const std::string &description, float VJStart, float VJStop, float VJStep, bool doYFactor=false, int repeatCount=1)
For the given pol, measure the IF output powers while stepping the SIS voltages from VJStart to VJStop by VJstep.
bool measureIFPowerVsVD (int pol, const std::string &description, float VDStart, float VDStop, float VDStep, bool doYFactor=false, int repeatCount=1)
For the given pol, measure the IF output powers while stepping the LO PA drain voltage from VDStart to VDStop by VDstep.
bool mixerDeflux (int pol, int sb, int IMagMax)
Perform a mixer defluxing procedure for the given pol and sb.
bool prepareHealtCheck (FrontEndDatabase &dbObject, const FEICDataBase::ID_T &feConfig, FEICDataBase::DATASTATUS_TYPES dataStatus, double &freqLOret, bool receiverIsCold, int warmUpTimeSeconds)
set up the cartridge for performing the health check and wait the specified warmUpTimeSeconds.
bool startHealthCheck ()
complete the health check last set up with prepareHealtCheck. executes on worker thread.
void abortMeasurement ()
Stops all optimization measurements which are in progress.
const XYPlotArray & getXYData () const
Get the lastest measured X-Y data from any of the above optimize/measurement functions.
bool setEnableLNALEDs (bool enable=false)
Enable/disable the LNA LEDs.
bool setEnableSISHeaters (bool enable=false, int pol=-1, float targetTemp=12.0, int timeout=30)
Enable/disable the SIS heaters.
bool setEnablePhotomixer (bool enable=false)
Enable/disable the photomixer.
bool getEnablePhotomixer () const
Return the enabled state of the photomixer.
const std::string & asString (std::string &target) const
format identification and state as a debugging string.
void appendThermalLog (std::string &target) const
append thermal information to a logging string
void appendThermalLogHeader (std::string &target) const
append thermal header information to a logging string
Public Member Functions inherited from ThermalLoggable
ThermalLoggable ()
virtual ~ThermalLoggable ()
Static Public Member Functions
static void setFineLOSweepIniFile (const std::string FineLoSweepIni)
static void appendThermalLogHeaderImpl (std::string &target)
append thermal header information to a logging string
Private Member Functions
void onEnableTasks ()
setup tasks to be done immediately after a cartridge is powered on.
void onDisableTasks ()
shutdown tasks to be done before a cartridge is powered off.
bool searchForLock (int &coarseYIG, int windowSteps, int stepSize)
Perform the LO lock search algorithm. TODO: move to worker thread.
int getCoarseYIG (double &freqYIG, double &freqREF, double freqLO, double freqFLOOG, int sbLock) const
Compute the coarse YIG tuning given freqLO, freqFLOOG, and sbLock.
int YIGFreqToCoarse (double freqYIG) const
Convert freqYIG to the corresponding coarse tuning; uses the lower and upper YIG limits.
double YIGCourseToFreq (int coarseYIG) const
Convert coarseYIG to the actual YIG frequency; uses the lower and upper YIG limits.
bool checkWCA (const char *caller_name) const
debugging helper to check wether WCA_mp is non-NULL.
bool checkColdCart (const char *caller_name) const
debugging helper to check wether coldCart_mp is non-NULL.
Private Attributes
FEConfig::CartAssemblyConfig config_m
The configuration database.
WCAImpl * WCA_mp
WCA sub-object.
ColdCartImpl * coldCart_mp
cold cartridge sub-object.
CartHealthCheck * cartHealthCheck_mp
worker object for cartridge health check
OptimizeLOPowerAmp * optimizerPA_mp
optimizer object for adjustLOPowerAmps()
MeasureFineLOSweep * measureLOSweep_mp
worker object for fine LO sweep measurement
MeasureIVCurve * measureIV_mp
worker object for I-V curve measurement
MeasureSISCurrent * measureSISCurrent_mp
worker object for IJ vs SIS magnet measurement
MeasureIFPower * measureIFPower_mp
worker object for IF Power vs VJ or VD measurement
MaximizeIFPower * optimizerIFPower_mp
optimizer for IF power vs LO drive.
MixerDeflux * mixerDefluxer_mp
worker object for mixer defluxing
MixerHeating * mixerHeater_mp
worker object for mixer heating
XYPlotArray * XYData_mp
X-Y data storage for various measurements.
int band_m
what band this cartridge assembly is. Cached here after querying WCA or ColdCart.
bool enable_m
true if this cartridge is enabled.
bool observing_m
true if this cartridge is observing.
int multAMC_m
cache the warm LO multiplication factor.
int multCold_m
cache the cold LO multiplication factor.
double freqLO_m
the currently set LO frequency.
double freqFLOOG_m
the currently set FLOOG frequency.
double freqREF_m
the expected reference frequency, computed from freqLO, freqFLOOG, multAMC, and sbLock.
bool isTunedLO_m
true if the LO frequency has been successfully set.
Static Private Attributes
static std::string FineLoSweepIni_m = std::string()
path to fine LO sweep ini file.
Detailed Description
The class representing a generic cartridge assembly, including cartrioperations for which a CartAssembly is responsible.
All cartridge operations are implemented here or in the constituent ColdCartImpl or WCAImpl objects. Cartridge behavior which varies from band-to-band is discriminated here.
Definition at line 46 of file CartAssembly.h.
Constructor & Destructor Documentation
CartAssembly::CartAssembly (const std::string & name, WCAImpl * WCA, ColdCartImpl * coldCart)
construct with a name and providing WCA and coldCart pointers to use.
either WCA or coldCart may be NULL but not both.
Definition at line 56 of file CartAssembly.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, coldCart_mp, getBand(), reset(), and WCA_mp.
CartAssembly::~CartAssembly ()
Definition at line 94 of file CartAssembly.cpp.
References cartHealthCheck_mp, measureIV_mp, measureLOSweep_mp, measureSISCurrent_mp, mixerDefluxer_mp, mixerHeater_mp, optimizerIFPower_mp, optimizerPA_mp, and XYData_mp.
Member Function Documentation
void CartAssembly::abortMeasurement ()
Stops all optimization measurements which are in progress.
Definition at line 1657 of file CartAssembly.cpp.
References measureIFPower_mp, measureIV_mp, measureLOSweep_mp, measureSISCurrent_mp, mixerDefluxer_mp, mixerHeater_mp, optimizerIFPower_mp, and optimizerPA_mp.
bool CartAssembly::adjustLOPASinglePol (int pol, float & VD, float targetIJ1, bool verboseLogging)
Adjust the LO PA drain voltage for the specified pol until the SIS1 junction current is close to targetIJ1.
Starting value is given and final value is returned in VD. Adjustment happens on the calling thread.
Definition at line 944 of file CartAssembly.cpp.
References FEMCEventQueue::addStatusMessage(), checkColdCart(), checkWCA(), coldCart_mp, and WCA_mp.
Referenced by measureFineLOSweepSingleSynchronous().
bool CartAssembly::adjustLOPowerAmps (int repeatCount = 1)
Adjust the LO PA drain voltages until the junction currents are as close as possible to the the target values given in the configuration database.
Adjustment happens on a worker thread. Sends the event EVENT_PA_ADJUST_DONE via the client app event queue when finished.
Definition at line 883 of file CartAssembly.cpp.
References checkColdCart(), checkWCA(), FEConfig::CartAssemblyConfig::coldCart_m, coldCart_mp, config_m, freqLO_m, FEConfig::ParamTable::get(), isTunedLO_m, FEConfig::ColdCartConfig::mixerParams_m, optimizerPA_mp, FEConfig::WCAConfig::PAParams_m, FEConfig::CartAssemblyConfig::WCA_m, and WCA_mp.
bool CartAssembly::adjustLOPowerAmpsIsBusy () const
Returns true if the asynchronous process adjustLOPowerAmps() is still running.
Returns false otherwise or if the process has not been called.
Definition at line 933 of file CartAssembly.cpp.
References optimizerPA_mp.
bool CartAssembly::adjustPLL (float targetCorrVoltage)
Adjust the YTO to get the correction voltage as close as possible to the given target voltage.
Definition at line 398 of file CartAssembly.cpp.
References pauseMonitor(), and WCA_mp.
Referenced by lockPLL().
bool CartAssembly::adjustYTO (int steps)
Adjust the YTO upward or downward as specified by 'steps'.
Definition at line 405 of file CartAssembly.cpp.
References WCA_mp.
void CartAssembly::appendThermalLog (std::string & target) const virtual
append thermal information to a logging string
Implements ThermalLoggable.
Definition at line 1775 of file CartAssembly.cpp.
References ColdCartImpl::appendThermalLogPlaceholder(), WCAImpl::appendThermalLogPlaceholder(), band_m, coldCart_mp, getEnable(), and WCA_mp.
void CartAssembly::appendThermalLogHeader (std::string & target) const inline virtual
append thermal header information to a logging string
Implements ThermalLoggable.
Definition at line 463 of file CartAssembly.h.
References appendThermalLogHeaderImpl().
void CartAssembly::appendThermalLogHeaderImpl (std::string & target) static
append thermal header information to a logging string
Definition at line 1769 of file CartAssembly.cpp.
References ColdCartImpl::appendThermalLogHeaderImpl(), and WCAImpl::appendThermalLogHeaderImpl().
Referenced by CartridgesContainer::appendThermalLogHeader(), and appendThermalLogHeader().
const std::string & CartAssembly::asString (std::string & target) const
format identification and state as a debugging string.
Definition at line 1750 of file CartAssembly.cpp.
References band_m, coldCart_mp, enable_m, observing_m, and WCA_mp.
bool CartAssembly::checkColdCart (const char * caller_name) const private
debugging helper to check wether coldCart_mp is non-NULL.
Definition at line 1802 of file CartAssembly.cpp.
References band_m, and coldCart_mp.
Referenced by adjustLOPASinglePol(), adjustLOPowerAmps(), getEnableLNABias(), getEnableSISBias(), getEnableSISMagnet(), measureFineLOSweep(), measureIFPowerVsVD(), measureIFPowerVsVJ(), measureIJvsSISMagnet(), mixerDeflux(), optimizeIFPower(), setColdCartConfig(), setEnableLNABias(), setEnableLNALEDs(), setEnableSISHeaters(), setLNABias(), setSISBias(), and setSISMagnet().
bool CartAssembly::checkWCA (const char * caller_name) const private
debugging helper to check wether WCA_mp is non-NULL.
Definition at line 1793 of file CartAssembly.cpp.
References band_m, and WCA_mp.
Referenced by adjustLOPASinglePol(), adjustLOPowerAmps(), getEnablePhotomixer(), getLOPowerAmpsEnable(), getNullPLLIntegrator(), lockPLL(), measureFineLOSweep(), measureIFPowerVsVD(), measureIFPowerVsVJ(), nullPLLIntegrator(), optimizeIFPower(), setAMC(), setEnablePhotomixer(), setLOFrequency(), setLOPowerAmps(), setWCAConfig(), and setYIGLimits().
void CartAssembly::clearEnable ()
Power the cartridge off, stop monitoring, etc.
Definition at line 200 of file CartAssembly.cpp.
References enable_m, getEnable(), onDisableTasks(), and reset().
void CartAssembly::clearObserving ()
set this cartridge assembly to be a non-observing band.
Has side-effects of setting the YTO to an extreme tuning and disabling the PLL.
Definition at line 238 of file CartAssembly.cpp.
References observing_m.
bool CartAssembly::existsColdCart () const inline
Definition at line 59 of file CartAssembly.h.
References coldCart_mp.
bool CartAssembly::existsWCA () const inline
Definition at line 57 of file CartAssembly.h.
References WCA_mp.
Referenced by getLOLockSettings().
int CartAssembly::getBand () const inline
Definition at line 72 of file CartAssembly.h.
References band_m.
Referenced by CartAssembly(), getSISMagnetNominal(), mixerDeflux(), queryCartridgeState(), setEnableSISHeaters(), and setLOFrequency().
const std::string & CartAssembly::getBandText (std::string & toFill) const
Definition at line 117 of file CartAssembly.cpp.
References band_m.
int CartAssembly::getCoarseYIG (double & freqYIG, double & freqREF, double freqLO, double freqFLOOG, int sbLock) const private
Compute the coarse YIG tuning given freqLO, freqFLOOG, and sbLock.
uses the lower and upper YIG limits and multAMC. returns the resulting YIG frequency and expected reference frequency as freqYIG and freqREF.
< the frequency at the WCA LO output ports.
< the required frequency at the WCA reference input port.
< the target YTO frequency.
Definition at line 416 of file CartAssembly.cpp.
References band_m, multAMC_m, multCold_m, and YIGFreqToCoarse().
Referenced by lockPLL(), and setLOFrequency().
const ColdCartImpl* CartAssembly::getColdCart () const inline
Definition at line 64 of file CartAssembly.h.
References coldCart_mp.
const FEConfig::ColdCartConfig& CartAssembly::getColdCartConfig () inline
get the cold cartridge configuration.
Definition at line 127 of file CartAssembly.h.
References FEConfig::CartAssemblyConfig::coldCart_m, and config_m.
bool CartAssembly::getEnable () const inline
Definition at line 90 of file CartAssembly.h.
References enable_m.
Referenced by appendThermalLog(), clearEnable(), queryCartridgeState(), setEnable(), and setObserving().
bool CartAssembly::getEnableLNABias () const
Return true if the LNAs are enabled – for updating the GUI.
Definition at line 647 of file CartAssembly.cpp.
References checkColdCart(), and coldCart_mp.
bool CartAssembly::getEnablePhotomixer () const
Return the enabled state of the photomixer.
Definition at line 1742 of file CartAssembly.cpp.
References checkWCA(), and WCA_mp.
bool CartAssembly::getEnableSISBias () const
Return true if the SIS bias is enabled – for updating the GUI.
Definition at line 734 of file CartAssembly.cpp.
References checkColdCart(), and coldCart_mp.
bool CartAssembly::getEnableSISMagnet () const
Return true if the SIS magnet is enabled – for updating the GUI.
Definition at line 795 of file CartAssembly.cpp.
References checkColdCart(), and coldCart_mp.
bool CartAssembly::getIVCurveDefaults (int pol, int sb, float * VJlow_p, float * VJhigh_p, float * VJstep_p)
get the default I-V curve range values appropriate for this cartridge band.
Definition at line 1501 of file CartAssembly.cpp.
References band_m, FEConfig::CartAssemblyConfig::coldCart_m, config_m, freqLO_m, FEConfig::ParamTable::get(), and FEConfig::ColdCartConfig::mixerParams_m.
Referenced by measureIVCurve(), and measureIVCurveSingleSynchronous().
bool CartAssembly::getLOFrequency (double & freqLO, double & freqREF) const inline
Get the last set LO frequency and the corresponding expected reference frequency.
Definition at line 142 of file CartAssembly.h.
References freqLO_m, and freqREF_m.
bool CartAssembly::getLOLockSettings (double & freqFLOOG, int & sbLock) const inline
Get the last set FLOOG frequency and sbLock settting.
Definition at line 148 of file CartAssembly.h.
References existsWCA(), freqFLOOG_m, and WCA_mp.
Referenced by measureFineLOSweepSingleSynchronous().
bool CartAssembly::getLOPowerAmpsEnable () const
Return the enable state of the LO PA.
Definition at line 877 of file CartAssembly.cpp.
References checkWCA(), and WCA_mp.
bool CartAssembly::getMonitorYTO (WCAImpl::YTO_t & target) const
Get the monitor data for the YTO: coarse tuning and equivalent frequency in GHz.
Definition at line 342 of file CartAssembly.cpp.
References WCAImpl::YTO_t::reset(), WCA_mp, YIGCourseToFreq(), WCAImpl::YTO_t::ytoCoarseTune_value, and WCAImpl::YTO_t::ytoFrequency_value.
bool CartAssembly::getNullPLLIntegrator () const
return the state of the LO_PLL_NULL_LOOP_INTEGRATOR
Definition at line 459 of file CartAssembly.cpp.
References checkWCA(), and WCA_mp.
bool CartAssembly::getObserving () const inline
Definition at line 101 of file CartAssembly.h.
References observing_m.
bool CartAssembly::getSISMagnet (int pol, int sb, float * IMag)
Get the SIS magnet bias current control for a given pol and sb.
Definition at line 801 of file CartAssembly.cpp.
References coldCart_mp.
bool CartAssembly::getSISMagnetNominal (float & IMag01, float & IMag02, float & IMag11, float & IMag12) const
Get the nominal SIS magnet current values from the configuration database for the currently set LO frequency.
Definition at line 817 of file CartAssembly.cpp.
References FEConfig::CartAssemblyConfig::coldCart_m, coldCart_mp, config_m, freqLO_m, FEConfig::ParamTable::get(), getBand(), and FEConfig::ColdCartConfig::magnetParams_m.
Referenced by setSISMagnet().
bool CartAssembly::getVJVD (int pol, float * VJ1, float * VJ2, float * VD)
Read the junction control voltages and/or drain voltage for the given polarization.
The existing control values are returend as VJ1, VJ2, and VD.
Definition at line 1227 of file CartAssembly.cpp.
References coldCart_mp, and WCA_mp.
const WCAImpl* CartAssembly::getWCA () const inline
Definition at line 62 of file CartAssembly.h.
References WCA_mp.
const FEConfig::WCAConfig& CartAssembly::getWCAConfig () inline
get the WCA configuration.
Definition at line 131 of file CartAssembly.h.
References config_m, and FEConfig::CartAssemblyConfig::WCA_m.
const XYPlotArray& CartAssembly::getXYData () const inline
Get the lastest measured X-Y data from any of the above optimize/measurement functions.
Definition at line 378 of file CartAssembly.h.
References XYData_mp.
bool CartAssembly::lockPLL ()
initiate the lock search process. setLOFrequency must have previously succeeded.
Definition at line 351 of file CartAssembly.cpp.
References adjustPLL(), checkWCA(), config_m, FEConfig::WCAConfig::FHIYIG_m, FEConfig::WCAConfig::FLOYIG_m, freqFLOOG_m, freqLO_m, getCoarseYIG(), pauseMonitor(), searchForLock(), FEConfig::CartAssemblyConfig::WCA_m, and WCA_mp.
bool CartAssembly::measureFineLOSweep (FrontEndDatabase & dbObject, const FEICDataBase::ID_T & feConfig, FEICDataBase::DATASTATUS_TYPES dataStatus, float tiltAngle, int pol = -1, const float * VJ = NULL, const float * IJ = NULL, const float * fixedVD = NULL, const double * LOStart = NULL, const double * LOStop = NULL, const double * LOStep = NULL, int repeatCount = 1)
For the given pol, set both SIS junction voltages to VJ; At each LO frequency from LOStart to LOStop by LOStep: adjust the LO PA drain voltage to get junction current IJ -or- set LO PA drain voltage to fixedVD if specified.
repeatCount gives the number of times to measure. Measurement happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent when finished. pol may be -1, indicating both pols are to be measured. If fixedVD is not NULL then use that VD setting and ignore IJ. If either of VJ or IJ are NULL then the settings from FineLOSweep.ini are used. If any of LOStart, LOStop, or LOStep are NULL, then the settings from FineLOSweep.ini are used.
Definition at line 1253 of file CartAssembly.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, checkColdCart(), checkWCA(), coldCart_mp, FineLoSweepIni_m, measureLOSweep_mp, WCA_mp, and XYData_mp.
bool CartAssembly::measureFineLOSweepSingleSynchronous (int pol, float VJ, float IJ, float fixedVD, float VDNom, double LOStart, double LOStop, double LOStep, XYPlotArray & sisCurrents, XYPlotArray & loPaVoltages)
Measure Fine LO sweep for a single polarization.
Place results in the given XYPlotArray objects. runs on the calling thread.
Definition at line 1354 of file CartAssembly.cpp.
References FEMCEventQueue::addProgressEvent(), FEMCEventQueue::addStatusMessage(), adjustLOPASinglePol(), coldCart_mp, getLOLockSettings(), measureLOSweep_mp, nullPLLIntegrator(), setLOFrequency(), ColdCartImpl::setSISVoltage(), and WCA_mp.
bool CartAssembly::measureIFPowerVsVD (int pol, const std::string & description, float VDStart, float VDStop, float VDStep, bool doYFactor = false, int repeatCount = 1)
For the given pol, measure the IF output powers while stepping the LO PA drain voltage from VDStart to VDStop by VDstep.
repeatCount gives the number of times to measure. Measurement happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent when finished.
Definition at line 1597 of file CartAssembly.cpp.
References checkColdCart(), checkWCA(), coldCart_mp, measureIFPower_mp, WCA_mp, and XYData_mp.
bool CartAssembly::measureIFPowerVsVJ (int pol, int sb, const std::string & description, float VJStart, float VJStop, float VJStep, bool doYFactor = false, int repeatCount = 1)
For the given pol, measure the IF output powers while stepping the SIS voltages from VJStart to VJStop by VJstep.
If sb is -1, step both junctions. Otherwise step one junction and leave the other set as it was. repeatCount gives the number of times to measure. Measurement happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent when finished.
Definition at line 1578 of file CartAssembly.cpp.
References checkColdCart(), checkWCA(), coldCart_mp, measureIFPower_mp, WCA_mp, and XYData_mp.
bool CartAssembly::measureIJvsSISMagnet (int pol, int sbMixer, float IMagStart, float IMagStop, float IMagStep, float VJLow, float VJHigh, float VJStep, int repeatCount = 1)
For the given pol, and sbMixer, step the magnet current from IMagStart to IMagStop by IMagStep.
At each step, sweep the mixer voltage from VJLow to VJHigh by VJStep, if VJMin==VJMax, record the mixer junction current at each magnet step. else, record half the difference between the max and min junction current seen. If sbMixer is -1, measure both mixers while stepping both magnets (or band-specific special cases.) repeatCount gives the number of times to measure. Measurement happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent when finished.
Definition at line 1560 of file CartAssembly.cpp.
References checkColdCart(), coldCart_mp, measureSISCurrent_mp, and XYData_mp.
bool CartAssembly::measureIVCurve (int pol, int sb, const float * VJlow_p = NULL, const float * VJhigh_p = NULL, const float * VJstep_p = NULL, int repeatCount = 1)
Take an I-V curve for the given pol, and sb.
If VJlow, VJhigh, or VJstep is NULL it will be computed from the nominal VJ. Measurement happens on a worker thread. Sends the event EVENT_IVCURVE_DONE via the client app event queue when finished.
Definition at line 1458 of file CartAssembly.cpp.
References coldCart_mp, getIVCurveDefaults(), measureIV_mp, and XYData_mp.
Referenced by measureIVCurveSingleSynchronous().
bool CartAssembly::measureIVCurveSingleSynchronous (int pol, int sb)
Measure the I-V curve once in a synchronous fashion – not on the worker thread.
Uses default stepping for the band. Sends the event EVENT_IVCURVE_DONE via the client app event queue when finished.
Definition at line 1487 of file CartAssembly.cpp.
References FEMCEventQueue::addEvent(), band_m, coldCart_mp, FEMCEventQueue::EVENT_IVCURVE_DONE, getIVCurveDefaults(), measureIVCurve(), and XYData_mp.
void CartAssembly::measureSISVoltageError ()
find and store the offset between the set and readback SIS voltage.
Definition at line 144 of file CartAssembly.cpp.
References band_m, coldCart_mp, pauseMonitor(), and setSISMagnet().
bool CartAssembly::mixerDeflux (int pol, int sb, int IMagMax)
Perform a mixer defluxing procedure for the given pol and sb.
pol may be 0 or 1. pol=-1 indicates defluxing both polarizations. sb may be 1 or 2. sb=-1 indicates defluxing both mixers. IMagMax gives the starting value for the coil demagnetization process. Defluxing happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent when finished.
Definition at line 1616 of file CartAssembly.cpp.
References checkColdCart(), coldCart_mp, getBand(), mixerDefluxer_mp, setEnableSISHeaters(), and XYData_mp.
bool CartAssembly::nullPLLIntegrator (bool enable = false)
Enable/disable the LO_PLL_NULL_LOOP_INTEGRATOR.
when true, the PLL is defeated and the YTO correction voltage set to zero. when false, the PLL operates.
Definition at line 451 of file CartAssembly.cpp.
References checkWCA(), and WCA_mp.
Referenced by measureFineLOSweepSingleSynchronous(), and setLOFrequency().
void CartAssembly::onDisableTasks () private
shutdown tasks to be done before a cartridge is powered off.
Definition at line 216 of file CartAssembly.cpp.
References coldCart_mp, stopMonitor(), and WCA_mp.
Referenced by clearEnable().
void CartAssembly::onEnableTasks () private
setup tasks to be done immediately after a cartridge is powered on.
Definition at line 208 of file CartAssembly.cpp.
References coldCart_mp, startMonitor(), and WCA_mp.
Referenced by setEnable().
bool CartAssembly::optimizeIFPower (bool doPol0, bool doPol1)
Perform optmization of IF power vs.
LO drive and junction voltage. works in conjunction with setIFPower() which injects ongoing power readings. Optimization happens on a worker thread. Sends the event EVENT_REQUEST_IFPOWER via the client app event queue power readings are required. Sends the event EVENT_PA_ADJUST_DONE whene finished.
Definition at line 1107 of file CartAssembly.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, checkColdCart(), checkWCA(), FEConfig::CartAssemblyConfig::coldCart_m, coldCart_mp, config_m, freqLO_m, FEConfig::ParamTable::get(), isTunedLO_m, FEConfig::ColdCartConfig::mixerParams_m, observing_m, optimizerIFPower_mp, FEConfig::WCAConfig::PAParams_m, FEConfig::CartAssemblyConfig::WCA_m, and WCA_mp.
void CartAssembly::pauseMonitor (bool pauseWCA, bool pauseCC, const char * reason = NULL)
temporarily pause/unpause monitoring for the WCA and/or ColdCart This can used when some communication-intensive operation is in progress or to prevent monitoring while observing.
Optional reason string will be logged.
Definition at line 256 of file CartAssembly.cpp.
References coldCart_mp, and WCA_mp.
Referenced by adjustPLL(), lockPLL(), and measureSISVoltageError().
bool CartAssembly::prepareHealtCheck (FrontEndDatabase & dbObject, const FEICDataBase::ID_T & feConfig, FEICDataBase::DATASTATUS_TYPES dataStatus, double & freqLOret, bool receiverIsCold, int warmUpTimeSeconds)
set up the cartridge for performing the health check and wait the specified warmUpTimeSeconds.
executes on calling thread. dbObject is the database connection object to use feConfig and dataStatus give info for how to record data to the database. returns the cartridge LO frequency in ref freqLOret. receiverIsCold controls which measurements are performed. warmUpTimeSeconds specifies how long to wait before starting to take data.
Definition at line 1640 of file CartAssembly.cpp.
References cartHealthCheck_mp, and XYData_mp.
void CartAssembly::queryCartridgeState ()
Uses monitor requests to synchronize state variables to the FE hardware state.
Definition at line 123 of file CartAssembly.cpp.
References band_m, coldCart_mp, freqLO_m, freqREF_m, getBand(), getEnable(), WCAImpl::getMultiplier(), ColdCartImpl::getMultiplier(), isTunedLO_m, multAMC_m, multCold_m, WCA_mp, and YIGCourseToFreq().
void CartAssembly::reset ()
set all state data to defaults, as if just constructed.
Definition at line 106 of file CartAssembly.cpp.
References coldCart_mp, enable_m, freqFLOOG_m, freqLO_m, freqREF_m, isTunedLO_m, multAMC_m, multCold_m, observing_m, and WCA_mp.
Referenced by CartAssembly(), clearEnable(), and setEnable().
bool CartAssembly::searchForLock (int & coarseYIG, int windowSteps, int stepSize) private
Perform the LO lock search algorithm. TODO: move to worker thread.
Referenced by lockPLL().
bool CartAssembly::setAMC (const float * VDE = NULL, const float * VGE = NULL)
Set or reset the AMC digital pots.
If both VDE and VGE are NULL then both are set to nominal (1.0, -0.1). If VDE is not NULL then its value is set otherwise no change. If VGE is not NULL then its value is set otherwise no change. Note: these control points do not work for most cartridges. They are used for the band 3 signal source.
Definition at line 1243 of file CartAssembly.cpp.
References checkWCA(), and WCA_mp.
void CartAssembly::setColdCartConfig (const FEConfig::ColdCartConfig & params)
set all configuration database parameters for the cold cartridge (SIS and LNAs)
Definition at line 263 of file CartAssembly.cpp.
References FEConfig::ColdCartConfig::band_m, FEConfig::CartAssemblyID::band_m, checkColdCart(), FEConfig::CartAssemblyConfig::coldCart_m, config_m, and FEConfig::CartAssemblyConfig::Id_m.
void CartAssembly::setEnable ()
Power the cartridge assembly on, start monitoring, etc.
Definition at line 192 of file CartAssembly.cpp.
References enable_m, getEnable(), onEnableTasks(), and reset().
bool CartAssembly::setEnableLNABias (bool enable = false, int pol = -1, int sb = -1)
Enable or disable the LNA for a given pol and sb or for all LNAs simultaneously.
If either pol or sb is -1, all LNAs are simultaneously affected.
Definition at line 636 of file CartAssembly.cpp.
References checkColdCart(), and coldCart_mp.
bool CartAssembly::setEnableLNALEDs (bool enable = false)
Enable/disable the LNA LEDs.
Definition at line 1676 of file CartAssembly.cpp.
References checkColdCart(), and coldCart_mp.
bool CartAssembly::setEnablePhotomixer (bool enable = false)
Enable/disable the photomixer.
Definition at line 1731 of file CartAssembly.cpp.
References checkWCA(), and WCA_mp.
bool CartAssembly::setEnableSISHeaters (bool enable = false, int pol = -1, float targetTemp = 12.0, int timeout = 30)
Enable/disable the SIS heaters.
If enable, start the mixer heating process. If pol == -1, heat both polarizations. Else pol must be 0 or 1. If targetTemp >= 4, retrigger the the heater for up to timeout seconds to attain the target temperature. Else, retrigger the heater for exactly timeout seconds. For band 9, timeout may be no longer than 2 seconds. For bands 678, timeout may be up to 2 minutes.
Definition at line 1693 of file CartAssembly.cpp.
References FEMCEventQueue::addStatusMessage(), checkColdCart(), coldCart_mp, getBand(), and mixerHeater_mp.
Referenced by mixerDeflux().
static void CartAssembly::setFineLOSweepIniFile (const std::string FineLoSweepIni) inline static
Definition at line 278 of file CartAssembly.h.
References FrontEndLVWrapper::FineLoSweepIni(), and FineLoSweepIni_m.
Referenced by FrontEndImpl::setFineLOSweepIniFile().
bool CartAssembly::setIFPower (int pol, float powerSB1, float powerSB2)
Inject the current IF power level readings for a single polarization.
Used for optimizing mixer and LO power amp bias voltages.
Definition at line 1173 of file CartAssembly.cpp.
References measureIFPower_mp, and optimizerIFPower_mp.
bool CartAssembly::setLNABias (int pol = -1, int sb = -1, const float * VD1 = NULL, const float * ID1 = NULL, const float * VD2 = NULL, const float * ID2 = NULL, const float * VD3 = NULL, const float * ID3 = NULL)
Set the LNA bias for a given pol and sb or for all LNAs simultaneously.
If any of the float values given is NULL the corresponding setting is used from the configuration database. If either pol or sb is -1, then all float values are ignored and the values from the config database are used for all LNAs in the cartridge.
Definition at line 465 of file CartAssembly.cpp.
References checkColdCart(), FEConfig::CartAssemblyConfig::coldCart_m, coldCart_mp, config_m, freqLO_m, FEConfig::ParamTable::get(), and FEConfig::ColdCartConfig::usePreampParams().
bool CartAssembly::setLOFrequency (double freqLO, double freqFLOOG, int sbLock)
Set the YTO tuning according to the given LO reference & floog frequencies, all in GHz.
sbLock = 0 means lock below the reference: freqREF = freqLO + freqFLOOG; sbLock = 1 means lock above the reference: freqREF = freqLO - freqFLOOG.
Definition at line 288 of file CartAssembly.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, checkWCA(), coldCart_mp, config_m, FEConfig::WCAConfig::FHIYIG_m, FEConfig::WCAConfig::FLOYIG_m, freqFLOOG_m, freqLO_m, freqREF_m, WCAImpl::getAltLoopBW(), getBand(), getCoarseYIG(), WCAImpl::getMultiplier(), ColdCartImpl::getMultiplier(), isTunedLO_m, multAMC_m, multCold_m, nullPLLIntegrator(), FEConfig::CartAssemblyConfig::WCA_m, and WCA_mp.
Referenced by measureFineLOSweepSingleSynchronous().
bool CartAssembly::setLOPowerAmps (bool enable = false, const float * VDP0 = NULL, const float * VGP0 = NULL, const float * VDP1 = NULL, const float * VGP1 = NULL)
Enable/disable and set the LO power amps.
If any of the float values given is NULL no change is made to the corresponding control point. If all the float values are NULL all settings are made according to the configuration database.
Definition at line 834 of file CartAssembly.cpp.
References checkWCA(), config_m, freqLO_m, FEConfig::ParamTable::get(), FEConfig::WCAConfig::PAParams_m, FEConfig::CartAssemblyConfig::WCA_m, and WCA_mp.
void CartAssembly::setObserving ()
set this cartridge assembly to be the observing band.
Has side-effects of setting the YTO to its last observing value and enabling the PLL.
Definition at line 232 of file CartAssembly.cpp.
References getEnable(), and observing_m.
bool CartAssembly::setSISBias (bool enable = false, int pol = -1, int sb = -1, const float * VJ = NULL, int openLoop = -1)
Enable/disable and set the SIS bias for a given pol and sb or for all SIS mixers simultanously.
If VJ is NULL the setting from the configuration database is used. If openLoop is -1, no change is made to the SIS openLoop state. If either pol or sb is -1, then all junctions are biased according to the database.
Definition at line 653 of file CartAssembly.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, checkColdCart(), FEConfig::CartAssemblyConfig::coldCart_m, coldCart_mp, config_m, freqLO_m, FEConfig::ParamTable::get(), and FEConfig::ColdCartConfig::mixerParams_m.
bool CartAssembly::setSISMagnet (bool enable = false, int pol = -1, int sb = -1, const float * IMag = NULL)
Enable/disable and set the SIS magnet bias for a given pol and sb or for all SIS magnets simultanously.
If IMag is NULL the setting from the configuration database is used. If either pol or sb is -1, then all magnets are biased according to the database.
Definition at line 740 of file CartAssembly.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, checkColdCart(), coldCart_mp, and getSISMagnetNominal().
Referenced by measureSISVoltageError().
bool CartAssembly::setVJVD (int pol, float * VJ1, float * VJ2, float * VD)
Set the junction voltages and/or drain voltage for the given polarization.
If any of VJ1, VJ2, or VD is NULL, no change is made to the corresponding control point.
Definition at line 1184 of file CartAssembly.cpp.
References coldCart_mp, and WCA_mp.
void CartAssembly::setWCAConfig (const FEConfig::WCAConfig & params)
set all configuration database parameters for the WCA (PLL, AMC, Power Amp, etc.) includes the YIG oscillator limits.
Definition at line 271 of file CartAssembly.cpp.
References FEConfig::WCAConfig::band_m, FEConfig::CartAssemblyID::band_m, checkWCA(), config_m, FEConfig::CartAssemblyConfig::Id_m, and FEConfig::CartAssemblyConfig::WCA_m.
void CartAssembly::setYIGLimits (double FLOYIG, double FHIYIG)
set just the YIG oscillator lower and upper limits in GHz.
Definition at line 279 of file CartAssembly.cpp.
References band_m, checkWCA(), config_m, FEConfig::WCAConfig::FHIYIG_m, FEConfig::WCAConfig::FLOYIG_m, and FEConfig::CartAssemblyConfig::WCA_m.
bool CartAssembly::startHealthCheck ()
complete the health check last set up with prepareHealtCheck. executes on worker thread.
Definition at line 1650 of file CartAssembly.cpp.
References cartHealthCheck_mp.
void CartAssembly::startMonitor ()
start the monitor threads for the WCA and ColdCart.
Definition at line 242 of file CartAssembly.cpp.
References coldCart_mp, and WCA_mp.
Referenced by onEnableTasks().
void CartAssembly::stopMonitor ()
stop the monitor threads for the WCA and ColdCart.
Definition at line 249 of file CartAssembly.cpp.
References coldCart_mp, and WCA_mp.
Referenced by onDisableTasks().
ColdCartImpl* CartAssembly::useColdCart () const inline
Definition at line 69 of file CartAssembly.h.
References coldCart_mp.
WCAImpl* CartAssembly::useWCA () const inline
Definition at line 67 of file CartAssembly.h.
References WCA_mp.
double CartAssembly::YIGCourseToFreq (int coarseYIG) const private
Convert coarseYIG to the actual YIG frequency; uses the lower and upper YIG limits.
Definition at line 445 of file CartAssembly.cpp.
References config_m, FEConfig::WCAConfig::FHIYIG_m, FEConfig::WCAConfig::FLOYIG_m, and FEConfig::CartAssemblyConfig::WCA_m.
Referenced by getMonitorYTO(), and queryCartridgeState().
int CartAssembly::YIGFreqToCoarse (double freqYIG) const private
Convert freqYIG to the corresponding coarse tuning; uses the lower and upper YIG limits.
Definition at line 436 of file CartAssembly.cpp.
References config_m, FEConfig::WCAConfig::FHIYIG_m, FEConfig::WCAConfig::FLOYIG_m, and FEConfig::CartAssemblyConfig::WCA_m.
Referenced by getCoarseYIG().
Member Data Documentation
int CartAssembly::band_m private
what band this cartridge assembly is. Cached here after querying WCA or ColdCart.
Definition at line 442 of file CartAssembly.h.
Referenced by appendThermalLog(), asString(), CartAssembly(), checkColdCart(), checkWCA(), getBand(), getBandText(), getCoarseYIG(), getIVCurveDefaults(), measureFineLOSweep(), measureIVCurveSingleSynchronous(), measureSISVoltageError(), optimizeIFPower(), queryCartridgeState(), setLOFrequency(), setSISBias(), setSISMagnet(), and setYIGLimits().
CartHealthCheck* CartAssembly::cartHealthCheck_mp private
worker object for cartridge health check
Definition at line 431 of file CartAssembly.h.
Referenced by prepareHealtCheck(), startHealthCheck(), and ~CartAssembly().
ColdCartImpl* CartAssembly::coldCart_mp private
cold cartridge sub-object.
Definition at line 429 of file CartAssembly.h.
Referenced by adjustLOPASinglePol(), adjustLOPowerAmps(), appendThermalLog(), asString(), CartAssembly(), checkColdCart(), existsColdCart(), getColdCart(), getEnableLNABias(), getEnableSISBias(), getEnableSISMagnet(), getSISMagnet(), getSISMagnetNominal(), getVJVD(), measureFineLOSweep(), measureFineLOSweepSingleSynchronous(), measureIFPowerVsVD(), measureIFPowerVsVJ(), measureIJvsSISMagnet(), measureIVCurve(), measureIVCurveSingleSynchronous(), measureSISVoltageError(), mixerDeflux(), onDisableTasks(), onEnableTasks(), optimizeIFPower(), pauseMonitor(), queryCartridgeState(), reset(), setEnableLNABias(), setEnableLNALEDs(), setEnableSISHeaters(), setLNABias(), setLOFrequency(), setSISBias(), setSISMagnet(), setVJVD(), startMonitor(), stopMonitor(), and useColdCart().
FEConfig::CartAssemblyConfig CartAssembly::config_m private
The configuration database.
Definition at line 426 of file CartAssembly.h.
Referenced by adjustLOPowerAmps(), getColdCartConfig(), getIVCurveDefaults(), getSISMagnetNominal(), getWCAConfig(), lockPLL(), optimizeIFPower(), setColdCartConfig(), setLNABias(), setLOFrequency(), setLOPowerAmps(), setSISBias(), setWCAConfig(), setYIGLimits(), YIGCourseToFreq(), and YIGFreqToCoarse().
bool CartAssembly::enable_m private
true if this cartridge is enabled.
Definition at line 443 of file CartAssembly.h.
Referenced by asString(), clearEnable(), getEnable(), reset(), and setEnable().
std::string CartAssembly::FineLoSweepIni_m = std::string() static private
path to fine LO sweep ini file.
Definition at line 454 of file CartAssembly.h.
Referenced by measureFineLOSweep(), and setFineLOSweepIniFile().
double CartAssembly::freqFLOOG_m private
the currently set FLOOG frequency.
Definition at line 450 of file CartAssembly.h.
Referenced by getLOLockSettings(), lockPLL(), reset(), and setLOFrequency().
double CartAssembly::freqLO_m private
the currently set LO frequency.
Definition at line 449 of file CartAssembly.h.
Referenced by adjustLOPowerAmps(), getIVCurveDefaults(), getLOFrequency(), getSISMagnetNominal(), lockPLL(), optimizeIFPower(), queryCartridgeState(), reset(), setLNABias(), setLOFrequency(), setLOPowerAmps(), and setSISBias().
double CartAssembly::freqREF_m private
the expected reference frequency, computed from freqLO, freqFLOOG, multAMC, and sbLock.
Definition at line 451 of file CartAssembly.h.
Referenced by getLOFrequency(), queryCartridgeState(), reset(), and setLOFrequency().
bool CartAssembly::isTunedLO_m private
true if the LO frequency has been successfully set.
Definition at line 452 of file CartAssembly.h.
Referenced by adjustLOPowerAmps(), optimizeIFPower(), queryCartridgeState(), reset(), and setLOFrequency().
MeasureIFPower* CartAssembly::measureIFPower_mp private
worker object for IF Power vs VJ or VD measurement
Definition at line 436 of file CartAssembly.h.
Referenced by abortMeasurement(), measureIFPowerVsVD(), measureIFPowerVsVJ(), and setIFPower().
MeasureIVCurve* CartAssembly::measureIV_mp mutable private
worker object for I-V curve measurement
Definition at line 434 of file CartAssembly.h.
Referenced by abortMeasurement(), measureIVCurve(), and ~CartAssembly().
MeasureFineLOSweep* CartAssembly::measureLOSweep_mp private
worker object for fine LO sweep measurement
Definition at line 433 of file CartAssembly.h.
Referenced by abortMeasurement(), measureFineLOSweep(), measureFineLOSweepSingleSynchronous(), and ~CartAssembly().
MeasureSISCurrent* CartAssembly::measureSISCurrent_mp mutable private
worker object for IJ vs SIS magnet measurement
Definition at line 435 of file CartAssembly.h.
Referenced by abortMeasurement(), measureIJvsSISMagnet(), and ~CartAssembly().
MixerDeflux* CartAssembly::mixerDefluxer_mp private
worker object for mixer defluxing
Definition at line 438 of file CartAssembly.h.
Referenced by abortMeasurement(), mixerDeflux(), and ~CartAssembly().
MixerHeating* CartAssembly::mixerHeater_mp private
worker object for mixer heating
Definition at line 439 of file CartAssembly.h.
Referenced by abortMeasurement(), setEnableSISHeaters(), and ~CartAssembly().
int CartAssembly::multAMC_m private
cache the warm LO multiplication factor.
Definition at line 446 of file CartAssembly.h.
Referenced by getCoarseYIG(), queryCartridgeState(), reset(), and setLOFrequency().
int CartAssembly::multCold_m private
cache the cold LO multiplication factor.
Definition at line 447 of file CartAssembly.h.
Referenced by getCoarseYIG(), queryCartridgeState(), reset(), and setLOFrequency().
bool CartAssembly::observing_m private
true if this cartridge is observing.
Definition at line 444 of file CartAssembly.h.
Referenced by asString(), clearObserving(), getObserving(), optimizeIFPower(), reset(), and setObserving().
MaximizeIFPower* CartAssembly::optimizerIFPower_mp private
optimizer for IF power vs LO drive.
Definition at line 437 of file CartAssembly.h.
Referenced by abortMeasurement(), optimizeIFPower(), setIFPower(), and ~CartAssembly().
OptimizeLOPowerAmp* CartAssembly::optimizerPA_mp private
optimizer object for adjustLOPowerAmps()
Definition at line 432 of file CartAssembly.h.
Referenced by abortMeasurement(), adjustLOPowerAmps(), adjustLOPowerAmpsIsBusy(), and ~CartAssembly().
WCAImpl* CartAssembly::WCA_mp private
WCA sub-object.
Definition at line 428 of file CartAssembly.h.
Referenced by adjustLOPASinglePol(), adjustLOPowerAmps(), adjustPLL(), adjustYTO(), appendThermalLog(), asString(), CartAssembly(), checkWCA(), existsWCA(), getEnablePhotomixer(), getLOLockSettings(), getLOPowerAmpsEnable(), getMonitorYTO(), getNullPLLIntegrator(), getVJVD(), getWCA(), lockPLL(), measureFineLOSweep(), measureFineLOSweepSingleSynchronous(), measureIFPowerVsVD(), measureIFPowerVsVJ(), nullPLLIntegrator(), onDisableTasks(), onEnableTasks(), optimizeIFPower(), pauseMonitor(), queryCartridgeState(), reset(), setAMC(), setEnablePhotomixer(), setLOFrequency(), setLOPowerAmps(), setVJVD(), startMonitor(), stopMonitor(), and useWCA().
XYPlotArray* CartAssembly::XYData_mp private
X-Y data storage for various measurements.
Definition at line 440 of file CartAssembly.h.
Referenced by getXYData(), measureFineLOSweep(), measureIFPowerVsVD(), measureIFPowerVsVJ(), measureIJvsSISMagnet(), measureIVCurve(), measureIVCurveSingleSynchronous(), mixerDeflux(), prepareHealtCheck(), and ~CartAssembly().
The documentation for this class was generated from the following files:
CartAssembly.h
CartAssembly.cpp