FrontEndControl2: ColdCartImplBase Class Reference
ColdCartImplBase Class Reference
#include <ColdCartImplBase.h>
Public Member Functions
ColdCartImplBase (const std::string &name, int port)
virtual ~ColdCartImplBase ()
int getPort () const
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual float sisPol0Sb1Voltage ()
virtual float sisPol0Sb2Voltage ()
virtual float sisPol1Sb1Voltage ()
virtual float sisPol1Sb2Voltage ()
virtual float sisPol0Sb1Current ()
virtual float sisPol0Sb2Current ()
virtual float sisPol1Sb1Current ()
virtual float sisPol1Sb2Current ()
virtual float avgSisPol0Sb1Current (int average=8)
virtual float avgSisPol0Sb2Current (int average=8)
virtual float avgSisPol1Sb1Current (int average=8)
virtual float avgSisPol1Sb2Current (int average=8)
virtual bool sisPol0Sb1OpenLoop ()
virtual bool sisPol0Sb2OpenLoop ()
virtual bool sisPol1Sb1OpenLoop ()
virtual bool sisPol1Sb2OpenLoop ()
virtual float sisMagnetPol0Sb1Voltage ()
virtual float sisMagnetPol0Sb1Current ()
virtual float sisMagnetPol0Sb2Voltage ()
virtual float sisMagnetPol0Sb2Current ()
virtual float sisMagnetPol1Sb1Voltage ()
virtual float sisMagnetPol1Sb1Current ()
virtual float sisMagnetPol1Sb2Voltage ()
virtual float sisMagnetPol1Sb2Current ()
virtual bool lnaPol0Sb1Enable ()
virtual float lnaPol0Sb1St1DrainVoltage ()
virtual float lnaPol0Sb1St1DrainCurrent ()
virtual float lnaPol0Sb1St1GateVoltage ()
virtual float lnaPol0Sb1St2DrainVoltage ()
virtual float lnaPol0Sb1St2DrainCurrent ()
virtual float lnaPol0Sb1St2GateVoltage ()
virtual float lnaPol0Sb1St3DrainVoltage ()
virtual float lnaPol0Sb1St3DrainCurrent ()
virtual float lnaPol0Sb1St3GateVoltage ()
virtual bool lnaPol0Sb2Enable ()
virtual float lnaPol0Sb2St1DrainVoltage ()
virtual float lnaPol0Sb2St1DrainCurrent ()
virtual float lnaPol0Sb2St1GateVoltage ()
virtual float lnaPol0Sb2St2DrainVoltage ()
virtual float lnaPol0Sb2St2DrainCurrent ()
virtual float lnaPol0Sb2St2GateVoltage ()
virtual float lnaPol0Sb2St3DrainVoltage ()
virtual float lnaPol0Sb2St3DrainCurrent ()
virtual float lnaPol0Sb2St3GateVoltage ()
virtual bool lnaPol1Sb1Enable ()
virtual float lnaPol1Sb1St1DrainVoltage ()
virtual float lnaPol1Sb1St1DrainCurrent ()
virtual float lnaPol1Sb1St1GateVoltage ()
virtual float lnaPol1Sb1St2DrainVoltage ()
virtual float lnaPol1Sb1St2DrainCurrent ()
virtual float lnaPol1Sb1St2GateVoltage ()
virtual float lnaPol1Sb1St3DrainVoltage ()
virtual float lnaPol1Sb1St3DrainCurrent ()
virtual float lnaPol1Sb1St3GateVoltage ()
virtual bool lnaPol1Sb2Enable ()
virtual float lnaPol1Sb2St1DrainVoltage ()
virtual float lnaPol1Sb2St1DrainCurrent ()
virtual float lnaPol1Sb2St1GateVoltage ()
virtual float lnaPol1Sb2St2DrainVoltage ()
virtual float lnaPol1Sb2St2DrainCurrent ()
virtual float lnaPol1Sb2St2GateVoltage ()
virtual float lnaPol1Sb2St3DrainVoltage ()
virtual float lnaPol1Sb2St3DrainCurrent ()
virtual float lnaPol1Sb2St3GateVoltage ()
virtual bool lnaLedPol0Enable ()
virtual bool lnaLedPol1Enable ()
virtual float sisHeaterPol0Current ()
virtual float sisHeaterPol1Current ()
virtual float cartridgeTemperature0 ()
virtual float cartridgeTemperature1 ()
virtual float cartridgeTemperature2 ()
virtual float cartridgeTemperature3 ()
virtual float cartridgeTemperature4 ()
virtual float cartridgeTemperature5 ()
virtual void sisPol0Sb1Voltage (float val)
virtual void sisPol0Sb1OpenLoop (bool val)
virtual void sisPol0Sb2Voltage (float val)
virtual void sisPol0Sb2OpenLoop (bool val)
virtual void sisPol1Sb1Voltage (float val)
virtual void sisPol1Sb1OpenLoop (bool val)
virtual void sisPol1Sb2Voltage (float val)
virtual void sisPol1Sb2OpenLoop (bool val)
virtual void sisMagnetPol0Sb1Current (float val)
virtual void sisMagnetPol0Sb2Current (float val)
virtual void sisMagnetPol1Sb1Current (float val)
virtual void sisMagnetPol1Sb2Current (float val)
virtual void lnaPol0Sb1Enable (bool val)
virtual void lnaPol0Sb1St1DrainVoltage (float val)
virtual void lnaPol0Sb1St1DrainCurrent (float val)
virtual void lnaPol0Sb1St2DrainVoltage (float val)
virtual void lnaPol0Sb1St2DrainCurrent (float val)
virtual void lnaPol0Sb1St3DrainVoltage (float val)
virtual void lnaPol0Sb1St3DrainCurrent (float val)
virtual void lnaPol0Sb2Enable (bool val)
virtual void lnaPol0Sb2St1DrainVoltage (float val)
virtual void lnaPol0Sb2St1DrainCurrent (float val)
virtual void lnaPol0Sb2St2DrainVoltage (float val)
virtual void lnaPol0Sb2St2DrainCurrent (float val)
virtual void lnaPol0Sb2St3DrainVoltage (float val)
virtual void lnaPol0Sb2St3DrainCurrent (float val)
virtual void lnaPol1Sb1Enable (bool val)
virtual void lnaPol1Sb1St1DrainVoltage (float val)
virtual void lnaPol1Sb1St1DrainCurrent (float val)
virtual void lnaPol1Sb1St2DrainVoltage (float val)
virtual void lnaPol1Sb1St2DrainCurrent (float val)
virtual void lnaPol1Sb1St3DrainVoltage (float val)
virtual void lnaPol1Sb1St3DrainCurrent (float val)
virtual void lnaPol1Sb2Enable (bool val)
virtual void lnaPol1Sb2St1DrainVoltage (float val)
virtual void lnaPol1Sb2St1DrainCurrent (float val)
virtual void lnaPol1Sb2St2DrainVoltage (float val)
virtual void lnaPol1Sb2St2DrainCurrent (float val)
virtual void lnaPol1Sb2St3DrainVoltage (float val)
virtual void lnaPol1Sb2St3DrainCurrent (float val)
virtual void lnaLedPol0Enable (bool val)
virtual void lnaLedPol1Enable (bool val)
virtual void sisHeaterPol0Enable (bool val)
virtual void sisHeaterPol1Enable (bool val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Protected Types
enum MonitorControlOffset {
CARTRIDGE_TEMP = 0x0880, SIS_VOLTAGE = 0x0008, SIS_CURRENT = 0x0010, SIS_OPEN_LOOP = 0x0018,
SIS_MAGNET_VOLTAGE = 0x0020, SIS_MAGNET_CURRENT = 0x0030, LNA_ENABLE = 0x0058, LNA1_DRAIN_VOLTAGE = 0x0040,
LNA1_DRAIN_CURRENT = 0x0041, LNA1_GATE_VOLTAGE = 0x0042, LNA2_DRAIN_VOLTAGE = 0x0044, LNA2_DRAIN_CURRENT = 0x0045,
LNA2_GATE_VOLTAGE = 0x0046, LNA3_DRAIN_VOLTAGE = 0x0048, LNA3_DRAIN_CURRENT = 0x0049, LNA3_GATE_VOLTAGE = 0x004A,
LNA4_DRAIN_VOLTAGE = 0x004C, LNA4_DRAIN_CURRENT = 0x004D, LNA4_GATE_VOLTAGE = 0x004E, LNA5_DRAIN_VOLTAGE = 0x0050,
LNA5_DRAIN_CURRENT = 0x0051, LNA5_GATE_VOLTAGE = 0x0052, LNA6_DRAIN_VOLTAGE = 0x0054, LNA6_DRAIN_CURRENT = 0x0055,
LNA6_GATE_VOLTAGE = 0x0056, LNA_LED_ENABLE = 0x0100, SIS_HEATER_ENABLE = 0x0180, SIS_HEATER_CURRENT = 0x01C0
}
Protected Member Functions
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Protected Attributes
float sisPol0Sb1Voltage_value
float sisPol0Sb1Current_value
bool sisPol0Sb1OpenLoop_value
float sisPol0Sb2Voltage_value
float sisPol0Sb2Current_value
bool sisPol0Sb2OpenLoop_value
float sisPol1Sb1Voltage_value
float sisPol1Sb1Current_value
bool sisPol1Sb1OpenLoop_value
float sisPol1Sb2Voltage_value
float sisPol1Sb2Current_value
bool sisPol1Sb2OpenLoop_value
float sisMagnetPol0Sb1Voltage_value
float sisMagnetPol0Sb1Current_value
float sisMagnetPol0Sb2Voltage_value
float sisMagnetPol0Sb2Current_value
float sisMagnetPol1Sb1Voltage_value
float sisMagnetPol1Sb1Current_value
float sisMagnetPol1Sb2Voltage_value
float sisMagnetPol1Sb2Current_value
bool lnaPol0Sb1Enable_value
float lnaPol0Sb1St1DrainVoltage_value
float lnaPol0Sb1St1DrainCurrent_value
float lnaPol0Sb1St1GateVoltage_value
float lnaPol0Sb1St2DrainVoltage_value
float lnaPol0Sb1St2DrainCurrent_value
float lnaPol0Sb1St2GateVoltage_value
float lnaPol0Sb1St3DrainVoltage_value
float lnaPol0Sb1St3DrainCurrent_value
float lnaPol0Sb1St3GateVoltage_value
bool lnaPol0Sb2Enable_value
float lnaPol0Sb2St1DrainVoltage_value
float lnaPol0Sb2St1DrainCurrent_value
float lnaPol0Sb2St1GateVoltage_value
float lnaPol0Sb2St2DrainVoltage_value
float lnaPol0Sb2St2DrainCurrent_value
float lnaPol0Sb2St2GateVoltage_value
float lnaPol0Sb2St3DrainVoltage_value
float lnaPol0Sb2St3DrainCurrent_value
float lnaPol0Sb2St3GateVoltage_value
bool lnaPol1Sb1Enable_value
float lnaPol1Sb1St1DrainVoltage_value
float lnaPol1Sb1St1DrainCurrent_value
float lnaPol1Sb1St1GateVoltage_value
float lnaPol1Sb1St2DrainVoltage_value
float lnaPol1Sb1St2DrainCurrent_value
float lnaPol1Sb1St2GateVoltage_value
float lnaPol1Sb1St3DrainVoltage_value
float lnaPol1Sb1St3DrainCurrent_value
float lnaPol1Sb1St3GateVoltage_value
bool lnaPol1Sb2Enable_value
float lnaPol1Sb2St1DrainVoltage_value
float lnaPol1Sb2St1DrainCurrent_value
float lnaPol1Sb2St1GateVoltage_value
float lnaPol1Sb2St2DrainVoltage_value
float lnaPol1Sb2St2DrainCurrent_value
float lnaPol1Sb2St2GateVoltage_value
float lnaPol1Sb2St3DrainVoltage_value
float lnaPol1Sb2St3DrainCurrent_value
float lnaPol1Sb2St3GateVoltage_value
bool lnaLedPol0Enable_value
bool lnaLedPol1Enable_value
float sisHeaterPol0Current_value
float sisHeaterPol1Current_value
float cartridgeTemperature0_value
float cartridgeTemperature1_value
float cartridgeTemperature2_value
float cartridgeTemperature3_value
float cartridgeTemperature4_value
float cartridgeTemperature5_value
int sisPol0Sb1Voltage_status
int sisPol0Sb1Current_status
int sisPol0Sb1OpenLoop_status
int sisPol0Sb2Voltage_status
int sisPol0Sb2Current_status
int sisPol0Sb2OpenLoop_status
int sisPol1Sb1Voltage_status
int sisPol1Sb1Current_status
int sisPol1Sb1OpenLoop_status
int sisPol1Sb2Voltage_status
int sisPol1Sb2Current_status
int sisPol1Sb2OpenLoop_status
int sisMagnetPol0Sb1Voltage_status
int sisMagnetPol0Sb1Current_status
int sisMagnetPol0Sb2Voltage_status
int sisMagnetPol0Sb2Current_status
int sisMagnetPol1Sb1Voltage_status
int sisMagnetPol1Sb1Current_status
int sisMagnetPol1Sb2Voltage_status
int sisMagnetPol1Sb2Current_status
int lnaPol0Sb1Enable_status
int lnaPol0Sb1St1DrainVoltage_status
int lnaPol0Sb1St1DrainCurrent_status
int lnaPol0Sb1St1GateVoltage_status
int lnaPol0Sb1St2DrainVoltage_status
int lnaPol0Sb1St2DrainCurrent_status
int lnaPol0Sb1St2GateVoltage_status
int lnaPol0Sb1St3DrainVoltage_status
int lnaPol0Sb1St3DrainCurrent_status
int lnaPol0Sb1St3GateVoltage_status
int lnaPol0Sb2Enable_status
int lnaPol0Sb2St1DrainVoltage_status
int lnaPol0Sb2St1DrainCurrent_status
int lnaPol0Sb2St1GateVoltage_status
int lnaPol0Sb2St2DrainVoltage_status
int lnaPol0Sb2St2DrainCurrent_status
int lnaPol0Sb2St2GateVoltage_status
int lnaPol0Sb2St3DrainVoltage_status
int lnaPol0Sb2St3DrainCurrent_status
int lnaPol0Sb2St3GateVoltage_status
int lnaPol1Sb1Enable_status
int lnaPol1Sb1St1DrainVoltage_status
int lnaPol1Sb1St1DrainCurrent_status
int lnaPol1Sb1St1GateVoltage_status
int lnaPol1Sb1St2DrainVoltage_status
int lnaPol1Sb1St2DrainCurrent_status
int lnaPol1Sb1St2GateVoltage_status
int lnaPol1Sb1St3DrainVoltage_status
int lnaPol1Sb1St3DrainCurrent_status
int lnaPol1Sb1St3GateVoltage_status
int lnaPol1Sb2Enable_status
int lnaPol1Sb2St1DrainVoltage_status
int lnaPol1Sb2St1DrainCurrent_status
int lnaPol1Sb2St1GateVoltage_status
int lnaPol1Sb2St2DrainVoltage_status
int lnaPol1Sb2St2DrainCurrent_status
int lnaPol1Sb2St2GateVoltage_status
int lnaPol1Sb2St3DrainVoltage_status
int lnaPol1Sb2St3DrainCurrent_status
int lnaPol1Sb2St3GateVoltage_status
int lnaLedPol0Enable_status
int lnaLedPol1Enable_status
int sisHeaterPol0Current_status
int sisHeaterPol1Current_status
int sisHeaterPol0Enable_status
int sisHeaterPol1Enable_status
int cartridgeTemperature0_status
int cartridgeTemperature1_status
int cartridgeTemperature2_status
int cartridgeTemperature3_status
int cartridgeTemperature4_status
int cartridgeTemperature5_status
AmbRelativeAddr baseRCA
AmbRelativeAddr sisPol0Sb1Voltage_RCA
AmbRelativeAddr sisPol0Sb1Current_RCA
AmbRelativeAddr sisPol0Sb1OpenLoop_RCA
AmbRelativeAddr sisPol0Sb2Voltage_RCA
AmbRelativeAddr sisPol0Sb2Current_RCA
AmbRelativeAddr sisPol0Sb2OpenLoop_RCA
AmbRelativeAddr sisPol1Sb1Voltage_RCA
AmbRelativeAddr sisPol1Sb1Current_RCA
AmbRelativeAddr sisPol1Sb1OpenLoop_RCA
AmbRelativeAddr sisPol1Sb2Voltage_RCA
AmbRelativeAddr sisPol1Sb2Current_RCA
AmbRelativeAddr sisPol1Sb2OpenLoop_RCA
AmbRelativeAddr sisMagnetPol0Sb1Voltage_RCA
AmbRelativeAddr sisMagnetPol0Sb1Current_RCA
AmbRelativeAddr sisMagnetPol0Sb2Voltage_RCA
AmbRelativeAddr sisMagnetPol0Sb2Current_RCA
AmbRelativeAddr sisMagnetPol1Sb1Voltage_RCA
AmbRelativeAddr sisMagnetPol1Sb1Current_RCA
AmbRelativeAddr sisMagnetPol1Sb2Voltage_RCA
AmbRelativeAddr sisMagnetPol1Sb2Current_RCA
AmbRelativeAddr lnaPol0Sb1Enable_RCA
AmbRelativeAddr lnaPol0Sb1St1DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St1DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb1St1GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St2DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St2DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb1St2GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St3DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St3DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb1St3GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb2Enable_RCA
AmbRelativeAddr lnaPol0Sb2St1DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St1DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb2St1GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St2DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St2DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb2St2GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St3DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St3DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb2St3GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb1Enable_RCA
AmbRelativeAddr lnaPol1Sb1St1DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St1DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb1St1GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St2DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St2DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb1St2GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St3DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St3DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb1St3GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb2Enable_RCA
AmbRelativeAddr lnaPol1Sb2St1DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St1DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb2St1GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St2DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St2DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb2St2GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St3DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St3DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb2St3GateVoltage_RCA
AmbRelativeAddr lnaLedPol0Enable_RCA
AmbRelativeAddr lnaLedPol1Enable_RCA
AmbRelativeAddr sisHeaterPol0Enable_RCA
AmbRelativeAddr sisHeaterPol0Current_RCA
AmbRelativeAddr sisHeaterPol1Enable_RCA
AmbRelativeAddr sisHeaterPol1Current_RCA
AmbRelativeAddr cartridgeTemperature0_RCA
AmbRelativeAddr cartridgeTemperature1_RCA
AmbRelativeAddr cartridgeTemperature2_RCA
AmbRelativeAddr cartridgeTemperature3_RCA
AmbRelativeAddr cartridgeTemperature4_RCA
AmbRelativeAddr cartridgeTemperature5_RCA
int port_m
to which FEMC port is this module connected.
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
ColdCartImplBase (const ColdCartImplBase &other)
void logMon (bool printHeader=false) const
Private Attributes
Time lastMonitorTime
int monitorPhase
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 33 of file ColdCartImplBase.h.
Member Enumeration Documentation
enum ColdCartImplBase::MonitorControlOffset protected
Enumerator
CARTRIDGE_TEMP
SIS_VOLTAGE
SIS_CURRENT
SIS_OPEN_LOOP
SIS_MAGNET_VOLTAGE
SIS_MAGNET_CURRENT
LNA_ENABLE
LNA1_DRAIN_VOLTAGE
LNA1_DRAIN_CURRENT
LNA1_GATE_VOLTAGE
LNA2_DRAIN_VOLTAGE
LNA2_DRAIN_CURRENT
LNA2_GATE_VOLTAGE
LNA3_DRAIN_VOLTAGE
LNA3_DRAIN_CURRENT
LNA3_GATE_VOLTAGE
LNA4_DRAIN_VOLTAGE
LNA4_DRAIN_CURRENT
LNA4_GATE_VOLTAGE
LNA5_DRAIN_VOLTAGE
LNA5_DRAIN_CURRENT
LNA5_GATE_VOLTAGE
LNA6_DRAIN_VOLTAGE
LNA6_DRAIN_CURRENT
LNA6_GATE_VOLTAGE
LNA_LED_ENABLE
SIS_HEATER_ENABLE
SIS_HEATER_CURRENT
Definition at line 182 of file ColdCartImplBase.h.
Constructor & Destructor Documentation
ColdCartImplBase::ColdCartImplBase (const std::string & name, int port)
Definition at line 31 of file ColdCartImplBase.cpp.
References baseRCA, CARTRIDGE_TEMP, cartridgeTemperature0(), cartridgeTemperature0_RCA, cartridgeTemperature0_value, cartridgeTemperature1(), cartridgeTemperature1_RCA, cartridgeTemperature1_value, cartridgeTemperature2(), cartridgeTemperature2_RCA, cartridgeTemperature2_value, cartridgeTemperature3(), cartridgeTemperature3_RCA, cartridgeTemperature3_value, cartridgeTemperature4(), cartridgeTemperature4_RCA, cartridgeTemperature4_value, cartridgeTemperature5(), cartridgeTemperature5_RCA, cartridgeTemperature5_value, LNA1_DRAIN_CURRENT, LNA1_DRAIN_VOLTAGE, LNA1_GATE_VOLTAGE, LNA2_DRAIN_CURRENT, LNA2_DRAIN_VOLTAGE, LNA2_GATE_VOLTAGE, LNA3_DRAIN_CURRENT, LNA3_DRAIN_VOLTAGE, LNA3_GATE_VOLTAGE, LNA_ENABLE, LNA_LED_ENABLE, lnaLedPol0Enable_RCA, lnaLedPol1Enable_RCA, lnaPol0Sb1Enable_RCA, lnaPol0Sb1St1DrainCurrent(), lnaPol0Sb1St1DrainCurrent_RCA, lnaPol0Sb1St1DrainCurrent_value, lnaPol0Sb1St1DrainVoltage(), lnaPol0Sb1St1DrainVoltage_RCA, lnaPol0Sb1St1DrainVoltage_value, lnaPol0Sb1St1GateVoltage(), lnaPol0Sb1St1GateVoltage_RCA, lnaPol0Sb1St1GateVoltage_value, lnaPol0Sb1St2DrainCurrent(), lnaPol0Sb1St2DrainCurrent_RCA, lnaPol0Sb1St2DrainCurrent_value, lnaPol0Sb1St2DrainVoltage(), lnaPol0Sb1St2DrainVoltage_RCA, lnaPol0Sb1St2DrainVoltage_value, lnaPol0Sb1St2GateVoltage(), lnaPol0Sb1St2GateVoltage_RCA, lnaPol0Sb1St2GateVoltage_value, lnaPol0Sb1St3DrainCurrent(), lnaPol0Sb1St3DrainCurrent_RCA, lnaPol0Sb1St3DrainCurrent_value, lnaPol0Sb1St3DrainVoltage(), lnaPol0Sb1St3DrainVoltage_RCA, lnaPol0Sb1St3DrainVoltage_value, lnaPol0Sb1St3GateVoltage(), lnaPol0Sb1St3GateVoltage_RCA, lnaPol0Sb1St3GateVoltage_value, lnaPol0Sb2Enable_RCA, lnaPol0Sb2St1DrainCurrent(), lnaPol0Sb2St1DrainCurrent_RCA, lnaPol0Sb2St1DrainCurrent_value, lnaPol0Sb2St1DrainVoltage(), lnaPol0Sb2St1DrainVoltage_RCA, lnaPol0Sb2St1DrainVoltage_value, lnaPol0Sb2St1GateVoltage(), lnaPol0Sb2St1GateVoltage_RCA, lnaPol0Sb2St1GateVoltage_value, lnaPol0Sb2St2DrainCurrent(), lnaPol0Sb2St2DrainCurrent_RCA, lnaPol0Sb2St2DrainCurrent_value, lnaPol0Sb2St2DrainVoltage(), lnaPol0Sb2St2DrainVoltage_RCA, lnaPol0Sb2St2DrainVoltage_value, lnaPol0Sb2St2GateVoltage(), lnaPol0Sb2St2GateVoltage_RCA, lnaPol0Sb2St2GateVoltage_value, lnaPol0Sb2St3DrainCurrent(), lnaPol0Sb2St3DrainCurrent_RCA, lnaPol0Sb2St3DrainCurrent_value, lnaPol0Sb2St3DrainVoltage(), lnaPol0Sb2St3DrainVoltage_RCA, lnaPol0Sb2St3DrainVoltage_value, lnaPol0Sb2St3GateVoltage(), lnaPol0Sb2St3GateVoltage_RCA, lnaPol0Sb2St3GateVoltage_value, lnaPol1Sb1Enable_RCA, lnaPol1Sb1St1DrainCurrent(), lnaPol1Sb1St1DrainCurrent_RCA, lnaPol1Sb1St1DrainCurrent_value, lnaPol1Sb1St1DrainVoltage(), lnaPol1Sb1St1DrainVoltage_RCA, lnaPol1Sb1St1DrainVoltage_value, lnaPol1Sb1St1GateVoltage(), lnaPol1Sb1St1GateVoltage_RCA, lnaPol1Sb1St1GateVoltage_value, lnaPol1Sb1St2DrainCurrent(), lnaPol1Sb1St2DrainCurrent_RCA, lnaPol1Sb1St2DrainCurrent_value, lnaPol1Sb1St2DrainVoltage(), lnaPol1Sb1St2DrainVoltage_RCA, lnaPol1Sb1St2DrainVoltage_value, lnaPol1Sb1St2GateVoltage(), lnaPol1Sb1St2GateVoltage_RCA, lnaPol1Sb1St2GateVoltage_value, lnaPol1Sb1St3DrainCurrent(), lnaPol1Sb1St3DrainCurrent_RCA, lnaPol1Sb1St3DrainCurrent_value, lnaPol1Sb1St3DrainVoltage(), lnaPol1Sb1St3DrainVoltage_RCA, lnaPol1Sb1St3DrainVoltage_value, lnaPol1Sb1St3GateVoltage(), lnaPol1Sb1St3GateVoltage_RCA, lnaPol1Sb1St3GateVoltage_value, lnaPol1Sb2Enable_RCA, lnaPol1Sb2St1DrainCurrent(), lnaPol1Sb2St1DrainCurrent_RCA, lnaPol1Sb2St1DrainCurrent_value, lnaPol1Sb2St1DrainVoltage(), lnaPol1Sb2St1DrainVoltage_RCA, lnaPol1Sb2St1DrainVoltage_value, lnaPol1Sb2St1GateVoltage(), lnaPol1Sb2St1GateVoltage_RCA, lnaPol1Sb2St1GateVoltage_value, lnaPol1Sb2St2DrainCurrent(), lnaPol1Sb2St2DrainCurrent_RCA, lnaPol1Sb2St2DrainCurrent_value, lnaPol1Sb2St2DrainVoltage(), lnaPol1Sb2St2DrainVoltage_RCA, lnaPol1Sb2St2DrainVoltage_value, lnaPol1Sb2St2GateVoltage(), lnaPol1Sb2St2GateVoltage_RCA, lnaPol1Sb2St2GateVoltage_value, lnaPol1Sb2St3DrainCurrent(), lnaPol1Sb2St3DrainCurrent_RCA, lnaPol1Sb2St3DrainCurrent_value, lnaPol1Sb2St3DrainVoltage(), lnaPol1Sb2St3DrainVoltage_RCA, lnaPol1Sb2St3DrainVoltage_value, lnaPol1Sb2St3GateVoltage(), lnaPol1Sb2St3GateVoltage_RCA, lnaPol1Sb2St3GateVoltage_value, SIS_CURRENT, SIS_HEATER_CURRENT, SIS_HEATER_ENABLE, SIS_MAGNET_CURRENT, SIS_MAGNET_VOLTAGE, SIS_OPEN_LOOP, SIS_VOLTAGE, sisHeaterPol0Current(), sisHeaterPol0Current_RCA, sisHeaterPol0Current_value, sisHeaterPol0Enable_RCA, sisHeaterPol1Current(), sisHeaterPol1Current_RCA, sisHeaterPol1Current_value, sisHeaterPol1Enable_RCA, sisMagnetPol0Sb1Current(), sisMagnetPol0Sb1Current_RCA, sisMagnetPol0Sb1Current_value, sisMagnetPol0Sb1Voltage(), sisMagnetPol0Sb1Voltage_RCA, sisMagnetPol0Sb1Voltage_value, sisMagnetPol0Sb2Current(), sisMagnetPol0Sb2Current_RCA, sisMagnetPol0Sb2Current_value, sisMagnetPol0Sb2Voltage(), sisMagnetPol0Sb2Voltage_RCA, sisMagnetPol0Sb2Voltage_value, sisMagnetPol1Sb1Current(), sisMagnetPol1Sb1Current_RCA, sisMagnetPol1Sb1Current_value, sisMagnetPol1Sb1Voltage(), sisMagnetPol1Sb1Voltage_RCA, sisMagnetPol1Sb1Voltage_value, sisMagnetPol1Sb2Current(), sisMagnetPol1Sb2Current_RCA, sisMagnetPol1Sb2Current_value, sisMagnetPol1Sb2Voltage(), sisMagnetPol1Sb2Voltage_RCA, sisMagnetPol1Sb2Voltage_value, sisPol0Sb1Current_RCA, sisPol0Sb1OpenLoop_RCA, sisPol0Sb1Voltage(), sisPol0Sb1Voltage_RCA, sisPol0Sb1Voltage_value, sisPol0Sb2Current_RCA, sisPol0Sb2OpenLoop_RCA, sisPol0Sb2Voltage(), sisPol0Sb2Voltage_RCA, sisPol0Sb2Voltage_value, sisPol1Sb1Current_RCA, sisPol1Sb1OpenLoop_RCA, sisPol1Sb1Voltage(), sisPol1Sb1Voltage_RCA, sisPol1Sb1Voltage_value, sisPol1Sb2Current_RCA, sisPol1Sb2OpenLoop_RCA, sisPol1Sb2Voltage(), sisPol1Sb2Voltage_RCA, and sisPol1Sb2Voltage_value.
virtual ColdCartImplBase::~ColdCartImplBase () inline virtual
Definition at line 36 of file ColdCartImplBase.h.
References shutdown().
ColdCartImplBase::ColdCartImplBase (const ColdCartImplBase & other) private
Member Function Documentation
float ColdCartImplBase::avgSisPol0Sb1Current (int average = 8) virtual
Definition at line 366 of file ColdCartImplBase.cpp.
References sisPol0Sb1Current(), and SYNCMON_AVG_LOG_FLOAT.
Referenced by ColdCartImpl::getSISCurrent(), and monitorAction().
float ColdCartImplBase::avgSisPol0Sb2Current (int average = 8) virtual
Definition at line 370 of file ColdCartImplBase.cpp.
References sisPol0Sb2Current(), and SYNCMON_AVG_LOG_FLOAT.
Referenced by ColdCartImpl::getSISCurrent(), and monitorAction().
float ColdCartImplBase::avgSisPol1Sb1Current (int average = 8) virtual
Definition at line 374 of file ColdCartImplBase.cpp.
References sisPol1Sb1Current(), and SYNCMON_AVG_LOG_FLOAT.
Referenced by ColdCartImpl::getSISCurrent(), and monitorAction().
float ColdCartImplBase::avgSisPol1Sb2Current (int average = 8) virtual
Definition at line 378 of file ColdCartImplBase.cpp.
References sisPol1Sb2Current(), and SYNCMON_AVG_LOG_FLOAT.
Referenced by ColdCartImpl::getSISCurrent(), and monitorAction().
float ColdCartImplBase::cartridgeTemperature0 () virtual
Definition at line 606 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::cartridgeTemperature1 () virtual
Definition at line 610 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::cartridgeTemperature2 () virtual
Definition at line 614 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::sisMixerHeatingProcess(), and ColdCartImpl::sisMixerHeatingReadData().
float ColdCartImplBase::cartridgeTemperature3 () virtual
Definition at line 618 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::cartridgeTemperature4 () virtual
Definition at line 622 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::cartridgeTemperature5 () virtual
Definition at line 626 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::sisMixerHeatingProcess(), and ColdCartImpl::sisMixerHeatingReadData().
int ColdCartImplBase::getPort () const inline
Definition at line 39 of file ColdCartImplBase.h.
References port_m.
void ColdCartImplBase::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Definition at line 325 of file ColdCartImplBase.cpp.
References FrontEndLVWrapper::nodeAddress.
Referenced by ColdCartImpl::ColdCartImpl().
bool ColdCartImplBase::lnaLedPol0Enable () virtual
Definition at line 590 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by lnaLedPol0Enable(), and monitorAction().
void ColdCartImplBase::lnaLedPol0Enable (bool val) virtual
Definition at line 791 of file ColdCartImplBase.cpp.
References lnaLedPol0Enable(), and SYNCCMD_LOG_BOOL.
bool ColdCartImplBase::lnaLedPol1Enable () virtual
Definition at line 594 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by lnaLedPol1Enable(), and monitorAction().
void ColdCartImplBase::lnaLedPol1Enable (bool val) virtual
Definition at line 795 of file ColdCartImplBase.cpp.
References lnaLedPol1Enable(), and SYNCCMD_LOG_BOOL.
bool ColdCartImplBase::lnaPol0Sb1Enable () virtual
Definition at line 430 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by lnaPol0Sb1Enable(), ColdCartImpl::lnaPol0Sb1Enable(), monitorAction(), and ColdCartImpl::setLNAEnable().
void ColdCartImplBase::lnaPol0Sb1Enable (bool val) virtual
Reimplemented in ColdCartImpl.
Definition at line 679 of file ColdCartImplBase.cpp.
References lnaPol0Sb1Enable(), and SYNCCMD_LOG_BOOL.
float ColdCartImplBase::lnaPol0Sb1St1DrainCurrent () virtual
Definition at line 438 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb1St1DrainCurrent().
void ColdCartImplBase::lnaPol0Sb1St1DrainCurrent (float val) virtual
Definition at line 687 of file ColdCartImplBase.cpp.
References lnaPol0Sb1St1DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb1St1DrainVoltage () virtual
Definition at line 434 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb1St1DrainVoltage().
void ColdCartImplBase::lnaPol0Sb1St1DrainVoltage (float val) virtual
Definition at line 683 of file ColdCartImplBase.cpp.
References lnaPol0Sb1St1DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb1St1GateVoltage () virtual
Definition at line 442 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::lnaPol0Sb1St2DrainCurrent () virtual
Definition at line 450 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb1St2DrainCurrent().
void ColdCartImplBase::lnaPol0Sb1St2DrainCurrent (float val) virtual
Definition at line 695 of file ColdCartImplBase.cpp.
References lnaPol0Sb1St2DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb1St2DrainVoltage () virtual
Definition at line 446 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb1St2DrainVoltage().
void ColdCartImplBase::lnaPol0Sb1St2DrainVoltage (float val) virtual
Definition at line 691 of file ColdCartImplBase.cpp.
References lnaPol0Sb1St2DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb1St2GateVoltage () virtual
Definition at line 454 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::lnaPol0Sb1St3DrainCurrent () virtual
Definition at line 462 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb1St3DrainCurrent().
void ColdCartImplBase::lnaPol0Sb1St3DrainCurrent (float val) virtual
Definition at line 703 of file ColdCartImplBase.cpp.
References lnaPol0Sb1St3DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb1St3DrainVoltage () virtual
Definition at line 458 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb1St3DrainVoltage().
void ColdCartImplBase::lnaPol0Sb1St3DrainVoltage (float val) virtual
Definition at line 699 of file ColdCartImplBase.cpp.
References lnaPol0Sb1St3DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb1St3GateVoltage () virtual
Definition at line 466 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
bool ColdCartImplBase::lnaPol0Sb2Enable () virtual
Definition at line 470 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by lnaPol0Sb2Enable(), ColdCartImpl::lnaPol0Sb2Enable(), monitorAction(), and ColdCartImpl::setLNAEnable().
void ColdCartImplBase::lnaPol0Sb2Enable (bool val) virtual
Reimplemented in ColdCartImpl.
Definition at line 707 of file ColdCartImplBase.cpp.
References lnaPol0Sb2Enable(), and SYNCCMD_LOG_BOOL.
float ColdCartImplBase::lnaPol0Sb2St1DrainCurrent () virtual
Definition at line 478 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb2St1DrainCurrent().
void ColdCartImplBase::lnaPol0Sb2St1DrainCurrent (float val) virtual
Definition at line 715 of file ColdCartImplBase.cpp.
References lnaPol0Sb2St1DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb2St1DrainVoltage () virtual
Definition at line 474 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb2St1DrainVoltage().
void ColdCartImplBase::lnaPol0Sb2St1DrainVoltage (float val) virtual
Definition at line 711 of file ColdCartImplBase.cpp.
References lnaPol0Sb2St1DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb2St1GateVoltage () virtual
Definition at line 482 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::lnaPol0Sb2St2DrainCurrent () virtual
Definition at line 490 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb2St2DrainCurrent().
void ColdCartImplBase::lnaPol0Sb2St2DrainCurrent (float val) virtual
Definition at line 723 of file ColdCartImplBase.cpp.
References lnaPol0Sb2St2DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb2St2DrainVoltage () virtual
Definition at line 486 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb2St2DrainVoltage().
void ColdCartImplBase::lnaPol0Sb2St2DrainVoltage (float val) virtual
Definition at line 719 of file ColdCartImplBase.cpp.
References lnaPol0Sb2St2DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb2St2GateVoltage () virtual
Definition at line 494 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::lnaPol0Sb2St3DrainCurrent () virtual
Definition at line 502 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb2St3DrainCurrent().
void ColdCartImplBase::lnaPol0Sb2St3DrainCurrent (float val) virtual
Definition at line 731 of file ColdCartImplBase.cpp.
References lnaPol0Sb2St3DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb2St3DrainVoltage () virtual
Definition at line 498 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol0Sb2St3DrainVoltage().
void ColdCartImplBase::lnaPol0Sb2St3DrainVoltage (float val) virtual
Definition at line 727 of file ColdCartImplBase.cpp.
References lnaPol0Sb2St3DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol0Sb2St3GateVoltage () virtual
Definition at line 506 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
bool ColdCartImplBase::lnaPol1Sb1Enable () virtual
Definition at line 510 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by lnaPol1Sb1Enable(), ColdCartImpl::lnaPol1Sb1Enable(), monitorAction(), and ColdCartImpl::setLNAEnable().
void ColdCartImplBase::lnaPol1Sb1Enable (bool val) virtual
Reimplemented in ColdCartImpl.
Definition at line 735 of file ColdCartImplBase.cpp.
References lnaPol1Sb1Enable(), and SYNCCMD_LOG_BOOL.
float ColdCartImplBase::lnaPol1Sb1St1DrainCurrent () virtual
Definition at line 518 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb1St1DrainCurrent().
void ColdCartImplBase::lnaPol1Sb1St1DrainCurrent (float val) virtual
Definition at line 743 of file ColdCartImplBase.cpp.
References lnaPol1Sb1St1DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb1St1DrainVoltage () virtual
Definition at line 514 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb1St1DrainVoltage().
void ColdCartImplBase::lnaPol1Sb1St1DrainVoltage (float val) virtual
Definition at line 739 of file ColdCartImplBase.cpp.
References lnaPol1Sb1St1DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb1St1GateVoltage () virtual
Definition at line 522 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::lnaPol1Sb1St2DrainCurrent () virtual
Definition at line 530 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb1St2DrainCurrent().
void ColdCartImplBase::lnaPol1Sb1St2DrainCurrent (float val) virtual
Definition at line 751 of file ColdCartImplBase.cpp.
References lnaPol1Sb1St2DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb1St2DrainVoltage () virtual
Definition at line 526 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb1St2DrainVoltage().
void ColdCartImplBase::lnaPol1Sb1St2DrainVoltage (float val) virtual
Definition at line 747 of file ColdCartImplBase.cpp.
References lnaPol1Sb1St2DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb1St2GateVoltage () virtual
Definition at line 534 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::lnaPol1Sb1St3DrainCurrent () virtual
Definition at line 542 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb1St3DrainCurrent().
void ColdCartImplBase::lnaPol1Sb1St3DrainCurrent (float val) virtual
Definition at line 759 of file ColdCartImplBase.cpp.
References lnaPol1Sb1St3DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb1St3DrainVoltage () virtual
Definition at line 538 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb1St3DrainVoltage().
void ColdCartImplBase::lnaPol1Sb1St3DrainVoltage (float val) virtual
Definition at line 755 of file ColdCartImplBase.cpp.
References lnaPol1Sb1St3DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb1St3GateVoltage () virtual
Definition at line 546 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
bool ColdCartImplBase::lnaPol1Sb2Enable () virtual
Definition at line 550 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by lnaPol1Sb2Enable(), ColdCartImpl::lnaPol1Sb2Enable(), monitorAction(), and ColdCartImpl::setLNAEnable().
void ColdCartImplBase::lnaPol1Sb2Enable (bool val) virtual
Reimplemented in ColdCartImpl.
Definition at line 763 of file ColdCartImplBase.cpp.
References lnaPol1Sb2Enable(), and SYNCCMD_LOG_BOOL.
float ColdCartImplBase::lnaPol1Sb2St1DrainCurrent () virtual
Definition at line 558 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb2St1DrainCurrent().
void ColdCartImplBase::lnaPol1Sb2St1DrainCurrent (float val) virtual
Definition at line 771 of file ColdCartImplBase.cpp.
References lnaPol1Sb2St1DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb2St1DrainVoltage () virtual
Definition at line 554 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb2St1DrainVoltage().
void ColdCartImplBase::lnaPol1Sb2St1DrainVoltage (float val) virtual
Definition at line 767 of file ColdCartImplBase.cpp.
References lnaPol1Sb2St1DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb2St1GateVoltage () virtual
Definition at line 562 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::lnaPol1Sb2St2DrainCurrent () virtual
Definition at line 570 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb2St2DrainCurrent().
void ColdCartImplBase::lnaPol1Sb2St2DrainCurrent (float val) virtual
Definition at line 779 of file ColdCartImplBase.cpp.
References lnaPol1Sb2St2DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb2St2DrainVoltage () virtual
Definition at line 566 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb2St2DrainVoltage().
void ColdCartImplBase::lnaPol1Sb2St2DrainVoltage (float val) virtual
Definition at line 775 of file ColdCartImplBase.cpp.
References lnaPol1Sb2St2DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb2St2GateVoltage () virtual
Definition at line 574 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::lnaPol1Sb2St3DrainCurrent () virtual
Definition at line 582 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb2St3DrainCurrent().
void ColdCartImplBase::lnaPol1Sb2St3DrainCurrent (float val) virtual
Definition at line 787 of file ColdCartImplBase.cpp.
References lnaPol1Sb2St3DrainCurrent(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb2St3DrainVoltage () virtual
Definition at line 578 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and lnaPol1Sb2St3DrainVoltage().
void ColdCartImplBase::lnaPol1Sb2St3DrainVoltage (float val) virtual
Definition at line 783 of file ColdCartImplBase.cpp.
References lnaPol1Sb2St3DrainVoltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::lnaPol1Sb2St3GateVoltage () virtual
Definition at line 586 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
void ColdCartImplBase::logMon (bool printHeader = false) const private
Definition at line 905 of file ColdCartImplBase.cpp.
Referenced by monitorAction().
void ColdCartImplBase::monitorAction (Time * timestamp_p) protected virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implements FEHardwareDevice.
Definition at line 807 of file ColdCartImplBase.cpp.
References avgSisPol0Sb1Current(), avgSisPol0Sb2Current(), avgSisPol1Sb1Current(), avgSisPol1Sb2Current(), lastMonitorTime, lnaLedPol0Enable(), lnaLedPol0Enable_value, lnaLedPol1Enable(), lnaLedPol1Enable_value, lnaPol0Sb1Enable(), lnaPol0Sb1Enable_value, lnaPol0Sb2Enable(), lnaPol0Sb2Enable_value, lnaPol1Sb1Enable(), lnaPol1Sb1Enable_value, lnaPol1Sb2Enable(), lnaPol1Sb2Enable_value, logMon(), FEHardwareDevice::logMonitors_m, monitorPhase, FEHardwareDevice::randomizeAnalogMonitors_m, sisPol0Sb1Current_value, sisPol0Sb1OpenLoop(), sisPol0Sb1OpenLoop_value, sisPol0Sb2Current_value, sisPol0Sb2OpenLoop(), sisPol0Sb2OpenLoop_value, sisPol1Sb1Current_value, sisPol1Sb1OpenLoop(), sisPol1Sb1OpenLoop_value, sisPol1Sb2Current_value, sisPol1Sb2OpenLoop(), and sisPol1Sb2OpenLoop_value.
void ColdCartImplBase::shutdown () virtual
Definition at line 330 of file ColdCartImplBase.cpp.
Referenced by ~ColdCartImplBase().
float ColdCartImplBase::sisHeaterPol0Current () virtual
Definition at line 598 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and ColdCartImpl::getSISHeaterCurrent().
void ColdCartImplBase::sisHeaterPol0Enable (bool val) virtual
Definition at line 799 of file ColdCartImplBase.cpp.
References SYNCCMD_LOG_BOOL.
Referenced by ColdCartImpl::setSISHeaterEnable().
float ColdCartImplBase::sisHeaterPol1Current () virtual
Definition at line 602 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), and ColdCartImpl::getSISHeaterCurrent().
void ColdCartImplBase::sisHeaterPol1Enable (bool val) virtual
Definition at line 803 of file ColdCartImplBase.cpp.
References SYNCCMD_LOG_BOOL.
Referenced by ColdCartImpl::setSISHeaterEnable().
float ColdCartImplBase::sisMagnetPol0Sb1Current () virtual
Definition at line 402 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::getSISMagnetCurrent(), ColdCartImpl::setSISMagnetCurrent(), sisMagnetPol0Sb1Current(), and ColdCartImpl::sisMagnetPol0Sb1Current().
void ColdCartImplBase::sisMagnetPol0Sb1Current (float val) virtual
Reimplemented in ColdCartImpl.
Definition at line 663 of file ColdCartImplBase.cpp.
References sisMagnetPol0Sb1Current(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::sisMagnetPol0Sb1Voltage () virtual
Definition at line 398 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::sisMagnetPol0Sb2Current () virtual
Definition at line 410 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::getSISMagnetCurrent(), ColdCartImpl::setSISMagnetCurrent(), sisMagnetPol0Sb2Current(), and ColdCartImpl::sisMagnetPol0Sb2Current().
void ColdCartImplBase::sisMagnetPol0Sb2Current (float val) virtual
Reimplemented in ColdCartImpl.
Definition at line 667 of file ColdCartImplBase.cpp.
References sisMagnetPol0Sb2Current(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::sisMagnetPol0Sb2Voltage () virtual
Definition at line 406 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::sisMagnetPol1Sb1Current () virtual
Definition at line 418 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::getSISMagnetCurrent(), ColdCartImpl::setSISMagnetCurrent(), sisMagnetPol1Sb1Current(), and ColdCartImpl::sisMagnetPol1Sb1Current().
void ColdCartImplBase::sisMagnetPol1Sb1Current (float val) virtual
Reimplemented in ColdCartImpl.
Definition at line 671 of file ColdCartImplBase.cpp.
References sisMagnetPol1Sb1Current(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::sisMagnetPol1Sb1Voltage () virtual
Definition at line 414 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::sisMagnetPol1Sb2Current () virtual
Definition at line 426 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::getSISMagnetCurrent(), ColdCartImpl::setSISMagnetCurrent(), sisMagnetPol1Sb2Current(), and ColdCartImpl::sisMagnetPol1Sb2Current().
void ColdCartImplBase::sisMagnetPol1Sb2Current (float val) virtual
Reimplemented in ColdCartImpl.
Definition at line 675 of file ColdCartImplBase.cpp.
References sisMagnetPol1Sb2Current(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::sisMagnetPol1Sb2Voltage () virtual
Definition at line 422 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase().
float ColdCartImplBase::sisPol0Sb1Current () virtual
Definition at line 350 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by avgSisPol0Sb1Current().
bool ColdCartImplBase::sisPol0Sb1OpenLoop () virtual
Definition at line 382 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and sisPol0Sb1OpenLoop().
void ColdCartImplBase::sisPol0Sb1OpenLoop (bool val) virtual
Definition at line 635 of file ColdCartImplBase.cpp.
References sisPol0Sb1OpenLoop(), and SYNCCMD_LOG_BOOL.
float ColdCartImplBase::sisPol0Sb1Voltage () virtual
Definition at line 334 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::getSISVoltage(), ColdCartImpl::setSISVoltage(), sisPol0Sb1Voltage(), and ColdCartImpl::sisPol0Sb1Voltage().
void ColdCartImplBase::sisPol0Sb1Voltage (float val) virtual
Reimplemented in ColdCartImpl.
Definition at line 631 of file ColdCartImplBase.cpp.
References sisPol0Sb1Voltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::sisPol0Sb2Current () virtual
Definition at line 354 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by avgSisPol0Sb2Current().
bool ColdCartImplBase::sisPol0Sb2OpenLoop () virtual
Definition at line 386 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and sisPol0Sb2OpenLoop().
void ColdCartImplBase::sisPol0Sb2OpenLoop (bool val) virtual
Definition at line 643 of file ColdCartImplBase.cpp.
References sisPol0Sb2OpenLoop(), and SYNCCMD_LOG_BOOL.
float ColdCartImplBase::sisPol0Sb2Voltage () virtual
Definition at line 338 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::getSISVoltage(), ColdCartImpl::setSISVoltage(), sisPol0Sb2Voltage(), and ColdCartImpl::sisPol0Sb2Voltage().
void ColdCartImplBase::sisPol0Sb2Voltage (float val) virtual
Reimplemented in ColdCartImpl.
Definition at line 639 of file ColdCartImplBase.cpp.
References sisPol0Sb2Voltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::sisPol1Sb1Current () virtual
Definition at line 358 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by avgSisPol1Sb1Current().
bool ColdCartImplBase::sisPol1Sb1OpenLoop () virtual
Definition at line 390 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and sisPol1Sb1OpenLoop().
void ColdCartImplBase::sisPol1Sb1OpenLoop (bool val) virtual
Definition at line 651 of file ColdCartImplBase.cpp.
References sisPol1Sb1OpenLoop(), and SYNCCMD_LOG_BOOL.
float ColdCartImplBase::sisPol1Sb1Voltage () virtual
Definition at line 342 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::getSISVoltage(), ColdCartImpl::setSISVoltage(), sisPol1Sb1Voltage(), and ColdCartImpl::sisPol1Sb1Voltage().
void ColdCartImplBase::sisPol1Sb1Voltage (float val) virtual
Reimplemented in ColdCartImpl.
Definition at line 647 of file ColdCartImplBase.cpp.
References sisPol1Sb1Voltage(), and SYNCCMD_LOG_FLOAT.
float ColdCartImplBase::sisPol1Sb2Current () virtual
Definition at line 362 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by avgSisPol1Sb2Current().
bool ColdCartImplBase::sisPol1Sb2OpenLoop () virtual
Definition at line 394 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and sisPol1Sb2OpenLoop().
void ColdCartImplBase::sisPol1Sb2OpenLoop (bool val) virtual
Definition at line 659 of file ColdCartImplBase.cpp.
References sisPol1Sb2OpenLoop(), and SYNCCMD_LOG_BOOL.
float ColdCartImplBase::sisPol1Sb2Voltage () virtual
Definition at line 346 of file ColdCartImplBase.cpp.
References SYNCMON_LOG_FLOAT.
Referenced by ColdCartImplBase(), ColdCartImpl::getSISVoltage(), ColdCartImpl::setSISVoltage(), sisPol1Sb2Voltage(), and ColdCartImpl::sisPol1Sb2Voltage().
void ColdCartImplBase::sisPol1Sb2Voltage (float val) virtual
Reimplemented in ColdCartImpl.
Definition at line 655 of file ColdCartImplBase.cpp.
References sisPol1Sb2Voltage(), and SYNCCMD_LOG_FLOAT.
Member Data Documentation
AmbRelativeAddr ColdCartImplBase::baseRCA protected
Definition at line 371 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
AmbRelativeAddr ColdCartImplBase::cartridgeTemperature0_RCA protected
Definition at line 443 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::cartridgeTemperature0_status protected
Definition at line 362 of file ColdCartImplBase.h.
float ColdCartImplBase::cartridgeTemperature0_value protected
Definition at line 282 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::appendThermalLog(), ColdCartImplBase(), and ColdCartImpl::getMonitorTemp().
AmbRelativeAddr ColdCartImplBase::cartridgeTemperature1_RCA protected
Definition at line 444 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::cartridgeTemperature1_status protected
Definition at line 363 of file ColdCartImplBase.h.
float ColdCartImplBase::cartridgeTemperature1_value protected
Definition at line 283 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::appendThermalLog(), ColdCartImplBase(), and ColdCartImpl::getMonitorTemp().
AmbRelativeAddr ColdCartImplBase::cartridgeTemperature2_RCA protected
Definition at line 445 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::cartridgeTemperature2_status protected
Definition at line 364 of file ColdCartImplBase.h.
float ColdCartImplBase::cartridgeTemperature2_value protected
Definition at line 284 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::appendThermalLog(), ColdCartImplBase(), and ColdCartImpl::getMonitorTemp().
AmbRelativeAddr ColdCartImplBase::cartridgeTemperature3_RCA protected
Definition at line 446 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::cartridgeTemperature3_status protected
Definition at line 365 of file ColdCartImplBase.h.
float ColdCartImplBase::cartridgeTemperature3_value protected
Definition at line 285 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::appendThermalLog(), ColdCartImplBase(), and ColdCartImpl::getMonitorTemp().
AmbRelativeAddr ColdCartImplBase::cartridgeTemperature4_RCA protected
Definition at line 447 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::cartridgeTemperature4_status protected
Definition at line 366 of file ColdCartImplBase.h.
float ColdCartImplBase::cartridgeTemperature4_value protected
Definition at line 286 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::appendThermalLog(), ColdCartImplBase(), and ColdCartImpl::getMonitorTemp().
AmbRelativeAddr ColdCartImplBase::cartridgeTemperature5_RCA protected
Definition at line 448 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::cartridgeTemperature5_status protected
Definition at line 367 of file ColdCartImplBase.h.
float ColdCartImplBase::cartridgeTemperature5_value protected
Definition at line 287 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::appendThermalLog(), ColdCartImplBase(), and ColdCartImpl::getMonitorTemp().
Time ColdCartImplBase::lastMonitorTime private
Definition at line 457 of file ColdCartImplBase.h.
Referenced by monitorAction().
AmbRelativeAddr ColdCartImplBase::lnaLedPol0Enable_RCA protected
Definition at line 435 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaLedPol0Enable_status protected
Definition at line 353 of file ColdCartImplBase.h.
bool ColdCartImplBase::lnaLedPol0Enable_value protected
Definition at line 276 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorAux(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::lnaLedPol1Enable_RCA protected
Definition at line 436 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaLedPol1Enable_status protected
Definition at line 354 of file ColdCartImplBase.h.
bool ColdCartImplBase::lnaLedPol1Enable_value protected
Definition at line 277 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorAux(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1Enable_RCA protected
Definition at line 394 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::lnaPol0Sb1Enable_status protected
Definition at line 312 of file ColdCartImplBase.h.
bool ColdCartImplBase::lnaPol0Sb1Enable_value protected
Definition at line 235 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorLNA(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1St1DrainCurrent_RCA protected
Definition at line 396 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb1St1DrainCurrent_status protected
Definition at line 314 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb1St1DrainCurrent_value protected
Definition at line 237 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1St1DrainVoltage_RCA protected
Definition at line 395 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb1St1DrainVoltage_status protected
Definition at line 313 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb1St1DrainVoltage_value protected
Definition at line 236 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1St1GateVoltage_RCA protected
Definition at line 397 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb1St1GateVoltage_status protected
Definition at line 315 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb1St1GateVoltage_value protected
Definition at line 238 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1St2DrainCurrent_RCA protected
Definition at line 399 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb1St2DrainCurrent_status protected
Definition at line 317 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb1St2DrainCurrent_value protected
Definition at line 240 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1St2DrainVoltage_RCA protected
Definition at line 398 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb1St2DrainVoltage_status protected
Definition at line 316 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb1St2DrainVoltage_value protected
Definition at line 239 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1St2GateVoltage_RCA protected
Definition at line 400 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb1St2GateVoltage_status protected
Definition at line 318 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb1St2GateVoltage_value protected
Definition at line 241 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1St3DrainCurrent_RCA protected
Definition at line 402 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb1St3DrainCurrent_status protected
Definition at line 320 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb1St3DrainCurrent_value protected
Definition at line 243 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1St3DrainVoltage_RCA protected
Definition at line 401 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb1St3DrainVoltage_status protected
Definition at line 319 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb1St3DrainVoltage_value protected
Definition at line 242 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb1St3GateVoltage_RCA protected
Definition at line 403 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb1St3GateVoltage_status protected
Definition at line 321 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb1St3GateVoltage_value protected
Definition at line 244 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2Enable_RCA protected
Definition at line 404 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::lnaPol0Sb2Enable_status protected
Definition at line 322 of file ColdCartImplBase.h.
bool ColdCartImplBase::lnaPol0Sb2Enable_value protected
Definition at line 245 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorLNA(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2St1DrainCurrent_RCA protected
Definition at line 406 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb2St1DrainCurrent_status protected
Definition at line 324 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb2St1DrainCurrent_value protected
Definition at line 247 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2St1DrainVoltage_RCA protected
Definition at line 405 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb2St1DrainVoltage_status protected
Definition at line 323 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb2St1DrainVoltage_value protected
Definition at line 246 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2St1GateVoltage_RCA protected
Definition at line 407 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb2St1GateVoltage_status protected
Definition at line 325 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb2St1GateVoltage_value protected
Definition at line 248 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2St2DrainCurrent_RCA protected
Definition at line 409 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb2St2DrainCurrent_status protected
Definition at line 327 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb2St2DrainCurrent_value protected
Definition at line 250 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2St2DrainVoltage_RCA protected
Definition at line 408 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb2St2DrainVoltage_status protected
Definition at line 326 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb2St2DrainVoltage_value protected
Definition at line 249 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2St2GateVoltage_RCA protected
Definition at line 410 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb2St2GateVoltage_status protected
Definition at line 328 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb2St2GateVoltage_value protected
Definition at line 251 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2St3DrainCurrent_RCA protected
Definition at line 412 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb2St3DrainCurrent_status protected
Definition at line 330 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb2St3DrainCurrent_value protected
Definition at line 253 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2St3DrainVoltage_RCA protected
Definition at line 411 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb2St3DrainVoltage_status protected
Definition at line 329 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb2St3DrainVoltage_value protected
Definition at line 252 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol0Sb2St3GateVoltage_RCA protected
Definition at line 413 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol0Sb2St3GateVoltage_status protected
Definition at line 331 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol0Sb2St3GateVoltage_value protected
Definition at line 254 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1Enable_RCA protected
Definition at line 414 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::lnaPol1Sb1Enable_status protected
Definition at line 332 of file ColdCartImplBase.h.
bool ColdCartImplBase::lnaPol1Sb1Enable_value protected
Definition at line 255 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorLNA(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1St1DrainCurrent_RCA protected
Definition at line 416 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb1St1DrainCurrent_status protected
Definition at line 334 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb1St1DrainCurrent_value protected
Definition at line 257 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1St1DrainVoltage_RCA protected
Definition at line 415 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb1St1DrainVoltage_status protected
Definition at line 333 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb1St1DrainVoltage_value protected
Definition at line 256 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1St1GateVoltage_RCA protected
Definition at line 417 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb1St1GateVoltage_status protected
Definition at line 335 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb1St1GateVoltage_value protected
Definition at line 258 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1St2DrainCurrent_RCA protected
Definition at line 419 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb1St2DrainCurrent_status protected
Definition at line 337 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb1St2DrainCurrent_value protected
Definition at line 260 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1St2DrainVoltage_RCA protected
Definition at line 418 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb1St2DrainVoltage_status protected
Definition at line 336 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb1St2DrainVoltage_value protected
Definition at line 259 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1St2GateVoltage_RCA protected
Definition at line 420 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb1St2GateVoltage_status protected
Definition at line 338 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb1St2GateVoltage_value protected
Definition at line 261 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1St3DrainCurrent_RCA protected
Definition at line 422 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb1St3DrainCurrent_status protected
Definition at line 340 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb1St3DrainCurrent_value protected
Definition at line 263 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1St3DrainVoltage_RCA protected
Definition at line 421 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb1St3DrainVoltage_status protected
Definition at line 339 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb1St3DrainVoltage_value protected
Definition at line 262 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb1St3GateVoltage_RCA protected
Definition at line 423 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb1St3GateVoltage_status protected
Definition at line 341 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb1St3GateVoltage_value protected
Definition at line 264 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2Enable_RCA protected
Definition at line 424 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::lnaPol1Sb2Enable_status protected
Definition at line 342 of file ColdCartImplBase.h.
bool ColdCartImplBase::lnaPol1Sb2Enable_value protected
Definition at line 265 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorLNA(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2St1DrainCurrent_RCA protected
Definition at line 426 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb2St1DrainCurrent_status protected
Definition at line 344 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb2St1DrainCurrent_value protected
Definition at line 267 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2St1DrainVoltage_RCA protected
Definition at line 425 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb2St1DrainVoltage_status protected
Definition at line 343 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb2St1DrainVoltage_value protected
Definition at line 266 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2St1GateVoltage_RCA protected
Definition at line 427 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb2St1GateVoltage_status protected
Definition at line 345 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb2St1GateVoltage_value protected
Definition at line 268 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2St2DrainCurrent_RCA protected
Definition at line 429 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb2St2DrainCurrent_status protected
Definition at line 347 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb2St2DrainCurrent_value protected
Definition at line 270 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2St2DrainVoltage_RCA protected
Definition at line 428 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb2St2DrainVoltage_status protected
Definition at line 346 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb2St2DrainVoltage_value protected
Definition at line 269 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2St2GateVoltage_RCA protected
Definition at line 430 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb2St2GateVoltage_status protected
Definition at line 348 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb2St2GateVoltage_value protected
Definition at line 271 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2St3DrainCurrent_RCA protected
Definition at line 432 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb2St3DrainCurrent_status protected
Definition at line 350 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb2St3DrainCurrent_value protected
Definition at line 273 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2St3DrainVoltage_RCA protected
Definition at line 431 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb2St3DrainVoltage_status protected
Definition at line 349 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb2St3DrainVoltage_value protected
Definition at line 272 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
AmbRelativeAddr ColdCartImplBase::lnaPol1Sb2St3GateVoltage_RCA protected
Definition at line 433 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::lnaPol1Sb2St3GateVoltage_status protected
Definition at line 351 of file ColdCartImplBase.h.
float ColdCartImplBase::lnaPol1Sb2St3GateVoltage_value protected
Definition at line 274 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorLNA().
int ColdCartImplBase::monitorPhase private
Definition at line 458 of file ColdCartImplBase.h.
Referenced by monitorAction().
int ColdCartImplBase::port_m protected
to which FEMC port is this module connected.
Definition at line 451 of file ColdCartImplBase.h.
Referenced by getPort(), and ColdCartImpl::queryCartridgeState().
AmbRelativeAddr ColdCartImplBase::sisHeaterPol0Current_RCA protected
Definition at line 439 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisHeaterPol0Current_status protected
Definition at line 356 of file ColdCartImplBase.h.
float ColdCartImplBase::sisHeaterPol0Current_value protected
Definition at line 279 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorAux().
AmbRelativeAddr ColdCartImplBase::sisHeaterPol0Enable_RCA protected
Definition at line 438 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisHeaterPol0Enable_status protected
Definition at line 359 of file ColdCartImplBase.h.
AmbRelativeAddr ColdCartImplBase::sisHeaterPol1Current_RCA protected
Definition at line 441 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisHeaterPol1Current_status protected
Definition at line 357 of file ColdCartImplBase.h.
float ColdCartImplBase::sisHeaterPol1Current_value protected
Definition at line 280 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorAux().
AmbRelativeAddr ColdCartImplBase::sisHeaterPol1Enable_RCA protected
Definition at line 440 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisHeaterPol1Enable_status protected
Definition at line 360 of file ColdCartImplBase.h.
AmbRelativeAddr ColdCartImplBase::sisMagnetPol0Sb1Current_RCA protected
Definition at line 386 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::sisMagnetPol0Sb1Current_status protected
Definition at line 304 of file ColdCartImplBase.h.
float ColdCartImplBase::sisMagnetPol0Sb1Current_value protected
Definition at line 227 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisMagnetPol0Sb1Voltage_RCA protected
Definition at line 385 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisMagnetPol0Sb1Voltage_status protected
Definition at line 303 of file ColdCartImplBase.h.
float ColdCartImplBase::sisMagnetPol0Sb1Voltage_value protected
Definition at line 226 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisMagnetPol0Sb2Current_RCA protected
Definition at line 388 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::sisMagnetPol0Sb2Current_status protected
Definition at line 306 of file ColdCartImplBase.h.
float ColdCartImplBase::sisMagnetPol0Sb2Current_value protected
Definition at line 229 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisMagnetPol0Sb2Voltage_RCA protected
Definition at line 387 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisMagnetPol0Sb2Voltage_status protected
Definition at line 305 of file ColdCartImplBase.h.
float ColdCartImplBase::sisMagnetPol0Sb2Voltage_value protected
Definition at line 228 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisMagnetPol1Sb1Current_RCA protected
Definition at line 390 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::sisMagnetPol1Sb1Current_status protected
Definition at line 308 of file ColdCartImplBase.h.
float ColdCartImplBase::sisMagnetPol1Sb1Current_value protected
Definition at line 231 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisMagnetPol1Sb1Voltage_RCA protected
Definition at line 389 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisMagnetPol1Sb1Voltage_status protected
Definition at line 307 of file ColdCartImplBase.h.
float ColdCartImplBase::sisMagnetPol1Sb1Voltage_value protected
Definition at line 230 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisMagnetPol1Sb2Current_RCA protected
Definition at line 392 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::sisMagnetPol1Sb2Current_status protected
Definition at line 310 of file ColdCartImplBase.h.
float ColdCartImplBase::sisMagnetPol1Sb2Current_value protected
Definition at line 233 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisMagnetPol1Sb2Voltage_RCA protected
Definition at line 391 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisMagnetPol1Sb2Voltage_status protected
Definition at line 309 of file ColdCartImplBase.h.
float ColdCartImplBase::sisMagnetPol1Sb2Voltage_value protected
Definition at line 232 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisPol0Sb1Current_RCA protected
Definition at line 373 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisPol0Sb1Current_status protected
Definition at line 291 of file ColdCartImplBase.h.
float ColdCartImplBase::sisPol0Sb1Current_value protected
Definition at line 214 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorSIS(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::sisPol0Sb1OpenLoop_RCA protected
Definition at line 374 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisPol0Sb1OpenLoop_status protected
Definition at line 292 of file ColdCartImplBase.h.
bool ColdCartImplBase::sisPol0Sb1OpenLoop_value protected
Definition at line 215 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorSIS(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::sisPol0Sb1Voltage_RCA protected
Definition at line 372 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::sisPol0Sb1Voltage_status protected
Definition at line 290 of file ColdCartImplBase.h.
float ColdCartImplBase::sisPol0Sb1Voltage_value protected
Definition at line 213 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisPol0Sb2Current_RCA protected
Definition at line 376 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisPol0Sb2Current_status protected
Definition at line 294 of file ColdCartImplBase.h.
float ColdCartImplBase::sisPol0Sb2Current_value protected
Definition at line 217 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorSIS(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::sisPol0Sb2OpenLoop_RCA protected
Definition at line 377 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisPol0Sb2OpenLoop_status protected
Definition at line 295 of file ColdCartImplBase.h.
bool ColdCartImplBase::sisPol0Sb2OpenLoop_value protected
Definition at line 218 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorSIS(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::sisPol0Sb2Voltage_RCA protected
Definition at line 375 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::sisPol0Sb2Voltage_status protected
Definition at line 293 of file ColdCartImplBase.h.
float ColdCartImplBase::sisPol0Sb2Voltage_value protected
Definition at line 216 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisPol1Sb1Current_RCA protected
Definition at line 379 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisPol1Sb1Current_status protected
Definition at line 297 of file ColdCartImplBase.h.
float ColdCartImplBase::sisPol1Sb1Current_value protected
Definition at line 220 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorSIS(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::sisPol1Sb1OpenLoop_RCA protected
Definition at line 380 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisPol1Sb1OpenLoop_status protected
Definition at line 298 of file ColdCartImplBase.h.
bool ColdCartImplBase::sisPol1Sb1OpenLoop_value protected
Definition at line 221 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorSIS(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::sisPol1Sb1Voltage_RCA protected
Definition at line 378 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::sisPol1Sb1Voltage_status protected
Definition at line 296 of file ColdCartImplBase.h.
float ColdCartImplBase::sisPol1Sb1Voltage_value protected
Definition at line 219 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
AmbRelativeAddr ColdCartImplBase::sisPol1Sb2Current_RCA protected
Definition at line 382 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisPol1Sb2Current_status protected
Definition at line 300 of file ColdCartImplBase.h.
float ColdCartImplBase::sisPol1Sb2Current_value protected
Definition at line 223 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorSIS(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::sisPol1Sb2OpenLoop_RCA protected
Definition at line 383 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase().
int ColdCartImplBase::sisPol1Sb2OpenLoop_status protected
Definition at line 301 of file ColdCartImplBase.h.
bool ColdCartImplBase::sisPol1Sb2OpenLoop_value protected
Definition at line 224 of file ColdCartImplBase.h.
Referenced by ColdCartImpl::getMonitorSIS(), and monitorAction().
AmbRelativeAddr ColdCartImplBase::sisPol1Sb2Voltage_RCA protected
Definition at line 381 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::queryCartridgeState().
int ColdCartImplBase::sisPol1Sb2Voltage_status protected
Definition at line 299 of file ColdCartImplBase.h.
float ColdCartImplBase::sisPol1Sb2Voltage_value protected
Definition at line 222 of file ColdCartImplBase.h.
Referenced by ColdCartImplBase(), and ColdCartImpl::getMonitorSIS().
The documentation for this class was generated from the following files:
FEBASE/ColdCartImplBase.h
FEBASE/ColdCartImplBase.cpp