FrontEndControl2: MixerHeating Class Reference
MixerHeating Class Reference
#include <MixerHeating.h>
Public Member Functions
MixerHeating (ColdCartImpl &coldCart)
virtual ~MixerHeating ()
void reset ()
reset all state to initial/just constructed.
bool start (int pol, float targetTemp, int timeout)
start the mixer heating process.
virtual void requestStop ()
force the heater process to stop.
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
virtual void optimizeAction ()
derived classes must declare an optimizeAction method for the worker thread to call.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
virtual void exitAction (bool success)
derived classes may declare an exitAction which gets called just prior to the thread exiting.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Private Attributes
ColdCartImpl & coldCart_m
int pol_m
float targetTemp_m
int timeout_m
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 32 of file MixerHeating.h.
Constructor & Destructor Documentation
MixerHeating::MixerHeating (ColdCartImpl & coldCart) inline
Definition at line 34 of file MixerHeating.h.
References reset().
virtual MixerHeating::~MixerHeating () inline virtual
Definition at line 39 of file MixerHeating.h.
Member Function Documentation
void MixerHeating::optimizeAction () protected virtual
derived classes must declare an optimizeAction method for the worker thread to call.
Implements OptimizeBase.
Definition at line 49 of file MixerHeating.cpp.
void MixerHeating::requestStop () virtual
force the heater process to stop.
Reimplemented from OptimizeBase.
Definition at line 36 of file MixerHeating.cpp.
References OptimizeBase::requestStop().
void MixerHeating::reset ()
reset all state to initial/just constructed.
Definition at line 30 of file MixerHeating.cpp.
Referenced by MixerHeating().
bool MixerHeating::start (int pol, float targetTemp, int timeout)
start the mixer heating process.
If pol == -1, heat both polarizations. Else pol must be 0 or 1. If targetTemp >= 4, retrigger the the heater for up to timeout seconds to attain the target temperature. Else, retrigger the heater for exactly timeout seconds. For band 9, timeout may be no longer than 2 seconds. For bands 678, timeout may be up to 2 minutes.
Definition at line 41 of file MixerHeating.cpp.
References OptimizeBase::startWorkerThread().
Member Data Documentation
ColdCartImpl& MixerHeating::coldCart_m private
Definition at line 60 of file MixerHeating.h.
int MixerHeating::pol_m private
Definition at line 61 of file MixerHeating.h.
float MixerHeating::targetTemp_m private
Definition at line 62 of file MixerHeating.h.
int MixerHeating::timeout_m private
Definition at line 63 of file MixerHeating.h.
The documentation for this class was generated from the following files:
OPTIMIZE/MixerHeating.h
OPTIMIZE/MixerHeating.cpp