FrontEndControl2: FEConfig::ConfigProviderIniFile Class Reference
FEConfig::ConfigProviderIniFile Class Reference
Loads FE configuration data from a MySQL database connection.
#include <ConfigProviderIniFile.h>
Public Member Functions
ConfigProviderIniFile (const std::string &filename)
construct the provider with filename and behavior info for the ini file.
virtual ~ConfigProviderIniFile ()
virtual bool exists (unsigned keyFacility, unsigned configId) const
return true if the config specified by (keyFacility, configId) exists in the database, false otherwise.
virtual bool getConfiguration (unsigned keyFacility, unsigned configId, Configuration::Record &target) const
get the top-level configuration record specified by (keyFacility, configId).
virtual bool getAllConfigurations (unsigned keyFacility, std::vector< Configuration::Record > &target) const
get all configurations for the given provider.
virtual bool saveConfiguration (const Configuration &source)
write out the entire configuration to the ini file.
virtual bool getFrontEndConfig (unsigned keyFacility, unsigned keyFrontEnd, FrontEndConfig &target) const
get the FrontEndConfig portion of the specified config.
virtual bool getCryostatConfig (unsigned keyFacility, unsigned keyCryostat, CryostatConfig &target) const
get the CryostatConfig portion of the specified config.
virtual bool getLPRConfig (unsigned keyFacility, unsigned keyLPR, LPRConfig &target) const
get the LPRConfig portion of the specified config.
virtual bool getCartAssemblyConfig (CartAssemblyID id, CartAssemblyConfig &target) const
load the configuration for the specified CartAssembly.
virtual bool getColdCartConfig (unsigned keyFacility, unsigned keyColdCart, ColdCartConfig &target) const
get the ColdCartConfig portion of the specified config for the specified band.
virtual bool getWCAConfig (unsigned keyFacility, unsigned keyWCA, WCAConfig &target) const
get the WCAConfig portion of the specified config for the specified band.
Public Member Functions inherited from FEConfig::ConfigProvider
ConfigProvider ()
virtual ~ConfigProvider ()
Private Member Functions
ConfigProviderIniFile (const ConfigProvider &other)
copy construct is private and forbidden.
ConfigProviderIniFile & operator= (const ConfigProvider &other)
assignment is private and forbidden.
bool saveFrontEndConfig (const FrontEndConfig &source) const
bool saveCryosatConfig (const CryostatConfig &source) const
bool saveLPRConfig (const LPRConfig &source) const
bool saveCartAssemblyConfig (const CartAssemblyConfig &source) const
bool saveColdCartConfig (const ColdCartConfig &source) const
bool saveWCAConfig (const WCAConfig &source) const
bool getConfigurationRecord (const char *sectionName, Configuration::Record &target) const
get the items which basically define a configuration.
Static Private Member Functions
static bool parseCartSectionName (const std::string &src, unsigned &provider, unsigned &id)
private helper to extract the provider and id from a section name formatted like "~WCA2-3" where provider=2 and id=3.
static bool parseCartRow (const std::string &src, CartAssemblyID &target)
private helper to parse a cartridge assembly description row formatted like "cartPos,cartBand,WCAFacility,WCAId,CCAFacility,CCAId"
static bool parseMixerParamRow (const std::string &src, double &FreqLO, float &VJ01, float &VJ02, float &VJ11, float &VJ12, float &IJ01, float &IJ02, float &IJ11, float &IJ12)
private helper to parse a MixerParam row formatted like "FreqLO,VJ01,VJ02,VJ11,VJ12,IJ01,IJ02,IJ11,IJ12"
static bool parseMagnetParamRow (const std::string &src, double &FreqLO, float &IMag01, float &IMag02, float &IMag11, float &IMag12)
private helper to parse a MagnetParam row formatted like "FreqLO,IMag01,IMag02,IMag11,IMag12"
static bool parsePreampParamRow (const std::string &src, double &FreqLO, unsigned &pol, unsigned &sis, float &VD1, float &VD2, float &VD3, float &ID1, float &ID2, float &ID3, float &VG1, float &VG2, float &VG3)
private helper to parse a PreampParam row formatted like "FreqLO,Pol,SIS,VD1,VD2,VD3,ID1,ID2,ID3,VG1,VG2,VG3"
static bool parseLOParamRow (const std::string &src, double &FreqLO, float &VD0, float &VD1, float &VG0, float &VG1)
private helper to parse an LOParam row formatted like "FreqLO,VD0,VD1,VG0,VG1"
static bool parseUnsigned (const std::string &src, unsigned &target, int &nextPos)
private helper to extract an unsigned from the given string formatted as one of the above.
static bool parseDouble (const std::string &src, double &target, int &nextPos)
private helper to extract a double from the given string formatted as one of the above.
static bool parseFloat (const std::string &src, float &target, int &nextPos)
private helper to extract a double from the given string formatted as one of the above.
Private Attributes
CIniFile * iniFile_mp
ini file to use
Detailed Description
Loads FE configuration data from a MySQL database connection.
Definition at line 37 of file ConfigProviderIniFile.h.
Constructor & Destructor Documentation
FEConfig::ConfigProviderIniFile::ConfigProviderIniFile (const std::string & filename)
construct the provider with filename and behavior info for the ini file.
Definition at line 35 of file ConfigProviderIniFile.cpp.
FEConfig::ConfigProviderIniFile::~ConfigProviderIniFile () virtual
Definition at line 41 of file ConfigProviderIniFile.cpp.
FEConfig::ConfigProviderIniFile::ConfigProviderIniFile (const ConfigProvider & other) private
copy construct is private and forbidden.
Member Function Documentation
bool FEConfig::ConfigProviderIniFile::exists (unsigned keyFacility, unsigned configId) const virtual
return true if the config specified by (keyFacility, configId) exists in the database, false otherwise.
Implements FEConfig::ConfigProvider.
Definition at line 45 of file ConfigProviderIniFile.cpp.
bool FEConfig::ConfigProviderIniFile::getAllConfigurations (unsigned keyFacility, std::vector< Configuration::Record > & target) const virtual
get all configurations for the given provider.
Reimplemented from FEConfig::ConfigProvider.
Definition at line 78 of file ConfigProviderIniFile.cpp.
References FrontEndLVWrapper::configId, and FEConfig::Configuration::Record::reset().
bool FEConfig::ConfigProviderIniFile::getCartAssemblyConfig (CartAssemblyID id, CartAssemblyConfig & target) const virtual
load the configuration for the specified CartAssembly.
returns false if the configuration is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 246 of file ConfigProviderIniFile.cpp.
References FEConfig::CartAssemblyID::CCAFacility_m, FEConfig::CartAssemblyID::CCAId_m, FEConfig::CartAssemblyConfig::coldCart_m, FEConfig::CartAssemblyConfig::Id_m, FEConfig::CartAssemblyID::isValid(), FEConfig::ColdCartConfig::reset(), FEConfig::WCAConfig::reset(), FEConfig::CartAssemblyConfig::reset(), FEConfig::CartAssemblyConfig::WCA_m, FEConfig::CartAssemblyID::WCAFacility_m, and FEConfig::CartAssemblyID::WCAId_m.
bool FEConfig::ConfigProviderIniFile::getColdCartConfig (unsigned keyFacility, unsigned keyColdCart, ColdCartConfig & target) const virtual
get the ColdCartConfig portion of the specified config for the specified band.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 266 of file ConfigProviderIniFile.cpp.
References FEConfig::ColdCartConfig::band_m, FEConfig::ColdCartConfig::description_m, FEConfig::ColdCartConfig::ESN_m, FEConfig::ColdCartConfig::magnetParams_m, FEConfig::ColdCartConfig::mixerParams_m, FEConfig::ColdCartConfig::reset(), FEConfig::ParamTable::set(), FEConfig::ColdCartConfig::SN_m, and FEConfig::ColdCartConfig::usePreampParams().
bool FEConfig::ConfigProviderIniFile::getConfiguration (unsigned keyFacility, unsigned configId, Configuration::Record & target) const virtual
get the top-level configuration record specified by (keyFacility, configId).
returns false if the config does not exist or on error.
Implements FEConfig::ConfigProvider.
Definition at line 53 of file ConfigProviderIniFile.cpp.
References FEConfig::Configuration::Record::CAId_m, FEConfig::Configuration::Record::description_m, FEConfig::Configuration::Record::isValid(), FEConfig::Configuration::Record::keyFacility_m, FEConfig::Configuration::Record::keyFrontEnd_m, and FEConfig::Configuration::Record::reset().
bool FEConfig::ConfigProviderIniFile::getConfigurationRecord (const char * sectionName, Configuration::Record & target) const private
get the items which basically define a configuration.
bool FEConfig::ConfigProviderIniFile::getCryostatConfig (unsigned keyFacility, unsigned keyCryostat, CryostatConfig & target) const virtual
get the CryostatConfig portion of the specified config.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 216 of file ConfigProviderIniFile.cpp.
References FEConfig::CryostatConfig::ESN_m, FEConfig::CryostatConfig::reset(), and FEConfig::CryostatConfig::SN_m.
bool FEConfig::ConfigProviderIniFile::getFrontEndConfig (unsigned keyFacility, unsigned keyFrontEnd, FrontEndConfig & target) const virtual
get the FrontEndConfig portion of the specified config.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 142 of file ConfigProviderIniFile.cpp.
References FEConfig::CartAssemblyID::CCAFacility_m, FEConfig::CartAssemblyID::CCAId_m, FEConfig::CartAssemblyID::CCAValid(), FEConfig::CartAssemblyConfig::coldCart_m, FEConfig::FrontEndConfig::ESN_m, FEConfig::FrontEndConfig::fkFETIM_m, FEConfig::FrontEndConfig::fkIFSwitch_m, FEConfig::FrontEndConfig::fkPowerDist_m, FEConfig::CartAssemblyConfig::Id_m, FEConfig::CartAssemblyID::port_m, FEConfig::ColdCartConfig::reset(), FEConfig::FrontEndConfig::reset(), FEConfig::WCAConfig::reset(), FEConfig::CartAssemblyConfig::reset(), FEConfig::FrontEndConfig::setCartridgeConfig(), FEConfig::FrontEndConfig::setCryostatConfig(), FEConfig::FrontEndConfig::setLPRConfig(), FEConfig::FrontEndConfig::SN_m, FEConfig::CartAssemblyConfig::WCA_m, FEConfig::CartAssemblyID::WCAFacility_m, FEConfig::CartAssemblyID::WCAId_m, and FEConfig::CartAssemblyID::WCAValid().
bool FEConfig::ConfigProviderIniFile::getLPRConfig (unsigned keyFacility, unsigned keyLPR, LPRConfig & target) const virtual
get the LPRConfig portion of the specified config.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 231 of file ConfigProviderIniFile.cpp.
References FEConfig::LPRConfig::ESN_m, FEConfig::LPRConfig::reset(), and FEConfig::LPRConfig::SN_m.
bool FEConfig::ConfigProviderIniFile::getWCAConfig (unsigned keyFacility, unsigned keyWCA, WCAConfig & target) const virtual
get the WCAConfig portion of the specified config for the specified band.
returns false if that portion is not available or on error.
Implements FEConfig::ConfigProvider.
Definition at line 363 of file ConfigProviderIniFile.cpp.
References FEConfig::WCAConfig::band_m, FEConfig::WCAConfig::description_m, FEConfig::WCAConfig::ESN_m, FEConfig::WCAConfig::FHIYIG_m, FEConfig::WCAConfig::FLOYIG_m, FEConfig::WCAConfig::PAParams_m, FEConfig::WCAConfig::reset(), FEConfig::ParamTable::set(), and FEConfig::WCAConfig::SN_m.
ConfigProviderIniFile& FEConfig::ConfigProviderIniFile::operator= (const ConfigProvider & other) private
assignment is private and forbidden.
bool FEConfig::ConfigProviderIniFile::parseCartRow (const std::string & src, CartAssemblyID & target) static private
private helper to parse a cartridge assembly description row formatted like "cartPos,cartBand,WCAFacility,WCAId,CCAFacility,CCAId"
Definition at line 647 of file ConfigProviderIniFile.cpp.
References FEConfig::CartAssemblyID::band_m, FEConfig::CartAssemblyID::CCAFacility_m, FEConfig::CartAssemblyID::CCAId_m, FEConfig::CartAssemblyID::port_m, FEConfig::CartAssemblyID::reset(), FEConfig::CartAssemblyID::WCAFacility_m, and FEConfig::CartAssemblyID::WCAId_m.
bool FEConfig::ConfigProviderIniFile::parseCartSectionName (const std::string & src, unsigned & provider, unsigned & id) static private
private helper to extract the provider and id from a section name formatted like "~WCA2-3" where provider=2 and id=3.
Definition at line 623 of file ConfigProviderIniFile.cpp.
bool FEConfig::ConfigProviderIniFile::parseDouble (const std::string & src, double & target, int & nextPos) static private
private helper to extract a double from the given string formatted as one of the above.
extraction starts at nextPos. Also nextPos returns the position of the next item in the string.
Definition at line 822 of file ConfigProviderIniFile.cpp.
References FEConfig::TrimStr().
bool FEConfig::ConfigProviderIniFile::parseFloat (const std::string & src, float & target, int & nextPos) static private
private helper to extract a double from the given string formatted as one of the above.
extraction starts at nextPos. Also nextPos returns the position of the next item in the string.
Definition at line 845 of file ConfigProviderIniFile.cpp.
bool FEConfig::ConfigProviderIniFile::parseLOParamRow (const std::string & src, double & FreqLO, float & VD0, float & VD1, float & VG0, float & VG1) static private
private helper to parse an LOParam row formatted like "FreqLO,VD0,VD1,VG0,VG1"
Definition at line 774 of file ConfigProviderIniFile.cpp.
bool FEConfig::ConfigProviderIniFile::parseMagnetParamRow (const std::string & src, double & FreqLO, float & IMag01, float & IMag02, float & IMag11, float & IMag12) static private
private helper to parse a MagnetParam row formatted like "FreqLO,IMag01,IMag02,IMag11,IMag12"
Definition at line 706 of file ConfigProviderIniFile.cpp.
bool FEConfig::ConfigProviderIniFile::parseMixerParamRow (const std::string & src, double & FreqLO, float & VJ01, float & VJ02, float & VJ11, float & VJ12, float & IJ01, float & IJ02, float & IJ11, float & IJ12) static private
private helper to parse a MixerParam row formatted like "FreqLO,VJ01,VJ02,VJ11,VJ12,IJ01,IJ02,IJ11,IJ12"
Definition at line 672 of file ConfigProviderIniFile.cpp.
bool FEConfig::ConfigProviderIniFile::parsePreampParamRow (const std::string & src, double & FreqLO, unsigned & pol, unsigned & sis, float & VD1, float & VD2, float & VD3, float & ID1, float & ID2, float & ID3, float & VG1, float & VG2, float & VG3) static private
private helper to parse a PreampParam row formatted like "FreqLO,Pol,SIS,VD1,VD2,VD3,ID1,ID2,ID3,VG1,VG2,VG3"
Definition at line 732 of file ConfigProviderIniFile.cpp.
bool FEConfig::ConfigProviderIniFile::parseUnsigned (const std::string & src, unsigned & target, int & nextPos) static private
private helper to extract an unsigned from the given string formatted as one of the above.
extraction starts at nextPos. Also nextPos returns the position of the next item in the string.
Definition at line 799 of file ConfigProviderIniFile.cpp.
References FEConfig::TrimStr().
bool FEConfig::ConfigProviderIniFile::saveCartAssemblyConfig (const CartAssemblyConfig & source) const private
Definition at line 499 of file ConfigProviderIniFile.cpp.
References FEConfig::CartAssemblyConfig::Id_m, and FEConfig::CartAssemblyID::isValid().
bool FEConfig::ConfigProviderIniFile::saveColdCartConfig (const ColdCartConfig & source) const private
Definition at line 506 of file ConfigProviderIniFile.cpp.
References FEConfig::ColdCartConfig::band_m, FEConfig::ParamTable::begin(), FEConfig::ColdCartConfig::description_m, FEConfig::ParamTable::end(), FEConfig::ColdCartConfig::ESN_m, FEConfig::ParamTable::get(), FEConfig::ColdCartConfig::getPreampParams(), FEConfig::ColdCartConfig::keyColdCart_m, FEConfig::ColdCartConfig::keyFacility_m, FEConfig::ColdCartConfig::magnetParams_m, FEConfig::ColdCartConfig::mixerParams_m, and FEConfig::ColdCartConfig::SN_m.
bool FEConfig::ConfigProviderIniFile::saveConfiguration (const Configuration & source) virtual
write out the entire configuration to the ini file.
Reimplemented from FEConfig::ConfigProvider.
Definition at line 105 of file ConfigProviderIniFile.cpp.
References FrontEndLVWrapper::configId, FEConfig::Configuration::getConfigID(), FEConfig::Configuration::getDescription(), and FEConfig::Configuration::getFrontEndConfig().
bool FEConfig::ConfigProviderIniFile::saveCryosatConfig (const CryostatConfig & source) const private
Definition at line 473 of file ConfigProviderIniFile.cpp.
References FEConfig::CryostatConfig::ESN_m, FEConfig::CryostatConfig::keyCryostat_m, FEConfig::CryostatConfig::keyFacility_m, and FEConfig::CryostatConfig::SN_m.
bool FEConfig::ConfigProviderIniFile::saveFrontEndConfig (const FrontEndConfig & source) const private
Definition at line 418 of file ConfigProviderIniFile.cpp.
References FEConfig::FrontEndConfig::ESN_m, FEConfig::FrontEndConfig::getCartridgeConfig(), FEConfig::FrontEndConfig::getCryostatConfig(), FEConfig::FrontEndConfig::getIFSwitchConfig(), FEConfig::FrontEndConfig::getLPRConfig(), FEConfig::FrontEndConfig::getPowerDistConfig(), FEConfig::FrontEndConfig::keyFacility_m, FEConfig::FrontEndConfig::keyFrontEnd_m, and FEConfig::FrontEndConfig::SN_m.
bool FEConfig::ConfigProviderIniFile::saveLPRConfig (const LPRConfig & source) const private
Definition at line 486 of file ConfigProviderIniFile.cpp.
References FEConfig::LPRConfig::ESN_m, FEConfig::LPRConfig::keyFacility_m, FEConfig::LPRConfig::keyLPR_m, and FEConfig::LPRConfig::SN_m.
bool FEConfig::ConfigProviderIniFile::saveWCAConfig (const WCAConfig & source) const private
Definition at line 576 of file ConfigProviderIniFile.cpp.
References FEConfig::WCAConfig::band_m, FEConfig::ParamTable::begin(), FEConfig::WCAConfig::description_m, FEConfig::ParamTable::end(), FEConfig::WCAConfig::ESN_m, FEConfig::WCAConfig::FHIYIG_m, FEConfig::WCAConfig::FLOYIG_m, FEConfig::ParamTable::get(), FEConfig::WCAConfig::keyFacility_m, FEConfig::WCAConfig::keyWCA_m, FEConfig::WCAConfig::PAParams_m, and FEConfig::WCAConfig::SN_m.
Member Data Documentation
CIniFile* FEConfig::ConfigProviderIniFile::iniFile_mp private
ini file to use
Definition at line 138 of file ConfigProviderIniFile.h.
The documentation for this class was generated from the following files:
CONFIG/ConfigProviderIniFile.h
CONFIG/ConfigProviderIniFile.cpp