FrontEndControl2: IFSwitchImplBase Class Reference
IFSwitchImplBase Class Reference
#include <IFSwitchImplBase.h>
Public Member Functions
IFSwitchImplBase (const std::string &name)
virtual ~IFSwitchImplBase ()
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual unsigned char switchCartridge ()
virtual unsigned char pol0Sb1Attenuation ()
virtual unsigned char pol0Sb2Attenuation ()
virtual unsigned char pol1Sb1Attenuation ()
virtual unsigned char pol1Sb2Attenuation ()
virtual float pol0Sb1AssemblyTemp ()
virtual float pol0Sb2AssemblyTemp ()
virtual float pol1Sb1AssemblyTemp ()
virtual float pol1Sb2AssemblyTemp ()
virtual bool pol0Sb1TempServoEnable ()
virtual bool pol0Sb2TempServoEnable ()
virtual bool pol1Sb1TempServoEnable ()
virtual bool pol1Sb2TempServoEnable ()
virtual void switchCartridge (unsigned char val)
virtual void pol0Sb1Attenuation (unsigned char val)
virtual void pol0Sb2Attenuation (unsigned char val)
virtual void pol1Sb1Attenuation (unsigned char val)
virtual void pol1Sb2Attenuation (unsigned char val)
virtual void pol0Sb1TempServoEnable (bool val)
virtual void pol0Sb2TempServoEnable (bool val)
virtual void pol1Sb1TempServoEnable (bool val)
virtual void pol1Sb2TempServoEnable (bool val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Protected Types
enum MonitorControlOffset { TEMP_SERVO_ENABLE = 0x0000, ATTENUATION = 0x0001, ASSEMBLY_TEMP = 0x0002, SWITCH_CARTRIDGE = 0x0010 }
Protected Member Functions
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Protected Attributes
unsigned char switchCartridge_value
unsigned char pol0Sb1Attenuation_value
unsigned char pol0Sb2Attenuation_value
unsigned char pol1Sb1Attenuation_value
unsigned char pol1Sb2Attenuation_value
float pol0Sb1AssemblyTemp_value
float pol0Sb2AssemblyTemp_value
float pol1Sb1AssemblyTemp_value
float pol1Sb2AssemblyTemp_value
bool pol0Sb1TempServoEnable_value
bool pol0Sb2TempServoEnable_value
bool pol1Sb1TempServoEnable_value
bool pol1Sb2TempServoEnable_value
int switchCartridge_status
int pol0Sb1Attenuation_status
int pol0Sb2Attenuation_status
int pol1Sb1Attenuation_status
int pol1Sb2Attenuation_status
int pol0Sb1AssemblyTemp_status
int pol0Sb2AssemblyTemp_status
int pol1Sb1AssemblyTemp_status
int pol1Sb2AssemblyTemp_status
int pol0Sb1TempServoEnable_status
int pol0Sb2TempServoEnable_status
int pol1Sb1TempServoEnable_status
int pol1Sb2TempServoEnable_status
AmbRelativeAddr baseRCA
AmbRelativeAddr switchCartridge_RCA
AmbRelativeAddr pol0Sb1Attenuation_RCA
AmbRelativeAddr pol0Sb2Attenuation_RCA
AmbRelativeAddr pol1Sb1Attenuation_RCA
AmbRelativeAddr pol1Sb2Attenuation_RCA
AmbRelativeAddr pol0Sb1AssemblyTemp_RCA
AmbRelativeAddr pol0Sb2AssemblyTemp_RCA
AmbRelativeAddr pol1Sb1AssemblyTemp_RCA
AmbRelativeAddr pol1Sb2AssemblyTemp_RCA
AmbRelativeAddr pol0Sb1TempServoEnable_RCA
AmbRelativeAddr pol0Sb2TempServoEnable_RCA
AmbRelativeAddr pol1Sb1TempServoEnable_RCA
AmbRelativeAddr pol1Sb2TempServoEnable_RCA
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Private Member Functions
IFSwitchImplBase (const IFSwitchImplBase &other)
void logMon (bool printHeader=false) const
Private Attributes
Time lastMonitorTime
int monitorPhase
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 32 of file IFSwitchImplBase.h.
Member Enumeration Documentation
enum IFSwitchImplBase::MonitorControlOffset protected
Enumerator
TEMP_SERVO_ENABLE
ATTENUATION
ASSEMBLY_TEMP
SWITCH_CARTRIDGE
Definition at line 70 of file IFSwitchImplBase.h.
Constructor & Destructor Documentation
IFSwitchImplBase::IFSwitchImplBase (const std::string & name)
Definition at line 33 of file IFSwitchImplBase.cpp.
References ASSEMBLY_TEMP, ATTENUATION, baseRCA, pol0Sb1AssemblyTemp(), pol0Sb1AssemblyTemp_RCA, pol0Sb1AssemblyTemp_value, pol0Sb1Attenuation_RCA, pol0Sb1TempServoEnable_RCA, pol0Sb2AssemblyTemp(), pol0Sb2AssemblyTemp_RCA, pol0Sb2AssemblyTemp_value, pol0Sb2Attenuation_RCA, pol0Sb2TempServoEnable_RCA, pol1Sb1AssemblyTemp(), pol1Sb1AssemblyTemp_RCA, pol1Sb1AssemblyTemp_value, pol1Sb1Attenuation_RCA, pol1Sb1TempServoEnable_RCA, pol1Sb2AssemblyTemp(), pol1Sb2AssemblyTemp_RCA, pol1Sb2AssemblyTemp_value, pol1Sb2Attenuation_RCA, pol1Sb2TempServoEnable_RCA, SWITCH_CARTRIDGE, switchCartridge_RCA, and TEMP_SERVO_ENABLE.
virtual IFSwitchImplBase::~IFSwitchImplBase () inline virtual
Definition at line 35 of file IFSwitchImplBase.h.
References shutdown().
IFSwitchImplBase::IFSwitchImplBase (const IFSwitchImplBase & other) private
Member Function Documentation
void IFSwitchImplBase::initialize (unsigned long channel, unsigned long nodeAddress) virtual
Definition at line 78 of file IFSwitchImplBase.cpp.
References FrontEndLVWrapper::nodeAddress.
Referenced by IFSwitchImpl::IFSwitchImpl().
void IFSwitchImplBase::logMon (bool printHeader = false) const private
Definition at line 229 of file IFSwitchImplBase.cpp.
Referenced by monitorAction().
void IFSwitchImplBase::monitorAction (Time * timestamp_p) protected virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implements FEHardwareDevice.
Definition at line 190 of file IFSwitchImplBase.cpp.
References lastMonitorTime, logMon(), FEHardwareDevice::logMonitors_m, pol0Sb1Attenuation(), pol0Sb1Attenuation_value, pol0Sb1TempServoEnable(), pol0Sb1TempServoEnable_value, pol0Sb2Attenuation(), pol0Sb2Attenuation_value, pol0Sb2TempServoEnable(), pol0Sb2TempServoEnable_value, pol1Sb1Attenuation(), pol1Sb1Attenuation_value, pol1Sb1TempServoEnable(), pol1Sb1TempServoEnable_value, pol1Sb2Attenuation(), pol1Sb2Attenuation_value, pol1Sb2TempServoEnable(), pol1Sb2TempServoEnable_value, FEHardwareDevice::randomizeAnalogMonitors_m, switchCartridge(), and switchCartridge_value.
float IFSwitchImplBase::pol0Sb1AssemblyTemp () virtual
Definition at line 106 of file IFSwitchImplBase.cpp.
References MONRETURN, pol0Sb1TempServoEnable_value, and SYNCMON_LOG_FLOAT.
Referenced by IFSwitchImplBase().
unsigned char IFSwitchImplBase::pol0Sb1Attenuation () virtual
Definition at line 90 of file IFSwitchImplBase.cpp.
References SYNCMON_LOG_INT.
Referenced by monitorAction(), and pol0Sb1Attenuation().
void IFSwitchImplBase::pol0Sb1Attenuation (unsigned char val) virtual
Definition at line 158 of file IFSwitchImplBase.cpp.
References pol0Sb1Attenuation(), and SYNCCMD_LOG_INT.
bool IFSwitchImplBase::pol0Sb1TempServoEnable () virtual
Definition at line 138 of file IFSwitchImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and pol0Sb1TempServoEnable().
void IFSwitchImplBase::pol0Sb1TempServoEnable (bool val) virtual
Definition at line 174 of file IFSwitchImplBase.cpp.
References pol0Sb1TempServoEnable(), and SYNCCMD_LOG_BOOL.
float IFSwitchImplBase::pol0Sb2AssemblyTemp () virtual
Definition at line 114 of file IFSwitchImplBase.cpp.
References MONRETURN, pol0Sb2TempServoEnable_value, and SYNCMON_LOG_FLOAT.
Referenced by IFSwitchImplBase().
unsigned char IFSwitchImplBase::pol0Sb2Attenuation () virtual
Definition at line 94 of file IFSwitchImplBase.cpp.
References SYNCMON_LOG_INT.
Referenced by monitorAction(), and pol0Sb2Attenuation().
void IFSwitchImplBase::pol0Sb2Attenuation (unsigned char val) virtual
Definition at line 162 of file IFSwitchImplBase.cpp.
References pol0Sb2Attenuation(), and SYNCCMD_LOG_INT.
bool IFSwitchImplBase::pol0Sb2TempServoEnable () virtual
Definition at line 142 of file IFSwitchImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and pol0Sb2TempServoEnable().
void IFSwitchImplBase::pol0Sb2TempServoEnable (bool val) virtual
Definition at line 178 of file IFSwitchImplBase.cpp.
References pol0Sb2TempServoEnable(), and SYNCCMD_LOG_BOOL.
float IFSwitchImplBase::pol1Sb1AssemblyTemp () virtual
Definition at line 122 of file IFSwitchImplBase.cpp.
References MONRETURN, pol1Sb1TempServoEnable_value, and SYNCMON_LOG_FLOAT.
Referenced by IFSwitchImplBase().
unsigned char IFSwitchImplBase::pol1Sb1Attenuation () virtual
Definition at line 98 of file IFSwitchImplBase.cpp.
References SYNCMON_LOG_INT.
Referenced by monitorAction(), and pol1Sb1Attenuation().
void IFSwitchImplBase::pol1Sb1Attenuation (unsigned char val) virtual
Definition at line 166 of file IFSwitchImplBase.cpp.
References pol1Sb1Attenuation(), and SYNCCMD_LOG_INT.
bool IFSwitchImplBase::pol1Sb1TempServoEnable () virtual
Definition at line 146 of file IFSwitchImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and pol1Sb1TempServoEnable().
void IFSwitchImplBase::pol1Sb1TempServoEnable (bool val) virtual
Definition at line 182 of file IFSwitchImplBase.cpp.
References pol1Sb1TempServoEnable(), and SYNCCMD_LOG_BOOL.
float IFSwitchImplBase::pol1Sb2AssemblyTemp () virtual
Definition at line 130 of file IFSwitchImplBase.cpp.
References MONRETURN, pol1Sb2TempServoEnable_value, and SYNCMON_LOG_FLOAT.
Referenced by IFSwitchImplBase().
unsigned char IFSwitchImplBase::pol1Sb2Attenuation () virtual
Definition at line 102 of file IFSwitchImplBase.cpp.
References SYNCMON_LOG_INT.
Referenced by monitorAction(), and pol1Sb2Attenuation().
void IFSwitchImplBase::pol1Sb2Attenuation (unsigned char val) virtual
Definition at line 170 of file IFSwitchImplBase.cpp.
References pol1Sb2Attenuation(), and SYNCCMD_LOG_INT.
bool IFSwitchImplBase::pol1Sb2TempServoEnable () virtual
Definition at line 150 of file IFSwitchImplBase.cpp.
References SYNCMON_LOG_BOOL.
Referenced by monitorAction(), and pol1Sb2TempServoEnable().
void IFSwitchImplBase::pol1Sb2TempServoEnable (bool val) virtual
Definition at line 186 of file IFSwitchImplBase.cpp.
References pol1Sb2TempServoEnable(), and SYNCCMD_LOG_BOOL.
void IFSwitchImplBase::shutdown () virtual
Definition at line 83 of file IFSwitchImplBase.cpp.
Referenced by ~IFSwitchImplBase().
unsigned char IFSwitchImplBase::switchCartridge () virtual
Definition at line 86 of file IFSwitchImplBase.cpp.
References SYNCMON_LOG_INT.
Referenced by IFSwitchImpl::getMonitorIFSwitch(), monitorAction(), IFSwitchImpl::setObservingBand(), and switchCartridge().
void IFSwitchImplBase::switchCartridge (unsigned char val) virtual
Definition at line 154 of file IFSwitchImplBase.cpp.
References switchCartridge(), and SYNCCMD_LOG_INT.
Member Data Documentation
AmbRelativeAddr IFSwitchImplBase::baseRCA protected
Definition at line 105 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
Time IFSwitchImplBase::lastMonitorTime private
Definition at line 124 of file IFSwitchImplBase.h.
Referenced by monitorAction().
int IFSwitchImplBase::monitorPhase private
Definition at line 125 of file IFSwitchImplBase.h.
AmbRelativeAddr IFSwitchImplBase::pol0Sb1AssemblyTemp_RCA protected
Definition at line 111 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol0Sb1AssemblyTemp_status protected
Definition at line 96 of file IFSwitchImplBase.h.
float IFSwitchImplBase::pol0Sb1AssemblyTemp_value protected
Definition at line 82 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::appendThermalLog(), IFSwitchImpl::getMonitorIFSwitch(), and IFSwitchImplBase().
AmbRelativeAddr IFSwitchImplBase::pol0Sb1Attenuation_RCA protected
Definition at line 107 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol0Sb1Attenuation_status protected
Definition at line 92 of file IFSwitchImplBase.h.
unsigned char IFSwitchImplBase::pol0Sb1Attenuation_value protected
Definition at line 78 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::getMonitorIFSwitch(), and monitorAction().
AmbRelativeAddr IFSwitchImplBase::pol0Sb1TempServoEnable_RCA protected
Definition at line 115 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol0Sb1TempServoEnable_status protected
Definition at line 100 of file IFSwitchImplBase.h.
bool IFSwitchImplBase::pol0Sb1TempServoEnable_value protected
Definition at line 86 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::getMonitorIFSwitch(), monitorAction(), and pol0Sb1AssemblyTemp().
AmbRelativeAddr IFSwitchImplBase::pol0Sb2AssemblyTemp_RCA protected
Definition at line 112 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol0Sb2AssemblyTemp_status protected
Definition at line 97 of file IFSwitchImplBase.h.
float IFSwitchImplBase::pol0Sb2AssemblyTemp_value protected
Definition at line 83 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::appendThermalLog(), IFSwitchImpl::getMonitorIFSwitch(), and IFSwitchImplBase().
AmbRelativeAddr IFSwitchImplBase::pol0Sb2Attenuation_RCA protected
Definition at line 108 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol0Sb2Attenuation_status protected
Definition at line 93 of file IFSwitchImplBase.h.
unsigned char IFSwitchImplBase::pol0Sb2Attenuation_value protected
Definition at line 79 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::getMonitorIFSwitch(), and monitorAction().
AmbRelativeAddr IFSwitchImplBase::pol0Sb2TempServoEnable_RCA protected
Definition at line 116 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol0Sb2TempServoEnable_status protected
Definition at line 101 of file IFSwitchImplBase.h.
bool IFSwitchImplBase::pol0Sb2TempServoEnable_value protected
Definition at line 87 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::getMonitorIFSwitch(), monitorAction(), and pol0Sb2AssemblyTemp().
AmbRelativeAddr IFSwitchImplBase::pol1Sb1AssemblyTemp_RCA protected
Definition at line 113 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol1Sb1AssemblyTemp_status protected
Definition at line 98 of file IFSwitchImplBase.h.
float IFSwitchImplBase::pol1Sb1AssemblyTemp_value protected
Definition at line 84 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::appendThermalLog(), IFSwitchImpl::getMonitorIFSwitch(), and IFSwitchImplBase().
AmbRelativeAddr IFSwitchImplBase::pol1Sb1Attenuation_RCA protected
Definition at line 109 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol1Sb1Attenuation_status protected
Definition at line 94 of file IFSwitchImplBase.h.
unsigned char IFSwitchImplBase::pol1Sb1Attenuation_value protected
Definition at line 80 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::getMonitorIFSwitch(), and monitorAction().
AmbRelativeAddr IFSwitchImplBase::pol1Sb1TempServoEnable_RCA protected
Definition at line 117 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol1Sb1TempServoEnable_status protected
Definition at line 102 of file IFSwitchImplBase.h.
bool IFSwitchImplBase::pol1Sb1TempServoEnable_value protected
Definition at line 88 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::getMonitorIFSwitch(), monitorAction(), and pol1Sb1AssemblyTemp().
AmbRelativeAddr IFSwitchImplBase::pol1Sb2AssemblyTemp_RCA protected
Definition at line 114 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol1Sb2AssemblyTemp_status protected
Definition at line 99 of file IFSwitchImplBase.h.
float IFSwitchImplBase::pol1Sb2AssemblyTemp_value protected
Definition at line 85 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::appendThermalLog(), IFSwitchImpl::getMonitorIFSwitch(), and IFSwitchImplBase().
AmbRelativeAddr IFSwitchImplBase::pol1Sb2Attenuation_RCA protected
Definition at line 110 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol1Sb2Attenuation_status protected
Definition at line 95 of file IFSwitchImplBase.h.
unsigned char IFSwitchImplBase::pol1Sb2Attenuation_value protected
Definition at line 81 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::getMonitorIFSwitch(), and monitorAction().
AmbRelativeAddr IFSwitchImplBase::pol1Sb2TempServoEnable_RCA protected
Definition at line 118 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::pol1Sb2TempServoEnable_status protected
Definition at line 103 of file IFSwitchImplBase.h.
bool IFSwitchImplBase::pol1Sb2TempServoEnable_value protected
Definition at line 89 of file IFSwitchImplBase.h.
Referenced by IFSwitchImpl::getMonitorIFSwitch(), monitorAction(), and pol1Sb2AssemblyTemp().
AmbRelativeAddr IFSwitchImplBase::switchCartridge_RCA protected
Definition at line 106 of file IFSwitchImplBase.h.
Referenced by IFSwitchImplBase().
int IFSwitchImplBase::switchCartridge_status protected
Definition at line 91 of file IFSwitchImplBase.h.
unsigned char IFSwitchImplBase::switchCartridge_value protected
Definition at line 77 of file IFSwitchImplBase.h.
Referenced by monitorAction().
The documentation for this class was generated from the following files:
FEBASE/IFSwitchImplBase.h
FEBASE/IFSwitchImplBase.cpp