FrontEndControl2: ColdCartImpl Class Reference
ColdCartImpl Class Reference
#include <ColdCartImpl.h>
Classes
struct Aux_t
structure for returning auxiliary monitor values.
struct CartridgeTemp_t
structure for returning cartridge temperature monitor values
struct LNA_t
structure for returning LNA monitor values.
struct SIS_t
structure for returning SIS and magnet monitor values
Public Member Functions
ColdCartImpl (unsigned long channel, unsigned long nodeAddress, const std::string &name, int port, int band, const std::string &ESN="")
construct with the CAN channel and node for the front end, the name for the cold cart, the location within the front end M&C and power distribution system, the actual cartridge band which may be different than the location, and the ESN
virtual ~ColdCartImpl ()
int getBand () const
const std::string & getBandText (std::string &toFill) const
bool hasSb2 () const
true if this cartridge is 2SB or DSB, false if SSB.
bool hasSIS () const
true if this cartridge has SIS mixers.
bool hasSb2Magnet () const
true if this cartridge has a separate sb2 magnet coil.
bool hasSISHeater () const
true if this cartridge has an SIS heater.
bool hasLNA () const
true if this cartridge has LNAs.
void reset ()
set all state data to defaults, as if just constructed.
void queryCartridgeState ()
determine the cartridge state data based on monitor values.
void measureSISVoltageError ()
find and store the offset between the set and readback SIS voltage.
float measureSISVoltageErrorImpl (int pol, int sb)
Implementation of find and store the offset between the set and readback SIS voltage.
bool measureIVCurve (XYPlotArray &target, int pol, int sb, float VJlow, float VJhigh, float VJstep)
Synchronous measurement of I-V curve, placing results in the given XYPlotArray: X=VJ set, Y1=VJ read, Y2=IJ read.
bool saveIVCurveData (const XYPlotArray &source, const std::string logDir, int pol, int sb) const
Write out the contents of the source array as a text data file in the given logDir.
void stopIVCurve ()
Force the I-V curve measurement process to stop.
bool setSISEnable (bool val)
set the SIS enable state.
bool getSISEnableSetting () const
get the SIS enable state.
void setSISVoltage (int pol, int sb, float val, bool sweep=true)
set the SIS voltage control for the specified pol and sb.
float getSISVoltageSetting (int pol, int sb) const
get the last SIS voltage setting for the specified pol and sb.
float getSISVoltage (int pol, int sb, int average=1, bool print=false)
get the SIS voltage monitor for the the specified pol and sb, averaging multiple readings if requested.
float getSISCurrent (int pol, int sb, int average=1)
get the SIS current monitor for the specified pol and sb, averaging multiple readings if requested.
bool setSISMagnetEnable (bool val)
set the SIS magnet enable state.
bool getSISMagnetEnableSetting () const
get the SIS magnet enable state.
void setSISMagnetCurrent (int pol, int sb, float val, bool sweep=true, float sweepStep=0.1, unsigned sweepDwell=0)
set the SIS magnet current control for the specified pol and sb.
float getSISMagnetCurrentSetting (int pol, int sb) const
get the last SIS magnet current setting for the specified pol and sb.
float getSISMagnetCurrent (int pol, int sb)
get the SIS magnet current monitor for the the specified pol and sb.
void setSISHeaterEnable (int pol, bool enable)
Enable/disable the SIS heaters. Pol must be 0 or 1.
float getSISHeaterCurrent (int pol)
get the SIS heater current for the specified pol.
bool sisMixerHeatingProcess (int pol=-1, float targetTemp=12.0, int timeout=30)
Start the mixer heating process.
void stopMixerHeating ()
Force the mixer heating process to stop.
virtual void lnaPol0Sb1Enable (bool val)
override the base class LNA enable control function so that we can cache the value in local state.
virtual void lnaPol0Sb2Enable (bool val)
override the base class LNA enable control function so that we can cache the value in local state.
virtual void lnaPol1Sb1Enable (bool val)
override the base class LNA enable control function so that we can cache the value in local state.
virtual void lnaPol1Sb2Enable (bool val)
override the base class LNA enable control function so that we can cache the value in local state.
bool setLNAEnable (bool val)
set the LNA enable state for all pol and sb.
bool setLNAEnable (int pol, int sb, bool val)
set the LNA enable state for the specified pol and sb.
bool getLNAEnableSetting () const
get the LNA enable state for all pol and sb.
bool getLNAEnableSetting (int pol, int sb) const
get the LNA enable setting for the specified pol and sb.
bool getMonitorTemp (CartridgeTemp_t &target) const
get the cartridge temperature monitor values.
bool getMonitorSIS (int pol, int sb, SIS_t &target) const
get the SIS and magnet monitor values for the given pol and sb.
bool getMonitorLNA (int pol, int sb, LNA_t &target) const
get the LNA monitor values for the given pol and sb.
bool getMonitorAux (int pol, Aux_t &target) const
get the auxiliary monitor values for the given pol.
void appendThermalLog (std::string &target) const
append thermal information to a logging string
void appendThermalLogHeader (std::string &target) const
append thermal header information to a logging string
Public Member Functions inherited from ColdCartImplBase
ColdCartImplBase (const std::string &name, int port)
virtual ~ColdCartImplBase ()
int getPort () const
virtual void initialize (unsigned long channel, unsigned long nodeAddress)
virtual void shutdown ()
virtual float sisPol0Sb1Voltage ()
virtual float sisPol0Sb2Voltage ()
virtual float sisPol1Sb1Voltage ()
virtual float sisPol1Sb2Voltage ()
virtual float sisPol0Sb1Current ()
virtual float sisPol0Sb2Current ()
virtual float sisPol1Sb1Current ()
virtual float sisPol1Sb2Current ()
virtual float avgSisPol0Sb1Current (int average=8)
virtual float avgSisPol0Sb2Current (int average=8)
virtual float avgSisPol1Sb1Current (int average=8)
virtual float avgSisPol1Sb2Current (int average=8)
virtual bool sisPol0Sb1OpenLoop ()
virtual bool sisPol0Sb2OpenLoop ()
virtual bool sisPol1Sb1OpenLoop ()
virtual bool sisPol1Sb2OpenLoop ()
virtual float sisMagnetPol0Sb1Voltage ()
virtual float sisMagnetPol0Sb1Current ()
virtual float sisMagnetPol0Sb2Voltage ()
virtual float sisMagnetPol0Sb2Current ()
virtual float sisMagnetPol1Sb1Voltage ()
virtual float sisMagnetPol1Sb1Current ()
virtual float sisMagnetPol1Sb2Voltage ()
virtual float sisMagnetPol1Sb2Current ()
virtual bool lnaPol0Sb1Enable ()
virtual float lnaPol0Sb1St1DrainVoltage ()
virtual float lnaPol0Sb1St1DrainCurrent ()
virtual float lnaPol0Sb1St1GateVoltage ()
virtual float lnaPol0Sb1St2DrainVoltage ()
virtual float lnaPol0Sb1St2DrainCurrent ()
virtual float lnaPol0Sb1St2GateVoltage ()
virtual float lnaPol0Sb1St3DrainVoltage ()
virtual float lnaPol0Sb1St3DrainCurrent ()
virtual float lnaPol0Sb1St3GateVoltage ()
virtual bool lnaPol0Sb2Enable ()
virtual float lnaPol0Sb2St1DrainVoltage ()
virtual float lnaPol0Sb2St1DrainCurrent ()
virtual float lnaPol0Sb2St1GateVoltage ()
virtual float lnaPol0Sb2St2DrainVoltage ()
virtual float lnaPol0Sb2St2DrainCurrent ()
virtual float lnaPol0Sb2St2GateVoltage ()
virtual float lnaPol0Sb2St3DrainVoltage ()
virtual float lnaPol0Sb2St3DrainCurrent ()
virtual float lnaPol0Sb2St3GateVoltage ()
virtual bool lnaPol1Sb1Enable ()
virtual float lnaPol1Sb1St1DrainVoltage ()
virtual float lnaPol1Sb1St1DrainCurrent ()
virtual float lnaPol1Sb1St1GateVoltage ()
virtual float lnaPol1Sb1St2DrainVoltage ()
virtual float lnaPol1Sb1St2DrainCurrent ()
virtual float lnaPol1Sb1St2GateVoltage ()
virtual float lnaPol1Sb1St3DrainVoltage ()
virtual float lnaPol1Sb1St3DrainCurrent ()
virtual float lnaPol1Sb1St3GateVoltage ()
virtual bool lnaPol1Sb2Enable ()
virtual float lnaPol1Sb2St1DrainVoltage ()
virtual float lnaPol1Sb2St1DrainCurrent ()
virtual float lnaPol1Sb2St1GateVoltage ()
virtual float lnaPol1Sb2St2DrainVoltage ()
virtual float lnaPol1Sb2St2DrainCurrent ()
virtual float lnaPol1Sb2St2GateVoltage ()
virtual float lnaPol1Sb2St3DrainVoltage ()
virtual float lnaPol1Sb2St3DrainCurrent ()
virtual float lnaPol1Sb2St3GateVoltage ()
virtual bool lnaLedPol0Enable ()
virtual bool lnaLedPol1Enable ()
virtual float sisHeaterPol0Current ()
virtual float sisHeaterPol1Current ()
virtual float cartridgeTemperature0 ()
virtual float cartridgeTemperature1 ()
virtual float cartridgeTemperature2 ()
virtual float cartridgeTemperature3 ()
virtual float cartridgeTemperature4 ()
virtual float cartridgeTemperature5 ()
virtual void sisPol0Sb1OpenLoop (bool val)
virtual void sisPol0Sb2OpenLoop (bool val)
virtual void sisPol1Sb1OpenLoop (bool val)
virtual void sisPol1Sb2OpenLoop (bool val)
virtual void lnaPol0Sb1St1DrainVoltage (float val)
virtual void lnaPol0Sb1St1DrainCurrent (float val)
virtual void lnaPol0Sb1St2DrainVoltage (float val)
virtual void lnaPol0Sb1St2DrainCurrent (float val)
virtual void lnaPol0Sb1St3DrainVoltage (float val)
virtual void lnaPol0Sb1St3DrainCurrent (float val)
virtual void lnaPol0Sb2St1DrainVoltage (float val)
virtual void lnaPol0Sb2St1DrainCurrent (float val)
virtual void lnaPol0Sb2St2DrainVoltage (float val)
virtual void lnaPol0Sb2St2DrainCurrent (float val)
virtual void lnaPol0Sb2St3DrainVoltage (float val)
virtual void lnaPol0Sb2St3DrainCurrent (float val)
virtual void lnaPol1Sb1St1DrainVoltage (float val)
virtual void lnaPol1Sb1St1DrainCurrent (float val)
virtual void lnaPol1Sb1St2DrainVoltage (float val)
virtual void lnaPol1Sb1St2DrainCurrent (float val)
virtual void lnaPol1Sb1St3DrainVoltage (float val)
virtual void lnaPol1Sb1St3DrainCurrent (float val)
virtual void lnaPol1Sb2St1DrainVoltage (float val)
virtual void lnaPol1Sb2St1DrainCurrent (float val)
virtual void lnaPol1Sb2St2DrainVoltage (float val)
virtual void lnaPol1Sb2St2DrainCurrent (float val)
virtual void lnaPol1Sb2St3DrainVoltage (float val)
virtual void lnaPol1Sb2St3DrainCurrent (float val)
virtual void lnaLedPol0Enable (bool val)
virtual void lnaLedPol1Enable (bool val)
virtual void sisHeaterPol0Enable (bool val)
virtual void sisHeaterPol1Enable (bool val)
Public Member Functions inherited from FEHardwareDevice
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Public Member Functions inherited from ThermalLoggable
ThermalLoggable ()
virtual ~ThermalLoggable ()
Static Public Member Functions
static bool hasSb2 (int band)
true if the given band cartridge is 2SB or DSB, false if SSB.
static bool hasSIS (int band)
true if the given band cartridge has SIS mixers.
static bool hasSb2Magnet (int band)
true if the given band cartridge has a separate sb2 magnet coil.
static bool hasSISHeater (int band)
true if the given band cartridge has an SIS heater.
static bool hasLNA (int band)
true if the given band cartridge has LNAs. All bands as far as we know.
static bool checkPolSb (int pol, int sb)
check whether valid values are provided for pol and sb.
static int getMultiplier (int band)
get the cold multiplier for the given band.
static void appendThermalLogHeaderImpl (std::string &target)
append thermal header information to a logging string
static void appendThermalLogPlaceholder (std::string &target)
append zero data to the thermal log so that columns will align.
Static Public Member Functions inherited from FEHardwareDevice
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Private Member Functions
virtual void sisPol0Sb1Voltage (float val)
override the base class SIS voltage control function so that we can cache the value in local state.
virtual void sisPol0Sb2Voltage (float val)
override the base class SIS voltage control function so that we can cache the value in local state.
virtual void sisPol1Sb1Voltage (float val)
override the base class SIS voltage control function so that we can cache the value in local state.
virtual void sisPol1Sb2Voltage (float val)
override the base class SIS voltage control function so that we can cache the value in local state.
virtual void sisMagnetPol0Sb1Current (float val)
override the base class SIS magnet current control function so that we can cache the value in local state.
virtual void sisMagnetPol0Sb2Current (float val)
override the base class SIS magnet current control function so that we can cache the value in local state.
virtual void sisMagnetPol1Sb1Current (float val)
override the base class SIS magnet current control function so that we can cache the value in local state.
virtual void sisMagnetPol1Sb2Current (float val)
override the base class SIS magnet current control function so that we can cache the value in local state.
void resetMixerHeating ()
void sisMixerHeatingReadData (bool printHeader=false)
Private Attributes
int band_m
which cartridge band this is.
bool sisEnableSet_m
cached state: are the SIS mixers enabled?
float sisVoltageSet_m [4]
caches latest control values set.
float sisVoltageError_m [4]
SIS voltage error measured at VJset = 0.
bool sisMagnetEnableSet_m
cached state: are the SIS magnets enabled?
float sisMagnetCurrentSet_m [4]
caches latest control values set.
bool lnaEnableSet_m [4]
caches latest control values set.
bool ivCurveStop_m
bool mixerHeatingStop_m
unsigned long mixerHeatingtimerStart_m
std::ostream * mixerHeatingdataFile_mp
Static Private Attributes
static const float mixerHeatingMinTargetTemp_m
static const int mixerHeatingMaxTimeout_m
static const int mixerHeatingMaxTimeoutBand9_m
Additional Inherited Members
Public Types inherited from FEHardwareDevice
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Static Public Attributes inherited from FEHardwareDevice
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Types inherited from ColdCartImplBase
enum MonitorControlOffset {
CARTRIDGE_TEMP = 0x0880, SIS_VOLTAGE = 0x0008, SIS_CURRENT = 0x0010, SIS_OPEN_LOOP = 0x0018,
SIS_MAGNET_VOLTAGE = 0x0020, SIS_MAGNET_CURRENT = 0x0030, LNA_ENABLE = 0x0058, LNA1_DRAIN_VOLTAGE = 0x0040,
LNA1_DRAIN_CURRENT = 0x0041, LNA1_GATE_VOLTAGE = 0x0042, LNA2_DRAIN_VOLTAGE = 0x0044, LNA2_DRAIN_CURRENT = 0x0045,
LNA2_GATE_VOLTAGE = 0x0046, LNA3_DRAIN_VOLTAGE = 0x0048, LNA3_DRAIN_CURRENT = 0x0049, LNA3_GATE_VOLTAGE = 0x004A,
LNA4_DRAIN_VOLTAGE = 0x004C, LNA4_DRAIN_CURRENT = 0x004D, LNA4_GATE_VOLTAGE = 0x004E, LNA5_DRAIN_VOLTAGE = 0x0050,
LNA5_DRAIN_CURRENT = 0x0051, LNA5_GATE_VOLTAGE = 0x0052, LNA6_DRAIN_VOLTAGE = 0x0054, LNA6_DRAIN_CURRENT = 0x0055,
LNA6_GATE_VOLTAGE = 0x0056, LNA_LED_ENABLE = 0x0100, SIS_HEATER_ENABLE = 0x0180, SIS_HEATER_CURRENT = 0x01C0
}
Protected Member Functions inherited from ColdCartImplBase
virtual void monitorAction (Time *timestamp_p)
derived classes must declare a monitorAction method for the monitor thread to call.
Protected Member Functions inherited from FEHardwareDevice
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
Static Protected Member Functions inherited from FEHardwareDevice
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Protected Attributes inherited from ColdCartImplBase
float sisPol0Sb1Voltage_value
float sisPol0Sb1Current_value
bool sisPol0Sb1OpenLoop_value
float sisPol0Sb2Voltage_value
float sisPol0Sb2Current_value
bool sisPol0Sb2OpenLoop_value
float sisPol1Sb1Voltage_value
float sisPol1Sb1Current_value
bool sisPol1Sb1OpenLoop_value
float sisPol1Sb2Voltage_value
float sisPol1Sb2Current_value
bool sisPol1Sb2OpenLoop_value
float sisMagnetPol0Sb1Voltage_value
float sisMagnetPol0Sb1Current_value
float sisMagnetPol0Sb2Voltage_value
float sisMagnetPol0Sb2Current_value
float sisMagnetPol1Sb1Voltage_value
float sisMagnetPol1Sb1Current_value
float sisMagnetPol1Sb2Voltage_value
float sisMagnetPol1Sb2Current_value
bool lnaPol0Sb1Enable_value
float lnaPol0Sb1St1DrainVoltage_value
float lnaPol0Sb1St1DrainCurrent_value
float lnaPol0Sb1St1GateVoltage_value
float lnaPol0Sb1St2DrainVoltage_value
float lnaPol0Sb1St2DrainCurrent_value
float lnaPol0Sb1St2GateVoltage_value
float lnaPol0Sb1St3DrainVoltage_value
float lnaPol0Sb1St3DrainCurrent_value
float lnaPol0Sb1St3GateVoltage_value
bool lnaPol0Sb2Enable_value
float lnaPol0Sb2St1DrainVoltage_value
float lnaPol0Sb2St1DrainCurrent_value
float lnaPol0Sb2St1GateVoltage_value
float lnaPol0Sb2St2DrainVoltage_value
float lnaPol0Sb2St2DrainCurrent_value
float lnaPol0Sb2St2GateVoltage_value
float lnaPol0Sb2St3DrainVoltage_value
float lnaPol0Sb2St3DrainCurrent_value
float lnaPol0Sb2St3GateVoltage_value
bool lnaPol1Sb1Enable_value
float lnaPol1Sb1St1DrainVoltage_value
float lnaPol1Sb1St1DrainCurrent_value
float lnaPol1Sb1St1GateVoltage_value
float lnaPol1Sb1St2DrainVoltage_value
float lnaPol1Sb1St2DrainCurrent_value
float lnaPol1Sb1St2GateVoltage_value
float lnaPol1Sb1St3DrainVoltage_value
float lnaPol1Sb1St3DrainCurrent_value
float lnaPol1Sb1St3GateVoltage_value
bool lnaPol1Sb2Enable_value
float lnaPol1Sb2St1DrainVoltage_value
float lnaPol1Sb2St1DrainCurrent_value
float lnaPol1Sb2St1GateVoltage_value
float lnaPol1Sb2St2DrainVoltage_value
float lnaPol1Sb2St2DrainCurrent_value
float lnaPol1Sb2St2GateVoltage_value
float lnaPol1Sb2St3DrainVoltage_value
float lnaPol1Sb2St3DrainCurrent_value
float lnaPol1Sb2St3GateVoltage_value
bool lnaLedPol0Enable_value
bool lnaLedPol1Enable_value
float sisHeaterPol0Current_value
float sisHeaterPol1Current_value
float cartridgeTemperature0_value
float cartridgeTemperature1_value
float cartridgeTemperature2_value
float cartridgeTemperature3_value
float cartridgeTemperature4_value
float cartridgeTemperature5_value
int sisPol0Sb1Voltage_status
int sisPol0Sb1Current_status
int sisPol0Sb1OpenLoop_status
int sisPol0Sb2Voltage_status
int sisPol0Sb2Current_status
int sisPol0Sb2OpenLoop_status
int sisPol1Sb1Voltage_status
int sisPol1Sb1Current_status
int sisPol1Sb1OpenLoop_status
int sisPol1Sb2Voltage_status
int sisPol1Sb2Current_status
int sisPol1Sb2OpenLoop_status
int sisMagnetPol0Sb1Voltage_status
int sisMagnetPol0Sb1Current_status
int sisMagnetPol0Sb2Voltage_status
int sisMagnetPol0Sb2Current_status
int sisMagnetPol1Sb1Voltage_status
int sisMagnetPol1Sb1Current_status
int sisMagnetPol1Sb2Voltage_status
int sisMagnetPol1Sb2Current_status
int lnaPol0Sb1Enable_status
int lnaPol0Sb1St1DrainVoltage_status
int lnaPol0Sb1St1DrainCurrent_status
int lnaPol0Sb1St1GateVoltage_status
int lnaPol0Sb1St2DrainVoltage_status
int lnaPol0Sb1St2DrainCurrent_status
int lnaPol0Sb1St2GateVoltage_status
int lnaPol0Sb1St3DrainVoltage_status
int lnaPol0Sb1St3DrainCurrent_status
int lnaPol0Sb1St3GateVoltage_status
int lnaPol0Sb2Enable_status
int lnaPol0Sb2St1DrainVoltage_status
int lnaPol0Sb2St1DrainCurrent_status
int lnaPol0Sb2St1GateVoltage_status
int lnaPol0Sb2St2DrainVoltage_status
int lnaPol0Sb2St2DrainCurrent_status
int lnaPol0Sb2St2GateVoltage_status
int lnaPol0Sb2St3DrainVoltage_status
int lnaPol0Sb2St3DrainCurrent_status
int lnaPol0Sb2St3GateVoltage_status
int lnaPol1Sb1Enable_status
int lnaPol1Sb1St1DrainVoltage_status
int lnaPol1Sb1St1DrainCurrent_status
int lnaPol1Sb1St1GateVoltage_status
int lnaPol1Sb1St2DrainVoltage_status
int lnaPol1Sb1St2DrainCurrent_status
int lnaPol1Sb1St2GateVoltage_status
int lnaPol1Sb1St3DrainVoltage_status
int lnaPol1Sb1St3DrainCurrent_status
int lnaPol1Sb1St3GateVoltage_status
int lnaPol1Sb2Enable_status
int lnaPol1Sb2St1DrainVoltage_status
int lnaPol1Sb2St1DrainCurrent_status
int lnaPol1Sb2St1GateVoltage_status
int lnaPol1Sb2St2DrainVoltage_status
int lnaPol1Sb2St2DrainCurrent_status
int lnaPol1Sb2St2GateVoltage_status
int lnaPol1Sb2St3DrainVoltage_status
int lnaPol1Sb2St3DrainCurrent_status
int lnaPol1Sb2St3GateVoltage_status
int lnaLedPol0Enable_status
int lnaLedPol1Enable_status
int sisHeaterPol0Current_status
int sisHeaterPol1Current_status
int sisHeaterPol0Enable_status
int sisHeaterPol1Enable_status
int cartridgeTemperature0_status
int cartridgeTemperature1_status
int cartridgeTemperature2_status
int cartridgeTemperature3_status
int cartridgeTemperature4_status
int cartridgeTemperature5_status
AmbRelativeAddr baseRCA
AmbRelativeAddr sisPol0Sb1Voltage_RCA
AmbRelativeAddr sisPol0Sb1Current_RCA
AmbRelativeAddr sisPol0Sb1OpenLoop_RCA
AmbRelativeAddr sisPol0Sb2Voltage_RCA
AmbRelativeAddr sisPol0Sb2Current_RCA
AmbRelativeAddr sisPol0Sb2OpenLoop_RCA
AmbRelativeAddr sisPol1Sb1Voltage_RCA
AmbRelativeAddr sisPol1Sb1Current_RCA
AmbRelativeAddr sisPol1Sb1OpenLoop_RCA
AmbRelativeAddr sisPol1Sb2Voltage_RCA
AmbRelativeAddr sisPol1Sb2Current_RCA
AmbRelativeAddr sisPol1Sb2OpenLoop_RCA
AmbRelativeAddr sisMagnetPol0Sb1Voltage_RCA
AmbRelativeAddr sisMagnetPol0Sb1Current_RCA
AmbRelativeAddr sisMagnetPol0Sb2Voltage_RCA
AmbRelativeAddr sisMagnetPol0Sb2Current_RCA
AmbRelativeAddr sisMagnetPol1Sb1Voltage_RCA
AmbRelativeAddr sisMagnetPol1Sb1Current_RCA
AmbRelativeAddr sisMagnetPol1Sb2Voltage_RCA
AmbRelativeAddr sisMagnetPol1Sb2Current_RCA
AmbRelativeAddr lnaPol0Sb1Enable_RCA
AmbRelativeAddr lnaPol0Sb1St1DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St1DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb1St1GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St2DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St2DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb1St2GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St3DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb1St3DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb1St3GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb2Enable_RCA
AmbRelativeAddr lnaPol0Sb2St1DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St1DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb2St1GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St2DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St2DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb2St2GateVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St3DrainVoltage_RCA
AmbRelativeAddr lnaPol0Sb2St3DrainCurrent_RCA
AmbRelativeAddr lnaPol0Sb2St3GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb1Enable_RCA
AmbRelativeAddr lnaPol1Sb1St1DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St1DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb1St1GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St2DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St2DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb1St2GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St3DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb1St3DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb1St3GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb2Enable_RCA
AmbRelativeAddr lnaPol1Sb2St1DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St1DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb2St1GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St2DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St2DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb2St2GateVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St3DrainVoltage_RCA
AmbRelativeAddr lnaPol1Sb2St3DrainCurrent_RCA
AmbRelativeAddr lnaPol1Sb2St3GateVoltage_RCA
AmbRelativeAddr lnaLedPol0Enable_RCA
AmbRelativeAddr lnaLedPol1Enable_RCA
AmbRelativeAddr sisHeaterPol0Enable_RCA
AmbRelativeAddr sisHeaterPol0Current_RCA
AmbRelativeAddr sisHeaterPol1Enable_RCA
AmbRelativeAddr sisHeaterPol1Current_RCA
AmbRelativeAddr cartridgeTemperature0_RCA
AmbRelativeAddr cartridgeTemperature1_RCA
AmbRelativeAddr cartridgeTemperature2_RCA
AmbRelativeAddr cartridgeTemperature3_RCA
AmbRelativeAddr cartridgeTemperature4_RCA
AmbRelativeAddr cartridgeTemperature5_RCA
int port_m
to which FEMC port is this module connected.
Protected Attributes inherited from FEHardwareDevice
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Static Protected Attributes inherited from FEHardwareDevice
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Detailed Description
Definition at line 35 of file ColdCartImpl.h.
Constructor & Destructor Documentation
ColdCartImpl::ColdCartImpl (unsigned long channel, unsigned long nodeAddress, const std::string & name, int port, int band, const std::string & ESN = "")
construct with the CAN channel and node for the front end, the name for the cold cart, the location within the front end M&C and power distribution system, the actual cartridge band which may be different than the location, and the ESN
Definition at line 41 of file ColdCartImpl.cpp.
References ColdCartImplBase::initialize(), reset(), and FEHardwareDevice::setESN().
virtual ColdCartImpl::~ColdCartImpl () inline virtual
Definition at line 48 of file ColdCartImpl.h.
Member Function Documentation
void ColdCartImpl::appendThermalLog (std::string & target) const virtual
append thermal information to a logging string
Implements ThermalLoggable.
Definition at line 1121 of file ColdCartImpl.cpp.
References ColdCartImplBase::cartridgeTemperature0_value, ColdCartImplBase::cartridgeTemperature1_value, ColdCartImplBase::cartridgeTemperature2_value, ColdCartImplBase::cartridgeTemperature3_value, ColdCartImplBase::cartridgeTemperature4_value, and ColdCartImplBase::cartridgeTemperature5_value.
void ColdCartImpl::appendThermalLogHeader (std::string & target) const inline virtual
append thermal header information to a logging string
Implements ThermalLoggable.
Definition at line 342 of file ColdCartImpl.h.
References appendThermalLogHeaderImpl().
void ColdCartImpl::appendThermalLogHeaderImpl (std::string & target) static
append thermal header information to a logging string
Definition at line 1117 of file ColdCartImpl.cpp.
Referenced by appendThermalLogHeader(), and CartAssembly::appendThermalLogHeaderImpl().
void ColdCartImpl::appendThermalLogPlaceholder (std::string & target) static
append zero data to the thermal log so that columns will align.
Definition at line 1137 of file ColdCartImpl.cpp.
Referenced by CartAssembly::appendThermalLog().
static bool ColdCartImpl::checkPolSb (int pol, int sb) inline static
check whether valid values are provided for pol and sb.
Definition at line 270 of file ColdCartImpl.h.
Referenced by getLNAEnableSetting(), getSISCurrent(), getSISMagnetCurrent(), getSISMagnetCurrentSetting(), getSISVoltage(), getSISVoltageSetting(), measureSISVoltageErrorImpl(), and setSISMagnetCurrent().
int ColdCartImpl::getBand () const inline
Definition at line 51 of file ColdCartImpl.h.
References band_m.
Referenced by CartridgesContainer::addCartridge().
const std::string & ColdCartImpl::getBandText (std::string & toFill) const
Definition at line 56 of file ColdCartImpl.cpp.
References band_m.
Referenced by saveIVCurveData(), and sisMixerHeatingProcess().
bool ColdCartImpl::getLNAEnableSetting () const inline
get the LNA enable state for all pol and sb.
Definition at line 258 of file ColdCartImpl.h.
References lnaEnableSet_m.
bool ColdCartImpl::getLNAEnableSetting (int pol, int sb) const inline
get the LNA enable setting for the specified pol and sb.
Definition at line 262 of file ColdCartImpl.h.
References checkPolSb(), and lnaEnableSet_m.
bool ColdCartImpl::getMonitorAux (int pol, Aux_t & target) const
get the auxiliary monitor values for the given pol.
Definition at line 1099 of file ColdCartImpl.cpp.
References hasLNA(), hasSIS(), ColdCartImpl::Aux_t::lnaLedEnable_value, ColdCartImplBase::lnaLedPol0Enable_value, ColdCartImplBase::lnaLedPol1Enable_value, ColdCartImpl::Aux_t::sisHeaterCurrent_value, ColdCartImplBase::sisHeaterPol0Current_value, and ColdCartImplBase::sisHeaterPol1Current_value.
bool ColdCartImpl::getMonitorLNA (int pol, int sb, LNA_t & target) const
get the LNA monitor values for the given pol and sb.
Definition at line 1037 of file ColdCartImpl.cpp.
References hasLNA(), hasSb2(), ColdCartImpl::LNA_t::lnaEnable_value, ColdCartImplBase::lnaPol0Sb1Enable_value, ColdCartImplBase::lnaPol0Sb1St1DrainCurrent_value, ColdCartImplBase::lnaPol0Sb1St1DrainVoltage_value, ColdCartImplBase::lnaPol0Sb1St1GateVoltage_value, ColdCartImplBase::lnaPol0Sb1St2DrainCurrent_value, ColdCartImplBase::lnaPol0Sb1St2DrainVoltage_value, ColdCartImplBase::lnaPol0Sb1St2GateVoltage_value, ColdCartImplBase::lnaPol0Sb1St3DrainCurrent_value, ColdCartImplBase::lnaPol0Sb1St3DrainVoltage_value, ColdCartImplBase::lnaPol0Sb1St3GateVoltage_value, ColdCartImplBase::lnaPol0Sb2Enable_value, ColdCartImplBase::lnaPol0Sb2St1DrainCurrent_value, ColdCartImplBase::lnaPol0Sb2St1DrainVoltage_value, ColdCartImplBase::lnaPol0Sb2St1GateVoltage_value, ColdCartImplBase::lnaPol0Sb2St2DrainCurrent_value, ColdCartImplBase::lnaPol0Sb2St2DrainVoltage_value, ColdCartImplBase::lnaPol0Sb2St2GateVoltage_value, ColdCartImplBase::lnaPol0Sb2St3DrainCurrent_value, ColdCartImplBase::lnaPol0Sb2St3DrainVoltage_value, ColdCartImplBase::lnaPol0Sb2St3GateVoltage_value, ColdCartImplBase::lnaPol1Sb1Enable_value, ColdCartImplBase::lnaPol1Sb1St1DrainCurrent_value, ColdCartImplBase::lnaPol1Sb1St1DrainVoltage_value, ColdCartImplBase::lnaPol1Sb1St1GateVoltage_value, ColdCartImplBase::lnaPol1Sb1St2DrainCurrent_value, ColdCartImplBase::lnaPol1Sb1St2DrainVoltage_value, ColdCartImplBase::lnaPol1Sb1St2GateVoltage_value, ColdCartImplBase::lnaPol1Sb1St3DrainCurrent_value, ColdCartImplBase::lnaPol1Sb1St3DrainVoltage_value, ColdCartImplBase::lnaPol1Sb1St3GateVoltage_value, ColdCartImplBase::lnaPol1Sb2Enable_value, ColdCartImplBase::lnaPol1Sb2St1DrainCurrent_value, ColdCartImplBase::lnaPol1Sb2St1DrainVoltage_value, ColdCartImplBase::lnaPol1Sb2St1GateVoltage_value, ColdCartImplBase::lnaPol1Sb2St2DrainCurrent_value, ColdCartImplBase::lnaPol1Sb2St2DrainVoltage_value, ColdCartImplBase::lnaPol1Sb2St2GateVoltage_value, ColdCartImplBase::lnaPol1Sb2St3DrainCurrent_value, ColdCartImplBase::lnaPol1Sb2St3DrainVoltage_value, ColdCartImplBase::lnaPol1Sb2St3GateVoltage_value, ColdCartImpl::LNA_t::lnaSt1DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt1DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt1GateVoltage_value, ColdCartImpl::LNA_t::lnaSt2DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt2DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt2GateVoltage_value, ColdCartImpl::LNA_t::lnaSt3DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt3DrainVoltage_value, and ColdCartImpl::LNA_t::lnaSt3GateVoltage_value.
bool ColdCartImpl::getMonitorSIS (int pol, int sb, SIS_t & target) const
get the SIS and magnet monitor values for the given pol and sb.
Definition at line 995 of file ColdCartImpl.cpp.
References hasSb2(), hasSIS(), ColdCartImpl::SIS_t::sisCurrent_value, ColdCartImpl::SIS_t::sisMagnetCurrent_value, ColdCartImplBase::sisMagnetPol0Sb1Current_value, ColdCartImplBase::sisMagnetPol0Sb1Voltage_value, ColdCartImplBase::sisMagnetPol0Sb2Current_value, ColdCartImplBase::sisMagnetPol0Sb2Voltage_value, ColdCartImplBase::sisMagnetPol1Sb1Current_value, ColdCartImplBase::sisMagnetPol1Sb1Voltage_value, ColdCartImplBase::sisMagnetPol1Sb2Current_value, ColdCartImplBase::sisMagnetPol1Sb2Voltage_value, ColdCartImpl::SIS_t::sisMagnetVoltage_value, ColdCartImpl::SIS_t::sisOpenLoop_value, ColdCartImplBase::sisPol0Sb1Current_value, ColdCartImplBase::sisPol0Sb1OpenLoop_value, ColdCartImplBase::sisPol0Sb1Voltage_value, ColdCartImplBase::sisPol0Sb2Current_value, ColdCartImplBase::sisPol0Sb2OpenLoop_value, ColdCartImplBase::sisPol0Sb2Voltage_value, ColdCartImplBase::sisPol1Sb1Current_value, ColdCartImplBase::sisPol1Sb1OpenLoop_value, ColdCartImplBase::sisPol1Sb1Voltage_value, ColdCartImplBase::sisPol1Sb2Current_value, ColdCartImplBase::sisPol1Sb2OpenLoop_value, ColdCartImplBase::sisPol1Sb2Voltage_value, and ColdCartImpl::SIS_t::sisVoltage_value.
bool ColdCartImpl::getMonitorTemp (CartridgeTemp_t & target) const
get the cartridge temperature monitor values.
Definition at line 984 of file ColdCartImpl.cpp.
References ColdCartImplBase::cartridgeTemperature0_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature0_value, ColdCartImplBase::cartridgeTemperature1_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature1_value, ColdCartImplBase::cartridgeTemperature2_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature2_value, ColdCartImplBase::cartridgeTemperature3_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature3_value, ColdCartImplBase::cartridgeTemperature4_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature4_value, ColdCartImplBase::cartridgeTemperature5_value, and ColdCartImpl::CartridgeTemp_t::cartridgeTemperature5_value.
static int ColdCartImpl::getMultiplier (int band) inline static
get the cold multiplier for the given band.
Definition at line 274 of file ColdCartImpl.h.
Referenced by LORTMImpl::getRef2DivideBy(), LORTMImpl::PhaseLockTuningInit(), CartAssembly::queryCartridgeState(), and CartAssembly::setLOFrequency().
float ColdCartImpl::getSISCurrent (int pol, int sb, int average = 1)
get the SIS current monitor for the specified pol and sb, averaging multiple readings if requested.
Definition at line 455 of file ColdCartImpl.cpp.
References ColdCartImplBase::avgSisPol0Sb1Current(), ColdCartImplBase::avgSisPol0Sb2Current(), ColdCartImplBase::avgSisPol1Sb1Current(), ColdCartImplBase::avgSisPol1Sb2Current(), checkPolSb(), and hasSIS().
Referenced by measureIVCurve(), and sisMixerHeatingReadData().
bool ColdCartImpl::getSISEnableSetting () const inline
get the SIS enable state.
Definition at line 146 of file ColdCartImpl.h.
References sisEnableSet_m.
Referenced by measureIVCurve().
float ColdCartImpl::getSISHeaterCurrent (int pol) inline
get the SIS heater current for the specified pol.
Definition at line 221 of file ColdCartImpl.h.
References ColdCartImplBase::sisHeaterPol0Current(), and ColdCartImplBase::sisHeaterPol1Current().
Referenced by sisMixerHeatingProcess(), and sisMixerHeatingReadData().
float ColdCartImpl::getSISMagnetCurrent (int pol, int sb)
get the SIS magnet current monitor for the the specified pol and sb.
Definition at line 582 of file ColdCartImpl.cpp.
References checkPolSb(), hasSIS(), ColdCartImplBase::sisMagnetPol0Sb1Current(), ColdCartImplBase::sisMagnetPol0Sb2Current(), ColdCartImplBase::sisMagnetPol1Sb1Current(), and ColdCartImplBase::sisMagnetPol1Sb2Current().
float ColdCartImpl::getSISMagnetCurrentSetting (int pol, int sb) const inline
get the last SIS magnet current setting for the specified pol and sb.
Definition at line 207 of file ColdCartImpl.h.
References checkPolSb(), and sisMagnetCurrentSet_m.
Referenced by setSISMagnetCurrent().
bool ColdCartImpl::getSISMagnetEnableSetting () const inline
get the SIS magnet enable state.
Definition at line 194 of file ColdCartImpl.h.
References sisMagnetEnableSet_m.
Referenced by sisMixerHeatingProcess().
float ColdCartImpl::getSISVoltage (int pol, int sb, int average = 1, bool print = false)
get the SIS voltage monitor for the the specified pol and sb, averaging multiple readings if requested.
Definition at line 410 of file ColdCartImpl.cpp.
References checkPolSb(), hasSIS(), ColdCartImplBase::sisPol0Sb1Voltage(), ColdCartImplBase::sisPol0Sb2Voltage(), ColdCartImplBase::sisPol1Sb1Voltage(), and ColdCartImplBase::sisPol1Sb2Voltage().
Referenced by measureIVCurve(), and measureSISVoltageErrorImpl().
float ColdCartImpl::getSISVoltageSetting (int pol, int sb) const inline
get the last SIS voltage setting for the specified pol and sb.
Definition at line 154 of file ColdCartImpl.h.
References checkPolSb(), and sisVoltageSet_m.
Referenced by measureIVCurve(), measureSISVoltageErrorImpl(), and setSISVoltage().
static bool ColdCartImpl::hasLNA (int band) inline static
true if the given band cartridge has LNAs. All bands as far as we know.
Definition at line 88 of file ColdCartImpl.h.
bool ColdCartImpl::hasLNA () const inline
true if this cartridge has LNAs.
Definition at line 92 of file ColdCartImpl.h.
References band_m.
Referenced by getMonitorAux(), getMonitorLNA(), lnaPol0Sb1Enable(), lnaPol0Sb2Enable(), lnaPol1Sb1Enable(), lnaPol1Sb2Enable(), queryCartridgeState(), and setLNAEnable().
static bool ColdCartImpl::hasSb2 (int band) inline static
true if the given band cartridge is 2SB or DSB, false if SSB.
Definition at line 56 of file ColdCartImpl.h.
bool ColdCartImpl::hasSb2 () const inline
true if this cartridge is 2SB or DSB, false if SSB.
Definition at line 60 of file ColdCartImpl.h.
References band_m.
Referenced by FrontEndImpl::cartHealthCheckSaveIFPowerData(), getMonitorLNA(), getMonitorSIS(), hasSb2Magnet(), FrontEndDatabase::insertIFTotalPowerData(), FrontEndDatabase::insertYFactorData(), lnaPol0Sb2Enable(), lnaPol1Sb2Enable(), measureSISVoltageErrorImpl(), CartHealthCheck::optimizeAction(), CartHealthCheck::prepare(), queryCartridgeState(), sisMagnetPol0Sb2Current(), sisMagnetPol1Sb2Current(), sisPol0Sb2Voltage(), and sisPol1Sb2Voltage().
static bool ColdCartImpl::hasSb2Magnet (int band) inline static
true if the given band cartridge has a separate sb2 magnet coil.
Definition at line 72 of file ColdCartImpl.h.
References hasSb2().
bool ColdCartImpl::hasSb2Magnet () const inline
true if this cartridge has a separate sb2 magnet coil.
Definition at line 76 of file ColdCartImpl.h.
References band_m.
static bool ColdCartImpl::hasSIS (int band) inline static
true if the given band cartridge has SIS mixers.
Definition at line 64 of file ColdCartImpl.h.
bool ColdCartImpl::hasSIS () const inline
true if this cartridge has SIS mixers.
Definition at line 68 of file ColdCartImpl.h.
References band_m.
Referenced by getMonitorAux(), getMonitorSIS(), getSISCurrent(), getSISMagnetCurrent(), getSISVoltage(), measureIVCurve(), measureSISVoltageError(), measureSISVoltageErrorImpl(), queryCartridgeState(), setSISEnable(), setSISMagnetCurrent(), setSISMagnetEnable(), setSISVoltage(), sisMagnetPol0Sb1Current(), sisMagnetPol0Sb2Current(), sisMagnetPol1Sb1Current(), sisMagnetPol1Sb2Current(), sisPol0Sb1Voltage(), sisPol0Sb2Voltage(), sisPol1Sb1Voltage(), and sisPol1Sb2Voltage().
static bool ColdCartImpl::hasSISHeater (int band) inline static
true if the given band cartridge has an SIS heater.
Definition at line 80 of file ColdCartImpl.h.
bool ColdCartImpl::hasSISHeater () const inline
true if this cartridge has an SIS heater.
Definition at line 84 of file ColdCartImpl.h.
References band_m.
Referenced by setSISHeaterEnable(), and sisMixerHeatingProcess().
void ColdCartImpl::lnaPol0Sb1Enable (bool val) virtual
override the base class LNA enable control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 915 of file ColdCartImpl.cpp.
References hasLNA(), lnaEnableSet_m, and ColdCartImplBase::lnaPol0Sb1Enable().
void ColdCartImpl::lnaPol0Sb2Enable (bool val) virtual
override the base class LNA enable control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 922 of file ColdCartImpl.cpp.
References hasLNA(), hasSb2(), lnaEnableSet_m, and ColdCartImplBase::lnaPol0Sb2Enable().
void ColdCartImpl::lnaPol1Sb1Enable (bool val) virtual
override the base class LNA enable control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 929 of file ColdCartImpl.cpp.
References hasLNA(), lnaEnableSet_m, and ColdCartImplBase::lnaPol1Sb1Enable().
void ColdCartImpl::lnaPol1Sb2Enable (bool val) virtual
override the base class LNA enable control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 936 of file ColdCartImpl.cpp.
References hasLNA(), hasSb2(), lnaEnableSet_m, and ColdCartImplBase::lnaPol1Sb2Enable().
bool ColdCartImpl::measureIVCurve (XYPlotArray & target, int pol, int sb, float VJlow, float VJhigh, float VJstep)
Synchronous measurement of I-V curve, placing results in the given XYPlotArray: X=VJ set, Y1=VJ read, Y2=IJ read.
Reports progress messages via FEMCEventQueue. Returns VJ to whatever it was set to prior to the measurement.
Definition at line 278 of file ColdCartImpl.cpp.
References FEMCEventQueue::addProgressEvent(), FEMCEventQueue::addStatusMessage(), band_m, getSISCurrent(), getSISEnableSetting(), getSISVoltage(), getSISVoltageSetting(), hasSIS(), ivCurveStop_m, and setSISVoltage().
void ColdCartImpl::measureSISVoltageError ()
find and store the offset between the set and readback SIS voltage.
Definition at line 201 of file ColdCartImpl.cpp.
References hasSIS(), measureSISVoltageErrorImpl(), and sisVoltageError_m.
float ColdCartImpl::measureSISVoltageErrorImpl (int pol, int sb)
Implementation of find and store the offset between the set and readback SIS voltage.
Definition at line 215 of file ColdCartImpl.cpp.
References band_m, checkPolSb(), getSISVoltage(), getSISVoltageSetting(), hasSb2(), hasSIS(), setSISVoltage(), and sisVoltageError_m.
Referenced by measureSISVoltageError().
void ColdCartImpl::queryCartridgeState ()
determine the cartridge state data based on monitor values.
Definition at line 72 of file ColdCartImpl.cpp.
References band_m, hasLNA(), hasSb2(), hasSIS(), lnaEnableSet_m, ColdCartImplBase::lnaPol0Sb1Enable_RCA, ColdCartImplBase::lnaPol0Sb2Enable_RCA, ColdCartImplBase::lnaPol1Sb1Enable_RCA, ColdCartImplBase::lnaPol1Sb2Enable_RCA, ColdCartImplBase::port_m, sisEnableSet_m, sisMagnetCurrentSet_m, sisMagnetEnableSet_m, ColdCartImplBase::sisMagnetPol0Sb1Current_RCA, ColdCartImplBase::sisMagnetPol0Sb2Current_RCA, ColdCartImplBase::sisMagnetPol1Sb1Current_RCA, ColdCartImplBase::sisMagnetPol1Sb2Current_RCA, ColdCartImplBase::sisPol0Sb1Voltage_RCA, ColdCartImplBase::sisPol0Sb2Voltage_RCA, ColdCartImplBase::sisPol1Sb1Voltage_RCA, ColdCartImplBase::sisPol1Sb2Voltage_RCA, sisVoltageSet_m, and FEHardwareDevice::syncMonitorWithRetry().
void ColdCartImpl::reset ()
set all state data to defaults, as if just constructed.
Definition at line 62 of file ColdCartImpl.cpp.
References lnaEnableSet_m, resetMixerHeating(), sisEnableSet_m, sisMagnetCurrentSet_m, sisMagnetEnableSet_m, sisVoltageError_m, and sisVoltageSet_m.
Referenced by ColdCartImpl().
void ColdCartImpl::resetMixerHeating () private
Definition at line 641 of file ColdCartImpl.cpp.
References mixerHeatingdataFile_mp, mixerHeatingStop_m, and mixerHeatingtimerStart_m.
Referenced by reset(), and sisMixerHeatingProcess().
bool ColdCartImpl::saveIVCurveData (const XYPlotArray & source, const std::string logDir, int pol, int sb) const
Write out the contents of the source array as a text data file in the given logDir.
Definition at line 375 of file ColdCartImpl.cpp.
References getBandText().
bool ColdCartImpl::setLNAEnable (bool val)
set the LNA enable state for all pol and sb.
returns true if LNA is defined for this band. Else logs an error message and returns false.
Definition at line 943 of file ColdCartImpl.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, hasLNA(), ColdCartImplBase::lnaPol0Sb1Enable(), ColdCartImplBase::lnaPol0Sb2Enable(), ColdCartImplBase::lnaPol1Sb1Enable(), and ColdCartImplBase::lnaPol1Sb2Enable().
bool ColdCartImpl::setLNAEnable (int pol, int sb, bool val)
set the LNA enable state for the specified pol and sb.
returns true if LNA is defined for this band. Else logs an error message and returns false.
Definition at line 960 of file ColdCartImpl.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, hasLNA(), ColdCartImplBase::lnaPol0Sb1Enable(), ColdCartImplBase::lnaPol0Sb2Enable(), ColdCartImplBase::lnaPol1Sb1Enable(), and ColdCartImplBase::lnaPol1Sb2Enable().
bool ColdCartImpl::setSISEnable (bool val)
set the SIS enable state.
If val is false, forces the SIS voltage to zero. returns true this band has an SIS. Otherwise false and logs an error.
Definition at line 478 of file ColdCartImpl.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, hasSIS(), setSISVoltage(), and sisEnableSet_m.
void ColdCartImpl::setSISHeaterEnable (int pol, bool enable)
Enable/disable the SIS heaters. Pol must be 0 or 1.
Definition at line 632 of file ColdCartImpl.cpp.
References hasSISHeater(), ColdCartImplBase::sisHeaterPol0Enable(), and ColdCartImplBase::sisHeaterPol1Enable().
Referenced by sisMixerHeatingProcess().
void ColdCartImpl::setSISMagnetCurrent (int pol, int sb, float val, bool sweep = true, float sweepStep = 0.1, unsigned sweepDwell = 0)
set the SIS magnet current control for the specified pol and sb.
sweep = true means to move gradually from the present setting to the new setting. The sweepStep size may be specified to be anything down to 0.001 mA. sweepDwell gives how many milliseconds to pause at each intermediate step.
Definition at line 529 of file ColdCartImpl.cpp.
References checkPolSb(), getSISMagnetCurrentSetting(), hasSIS(), ColdCartImplBase::sisMagnetPol0Sb1Current(), ColdCartImplBase::sisMagnetPol0Sb2Current(), ColdCartImplBase::sisMagnetPol1Sb1Current(), and ColdCartImplBase::sisMagnetPol1Sb2Current().
Referenced by setSISMagnetEnable().
bool ColdCartImpl::setSISMagnetEnable (bool val)
set the SIS magnet enable state.
If val is false, forces the magnets to zero bias. return true of the band has a magnet and no error. Else log an error and return false.
Definition at line 601 of file ColdCartImpl.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, hasSIS(), setSISMagnetCurrent(), and sisMagnetEnableSet_m.
Referenced by sisMixerHeatingProcess().
void ColdCartImpl::setSISVoltage (int pol, int sb, float val, bool sweep = true)
set the SIS voltage control for the specified pol and sb.
sweep = true means to move gradually from the present setting to the new setting.
Definition at line 152 of file ColdCartImpl.cpp.
References band_m, getSISVoltageSetting(), hasSIS(), ColdCartImplBase::sisPol0Sb1Voltage(), ColdCartImplBase::sisPol0Sb2Voltage(), ColdCartImplBase::sisPol1Sb1Voltage(), and ColdCartImplBase::sisPol1Sb2Voltage().
Referenced by CartAssembly::measureFineLOSweepSingleSynchronous(), measureIVCurve(), measureSISVoltageErrorImpl(), and setSISEnable().
void ColdCartImpl::sisMagnetPol0Sb1Current (float val) private virtual
override the base class SIS magnet current control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 501 of file ColdCartImpl.cpp.
References hasSIS(), sisMagnetCurrentSet_m, and ColdCartImplBase::sisMagnetPol0Sb1Current().
void ColdCartImpl::sisMagnetPol0Sb2Current (float val) private virtual
override the base class SIS magnet current control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 508 of file ColdCartImpl.cpp.
References hasSb2(), hasSIS(), sisMagnetCurrentSet_m, and ColdCartImplBase::sisMagnetPol0Sb2Current().
void ColdCartImpl::sisMagnetPol1Sb1Current (float val) private virtual
override the base class SIS magnet current control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 515 of file ColdCartImpl.cpp.
References hasSIS(), sisMagnetCurrentSet_m, and ColdCartImplBase::sisMagnetPol1Sb1Current().
void ColdCartImpl::sisMagnetPol1Sb2Current (float val) private virtual
override the base class SIS magnet current control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 522 of file ColdCartImpl.cpp.
References hasSb2(), hasSIS(), sisMagnetCurrentSet_m, and ColdCartImplBase::sisMagnetPol1Sb2Current().
bool ColdCartImpl::sisMixerHeatingProcess (int pol = -1, float targetTemp = 12.0, int timeout = 30)
Start the mixer heating process.
If pol == -1, heat both polarizations. Else pol must be 0 or 1. If targetTemp >= 4, retrigger the the heater for up to timeout seconds to attain the target temperature. Else, retrigger the heater for exactly timeout seconds. For band 9, timeout may be no longer than 2 seconds. For bands 678, timeout may be up to 2 minutes. Watches member variable mixerHeatingStop_m and aborts if true.
Definition at line 651 of file ColdCartImpl.cpp.
References FEMCEventQueue::addStatusMessage(), band_m, ColdCartImplBase::cartridgeTemperature2(), ColdCartImplBase::cartridgeTemperature5(), getBandText(), FEConfig::getLogDir(), getSISHeaterCurrent(), getSISMagnetEnableSetting(), hasSISHeater(), FEConfig::logDir, mixerHeatingdataFile_mp, mixerHeatingMaxTimeout_m, mixerHeatingMaxTimeoutBand9_m, mixerHeatingMinTargetTemp_m, mixerHeatingStop_m, mixerHeatingtimerStart_m, resetMixerHeating(), setSISHeaterEnable(), setSISMagnetEnable(), and sisMixerHeatingReadData().
void ColdCartImpl::sisMixerHeatingReadData (bool printHeader = false) private
Definition at line 888 of file ColdCartImpl.cpp.
References ColdCartImplBase::cartridgeTemperature2(), ColdCartImplBase::cartridgeTemperature5(), getSISCurrent(), getSISHeaterCurrent(), mixerHeatingdataFile_mp, and mixerHeatingtimerStart_m.
Referenced by sisMixerHeatingProcess().
void ColdCartImpl::sisPol0Sb1Voltage (float val) private virtual
override the base class SIS voltage control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 120 of file ColdCartImpl.cpp.
References hasSIS(), ColdCartImplBase::sisPol0Sb1Voltage(), sisVoltageError_m, and sisVoltageSet_m.
void ColdCartImpl::sisPol0Sb2Voltage (float val) private virtual
override the base class SIS voltage control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 128 of file ColdCartImpl.cpp.
References hasSb2(), hasSIS(), ColdCartImplBase::sisPol0Sb2Voltage(), sisVoltageError_m, and sisVoltageSet_m.
void ColdCartImpl::sisPol1Sb1Voltage (float val) private virtual
override the base class SIS voltage control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 136 of file ColdCartImpl.cpp.
References hasSIS(), ColdCartImplBase::sisPol1Sb1Voltage(), sisVoltageError_m, and sisVoltageSet_m.
void ColdCartImpl::sisPol1Sb2Voltage (float val) private virtual
override the base class SIS voltage control function so that we can cache the value in local state.
Reimplemented from ColdCartImplBase.
Definition at line 144 of file ColdCartImpl.cpp.
References hasSb2(), hasSIS(), ColdCartImplBase::sisPol1Sb2Voltage(), sisVoltageError_m, and sisVoltageSet_m.
void ColdCartImpl::stopIVCurve () inline
Force the I-V curve measurement process to stop.
Definition at line 116 of file ColdCartImpl.h.
References ivCurveStop_m.
void ColdCartImpl::stopMixerHeating () inline
Force the mixer heating process to stop.
Definition at line 234 of file ColdCartImpl.h.
References mixerHeatingStop_m.
Member Data Documentation
int ColdCartImpl::band_m private
which cartridge band this is.
Definition at line 353 of file ColdCartImpl.h.
Referenced by getBand(), getBandText(), hasLNA(), hasSb2(), hasSb2Magnet(), hasSIS(), hasSISHeater(), measureIVCurve(), measureSISVoltageErrorImpl(), queryCartridgeState(), setLNAEnable(), setSISEnable(), setSISMagnetEnable(), setSISVoltage(), and sisMixerHeatingProcess().
bool ColdCartImpl::ivCurveStop_m private
Definition at line 365 of file ColdCartImpl.h.
Referenced by measureIVCurve(), and stopIVCurve().
bool ColdCartImpl::lnaEnableSet_m[4] private
caches latest control values set.
Definition at line 359 of file ColdCartImpl.h.
Referenced by getLNAEnableSetting(), lnaPol0Sb1Enable(), lnaPol0Sb2Enable(), lnaPol1Sb1Enable(), lnaPol1Sb2Enable(), queryCartridgeState(), and reset().
std::ostream* ColdCartImpl::mixerHeatingdataFile_mp private
Definition at line 368 of file ColdCartImpl.h.
Referenced by resetMixerHeating(), sisMixerHeatingProcess(), and sisMixerHeatingReadData().
const int ColdCartImpl::mixerHeatingMaxTimeout_m static private
Definition at line 370 of file ColdCartImpl.h.
Referenced by sisMixerHeatingProcess().
const int ColdCartImpl::mixerHeatingMaxTimeoutBand9_m static private
Definition at line 371 of file ColdCartImpl.h.
Referenced by sisMixerHeatingProcess().
const float ColdCartImpl::mixerHeatingMinTargetTemp_m static private
Definition at line 369 of file ColdCartImpl.h.
Referenced by sisMixerHeatingProcess().
bool ColdCartImpl::mixerHeatingStop_m private
Definition at line 366 of file ColdCartImpl.h.
Referenced by resetMixerHeating(), sisMixerHeatingProcess(), and stopMixerHeating().
unsigned long ColdCartImpl::mixerHeatingtimerStart_m private
Definition at line 367 of file ColdCartImpl.h.
Referenced by resetMixerHeating(), sisMixerHeatingProcess(), and sisMixerHeatingReadData().
bool ColdCartImpl::sisEnableSet_m private
cached state: are the SIS mixers enabled?
Definition at line 354 of file ColdCartImpl.h.
Referenced by getSISEnableSetting(), queryCartridgeState(), reset(), and setSISEnable().
float ColdCartImpl::sisMagnetCurrentSet_m[4] private
caches latest control values set.
Definition at line 358 of file ColdCartImpl.h.
Referenced by getSISMagnetCurrentSetting(), queryCartridgeState(), reset(), sisMagnetPol0Sb1Current(), sisMagnetPol0Sb2Current(), sisMagnetPol1Sb1Current(), and sisMagnetPol1Sb2Current().
bool ColdCartImpl::sisMagnetEnableSet_m private
cached state: are the SIS magnets enabled?
Definition at line 357 of file ColdCartImpl.h.
Referenced by getSISMagnetEnableSetting(), queryCartridgeState(), reset(), and setSISMagnetEnable().
float ColdCartImpl::sisVoltageError_m[4] private
SIS voltage error measured at VJset = 0.
Definition at line 356 of file ColdCartImpl.h.
Referenced by measureSISVoltageError(), measureSISVoltageErrorImpl(), reset(), sisPol0Sb1Voltage(), sisPol0Sb2Voltage(), sisPol1Sb1Voltage(), and sisPol1Sb2Voltage().
float ColdCartImpl::sisVoltageSet_m[4] private
caches latest control values set.
Definition at line 355 of file ColdCartImpl.h.
Referenced by getSISVoltageSetting(), queryCartridgeState(), reset(), sisPol0Sb1Voltage(), sisPol0Sb2Voltage(), sisPol1Sb1Voltage(), and sisPol1Sb2Voltage().
The documentation for this class was generated from the following files:
ColdCartImpl.h
ColdCartImpl.cpp