FrontEndControl2: FEConfig::ConfigManager Class Reference
FEConfig::ConfigManager Class Reference
ConfigManager uses a ConfigProvider load config parameters into a target FrontEndImpl or SignalSourceImpl.
#include <ConfigManager.h>
Public Member Functions
ConfigManager (const ConfigProvider &provider)
construct with a reference to the ConfigProvider to use.
~ConfigManager ()
bool configure (const Configuration &config, FrontEndImpl &target) const
Apply the given Configuration to the target FrontEndImpl object.
bool configure (unsigned keyFacility, unsigned configId, FrontEndImpl &target) const
load the config identified by (keyFacility, configId) into the target FrontEndImpl object.
bool configure (const Configuration &config, SignalSourceImpl &target) const
Apply the given Configuration to the target SignalSourceImpl object.
bool configure (unsigned keyFacility, unsigned configId, SignalSourceImpl &target) const
load the config identified by (keyFacility, configId) into the target SignalSourceImpl object.
Private Member Functions
ConfigManager (const ConfigManager &other)
copy construct is private and forbidden.
ConfigManager & operator= (const ConfigManager &other)
assignment is private and forbidden.
bool configureCryostat (const CryostatConfig &cryo, FrontEndImpl &target) const
helper to apply a CryostatConfig to the target.
bool configureLPR (const LPRConfig &lpr, FrontEndImpl &target) const
helper to apply a LPRConfig to the target.
bool configureCartAssembly (const CartAssemblyConfig &cartAssy, FrontEndImpl &target) const
bool configureCartAssembly (const CartAssemblyConfig &cartAssy, SignalSourceImpl &target) const
helpers to apply a CartAssemblyConfig to the target.
bool configureColdCart (unsigned keyFacility, const ColdCartConfig &coldCart, FrontEndImpl &target) const
helper to apply a ColdCartConfig to the target.
bool configureWCA (unsigned keyFacility, const WCAConfig &WCA, FrontEndImpl &target) const
bool configureWCA (unsigned port, const WCAConfig &wcaConfig, SignalSourceImpl &target) const
helpers to apply a WCAConfig to the target.
Private Attributes
const ConfigProvider & provider_m
reference to the provider given when constructed.
Detailed Description
ConfigManager uses a ConfigProvider load config parameters into a target FrontEndImpl or SignalSourceImpl.
Definition at line 33 of file ConfigManager.h.
Constructor & Destructor Documentation
FEConfig::ConfigManager::ConfigManager (const ConfigProvider & provider) inline
construct with a reference to the ConfigProvider to use.
Definition at line 35 of file ConfigManager.h.
FEConfig::ConfigManager::~ConfigManager () inline
Definition at line 39 of file ConfigManager.h.
FEConfig::ConfigManager::ConfigManager (const ConfigManager & other) private
copy construct is private and forbidden.
Member Function Documentation
bool FEConfig::ConfigManager::configure (const Configuration & config, FrontEndImpl & target) const
Apply the given Configuration to the target FrontEndImpl object.
returns true if no error.
Definition at line 31 of file ConfigManager.cpp.
References FrontEndImpl::addCPDS(), FrontEndImpl::addCryostat(), FrontEndImpl::addFETIM(), FrontEndImpl::addIFSwitch(), FrontEndImpl::addLPR(), FEConfig::Configuration::getCartAssemblyConfig(), FEConfig::Configuration::getFrontEndConfig(), and FrontEndImpl::setFrontEndSN().
Referenced by FELoadConfiguration(), and sigSrcLoadConfiguration().
bool FEConfig::ConfigManager::configure (unsigned keyFacility, unsigned configId, FrontEndImpl & target) const
load the config identified by (keyFacility, configId) into the target FrontEndImpl object.
returns true if the specified configuration was found and loaded. False on otherwise or on error.
Definition at line 87 of file ConfigManager.cpp.
References FEConfig::Configuration::getDescription(), and FEConfig::Configuration::load().
bool FEConfig::ConfigManager::configure (const Configuration & config, SignalSourceImpl & target) const
Apply the given Configuration to the target SignalSourceImpl object.
returns true if no error.
Definition at line 97 of file ConfigManager.cpp.
References FEConfig::Configuration::getCartAssemblyConfig().
bool FEConfig::ConfigManager::configure (unsigned keyFacility, unsigned configId, SignalSourceImpl & target) const
load the config identified by (keyFacility, configId) into the target SignalSourceImpl object.
returns true if the specified configuration was found and loaded. False on otherwise or on error.
Definition at line 109 of file ConfigManager.cpp.
References FEConfig::Configuration::getDescription(), and FEConfig::Configuration::load().
bool FEConfig::ConfigManager::configureCartAssembly (const CartAssemblyConfig & cartAssy, FrontEndImpl & target) const private
Definition at line 131 of file ConfigManager.cpp.
References FEConfig::CartAssemblyConfig::coldCart_m, FEConfig::CartAssemblyConfig::Id_m, FEConfig::CartAssemblyID::port_m, and FEConfig::CartAssemblyConfig::WCA_m.
bool FEConfig::ConfigManager::configureCartAssembly (const CartAssemblyConfig & cartAssy, SignalSourceImpl & target) const private
helpers to apply a CartAssemblyConfig to the target.
Definition at line 143 of file ConfigManager.cpp.
References FEConfig::CartAssemblyConfig::Id_m, FEConfig::CartAssemblyID::port_m, and FEConfig::CartAssemblyConfig::WCA_m.
bool FEConfig::ConfigManager::configureColdCart (unsigned keyFacility, const ColdCartConfig & coldCart, FrontEndImpl & target) const private
helper to apply a ColdCartConfig to the target.
Definition at line 155 of file ConfigManager.cpp.
References FrontEndImpl::setColdCartConfig().
bool FEConfig::ConfigManager::configureCryostat (const CryostatConfig & cryo, FrontEndImpl & target) const private
helper to apply a CryostatConfig to the target.
Definition at line 119 of file ConfigManager.cpp.
References FEConfig::CryostatConfig::keyCryostat_m, and FEConfig::CryostatConfig::keyFacility_m.
bool FEConfig::ConfigManager::configureLPR (const LPRConfig & lpr, FrontEndImpl & target) const private
helper to apply a LPRConfig to the target.
Definition at line 125 of file ConfigManager.cpp.
References FEConfig::LPRConfig::keyFacility_m, and FEConfig::LPRConfig::keyLPR_m.
bool FEConfig::ConfigManager::configureWCA (unsigned keyFacility, const WCAConfig & WCA, FrontEndImpl & target) const private
Definition at line 159 of file ConfigManager.cpp.
References FrontEndImpl::setWCAConfig().
bool FEConfig::ConfigManager::configureWCA (unsigned port, const WCAConfig & wcaConfig, SignalSourceImpl & target) const private
helpers to apply a WCAConfig to the target.
Definition at line 163 of file ConfigManager.cpp.
References SignalSourceImpl::setWCAConfig().
ConfigManager& FEConfig::ConfigManager::operator= (const ConfigManager & other) private
assignment is private and forbidden.
Member Data Documentation
const ConfigProvider& FEConfig::ConfigManager::provider_m private
reference to the provider given when constructed.
Definition at line 79 of file ConfigManager.h.
The documentation for this class was generated from the following files:
CONFIG/ConfigManager.h
CONFIG/ConfigManager.cpp