FrontEndControl2: MixerDeflux Class Reference
MixerDeflux Class Reference
#include <MixerDeflux.h>
Public Member Functions
MixerDeflux (CartAssembly &ca, XYPlotArray &target)
virtual ~MixerDeflux ()
void reset ()
reset all state to initial/just constructed.
bool start (int pol)
Public Member Functions inherited from OptimizeBase
OptimizeBase (const char *name="")
construct with an object name to use for logging
virtual ~OptimizeBase ()
destructor forces worker thread to stop.
bool busy () const
true if the thread was started and it has not finished or or been stopped.
bool finished () const
true if setFinished() has been called by the derived class' optimizeAction()
bool success () const
true if setFinished(success=true) has been called by the derived class' optimizeAction()
virtual void requestStop ()
main thread can call this to request worker thread to stop.
bool stopRequested () const
main or worker thread can use this to check whether the thread has been told to stop.
Protected Member Functions
virtual void optimizeAction ()
derived classes must declare an optimizeAction method for the worker thread to call.
Protected Member Functions inherited from OptimizeBase
bool startWorkerThread ()
start the worker thread. Call from derived class after all preconditions are set.
virtual void exitAction (bool success)
derived classes may declare an exitAction which gets called just prior to the thread exiting.
void setFinished (bool success=true)
derived class calls to report that the optimization procedure is finished.
void setEvent (short eventCode, short band=0, short pol=-1, short param=0, short progress=0, const std::string &message=std::string())
send an event to the client via the FEMCEventQueue.
void setStatusMessage (bool success, const std::string &message)
send a status message event to the client via FEMCEventQueue
void setProgress (short progress)
helper for reporting progress.
Private Member Functions
void demagnetize (int pol, int sb)
void goToMagnetCurrent (int pol, int sb, float IMag)
void mixerHeating (int pol, int sb)
void readData (int pol, int sb, bool printHeader=false)
Private Attributes
CartAssembly & ca_m
cart assembly to demagnetize
ColdCartImpl * cca_m
cold cartridge in the cart assembly
WCAImpl * wca_m
optional WCA in the cart assembly
int pol_m
which pol to demagnetize. -1 means both pols
float IMagMax_m
maximum magnet current for the demag operating
float IMag_m
instantaneous magnet current
unsigned stepSleep_m
wait this long between setting and reading the magnet current.
float stepSize_m
how much less we swing the magnet current at each step.
bool band5sweepMode_m
true for band 5, special sweeping mode.
float VDNom0_m
Cache the prior/nominal LO PA drain voltage settings.
float VDNom1_m
float VJNom01_m
Cache the prior/nominal junction voltage settings.
float VJNom02_m
float VJNom11_m
float VJNom12_m
float IMagNom01_m
Cache the prior/nominal magnet current settings.
float IMagNom02_m
float IMagNom11_m
float IMagNom12_m
float progress_m
Progress bar value varies from 0 to 100%.
float progressIncrement_m
Step size for progress bar.
unsigned long timerStart_m
Timer when operation started, for logging.
XYPlotArray & data_m
Output data array.
std::ostream * dataFile_mp
output data log file
Additional Inherited Members
Protected Attributes inherited from OptimizeBase
const std::string & logDir_m
directory to use for logs and results files.
struct OptimizeBase::optimizeData data_m
single instance of shared data structure.
Detailed Description
Definition at line 33 of file MixerDeflux.h.
Constructor & Destructor Documentation
MixerDeflux::MixerDeflux (CartAssembly & ca, XYPlotArray & target) inline
Definition at line 35 of file MixerDeflux.h.
References reset().
virtual MixerDeflux::~MixerDeflux () inline virtual
Definition at line 44 of file MixerDeflux.h.
Member Function Documentation
void MixerDeflux::demagnetize (int pol, int sb) private
Definition at line 291 of file MixerDeflux.cpp.
void MixerDeflux::goToMagnetCurrent (int pol, int sb, float IMag) private
Definition at line 320 of file MixerDeflux.cpp.
void MixerDeflux::mixerHeating (int pol, int sb) private
void MixerDeflux::optimizeAction () protected virtual
derived classes must declare an optimizeAction method for the worker thread to call.
Implements OptimizeBase.
Definition at line 129 of file MixerDeflux.cpp.
References FEMCEventQueue::EVENT_OPTIMIZE_DONE.
void MixerDeflux::readData (int pol, int sb, bool printHeader = false) private
Definition at line 341 of file MixerDeflux.cpp.
void MixerDeflux::reset ()
reset all state to initial/just constructed.
Definition at line 30 of file MixerDeflux.cpp.
Referenced by MixerDeflux().
bool MixerDeflux::start (int pol)
Definition at line 50 of file MixerDeflux.cpp.
References OptimizeBase::startWorkerThread().
Member Data Documentation
bool MixerDeflux::band5sweepMode_m private
true for band 5, special sweeping mode.
Definition at line 69 of file MixerDeflux.h.
CartAssembly& MixerDeflux::ca_m private
cart assembly to demagnetize
Definition at line 61 of file MixerDeflux.h.
ColdCartImpl* MixerDeflux::cca_m private
cold cartridge in the cart assembly
Definition at line 62 of file MixerDeflux.h.
XYPlotArray& MixerDeflux::data_m private
Output data array.
Definition at line 83 of file MixerDeflux.h.
std::ostream* MixerDeflux::dataFile_mp private
output data log file
Definition at line 84 of file MixerDeflux.h.
float MixerDeflux::IMag_m private
instantaneous magnet current
Definition at line 66 of file MixerDeflux.h.
float MixerDeflux::IMagMax_m private
maximum magnet current for the demag operating
Definition at line 65 of file MixerDeflux.h.
float MixerDeflux::IMagNom01_m private
Cache the prior/nominal magnet current settings.
Definition at line 76 of file MixerDeflux.h.
float MixerDeflux::IMagNom02_m private
Definition at line 77 of file MixerDeflux.h.
float MixerDeflux::IMagNom11_m private
Definition at line 78 of file MixerDeflux.h.
float MixerDeflux::IMagNom12_m private
Definition at line 79 of file MixerDeflux.h.
int MixerDeflux::pol_m private
which pol to demagnetize. -1 means both pols
Definition at line 64 of file MixerDeflux.h.
float MixerDeflux::progress_m private
Progress bar value varies from 0 to 100%.
Definition at line 80 of file MixerDeflux.h.
float MixerDeflux::progressIncrement_m private
Step size for progress bar.
Definition at line 81 of file MixerDeflux.h.
float MixerDeflux::stepSize_m private
how much less we swing the magnet current at each step.
Definition at line 68 of file MixerDeflux.h.
unsigned MixerDeflux::stepSleep_m private
wait this long between setting and reading the magnet current.
Definition at line 67 of file MixerDeflux.h.
unsigned long MixerDeflux::timerStart_m private
Timer when operation started, for logging.
Definition at line 82 of file MixerDeflux.h.
float MixerDeflux::VDNom0_m private
Cache the prior/nominal LO PA drain voltage settings.
Definition at line 70 of file MixerDeflux.h.
float MixerDeflux::VDNom1_m private
Definition at line 71 of file MixerDeflux.h.
float MixerDeflux::VJNom01_m private
Cache the prior/nominal junction voltage settings.
Definition at line 72 of file MixerDeflux.h.
float MixerDeflux::VJNom02_m private
Definition at line 73 of file MixerDeflux.h.
float MixerDeflux::VJNom11_m private
Definition at line 74 of file MixerDeflux.h.
float MixerDeflux::VJNom12_m private
Definition at line 75 of file MixerDeflux.h.
WCAImpl* MixerDeflux::wca_m private
optional WCA in the cart assembly
Definition at line 63 of file MixerDeflux.h.
The documentation for this class was generated from the following files:
OPTIMIZE/MixerDeflux.h
OPTIMIZE/MixerDeflux.cpp