FrontEndControl2: FEHardwareDevice Class Reference
FEHardwareDevice Class Reference abstract
FEHardwareDevice is a base class common to all front end ImplBase classes.
#include <FEHardwareDevice.h>
Classes
class LogInterface
declare an interface for CAN transaction logging.
Public Types
enum FEMC_ERROR {
FEMC_NO_ERROR = 0, FEMC_GENERIC_ERROR = -1, FEMC_HARDW_RANGE_ERR = -2, FEMC_HARDW_BLOCKED_ERR = -3,
FEMC_HARDW_UPDATE_WARN = -4, FEMC_HARDW_CONVERT_ERR = -5, FEMC_HARDW_RETRY_WARN = -6, FEMC_MON_ERROR_RANGE = -10,
FEMC_MON_WARN_RANGE = -11, FEMC_UNDEFINED_RCA = -12, FEMC_MON_ERROR_ACTION = -13, FEMC_MON_WARN_ACTION = -14,
FEMC_MON_NOTIMPL = -15, FEMC_LAST_ERROR_CODE = -31, FEMC_AMB_ERROR = -44, FEMC_UNPACK_ERROR = -45,
FEMC_NOT_CONNECTED = -46
}
Error codes defined by the FEMC firmware and by this module.
enum Transaction_t {
FEMC_LOG_NONE = 0, FEMC_LOG_CHECKPOINT = 10, FEMC_LOG_MONITOR = 11, FEMC_LOG_COMMAND = 12,
FEMC_LOG_COMMAND_READBACK = 13
}
types of device transactions which may be logged.
Public Member Functions
FEHardwareDevice (const std::string &name)
construct with the device name to pass down to AmbDeviceImpl.
virtual ~FEHardwareDevice ()
void setESN (const std::string &esn)
set the Electronic Serial Number
const std::string & getESN () const
get the Electronic Serial Number
bool valueIgnorableError (FEMC_ERROR &err)
returns true if the data associated with the error can perhaps be used anyway.
bool monitorIgnorableError (FEMC_ERROR &err)
returns true this error should not contribute to the monitor thread errorCount.
virtual void startMonitor ()
start the monitor thread.
virtual void stopMonitor ()
stop the monitor thread.
void pauseMonitor (bool pause, const char *reason=NULL)
pause/resume the monitor thread.
void minimalMonitor (bool minimal, const char *reason=NULL)
reduce monitoring to the minimum if true.
LogInterface & getLogger ()
get a reference to the current logger
Static Public Member Functions
static void randomizeAnalogMonitors (bool doRandomize)
enable/disable randomized order for analog monitor points.
static void logMonitors (bool doLog)
enable/disable continuous logging of monitor points for all devices.
static void logAmbErrors (bool doLog)
enable/disable logging of CAN bus error messages.
static void setLogger (LogInterface &logger)
Set the logger object to use.
static void clearLogger ()
Set the logger object to use.
static void setMaxMonitorErrors (unsigned max)
Static Public Attributes
static const char * TransactionText []
a string corresponding to each TRANSACTION_TYPE.
Protected Member Functions
FEMC_ERROR syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string &target)
Monitor a three-byte software version number and return a string.
FEMC_ERROR syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string &target, bool reverseBytes=false)
Monitor an eight-byte ESN and return a string.
template<typename T >
FEMC_ERROR syncMonitor (AmbRelativeAddr RCA, T &target, sem_t &synchLock)
Synchronous monitor of any type supported with an unpack() function.
template<typename T >
FEMC_ERROR syncMonitorWithRetry (AmbRelativeAddr RCA, T &target, int retries=12)
Synchronous monitor with retries of any type supported with an unpack() function.
FEMC_ERROR syncMonitorAverage (AmbRelativeAddr RCA, float &target, int average)
Synchronous monitor a float with averaging.
template<typename T >
FEMC_ERROR syncCommand (AmbRelativeAddr RCA, T value)
Template function to perform a pair of command/readback transactions at the given RCA.
virtual void monitorAction (Time *timestamp_p)=0
derived classes must declare a monitorAction method for the monitor thread to call.
Static Protected Member Functions
static FEMC_ERROR unpack (unsigned long &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
static void pack (unsigned long value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned long into a CAN payload.
static FEMC_ERROR unpack (unsigned short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
static void pack (unsigned short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned short into a CAN payload.
static FEMC_ERROR unpack (short &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
static void pack (short value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a signed short into a 2s complement CAN payload.
static FEMC_ERROR unpack (unsigned char &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
static void pack (unsigned char value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an unsigned char into a CAN payload.
static FEMC_ERROR unpack (bool &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
static void pack (bool value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack an bool into a CAN payload as unsigned char.
static FEMC_ERROR unpack (float &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into a float. Return value is the FEStatus byte.
static void pack (float value, AmbDataLength_t &dataLength, AmbDataMem_t *data)
pack a float into a CAN payload.
static FEMC_ERROR unpack (std::string &target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
static FEMC_ERROR unpack (AmbDataMem_t *target, AmbDataLength_t dataLength, const AmbDataMem_t *data)
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Protected Attributes
unsigned errorCount
count of errors seen by the monitor thread since started/unpaused.
bool minimalMonitoring_m
true if only the bare minimum monitoring should be performed.
Static Protected Attributes
static unsigned maxErrorCount
global maximum error count before the thread is paused.
static bool randomizeAnalogMonitors_m
true if the analog monitoring should be done in randomized order.
static bool logMonitors_m
true if analog monitor points should be continuously dumped to the log.
static bool logAmbErrors_m
true if AMB errors should be logged.
Private Member Functions
FEHardwareDevice (const FEHardwareDevice &other)
forbid copy construct.
Static Private Member Functions
static void * monitorThread (FEHardwareDevice *dev)
the monitor thread runner function. Calls derived class' monitorAction().
Private Attributes
bool running
true if the monitor thread should continue to run.
bool paused
true if the monitor thread is paused.
std::string ESN_m
Storage for the device ESN.
pthread_t thread_m
the monitor thread handle.
bool stopped
true when the monitor thread has stopped and may be destroyed.
Static Private Attributes
static LogInterface defaultLogger_m
a do-nothing transaction logger which dumps all messages.
static LogInterface * logger_mp
the interface to use for all transaction logging.
Detailed Description
FEHardwareDevice is a base class common to all front end ImplBase classes.
It provides CAN message packing and unpacking services, synchronous monitor and control, and a monitor thread for each device.
Definition at line 32 of file FEHardwareDevice.h.
Member Enumeration Documentation
enum FEHardwareDevice::FEMC_ERROR
Error codes defined by the FEMC firmware and by this module.
Enumerator
FEMC_NO_ERROR
No error during the monitor operation.
FEMC_GENERIC_ERROR
Error during the monitor operation. FEMC failed to communicate with hardware.
FEMC_HARDW_RANGE_ERR
The addressed hardware is not installed.
FEMC_HARDW_BLOCKED_ERR
The hardware cannot be accessed because of operational state.
FEMC_HARDW_UPDATE_WARN
Properties of the addressed hardware need to be updated in firmware. Result may be suspect.
FEMC_HARDW_CONVERT_ERR
Monitor data is out of range for conversion to proper units.
FEMC_HARDW_RETRY_WARN
The monitor point takes time to stabilize. Retry the request immediately.
FEMC_MON_ERROR_RANGE
The monitor value is in the error range, according to the configuration database.
FEMC_MON_WARN_RANGE
The monitor value is in the warning range, according to the configuration database.
FEMC_UNDEFINED_RCA
The monitor request is to an undefined RCA.
FEMC_MON_ERROR_ACTION
FEMC took action because the monitor value is in the error range.
FEMC_MON_WARN_ACTION
FEMC took action because the monitor value is in the warning range.
FEMC_MON_NOTIMPL
The monitor request is not yet implemented in hardware. Result may be suspect.
FEMC_LAST_ERROR_CODE
We assume that this is the largest negative number the FEMC will return as a status byte.
FEMC_AMB_ERROR
The AMB subsystem reported an error.
FEMC_UNPACK_ERROR
Unpacking monitor data failed.
FEMC_NOT_CONNECTED
Cannot monitor because not connected to FE.
Definition at line 47 of file FEHardwareDevice.h.
enum FEHardwareDevice::Transaction_t
types of device transactions which may be logged.
Enumerator
FEMC_LOG_NONE
FEMC_LOG_CHECKPOINT
FEMC_LOG_MONITOR
FEMC_LOG_COMMAND
FEMC_LOG_COMMAND_READBACK
Definition at line 101 of file FEHardwareDevice.h.
Constructor & Destructor Documentation
FEHardwareDevice::FEHardwareDevice (const std::string & name)
construct with the device name to pass down to AmbDeviceImpl.
Definition at line 15 of file FEHardwareDevice.cpp.
FEHardwareDevice::~FEHardwareDevice () virtual
Definition at line 25 of file FEHardwareDevice.cpp.
References stopMonitor().
FEHardwareDevice::FEHardwareDevice (const FEHardwareDevice & other) private
forbid copy construct.
Member Function Documentation
static void FEHardwareDevice::clearLogger () inline static
Set the logger object to use.
Definition at line 141 of file FEHardwareDevice.h.
References logger_mp.
Referenced by LVWrapperShutdown().
const std::string& FEHardwareDevice::getESN () const inline
get the Electronic Serial Number
Definition at line 42 of file FEHardwareDevice.h.
References ESN_m.
LogInterface& FEHardwareDevice::getLogger () inline
get a reference to the current logger
Definition at line 145 of file FEHardwareDevice.h.
References defaultLogger_m, and logger_mp.
Referenced by LORTMImplBase::PhaselockGetStatus(), FrontEndImplBase::powerEnableModule(), and LORTMImplBase::SystemGetStatus().
static void FEHardwareDevice::logAmbErrors (bool doLog) inline static
enable/disable logging of CAN bus error messages.
Definition at line 94 of file FEHardwareDevice.h.
References logAmbErrors_m.
Referenced by FEControlInit().
static void FEHardwareDevice::logMonitors (bool doLog) inline static
enable/disable continuous logging of monitor points for all devices.
Definition at line 91 of file FEHardwareDevice.h.
References logMonitors_m.
Referenced by FEControlInit().
void FEHardwareDevice::minimalMonitor (bool minimal, const char * reason = NULL)
reduce monitoring to the minimum if true.
Definition at line 64 of file FEHardwareDevice.cpp.
References minimalMonitoring_m.
virtual void FEHardwareDevice::monitorAction (Time * timestamp_p) protected pure virtual
derived classes must declare a monitorAction method for the monitor thread to call.
Implemented in ColdCartImplBase, LORTMImplBase, WCAImplBase, CryostatImplBase, FETIMImplBase, CompressorImplBase, IFSwitchImplBase, FrontEndImplBase, PowerModuleImplBase, and LPRImplBase.
Referenced by monitorThread().
bool FEHardwareDevice::monitorIgnorableError (FEMC_ERROR & err) inline
returns true this error should not contribute to the monitor thread errorCount.
Definition at line 74 of file FEHardwareDevice.h.
References FEMC_HARDW_BLOCKED_ERR, and valueIgnorableError().
Referenced by syncMonitor().
void * FEHardwareDevice::monitorThread (FEHardwareDevice * dev) static private
the monitor thread runner function. Calls derived class' monitorAction().
Definition at line 347 of file FEHardwareDevice.cpp.
References errorCount, maxErrorCount, monitorAction(), paused, pauseMonitor(), running, and stopped.
Referenced by startMonitor().
void FEHardwareDevice::pack (unsigned long value, AmbDataLength_t & dataLength, AmbDataMem_t * data) static protected
pack an unsigned long into a CAN payload.
Definition at line 116 of file FEHardwareDevice.cpp.
References AmbULConv::chr_val, and AmbULConv::long_val.
Referenced by pack(), FrontEndImplBase::setFEMode(), FrontEndImplBase::specialExitProgram(), FrontEndImplBase::specialReadESNs(), and syncCommand().
void FEHardwareDevice::pack (unsigned short value, AmbDataLength_t & dataLength, AmbDataMem_t * data) static protected
pack an unsigned short into a CAN payload.
Definition at line 142 of file FEHardwareDevice.cpp.
void FEHardwareDevice::pack (short value, AmbDataLength_t & dataLength, AmbDataMem_t * data) static protected
pack a signed short into a 2s complement CAN payload.
Definition at line 175 of file FEHardwareDevice.cpp.
void FEHardwareDevice::pack (unsigned char value, AmbDataLength_t & dataLength, AmbDataMem_t * data) static protected
pack an unsigned char into a CAN payload.
Definition at line 212 of file FEHardwareDevice.cpp.
static void FEHardwareDevice::pack (bool value, AmbDataLength_t & dataLength, AmbDataMem_t * data) inline static protected
pack an bool into a CAN payload as unsigned char.
Definition at line 183 of file FEHardwareDevice.h.
References pack().
void FEHardwareDevice::pack (float value, AmbDataLength_t & dataLength, AmbDataMem_t * data) static protected
pack a float into a CAN payload.
Definition at line 243 of file FEHardwareDevice.cpp.
References AmbFloatConv::chr_val, and AmbFloatConv::flt_val.
void FEHardwareDevice::pauseMonitor (bool pause, const char * reason = NULL)
pause/resume the monitor thread.
Definition at line 54 of file FEHardwareDevice.cpp.
References errorCount, and paused.
Referenced by SignalSourceImpl::cartPauseMonitor(), FrontEndImpl::cartPauseMonitor(), monitorThread(), and CartHealthCheck::optimizeAction().
static void FEHardwareDevice::randomizeAnalogMonitors (bool doRandomize) inline static
enable/disable randomized order for analog monitor points.
Definition at line 88 of file FEHardwareDevice.h.
References randomizeAnalogMonitors_m.
Referenced by FEControlInit(), and randomizeAnalogMonitors().
void FEHardwareDevice::setESN (const std::string & esn) inline
set the Electronic Serial Number
Definition at line 38 of file FEHardwareDevice.h.
References ESN_m.
Referenced by ColdCartImpl::ColdCartImpl(), CryostatImpl::CryostatImpl(), FETIMImpl::FETIMImpl(), FrontEndImpl::FrontEndImpl(), LPRImpl::LPRImpl(), SignalSourceImpl::SignalSourceImpl(), and WCAImpl::WCAImpl().
static void FEHardwareDevice::setLogger (LogInterface & logger) inline static
Set the logger object to use.
Definition at line 137 of file FEHardwareDevice.h.
References logger_mp.
Referenced by LVWrapperInit().
static void FEHardwareDevice::setMaxMonitorErrors (unsigned max) inline static
Definition at line 149 of file FEHardwareDevice.h.
References maxErrorCount.
Referenced by LVWrapperInit().
void FEHardwareDevice::startMonitor () virtual
start the monitor thread.
Reimplemented in FrontEndImpl, SignalSourceImpl, and CompressorImpl.
Definition at line 31 of file FEHardwareDevice.cpp.
References errorCount, monitorThread(), running, and thread_m.
Referenced by CompressorImpl::startMonitor(), SignalSourceImpl::startMonitor(), and FrontEndImpl::startMonitor().
void FEHardwareDevice::stopMonitor () virtual
stop the monitor thread.
Reimplemented in FrontEndImpl, SignalSourceImpl, and CompressorImpl.
Definition at line 41 of file FEHardwareDevice.cpp.
References running, and stopped.
Referenced by CompressorImpl::stopMonitor(), FrontEndImpl::stopMonitor(), and ~FEHardwareDevice().
template<typename T > FEMC_ERROR FEHardwareDevice::syncCommand (AmbRelativeAddr RCA, T value) inline protected
Template function to perform a pair of command/readback transactions at the given RCA.
The 'value' is sent as the payload. FEStatus receives the status byte from the readback. pack(T, AmbDataLength_t&, AmbDataMem_t*) must be defined for T.
Definition at line 266 of file FEHardwareDevice.h.
References FEMC_NO_ERROR, pack(), and unpack().
Referenced by FrontEndImplBase::powerEnableModule().
template<typename T > FEMC_ERROR FEHardwareDevice::syncMonitor (AmbRelativeAddr RCA, T & target, sem_t & synchLock) inline protected
Synchronous monitor of any type supported with an unpack() function.
synchLock must be initialized before and destroyed after calling.
Definition at line 211 of file FEHardwareDevice.h.
References errorCount, FEMC_AMB_ERROR, FEMC_NO_ERROR, logAmbErrors_m, monitorIgnorableError(), and unpack().
Referenced by CryostatImplBase::CryostatMonitorTempsensor(), FrontEndImplBase::powerEnableModule(), syncMonitorAverage(), and syncMonitorWithRetry().
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::syncMonitorAverage (AmbRelativeAddr RCA, float & target, int average) protected
Synchronous monitor a float with averaging.
Definition at line 317 of file FEHardwareDevice.cpp.
References FEMC_AMB_ERROR, FEMC_NO_ERROR, and syncMonitor().
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::syncMonitorEightByteESN (AmbRelativeAddr RCA, std::string & target, bool reverseBytes = false) protected
Monitor an eight-byte ESN and return a string.
Definition at line 291 of file FEHardwareDevice.cpp.
References FEMC_NO_ERROR, and FEMC_UNPACK_ERROR.
Referenced by AMBSIHardwareDevice::AMBSISerialNum(), FrontEndImplBase::FEMCGetNextESN(), and LORTMImplBase::GetSerialNumber().
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::syncMonitorThreeByteRevLevel (AmbRelativeAddr RCA, std::string & target) protected
Monitor a three-byte software version number and return a string.
Definition at line 271 of file FEHardwareDevice.cpp.
References FEMC_NO_ERROR, and FEMC_UNPACK_ERROR.
Referenced by AMBSIHardwareDevice::AMBSIFirmwareRev(), FrontEndImplBase::AMBSILibraryVersion(), FrontEndImplBase::FEMCFirmwareVersion(), FrontEndImplBase::FEMCFPGAVersion(), and CompressorImplBase::getSWRevisionLevel().
template<typename T > FEMC_ERROR FEHardwareDevice::syncMonitorWithRetry (AmbRelativeAddr RCA, T & target, int retries = 12) inline protected
Synchronous monitor with retries of any type supported with an unpack() function.
Definition at line 237 of file FEHardwareDevice.h.
References FEMC_AMB_ERROR, FEMC_HARDW_RETRY_WARN, FEMC_NO_ERROR, and syncMonitor().
Referenced by WCAImpl::queryCartridgeState(), and ColdCartImpl::queryCartridgeState().
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::unpack (unsigned long & target, AmbDataLength_t dataLength, const AmbDataMem_t * data) static protected
unpack a CAN payload into an unsigned long. Return value is the FEStatus byte.
Definition at line 100 of file FEHardwareDevice.cpp.
References FEMC_NO_ERROR, and FEMC_UNPACK_ERROR.
Referenced by AMBSIHardwareDevice::AMBSINumErrors(), LORTMImplBase::AMBSINumErrors(), AMBSIHardwareDevice::AMBSINumTransactions(), LORTMImplBase::AMBSINumTransactions(), LORTMImplBase::PhaselockGetStatus(), FrontEndImplBase::specialGetSetupInfo(), syncCommand(), syncMonitor(), LORTMImplBase::SystemGetStatus(), and unpack().
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::unpack (unsigned short & target, AmbDataLength_t dataLength, const AmbDataMem_t * data) static protected
unpack a CAN payload into an unsigned short. Return value is the FEStatus byte.
Definition at line 128 of file FEHardwareDevice.cpp.
References FEMC_NO_ERROR, and FEMC_UNPACK_ERROR.
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::unpack (short & target, AmbDataLength_t dataLength, const AmbDataMem_t * data) static protected
unpack a 2s complement CAN payload into a signed short. Return value is the FEStatus byte.
Definition at line 150 of file FEHardwareDevice.cpp.
References FEMC_NO_ERROR, and FEMC_UNPACK_ERROR.
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::unpack (unsigned char & target, AmbDataLength_t dataLength, const AmbDataMem_t * data) static protected
unpack a CAN payload into an unsigned char. Return value is the FEStatus byte.
Definition at line 191 of file FEHardwareDevice.cpp.
References FEMC_LAST_ERROR_CODE, FEMC_NO_ERROR, and FEMC_UNPACK_ERROR.
static FEMC_ERROR FEHardwareDevice::unpack (bool & target, AmbDataLength_t dataLength, const AmbDataMem_t * data) inline static protected
unpack an unsigned char CAN payload into a bool. Return value is the FEStatus byte.
Definition at line 176 of file FEHardwareDevice.h.
References unpack().
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::unpack (float & target, AmbDataLength_t dataLength, const AmbDataMem_t * data) static protected
unpack a CAN payload into a float. Return value is the FEStatus byte.
Definition at line 224 of file FEHardwareDevice.cpp.
References AmbFloatConv::chr_val, FEMC_NO_ERROR, FEMC_UNPACK_ERROR, and AmbFloatConv::flt_val.
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::unpack (std::string & target, AmbDataLength_t dataLength, const AmbDataMem_t * data) static protected
unpack a CAN payload into an std::string. Return value is the FEStatus byte.
Definition at line 256 of file FEHardwareDevice.cpp.
References FEMC_NO_ERROR.
FEHardwareDevice::FEMC_ERROR FEHardwareDevice::unpack (AmbDataMem_t * target, AmbDataLength_t dataLength, const AmbDataMem_t * data) static protected
copy a CAN payload into an array of bytes. Returns FEMC_UNPACK_ERROR on error, else FEMC_NO_ERROR.
Definition at line 264 of file FEHardwareDevice.cpp.
References FEMC_NO_ERROR, and FEMC_UNPACK_ERROR.
bool FEHardwareDevice::valueIgnorableError (FEMC_ERROR & err) inline
returns true if the data associated with the error can perhaps be used anyway.
Definition at line 70 of file FEHardwareDevice.h.
References FEMC_HARDW_RETRY_WARN, FEMC_HARDW_UPDATE_WARN, and FEMC_NO_ERROR.
Referenced by monitorIgnorableError().
Member Data Documentation
FEHardwareDevice::LogInterface FEHardwareDevice::defaultLogger_m static private
a do-nothing transaction logger which dumps all messages.
Definition at line 311 of file FEHardwareDevice.h.
Referenced by getLogger().
unsigned FEHardwareDevice::errorCount protected
count of errors seen by the monitor thread since started/unpaused.
Definition at line 292 of file FEHardwareDevice.h.
Referenced by monitorThread(), pauseMonitor(), startMonitor(), and syncMonitor().
std::string FEHardwareDevice::ESN_m private
Storage for the device ESN.
Definition at line 308 of file FEHardwareDevice.h.
Referenced by getESN(), and setESN().
bool FEHardwareDevice::logAmbErrors_m static protected
true if AMB errors should be logged.
Definition at line 299 of file FEHardwareDevice.h.
Referenced by logAmbErrors(), and syncMonitor().
FEHardwareDevice::LogInterface * FEHardwareDevice::logger_mp static private
the interface to use for all transaction logging.
Definition at line 314 of file FEHardwareDevice.h.
Referenced by clearLogger(), getLogger(), and setLogger().
bool FEHardwareDevice::logMonitors_m static protected
true if analog monitor points should be continuously dumped to the log.
Definition at line 298 of file FEHardwareDevice.h.
Referenced by logMonitors(), LPRImplBase::monitorAction(), PowerModuleImplBase::monitorAction(), IFSwitchImplBase::monitorAction(), FETIMImplBase::monitorAction(), CryostatImplBase::monitorAction(), WCAImplBase::monitorAction(), and ColdCartImplBase::monitorAction().
unsigned FEHardwareDevice::maxErrorCount static protected
global maximum error count before the thread is paused.
Definition at line 293 of file FEHardwareDevice.h.
Referenced by monitorThread(), and setMaxMonitorErrors().
bool FEHardwareDevice::minimalMonitoring_m protected
true if only the bare minimum monitoring should be performed.
Definition at line 296 of file FEHardwareDevice.h.
Referenced by WCAImpl::getMonitorPLL(), minimalMonitor(), and WCAImplBase::monitorAction().
bool FEHardwareDevice::paused private
true if the monitor thread is paused.
Definition at line 303 of file FEHardwareDevice.h.
Referenced by monitorThread(), and pauseMonitor().
bool FEHardwareDevice::randomizeAnalogMonitors_m static protected
true if the analog monitoring should be done in randomized order.
Definition at line 297 of file FEHardwareDevice.h.
Referenced by LPRImplBase::monitorAction(), PowerModuleImplBase::monitorAction(), IFSwitchImplBase::monitorAction(), FETIMImplBase::monitorAction(), CryostatImplBase::monitorAction(), WCAImplBase::monitorAction(), ColdCartImplBase::monitorAction(), and randomizeAnalogMonitors().
bool FEHardwareDevice::running private
true if the monitor thread should continue to run.
Definition at line 302 of file FEHardwareDevice.h.
Referenced by monitorThread(), startMonitor(), and stopMonitor().
bool FEHardwareDevice::stopped private
true when the monitor thread has stopped and may be destroyed.
Definition at line 318 of file FEHardwareDevice.h.
Referenced by monitorThread(), and stopMonitor().
pthread_t FEHardwareDevice::thread_m private
the monitor thread handle.
Definition at line 317 of file FEHardwareDevice.h.
Referenced by startMonitor().
const char * FEHardwareDevice::TransactionText static
Initial value:
= {
    "000",
    "   ",
    "   ",
    "   ",
    "   ",
    "   ",
    "   ",
    "   ",
    "   ",
    "   ",
    "CHK",
    "MON",
    "CMD",
    "RBK"
}
a string corresponding to each TRANSACTION_TYPE.
Definition at line 110 of file FEHardwareDevice.h.
Referenced by AmbTransactionLogger::logSingleItem().
The documentation for this class was generated from the following files:
FEBASE/FEHardwareDevice.h
FEBASE/FEHardwareDevice.cpp