FrontEndControl2: DLL/lv_wrapper_FE.cpp File Reference
lv_wrapper_FE.cpp File Reference
#include "lv_wrapper_FE.h"
#include "lv_wrapper_Compressor.h"
#include "lv_wrapper_sigSrc.h"
#include "lv_wrapper.h"
#include "lv_structs.h"
#include "FEMCEventQueue.h"
#include "FrontEndImpl.h"
#include "SignalSourceImpl.h"
#include "logger.h"
#include "CONFIG/ConfigProviderMySQL.h"
#include "CONFIG/ConfigProviderIniFile.h"
#include "CONFIG/ConfigManager.h"
#include "CONFIG/IFPowerDataSet.h"
#include "iniFile.h"
#include "stringConvert.h"
#include "splitPath.h"
#include "FEBASE/FEHardwareDevice.h"
#include "OPTIMIZE/XYPlotArray.h"
#include "ColdCartImpl.h"
#include "CryostatImpl.h"
#include "FETIMImpl.h"
#include "IFSwitchImpl.h"
#include "PowerModuleImpl.h"
#include "WCAImpl.h"
#include <math.h>
Namespaces
FrontEndLVWrapper
Functions
std::string FrontEndLVWrapper::FineLoSweepIni ("")
DLLEXPORT short FEControlInit ()
Initialize the control connection to the FE.
DLLEXPORT short FEControlShutdown ()
Destroy the control connection to the FE.
DLLEXPORT short FEMCExit ()
Shutdown the firmware on the FE M&C module.
DLLEXPORT short FEMCGetAMBSIInfo (char *_serialNum, char *_firmwareRev, unsigned long *numErrors, unsigned long *numTransactions)
Get the AMBSI1's monitor data.
DLLEXPORT short FEMCGetAMBSITemperature (float *temperature)
Get the AMBSI1's temperature.
DLLEXPORT short FEMCGetFirmwareInfo (char *_AMBSILibraryVersion, char *_FEMCFirmwareVersion, char *_FEMCFPGAVersion)
Get the FE M&C firmware version information.
DLLEXPORT short FEMCGetESNText (char *target)
Get the list of electronic serial numbers found in the FE.
DLLEXPORT short FEMCRescanESNs ()
Send a command to the FEMC module to rescan the 1-wire bus for ESNs.
DLLEXPORT short FEMCGetNumErrors ()
How many unread errors are waiting in the error queue? Returns >= 0 if there are unread errors; -1 if not connected to the FE.
DLLEXPORT short FEMCGetNextError (short *moduleNum, short *errorNum, char *description)
Read the next unread error from the error queue.
DLLEXPORT short FEMCSetFEMode (short mode)
Set the FE operating mode to one of 0 -> Operational 1 -> Troubleshooting 2 -> Maintenance All other values are rejected.
void createCartridge (int port, const FrontEndConfig &feConfig, WCAImpl **WCA, ColdCartImpl **coldCart, PowerModuleImpl **powerMod)
DLLEXPORT short FELoadConfiguration (short keyFacility, short configId)
Configure the FE from the configuration database according to the given configId.
DLLEXPORT short FEGetNextSerialNum (short reset, char *serialNum, unsigned long *frontEndId)
Iterate through the list of available front end serial numbers and their associated keys.
DLLEXPORT short FEStartHealthCheck (short isPASData, short fullAuto)
Set initial conditions for front end overall and cartridge health check.
DLLEXPORT short cartHealthCheck (short port, short warmUpTimeSeconds)
Peform a health check on the cartridge assembly at the given port.
DLLEXPORT short cartHealthCheckSaveIFPowerData (short port, CartIFPowerData_t *source)
Save the provided IF power and Y-factor data to the datbase as part of the health check in progress.
DLLEXPORT short FEFinishHealthCheck ()
Set the front end back to normal conditions after health check.
bool validatePortNumber (short &port, bool *isSignalSource=NULL)
DLLEXPORT short FESetCartridgeOff (short port)
DLLEXPORT short FESetCartridgeOn (short port)
DLLEXPORT short FESetCartridgeObserving (short port)
DLLEXPORT short FEClearCartridgeObserving (short port)
DLLEXPORT short FEGetCartridgeState (short port, CartStateData_t *target)
Get the state of the cartridge and its subsystem control switches (enable, observing, SIS enable, etc.)
DLLEXPORT short FEGetNumCartridgesOn ()
ERROR -1 0-10 number of cartridges in ON or OBSERVING state.
DLLEXPORT short cartPauseMonitor (short port, short pauseWCA, short pauseCC)
Pause/restart monitoring for the specified port WCA and/or cold cart.
DLLEXPORT short randomizeAnalogMonitors (short enable)
enable/disble random ordering on analog monitor points.
DLLEXPORT short cartSetLOFrequency (short port, double freqLO, double freqFLOOG, short sbLock)
Set the YTO tuning according to the given LO reference & floog frequencies.
DLLEXPORT short cartGetLOFrequency (short port, double *freqLO, double *freqREF)
Get the current freqLO and freqREF settings. Software readback only.
DLLEXPORT short cartLockPLL (short port)
Initiate the search for a lock.
DLLEXPORT short cartGetLocked (short port, short *locked)
Get the LO locked status.
DLLEXPORT short cartAdjustPLL (short port, float targetCorrVoltage)
Adjust the YTO to get the correction voltage as close as possible to the given target voltage.
DLLEXPORT short cartAdjustYTO (short port, short steps)
Bump the YTO up or down by the given number of steps. May be + or -.
DLLEXPORT short cartNullPLLIntegrator (short port, short enable)
Enable the PLL null integrator setting. Prevents PLL locking and allows free-running operation.
DLLEXPORT short cartSetLNABias (short port, short pol, short sb, float VD1, float ID1, float VD2, float ID2, float VD3, float ID3)
Set the LNA bias for a given pol and sb or for all LNAs simultaneously.
DLLEXPORT short cartSetEnableLNABias (short port, short enable, short pol, short sb)
Enable or disable the LNA for a given pol and sb or for all LNAs simultaneously.
DLLEXPORT short cartSetSISBias (short port, short enable, short pol, short sb, float VJ, short openLoop)
Enable/disable and set the SIS bias for a given pol and sb or for all SIS mixers simultanously.
DLLEXPORT short cartSetSISMagnet (short port, short enable, short pol, short sb, float IMag)
Enable/disable and set the SIS magnet bias for a given pol and sb or for all SIS magnets simultanously.
DLLEXPORT short cartGetSISMagnet (short port, short pol, short sb, float *IMag)
Get the SIS magnet control setting for a given pol and sb.
DLLEXPORT short cartSetLOPowerAmps (short port, short enable, float VDP0, float VGP0, float VDP1, float VGP1)
Enable/disable and set the LO power amps.
DLLEXPORT short cartAdjustLOPowerAmps (short port, short repeatCount)
Adjust the LO PA drain voltages until the junction currents are as close as possible to the the target values given in the configuration database.
DLLEXPORT short cartSetEnableLO (short port, short enable)
Enable or disable the LO output for the specified WCA.
DLLEXPORT short cartSetLOPower (short port, short pol, float percent)
set the LO output power level as a percentage (0.0 - 100.0) of maximum
DLLEXPORT short cartOptimizeIFPower (short port, short pol)
Perform optmization of IF power vs.
DLLEXPORT short cartSetIFPower (short port, short pol, float powerSB1, float powerSB2)
Inject the current IF power level readings for a single port and polarization.
DLLEXPORT short cartSetVJVD (short port, short pol, float VJ1, float VJ2, float VD)
Set the junction voltages and/or PA drain voltage for the given port and polarization.
DLLEXPORT short cartGetVJVD (short port, short pol, float *VJ1, float *VJ2, float *VD)
Read the junction control voltages and PA drain voltage for the given port and polarization.
DLLEXPORT short cartGetLOPADrainVoltageSetting (short port, float *VDP0, float *VDP1)
Retrieve the drain voltage settings for the specified port.
DLLEXPORT short cartSetAMC (short port, float VDE, float VGE)
Set or reset the AMC digital pots.
DLLEXPORT short cartMeasureFineLOSweep (short port, float tiltAngle, short pol, float VJ, float IJ, float fixedVD, double LOStart, double LOStop, double LOStep, short repeatCount)
For the given port and pol, set both SIS junction voltages to VJ; At each LO frequency from LOStart to LOStop by LOStep: adjust the LO PA drain voltage to get junction current IJ -or- set LO PA drain voltage to fixedVD if specified.
DLLEXPORT short cartMeasureIVCurve (short port, short pol, short sb, float VJLow, float VJHigh, float VJStep, short repeatCount)
Take an I-V curve for the given port, pol, and sb.
DLLEXPORT short cartMeasureIJvsSISMagnet (short port, short pol, short sb, float IMagStart, float IMagStop, float IMagStep, float VJLow, float VJHigh, float VJStep, short repeatCount)
For the given port, pol, and sb, step the magnet current from IMagStart to IMagStop by IMagStep.
DLLEXPORT short cartMeasureIFPowerVsVJ (short port, short pol, short sb, float VJStart, float VJStop, float VJStep, bool doYFactor, short repeatCount)
For the given port and pol, sweep both sidebands junction voltage from VJStart to VJStop by VJStep, record the IF output power.
DLLEXPORT short cartMeasureIFPowerVsVD (short port, short pol, float VDLow, float VDHigh, float VDStep, bool doYFactor, short repeatCount)
For the given port and pol, sweep the LO PA drain voltage from VDStart to VDStop by VDStep, record the IF output power from both sidebands.
DLLEXPORT short cartMixerDeflux (short port, short pol, short sb, short IMagMax)
For the given port and pol, perform a coil demagnetization and mixer deflux operation.
DLLEXPORT short cartAbortMeasurement (short port)
Stops any cartridge optimization measurement in progress on the given port.
DLLEXPORT short cartGetXYData (short port, short *size, float *X, float *Y, float *Y2)
Retrieve the X-Y data array from the last measurement on the specified port.
DLLEXPORT short cartSetEnableLNALEDs (short port, short enable)
Enable/disable the LNA LEDs.
DLLEXPORT short cartSetEnableSISHeaters (short port, short enable, short pol, float targetTemp, short timeout)
Enable/disable the SIS heaters.
DLLEXPORT short cartSetEnablePhotomixer (short port, short enable)
Enable/disable the photomixer.
DLLEXPORT short ifSwitchSetAttenuation (short pol, short sb, short atten)
Set the IF switch attenuator(s) 0-15 dB If pol < 0 or sb < 1, all four attenuators will be set the same.
DLLEXPORT short ifSwitchSetEnableTempServo (short pol, short sb, short enable)
Enable/disable the IF switch temperature servo.
DLLEXPORT short cryostatSetEnableBackingPump (short enable)
Start/stop the backing pump.
DLLEXPORT short cryostatSetEnableTurboPump (short enable)
Start/stop the turbo pump.
DLLEXPORT short cryostatSetGateValveState (short open)
Open/close the gate valve.
DLLEXPORT short cryostatSetSolenoidValveState (short open)
Open/close the solenoid valve.
DLLEXPORT short cryostatSetEnableVacuumGauge (short enable)
Enable/disable the vacuum gauge.
DLLEXPORT short cryostatSetEnableCryoPumping (short enable)
Enable/disable the pump-down process.
DLLEXPORT short fetimSetTriggerDewarN2Fill (short enable)
Enable/disable the N2 fill trigger.
DLLEXPORT short lprSetOpticalSwitchPort (short port)
Set the optical switch output port and disable the shutter.
DLLEXPORT short lprSetOpticalSwitchShutter ()
Enables the shutter (disables the laser).
DLLEXPORT short lprSetOpticalSwitchForceShutter ()
Enables the shutter (disables the laser) more forcefully (for debugging).
DLLEXPORT short lprSetEDFAModulationInput (float value)
Sets the EDFA modulation input value in Volts.
DLLEXPORT short cartGetMonitorYTO (short port, CartYTOData_t *target)
DLLEXPORT short cartGetMonitorPhotomixer (short port, CartPhotomixerData_t *target)
DLLEXPORT short cartGetMonitorPLL (short port, CartPLLData_t *target)
DLLEXPORT short cartGetMonitorAMC (short port, CartAMCData_t *target)
DLLEXPORT short cartGetMonitorPA (short port, CartPAData_t *target)
DLLEXPORT short cartGetMonitorTemp (short port, CartTempData_t *target)
DLLEXPORT short cartGetMonitorSIS (short port, short pol, short sb, CartSISData_t *target)
DLLEXPORT short cartGetMonitorLNA (short port, short pol, short sb, CartLNAData_t *target)
DLLEXPORT short cartGetMonitorAux (short port, short pol, CartAuxData_t *target)
DLLEXPORT short powerGetMonitorModule (short port, PowerModuleData_t *target)
DLLEXPORT short ifSwitchGetMonitor (IFSwitchData_t *target)
DLLEXPORT short cryostatGetMonitor (CryostatData_t *target)
DLLEXPORT short lprGetMonitor (LPRData_t *target)
DLLEXPORT short fetimGetMonitor (FETIMData_t *target)
Variables
unsigned long FrontEndLVWrapper::facilityId = 40
unsigned long FrontEndLVWrapper::configId = 1
bool FrontEndLVWrapper::configFromDatabase = false
bool FrontEndLVWrapper::allowSISHeaters = false
bool FrontEndLVWrapper::SISOpenLoop = false
short FrontEndLVWrapper::FEMode = 0
bool FrontEndLVWrapper::tryAlternateLockMethod = false
bool FrontEndLVWrapper::defeatNormalLockDetect = false
bool FrontEndLVWrapper::correctSISVoltageError = true
bool FrontEndLVWrapper::randomizeMonitors = false
bool FrontEndLVWrapper::logMonitors = false
bool FrontEndLVWrapper::logAmbErrors = true
unsigned long FrontEndLVWrapper::CANChannel = 0
unsigned long FrontEndLVWrapper::nodeAddress = 0x13
bool FrontEndLVWrapper::startCompressorModule = false
Function Documentation
DLLEXPORT short cartAbortMeasurement (short port)
Stops any cartridge optimization measurement in progress on the given port.
Definition at line 1299 of file lv_wrapper_FE.cpp.
References cartAbortMeasurement(), and validatePortNumber().
Referenced by cartAbortMeasurement().
DLLEXPORT short cartAdjustLOPowerAmps (short port, short repeatCount)
Adjust the LO PA drain voltages until the junction currents are as close as possible to the the target values given in the configuration database.
Adjustment happens on a worker thread. Sends the event EVENT_PA_ADJUST_DONE via getNextEvent whene finished.
Definition at line 1056 of file lv_wrapper_FE.cpp.
References cartAdjustLOPowerAmps(), and validatePortNumber().
Referenced by cartAdjustLOPowerAmps().
DLLEXPORT short cartAdjustPLL (short port, float targetCorrVoltage)
Adjust the YTO to get the correction voltage as close as possible to the given target voltage.
Definition at line 838 of file lv_wrapper_FE.cpp.
References cartAdjustPLL(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartAdjustPLL().
DLLEXPORT short cartAdjustYTO (short port, short steps)
Bump the YTO up or down by the given number of steps. May be + or -.
Definition at line 860 of file lv_wrapper_FE.cpp.
References cartAdjustYTO(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartAdjustYTO().
DLLEXPORT short cartGetLocked (short port, short * locked)
Get the LO locked status.
Definition at line 815 of file lv_wrapper_FE.cpp.
References cartGetLocked(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartGetLocked().
DLLEXPORT short cartGetLOFrequency (short port, double * freqLO, double * freqREF)
Get the current freqLO and freqREF settings. Software readback only.
Definition at line 768 of file lv_wrapper_FE.cpp.
References cartGetLOFrequency(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartGetLOFrequency().
DLLEXPORT short cartGetLOPADrainVoltageSetting (short port, float * VDP0, float * VDP1)
Retrieve the drain voltage settings for the specified port.
Definition at line 1162 of file lv_wrapper_FE.cpp.
References cartGetLOPADrainVoltageSetting(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartGetLOPADrainVoltageSetting().
DLLEXPORT short cartGetMonitorAMC (short port, CartAMCData_t * target)
Definition at line 1588 of file lv_wrapper_FE.cpp.
References CartAMCData_t::AMC_DRAIN_A_CURRENT, CartAMCData_t::AMC_DRAIN_A_VOLTAGE, CartAMCData_t::AMC_DRAIN_B_CURRENT, CartAMCData_t::AMC_DRAIN_B_VOLTAGE, CartAMCData_t::AMC_DRAIN_E_CURRENT, CartAMCData_t::AMC_DRAIN_E_VOLTAGE, CartAMCData_t::AMC_GATE_A_VOLTAGE, CartAMCData_t::AMC_GATE_B_VOLTAGE, CartAMCData_t::AMC_GATE_E_VOLTAGE, CartAMCData_t::AMC_MULTIPLIER_D_CURRENT, CartAMCData_t::AMC_MULTIPLIER_D_VOLTAGE, CartAMCData_t::AMC_SUPPLY_VOLTAGE_5V, WCAImpl::AMC_t::amcDrainACurrent_value, WCAImpl::AMC_t::amcDrainAVoltage_value, WCAImpl::AMC_t::amcDrainBCurrent_value, WCAImpl::AMC_t::amcDrainBVoltage_value, WCAImpl::AMC_t::amcDrainECurrent_value, WCAImpl::AMC_t::amcDrainEVoltage_value, WCAImpl::AMC_t::amcGateAVoltage_value, WCAImpl::AMC_t::amcGateBVoltage_value, WCAImpl::AMC_t::amcGateEVoltage_value, WCAImpl::AMC_t::amcMultiplierDCurrent_value, WCAImpl::AMC_t::amcMultiplierDVoltage_value, WCAImpl::AMC_t::amcSupplyVoltage5V_value, cartGetMonitorAMC(), FrontEndLVWrapper::debugLVStructures, FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartGetMonitorAMC(), and main().
DLLEXPORT short cartGetMonitorAux (short port, short pol, CartAuxData_t * target)
Definition at line 1739 of file lv_wrapper_FE.cpp.
References cartGetMonitorAux(), FrontEndLVWrapper::debugLVStructures, ColdCartImpl::Aux_t::lnaLedEnable_value, ColdCartImpl::Aux_t::sisHeaterCurrent_value, and validatePortNumber().
Referenced by cartGetMonitorAux(), and main().
DLLEXPORT short cartGetMonitorLNA (short port, short pol, short sb, CartLNAData_t * target)
Definition at line 1711 of file lv_wrapper_FE.cpp.
References cartGetMonitorLNA(), FrontEndLVWrapper::debugLVStructures, CartLNAData_t::LNA1_DRAIN_CURRENT, CartLNAData_t::LNA1_DRAIN_VOLTAGE, CartLNAData_t::LNA1_GATE_VOLTAGE, CartLNAData_t::LNA2_DRAIN_CURRENT, CartLNAData_t::LNA2_DRAIN_VOLTAGE, CartLNAData_t::LNA2_GATE_VOLTAGE, CartLNAData_t::LNA3_DRAIN_CURRENT, CartLNAData_t::LNA3_DRAIN_VOLTAGE, CartLNAData_t::LNA3_GATE_VOLTAGE, ColdCartImpl::LNA_t::lnaEnable_value, ColdCartImpl::LNA_t::lnaSt1DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt1DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt1GateVoltage_value, ColdCartImpl::LNA_t::lnaSt2DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt2DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt2GateVoltage_value, ColdCartImpl::LNA_t::lnaSt3DrainCurrent_value, ColdCartImpl::LNA_t::lnaSt3DrainVoltage_value, ColdCartImpl::LNA_t::lnaSt3GateVoltage_value, and validatePortNumber().
Referenced by cartGetMonitorLNA(), and main().
DLLEXPORT short cartGetMonitorPA (short port, CartPAData_t * target)
Definition at line 1628 of file lv_wrapper_FE.cpp.
References cartGetMonitorPA(), FrontEndLVWrapper::debugLVStructures, FrontEndLVWrapper::getSignalSourceImpl(), CartPAData_t::PA_POL0_DRAIN_CURRENT, CartPAData_t::PA_POL0_DRAIN_VOLTAGE, CartPAData_t::PA_POL0_GATE_VOLTAGE, CartPAData_t::PA_POL1_DRAIN_CURRENT, CartPAData_t::PA_POL1_DRAIN_VOLTAGE, CartPAData_t::PA_POL1_GATE_VOLTAGE, CartPAData_t::PA_SUPPLY_VOLTAGE_3V, CartPAData_t::PA_SUPPLY_VOLTAGE_5V, WCAImpl::PA_t::paPol0DrainCurrent_value, WCAImpl::PA_t::paPol0DrainVoltage_value, WCAImpl::PA_t::paPol0GateVoltage_value, WCAImpl::PA_t::paPol1DrainCurrent_value, WCAImpl::PA_t::paPol1DrainVoltage_value, WCAImpl::PA_t::paPol1GateVoltage_value, WCAImpl::PA_t::paSupplyVoltage3V_value, WCAImpl::PA_t::paSupplyVoltage5V_value, and validatePortNumber().
Referenced by cartGetMonitorPA(), and main().
DLLEXPORT short cartGetMonitorPhotomixer (short port, CartPhotomixerData_t * target)
Definition at line 1518 of file lv_wrapper_FE.cpp.
References cartGetMonitorPhotomixer(), FrontEndLVWrapper::debugLVStructures, FrontEndLVWrapper::getSignalSourceImpl(), CartPhotomixerData_t::PHOTOMIXER_CURRENT, CartPhotomixerData_t::PHOTOMIXER_VOLTAGE, WCAImpl::Photomixer_t::photomixerCurrent_value, WCAImpl::Photomixer_t::photomixerEnable_value, WCAImpl::Photomixer_t::photomixerVoltage_value, and validatePortNumber().
Referenced by cartGetMonitorPhotomixer(), and main().
DLLEXPORT short cartGetMonitorPLL (short port, CartPLLData_t * target)
Definition at line 1549 of file lv_wrapper_FE.cpp.
References cartGetMonitorPLL(), FrontEndLVWrapper::debugLVStructures, FrontEndLVWrapper::getSignalSourceImpl(), CartPLLData_t::PLL_ASSEMBLY_TEMP, CartPLLData_t::PLL_CORRECTION_VOLTAGE, CartPLLData_t::PLL_IF_TOTAL_POWER, CartPLLData_t::PLL_LOCK, CartPLLData_t::PLL_LOCK_DETECT_VOLTAGE, CartPLLData_t::PLL_LOOP_BANDWIDTH_SELECT, CartPLLData_t::PLL_NULL_LOOP_INTEGRATOR, CartPLLData_t::PLL_REF_TOTAL_POWER, CartPLLData_t::PLL_SIDEBAND_LOCK_POL_SELECT, CartPLLData_t::PLL_UNLOCK_DETECT_LATCH, CartPLLData_t::PLL_YTO_HEATER_CURRENT, WCAImpl::PLL_t::pllAssemblyTemp_value, WCAImpl::PLL_t::pllCorrectionVoltage_value, WCAImpl::PLL_t::pllIfTotalPower_value, WCAImpl::PLL_t::pllLock_value, WCAImpl::PLL_t::pllLockDetectVoltage_value, WCAImpl::PLL_t::pllLoopBandwidthSelect_value, WCAImpl::PLL_t::pllNullLoopIntegrator_value, WCAImpl::PLL_t::pllRefTotalPower_value, WCAImpl::PLL_t::pllSidebandLockSelect_value, WCAImpl::PLL_t::pllUnlockDetectLatch_value, WCAImpl::PLL_t::pllYTOHeaterCurrent_value, and validatePortNumber().
Referenced by cartGetMonitorPLL(), and main().
DLLEXPORT short cartGetMonitorSIS (short port, short pol, short sb, CartSISData_t * target)
Definition at line 1688 of file lv_wrapper_FE.cpp.
References cartGetMonitorSIS(), FrontEndLVWrapper::debugLVStructures, CartSISData_t::SIS_CURRENT, CartSISData_t::SIS_MAGNET_CURRENT, CartSISData_t::SIS_MAGNET_VOLTAGE, CartSISData_t::SIS_VOLTAGE, ColdCartImpl::SIS_t::sisCurrent_value, ColdCartImpl::SIS_t::sisMagnetCurrent_value, ColdCartImpl::SIS_t::sisMagnetVoltage_value, ColdCartImpl::SIS_t::sisOpenLoop_value, ColdCartImpl::SIS_t::sisVoltage_value, and validatePortNumber().
Referenced by cartGetMonitorSIS(), and main().
DLLEXPORT short cartGetMonitorTemp (short port, CartTempData_t * target)
Definition at line 1664 of file lv_wrapper_FE.cpp.
References cartGetMonitorTemp(), CartTempData_t::CARTRIDGE_TEMP0, CartTempData_t::CARTRIDGE_TEMP1, CartTempData_t::CARTRIDGE_TEMP2, CartTempData_t::CARTRIDGE_TEMP3, CartTempData_t::CARTRIDGE_TEMP4, CartTempData_t::CARTRIDGE_TEMP5, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature0_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature1_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature2_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature3_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature4_value, ColdCartImpl::CartridgeTemp_t::cartridgeTemperature5_value, FrontEndLVWrapper::debugLVStructures, and validatePortNumber().
Referenced by cartGetMonitorTemp(), and main().
DLLEXPORT short cartGetMonitorYTO (short port, CartYTOData_t * target)
Definition at line 1488 of file lv_wrapper_FE.cpp.
References cartGetMonitorYTO(), FrontEndLVWrapper::debugLVStructures, FrontEndLVWrapper::getSignalSourceImpl(), validatePortNumber(), WCAImpl::YTO_t::ytoCoarseTune_value, and WCAImpl::YTO_t::ytoFrequency_value.
Referenced by cartGetMonitorYTO(), and main().
DLLEXPORT short cartGetSISMagnet (short port, short pol, short sb, float * IMag)
Get the SIS magnet control setting for a given pol and sb.
Definition at line 1013 of file lv_wrapper_FE.cpp.
References cartGetSISMagnet(), and validatePortNumber().
Referenced by cartGetSISMagnet().
DLLEXPORT short cartGetVJVD (short port, short pol, float * VJ1, float * VJ2, float * VD)
Read the junction control voltages and PA drain voltage for the given port and polarization.
The existing control values are returend as VJ1, VJ2, and VD.
Definition at line 1150 of file lv_wrapper_FE.cpp.
References cartGetVJVD(), and validatePortNumber().
Referenced by cartGetVJVD().
DLLEXPORT short cartGetXYData (short port, short * size, float * X, float * Y, float * Y2)
Retrieve the X-Y data array from the last measurement on the specified port.
X, Y, and Y2 point to data arrays. size, X and Y are required. Y2 may be NULL. *size specifies how many elements are in the arrays before the call and how many valid elements are there after the call. Array memory must be pre-allocated.
Definition at line 1309 of file lv_wrapper_FE.cpp.
References cartGetXYData(), and validatePortNumber().
Referenced by cartGetXYData().
DLLEXPORT short cartHealthCheck (short port, short warmUpTimeSeconds)
Peform a health check on the cartridge assembly at the given port.
Wait the specified number of seconds before taking data.
Definition at line 537 of file lv_wrapper_FE.cpp.
References cartHealthCheck().
Referenced by cartHealthCheck().
DLLEXPORT short cartHealthCheckSaveIFPowerData (short port, CartIFPowerData_t * source)
Save the provided IF power and Y-factor data to the datbase as part of the health check in progress.
Definition at line 545 of file lv_wrapper_FE.cpp.
References cartHealthCheckSaveIFPowerData().
Referenced by cartHealthCheckSaveIFPowerData().
DLLEXPORT short cartLockPLL (short port)
Initiate the search for a lock.
Can take a long time if the YTO is not tuned correctly for the actual LO reference and FLOOG signals.
Definition at line 793 of file lv_wrapper_FE.cpp.
References cartLockPLL(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartLockPLL().
DLLEXPORT short cartMeasureFineLOSweep (short port, float tiltAngle, short pol, float VJ, float IJ, float fixedVD, double LOStart, double LOStop, double LOStep, short repeatCount)
For the given port and pol, set both SIS junction voltages to VJ; At each LO frequency from LOStart to LOStop by LOStep: adjust the LO PA drain voltage to get junction current IJ -or- set LO PA drain voltage to fixedVD if specified.
record the resulting SIS current and PA drain voltage. repeatCount gives the number of times to measure. Measurement happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent when finished. pol may be -1, indicating both pols are to be measured. If fixedVD is a valid value (not +Inf or -Inf) then use that VD setting and ignore IJ. If either of VJ or IJ are +Inf or -Inf then the settings from FineLOSweep.ini are used. If any of LOStart, LOStop, or LOStep are 0, then the settings from FineLOSweep.ini are used.
Definition at line 1213 of file lv_wrapper_FE.cpp.
References cartMeasureFineLOSweep(), and validatePortNumber().
Referenced by cartMeasureFineLOSweep().
DLLEXPORT short cartMeasureIFPowerVsVD (short port, short pol, float VDStart, float VDStop, float VDStep, bool doYFactor, short repeatCount)
For the given port and pol, sweep the LO PA drain voltage from VDStart to VDStop by VDStep, record the IF output power from both sidebands.
repeatCount gives the number of times to measure. Measurement happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent whene finished.
Definition at line 1275 of file lv_wrapper_FE.cpp.
References cartMeasureIFPowerVsVD(), and validatePortNumber().
Referenced by cartMeasureIFPowerVsVD().
DLLEXPORT short cartMeasureIFPowerVsVJ (short port, short pol, short sb, float VJStart, float VJStop, float VJStep, bool doYFactor, short repeatCount)
For the given port and pol, sweep both sidebands junction voltage from VJStart to VJStop by VJStep, record the IF output power.
If sb is -1, step both junctions. Otherwise step one junction and leave the other set as it was. repeatCount gives the number of times to measure. Measurement happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent whene finished.
Definition at line 1262 of file lv_wrapper_FE.cpp.
References cartMeasureIFPowerVsVJ(), and validatePortNumber().
Referenced by cartMeasureIFPowerVsVJ().
DLLEXPORT short cartMeasureIJvsSISMagnet (short port, short pol, short sb, float IMagStart, float IMagStop, float IMagStep, float VJLow, float VJHigh, float VJStep, short repeatCount)
For the given port, pol, and sb, step the magnet current from IMagStart to IMagStop by IMagStep.
At each step, sweep the mixer voltage from VJLow to VJHigh by VJStep, if VJMin==VJMax, record the mixer junction current at each magnet step. else, record half the difference between the max and min junction current seen. If sbMixer is -1, measure both mixers while stepping both magnets (or band-specific special cases.) repeatCount gives the number of times to measure. Measurement happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent whene finished.
Definition at line 1248 of file lv_wrapper_FE.cpp.
References cartMeasureIJvsSISMagnet(), and validatePortNumber().
Referenced by cartMeasureIJvsSISMagnet().
DLLEXPORT short cartMeasureIVCurve (short port, short pol, short sb, float VJLow, float VJHigh, float VJStep, short repeatCount)
Take an I-V curve for the given port, pol, and sb.
If VJlow, VJhigh, or VJstep is +Inf or -Inf it will be computed from the nominal VJ. Measurement happens on a worker thread. Sends the event EVENT_IVCURVE_DONE via getNextEvent whene finished.
Definition at line 1232 of file lv_wrapper_FE.cpp.
References cartMeasureIVCurve(), and validatePortNumber().
Referenced by cartMeasureIVCurve().
DLLEXPORT short cartMixerDeflux (short port, short pol, short sb, short IMagMax)
For the given port and pol, perform a coil demagnetization and mixer deflux operation.
sb may be 1, 2 or -1 specifying that both sidebands should be defluxed simultaneously. IMagMax is the maximum magnet current to use in the demagnetization phase. Produces an X-Y data set containing the magnet current and heater current vs. time. Defluxing happens on a worker thread. Sends the event EVENT_OPTIMIZE_DONE via getNextEvent whene finished.
Definition at line 1288 of file lv_wrapper_FE.cpp.
References cartMixerDeflux(), and validatePortNumber().
Referenced by cartMixerDeflux().
DLLEXPORT short cartNullPLLIntegrator (short port, short enable)
Enable the PLL null integrator setting. Prevents PLL locking and allows free-running operation.
Definition at line 882 of file lv_wrapper_FE.cpp.
References cartNullPLLIntegrator(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartNullPLLIntegrator().
DLLEXPORT short cartOptimizeIFPower (short port, short pol)
Perform optmization of IF power vs.
LO drive and junction voltage. works in conjunction with setIFPower() which injects ongoing power readings. Optimization happens on a worker thread. if pol is -1, both polarizations are optimized in turn. Sends the event EVENT_REQUEST_IFPOWER via the client app event queue when power readings are required. Sends the event EVENT_PA_ADJUST_DONE when finished.
Definition at line 1110 of file lv_wrapper_FE.cpp.
References cartOptimizeIFPower(), and validatePortNumber().
Referenced by cartOptimizeIFPower().
DLLEXPORT short cartPauseMonitor (short port, short pauseWCA, short pauseCC)
Pause/restart monitoring for the specified port WCA and/or cold cart.
Definition at line 721 of file lv_wrapper_FE.cpp.
References cartPauseMonitor(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartPauseMonitor().
DLLEXPORT short cartSetAMC (short port, float VDE, float VGE)
Set or reset the AMC digital pots.
If both VDE and VGE are +Inf or -Inf then both are set to nominal (1.0, -0.1). If VDE is not +Inf or -Inf then its value is set otherwise no change. If VGE is not +Inf or -Inf then its value is set otherwise no change.
Definition at line 1187 of file lv_wrapper_FE.cpp.
References cartSetAMC(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartSetAMC().
DLLEXPORT short cartSetEnableLNABias (short port, short enable, short pol, short sb)
Enable or disable the LNA for a given pol and sb or for all LNAs simultaneously.
If pol or sb is -1, all LNAs are simultaneously affected.
Definition at line 935 of file lv_wrapper_FE.cpp.
References cartSetEnableLNABias(), and validatePortNumber().
Referenced by cartSetEnableLNABias(), and main().
DLLEXPORT short cartSetEnableLNALEDs (short port, short enable)
Enable/disable the LNA LEDs.
Definition at line 1338 of file lv_wrapper_FE.cpp.
References cartSetEnableLNALEDs(), and validatePortNumber().
Referenced by cartSetEnableLNALEDs().
DLLEXPORT short cartSetEnableLO (short port, short enable)
Enable or disable the LO output for the specified WCA.
Intended for use with BeaSTs. This turns off the the LO PA and moves the YTO to the opposite extreme of the tuning range. In conjunction with the IF Processor YIG filter this effectively removes all source power, even in cases where source power may be leaking through or around the PA.
Definition at line 1066 of file lv_wrapper_FE.cpp.
References cartSetEnableLO(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartSetEnableLO().
DLLEXPORT short cartSetEnablePhotomixer (short port, short enable)
Enable/disable the photomixer.
Definition at line 1360 of file lv_wrapper_FE.cpp.
References cartSetEnablePhotomixer(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartSetEnablePhotomixer().
DLLEXPORT short cartSetEnableSISHeaters (short port, short enable, short pol, float targetTemp, short timeout)
Enable/disable the SIS heaters.
If enable, start the mixer heating process. If pol == -1, heat both polarizations. Else pol must be 0 or 1. If targetTemp >= 4, retrigger the the heater for up to timeout seconds to attain the target temperature. Else, retrigger the heater for exactly timeout seconds. For band 9, timeout may be no longer than 2 seconds. For bands 678, timeout may be up to 2 minutes.
Definition at line 1348 of file lv_wrapper_FE.cpp.
References FrontEndLVWrapper::allowSISHeaters, cartSetEnableSISHeaters(), and validatePortNumber().
Referenced by cartSetEnableSISHeaters().
DLLEXPORT short cartSetIFPower (short port, short pol, float powerSB1, float powerSB2)
Inject the current IF power level readings for a single port and polarization.
Used for optimizing mixer and LO power amp bias voltages.
Definition at line 1125 of file lv_wrapper_FE.cpp.
References cartSetIFPower(), and validatePortNumber().
Referenced by cartSetIFPower().
DLLEXPORT short cartSetLNABias (short port, short pol, short sb, float VD1, float ID1, float VD2, float ID2, float VD3, float ID3)
Set the LNA bias for a given pol and sb or for all LNAs simultaneously.
If any of the float values given is +Inf or -Inf it is ignored and the corresponding setting is used from the configuration database. If either pol or sb is -1, then all float values are ignored and the values from the config database are used.
Definition at line 904 of file lv_wrapper_FE.cpp.
References cartSetLNABias(), and validatePortNumber().
Referenced by cartSetLNABias(), and main().
DLLEXPORT short cartSetLOFrequency (short port, double freqLO, double freqFLOOG, short sbLock)
Set the YTO tuning according to the given LO reference & floog frequencies.
sbLock = 0 means lock below the reference: freqREF = freqLO + freqFLOOG; sbLock = 1 means lock above the reference: freqREF = freqLO - freqFLOOG.
Definition at line 746 of file lv_wrapper_FE.cpp.
References cartSetLOFrequency(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartSetLOFrequency(), and main().
DLLEXPORT short cartSetLOPower (short port, short pol, float percent)
set the LO output power level as a percentage (0.0 - 100.0) of maximum
Definition at line 1088 of file lv_wrapper_FE.cpp.
References cartSetLOPower(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartSetLOPower().
DLLEXPORT short cartSetLOPowerAmps (short port, short enable, float VDP0, float VGP0, float VDP1, float VGP1)
Enable/disable and set the LO power amps.
If any of the float values given is +Inf or -Inf, no change is made to the corresponding control point. If all the float values are +Inf or -Inf, all settings are made according to the configuration database.
Definition at line 1023 of file lv_wrapper_FE.cpp.
References cartSetLOPowerAmps(), FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by cartSetLOPowerAmps(), and main().
DLLEXPORT short cartSetSISBias (short port, short enable, short pol, short sb, float VJ, short openLoop)
Enable/disable and set the SIS bias for a given pol and sb or for all SIS mixers simultanously.
If VJ is +Inf or -Inf, it is ignored and the setting from the configuration database is used. If openLoop is -1, no change is made to the SIS openLoop state. If either pol or sb is -1, then all junctions are biased according to the database.
Definition at line 956 of file lv_wrapper_FE.cpp.
References cartSetSISBias(), FrontEndLVWrapper::SISOpenLoop, and validatePortNumber().
Referenced by cartSetSISBias(), and main().
DLLEXPORT short cartSetSISMagnet (short port, short enable, short pol, short sb, float IMag)
Enable/disable and set the SIS magnet bias for a given pol and sb or for all SIS magnets simultanously.
If IMAG is +Inf or -Inf, it is ignored and the setting from the configuration database is used. If either pol or sb is -1, then all magnets are biased according to the database.
Definition at line 990 of file lv_wrapper_FE.cpp.
References cartSetSISMagnet(), and validatePortNumber().
Referenced by cartSetSISMagnet(), and main().
DLLEXPORT short cartSetVJVD (short port, short pol, float VJ1, float VJ2, float VD)
Set the junction voltages and/or PA drain voltage for the given port and polarization.
If any of VJ1, VJ2, or VD is +Inf or -Inf, no change is made to the corresponding control point.
Definition at line 1135 of file lv_wrapper_FE.cpp.
References cartSetVJVD(), and validatePortNumber().
Referenced by cartSetVJVD().
void createCartridge (int port, const FrontEndConfig & feConfig, WCAImpl ** WCA, ColdCartImpl ** coldCart, PowerModuleImpl ** powerMod)
Definition at line 415 of file lv_wrapper_FE.cpp.
References FEConfig::ColdCartConfig::band_m, FEConfig::WCAConfig::band_m, FrontEndLVWrapper::CANChannel, FEConfig::ColdCartConfig::ESN_m, FEConfig::WCAConfig::ESN_m, FEConfig::FrontEndConfig::getCartridgeConfig(), and FrontEndLVWrapper::nodeAddress.
Referenced by FELoadConfiguration().
DLLEXPORT short cryostatGetMonitor (CryostatData_t * target)
Definition at line 1819 of file lv_wrapper_FE.cpp.
References CryostatData_t::BACKING_PUMP_ENABLE, CryostatImpl::Cryostat_t::backingPumpEnable_value, CryostatData_t::CRYOSTAT_TEMP_0, CryostatData_t::CRYOSTAT_TEMP_1, CryostatData_t::CRYOSTAT_TEMP_10, CryostatData_t::CRYOSTAT_TEMP_11, CryostatData_t::CRYOSTAT_TEMP_12, CryostatData_t::CRYOSTAT_TEMP_2, CryostatData_t::CRYOSTAT_TEMP_3, CryostatData_t::CRYOSTAT_TEMP_4, CryostatData_t::CRYOSTAT_TEMP_5, CryostatData_t::CRYOSTAT_TEMP_6, CryostatData_t::CRYOSTAT_TEMP_7, CryostatData_t::CRYOSTAT_TEMP_8, CryostatData_t::CRYOSTAT_TEMP_9, CryostatImpl::Cryostat_t::cryostatTemperature0_value, CryostatImpl::Cryostat_t::cryostatTemperature10_value, CryostatImpl::Cryostat_t::cryostatTemperature11_value, CryostatImpl::Cryostat_t::cryostatTemperature12_value, CryostatImpl::Cryostat_t::cryostatTemperature1_value, CryostatImpl::Cryostat_t::cryostatTemperature2_value, CryostatImpl::Cryostat_t::cryostatTemperature3_value, CryostatImpl::Cryostat_t::cryostatTemperature4_value, CryostatImpl::Cryostat_t::cryostatTemperature5_value, CryostatImpl::Cryostat_t::cryostatTemperature6_value, CryostatImpl::Cryostat_t::cryostatTemperature7_value, CryostatImpl::Cryostat_t::cryostatTemperature8_value, CryostatImpl::Cryostat_t::cryostatTemperature9_value, FrontEndLVWrapper::debugLVStructures, CryostatData_t::GATE_VALVE_STATE, CryostatImpl::Cryostat_t::gateValveState_value, CryostatData_t::SOLENOID_VALVE_STATE, CryostatImpl::Cryostat_t::solenoidValveState_value, CryostatData_t::SUPPLY_CURRENT_230V, CryostatImpl::Cryostat_t::supplyCurrent230V_value, CryostatData_t::TURBO_PUMP_ENABLE, CryostatData_t::TURBO_PUMP_SPEED, CryostatData_t::TURBO_PUMP_STATE, CryostatImpl::Cryostat_t::turboPumpEnable_value, CryostatImpl::Cryostat_t::turboPumpErrorState_value, CryostatImpl::Cryostat_t::turboPumpHighSpeed_value, CryostatData_t::VACUUM_CRYOSTAT_PRES, CryostatData_t::VACUUM_GAUGE_ENABLE, CryostatData_t::VACUUM_GAUGE_STATE, CryostatData_t::VACUUM_PORT_PRES, CryostatImpl::Cryostat_t::vacuumCryostatPressure_value, CryostatImpl::Cryostat_t::vacuumGaugeEnable_value, CryostatImpl::Cryostat_t::vacuumGaugeErrorState_value, and CryostatImpl::Cryostat_t::vacuumPortPressure_value.
DLLEXPORT short cryostatSetEnableBackingPump (short enable)
Start/stop the backing pump.
Definition at line 1398 of file lv_wrapper_FE.cpp.
References cryostatSetEnableBackingPump().
Referenced by cryostatSetEnableBackingPump().
DLLEXPORT short cryostatSetEnableCryoPumping (short enable)
Enable/disable the pump-down process.
Definition at line 1438 of file lv_wrapper_FE.cpp.
References cryostatSetEnableCryoPumping().
Referenced by cryostatSetEnableCryoPumping().
DLLEXPORT short cryostatSetEnableTurboPump (short enable)
Start/stop the turbo pump.
Definition at line 1406 of file lv_wrapper_FE.cpp.
References cryostatSetEnableTurboPump().
Referenced by cryostatSetEnableTurboPump().
DLLEXPORT short cryostatSetEnableVacuumGauge (short enable)
Enable/disable the vacuum gauge.
Definition at line 1430 of file lv_wrapper_FE.cpp.
References cryostatSetEnableVacuumGauge().
Referenced by cryostatSetEnableVacuumGauge().
DLLEXPORT short cryostatSetGateValveState (short open)
Open/close the gate valve.
Definition at line 1414 of file lv_wrapper_FE.cpp.
References cryostatSetGateValveState().
Referenced by cryostatSetGateValveState().
DLLEXPORT short cryostatSetSolenoidValveState (short open)
Open/close the solenoid valve.
Definition at line 1422 of file lv_wrapper_FE.cpp.
References cryostatSetSolenoidValveState().
Referenced by cryostatSetSolenoidValveState().
DLLEXPORT short FEClearCartridgeObserving (short port)
Definition at line 641 of file lv_wrapper_FE.cpp.
References validatePortNumber().
DLLEXPORT short FEControlInit ()
Initialize the control connection to the FE.
Definition at line 83 of file lv_wrapper_FE.cpp.
References FEMCEventQueue::addStatusMessage(), FrontEndLVWrapper::allowSISHeaters, FrontEndLVWrapper::CAN_noTransmit, FrontEndLVWrapper::CANChannel, CompressorControlInit(), FrontEndLVWrapper::configFromDatabase, FrontEndLVWrapper::configId, FrontEndLVWrapper::correctSISVoltageError, FrontEndLVWrapper::defeatNormalLockDetect, FrontEndLVWrapper::facilityId, FELoadConfiguration(), FrontEndLVWrapper::FEMode, FrontEndLVWrapper::FineLoSweepIni(), FrontEndLVWrapper::iniFileName, FrontEndLVWrapper::logAmbErrors, FEHardwareDevice::logAmbErrors(), FrontEndLVWrapper::logMonitors, FEHardwareDevice::logMonitors(), LVWrapperInit(), FrontEndLVWrapper::nodeAddress, FEHardwareDevice::randomizeAnalogMonitors(), FrontEndLVWrapper::randomizeMonitors, FrontEndLVWrapper::SISOpenLoop, FrontEndLVWrapper::startCompressorModule, FrontEndLVWrapper::thermalLogInterval, and FrontEndLVWrapper::tryAlternateLockMethod.
Referenced by main().
DLLEXPORT short FEControlShutdown ()
Destroy the control connection to the FE.
Definition at line 260 of file lv_wrapper_FE.cpp.
References CompressorControlShutdown(), LVWrapperShutdown(), FrontEndLVWrapper::startCompressorModule, and WHACK.
Referenced by main().
DLLEXPORT short FEFinishHealthCheck ()
Set the front end back to normal conditions after health check.
Definition at line 558 of file lv_wrapper_FE.cpp.
DLLEXPORT short FEGetCartridgeState (short port, CartStateData_t * target)
Get the state of the cartridge and its subsystem control switches (enable, observing, SIS enable, etc.)
Definition at line 650 of file lv_wrapper_FE.cpp.
References CartStateData_t::CART_ENABLED, CartStateData_t::CART_LNA_ENABLED, CartStateData_t::CART_LO_PA_ENABLED, CartStateData_t::CART_OBSERVING, CartStateData_t::CART_PHOTOMIXER_ENABLED, CartStateData_t::CART_SIS_ENABLED, CartStateData_t::CART_SIS_MAGNET_ENABLED, CartStateData_t::CART_ZERO_INTEGRATOR_ENABLED, FrontEndLVWrapper::debugLVStructures, FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
DLLEXPORT short FEGetNextSerialNum (short reset, char * serialNum, unsigned long * frontEndId)
Iterate through the list of available front end serial numbers and their associated keys.
Definition at line 496 of file lv_wrapper_FE.cpp.
DLLEXPORT short FEGetNumCartridgesOn ()
ERROR -1 0-10 number of cartridges in ON or OBSERVING state.
Definition at line 715 of file lv_wrapper_FE.cpp.
DLLEXPORT short FELoadConfiguration (short keyFacility, short configId)
Configure the FE from the configuration database according to the given configId.
Definition at line 466 of file lv_wrapper_FE.cpp.
References FrontEndLVWrapper::configFromDatabase, FEConfig::ConfigManager::configure(), createCartridge(), FEConfig::Configuration::getFrontEndConfig(), FrontEndLVWrapper::iniFileName, and FEConfig::Configuration::load().
Referenced by FEControlInit().
DLLEXPORT short FEMCExit ()
Shutdown the firmware on the FE M&C module.
Definition at line 288 of file lv_wrapper_FE.cpp.
DLLEXPORT short FEMCGetAMBSIInfo (char * _serialNum, char * _firmwareRev, unsigned long * numErrors, unsigned long * numTransactions)
Get the AMBSI1's monitor data.
Definition at line 296 of file lv_wrapper_FE.cpp.
Referenced by main().
DLLEXPORT short FEMCGetAMBSITemperature (float * temperature)
Get the AMBSI1's temperature.
Definition at line 312 of file lv_wrapper_FE.cpp.
Referenced by main().
DLLEXPORT short FEMCGetESNText (char * target)
Get the list of electronic serial numbers found in the FE.
Definition at line 335 of file lv_wrapper_FE.cpp.
DLLEXPORT short FEMCGetFirmwareInfo (char * _AMBSILibraryVersion, char * _FEMCFirmwareVersion, char * _FEMCFPGAVersion)
Get the FE M&C firmware version information.
Definition at line 319 of file lv_wrapper_FE.cpp.
Referenced by main().
DLLEXPORT short FEMCGetNextError (short * moduleNum, short * errorNum, char * description)
Read the next unread error from the error queue.
Returns {-1, -1, ""} if the queue is empty or an error occurs.
Definition at line 380 of file lv_wrapper_FE.cpp.
Referenced by main().
DLLEXPORT short FEMCGetNumErrors ()
How many unread errors are waiting in the error queue? Returns >= 0 if there are unread errors; -1 if not connected to the FE.
Definition at line 373 of file lv_wrapper_FE.cpp.
DLLEXPORT short FEMCRescanESNs ()
Send a command to the FEMC module to rescan the 1-wire bus for ESNs.
Definition at line 364 of file lv_wrapper_FE.cpp.
DLLEXPORT short FEMCSetFEMode (short mode)
Set the FE operating mode to one of 0 -> Operational 1 -> Troubleshooting 2 -> Maintenance All other values are rejected.
Definition at line 405 of file lv_wrapper_FE.cpp.
DLLEXPORT short FESetCartridgeObserving (short port)
Definition at line 631 of file lv_wrapper_FE.cpp.
References validatePortNumber().
Referenced by main().
DLLEXPORT short FESetCartridgeOff (short port)
Definition at line 585 of file lv_wrapper_FE.cpp.
References FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by main().
DLLEXPORT short FESetCartridgeOn (short port)
Definition at line 607 of file lv_wrapper_FE.cpp.
References FrontEndLVWrapper::correctSISVoltageError, FrontEndLVWrapper::getSignalSourceImpl(), and validatePortNumber().
Referenced by main().
DLLEXPORT short FEStartHealthCheck (short isPASData, short fullAuto)
Set initial conditions for front end overall and cartridge health check.
if isPASData is nonzero, data will be stored as PAS reference data, else as healthcheck data. if fullAuto is nonzero, all cartridges will be tested one at a time with 15 minutes warm-up time.
Definition at line 529 of file lv_wrapper_FE.cpp.
DLLEXPORT short fetimGetMonitor (FETIMData_t * target)
Definition at line 1887 of file lv_wrapper_FE.cpp.
References FETIMData_t::AIRFLOW1, FETIMData_t::AIRFLOW2, FETIMData_t::AIRFLOW_OOR, FETIMImpl::FETIM_t::airflowSensorOOR_value, FETIMData_t::COMP_CABLE_STATUS, FETIMData_t::COMP_INTERLOCK_STATUS, FETIMData_t::COMP_STATUS, FrontEndLVWrapper::debugLVStructures, FETIMData_t::DELAY_SHUTDOWN_TRIG, FETIMImpl::FETIM_t::delayShutdownTriggered_value, FETIMData_t::EXTERNAL_TEMP1, FETIMData_t::EXTERNAL_TEMP1_OOR, FETIMData_t::EXTERNAL_TEMP2, FETIMData_t::EXTERNAL_TEMP2_OOR, FETIMImpl::FETIM_t::externalTemperature1_value, FETIMImpl::FETIM_t::externalTemperature2_value, FETIMImpl::FETIM_t::externalTemperatureOOR1_value, FETIMImpl::FETIM_t::externalTemperatureOOR2_value, FETIMData_t::FINAL_SHUTDOWN_TRIG, FETIMImpl::FETIM_t::finalShutdownTriggered_value, FETIMImpl::FETIM_t::getAirflowSensor1_value, FETIMImpl::FETIM_t::getAirflowSensor2_value, FETIMImpl::FETIM_t::getCompressorCableStatus_value, FETIMImpl::FETIM_t::getCompressorInterlockStatus_value, FETIMImpl::FETIM_t::getCompressorStatus_value, FETIMData_t::GLITCH_COUNTER_TRIG, FETIMData_t::GLITCH_VALUE, FETIMImpl::FETIM_t::glitchCounterTriggered_value, FETIMImpl::FETIM_t::glitchValue_value, FETIMData_t::HE2_PRESSURE, FETIMData_t::HE2_PRESSURE_OOR, FETIMImpl::FETIM_t::heliumBufferPressure_value, FETIMImpl::FETIM_t::heliumBufferPressureOOR_value, FETIMData_t::INTERNAL_TEMP1, FETIMData_t::INTERNAL_TEMP2, FETIMData_t::INTERNAL_TEMP3, FETIMData_t::INTERNAL_TEMP4, FETIMData_t::INTERNAL_TEMP5, FETIMData_t::INTERNAL_TEMP_OOR, FETIMImpl::FETIM_t::internalTemperature1_value, FETIMImpl::FETIM_t::internalTemperature2_value, FETIMImpl::FETIM_t::internalTemperature3_value, FETIMImpl::FETIM_t::internalTemperature4_value, FETIMImpl::FETIM_t::internalTemperature5_value, FETIMImpl::FETIM_t::internalTemperatureOOR_value, FETIMData_t::SENSOR_MULTI_FAIL, FETIMData_t::SENSOR_SINGLE_FAIL, FETIMImpl::FETIM_t::sensorMultiFailed_value, and FETIMImpl::FETIM_t::sensorSingleFailed_value.
DLLEXPORT short fetimSetTriggerDewarN2Fill (short enable)
Enable/disable the N2 fill trigger.
Definition at line 1446 of file lv_wrapper_FE.cpp.
References fetimSetTriggerDewarN2Fill().
Referenced by fetimSetTriggerDewarN2Fill().
DLLEXPORT short ifSwitchGetMonitor (IFSwitchData_t * target)
Definition at line 1790 of file lv_wrapper_FE.cpp.
References IFSwitchData_t::ATTENUATION_POL0SB1, IFSwitchData_t::ATTENUATION_POL0SB2, IFSwitchData_t::ATTENUATION_POL1SB1, IFSwitchData_t::ATTENUATION_POL1SB2, FrontEndLVWrapper::debugLVStructures, IFSwitchData_t::OBSERVING_BAND, IFSwitchImpl::IFSwitch_t::pol0Sb1AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol0Sb1Attenuation_value, IFSwitchImpl::IFSwitch_t::pol0Sb1TempServoEnable_value, IFSwitchImpl::IFSwitch_t::pol0Sb2AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol0Sb2Attenuation_value, IFSwitchImpl::IFSwitch_t::pol0Sb2TempServoEnable_value, IFSwitchImpl::IFSwitch_t::pol1Sb1AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol1Sb1Attenuation_value, IFSwitchImpl::IFSwitch_t::pol1Sb1TempServoEnable_value, IFSwitchImpl::IFSwitch_t::pol1Sb2AssemblyTemp_value, IFSwitchImpl::IFSwitch_t::pol1Sb2Attenuation_value, IFSwitchImpl::IFSwitch_t::pol1Sb2TempServoEnable_value, IFSwitchImpl::IFSwitch_t::switchCartridge_value, IFSwitchData_t::TEMPERATURE_POL0SB1, IFSwitchData_t::TEMPERATURE_POL0SB2, IFSwitchData_t::TEMPERATURE_POL1SB1, IFSwitchData_t::TEMPERATURE_POL1SB2, IFSwitchData_t::TEMPSERVO_POL0SB1, IFSwitchData_t::TEMPSERVO_POL0SB2, IFSwitchData_t::TEMPSERVO_POL1SB1, and IFSwitchData_t::TEMPSERVO_POL1SB2.
DLLEXPORT short ifSwitchSetAttenuation (short pol, short sb, short atten)
Set the IF switch attenuator(s) 0-15 dB If pol < 0 or sb < 1, all four attenuators will be set the same.
Definition at line 1382 of file lv_wrapper_FE.cpp.
References ifSwitchSetAttenuation().
Referenced by ifSwitchSetAttenuation().
DLLEXPORT short ifSwitchSetEnableTempServo (short pol, short sb, short enable)
Enable/disable the IF switch temperature servo.
If pol < 0 or sb < 1, all four temp servos will be set the same.
Definition at line 1390 of file lv_wrapper_FE.cpp.
References ifSwitchSetEnableTempServo().
Referenced by ifSwitchSetEnableTempServo().
DLLEXPORT short lprGetMonitor (LPRData_t * target)
Definition at line 1859 of file lv_wrapper_FE.cpp.
References FrontEndLVWrapper::debugLVStructures, LPRData_t::EDFA_LASER_DRIVE_CURRENT, LPRData_t::EDFA_LASER_PHOTODETECT_CURRENT, LPRData_t::EDFA_LASER_PUMP_TEMPERATURE, LPRData_t::EDFA_MODULATION_INPUT, LPRData_t::EDFA_PHOTODETECT_CURRENT, LPRData_t::EDFA_PHOTODETECT_POWER, LPRImpl::LPR_t::EDFALaserDriveCurrent_value, LPRImpl::LPR_t::EDFALaserPhotoDetectCurrent_value, LPRImpl::LPR_t::EDFALaserPumpTemperature_value, LPRImpl::LPR_t::EDFAModulationInput_value, LPRImpl::LPR_t::EDFAPhotoDetectCurrent_value, LPRImpl::LPR_t::EDFAPhotoDetectPower_value, LPRData_t::LPR_TEMPERATURE_0, LPRData_t::LPR_TEMPERATURE_1, LPRImpl::LPR_t::LPRTemperature0_value, LPRImpl::LPR_t::LPRTemperature1_value, LPRData_t::OPTICAL_SWITCH_BUSY, LPRData_t::OPTICAL_SWITCH_PORT, LPRData_t::OPTICAL_SWITCH_SHUTTER, LPRData_t::OPTICAL_SWITCH_STATE, LPRImpl::LPR_t::opticalSwitchBusy_value, LPRImpl::LPR_t::opticalSwitchPort_value, LPRImpl::LPR_t::opticalSwitchShutter_value, and LPRImpl::LPR_t::opticalSwitchState_value.
DLLEXPORT short lprSetEDFAModulationInput (float value)
Sets the EDFA modulation input value in Volts.
Definition at line 1478 of file lv_wrapper_FE.cpp.
References lprSetEDFAModulationInput().
Referenced by lprSetEDFAModulationInput().
DLLEXPORT short lprSetOpticalSwitchForceShutter ()
Enables the shutter (disables the laser) more forcefully (for debugging).
Definition at line 1470 of file lv_wrapper_FE.cpp.
References lprSetOpticalSwitchForceShutter().
Referenced by lprSetOpticalSwitchForceShutter().
DLLEXPORT short lprSetOpticalSwitchPort (short port)
Set the optical switch output port and disable the shutter.
Definition at line 1454 of file lv_wrapper_FE.cpp.
References lprSetOpticalSwitchPort().
Referenced by lprSetOpticalSwitchPort().
DLLEXPORT short lprSetOpticalSwitchShutter ()
Enables the shutter (disables the laser).
Definition at line 1462 of file lv_wrapper_FE.cpp.
References lprSetOpticalSwitchShutter().
Referenced by lprSetOpticalSwitchShutter().
DLLEXPORT short powerGetMonitorModule (short port, PowerModuleData_t * target)
Definition at line 1759 of file lv_wrapper_FE.cpp.
References PowerModuleData_t::CURRENT_N15V, PowerModuleData_t::CURRENT_N6V, PowerModuleData_t::CURRENT_P15V, PowerModuleData_t::CURRENT_P24V, PowerModuleData_t::CURRENT_P6V, PowerModuleData_t::CURRENT_P8V, PowerModuleImpl::PowerModule_t::currentN15V_value, PowerModuleImpl::PowerModule_t::currentN6V_value, PowerModuleImpl::PowerModule_t::currentP15V_value, PowerModuleImpl::PowerModule_t::currentP24V_value, PowerModuleImpl::PowerModule_t::currentP6V_value, PowerModuleImpl::PowerModule_t::currentP8V_value, FrontEndLVWrapper::debugLVStructures, PowerModuleImpl::PowerModule_t::enableModule_value, powerGetMonitorModule(), validatePortNumber(), PowerModuleData_t::VOLTAGE_N15V, PowerModuleData_t::VOLTAGE_N6V, PowerModuleData_t::VOLTAGE_P15V, PowerModuleData_t::VOLTAGE_P24V, PowerModuleData_t::VOLTAGE_P6V, PowerModuleData_t::VOLTAGE_P8V, PowerModuleImpl::PowerModule_t::voltageN15V_value, PowerModuleImpl::PowerModule_t::voltageN6V_value, PowerModuleImpl::PowerModule_t::voltageP15V_value, PowerModuleImpl::PowerModule_t::voltageP24V_value, PowerModuleImpl::PowerModule_t::voltageP6V_value, and PowerModuleImpl::PowerModule_t::voltageP8V_value.
Referenced by powerGetMonitorModule().
DLLEXPORT short randomizeAnalogMonitors (short enable)
enable/disble random ordering on analog monitor points.
Definition at line 739 of file lv_wrapper_FE.cpp.
References FEHardwareDevice::randomizeAnalogMonitors().
bool validatePortNumber (short & port, bool * isSignalSource = NULL)
Definition at line 568 of file lv_wrapper_FE.cpp.
Referenced by cartAbortMeasurement(), cartAdjustLOPowerAmps(), cartAdjustPLL(), cartAdjustYTO(), cartGetLocked(), cartGetLOFrequency(), cartGetLOPADrainVoltageSetting(), cartGetMonitorAMC(), cartGetMonitorAux(), cartGetMonitorLNA(), cartGetMonitorPA(), cartGetMonitorPhotomixer(), cartGetMonitorPLL(), cartGetMonitorSIS(), cartGetMonitorTemp(), cartGetMonitorYTO(), cartGetSISMagnet(), cartGetVJVD(), cartGetXYData(), cartLockPLL(), cartMeasureFineLOSweep(), cartMeasureIFPowerVsVD(), cartMeasureIFPowerVsVJ(), cartMeasureIJvsSISMagnet(), cartMeasureIVCurve(), cartMixerDeflux(), cartNullPLLIntegrator(), cartOptimizeIFPower(), cartPauseMonitor(), cartSetAMC(), cartSetEnableLNABias(), cartSetEnableLNALEDs(), cartSetEnableLO(), cartSetEnablePhotomixer(), cartSetEnableSISHeaters(), cartSetIFPower(), cartSetLNABias(), cartSetLOFrequency(), cartSetLOPower(), cartSetLOPowerAmps(), cartSetSISBias(), cartSetSISMagnet(), cartSetVJVD(), FEClearCartridgeObserving(), FEGetCartridgeState(), FESetCartridgeObserving(), FESetCartridgeOff(), FESetCartridgeOn(), and powerGetMonitorModule().