FrontEndControl2: DLL/lv_structs.h File Reference
lv_structs.h File Reference
#include <iostream>
#include <string.h>
Classes
struct CartStateData_t
struct CartIFPowerData_t
struct CartYTOData_t
struct CartPhotomixerData_t
struct CartPLLData_t
struct CartAMCData_t
struct CartPAData_t
struct CartTempData_t
struct CartSISData_t
struct CartLNAData_t
struct CartAuxData_t
struct PowerModuleData_t
struct IFSwitchData_t
struct CryostatData_t
struct LPRData_t
struct LORTMStatus_t
struct LORTMLasers_t
struct LORTMOther_t
struct FETIMData_t
struct CompressorData_t
Functions
bool LVGetBool (int field, const unsigned char data[], const int offsets[])
void LVSetBool (int field, unsigned char data[], const int offsets[], const bool &_value)
float LVGetFloat (int field, const unsigned char data[], const int offsets[])
void LVSetFloat (int field, unsigned char data[], const int offsets[], const float &value)
short LVGetShort (int field, const unsigned char data[], const int offsets[])
void LVSetShort (int field, unsigned char data[], const int offsets[], const short &value)
unsigned long LVGetULong (int field, const unsigned char data[], const int offsets[])
void LVSetULong (int field, unsigned char data[], const int offsets[], const unsigned long &value)
unsigned char LVGetByte (int field, const unsigned char data[], const int offsets[])
void LVSetByte (int field, unsigned char data[], const int offsets[], const unsigned char &value)
std::ostream & operator<< (std::ostream &out, const CartStateData_t &data)
stream output for debugging CartStateData_t
std::ostream & operator<< (std::ostream &out, const CartIFPowerData_t &data)
stream output for debugging CartStateData_t
std::ostream & operator<< (std::ostream &out, const CartYTOData_t &data)
stream output for debugging CartYTOData_t
std::ostream & operator<< (std::ostream &out, const CartPhotomixerData_t &data)
stream output for debugging CartPhotomixerData_t
std::ostream & operator<< (std::ostream &out, const CartPLLData_t &data)
stream output for debugging CartPLLData_t
std::ostream & operator<< (std::ostream &out, const CartAMCData_t &data)
stream output for debugging CartAMCData_t
std::ostream & operator<< (std::ostream &out, const CartPAData_t &data)
stream output for debugging CartPAData_t
std::ostream & operator<< (std::ostream &out, const CartTempData_t &data)
stream output for debugging CartTempData_t
std::ostream & operator<< (std::ostream &out, const CartSISData_t &data)
stream output for debugging CartSISData_t
std::ostream & operator<< (std::ostream &out, const CartLNAData_t &data)
stream output for debugging CartLNAData_t
std::ostream & operator<< (std::ostream &out, const CartAuxData_t &data)
stream output for debugging CartAuxData_t
std::ostream & operator<< (std::ostream &out, const PowerModuleData_t &data)
stream output for debugging CartAuxData_t
std::ostream & operator<< (std::ostream &out, const IFSwitchData_t &data)
stream output for debugging IFSwitchData_t
std::ostream & operator<< (std::ostream &out, const CryostatData_t &data)
stream output for debugging CryostatData_t
std::ostream & operator<< (std::ostream &out, const LPRData_t &data)
stream output for debugging LPRData_t
std::ostream & operator<< (std::ostream &out, const LORTMStatus_t &data)
stream output for debugging LORTMStatus_t
std::ostream & operator<< (std::ostream &out, const LORTMLasers_t &data)
stream output for debugging LORTMLasers_t
std::ostream & operator<< (std::ostream &out, const LORTMOther_t &data)
stream output for debugging LORTMOther_t
std::ostream & operator<< (std::ostream &out, const FETIMData_t &data)
stream output for debugging FETIMData_t
std::ostream & operator<< (std::ostream &out, const CompressorData_t &data)
stream output for debugging FETIMData_t
Function Documentation
bool LVGetBool (int field, const unsigned char data[], const int offsets[]) inline
Definition at line 58 of file lv_structs.h.
Referenced by CartStateData_t::getBool(), CartPLLData_t::getBool(), CryostatData_t::getBool(), LORTMStatus_t::getBool(), FETIMData_t::getBool(), CompressorData_t::getBool(), CartPhotomixerData_t::getEnable(), CartLNAData_t::getEnable(), PowerModuleData_t::getEnable(), CartAuxData_t::getLEDEnable(), and CartSISData_t::getOpenLoop().
unsigned char LVGetByte (int field, const unsigned char data[], const int offsets[]) inline
Definition at line 95 of file lv_structs.h.
Referenced by CartAMCData_t::getByte(), IFSwitchData_t::getByte(), CryostatData_t::getByte(), LPRData_t::getByte(), LORTMStatus_t::getByte(), and LORTMLasers_t::getByte().
float LVGetFloat (int field, const unsigned char data[], const int offsets[]) inline
Definition at line 68 of file lv_structs.h.
Referenced by CartIFPowerData_t::getFloat(), CartPhotomixerData_t::getFloat(), CartPLLData_t::getFloat(), CartAMCData_t::getFloat(), CartPAData_t::getFloat(), CartTempData_t::getFloat(), CartSISData_t::getFloat(), CartLNAData_t::getFloat(), PowerModuleData_t::getFloat(), IFSwitchData_t::getFloat(), CryostatData_t::getFloat(), LPRData_t::getFloat(), LORTMLasers_t::getFloat(), LORTMOther_t::getFloat(), FETIMData_t::getFloat(), CompressorData_t::getFloat(), and CartAuxData_t::getHeaterCurrent().
short LVGetShort (int field, const unsigned char data[], const int offsets[]) inline
Definition at line 77 of file lv_structs.h.
Referenced by CartYTOData_t::getCoarseTune(), and LORTMStatus_t::getShort().
unsigned long LVGetULong (int field, const unsigned char data[], const int offsets[]) inline
Definition at line 86 of file lv_structs.h.
Referenced by CompressorData_t::getULong().
void LVSetBool (int field, unsigned char data[], const int offsets[], const bool & _value) inline
Definition at line 63 of file lv_structs.h.
Referenced by CartStateData_t::setBool(), CartPLLData_t::setBool(), CryostatData_t::setBool(), LORTMStatus_t::setBool(), FETIMData_t::setBool(), CompressorData_t::setBool(), CartPhotomixerData_t::setEnable(), CartLNAData_t::setEnable(), PowerModuleData_t::setEnable(), CartAuxData_t::setLEDEnable(), and CartSISData_t::setOpenLoop().
void LVSetByte (int field, unsigned char data[], const int offsets[], const unsigned char & value) inline
Definition at line 100 of file lv_structs.h.
Referenced by CartAMCData_t::setByte(), IFSwitchData_t::setByte(), CryostatData_t::setByte(), LPRData_t::setByte(), LORTMStatus_t::setByte(), and LORTMLasers_t::setByte().
void LVSetFloat (int field, unsigned char data[], const int offsets[], const float & value) inline
Definition at line 73 of file lv_structs.h.
Referenced by CartIFPowerData_t::setFloat(), CartPhotomixerData_t::setFloat(), CartPLLData_t::setFloat(), CartAMCData_t::setFloat(), CartPAData_t::setFloat(), CartTempData_t::setFloat(), CartSISData_t::setFloat(), CartLNAData_t::setFloat(), PowerModuleData_t::setFloat(), IFSwitchData_t::setFloat(), CryostatData_t::setFloat(), LPRData_t::setFloat(), LORTMLasers_t::setFloat(), LORTMOther_t::setFloat(), FETIMData_t::setFloat(), CompressorData_t::setFloat(), and CartAuxData_t::setHeaterCurrent().
void LVSetShort (int field, unsigned char data[], const int offsets[], const short & value) inline
Definition at line 82 of file lv_structs.h.
Referenced by CartYTOData_t::setCoarseTune(), and LORTMStatus_t::setShort().
void LVSetULong (int field, unsigned char data[], const int offsets[], const unsigned long & value) inline
Definition at line 91 of file lv_structs.h.
Referenced by CompressorData_t::setULong().
std::ostream& operator<< (std::ostream & out, const CartStateData_t & data) inline
stream output for debugging CartStateData_t
Definition at line 143 of file lv_structs.h.
References CartStateData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartIFPowerData_t & data) inline
stream output for debugging CartStateData_t
Definition at line 191 of file lv_structs.h.
References CartIFPowerData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartYTOData_t & data) inline
stream output for debugging CartYTOData_t
Definition at line 229 of file lv_structs.h.
References CartYTOData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartPhotomixerData_t & data) inline
stream output for debugging CartPhotomixerData_t
Definition at line 267 of file lv_structs.h.
References CartPhotomixerData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartPLLData_t & data) inline
stream output for debugging CartPLLData_t
Definition at line 313 of file lv_structs.h.
References CartPLLData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartAMCData_t & data) inline
stream output for debugging CartAMCData_t
Definition at line 361 of file lv_structs.h.
References CartAMCData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartPAData_t & data) inline
stream output for debugging CartPAData_t
Definition at line 399 of file lv_structs.h.
References CartPAData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartTempData_t & data) inline
stream output for debugging CartTempData_t
Definition at line 435 of file lv_structs.h.
References CartTempData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartSISData_t & data) inline
stream output for debugging CartSISData_t
Definition at line 475 of file lv_structs.h.
References CartSISData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartLNAData_t & data) inline
stream output for debugging CartLNAData_t
Definition at line 520 of file lv_structs.h.
References CartLNAData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CartAuxData_t & data) inline
stream output for debugging CartAuxData_t
Definition at line 557 of file lv_structs.h.
References CartAuxData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const PowerModuleData_t & data) inline
stream output for debugging CartAuxData_t
Definition at line 605 of file lv_structs.h.
References PowerModuleData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const IFSwitchData_t & data) inline
stream output for debugging IFSwitchData_t
Definition at line 654 of file lv_structs.h.
References IFSwitchData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CryostatData_t & data) inline
stream output for debugging CryostatData_t
Definition at line 720 of file lv_structs.h.
References CryostatData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const LPRData_t & data) inline
stream output for debugging LPRData_t
Definition at line 768 of file lv_structs.h.
References LPRData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const LORTMStatus_t & data) inline
stream output for debugging LORTMStatus_t
Definition at line 821 of file lv_structs.h.
References LORTMStatus_t::streamOut().
std::ostream& operator<< (std::ostream & out, const LORTMLasers_t & data) inline
stream output for debugging LORTMLasers_t
Definition at line 869 of file lv_structs.h.
References LORTMLasers_t::streamOut().
std::ostream& operator<< (std::ostream & out, const LORTMOther_t & data) inline
stream output for debugging LORTMOther_t
Definition at line 914 of file lv_structs.h.
References LORTMOther_t::streamOut().
std::ostream& operator<< (std::ostream & out, const FETIMData_t & data) inline
stream output for debugging FETIMData_t
Definition at line 973 of file lv_structs.h.
References FETIMData_t::streamOut().
std::ostream& operator<< (std::ostream & out, const CompressorData_t & data) inline
stream output for debugging FETIMData_t
Definition at line 1034 of file lv_structs.h.
References CompressorData_t::streamOut().