FrontEndControl2: DLL/lv_wrapper_sigSrc.cpp File Reference
lv_wrapper_sigSrc.cpp File Reference
#include "lv_wrapper_sigSrc.h"
#include "lv_wrapper.h"
#include "FEMCEventQueue.h"
#include "SignalSourceImpl.h"
#include "logger.h"
#include "iniFile.h"
#include "stringConvert.h"
#include "splitPath.h"
#include "CONFIG/ConfigProviderIniFile.h"
#include "CONFIG/ConfigManager.h"
#include "WCAImpl.h"
Namespaces
FrontEndLVWrapper
Functions
SignalSourceImpl * FrontEndLVWrapper::getSignalSourceImpl ()
DLLEXPORT short sigSrcControlInit ()
Initialize the control connection to the signal source.
DLLEXPORT short sigSrcControlShutdown ()
Destroy the control connection to the signal source.
DLLEXPORT short sigSrcExit ()
Shutdown the firmware on the FE M&C module.
DLLEXPORT short sigSrcEnableMonitoring (short enable)
Start/stop the monitoring thread for the signal source.
DLLEXPORT short sigSrcGetNextConfiguration (short reset, short *configId, char *description)
Iterate through the list of available configurations.
DLLEXPORT short sigSrcLoadConfiguration (short configId)
Configure the FE from the configuration database according to the given configId.
DLLEXPORT short sigSrcGetBand (short *band_p)
Get the cartridge band associated with the loaded configuration.
DLLEXPORT short sigSrcGetAMBSIInfo (char *_serialNum, char *_firmwareRev, unsigned long *numErrors, unsigned long *numTransactions)
Get the AMBSI1's monitor data.
DLLEXPORT short sigSrcGetAMBSITemperature (float *temperature)
Get the AMBSI1's temperature.
DLLEXPORT short sigSrcGetFirmwareInfo (char *_AMBSILibraryVersion, char *_FEMCFirmwareVersion, char *_FEMCFPGAVersion)
Get the FE M&C firmware version information.
DLLEXPORT short sigSrcGetNumCartridgesOn ()
ERROR -1 0-10 number of cartridges ON.
Variables
unsigned long FrontEndLVWrapper::CANChannelSigSrc = 0
unsigned long FrontEndLVWrapper::nodeAddressSigSrc = 0x14
unsigned long FrontEndLVWrapper::facilityIdSigSrc = 40
unsigned long FrontEndLVWrapper::configIdSigSrc = 1
std::string FrontEndLVWrapper::sigSrcIniFilename
Function Documentation
DLLEXPORT short sigSrcControlInit ()
Initialize the control connection to the signal source.
Definition at line 60 of file lv_wrapper_sigSrc.cpp.
References FEMCEventQueue::addStatusMessage(), FrontEndLVWrapper::CAN_noTransmit, FrontEndLVWrapper::CANChannelSigSrc, FrontEndLVWrapper::configIdSigSrc, FrontEndLVWrapper::facilityIdSigSrc, FrontEndLVWrapper::iniFileName, LVWrapperInit(), FrontEndLVWrapper::nodeAddressSigSrc, FrontEndLVWrapper::sigSrcIniFilename, and sigSrcLoadConfiguration().
Referenced by main().
DLLEXPORT short sigSrcControlShutdown ()
Destroy the control connection to the signal source.
Definition at line 155 of file lv_wrapper_sigSrc.cpp.
References LVWrapperShutdown(), and WHACK.
Referenced by main().
DLLEXPORT short sigSrcEnableMonitoring (short enable)
Start/stop the monitoring thread for the signal source.
Normally the signal source starts with monitoring disabled.
Definition at line 180 of file lv_wrapper_sigSrc.cpp.
DLLEXPORT short sigSrcExit ()
Shutdown the firmware on the FE M&C module.
Definition at line 173 of file lv_wrapper_sigSrc.cpp.
DLLEXPORT short sigSrcGetAMBSIInfo (char * _serialNum, char * _firmwareRev, unsigned long * numErrors, unsigned long * numTransactions)
Get the AMBSI1's monitor data.
Definition at line 289 of file lv_wrapper_sigSrc.cpp.
Referenced by main().
DLLEXPORT short sigSrcGetAMBSITemperature (float * temperature)
Get the AMBSI1's temperature.
Definition at line 305 of file lv_wrapper_sigSrc.cpp.
Referenced by main().
DLLEXPORT short sigSrcGetBand (short * band_p)
Get the cartridge band associated with the loaded configuration.
Definition at line 274 of file lv_wrapper_sigSrc.cpp.
DLLEXPORT short sigSrcGetFirmwareInfo (char * _AMBSILibraryVersion, char * _FEMCFirmwareVersion, char * _FEMCFPGAVersion)
Get the FE M&C firmware version information.
Definition at line 312 of file lv_wrapper_sigSrc.cpp.
Referenced by main().
DLLEXPORT short sigSrcGetNextConfiguration (short reset, short * configId, char * description)
Iterate through the list of available configurations.
Definition at line 191 of file lv_wrapper_sigSrc.cpp.
References FrontEndLVWrapper::facilityIdSigSrc, and FrontEndLVWrapper::sigSrcIniFilename.
Referenced by main().
DLLEXPORT short sigSrcGetNumCartridgesOn ()
ERROR -1 0-10 number of cartridges ON.
Definition at line 328 of file lv_wrapper_sigSrc.cpp.
DLLEXPORT short sigSrcLoadConfiguration (short configId)
Configure the FE from the configuration database according to the given configId.
Definition at line 228 of file lv_wrapper_sigSrc.cpp.
References FEConfig::WCAConfig::band_m, FrontEndLVWrapper::CANChannelSigSrc, FrontEndLVWrapper::configIdSigSrc, FEConfig::ConfigManager::configure(), FEConfig::WCAConfig::ESN_m, FrontEndLVWrapper::facilityIdSigSrc, FEConfig::Configuration::getCartAssemblyConfig(), FEConfig::Configuration::load(), FrontEndLVWrapper::nodeAddressSigSrc, FrontEndLVWrapper::sigSrcIniFilename, and WHACK.
Referenced by main(), and sigSrcControlInit().