FrontEndControl2: DLL/lv_wrapper_Compressor.cpp File Reference
lv_wrapper_Compressor.cpp File Reference
#include "lv_wrapper_Compressor.h"
#include "lv_wrapper.h"
#include "lv_structs.h"
#include "iniFile.h"
#include "logger.h"
#include "FrontEndAMB/NICANBusInterface.h"
#include "FrontEndAMB/SocketClientBusInterface.h"
#include "stringConvert.h"
#include "CompressorImpl.h"
#include <iomanip>
Namespaces
FrontEndLVWrapper
Functions
DLLEXPORT short CompressorControlInit ()
Initialize the control connection to the FE.
DLLEXPORT short CompressorControlShutdown ()
Destroy the control connection to the FE.
DLLEXPORT short CompressorGetAMBSIInfo (char *_serialNum, char *_firmwareRev, unsigned long *numErrors, unsigned long *numTransactions)
Get the AMBSI standard data items.
DLLEXPORT short CompressorGetAMBSITemperature (float *temperature)
Get the AMBSI temperature.
DLLEXPORT short CompressorGetSWRevisionLevel (char *_swRev)
Get the compressor embedded software revision.
DLLEXPORT short CompressorGetECUType (short *val)
Get the ECU type connected to the compressor M&C module.
DLLEXPORT short CompressorGetInterlockOverride (short *val)
DLLEXPORT short CompressorSetRemoteDrive (short val)
Enable/disable remote drive.
DLLEXPORT short CompressorSetRemoteReset ()
Reset the compressor.
DLLEXPORT short CompressorSetFaultLatchReset ()
Reset the compressor M&C module fault latch.
DLLEXPORT short CompressorGetMonitorData (CompressorData_t *target)
Get all monitor points for the compressor.
Variables
unsigned long FrontEndLVWrapper::CANChannelCompressor = 0
unsigned long FrontEndLVWrapper::nodeAddressCompressor = 0
Function Documentation
DLLEXPORT short CompressorControlInit ()
Initialize the control connection to the FE.
Definition at line 46 of file lv_wrapper_Compressor.cpp.
References FrontEndLVWrapper::CANChannelCompressor, FrontEndLVWrapper::iniFileName, LVWrapperInit(), FrontEndLVWrapper::nodeAddressCompressor, and FrontEndLVWrapper::thermalLogInterval.
Referenced by FEControlInit().
DLLEXPORT short CompressorControlShutdown ()
Destroy the control connection to the FE.
Definition at line 96 of file lv_wrapper_Compressor.cpp.
References LVWrapperShutdown(), and WHACK.
Referenced by FEControlShutdown().
DLLEXPORT short CompressorGetAMBSIInfo (char * _serialNum, char * _firmwareRev, unsigned long * numErrors, unsigned long * numTransactions)
Get the AMBSI standard data items.
Definition at line 115 of file lv_wrapper_Compressor.cpp.
DLLEXPORT short CompressorGetAMBSITemperature (float * temperature)
Get the AMBSI temperature.
Definition at line 132 of file lv_wrapper_Compressor.cpp.
DLLEXPORT short CompressorGetECUType (short * val)
Get the ECU type connected to the compressor M&C module.
Definition at line 147 of file lv_wrapper_Compressor.cpp.
DLLEXPORT short CompressorGetInterlockOverride (short * val)
Definition at line 154 of file lv_wrapper_Compressor.cpp.
DLLEXPORT short CompressorGetMonitorData (CompressorData_t * target)
Get all monitor points for the compressor.
Definition at line 182 of file lv_wrapper_Compressor.cpp.
References CompressorData_t::AUX_TRANSDUCER, FrontEndLVWrapper::debugLVStructures, CompressorData_t::DRIVE_INDICATOR, CompressorData_t::FAULT_STATUS, CompressorData_t::FETIM_CABLE_ERROR, CompressorData_t::FETIM_STATUS, CompressorImpl::Compressor_t::getAuxTransducer_value, CompressorImpl::Compressor_t::getDriveIndicator_value, CompressorImpl::Compressor_t::getFaultStatusError_value, CompressorImpl::Compressor_t::getFETIMCableError_value, CompressorImpl::Compressor_t::getFETIMStatusError_value, CompressorImpl::Compressor_t::getICCUCableError_value, CompressorImpl::Compressor_t::getICCUStatusError_value, CompressorImpl::Compressor_t::getInterlockOverride_value, CompressorImpl::Compressor_t::getPressureAlarm_value, CompressorImpl::Compressor_t::getReturnLinePressure_value, CompressorImpl::Compressor_t::getSupplyPressure_value, CompressorImpl::Compressor_t::getTemp1_value, CompressorImpl::Compressor_t::getTemp2_value, CompressorImpl::Compressor_t::getTemp3_value, CompressorImpl::Compressor_t::getTemp4_value, CompressorImpl::Compressor_t::getTempAlarm_value, CompressorImpl::Compressor_t::getTimeSinceLastPowerOff_value, CompressorImpl::Compressor_t::getTimeSinceLastPowerOn_value, CompressorData_t::ICCU_CABLE_ERROR, CompressorData_t::ICCU_STATUS, CompressorData_t::INTERLOCK_OVERRIDE, CompressorData_t::PRESSURE_ALARM, CompressorData_t::RETURN_PRESSURE, CompressorData_t::SUPPLY_PRESSURE, CompressorData_t::TEMP1, CompressorData_t::TEMP2, CompressorData_t::TEMP3, CompressorData_t::TEMP4, CompressorData_t::TEMP_ALARM, CompressorData_t::TIME_SINCE_POWER_OFF, and CompressorData_t::TIME_SINCE_POWER_ON.
DLLEXPORT short CompressorGetSWRevisionLevel (char * _swRev)
Get the compressor embedded software revision.
Definition at line 139 of file lv_wrapper_Compressor.cpp.
DLLEXPORT short CompressorSetFaultLatchReset ()
Reset the compressor M&C module fault latch.
Definition at line 175 of file lv_wrapper_Compressor.cpp.
DLLEXPORT short CompressorSetRemoteDrive (short val)
Enable/disable remote drive.
Definition at line 161 of file lv_wrapper_Compressor.cpp.
DLLEXPORT short CompressorSetRemoteReset ()
Reset the compressor.
Definition at line 168 of file lv_wrapper_Compressor.cpp.