FrontEndControl2: DLL/lv_wrapper.cpp File Reference
lv_wrapper.cpp File Reference
#include "lv_wrapper.h"
#include "lv_structs.h"
#include "iniFile.h"
#include "logger.h"
#include "setTimeStamp.h"
#include "stringConvert.h"
#include "FrontEndAMB/NICANBusInterface.h"
#include "FrontEndAMB/SocketClientBusInterface.h"
#include "FEBASE/FEHardwareDevice.h"
#include "LOGGER/AmbTransactionLogger.h"
#include "LOGGER/logDir.h"
#include "OPTIMIZE/OptimizeBase.h"
#include "FEMCEventQueue.h"
#include "DLL/SWVersion.h"
Namespaces
FrontEndLVWrapper
Functions
short LVWrapperInit ()
Initialize the shared data.
short LVWrapperShutdown ()
Disconnect from the shared data.
DLLEXPORT short getSoftwareVersion (char *versionString)
Get the FrontEndControl.DLL version string.
DLLEXPORT short getDataPath (char *pathString)
Get the configured logDir path.
DLLEXPORT short subscribeForEvents (short doSubscribe)
subscribe/unsubscribe for events.
DLLEXPORT short getNextEvent (short *eventCode, short *band, short *pol, short *param, short *progress, short messageLen, char *message)
Poll the event queue and remove the next event, if any.
DLLEXPORT short TestSocketClient ()
Variables
FILE * FrontEndLVWrapper::logStream = NULL
bool FrontEndLVWrapper::logTransactions = false
bool FrontEndLVWrapper::debugLVStructures = false
bool FrontEndLVWrapper::CAN_noTransmit = false
std::string FrontEndLVWrapper::iniFileName
unsigned int FrontEndLVWrapper::thermalLogInterval = 30
Function Documentation
DLLEXPORT short getDataPath (char * pathString)
Get the configured logDir path.
Definition at line 193 of file lv_wrapper.cpp.
References FEConfig::getLogDir(), and FEConfig::logDir.
DLLEXPORT short getNextEvent (short * eventCode, short * band, short * pol, short * param, short * progress, short messageLen, char * message)
Poll the event queue and remove the next event, if any.
Definition at line 212 of file lv_wrapper.cpp.
References FEMCEventQueue::Event::band_m, FEMCEventQueue::Event::eventCode_m, FEMCEventQueue::getNextEvent(), FEMCEventQueue::Event::message_m, FEMCEventQueue::Event::param_m, FEMCEventQueue::Event::pol_m, and FEMCEventQueue::Event::progress_m.
DLLEXPORT short getSoftwareVersion (char * versionString)
Get the FrontEndControl.DLL version string.
Definition at line 186 of file lv_wrapper.cpp.
References FECONTROL_SW_VERSION_STRING.
short LVWrapperInit ()
Initialize the shared data.
Definition at line 53 of file lv_wrapper.cpp.
References FrontEndLVWrapper::CAN_noTransmit, FEMCEventQueue::createInstance(), FrontEndLVWrapper::debugLVStructures, FECONTROL_SW_VERSION_STRING, FrontEndLVWrapper::iniFileName, FEConfig::logDir, FrontEndLVWrapper::logStream, FrontEndLVWrapper::logTransactions, FEConfig::setLogDir(), FEHardwareDevice::setLogger(), FEHardwareDevice::setMaxMonitorErrors(), FrontEndLVWrapper::thermalLogInterval, and WHACK.
Referenced by CompressorControlInit(), FEControlInit(), LORTMControlInit(), and sigSrcControlInit().
short LVWrapperShutdown ()
Disconnect from the shared data.
Definition at line 159 of file lv_wrapper.cpp.
References FEHardwareDevice::clearLogger(), FEMCEventQueue::destroyInstance(), FrontEndLVWrapper::logStream, and WHACK.
Referenced by CompressorControlShutdown(), FEControlShutdown(), LORTMControlShutdown(), and sigSrcControlShutdown().
DLLEXPORT short subscribeForEvents (short doSubscribe)
subscribe/unsubscribe for events.
events will be generated only if there is at least one subscriber. pass 1 to subscribe, 0 to unsubscribe.
Definition at line 205 of file lv_wrapper.cpp.
References FEMCEventQueue::subscribe().
DLLEXPORT short TestSocketClient ()
Definition at line 238 of file lv_wrapper.cpp.
Referenced by main().