FrontEndControl2: FEConfig Namespace Reference
FEConfig Namespace Reference
namespace for all items relating to Front End configuration
Classes
class CartAssemblyConfig
holds the configuration for a ColdCart together with a WCA.
class CartAssemblyID
class ColdCartConfig
holds the configuration for a cold cartridge
class ConfigManager
ConfigManager uses a ConfigProvider load config parameters into a target FrontEndImpl or SignalSourceImpl.
class ConfigProvider
A ConfigProver loads FE configuration data from a database.
class ConfigProviderIniFile
Loads FE configuration data from a MySQL database connection.
class ConfigProviderMySQL
Loads FE configuration data from a MySQL database connection.
class Configuration
Uses the abstract ConfigProvider interface to load a Configuration record into memory.
class CryostatConfig
configuration data for the cryostat.
class FrontEndConfig
FrontEndConfig is an object with space for the config parameters front end and all of its subsystems.
class LPRConfig
configuration data for the LPR.
class MagnetParams
lookup table for SIS magnet bias parameters
class MixerParams
lookup table for SIS mixer voltage and current vs LO frequency
class ParamTable
A ParamTable is a 2-D table of float values, indexed by a double 'freq' column.
class ParamTableRow
A ParamTableRow is a 1-D array of float of a fixed size.
class PowerAmpParams
lookup table for LO power amp bias parameters
class PreampParams
lookup table for LNA bias parameters for a single polirization and sideband
class WCAConfig
Holds the configuration for a warm cartridge assembly and the associated first LO.
Functions
std::ostream & operator<< (std::ostream &out, const ColdCartConfig &config)
stream output for debugging ColdCartConfig
std::ostream & operator<< (std::ostream &out, const WCAConfig &config)
stream output for debugging WCAConfig
std::ostream & operator<< (std::ostream &out, const CartAssemblyID &id)
std::ostream & operator<< (std::ostream &out, const CartAssemblyConfig &config)
stream output for debugging CartAssemblyConfig
std::string TrimStr (const std::string &src, const std::string &c=" \t\r\n")
std::ostream & operator<< (std::ostream &out, const FrontEndConfig &config)
stream output for debugging FrontEndConfig
std::ostream & operator<< (std::ostream &out, const ParamTableRow &row)
stream output for debugging ParamTableRow
std::ostream & operator<< (std::ostream &out, const ParamTable &table)
stream output for debugging ParamTable
std::ostream & operator<< (std::ostream &out, const MixerParams &params)
stream output for debugging MixerParams
std::ostream & operator<< (std::ostream &out, const MagnetParams &params)
stream output for debugging MagnetParams
std::ostream & operator<< (std::ostream &out, const PreampParams &params)
stream output for debugging PreampParams
std::ostream & operator<< (std::ostream &out, const PowerAmpParams &params)
stream output for debugging PowerAmpParams
std::ostream & operator<< (std::ostream &out, const CryostatConfig &config)
stream output for debugging CryostatConfig
std::ostream & operator<< (std::ostream &out, const LPRConfig &config)
stream output for debugging LPRConfig
const std::string & getLogDir ()
void setLogDir (const std::string newValue)
Variables
std::string logDir
Detailed Description
namespace for all items relating to Front End configuration
The following band-specific tuning behaviors are supported: band3: 2 pols, 2 SIS/pol, no magnets.
SIS voltage (VJ) and LO PA drain voltage (VD) are optimized for max output power and lowest noise. band6: 2 pols, 2 SIS/pol, one magnet coil/pol controls both junctions (IMag01, IMag11). LO PA (VD) is adjusted to set target SIS current (IJ). band7: 2 pols, 2 SIS/pol, separate magnets on all junctions. Magnet current is optimized to minimize junction Josephson current with VJ=0. LO PA (VD) is adjusted to set target SIS current (IJ). band9: 2 pols, 1 SIS/pol, one magnet pol (IMag01, IMag11). Magnet current is optimized to minimize Josephson current with VJ swept +/- 0.2 mV. Output power is measured while sweeping VJ. LO PA (VD) is adjusted to set target SIS current (IJ).
Function Documentation
const std::string & FEConfig::getLogDir ()
Definition at line 14 of file logDir.cpp.
References logDir.
Referenced by getDataPath(), and ColdCartImpl::sisMixerHeatingProcess().
std::ostream& FEConfig::operator<< (std::ostream & out, const CryostatConfig & config) inline
stream output for debugging CryostatConfig
Definition at line 58 of file SubsysConfig.h.
References FEConfig::CryostatConfig::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const ColdCartConfig & config) inline
stream output for debugging ColdCartConfig
Definition at line 71 of file CartConfig.h.
References FEConfig::ColdCartConfig::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const LPRConfig & config) inline
stream output for debugging LPRConfig
Definition at line 87 of file SubsysConfig.h.
References FEConfig::LPRConfig::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const ParamTableRow & row) inline
stream output for debugging ParamTableRow
Definition at line 92 of file LookupTables.h.
References FEConfig::ParamTableRow::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const FrontEndConfig & config) inline
stream output for debugging FrontEndConfig
Definition at line 105 of file FrontEndConfig.h.
References FEConfig::FrontEndConfig::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const WCAConfig & config) inline
stream output for debugging WCAConfig
Definition at line 108 of file CartConfig.h.
References FEConfig::WCAConfig::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const CartAssemblyID & id) inline
Definition at line 153 of file CartConfig.h.
std::ostream& FEConfig::operator<< (std::ostream & out, const ParamTable & table) inline
stream output for debugging ParamTable
Definition at line 176 of file LookupTables.h.
References FEConfig::ParamTable::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const CartAssemblyConfig & config) inline
stream output for debugging CartAssemblyConfig
Definition at line 178 of file CartConfig.h.
References FEConfig::CartAssemblyConfig::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const MixerParams & params) inline
stream output for debugging MixerParams
Definition at line 226 of file LookupTables.h.
References FEConfig::MixerParams::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const MagnetParams & params) inline
stream output for debugging MagnetParams
Definition at line 261 of file LookupTables.h.
References FEConfig::MagnetParams::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const PreampParams & params) inline
stream output for debugging PreampParams
Definition at line 294 of file LookupTables.h.
References FEConfig::PreampParams::streamOut().
std::ostream& FEConfig::operator<< (std::ostream & out, const PowerAmpParams & params) inline
stream output for debugging PowerAmpParams
Definition at line 322 of file LookupTables.h.
References FEConfig::PowerAmpParams::streamOut().
void FEConfig::setLogDir (const std::string newValue)
Definition at line 19 of file logDir.cpp.
Referenced by LVWrapperInit().
std::string FEConfig::TrimStr (const std::string & src, const std::string & c = " \t\r\n") inline
Definition at line 615 of file ConfigProviderIniFile.cpp.
Referenced by FEConfig::ConfigProviderIniFile::parseDouble(), and FEConfig::ConfigProviderIniFile::parseUnsigned().
Variable Documentation
std::string FEConfig::logDir
Definition at line 12 of file logDir.cpp.
Referenced by getDataPath(), getLogDir(), LVWrapperInit(), and ColdCartImpl::sisMixerHeatingProcess().