FrontEndControl2: CartPAData_t Struct Reference
CartPAData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
PA_POL0_DRAIN_VOLTAGE, PA_POL0_DRAIN_CURRENT, PA_POL0_GATE_VOLTAGE, PA_POL1_DRAIN_VOLTAGE,
PA_POL1_DRAIN_CURRENT, PA_POL1_GATE_VOLTAGE, PA_SUPPLY_VOLTAGE_3V, PA_SUPPLY_VOLTAGE_5V
}
Public Member Functions
CartPAData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [32]
Static Public Attributes
static const int offsets [] = { 0, 4, 8, 12, 16, 20, 24, 28 }
Detailed Description
Definition at line 368 of file lv_structs.h.
Member Enumeration Documentation
enum CartPAData_t::Field
Enumerator
PA_POL0_DRAIN_VOLTAGE
PA_POL0_DRAIN_CURRENT
PA_POL0_GATE_VOLTAGE
PA_POL1_DRAIN_VOLTAGE
PA_POL1_DRAIN_CURRENT
PA_POL1_GATE_VOLTAGE
PA_SUPPLY_VOLTAGE_3V
PA_SUPPLY_VOLTAGE_5V
Definition at line 369 of file lv_structs.h.
Constructor & Destructor Documentation
CartPAData_t::CartPAData_t () inline
Definition at line 383 of file lv_structs.h.
References reset().
Member Function Documentation
float CartPAData_t::getFloat (Field field) const inline
Definition at line 389 of file lv_structs.h.
References LVGetFloat().
void CartPAData_t::reset () inline
Definition at line 386 of file lv_structs.h.
Referenced by CartPAData_t().
void CartPAData_t::setFloat (Field field, const float & value) inline
Definition at line 392 of file lv_structs.h.
References LVSetFloat().
void CartPAData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 174 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartPAData_t::data[32]
Definition at line 380 of file lv_structs.h.
const int CartPAData_t::offsets = { 0, 4, 8, 12, 16, 20, 24, 28 } static
Definition at line 381 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp