FrontEndControl2: CartTempData_t Struct Reference
CartTempData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
CARTRIDGE_TEMP0, CARTRIDGE_TEMP1, CARTRIDGE_TEMP2, CARTRIDGE_TEMP3,
CARTRIDGE_TEMP4, CARTRIDGE_TEMP5
}
Public Member Functions
CartTempData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [24]
Static Public Attributes
static const int offsets [] = { 0, 4, 8, 12, 16, 20 }
Detailed Description
Definition at line 406 of file lv_structs.h.
Member Enumeration Documentation
enum CartTempData_t::Field
Enumerator
CARTRIDGE_TEMP0
CARTRIDGE_TEMP1
CARTRIDGE_TEMP2
CARTRIDGE_TEMP3
CARTRIDGE_TEMP4
CARTRIDGE_TEMP5
Definition at line 407 of file lv_structs.h.
Constructor & Destructor Documentation
CartTempData_t::CartTempData_t () inline
Definition at line 419 of file lv_structs.h.
References reset().
Member Function Documentation
float CartTempData_t::getFloat (Field field) const inline
Definition at line 425 of file lv_structs.h.
References LVGetFloat().
void CartTempData_t::reset () inline
Definition at line 422 of file lv_structs.h.
Referenced by CartTempData_t().
void CartTempData_t::setFloat (Field field, const float & value) inline
Definition at line 428 of file lv_structs.h.
References LVSetFloat().
void CartTempData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 199 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartTempData_t::data[24]
Definition at line 416 of file lv_structs.h.
const int CartTempData_t::offsets = { 0, 4, 8, 12, 16, 20 } static
Definition at line 417 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp