FrontEndControl2: LORTMOther_t Struct Reference
LORTMOther_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
LASER_TEC_I_MON1, LASER_TEC_I_MON2, LASER_TEC_I_MON3, LASER_TEC_I_MON4,
LASER_POW_MON1, LASER_POW_MON2, LASER_POW_MON3, LASER_POW_MON4,
PHMIX_BIAS_MON1, PHMIX_BIAS_MON2, PHMIX_BIAS_MON3, PHMIX_BIAS_MON4,
RF_AGC_GAIN_MON, RF_POW_MON_34DB, EXTERN_THERM_MON, INTERN_THERM_MON
}
Public Member Functions
LORTMOther_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [64]
Static Public Attributes
static const int offsets [] = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60 }
Detailed Description
Definition at line 876 of file lv_structs.h.
Member Enumeration Documentation
enum LORTMOther_t::Field
Enumerator
LASER_TEC_I_MON1
LASER_TEC_I_MON2
LASER_TEC_I_MON3
LASER_TEC_I_MON4
LASER_POW_MON1
LASER_POW_MON2
LASER_POW_MON3
LASER_POW_MON4
PHMIX_BIAS_MON1
PHMIX_BIAS_MON2
PHMIX_BIAS_MON3
PHMIX_BIAS_MON4
RF_AGC_GAIN_MON
RF_POW_MON_34DB
EXTERN_THERM_MON
INTERN_THERM_MON
Definition at line 877 of file lv_structs.h.
Constructor & Destructor Documentation
LORTMOther_t::LORTMOther_t () inline
Definition at line 898 of file lv_structs.h.
References reset().
Member Function Documentation
float LORTMOther_t::getFloat (Field field) const inline
Definition at line 904 of file lv_structs.h.
References LVGetFloat().
void LORTMOther_t::reset () inline
Definition at line 901 of file lv_structs.h.
Referenced by LORTMOther_t().
void LORTMOther_t::setFloat (Field field, const float & value) inline
Definition at line 907 of file lv_structs.h.
References LVSetFloat().
void LORTMOther_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 484 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char LORTMOther_t::data[64]
Definition at line 895 of file lv_structs.h.
const int LORTMOther_t::offsets = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60 } static
Definition at line 896 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp