FrontEndControl2: FrontEnd::FESelector_t Struct Reference
FrontEnd::FESelector_t Struct Reference
This structure is populated when a monitor or control command is parsed.
#include <feAddressMeta.h>
Public Member Functions
bool isMonitor () const
FESelector_t ()
unsigned getCartridge () const
void reset ()
bool decode (AmbRelativeAddr RCA)
void streamOut (std::ostream &out) const
stream output for debugging
Static Public Member Functions
static bool match (AmbRelativeAddr RCA, AmbRelativeAddr mask)
test whether set bits of mask are exactly matched in the RCA.
Public Attributes
AmbRelativeAddr base
SubSystem_t subsys
AmbRelativeAddr offset
std::string description
bool isCommand
bool isReadBack
int cartridge
Detailed Description
This structure is populated when a monitor or control command is parsed.
Definition at line 86 of file feAddressMeta.h.
Constructor & Destructor Documentation
FrontEnd::FESelector_t::FESelector_t () inline
Definition at line 96 of file feAddressMeta.h.
References reset().
Member Function Documentation
bool FrontEnd::FESelector_t::decode (AmbRelativeAddr RCA)
Definition at line 12 of file feAddressMeta.cpp.
References FrontEnd::AMBSI_BASE, base, FrontEnd::BITMASK_CARTRIDGE, FrontEnd::BITMASK_CARTRIDGE_BIAS, FrontEnd::BITMASK_CARTRIDGE_LO, FrontEnd::BITMASK_CARTRIDGE_TEMP, FrontEnd::BITMASK_CRYOSTAT, FrontEnd::BITMASK_E_NOT_IMPL, FrontEnd::BITMASK_F_NOT_IMPL, FrontEnd::BITMASK_IFSWITCH, FrontEnd::BITMASK_LPR, FrontEnd::BITMASK_POWERDIST, FrontEnd::BITMASK_POWERDIST_CART, FrontEnd::BITSHIFT_CARTRIDGE, FrontEnd::BITSHIFT_POWERDIST_CART, cartridge, FrontEnd::CONTROL_BASE, isCommand, match(), FrontEnd::MONITOR_BASE, offset, reset(), FrontEnd::SPECIAL_CONTROL, FrontEnd::SPECIAL_MONITOR, subsys, FrontEnd::SUBSYS_AMBSI, FrontEnd::SUBSYS_AMBSI_SN, FrontEnd::SUBSYS_CARTRIDGE_BIAS, FrontEnd::SUBSYS_CARTRIDGE_LO, FrontEnd::SUBSYS_CARTRIDGE_TEMP, FrontEnd::SUBSYS_CRYOSTAT, FrontEnd::SUBSYS_IFSWITCH, FrontEnd::SUBSYS_LPR, FrontEnd::SUBSYS_POWERDIST, FrontEnd::SUBSYS_POWERDIST_CHANNEL, FrontEnd::SUBSYS_SPECIAL_CONTROL, and FrontEnd::SUBSYS_SPECIAL_MONITOR.
Referenced by AmbTransactionLogger::logSingleItem().
unsigned FrontEnd::FESelector_t::getCartridge () const inline
Definition at line 98 of file feAddressMeta.h.
bool FrontEnd::FESelector_t::isMonitor () const inline
Definition at line 92 of file feAddressMeta.h.
References isCommand.
static bool FrontEnd::FESelector_t::match (AmbRelativeAddr RCA, AmbRelativeAddr mask) inline static
test whether set bits of mask are exactly matched in the RCA.
Definition at line 107 of file feAddressMeta.h.
Referenced by decode().
void FrontEnd::FESelector_t::reset ()
Definition at line 5 of file feAddressMeta.cpp.
References base, cartridge, isCommand, isReadBack, offset, subsys, and FrontEnd::SUBSYS_NONE.
Referenced by decode(), and FESelector_t().
void FrontEnd::FESelector_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 125 of file feAddressMeta.cpp.
References cartridge.
Referenced by FrontEnd::operator<<().
Member Data Documentation
AmbRelativeAddr FrontEnd::FESelector_t::base
Definition at line 87 of file feAddressMeta.h.
Referenced by decode(), and reset().
int FrontEnd::FESelector_t::cartridge
Definition at line 94 of file feAddressMeta.h.
Referenced by decode(), reset(), and streamOut().
std::string FrontEnd::FESelector_t::description
Definition at line 90 of file feAddressMeta.h.
bool FrontEnd::FESelector_t::isCommand
Definition at line 91 of file feAddressMeta.h.
Referenced by decode(), isMonitor(), and reset().
bool FrontEnd::FESelector_t::isReadBack
Definition at line 93 of file feAddressMeta.h.
Referenced by reset().
AmbRelativeAddr FrontEnd::FESelector_t::offset
Definition at line 89 of file feAddressMeta.h.
Referenced by decode(), and reset().
SubSystem_t FrontEnd::FESelector_t::subsys
Definition at line 88 of file feAddressMeta.h.
Referenced by decode(), and reset().
The documentation for this struct was generated from the following files:
LOGGER/feAddressMeta.h
LOGGER/feAddressMeta.cpp