FrontEndControl2: CartStateData_t Struct Reference
CartStateData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
CART_ENABLED, CART_OBSERVING, CART_LNA_ENABLED, CART_SIS_ENABLED,
CART_SIS_MAGNET_ENABLED, CART_SIS_HEATER_ENABLED, CART_HEMT_LED_ENABLED, CART_LO_PA_ENABLED,
CART_PHOTOMIXER_ENABLED, CART_ZERO_INTEGRATOR_ENABLED
}
Public Member Functions
CartStateData_t ()
void reset ()
bool getBool (Field field) const
void setBool (Field field, const bool &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [10]
Static Public Attributes
static const int offsets [] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
Detailed Description
Definition at line 108 of file lv_structs.h.
Member Enumeration Documentation
enum CartStateData_t::Field
Enumerator
CART_ENABLED
CART_OBSERVING
CART_LNA_ENABLED
CART_SIS_ENABLED
CART_SIS_MAGNET_ENABLED
CART_SIS_HEATER_ENABLED
CART_HEMT_LED_ENABLED
CART_LO_PA_ENABLED
CART_PHOTOMIXER_ENABLED
CART_ZERO_INTEGRATOR_ENABLED
Definition at line 110 of file lv_structs.h.
Constructor & Destructor Documentation
CartStateData_t::CartStateData_t () inline
Definition at line 127 of file lv_structs.h.
References reset().
Member Function Documentation
bool CartStateData_t::getBool (Field field) const inline
Definition at line 133 of file lv_structs.h.
References LVGetBool().
void CartStateData_t::reset () inline
Definition at line 130 of file lv_structs.h.
Referenced by CartStateData_t().
void CartStateData_t::setBool (Field field, const bool & value) inline
Definition at line 136 of file lv_structs.h.
References LVSetBool().
void CartStateData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 20 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartStateData_t::data[10]
Definition at line 124 of file lv_structs.h.
const int CartStateData_t::offsets = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9} static
Definition at line 125 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp