FrontEndControl2: FEConfig::Configuration::Record Struct Reference
FEConfig::Configuration::Record Struct Reference
A structure for the elements in the top-level Configuration record.
#include <Configuration.h>
Public Member Functions
Record (unsigned keyFacility=0, unsigned configId=0, unsigned keyFrontEnd=0, CartAssemblyID CAId=CartAssemblyID(), const std::string &description=std::string())
void reset (unsigned keyFacility=0, unsigned configId=0)
bool isValid () const
Public Attributes
unsigned keyFacility_m
the provider portion of the foreign keys.
unsigned configId_m
the configuration ID for this record.
unsigned keyFrontEnd_m
a foreign key into the FrontEnds table.
CartAssemblyID CAId_m
identifying information for a CartAssembly.
std::string description_m
the description of the configuration.
Detailed Description
A structure for the elements in the top-level Configuration record.
bundled together for convenient interaction with the ConfigProvider.
Definition at line 78 of file Configuration.h.
Constructor & Destructor Documentation
FEConfig::Configuration::Record::Record (unsigned keyFacility = 0, unsigned configId = 0, unsigned keyFrontEnd = 0, CartAssemblyID CAId = CartAssemblyID(), const std::string & description = std::string()) inline
Definition at line 85 of file Configuration.h.
Member Function Documentation
bool FEConfig::Configuration::Record::isValid () const inline
Definition at line 104 of file Configuration.h.
References FEConfig::CartAssemblyID::isValid().
Referenced by FEConfig::ConfigProviderIniFile::getConfiguration().
void FEConfig::Configuration::Record::reset (unsigned keyFacility = 0, unsigned configId = 0) inline
Definition at line 97 of file Configuration.h.
References FrontEndLVWrapper::configId, and FEConfig::CartAssemblyID::reset().
Referenced by FEConfig::ConfigProviderIniFile::getAllConfigurations(), FEConfig::ConfigProviderIniFile::getConfiguration(), FEConfig::ConfigProviderMySQL::getConfiguration(), and FEConfig::Configuration::reset().
Member Data Documentation
CartAssemblyID FEConfig::Configuration::Record::CAId_m
identifying information for a CartAssembly.
Definition at line 82 of file Configuration.h.
Referenced by FEConfig::ConfigProviderIniFile::getConfiguration(), FrontEndDatabase::getConfigurationRecord(), and FEConfig::Configuration::load().
unsigned FEConfig::Configuration::Record::configId_m
the configuration ID for this record.
Definition at line 80 of file Configuration.h.
Referenced by FrontEndDatabase::getConfigurationRecord().
std::string FEConfig::Configuration::Record::description_m
the description of the configuration.
Definition at line 83 of file Configuration.h.
Referenced by FEConfig::ConfigProviderIniFile::getConfiguration(), FrontEndDatabase::getConfigurationRecord(), FEConfig::Configuration::getDescription(), FEConfig::Configuration::load(), and FEConfig::Configuration::save().
unsigned FEConfig::Configuration::Record::keyFacility_m
the provider portion of the foreign keys.
Definition at line 79 of file Configuration.h.
Referenced by FEConfig::ConfigProviderIniFile::getConfiguration(), and FrontEndDatabase::getConfigurationRecord().
unsigned FEConfig::Configuration::Record::keyFrontEnd_m
a foreign key into the FrontEnds table.
Definition at line 81 of file Configuration.h.
Referenced by FEConfig::ConfigProviderIniFile::getConfiguration(), FrontEndDatabase::getConfigurationRecord(), and FEConfig::Configuration::load().
The documentation for this struct was generated from the following file:
CONFIG/Configuration.h