FrontEndControl2: CartYTOData_t Struct Reference
CartYTOData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field { YTO_COARSE_TUNE, YTO_FREQUENCY }
Public Member Functions
CartYTOData_t ()
void reset ()
short getCoarseTune () const
void setCoarseTune (const short &value)
double getFrequency () const
void setFrequency (const double &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [10]
Static Public Attributes
static const int offsets [] = {0, 2}
Detailed Description
Definition at line 198 of file lv_structs.h.
Member Enumeration Documentation
enum CartYTOData_t::Field
Enumerator
YTO_COARSE_TUNE
YTO_FREQUENCY
Definition at line 200 of file lv_structs.h.
Constructor & Destructor Documentation
CartYTOData_t::CartYTOData_t () inline
Definition at line 207 of file lv_structs.h.
References reset().
Member Function Documentation
short CartYTOData_t::getCoarseTune () const inline
Definition at line 213 of file lv_structs.h.
References LVGetShort(), and YTO_COARSE_TUNE.
double CartYTOData_t::getFrequency () const inline
Definition at line 219 of file lv_structs.h.
References YTO_FREQUENCY.
void CartYTOData_t::reset () inline
Definition at line 210 of file lv_structs.h.
Referenced by CartYTOData_t().
void CartYTOData_t::setCoarseTune (const short & value) inline
Definition at line 216 of file lv_structs.h.
References LVSetShort(), and YTO_COARSE_TUNE.
void CartYTOData_t::setFrequency (const double & value) inline
Definition at line 222 of file lv_structs.h.
References YTO_FREQUENCY.
void CartYTOData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 70 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartYTOData_t::data[10]
Definition at line 204 of file lv_structs.h.
const int CartYTOData_t::offsets = {0, 2} static
Definition at line 205 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp