FrontEndControl2: CompressorData_t Struct Reference
CompressorData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
TEMP1, TEMP2, TEMP3, TEMP4,
RETURN_PRESSURE, SUPPLY_PRESSURE, AUX_TRANSDUCER, TIME_SINCE_POWER_ON,
TIME_SINCE_POWER_OFF, TEMP_ALARM, PRESSURE_ALARM, DRIVE_INDICATOR,
ICCU_STATUS, ICCU_CABLE_ERROR, FETIM_STATUS, FETIM_CABLE_ERROR,
INTERLOCK_OVERRIDE, FAULT_STATUS
}
Public Member Functions
CompressorData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
unsigned long getULong (Field field) const
void setULong (Field field, const unsigned long &value)
bool getBool (Field field) const
void setBool (Field field, const bool &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [45]
Static Public Attributes
static const int offsets [] = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44 }
Detailed Description
Definition at line 981 of file lv_structs.h.
Member Enumeration Documentation
enum CompressorData_t::Field
Enumerator
TEMP1
TEMP2
TEMP3
TEMP4
RETURN_PRESSURE
SUPPLY_PRESSURE
AUX_TRANSDUCER
TIME_SINCE_POWER_ON
TIME_SINCE_POWER_OFF
TEMP_ALARM
PRESSURE_ALARM
DRIVE_INDICATOR
ICCU_STATUS
ICCU_CABLE_ERROR
FETIM_STATUS
FETIM_CABLE_ERROR
INTERLOCK_OVERRIDE
FAULT_STATUS
Definition at line 982 of file lv_structs.h.
Constructor & Destructor Documentation
CompressorData_t::CompressorData_t () inline
Definition at line 1006 of file lv_structs.h.
References reset().
Member Function Documentation
bool CompressorData_t::getBool (Field field) const inline
Definition at line 1024 of file lv_structs.h.
References LVGetBool().
float CompressorData_t::getFloat (Field field) const inline
Definition at line 1012 of file lv_structs.h.
References LVGetFloat().
unsigned long CompressorData_t::getULong (Field field) const inline
Definition at line 1018 of file lv_structs.h.
References LVGetULong().
void CompressorData_t::reset () inline
Definition at line 1009 of file lv_structs.h.
Referenced by CompressorData_t().
void CompressorData_t::setBool (Field field, const bool & value) inline
Definition at line 1027 of file lv_structs.h.
References LVSetBool().
void CompressorData_t::setFloat (Field field, const float & value) inline
Definition at line 1015 of file lv_structs.h.
References LVSetFloat().
void CompressorData_t::setULong (Field field, const unsigned long & value) inline
Definition at line 1021 of file lv_structs.h.
References LVSetULong().
void CompressorData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 561 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CompressorData_t::data[45]
Definition at line 1003 of file lv_structs.h.
const int CompressorData_t::offsets = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44 } static
Definition at line 1004 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp