FrontEndControl2: CartIFPowerData_t Struct Reference
CartIFPowerData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
PHOT0_IF0, PHOT0_IF1, PHOT0_IF2, PHOT0_IF3,
PHOT15_IF0, PHOT15_IF1, PHOT15_IF2, PHOT15_IF3,
PCOLD_IF0, PCOLD_IF1, PCOLD_IF2, PCOLD_IF3,
YFACTOR_IF0, YFACTOR_IF1, YFACTOR_IF2, YFACTOR_IF3
}
Public Member Functions
CartIFPowerData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [64]
Static Public Attributes
static const int offsets [] = {0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60}
Detailed Description
Definition at line 151 of file lv_structs.h.
Member Enumeration Documentation
enum CartIFPowerData_t::Field
Enumerator
PHOT0_IF0
PHOT0_IF1
PHOT0_IF2
PHOT0_IF3
PHOT15_IF0
PHOT15_IF1
PHOT15_IF2
PHOT15_IF3
PCOLD_IF0
PCOLD_IF1
PCOLD_IF2
PCOLD_IF3
YFACTOR_IF0
YFACTOR_IF1
YFACTOR_IF2
YFACTOR_IF3
Definition at line 152 of file lv_structs.h.
Constructor & Destructor Documentation
CartIFPowerData_t::CartIFPowerData_t () inline
Definition at line 175 of file lv_structs.h.
References reset().
Member Function Documentation
float CartIFPowerData_t::getFloat (Field field) const inline
Definition at line 181 of file lv_structs.h.
References LVGetFloat().
void CartIFPowerData_t::reset () inline
Definition at line 178 of file lv_structs.h.
Referenced by CartIFPowerData_t().
void CartIFPowerData_t::setFloat (Field field, const float & value) inline
Definition at line 184 of file lv_structs.h.
References LVSetFloat().
void CartIFPowerData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 47 of file lv_structs.cpp.
Referenced by operator<<().
Member Data Documentation
unsigned char CartIFPowerData_t::data[64]
Definition at line 172 of file lv_structs.h.
const int CartIFPowerData_t::offsets = {0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60} static
Definition at line 173 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp