FrontEndControl2: CartPLLData_t Struct Reference
CartPLLData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
PLL_LOCK, PLL_UNLOCK_DETECT_LATCH, PLL_LOCK_DETECT_VOLTAGE, PLL_CORRECTION_VOLTAGE,
PLL_REF_TOTAL_POWER, PLL_IF_TOTAL_POWER, PLL_LOOP_BANDWIDTH_SELECT, PLL_SIDEBAND_LOCK_POL_SELECT,
PLL_NULL_LOOP_INTEGRATOR, PLL_ASSEMBLY_TEMP, PLL_YTO_HEATER_CURRENT
}
Public Member Functions
CartPLLData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
bool getBool (Field field) const
void setBool (Field field, const bool &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [29]
Static Public Attributes
static const int offsets []
Detailed Description
Definition at line 274 of file lv_structs.h.
Member Enumeration Documentation
enum CartPLLData_t::Field
Enumerator
PLL_LOCK
PLL_UNLOCK_DETECT_LATCH
PLL_LOCK_DETECT_VOLTAGE
PLL_CORRECTION_VOLTAGE
PLL_REF_TOTAL_POWER
PLL_IF_TOTAL_POWER
PLL_LOOP_BANDWIDTH_SELECT
PLL_SIDEBAND_LOCK_POL_SELECT
PLL_NULL_LOOP_INTEGRATOR
PLL_ASSEMBLY_TEMP
PLL_YTO_HEATER_CURRENT
Definition at line 275 of file lv_structs.h.
Constructor & Destructor Documentation
CartPLLData_t::CartPLLData_t () inline
Definition at line 291 of file lv_structs.h.
References reset().
Member Function Documentation
bool CartPLLData_t::getBool (Field field) const inline
Definition at line 303 of file lv_structs.h.
References LVGetBool().
float CartPLLData_t::getFloat (Field field) const inline
Definition at line 297 of file lv_structs.h.
References LVGetFloat().
void CartPLLData_t::reset () inline
Definition at line 294 of file lv_structs.h.
Referenced by CartPLLData_t().
void CartPLLData_t::setBool (Field field, const bool & value) inline
Definition at line 306 of file lv_structs.h.
References LVSetBool().
void CartPLLData_t::setFloat (Field field, const float & value) inline
Definition at line 300 of file lv_structs.h.
References LVSetFloat().
void CartPLLData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 103 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartPLLData_t::data[29]
Definition at line 288 of file lv_structs.h.
const int CartPLLData_t::offsets static
Initial value:
= {
    0,
    1,
    2,
    6,
    10,
    14,
    18,
    19,
    20,
    21,
    25
}
Definition at line 289 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp