FrontEndControl2: LORTMLasers_t Struct Reference
LORTMLasers_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
LASER_STATUS1, LASER_STATUS2, LASER_STATUS3, LASER_STATUS4,
LASER_BIAS_MON1, LASER_BIAS_MON2, LASER_BIAS_MON3, LASER_BIAS_MON4,
LASER_TEMP_MON1, LASER_TEMP_MON2, LASER_TEMP_MON3, LASER_TEMP_MON4,
LASER_SLOW_CORR_MON
}
Public Member Functions
LORTMLasers_t ()
void reset ()
unsigned char getByte (Field field) const
void setByte (Field field, const unsigned char &value)
float getFloat (Field field) const
void setFloat (Field field, const float &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [40]
Static Public Attributes
static const int offsets [] = { 0, 1, 2, 3, 4, 8, 12, 16, 20, 24, 28, 32, 36 }
Detailed Description
Definition at line 828 of file lv_structs.h.
Member Enumeration Documentation
enum LORTMLasers_t::Field
Enumerator
LASER_STATUS1
LASER_STATUS2
LASER_STATUS3
LASER_STATUS4
LASER_BIAS_MON1
LASER_BIAS_MON2
LASER_BIAS_MON3
LASER_BIAS_MON4
LASER_TEMP_MON1
LASER_TEMP_MON2
LASER_TEMP_MON3
LASER_TEMP_MON4
LASER_SLOW_CORR_MON
Definition at line 829 of file lv_structs.h.
Constructor & Destructor Documentation
LORTMLasers_t::LORTMLasers_t () inline
Definition at line 847 of file lv_structs.h.
References reset().
Member Function Documentation
unsigned char LORTMLasers_t::getByte (Field field) const inline
Definition at line 853 of file lv_structs.h.
References LVGetByte().
float LORTMLasers_t::getFloat (Field field) const inline
Definition at line 859 of file lv_structs.h.
References LVGetFloat().
void LORTMLasers_t::reset () inline
Definition at line 850 of file lv_structs.h.
Referenced by LORTMLasers_t().
void LORTMLasers_t::setByte (Field field, const unsigned char & value) inline
Definition at line 856 of file lv_structs.h.
References LVSetByte().
void LORTMLasers_t::setFloat (Field field, const float & value) inline
Definition at line 862 of file lv_structs.h.
References LVSetFloat().
void LORTMLasers_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 453 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char LORTMLasers_t::data[40]
Definition at line 844 of file lv_structs.h.
const int LORTMLasers_t::offsets = { 0, 1, 2, 3, 4, 8, 12, 16, 20, 24, 28, 32, 36 } static
Definition at line 845 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp