FrontEndControl2: CartSISData_t Struct Reference
CartSISData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
SIS_OPEN_LOOP, SIS_VOLTAGE, SIS_CURRENT, SIS_MAGNET_VOLTAGE,
SIS_MAGNET_CURRENT
}
Public Member Functions
CartSISData_t ()
void reset ()
bool getOpenLoop () const
void setOpenLoop (const bool &value)
float getFloat (Field field) const
void setFloat (Field field, const float &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [17]
Static Public Attributes
static const int offsets []
Detailed Description
Definition at line 442 of file lv_structs.h.
Member Enumeration Documentation
enum CartSISData_t::Field
Enumerator
SIS_OPEN_LOOP
SIS_VOLTAGE
SIS_CURRENT
SIS_MAGNET_VOLTAGE
SIS_MAGNET_CURRENT
Definition at line 443 of file lv_structs.h.
Constructor & Destructor Documentation
CartSISData_t::CartSISData_t () inline
Definition at line 453 of file lv_structs.h.
References reset().
Member Function Documentation
float CartSISData_t::getFloat (Field field) const inline
Definition at line 465 of file lv_structs.h.
References LVGetFloat().
bool CartSISData_t::getOpenLoop () const inline
Definition at line 459 of file lv_structs.h.
References LVGetBool(), and SIS_OPEN_LOOP.
void CartSISData_t::reset () inline
Definition at line 456 of file lv_structs.h.
Referenced by CartSISData_t().
void CartSISData_t::setFloat (Field field, const float & value) inline
Definition at line 468 of file lv_structs.h.
References LVSetFloat().
void CartSISData_t::setOpenLoop (const bool & value) inline
Definition at line 462 of file lv_structs.h.
References LVSetBool(), and SIS_OPEN_LOOP.
void CartSISData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 220 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartSISData_t::data[17]
Definition at line 450 of file lv_structs.h.
const int CartSISData_t::offsets static
Initial value:
= {
    0,
    1,
    5,
    9,
    13
}
Definition at line 451 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp