FrontEndControl2: CartLNAData_t Struct Reference
CartLNAData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
LNA_ENABLE, LNA1_DRAIN_VOLTAGE, LNA1_DRAIN_CURRENT, LNA1_GATE_VOLTAGE,
LNA2_DRAIN_VOLTAGE, LNA2_DRAIN_CURRENT, LNA2_GATE_VOLTAGE, LNA3_DRAIN_VOLTAGE,
LNA3_DRAIN_CURRENT, LNA3_GATE_VOLTAGE
}
Public Member Functions
CartLNAData_t ()
void reset ()
bool getEnable () const
void setEnable (const bool &value)
float getFloat (Field field) const
void setFloat (Field field, const float &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [37]
Static Public Attributes
static const int offsets []
Detailed Description
Definition at line 482 of file lv_structs.h.
Member Enumeration Documentation
enum CartLNAData_t::Field
Enumerator
LNA_ENABLE
LNA1_DRAIN_VOLTAGE
LNA1_DRAIN_CURRENT
LNA1_GATE_VOLTAGE
LNA2_DRAIN_VOLTAGE
LNA2_DRAIN_CURRENT
LNA2_GATE_VOLTAGE
LNA3_DRAIN_VOLTAGE
LNA3_DRAIN_CURRENT
LNA3_GATE_VOLTAGE
Definition at line 483 of file lv_structs.h.
Constructor & Destructor Documentation
CartLNAData_t::CartLNAData_t () inline
Definition at line 498 of file lv_structs.h.
References reset().
Member Function Documentation
bool CartLNAData_t::getEnable () const inline
Definition at line 504 of file lv_structs.h.
References LNA_ENABLE, and LVGetBool().
float CartLNAData_t::getFloat (Field field) const inline
Definition at line 510 of file lv_structs.h.
References LVGetFloat().
void CartLNAData_t::reset () inline
Definition at line 501 of file lv_structs.h.
Referenced by CartLNAData_t().
void CartLNAData_t::setEnable (const bool & value) inline
Definition at line 507 of file lv_structs.h.
References LNA_ENABLE, and LVSetBool().
void CartLNAData_t::setFloat (Field field, const float & value) inline
Definition at line 513 of file lv_structs.h.
References LVSetFloat().
void CartLNAData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 245 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartLNAData_t::data[37]
Definition at line 495 of file lv_structs.h.
const int CartLNAData_t::offsets static
Initial value:
= {
    0,
    1,
    5,
    9,
    13,
    17,
    21,
    25,
    29,
    33
}
Definition at line 496 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp