FrontEndControl2: CartAuxData_t Struct Reference
CartAuxData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field { SIS_HEATER_CURRENT, LNA_LED_ENABLE }
Public Member Functions
CartAuxData_t ()
void reset ()
float getHeaterCurrent () const
void setHeaterCurrent (const float &value)
bool getLEDEnable () const
void setLEDEnable (const bool &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [8]
Static Public Attributes
static const int offsets [] = { 0, 4 }
Detailed Description
Definition at line 527 of file lv_structs.h.
Member Enumeration Documentation
enum CartAuxData_t::Field
Enumerator
SIS_HEATER_CURRENT
LNA_LED_ENABLE
Definition at line 528 of file lv_structs.h.
Constructor & Destructor Documentation
CartAuxData_t::CartAuxData_t () inline
Definition at line 535 of file lv_structs.h.
References reset().
Member Function Documentation
float CartAuxData_t::getHeaterCurrent () const inline
Definition at line 541 of file lv_structs.h.
References LVGetFloat(), and SIS_HEATER_CURRENT.
bool CartAuxData_t::getLEDEnable () const inline
Definition at line 547 of file lv_structs.h.
References LNA_LED_ENABLE, and LVGetBool().
void CartAuxData_t::reset () inline
Definition at line 538 of file lv_structs.h.
Referenced by CartAuxData_t().
void CartAuxData_t::setHeaterCurrent (const float & value) inline
Definition at line 544 of file lv_structs.h.
References LVSetFloat(), and SIS_HEATER_CURRENT.
void CartAuxData_t::setLEDEnable (const bool & value) inline
Definition at line 550 of file lv_structs.h.
References LNA_LED_ENABLE, and LVSetBool().
void CartAuxData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 283 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartAuxData_t::data[8]
Definition at line 532 of file lv_structs.h.
const int CartAuxData_t::offsets = { 0, 4 } static
Definition at line 533 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp