FrontEndControl2: IFSwitchData_t Struct Reference
IFSwitchData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
ATTENUATION_POL0SB1, ATTENUATION_POL0SB2, ATTENUATION_POL1SB1, ATTENUATION_POL1SB2,
TEMPERATURE_POL0SB1, TEMPERATURE_POL0SB2, TEMPERATURE_POL1SB1, TEMPERATURE_POL1SB2,
TEMPSERVO_POL0SB1, TEMPSERVO_POL0SB2, TEMPSERVO_POL1SB1, TEMPSERVO_POL1SB2,
OBSERVING_BAND
}
Public Member Functions
IFSwitchData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
unsigned char getByte (Field field) const
void setByte (Field field, const unsigned char &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [25]
Static Public Attributes
static const int offsets [] = { 0, 1, 2, 3, 4, 8, 12, 16, 20, 21, 22, 23, 24 }
Detailed Description
Definition at line 612 of file lv_structs.h.
Member Enumeration Documentation
enum IFSwitchData_t::Field
Enumerator
ATTENUATION_POL0SB1
ATTENUATION_POL0SB2
ATTENUATION_POL1SB1
ATTENUATION_POL1SB2
TEMPERATURE_POL0SB1
TEMPERATURE_POL0SB2
TEMPERATURE_POL1SB1
TEMPERATURE_POL1SB2
TEMPSERVO_POL0SB1
TEMPSERVO_POL0SB2
TEMPSERVO_POL1SB1
TEMPSERVO_POL1SB2
OBSERVING_BAND
Definition at line 614 of file lv_structs.h.
Constructor & Destructor Documentation
IFSwitchData_t::IFSwitchData_t () inline
Definition at line 632 of file lv_structs.h.
References reset().
Member Function Documentation
unsigned char IFSwitchData_t::getByte (Field field) const inline
Definition at line 644 of file lv_structs.h.
References LVGetByte().
float IFSwitchData_t::getFloat (Field field) const inline
Definition at line 638 of file lv_structs.h.
References LVGetFloat().
void IFSwitchData_t::reset () inline
Definition at line 635 of file lv_structs.h.
Referenced by IFSwitchData_t().
void IFSwitchData_t::setByte (Field field, const unsigned char & value) inline
Definition at line 647 of file lv_structs.h.
References LVSetByte().
void IFSwitchData_t::setFloat (Field field, const float & value) inline
Definition at line 641 of file lv_structs.h.
References LVSetFloat().
void IFSwitchData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 320 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char IFSwitchData_t::data[25]
Definition at line 629 of file lv_structs.h.
const int IFSwitchData_t::offsets = { 0, 1, 2, 3, 4, 8, 12, 16, 20, 21, 22, 23, 24 } static
Definition at line 630 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp