FrontEndControl2: LPRData_t Struct Reference
LPRData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
OPTICAL_SWITCH_PORT, OPTICAL_SWITCH_SHUTTER, OPTICAL_SWITCH_STATE, OPTICAL_SWITCH_BUSY,
LPR_TEMPERATURE_0, LPR_TEMPERATURE_1, EDFA_LASER_PUMP_TEMPERATURE, EDFA_LASER_DRIVE_CURRENT,
EDFA_LASER_PHOTODETECT_CURRENT, EDFA_PHOTODETECT_CURRENT, EDFA_PHOTODETECT_POWER, EDFA_MODULATION_INPUT
}
Public Member Functions
LPRData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
unsigned char getByte (Field field) const
void setByte (Field field, const unsigned char &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [36]
Static Public Attributes
static const int offsets [] = { 0, 1, 2, 3, 4, 8, 12, 16, 20, 24, 28, 32 }
Detailed Description
Definition at line 727 of file lv_structs.h.
Member Enumeration Documentation
enum LPRData_t::Field
Enumerator
OPTICAL_SWITCH_PORT
OPTICAL_SWITCH_SHUTTER
OPTICAL_SWITCH_STATE
OPTICAL_SWITCH_BUSY
LPR_TEMPERATURE_0
LPR_TEMPERATURE_1
EDFA_LASER_PUMP_TEMPERATURE
EDFA_LASER_DRIVE_CURRENT
EDFA_LASER_PHOTODETECT_CURRENT
EDFA_PHOTODETECT_CURRENT
EDFA_PHOTODETECT_POWER
EDFA_MODULATION_INPUT
Definition at line 729 of file lv_structs.h.
Constructor & Destructor Documentation
LPRData_t::LPRData_t () inline
Definition at line 746 of file lv_structs.h.
References reset().
Member Function Documentation
unsigned char LPRData_t::getByte (Field field) const inline
Definition at line 758 of file lv_structs.h.
References LVGetByte().
float LPRData_t::getFloat (Field field) const inline
Definition at line 752 of file lv_structs.h.
References LVGetFloat().
void LPRData_t::reset () inline
Definition at line 749 of file lv_structs.h.
Referenced by LPRData_t().
void LPRData_t::setByte (Field field, const unsigned char & value) inline
Definition at line 761 of file lv_structs.h.
References LVSetByte().
void LPRData_t::setFloat (Field field, const float & value) inline
Definition at line 755 of file lv_structs.h.
References LVSetFloat().
void LPRData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 396 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char LPRData_t::data[36]
Definition at line 743 of file lv_structs.h.
const int LPRData_t::offsets = { 0, 1, 2, 3, 4, 8, 12, 16, 20, 24, 28, 32 } static
Definition at line 744 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp