FrontEndControl2: PowerModuleData_t Struct Reference
PowerModuleData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
VOLTAGE_P6V, CURRENT_P6V, VOLTAGE_N6V, CURRENT_N6V,
VOLTAGE_P15V, CURRENT_P15V, VOLTAGE_N15V, CURRENT_N15V,
VOLTAGE_P24V, CURRENT_P24V, VOLTAGE_P8V, CURRENT_P8V,
ENABLE_MODULE
}
Public Member Functions
PowerModuleData_t ()
void reset ()
bool getEnable () const
void setEnable (const bool &value)
float getFloat (Field field) const
void setFloat (Field field, const float &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [49]
Static Public Attributes
static const int offsets [] = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48 }
Detailed Description
Definition at line 564 of file lv_structs.h.
Member Enumeration Documentation
enum PowerModuleData_t::Field
Enumerator
VOLTAGE_P6V
CURRENT_P6V
VOLTAGE_N6V
CURRENT_N6V
VOLTAGE_P15V
CURRENT_P15V
VOLTAGE_N15V
CURRENT_N15V
VOLTAGE_P24V
CURRENT_P24V
VOLTAGE_P8V
CURRENT_P8V
ENABLE_MODULE
Definition at line 565 of file lv_structs.h.
Constructor & Destructor Documentation
PowerModuleData_t::PowerModuleData_t () inline
Definition at line 583 of file lv_structs.h.
References reset().
Member Function Documentation
bool PowerModuleData_t::getEnable () const inline
Definition at line 589 of file lv_structs.h.
References ENABLE_MODULE, and LVGetBool().
float PowerModuleData_t::getFloat (Field field) const inline
Definition at line 595 of file lv_structs.h.
References LVGetFloat().
void PowerModuleData_t::reset () inline
Definition at line 586 of file lv_structs.h.
Referenced by PowerModuleData_t().
void PowerModuleData_t::setEnable (const bool & value) inline
Definition at line 592 of file lv_structs.h.
References ENABLE_MODULE, and LVSetBool().
void PowerModuleData_t::setFloat (Field field, const float & value) inline
Definition at line 598 of file lv_structs.h.
References LVSetFloat().
void PowerModuleData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 299 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char PowerModuleData_t::data[49]
Definition at line 580 of file lv_structs.h.
const int PowerModuleData_t::offsets = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48 } static
Definition at line 581 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp