FrontEndControl2: CartAMCData_t Struct Reference
CartAMCData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
AMC_DRAIN_A_VOLTAGE, AMC_DRAIN_A_CURRENT, AMC_GATE_A_VOLTAGE, AMC_DRAIN_B_VOLTAGE,
AMC_DRAIN_B_CURRENT, AMC_GATE_B_VOLTAGE, AMC_DRAIN_E_VOLTAGE, AMC_DRAIN_E_CURRENT,
AMC_GATE_E_VOLTAGE, AMC_MULTIPLIER_D_CURRENT, AMC_SUPPLY_VOLTAGE_5V, AMC_MULTIPLIER_D_VOLTAGE
}
Public Member Functions
CartAMCData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
unsigned char getByte (Field field) const
void setByte (Field field, const unsigned char &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [45]
Static Public Attributes
static const int offsets [] = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44 }
Detailed Description
Definition at line 320 of file lv_structs.h.
Member Enumeration Documentation
enum CartAMCData_t::Field
Enumerator
AMC_DRAIN_A_VOLTAGE
AMC_DRAIN_A_CURRENT
AMC_GATE_A_VOLTAGE
AMC_DRAIN_B_VOLTAGE
AMC_DRAIN_B_CURRENT
AMC_GATE_B_VOLTAGE
AMC_DRAIN_E_VOLTAGE
AMC_DRAIN_E_CURRENT
AMC_GATE_E_VOLTAGE
AMC_MULTIPLIER_D_CURRENT
AMC_SUPPLY_VOLTAGE_5V
AMC_MULTIPLIER_D_VOLTAGE
Definition at line 321 of file lv_structs.h.
Constructor & Destructor Documentation
CartAMCData_t::CartAMCData_t () inline
Definition at line 339 of file lv_structs.h.
References reset().
Member Function Documentation
unsigned char CartAMCData_t::getByte (Field field) const inline
Definition at line 351 of file lv_structs.h.
References LVGetByte().
float CartAMCData_t::getFloat (Field field) const inline
Definition at line 345 of file lv_structs.h.
References LVGetFloat().
void CartAMCData_t::reset () inline
Definition at line 342 of file lv_structs.h.
Referenced by CartAMCData_t().
void CartAMCData_t::setByte (Field field, const unsigned char & value) inline
Definition at line 354 of file lv_structs.h.
References LVSetByte().
void CartAMCData_t::setFloat (Field field, const float & value) inline
Definition at line 348 of file lv_structs.h.
References LVSetFloat().
void CartAMCData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 143 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartAMCData_t::data[45]
Definition at line 336 of file lv_structs.h.
const int CartAMCData_t::offsets = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44 } static
Definition at line 337 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp