FrontEndControl2: FETIMData_t Struct Reference
FETIMData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
INTERNAL_TEMP1, INTERNAL_TEMP2, INTERNAL_TEMP3, INTERNAL_TEMP4,
INTERNAL_TEMP5, EXTERNAL_TEMP1, EXTERNAL_TEMP2, AIRFLOW1,
AIRFLOW2, HE2_PRESSURE, GLITCH_VALUE, INTERNAL_TEMP_OOR,
EXTERNAL_TEMP1_OOR, EXTERNAL_TEMP2_OOR, AIRFLOW_OOR, HE2_PRESSURE_OOR,
SENSOR_SINGLE_FAIL, SENSOR_MULTI_FAIL, GLITCH_COUNTER_TRIG, DELAY_SHUTDOWN_TRIG,
FINAL_SHUTDOWN_TRIG, COMP_STATUS, COMP_INTERLOCK_STATUS, COMP_CABLE_STATUS
}
Public Member Functions
FETIMData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
bool getBool (Field field) const
void setBool (Field field, const bool &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [57]
Static Public Attributes
static const int offsets [] = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56 }
Detailed Description
Definition at line 921 of file lv_structs.h.
Member Enumeration Documentation
enum FETIMData_t::Field
Enumerator
INTERNAL_TEMP1
INTERNAL_TEMP2
INTERNAL_TEMP3
INTERNAL_TEMP4
INTERNAL_TEMP5
EXTERNAL_TEMP1
EXTERNAL_TEMP2
AIRFLOW1
AIRFLOW2
HE2_PRESSURE
GLITCH_VALUE
INTERNAL_TEMP_OOR
EXTERNAL_TEMP1_OOR
EXTERNAL_TEMP2_OOR
AIRFLOW_OOR
HE2_PRESSURE_OOR
SENSOR_SINGLE_FAIL
SENSOR_MULTI_FAIL
GLITCH_COUNTER_TRIG
DELAY_SHUTDOWN_TRIG
FINAL_SHUTDOWN_TRIG
COMP_STATUS
COMP_INTERLOCK_STATUS
COMP_CABLE_STATUS
Definition at line 922 of file lv_structs.h.
Constructor & Destructor Documentation
FETIMData_t::FETIMData_t () inline
Definition at line 951 of file lv_structs.h.
References reset().
Member Function Documentation
bool FETIMData_t::getBool (Field field) const inline
Definition at line 963 of file lv_structs.h.
References LVGetBool().
float FETIMData_t::getFloat (Field field) const inline
Definition at line 957 of file lv_structs.h.
References LVGetFloat().
void FETIMData_t::reset () inline
Definition at line 954 of file lv_structs.h.
Referenced by FETIMData_t().
void FETIMData_t::setBool (Field field, const bool & value) inline
Definition at line 966 of file lv_structs.h.
References LVSetBool().
void FETIMData_t::setFloat (Field field, const float & value) inline
Definition at line 960 of file lv_structs.h.
References LVSetFloat().
void FETIMData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 518 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char FETIMData_t::data[57]
Definition at line 948 of file lv_structs.h.
const int FETIMData_t::offsets = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56 } static
Definition at line 949 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp