FrontEndControl2: LORTMStatus_t Struct Reference
LORTMStatus_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
SYSTEM_STATE, SYSTEM_WARNING, SYSTEM_ERROR, OPERATION_PENDING,
INTERLOCK_STATUS, SYSTEM_WARNING_CODE, SYSTEM_ERROR_CODE, PHASELOCK_LOCKED,
PHASELOCK_TUNING_READY, PHASELOCK_RF_INPUT_READY, SELECTED_LASER, SELECTED_BAND
}
Public Member Functions
LORTMStatus_t ()
void reset ()
unsigned char getByte (Field field) const
void setByte (Field field, const unsigned char &value)
bool getBool (Field field) const
void setBool (Field field, const bool &value)
short getShort (Field field) const
void setShort (Field field, const short &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [4]
Static Public Attributes
static const int offsets [] = { 0, 1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13 }
Detailed Description
Definition at line 775 of file lv_structs.h.
Member Enumeration Documentation
enum LORTMStatus_t::Field
Enumerator
SYSTEM_STATE
SYSTEM_WARNING
SYSTEM_ERROR
OPERATION_PENDING
INTERLOCK_STATUS
SYSTEM_WARNING_CODE
SYSTEM_ERROR_CODE
PHASELOCK_LOCKED
PHASELOCK_TUNING_READY
PHASELOCK_RF_INPUT_READY
SELECTED_LASER
SELECTED_BAND
Definition at line 776 of file lv_structs.h.
Constructor & Destructor Documentation
LORTMStatus_t::LORTMStatus_t () inline
Definition at line 793 of file lv_structs.h.
References reset().
Member Function Documentation
bool LORTMStatus_t::getBool (Field field) const inline
Definition at line 805 of file lv_structs.h.
References LVGetBool().
unsigned char LORTMStatus_t::getByte (Field field) const inline
Definition at line 799 of file lv_structs.h.
References LVGetByte().
short LORTMStatus_t::getShort (Field field) const inline
Definition at line 811 of file lv_structs.h.
References LVGetShort().
void LORTMStatus_t::reset () inline
Definition at line 796 of file lv_structs.h.
Referenced by LORTMStatus_t().
void LORTMStatus_t::setBool (Field field, const bool & value) inline
Definition at line 808 of file lv_structs.h.
References LVSetBool().
void LORTMStatus_t::setByte (Field field, const unsigned char & value) inline
Definition at line 802 of file lv_structs.h.
References LVSetByte().
void LORTMStatus_t::setShort (Field field, const short & value) inline
Definition at line 814 of file lv_structs.h.
References LVSetShort().
void LORTMStatus_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 424 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char LORTMStatus_t::data[4]
Definition at line 790 of file lv_structs.h.
const int LORTMStatus_t::offsets = { 0, 1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13 } static
Definition at line 791 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp