FrontEndControl2: CryostatData_t Struct Reference
CryostatData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field {
CRYOSTAT_TEMP_0, CRYOSTAT_TEMP_1, CRYOSTAT_TEMP_2, CRYOSTAT_TEMP_3,
CRYOSTAT_TEMP_4, CRYOSTAT_TEMP_5, CRYOSTAT_TEMP_6, CRYOSTAT_TEMP_7,
CRYOSTAT_TEMP_8, CRYOSTAT_TEMP_9, CRYOSTAT_TEMP_10, CRYOSTAT_TEMP_11,
CRYOSTAT_TEMP_12, SUPPLY_CURRENT_230V, VACUUM_CRYOSTAT_PRES, VACUUM_PORT_PRES,
BACKING_PUMP_ENABLE, TURBO_PUMP_ENABLE, TURBO_PUMP_STATE, TURBO_PUMP_SPEED,
GATE_VALVE_STATE, SOLENOID_VALVE_STATE, VACUUM_GAUGE_ENABLE, VACUUM_GAUGE_STATE
}
Public Member Functions
CryostatData_t ()
void reset ()
float getFloat (Field field) const
void setFloat (Field field, const float &value)
unsigned char getByte (Field field) const
void setByte (Field field, const unsigned char &value)
bool getBool (Field field) const
void setBool (Field field, const bool &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [72]
Static Public Attributes
static const int offsets []
Detailed Description
Definition at line 661 of file lv_structs.h.
Member Enumeration Documentation
enum CryostatData_t::Field
Enumerator
CRYOSTAT_TEMP_0
CRYOSTAT_TEMP_1
CRYOSTAT_TEMP_2
CRYOSTAT_TEMP_3
CRYOSTAT_TEMP_4
CRYOSTAT_TEMP_5
CRYOSTAT_TEMP_6
CRYOSTAT_TEMP_7
CRYOSTAT_TEMP_8
CRYOSTAT_TEMP_9
CRYOSTAT_TEMP_10
CRYOSTAT_TEMP_11
CRYOSTAT_TEMP_12
SUPPLY_CURRENT_230V
VACUUM_CRYOSTAT_PRES
VACUUM_PORT_PRES
BACKING_PUMP_ENABLE
TURBO_PUMP_ENABLE
TURBO_PUMP_STATE
TURBO_PUMP_SPEED
GATE_VALVE_STATE
SOLENOID_VALVE_STATE
VACUUM_GAUGE_ENABLE
VACUUM_GAUGE_STATE
Definition at line 663 of file lv_structs.h.
Constructor & Destructor Documentation
CryostatData_t::CryostatData_t () inline
Definition at line 692 of file lv_structs.h.
References reset().
Member Function Documentation
bool CryostatData_t::getBool (Field field) const inline
Definition at line 710 of file lv_structs.h.
References LVGetBool().
unsigned char CryostatData_t::getByte (Field field) const inline
Definition at line 704 of file lv_structs.h.
References LVGetByte().
float CryostatData_t::getFloat (Field field) const inline
Definition at line 698 of file lv_structs.h.
References LVGetFloat().
void CryostatData_t::reset () inline
Definition at line 695 of file lv_structs.h.
Referenced by CryostatData_t().
void CryostatData_t::setBool (Field field, const bool & value) inline
Definition at line 713 of file lv_structs.h.
References LVSetBool().
void CryostatData_t::setByte (Field field, const unsigned char & value) inline
Definition at line 707 of file lv_structs.h.
References LVSetByte().
void CryostatData_t::setFloat (Field field, const float & value) inline
Definition at line 701 of file lv_structs.h.
References LVSetFloat().
void CryostatData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 349 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CryostatData_t::data[72]
Definition at line 689 of file lv_structs.h.
const int CryostatData_t::offsets static
Initial value:
= { 0, 4, 8, 12, 16, 20, 24, 28, 32,
                                        36, 40, 44, 48, 52, 56, 60, 64,
                                        65, 66, 67, 68, 69, 70, 71 }
Definition at line 690 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp