FrontEndControl2: CartPhotomixerData_t Struct Reference
CartPhotomixerData_t Struct Reference
#include <lv_structs.h>
Public Types
enum Field { PHOTOMIXER_ENABLE, PHOTOMIXER_VOLTAGE, PHOTOMIXER_CURRENT }
Public Member Functions
CartPhotomixerData_t ()
void reset ()
bool getEnable () const
void setEnable (const bool &value)
float getFloat (Field field) const
void setFloat (Field field, const float &value)
void streamOut (std::ostream &out) const
stream output for debugging
Public Attributes
unsigned char data [9]
Static Public Attributes
static const int offsets [] = {0, 1, 5}
Detailed Description
Definition at line 236 of file lv_structs.h.
Member Enumeration Documentation
enum CartPhotomixerData_t::Field
Enumerator
PHOTOMIXER_ENABLE
PHOTOMIXER_VOLTAGE
PHOTOMIXER_CURRENT
Definition at line 237 of file lv_structs.h.
Constructor & Destructor Documentation
CartPhotomixerData_t::CartPhotomixerData_t () inline
Definition at line 245 of file lv_structs.h.
References reset().
Member Function Documentation
bool CartPhotomixerData_t::getEnable () const inline
Definition at line 251 of file lv_structs.h.
References LVGetBool(), and PHOTOMIXER_ENABLE.
float CartPhotomixerData_t::getFloat (Field field) const inline
Definition at line 257 of file lv_structs.h.
References LVGetFloat().
void CartPhotomixerData_t::reset () inline
Definition at line 248 of file lv_structs.h.
Referenced by CartPhotomixerData_t().
void CartPhotomixerData_t::setEnable (const bool & value) inline
Definition at line 254 of file lv_structs.h.
References LVSetBool(), and PHOTOMIXER_ENABLE.
void CartPhotomixerData_t::setFloat (Field field, const float & value) inline
Definition at line 260 of file lv_structs.h.
References LVSetFloat().
void CartPhotomixerData_t::streamOut (std::ostream & out) const
stream output for debugging
Definition at line 86 of file lv_structs.cpp.
References canDataAsText().
Referenced by operator<<().
Member Data Documentation
unsigned char CartPhotomixerData_t::data[9]
Definition at line 242 of file lv_structs.h.
const int CartPhotomixerData_t::offsets = {0, 1, 5} static
Definition at line 243 of file lv_structs.h.
The documentation for this struct was generated from the following files:
DLL/lv_structs.h
DLL/lv_structs.cpp