FrontEndControl2: TESTS/t_lv_wrapper_sigSrc.cpp File Reference
t_lv_wrapper_sigSrc.cpp File Reference
#include "../DLL/lv_wrapper_sigSrc.h"
#include "../DLL/lv_wrapper_FE.h"
#include "../DLL/lv_structs.h"
#include <stdio.h>
#include <windows.h>
#include <math.h>
Functions
int main (int, char *[])
Function Documentation
int main (int , char * [])
Definition at line 8 of file t_lv_wrapper_sigSrc.cpp.
References cartGetMonitorAMC(), cartGetMonitorPA(), cartGetMonitorPhotomixer(), cartGetMonitorPLL(), cartGetMonitorYTO(), cartSetLOFrequency(), FESetCartridgeOff(), FESetCartridgeOn(), sigSrcControlInit(), sigSrcControlShutdown(), sigSrcGetAMBSIInfo(), sigSrcGetAMBSITemperature(), sigSrcGetFirmwareInfo(), sigSrcGetNextConfiguration(), and sigSrcLoadConfiguration().